### ISSUE TITLE
Publish throws exception Caused by: java.io.IOException: No available connection to address 

### ISSUE THREAD

**Issue by kdohz** [hazelcast/hazelcast#14065] opened 2018-11-05 23:15 UTC
Report issue: 
========
HZ client fails to publish message in topic container when the connection between the HZ client and the cluster is disconnected. 

Scenario details: 
==========
A HZ cluster has 2 members: 41 and 43. HZ client running on server-A is connected to the HZ cluster successfully and the client log indicates that 43 is the owner member. The connectivity between the client and the cluster is dropped. As a result, the client re-establishes the connection with the cluster successfully and the owner member is now 41. The members in the cluster are still communicating with each other. Hence the cluster still presenting two members to the client when it re-connects to the cluster. 
An application running on server-A performs it jobs and publish a message to the reliable topic container. It throws exception on executing the client.getReliableTopic(topicName).publish(message).
The exception is "Caused by: java.io.IOException: No available connection to address [x.x.x.43]:5701".

Observation:
=========
The client knew it disconnects from 43, switches and connects to member 41 successfully as said above but why does the client still throw exception on unavailable connection to member 43???
I am just thinking that the client still act on 43 because it is told by the cluster that 41 and 43 are available when it reconnects to the cluster. That is ok but it should also knows that it switches away from 43 earlier. It is observed that instead of dropping the connectivity between server-A and member 43, we take 43 off the network. i.e the cluster shows 41 as member only then publish is successfu.
Down below is the exception thrown on the publish.
Our log also shows that following the publish exception, the context.commitTransaction() also fails with "Transaction is timed-out" reason.

```
        at com.broadsoft.profileBuilder.util.documents.SubscriberDocumentUtility.broadcastPublishMessage(DocumentUtility.java:884)
Caused by: java.io.IOException: No available connection to address [x.x.x.43]:5701
        at com.hazelcast.client.spi.impl.SmartClientInvocationService.getOrTriggerConnect(SmartClientInvocationService.java:75)
        at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnPartitionOwner(SmartClientInvocationService.java:48)
        at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:163)
        at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:194)
        at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:179)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by sancar** [comment] 2018-11-06 07:06
It should not be possible for our users to get java.io.IOException. This exception should have been retried on new port automatically. @kdohz Can you share the hazelcast version ? May be this is an old bug.

**Comment by kdohz** [comment] 2018-11-06 15:43
The HZ version under test is 3.11. However we also see this exact issue with version 3.8. 

Some clarification I want to add, hopefully it gives some more details for analyzing the issue:
1) Client configuration: we are not using auto-discovery. The client is manually configured with nodes 41 and 43 (clientConfig.getNetworkConfig().setAddresses(clusterNodes);

2) "The connectivity between the client and the cluster is dropped". This statement means  "that the connectivity between the client and the current owner member (43) is dropped (not the connectivity to the entire cluster) while both remain active.

3) How do I drop the connectivity? At server-A where the client is running, I drop the connectivity to member 43 by using iptables like this (The x.x.x.43 is the IP address of member 43). Member 43 is still connected with the cluster.
iptables -I INPUT -s x.x.x.43 -j DROP
iptables -I OUTPUT -s x.x.x.43 -j DROP

4) When the client switch away, it establishes the connectivity to the other member (41) while the connectivity with member (43) is still down. At this point, if the client executes the publish, it throws the exception Caused by: java.io.IOException: No available connection to address [x.x.x.43]:5701. Subsequently, the client finishes the transaction by executing commitTransaction() and that throws exception with reason "Transaction is timed-out"

This issue is reproducible.

**Comment by kdohz** [comment] 2018-11-16 23:39
Hello Sancar:

Not sure where to put the severity of this issue. This is a Major issue for our network deployment and we would like to know if you need more information to diagnose this problem and we would like to know if the fix for this issue would be in 3.11.1

Thanks,
Kinh

**Comment by sancar** [comment] 2018-11-19 08:33
Hi, sorry I missed your earlier message. I've rechecked and could not find a path that we throw `java.io.IOException` to user. I will try to reproduce the issue . 

About `Transaction is timed-out` , this is more likely to happen. Default transaction timeout is 2 minutes and can be set when creating transaction context on `TransactionOptions`
TransactionContext newTransactionContext(TransactionOptions options);

**Comment by sancar** [comment] 2018-11-19 10:05
@kdohz 

I have tried Iptables but could not reproduce the issue. First of all, I see `heartbeat timeout` logs. It seems that Iptable does not close the connection but only drop the packages. 
My publish method fails with following log which is expected:
```
com.hazelcast.spi.exception.TargetDisconnectedException: Heartbeat timed out
	at com.hazelcast.client.spi.impl.AbstractClientInvocationService$CleanResourcesTask.notifyException(AbstractClientInvocationService.java:225)
	at com.hazelcast.client.spi.impl.AbstractClientInvocationService$CleanResourcesTask.run(AbstractClientInvocationService.java:220)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:190)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:139)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:130)
	at com.hazelcast.client.proxy.ClientReliableTopicProxy.addWithBackoff(ClientReliableTopicProxy.java:130)
	at com.hazelcast.client.proxy.ClientReliableTopicProxy.publish(ClientReliableTopicProxy.java:105)
	at test.Client$1.run(Client.java:42)
```

Further questions to understand the scenario more, 
Do you have any non-default configuration on the member or on the client ? Especially related to heartbeat time-out. 
Is the client smartRouting disabled ?

Can you share logs of clients from startup to time that IOException is logged ?

**Comment by kdohz** [comment] 2018-11-20 23:59
Hi @sancar 

Please find the attach log of the client server that raise exception during publish to RingBuffer said above. When you go thru the log, search for "Sancar" tag that has my comments in there.

We don't have fancy client config. Here is what we did
      clientConfig = new ClientConfig();
      clientConfig.setLicenseKey(cluster.getLicenseKey());
      
      clientConfig.getNetworkConfig().setAddresses(cluster.getNodes());

      /* ********************
       * Configure SSL
       * ********************/
      SSLConfig sslConfig = new SSLConfig();
      sslConfig.setEnabled(cluster.isSecure());
      sslConfig.setFactoryImplementation(new HazelcastSSLContextFactory());
      clientConfig.getNetworkConfig().setSSLConfig(sslConfig);
     
      clientConfig.setGroupConfig(new GroupConfig(cluster.getClusterName(), Base64.decodeToString(cluster.getPasswd())));    
      
      // Add lifecycle listener.
      clientConfig.addListenerConfig(new ListenerConfig().setImplementation(new LifecycleListenerImpl()));
      
      // Client connect/re-connect strategy
      ClientConnectionStrategyConfig connectionStrategy = clientConfig.getConnectionStrategyConfig();
      ConnectionRetryConfig connectionRetry = connectionStrategy.getConnectionRetryConfig();
      
      connectionStrategy.setAsyncStart(true); // default is false
      connectionStrategy.setReconnectMode(ClientConnectionStrategyConfig.ReconnectMode.ASYNC); // default is OFF
      connectionRetry.setInitialBackoffMillis(1000);
      connectionRetry.setMaxBackoffMillis(1000); // default is 30000
      connectionRetry.setMultiplier(2); // default is 2
      connectionRetry.setFailOnMaxBackoff(false); // default is false. 
      connectionRetry.setJitter(0.2); // default is 0.2
      connectionRetry.setEnabled(true); // default is false

Here is the config on the member in xml format. 



<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.8.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.hazelcast.com/schema/config">
  <group>
    <name>as</name>
    <password>${group.password}</password>
  </group>
  <management-center enabled="true" update-interval="3">http://localhost/mancenter</management-center>
  <network>
    <port auto-increment="false" port-count="1">5701</port>
    <outbound-ports>
      <ports>0</ports>
    </outbound-ports>
    <join>
      <multicast enabled="false"/>
      <tcp-ip enabled="true" connection-timeout-seconds="5">
        <member-list>
          <member>10.94.169.41</member>
        </member-list>
      </tcp-ip>
    </join>
    <interfaces enabled="true">
      <interface>10.94.169.43</interface>
    </interfaces>
    <ssl enabled="true">
      <factory-class-name>com.broadsoft.bwapps.hazelcast.HazelcastSSLContextFactory</factory-class-name>
      <properties>
        <property name="alias">as</property>
      </properties>
    </ssl>
  </network>
  <executor-service name="default">
    <pool-size>16</pool-size>
    <queue-capacity>0</queue-capacity>
  </executor-service>
  <queue name="default">
    <max-size>0</max-size>
    <backup-count>0</backup-count>
    <async-backup-count>1</async-backup-count>
    <empty-queue-ttl>-1</empty-queue-ttl>
  </queue>
  <map name="default">
    <in-memory-format>BINARY</in-memory-format>
    <backup-count>0</backup-count>
    <async-backup-count>1</async-backup-count>
    <time-to-live-seconds>0</time-to-live-seconds>
    <max-idle-seconds>0</max-idle-seconds>
    <eviction-policy>NONE</eviction-policy>
    <max-size policy="PER_NODE">0</max-size>
    <eviction-percentage>25</eviction-percentage>
    <min-eviction-check-millis>100</min-eviction-check-millis>
    <merge-policy>com.hazelcast.map.merge.PutIfAbsentMapMergePolicy</merge-policy>
    <cache-deserialized-values>INDEX-ONLY</cache-deserialized-values>
  </map>
  <multimap name="default">
    <async-backup-count>1</async-backup-count>
    <value-collection-type>SET</value-collection-type>
  </multimap>
  <list name="default">
    <async-backup-count>1</async-backup-count>
  </list>
  <set name="default">
    <async-backup-count>1</async-backup-count>
  </set>
  <jobtracker name="default">
    <max-thread-size>0</max-thread-size>
    <queue-size>0</queue-size>
    <retry-count>0</retry-count>
    <chunk-size>1000</chunk-size>
    <communicate-stats>true</communicate-stats>
    <topology-changed-strategy>CANCEL_RUNNING_OPERATION</topology-changed-strategy>
  </jobtracker>
  <semaphore name="default">
    <initial-permits>0</initial-permits>
    <backup-count>0</backup-count>
    <async-backup-count>1</async-backup-count>
  </semaphore>
  <reliable-topic name="default">
    <read-batch-size>10</read-batch-size>
    <topic-overload-policy>BLOCK</topic-overload-policy>
    <statistics-enabled>true</statistics-enabled>
  </reliable-topic>
  <ringbuffer name="default">
    <capacity>10000</capacity>
    <backup-count>0</backup-count>
    <async-backup-count>1</async-backup-count>
    <time-to-live-seconds>30</time-to-live-seconds>
    <in-memory-format>BINARY</in-memory-format>
  </ringbuffer>
  <serialization>
    <portable-version>0</portable-version>
  </serialization>
  <services enable-defaults="true"/>
  <lite-member enabled="false"/>
  <queue name="profileManagement*">
    <max-size>0</max-size>
    <backup-count>0</backup-count>
    <async-backup-count>1</async-backup-count>
    <empty-queue-ttl>-1</empty-queue-ttl>
  </queue>
  <reliable-topic name="profileManagement*">
    <read-batch-size>10</read-batch-size>
    <topic-overload-policy>DISCARD_OLDEST</topic-overload-policy>
    <statistics-enabled>true</statistics-enabled>
  </reliable-topic>
  <ringbuffer name="profileManagement*">
    <capacity>10000</capacity>
    <backup-count>0</backup-count>
    <async-backup-count>1</async-backup-count>
    <time-to-live-seconds>0</time-to-live-seconds>
    <in-memory-format>BINARY</in-memory-format>
  </ringbuffer>
  <map name="callProcessing*">
    <in-memory-format>BINARY</in-memory-format>
    <backup-count>0</backup-count>
    <async-backup-count>1</async-backup-count>
    <time-to-live-seconds>0</time-to-live-seconds>
    <max-idle-seconds>0</max-idle-seconds>
    <eviction-policy>NONE</eviction-policy>
    <max-size policy="PER_NODE">0</max-size>
    <eviction-percentage>25</eviction-percentage>
    <min-eviction-check-millis>100</min-eviction-check-millis>
    <merge-policy>com.hazelcast.map.merge.PutIfAbsentMapMergePolicy</merge-policy>
    <cache-deserialized-values>INDEX-ONLY</cache-deserialized-values>
    <wan-replication-ref name="broadworks-batch">
      <merge-policy>com.hazelcast.map.merge.PassThroughMergePolicy</merge-policy>
      <republishing-enabled>false</republishing-enabled>
    </wan-replication-ref>
  </map>
</hazelcast>
[Sancar_PBLog_iptablesDrop41.txt](https://github.com/hazelcast/hazelcast/files/2602041/Sancar_PBLog_iptablesDrop41.txt)

I drag the log file in this window. If you don't receive it please let me know.
One request I would like to make: Can you make an API that the client can get the owner member IP?
For example hazelcastInstance.getConnectedOwnerMember() return the IP address in String. I would like to use this API for logging purposes.
Regards,

**Comment by kdohz** [comment] 2018-11-21 00:03
The config on the member is attached.


[hazelcast.txt](https://github.com/hazelcast/hazelcast/files/2602049/hazelcast.txt)

**Comment by kdohz** [comment] 2018-11-21 00:04
Attach the log again just in case:

[Sancar_PBLog_iptablesDrop41.txt](https://github.com/hazelcast/hazelcast/files/2602053/Sancar_PBLog_iptablesDrop41.txt)

**Comment by sancar** [comment] 2018-11-21 09:50
> One request I would like to make: Can you make an API that the client can get the owner member IP?
We do not want to expose owner member. It is part of an internal logic and can change(may be removed completely).

Ok, after seeing the full logs, I see that `publish` throws OperationTimeoutException not IOException. 
I was thinking that you get IOException immediately. `OperationTimeoutException` is thrown after all retries are exhausted. `"hazelcast.client.invocation.timeout.seconds", 120, SECONDS ` 
So, this is expected. 

In short, your test setup is not supported.
Reasoning is as follows, 
Client can not decide which members are alive or not. Client has to follow what master member says, as all other hazelcast instances also do. Master member publishes member-list and partition table. 
As long as the `disconnected`(from client) member is in member-list, client will try to open a connection to that `disconnected` member . If it can't within configured time, it will fail with `timeout`. 

When SmartRouting is enabled, the client must have connection to all members. 
It disconnects and connects back to another member to be able to listen up-to-date member-list. That does not mean connections will be redirected from the new connection. 
All other operations must go through the connection according to partition table in smartRouting. 

If you disable smartRouting, then we use only one connection. This time client will switch to a healthy connection in case of a heartbeat problem. Note that this configuration has performance penalty. Because client will no longer use the shortest path to data, and all operations will go through single member.

**Comment by kdohz** [comment] 2018-11-21 19:46
I am still checking with our engineering team regarding the configuration said in this issue.
I believe the situation described in this ticket is legitimate configuration.
The connection path from the client to the members may not the same. In such case if a connectivity path is disrupted then we have this problem. 

My understanding is  that the client view of the members are from the cluster perspective and via the healthy connection between the client and a selected owner member. The publish and commit transaction should continue to operate via that healthy connection with the new owner member. Why does the client still care about the disconnected connection with one of the member? And that is ok to raise OperationTimeoutException but it shall not fail the publish as well as commitTransaction because those two operations are still operating on the healthy connection with new owner member of the cluster.

**Comment by sancar** [comment] 2018-11-22 09:12
Transaction failure is not related to disconnection in your case. It is just timeout. You called the commit too late after starting the transaction context. It is configurable as I said before. 

The connection you see as owner are not related to user operations. It is just for listening member-list.
`publish` or `transaction` should not follow the owner. 
`transaction` always continues from the connection it is started.
`publish` always follows the partition owner of the ringbuffer.

If the `publish` was first made on the disconnected one, you will gonna get TargetDisconnectedException immediately. 
Since you get OperationTimeout, it shows that when `publish` is done target was already disconnected. 

Unhealthy connections can happen but we have to assume they are temporary. You can configure how much you want to tolerate by configuring `"hazelcast.client.invocation.timeout.seconds"`. Redirecting these invocations on random healthy connections are not feasible and cause lots of uncertainties in the logic.
Again this is the same for the members. If you have a connection problem only between two members (lets assume neither of them are master node), you will get OperationTimeoutException. The invocations will not be redirected from another healthy connection.

**Comment by sancar** [comment] 2018-11-23 07:37
Closing the issue since reported incident is identified as expected behaviour.

**Closed by sancar** 2018-11-23 07:37 UTC
Labels: Source: Community, Team: Client
