### ISSUE TITLE
Too much cpu used when Hazelcast is idle V 3.6.2

### ISSUE THREAD

**Issue by NiranjanBS** [hazelcast/hazelcast#7943] opened 2016-04-12 13:40 UTC
As requested by @noctarius creating new ticket.
Am using 3.6.2 new release still taking high CUP usage.
Verified in java 1.7.0_75 and 1.8.0_77.
Tomcat 7.0.68 (java 1.7),Tomcat 8.0.30 (java 1.8).
OS Windows 7.
Use case - We are using apache shiro as security framework and hazelcast is beeing used to store user session in hazelcast map. We are observing high cpu when no user has logged in for around 3 hours.

[hazelcast.txt](https://github.com/hazelcast/hazelcast/files/215087/hazelcast.txt)

![untitled1](https://cloud.githubusercontent.com/assets/9413835/14461697/4d409130-00e1-11e6-8248-55c51acfedb3.png)
![untitled](https://cloud.githubusercontent.com/assets/9413835/14461696/4d3ff23e-00e1-11e6-88fd-e79d46ff4ef5.png)

**Comment by noctarius** [comment] 2016-04-12 13:46
What type of serialization do you use? Are there any complex objects involved? I guess you utilize Hazelcast Session Replication or just Shiro?

**Comment by NiranjanBS** [comment] 2016-04-12 13:53
I am using java serialization, its not complex object its a simple object having few fields about user details.
Ya we have server running as standalone application and our application is interacting with hazelcast through hazelcast client.

**Comment by noctarius** [comment] 2016-04-12 13:55
Any chance to share some testcode that reproduces the issue? If you can't share it privately you could also send it via mail.

**Comment by NiranjanBS** [comment] 2016-04-12 14:10
Ok I will send through mail.

**Comment by NiranjanBS** [comment] 2016-04-12 15:21
Hi @noctarius I have sent mail to you please verify and let me know if you need any more help.

**Comment by NiranjanBS** [comment] 2016-04-15 04:34
I am still facing same issue.
![untitled](https://cloud.githubusercontent.com/assets/9413835/14551483/68765360-02f1-11e6-9ae2-cbf598824036.png)

Any config changes I need to do??

**Comment by pveentjer** [comment] 2016-04-15 10:00
@noctarius please switch to 3.7 and add the following:

```
-Dhazelcast.performance.metric.level=info
-Dhazelcast.performance.monitor.enabled=true
-Dhazelcast.performance.monitor.invocation.sample.period.seconds=30
-Dhazelcast.performance.monitor.pending.invocations.period.seconds=30
-Dhazelcast.performance.monitor.slowoperations.period.seconds=30
```

This should give detailed information of what is happening; especially it should give some insights in operation executions.

@NiranjanBS I'm not that familiar with the tool you are using. It don't need to mean that Hazelcast has high cpu usage; it can also be that the whole system isn't doing much, and the it seems that threads that do a little bit of stuff, are consuming most of the cpu time; but this is all very relative. Imagine having a room of super lazy programmers, where each programmer writes 1 line of code per week, but 1 programmer writes 2-lines a week. Then it seems the  2-line programmer is very busy.

If you look at one of the graphs, you see that the 'acceptor thread' is doing a lot of work just like the regular io threads. But it is very unlikely that the acceptor thread is doing work all the time; so my guess it is almost idle just as the io threads. 

![4d409130-00e1-11e6-8248-55c51acfedb3](https://cloud.githubusercontent.com/assets/105243/14558146/71eb3e66-0309-11e6-8495-f53f86716881.png)

**Comment by NiranjanBS** [comment] 2016-04-15 14:20
@pveentjer 
As I have mentioned in my first comment I am testing in Windows 7 OS and all the screen shots I had uploaded are from JConsole and jvisualvm which are provided by java itself.

Today I tested by running only cache server there was no client connected and nothing else was running but still after around 2 hours cup is taking 100%. And once it goes to 100% it will never come down.

![100percentcpu](https://cloud.githubusercontent.com/assets/9413835/14564190/09d01aba-0343-11e6-83d4-acf2de009fe6.png)

**Comment by vbekiaris** [comment] 2016-04-15 14:57
@NiranjanBS thanks for the update, the CPU usage comes from Tomcat process so it looks like there's something wrong on the Tomcat/Shiro/Hazelcast-client side (if I remember correctly you mentioned you run Hazelcast in client-server mode, is this accurate?). Can you please provide more details on your use case so we can setup a lab to reproduce the issue?

- Which version of Shiro do you use?
- Do you use Hazelcast as cache for Shiro? or just for Tomcat web sessions?
- Could you please provide the relevant fragments of your Tomcat/Shiro configuration?

**Comment by NiranjanBS** [comment] 2016-04-15 15:27
@vbekiaris 

We have one dedicated web application in which we initialize the cache and load the userdetails and shiro session string, we use hazelcast clients to interact with hazelcast server.

In the above scenario we had just started the cache application without starting any other clients, basically there was no client interaction, only on startup data was loaded to the map through mapstore.

Shiro Version: 1.2.3
We use hazelcast map to store the shiro session
I have shared the code in mail with @noctarius if you need more details let me know I can share.
I am attaching the configuration files here.
[shiro.txt](https://github.com/hazelcast/hazelcast/files/221240/shiro.txt)

[hazelcast-client.xml.txt](https://github.com/hazelcast/hazelcast/files/221244/hazelcast-client.xml.txt)
[hazelcast.xml.txt](https://github.com/hazelcast/hazelcast/files/221245/hazelcast.xml.txt)

**Comment by vbekiaris** [comment] 2016-04-16 08:14
@NiranjanBS it would be great if you could also email me the code via mail.

**Comment by NiranjanBS** [comment] 2016-04-18 04:21
@vbekiaris 
Can you please share your email.

**Comment by NiranjanBS** [comment] 2016-04-18 08:58
@vbekiaris @noctarius @pveentjer 

I tested by creating simple cache server with out connecting any client, still I am facing same issue.
I am just creating a USER_DETAILS map with default configaration for hazelcast instance and just loaded 100 user objects. After 2 hours again CPU is burning to 100%.

We where suppose to give live next week, but hazelcast is become big block for us.

Versions are as follows.
Hazelcast - 3.6.2.
Java - 1.8.0_77.
Tomcat 8.0.30.
OS Windows 7.

I have attacked the complete source code here.

[cacheserver.zip](https://github.com/hazelcast/hazelcast/files/223359/cacheserver.zip)

**Comment by pveentjer** [comment] 2016-04-18 09:09
@NiranjanBS would it be possible to switch to 3.7-SNAPSHOT and add the following parameters:

```
-Dhazelcast.performance.metric.level=info
-Dhazelcast.performance.monitor.enabled=true
-Dhazelcast.performance.monitor.invocation.sample.period.seconds=30
-Dhazelcast.performance.monitor.pending.invocations.period.seconds=30
-Dhazelcast.performance.monitor.slowoperations.period.seconds=30
```

And rerun your test? This should give us a lot more detailed information what is happening. What confuses me is why only the io threads are doing something.

**Comment by NiranjanBS** [comment] 2016-04-18 09:17
@pveentjer We have already added the mentioned parameters (3.6.2) while running the test. PFA jvm option for your reference.
But i am not able to see more information in the tomcat & application log files. please let me know where to check. 

![jvm_details](https://cloud.githubusercontent.com/assets/9413835/14599302/38d02b2e-0574-11e6-81b3-3b299d6fef83.png)

**Comment by pveentjer** [comment] 2016-04-18 09:18
These properties only work with 3.7. I have improved the performance logging system in 3.7.

**Comment by NiranjanBS** [comment] 2016-04-18 11:12
@pveentjer 
Ok I will test in 3.7 too.

do you make new HZ client instance all the time?
- No, I am creating only one client instance for entire application, my client manager is a single top.
And as I mentioned above code I have shared above has only server there is no client interaction at all.

**Comment by pveentjer** [comment] 2016-04-18 11:22
@NiranjanBS no; creating new clients would be disastrous for your performance :)

I'm looking forward to the log file. What I find strange is that according to the following graph:
https://cloud.githubusercontent.com/assets/9413835/14461697/4d409130-00e1-11e6-8248-55c51acfedb3.png

is the following:
1: your client is doing stuff since the ClientInSelector/ClientOutSelector are the io threads of the client. In 3.7 they will have a more sensible name btw
2: why is the acceptor thread doing so much work. Because normally it should not.

Anyhow... the performance log files will provide some insights in what is happening. Especially on the connection level.

**Comment by NiranjanBS** [comment] 2016-04-18 11:30
@pveentjer 

I have started testing on 3.7 by setting -Dhazelcast property to tomcat.
where can I find log files which you are expecting, because I am not seeing any extra log in tomcat as well as application log.

**Comment by pveentjer** [comment] 2016-04-18 11:33
you should fine them in the working directory of your application. See 'user.dir' from System properties. Files should be called performance-xxx.log

**Comment by NiranjanBS** [comment] 2016-04-18 12:00
Ok It is generating performance-xxx.log files. Give me some time, once CPU hits 100% I will share them here.

**Comment by pveentjer** [comment] 2016-04-18 12:03
keep it running for at least 10 minutes after you get the problems.

**Comment by NiranjanBS** [comment] 2016-04-18 12:09
ya sure.

**Comment by vbekiaris** [comment] 2016-04-18 12:38
I have been running the sample code on Windows 7, Tomcat 8.0_30, JDK 1.8.0_77 with Hazelcast 3.6.2 for more than an hour and I don't see any CPU usage on tomcat process. Perhaps there is something else in your environment causing the additional CPU usage? Let's wait for the 3.7 performance logs and see if we find anything interesting there.

**Comment by NiranjanBS** [comment] 2016-04-18 14:34
@pveentjer @vbekiaris @noctarius 

With 3.7-SNAPSHOT also I am facing same issue. Please find the performance-xxx.log file and screenshot attached below.

Even heap memory is increasing continually you can see in screen shot.

![cpu_usage](https://cloud.githubusercontent.com/assets/9413835/14607701/4e1e9bc4-05a0-11e6-9776-2246058999b5.png)

[performance-127.0.0.1#5701-1460978886777-000.zip](https://github.com/hazelcast/hazelcast/files/223959/performance-127.0.0.1.5701-1460978886777-000.zip)

**Comment by pveentjer** [comment] 2016-04-18 18:44
I need to do more careful analysis but I'm very confused. According to the performance log the io threads are not doing much (nothing actually) since they are idle. Also there are no connections; hence another reason for the io threads to be idle. Also not much operations are being executed.

So currently I'm baffled how it can be that the io threads are appearing to cpu time even though according to the probes, there is really no indication they are actually doing anything.

I'll have a closer look at the log files tomorrow morning.

**Comment by pveentjer** [comment] 2016-04-18 18:47
Could you do a run with flight recorder?

**Comment by pveentjer** [comment] 2016-04-19 03:59
If you could run with flight recorder, I can see what the threads are doing. Even though the IO threads show they are not doing any effective work (since they have not updated their last usage time; hence they are idle), according to your observations they are doing stuff. Another option would be to enable the profiler-plugin inside JVisualVM and see which methods are being executed by the io threads and where time is being spend.

**Comment by NiranjanBS** [comment] 2016-04-19 04:08
Ya sure I will check.

**Comment by NiranjanBS** [comment] 2016-04-19 06:28
@pveentjer 
I enabled flight recorder and i have attached the screenshot.
![1](https://cloud.githubusercontent.com/assets/9413835/14629654/c56b09ee-0625-11e6-970d-355820f1bc5c.png)

**Comment by vbekiaris** [comment] 2016-04-19 07:31
The cpu consumption in nio SelectorImpl.select under Windows looks quite similar to this netty issue https://github.com/netty/netty/issues/3857. I will look into this and get back to you. 

19 Απρ 2016, 09:28, ο/η Niranjan <notifications@github.com> έγραψε:

**Comment by NiranjanBS** [comment] 2016-04-19 09:07
@vbekiaris 
You can refer below attachment also. Which gives complete stack of method calls.

![methods](https://cloud.githubusercontent.com/assets/9413835/14633657/3b414f64-063c-11e6-93aa-930d941aab41.png)

**Comment by vbekiaris** [comment] 2016-04-19 12:28
Hi @NiranjanBS, can you download updated version of Hazelcast 3.7-SNAPSHOT from https://tresor.it/s#_ZLVvB6AX7VCSwScCB5myw and test again (github won't let me attach the JAR here)? You need to add `-Dhazelcast.io.selectorWorkaround=true` to your Tomcat JVM startup options. This jar was built from https://github.com/vbekiaris/hazelcast/tree/master-nio-cpu, you can see the changes in the last commit on that branch.

**Comment by NiranjanBS** [comment] 2016-04-19 13:09
Ya sure I will check.

**Comment by NiranjanBS** [comment] 2016-04-19 15:35
@vbekiaris 
My test is still going on, usually after 2 hours CPU use to hit 100% from (0% - 2%), but now it is hitting 25% from (0% - 2%). I will test for long duration and get back.
Thanks for you support.

**Comment by vbekiaris** [comment] 2016-04-19 15:53
Great, I think that if you fire up a visualvm/mission control and check cpu usage, the acceptor thread must be the one causing the excess usage while in/out threads should now be at the bottom end. Can you please confirm? Also, once you conclude your test, can you share the performance log? 
Thanks

**Comment by NiranjanBS** [comment] 2016-04-20 04:34
Hi @vbekiaris , yes you are right now acceptor thread is the one which is taking more CPU.
But you can see in screenshot memory is growing rapidly. I have attached the performance-xxx.log files and screenshot.
[Uploading performance.zip…]()
![cpuusage](https://cloud.githubusercontent.com/assets/9413835/14663434/a663cd2e-06de-11e6-95f0-e5347a5e3736.png)

**Comment by NiranjanBS** [comment] 2016-04-20 04:45
PFA of performance-xxx.log

[performance-127.0.0.1#5701-1460993461631-001.txt](https://github.com/hazelcast/hazelcast/files/227219/performance-127.0.0.1.5701-1460993461631-001.txt)
[performance-127.0.0.1#5702-1461071727679-000.txt](https://github.com/hazelcast/hazelcast/files/227221/performance-127.0.0.1.5702-1461071727679-000.txt)
[performance-127.0.0.1#5702-1461071727679-001.txt](https://github.com/hazelcast/hazelcast/files/227220/performance-127.0.0.1.5702-1461071727679-001.txt)
[performance-127.0.0.1#5701-1461057839371-000.txt](https://github.com/hazelcast/hazelcast/files/227222/performance-127.0.0.1.5701-1461057839371-000.txt)

**Comment by NiranjanBS** [comment] 2016-04-21 07:37
@vbekiaris @pveentjer @noctarius 
I have not stoped the test, its still running I am still facing issue with Memory and CUP. Any updates please. 
![untitled](https://cloud.githubusercontent.com/assets/9413835/14701187/a33474b2-07c1-11e6-8b99-ea539da0a2ff.png)

**Comment by vbekiaris** [comment] 2016-04-21 07:41
Hi @NiranjanBS , we are working on the final fix for this one, which will address excess object allocation (this was introduced as a side-effect of the temporary workaround you are now testing) and also introduce the workaround in acceptor thread as well.

**Comment by vbekiaris** [comment] 2016-04-22 09:38
Hi @NiranjanBS , would you be so kind as to run your test again with the attached Hazelcast binary? [hazelcast-3.7-SNAPSHOT.jar.zip](https://github.com/hazelcast/hazelcast/files/231512/hazelcast-3.7-SNAPSHOT.jar.zip)
This is built from https://github.com/vbekiaris/hazelcast/tree/master-nio-workaround and should fix Acceptor thread CPU usage and excess object allocation.
It would be great if you could also attach your performance logs at the end of the test run.

**Comment by NiranjanBS** [comment] 2016-04-22 12:41
ya sure we will check.

**Comment by bwzhang2011** [comment] 2016-04-27 08:12
@NiranjanBS, any update with such issue ?

**Comment by NiranjanBS** [comment] 2016-04-27 11:04
Hi, I am running test from 4-5 days, there is no high CPU usage, but still am facing Memory issue as you can see in attachment.

@vbekiaris We have done workaround for both server and client selector threads, because I have seen client selector threads also using high CPU.

https://cloud.githubusercontent.com/assets/9413835/14551483/68765360-02f1-11e6-9ae2-cbf598824036.png

![27apr2016](https://cloud.githubusercontent.com/assets/9413835/14850248/64c634f8-0c95-11e6-8627-19b1c4526388.png)

**Comment by vbekiaris** [comment] 2016-04-27 14:11
Hi @NiranjanBS , a couple of questions:
- Can you compare the heap memory usage you see in your application now against running without the workaround enabled (remove `-Dhazelcast.io.selectorWorkaround=true` from your JVM options), in order to see how the workaround affects memory usage vs no workaround?
Comparing current to the [previous workaround version](https://github.com/hazelcast/hazelcast/issues/7943#issuecomment-212787618), the sawtooth is now sparser (implying less allocation) and seems to reach maximum heap size less frequently than once per day, while the previous version reached max heap size twice per day.
- Can you also share your performance.log files?

The workaround is currently only implemented on the server side, so if you see client side IO threads with high CPU usage, we'll need to apply the workaround there as well.

**Comment by bwzhang2011** [comment] 2016-04-28 03:39
Dear all, as there's a period of time before hazelcast3.7 released,  @vbekiaris, @pveentjer, does next stable version 3.6.3 solve such problem ?

**Comment by bwzhang2011** [comment] 2016-05-05 15:42
any update with such issue ?

**Closed** 2016-05-11 10:28 UTC
Labels: Team: Core, Type: Defect

**Comment by vbekiaris** [comment] 2016-05-11 20:53
@NiranjanBS, @bwzhang2011 the fix is now merged in master and a backport will be available in 3.x branch shortly. In order to enable the workaround, you need to supply system property `-Dhazelcast.io.selectorMode=selectwithfix` on JVM startup (note it's different from the property used in intermediate versions posted above).

@NiranjanBS thanks for your help in locating and fixing this. It would be great if you could use 3.7-SNAPSHOT to run a test with following system properties:
```
-Dhazelcast.io.selectorMode=selectwithfix
-Dhazelcast.diagnostics.enabled=true
-Dhazelcast.diagnostics.metric.level=info
-Dhazelcast.diagnostics.invocation.sample.period.seconds=30
-Dhazelcast.diagnostics.pending.invocations.period.seconds=30
-Dhazelcast.diagnostics.slowoperations.period.seconds=30
```
and attach here your performance.log after the test. I guess a 3.7-SNAPSHOT build with the fix included should be available tomorrow on [Hazelcast maven snapshot repository](https://oss.sonatype.org/content/repositories/snapshots).

**Comment by SomannaDC** [comment] 2016-10-06 15:12
@vbekiaris @pveentjer @noctarius @bwzhang2011 @NiranjanBS -- Is the issue resolved, we are facing similar issue with 3.6.2, is there a later version of Hazelcast with the fix for this issue?

**Comment by vbekiaris** [comment] 2016-10-06 15:35
Hi @SomannaDC , yes, it is fixed in 3.6.3 (by https://github.com/hazelcast/hazelcast/pull/8154) and 3.7 (by https://github.com/hazelcast/hazelcast/pull/7998).

If you believe you are hit by the same JVM/network stack bug, then you should start hazelcast adding the system property `hazelcast.io.selectorMode=selectwithfix` to your JVM startup.

If after upgrading & testing with this system property enabled you still see high cpu usage while idle, then please create a new issue for further investigation.

**Comment by linkedz** [comment] 2018-04-30 07:16
Hi

I've got the same problem, when very simple project (from the comment of related issue) after 2 hrs (+/- few minutes) got 100% CPU usage
hazelcast/hazelcast#7943 (comment)

Env: Windows 10, jdk build 1.8.0_171-b11, tried also with jdk v71, v161
also different versions of hazelcast: 3.6.2, 3.8.8, 3.9.4, 3.10.
Problem always is reproducing with 100% chance after 2 hrs of idle.

In debug there is next info, if compare data before and after CPU overhead:
sun.nio.ch.WindowsSelectorImpl.SubSelector#poll0
before - readFds array is fulled with 0
after - readFds[0] == 1, value of readFds[1] == sun.nio.ch.WindowsSelectorImpl#wakeupSourceFd
also method poll0 is executing instantly, without any timeout and thread is in endless loop without block or wait.

Any help on the problem? Or any advise what to debug else or try to change?

**Comment by vbekiaris** [comment] 2018-04-30 10:05
> you should start hazelcast adding the system property hazelcast.io.selectorMode=selectwithfix to your JVM startup.

@linkedz did you try this advice in the comment above? This property enables the selector issue workaround.

**Comment by linkedz** [comment] 2018-04-30 13:13
Just now tried and it helped to fix the problem, thanks!

**Comment by vbekiaris** [comment] 2018-05-02 09:53
nice, thanks for the heads up @linkedz
