### ISSUE TITLE
SemaphoreAdvancedTest.testSemaphoreWithFailuresAndJoin

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11818] opened 2017-11-20 07:37 UTC
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1012)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:997)
	at com.hazelcast.concurrent.semaphore.SemaphoreAdvancedTest.testSemaphoreWithFailuresAndJoin(SemaphoreAdvancedTest.java:112)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/338/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreAdvancedTest/testSemaphoreWithFailuresAndJoin/

**Comment by mdogan** [comment] 2017-11-28 14:37
```
17:30:15 java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
17:30:15 	at org.junit.Assert.fail(Assert.java:88)
17:30:15 	at org.junit.Assert.assertTrue(Assert.java:41)
17:30:15 	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1016)
17:30:15 	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1009)
17:30:15 	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1001)
17:30:15 	at com.hazelcast.concurrent.semaphore.SemaphoreAdvancedTest.testSemaphoreWithFailuresAndJoin(SemaphoreAdvancedTest.java:112)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11859/console

**Comment by hasancelik** [comment] 2017-12-04 07:58
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1016)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1001)
	at com.hazelcast.concurrent.semaphore.SemaphoreAdvancedTest.testSemaphoreWithFailuresAndJoin(SemaphoreAdvancedTest.java:112)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/305/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreAdvancedTest/testSemaphoreWithFailuresAndJoin/

**Comment by Holmistr** [comment] 2017-12-08 10:49
This test has been ignored, because of a complex root cause (see the comment https://github.com/hazelcast/hazelcast/pull/11935 ). The root cause is described in detail in https://github.com/hazelcast/hazelcast/issues/11839
Closing this issue.

**Closed by Holmistr** 2017-12-08 10:49 UTC
Labels: Team: Core, Type: Test-Failure
