### ISSUE TITLE
Hazelcast 3.2.1: PortableFactory[-23] is already registered! with custom class loader

### ISSUE THREAD

**Issue by lbakman** [hazelcast/hazelcast#2395] opened 2014-05-06 11:38 UTC
We are using a custom class loader in our application. After upgrading to Hazelcast 3.2.1 this causes Hazelcast to throw an IllegalArgumentException: PortableFactory[-23] is already registered! in PortableHookLoader.register().

This is caused by the ServiceLoader returning a set of ServiceDefinitions with duplicate class name entries. This in turn seems to caused by a change in revision 88b8e4d (2014-04-14) where the ServiceDefinition.equals() and ServiceDefinition.hashCode() was changed to include the classLoader as well as the className.

Was this change to ServiceDefinition intended?

**Comment by ejain** [comment] 2016-09-08 00:37
Seeing the same problem in a Spring Boot web application (but only when the application is run as an executable war file): `ServiceLoader.iterator` returns duplicates, which causes the _PortableFactory is already registered!_ failures.

Everything works fine when `selectClassLoaders` returns:
```
[TomcatEmbeddedWebappClassLoader
  context:
  delegate: true
  repositories:
----------> Parent Classloader:
java.net.URLClassLoader@b6810f
, java.net.URLClassLoader@b6810f]
```
...but fails with this set of class loaders:
```
[TomcatEmbeddedWebappClassLoader
  context:
  delegate: true
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
org.springframework.boot.loader.LaunchedURLClassLoader@4c873330
, org.springframework.boot.loader.LaunchedURLClassLoader@4c873330]
```

**Comment by mrahbar** [comment] 2016-09-27 06:39
@ejain Which Spring-Boot version are you using? I had the same problem with the 1.3.6 Release but it was resolved with the 1.4.1. The problem lies in the class LaunchedURLClassLoader which has gone through some code changes between those versions.

**Comment by ejain** [comment] 2016-09-27 17:58
@mrahbar using Spring Boot 1.3.5; good to know that upgrading might resolve the issue.

**Comment by ejain** [comment] 2016-09-29 20:13
Seeing the same problem with Spring Boot 1.4.1 (Spring 4.3.3) and Hazelcast 3.7.1:

```java.lang.IllegalArgumentException: PortableFactory[-1] is already registered! com.hazelcast.spi.impl.SpiPortableHook$1@62029d43 -> com.hazelcast.spi.impl.SpiPortableHook$1@9a7cc10
        at com.hazelcast.internal.serialization.impl.PortableHookLoader.register(PortableHookLoader.java:87) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.internal.serialization.impl.PortableHookLoader.load(PortableHookLoader.java:54) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.internal.serialization.impl.PortableHookLoader.<init>(PortableHookLoader.java:44) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.internal.serialization.impl.SerializationServiceV1.<init>(SerializationServiceV1.java:88) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:264) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:218) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:46) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:126) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.instance.Node.<init>(Node.java:181) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:155) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58) ~[hazelcast-3.7.1.jar!/:3.7.1]
        at org.springframework.boot.autoconfigure.hazelcast.HazelcastInstanceFactory.getHazelcastInstance(HazelcastInstanceFactory.java:82) ~[spring-boot-autoconfigure-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
        at org.springframework.boot.autoconfigure.hazelcast.HazelcastAutoConfiguration$HazelcastConfigConfiguration.hazelcastInstance(HazelcastAutoConfiguration.java:78) ~[spring-boot-autoconfigure-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
        at org.springframework.boot.autoconfigure.hazelcast.HazelcastAutoConfiguration$HazelcastConfigConfiguration$$EnhancerBySpringCGLIB$$a5d829fe.CGLIB$hazelcastInstance$0(<generated>) ~[spring-boot-autoconfigure-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
        at org.springframework.boot.autoconfigure.hazelcast.HazelcastAutoConfiguration$HazelcastConfigConfiguration$$EnhancerBySpringCGLIB$$a5d829fe$$FastClassBySpringCGLIB$$7c2bd309.invoke(<generated>) ~[spring-boot-autoconfigure-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        at org.springframework.boot.autoconfigure.hazelcast.HazelcastAutoConfiguration$HazelcastConfigConfiguration$$EnhancerBySpringCGLIB$$a5d829fe.hazelcastInstance(<generated>) ~[spring-boot-autoconfigure-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
        ... 63 common frames omitted```

**Comment by ejain** [comment] 2016-10-04 21:34
Ended up using the workaround described in https://github.com/hazelcast/hazelcast/issues/3922#issuecomment-61421708.

**Comment by enesakar** [comment] 2016-11-23 11:49
3.2.1 is pretty old. Please comment if the issues exists in 3.7 and newer. Closing.

**Closed by enesakar** 2016-11-23 11:49 UTC
Labels: Team: Client, Type: Defect

**Comment by ejain** [comment] 2016-11-23 23:10
@enesakar, this problem exists with 3.7.1, see https://github.com/hazelcast/hazelcast/issues/2395#issuecomment-250577842.

**Comment by bmudda** [comment] 2016-12-01 17:04
@enesakar @ejain this issue still exists with Spring boot 1.4.2 and Hazelcast 3.7.3.
```java
2016-12-01 11:40:07.935  INFO 93667 --- [           main] com.hazelcast.config.ClasspathXmlConfig  : Configuring Hazelcast from 'springConfigs/hazelcast/hazelcast-docker.xml'.
2016-12-01 11:40:08.170  INFO 93667 --- [           main] c.h.instance.DefaultAddressPicker        : [LOCAL] [hazelcast-docker-test] [3.7.3] Prefer IPv4 stack is true.
2016-12-01 11:40:08.243  INFO 93667 --- [           main] c.h.instance.DefaultAddressPicker        : [LOCAL] [hazelcast-docker-test] [3.7.3] Picked [127.0.0.1]:5701, using socket ServerSocket[addr=/127.0.0.1,localport=5701], bind any local is false
2016-12-01 11:40:08.289  INFO 93667 --- [           main] com.hazelcast.system                     : [127.0.0.1]:5701 [hazelcast-docker-test] [3.7.3] Hazelcast 3.7.3 (20161117 - 8166eea) starting at [127.0.0.1]:5701
2016-12-01 11:40:08.292  INFO 93667 --- [           main] com.hazelcast.system                     : [127.0.0.1]:5701 [hazelcast-docker-test] [3.7.3] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
2016-12-01 11:40:08.292  INFO 93667 --- [           main] com.hazelcast.system                     : [127.0.0.1]:5701 [hazelcast-docker-test] [3.7.3] Configured Hazelcast Serialization version : 1
2016-12-01 11:40:08.373  WARN 93667 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastRunner' defined in class path resource [springConfigs/hazelcast/hazelcastRunner.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.bmudda.hazelcast.docker.test.HazelcastRunner]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: PortableFactory[-22] is already registered! com.hazelcast.replicatedmap.impl.client.ReplicatedMapPortableHook$1@1a8a8f7c -> com.hazelcast.replicatedmap.impl.client.ReplicatedMapPortableHook$1@2353b3e6
2016-12-01 11:40:08.378  INFO 93667 --- [           main] o.apache.catalina.core.StandardService   : Stopping service Tomcat
```

And the stacktrace:
```java
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastRunner' defined in class path resource [springConfigs/hazelcast/hazelcastRunner.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.bmudda.hazelcast.docker.test.HazelcastRunner]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: PortableFactory[-22] is already registered! com.hazelcast.replicatedmap.impl.client.ReplicatedMapPortableHook$1@1a8a8f7c -> com.hazelcast.replicatedmap.impl.client.ReplicatedMapPortableHook$1@2353b3e6
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:279) ~[classes!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1148) ~[classes!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050) ~[classes!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512) ~[classes!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[classes!/:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[classes!/:na]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[classes!/:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[classes!/:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[classes!/:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754) ~[classes!/:na]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[classes!/:na]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[classes!/:na]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[classes!/:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [classes!/:na]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [classes!/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [classes!/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [classes!/:na]
	at com.bmudda.util.boot.Application.main(Application.java:21) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [hazelcast-docker-spring-test-1.0-RC1.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [hazelcast-docker-spring-test-1.0-RC1.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [hazelcast-docker-spring-test-1.0-RC1.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [hazelcast-docker-spring-test-1.0-RC1.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.bmudda.hazelcast.docker.test.HazelcastRunner]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: PortableFactory[-22] is already registered! com.hazelcast.replicatedmap.impl.client.ReplicatedMapPortableHook$1@1a8a8f7c -> com.hazelcast.replicatedmap.impl.client.ReplicatedMapPortableHook$1@2353b3e6
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154) ~[classes!/:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122) ~[classes!/:na]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271) ~[classes!/:na]
	... 25 common frames omitted
Caused by: java.lang.IllegalArgumentException: PortableFactory[-22] is already registered! com.hazelcast.replicatedmap.impl.client.ReplicatedMapPortableHook$1@1a8a8f7c -> com.hazelcast.replicatedmap.impl.client.ReplicatedMapPortableHook$1@2353b3e6
	at com.hazelcast.internal.serialization.impl.PortableHookLoader.register(PortableHookLoader.java:87) ~[classes!/:na]
	at com.hazelcast.internal.serialization.impl.PortableHookLoader.load(PortableHookLoader.java:54) ~[classes!/:na]
	at com.hazelcast.internal.serialization.impl.PortableHookLoader.<init>(PortableHookLoader.java:44) ~[classes!/:na]
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1.<init>(SerializationServiceV1.java:88) ~[classes!/:na]
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:264) ~[classes!/:na]
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:218) ~[classes!/:na]
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:46) ~[classes!/:na]
	at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:126) ~[classes!/:na]
	at com.hazelcast.instance.Node.<init>(Node.java:181) ~[classes!/:na]
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:155) ~[classes!/:na]
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126) ~[classes!/:na]
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218) ~[classes!/:na]
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176) ~[classes!/:na]
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126) ~[classes!/:na]
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58) ~[classes!/:na]
	at com.bmudda.hazelcast.docker.test.HazelcastRunner.<init>(HazelcastRunner.java:40) ~[classes!/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_51]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142) ~[classes!/:na]
	... 27 common frames omitted
```

**Comment by bitsofinfo** [comment] 2016-12-01 17:06
blocker for us

**Comment by jerrinot** [comment] 2016-12-01 19:24
@ejain: perhaps this could help you? https://github.com/hazelcast/hazelcast/issues/9353#issuecomment-264266267

**Comment by ejain** [comment] 2016-12-01 19:36
@jerrinot: at least in our case, there is no duplicate `com.hazelcast.PortableHook` file; the problem is due to Spring Boot's classloader hierarchy. Maybe the Spring and Hazelcast teams can spend the next couple of years pointing fingers at each other :-)

**Comment by jerrinot** [comment] 2016-12-01 19:41
@ejain: Spring folks are our buddies and there is nothing to gain by pointing fingers. 

It means your issues have a different cause. Do you have a reproducer to share?

**Comment by JanMosigItemis** [comment] 2017-01-11 18:54
In case anyone is building a fat jar with maven + shade plugin and encounters this problem, this is what I did to resolve it:

````
<plugins>
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
            <execution>
                <phase>package</phase>
	        <goals>
                    <goal>shade</goal>
                </goals>
                <configuration>
                 ...
                <filter>
                    <!-- using the Spring Boot variety of hz -->
                    <artifact>com.hazelcast:hazelcast</artifact>
		    <excludes>
                        <exclude>META-INF/services/com.hazelcast.DataSerializerHook</exclude>
			<exclude>META-INF/services/com.hazelcast.instance.NodeExtension</exclude>
			<exclude>META-INF/services/com.hazelcast.PortableHook</exclude>
                   </excludes>
		</filter>
                ...
````

The reason is, like @jerrinot (I think it was him), pointed out in another thread, that some startup hooks are ending up in the fat jar on two places: Inside hazelcast.jar and inside the META-INF folder. This causes the duplicate registration error. This is not easy to spot and should be documented somewhere.

**Comment by jerrinot** [comment] 2017-04-28 07:52
thanks to @mmoayyed we have a reproducer for the "Spring Boot with embedded Tomcat" situation: https://github.com/hazelcast/hazelcast/issues/10438

The simplest workaround is to switch your application from WAR to (executable) JAR packaging. 

To me it looks like a Spring Boot issue and I have create a [new issue](https://github.com/spring-projects/spring-boot/issues/9014) We also have a [possible workaround](https://github.com/hazelcast/hazelcast/pull/10444) inside Hazelcast ready.
