### ISSUE TITLE
BasicMapTest.github_11489_verifyNoFailingCastOnValue

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11559] opened 2017-10-11 09:41 UTC
```
04:50:38 Running com.hazelcast.map.BasicMapTest
04:50:52 Tests run: 42, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.447 sec <<< FAILURE! - in com.hazelcast.map.BasicMapTest
04:50:52 github_11489_verifyNoFailingCastOnValue(com.hazelcast.map.BasicMapTest)  Time elapsed: 3.629 sec  <<< ERROR!
04:50:52 
java.lang.UnsupportedClassVersionError: com/fasterxml/jackson/databind/ObjectMapper : Unsupported major.minor version 51.0
04:50:52 	at java.lang.ClassLoader.defineClass1(Native Method)
04:50:52 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
04:50:52 	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
04:50:52 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
04:50:52 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
04:50:52 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
04:50:52 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
04:50:52 	at java.security.AccessController.doPrivileged(Native Method)
04:50:52 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
04:50:52 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
04:50:52 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
04:50:52 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
04:50:52 	at com.hazelcast.map.BasicMapTest.github_11489_verifyNoFailingCastOnValue(BasicMapTest.java:1203)
```

Our JDK-6 builds started to fail after this commit:
https://github.com/hazelcast/hazelcast/commit/043741d2966d6899eea4374b07c62897bb6f4b47#diff-18f8043a9c9630c7c4c6d437cb8ac71a

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/254/consoleFull#-2027326521cf6124f9-bc3d-408b-b969-6e8323ce4167

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/255/

**Comment by Donnerbart** [comment] 2017-10-11 09:43
Duplicate of https://github.com/hazelcast/hazelcast-enterprise/issues/1764

**Comment by Donnerbart** [comment] 2017-10-11 09:46
We could guard this test with `assumeFalse(System.getProperty("java.version").startsWith("1.6."));`

**Closed** 2017-10-11 14:21 UTC
Labels: Team: Core, Type: Test-Failure
