### ISSUE TITLE
com.hazelcast.internal.dynamicconfig.DynamicConfigTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18738] opened 2021-05-24 08:58 UTC
_master_ (commit c3c641fc6af0924ccc140f24d98e37f7f8dd66b1)

Failed on IBM JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/131/testReport/com.hazelcast.internal.dynamicconfig/DynamicConfigTest/

Following tests from `com.hazelcast.internal.dynamicconfig.DynamicConfigTest` failed with various exceptions:
- `testMapConfig_withQueryCacheConfig`
- `testMapConfig_withQueryCacheConfig_andEntryListenerConfigByClassName`
- `testCacheConfig_withEvictionPolicyImplementation_cacheLoaderAndWriterFactory`
- `testTopicConfig_whenListenerConfigByImplementation`
- `testMapConfig`

See stacktraces and standard output here - https://s3.console.aws.amazon.com/s3/object/j-artifacts?region=us-east-1&prefix=Hazelcast-master-IbmJDK8/131/Hazelcast-master-IbmJDK8-131.tar

**Comment by fbarotov** [comment] 2021-06-17 11:49
I went over the logs and all the above failures seem to be due to network / split-brain issue. For example, `testMapConfig` failure is as follows:


1. instances `i1`, `i2`
2. They both connect to form a cluster, where `i1` is the master.
3. `i2` does not hear from `i1` for a while, transitions to suspicious state, declares `i1` as dead, and then claims mastership
4. `i2` receives `addMapConfig` request, applies to itself and returns success, i.e., does not throw an exception
5. in the test, we assert `i1` should have the new configuration, but it does not. 
6. thus test failure


Here are related failure logs for `testMapConfig_withQueryCacheConfig_andEntryListenerConfigByClassName`

> INFO |testMapConfig_withQueryCacheConfig_andEntryListenerConfigByClassName| - [HealthMonitor] hz.peaceful_goldwasser.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=167.9G, swap.space.total=4.0G, swap.space.free=2.1G, heap.memory.used=1.9G, heap.memory.free=2.1G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=48.28%, heap.memory.used/max=48.28%, **_minor.gc.count=246, minor.gc.time=7204ms_**,
...

> WARN |testMapConfig_withQueryCacheConfig_andEntryListenerConfigByClassName| - [ClusterHeartbeatManager] hz.peaceful_goldwasser.cached.thread-6 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Suspecting Member [127.0.0.1]:5701 - c6fa84fb-0da7-40c8-91ce-7d3dd1f020b9 because it has not sent any heartbeats since 2021-05-21 23:16:19.513. Now: 2021-05-21 23:20:03.202, heartbeat timeout: 60000 ms, suspicion level: 1.00
23:26:07,003  

> WARN |testMapConfig_withQueryCacheConfig_andEntryListenerConfigByClassName| - [MembershipManager] hz.peaceful_goldwasser.cached.thread-6 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Member [127.0.0.1]:5701 - c6fa84fb-0da7-40c8-91ce-7d3dd1f020b9 is suspected to be dead for reason: Suspecting Member [127.0.0.1]:5701 - c6fa84fb-0da7-40c8-91ce-7d3dd1f020b9 because it has not sent any heartbeats since 2021-05-21 23:16:19.513. Now: 2021-05-21 23:20:03.202, heartbeat timeout: 60000 ms, suspicion level: 1.00
23:26:07,003  

> INFO |testMapConfig_withQueryCacheConfig_andEntryListenerConfigByClassName| - [MembershipManager] hz.peaceful_goldwasser.cached.thread-6 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Starting mastership claim process...


> THREAD DUMP FOR TEST FAILURE: "AddDynamicConfigOperation invocation failed to complete due to operation-heartbeat-timeout.

Others all follow same path of getting into split-brain state, except test failures are due to assertions (like the one described above for `testMapConfig`) but not operation invocation timeout

**Comment by mmedenjak** [comment] 2021-07-26 13:37
Thank you for the nice analysis @fbarotov . I'll close this issue as it's an environment cause, and there's very little we can do in our codebase really. A similar test failure was [here](https://github.com/hazelcast/hazelcast/issues/18611). But inspired by [this article](https://eng.uber.com/handling-flaky-tests-java/), I'm really wondering if we can improve on the current situation. First, I'm curious to see if we can somehow quantify the frequency of root causes on flaky test failures. We definitely have environment issues, problems on test code, problems on production code. I'm wondering if we can somehow quantify how much of environment root causes we get as opposed to actual issues on code, and base our next decision on that - actually decrease test parallelism, run in cloud on dedicated boxes, IDK.

Anyway, food for thought.

**Closed by mmedenjak** 2021-07-26 13:37 UTC
Labels: Module: Config, Source: Internal, Team: Core, Type: Test-Failure
