### ISSUE TITLE
Add putMulti and removeMulti to MultiMap and removeMulti to IMap

### ISSUE THREAD

**Issue by hazelcast** [hazelcast/hazelcast#46] opened 2012-03-23 21:03 UTC
I noticed that there aren't MultiMap.putAll, MultiMap.removeAll and IMap.removeAll in API. It will be great to have these abilities to increase performance of 'multi' operations (i.e. do it in a bulk). We really need them (especially for MultiMap).<p>Migrated from http://code.google.com/p/hazelcast/issues/detail?id=553</p><hr/><h2>earlier comments</h2>

<p><strong>borislav.andruschuk said, at 2011-05-13T09:51:30.000Z:</strong></p>

<p>and the same IMap/MultiMap -> evictAll please.</p><p><strong>borislav.andruschuk said, at 2011-05-14T09:23:44.000Z:</strong></p>

<p>I've noticed that IMap.localKeySet already returns Entries - the list of local map entries. I think it will be quite good to have IMap.getLocalEntries() in API. Actually I' seeking for good filtering API for local entries w/o predicate usage: could you please add IMap.getAllLocalValues(Set keys) or IMap.getAllLocalEntries(Set keys) because you can efficiently filter local entries in CMap.</p><p><strong>hugo.zwaal said, at 2011-05-17T14:25:52.000Z:</strong></p>

<p>I would also like to see a MultiMap<K,V>.putMulti(K key, V values...) and a removeMulti()</p>

**Comment by mdogan** [comment] 2017-02-16 10:45
By version 3.8, `IMap` has `removeAll(Predicate<K, V> predicate)`;

```java
 /**
     * Removes all entries which match with the supplied predicate.
     * If this map has index, matching entries will be found via index search, otherwise they will be found by full-scan.
     *
     * Note that calling this method also removes all entries from callers near cache.
     *
     * @param predicate matching entries with this predicate will be removed from this map
     * @throws NullPointerException if the specified predicate is null.
     */
    void removeAll(Predicate<K, V> predicate);
```

**Comment by burakcelebi** [comment] 2018-01-03 14:10
Related: https://github.com/hazelcast/hazelcast/issues/9079

**Comment by peterjot** [comment] 2020-02-26 17:04
Hey, I would like to take that issue

@Holmistr

**Comment by Holmistr** [comment] 2020-02-26 20:59
Hey @peterjot , that would be awesome. However, I see that some work is actually being done on https://github.com/hazelcast/hazelcast/issues/9079 in https://github.com/abdulazizali77/hazelcast/commit/fa98e9b4fd6ff37b5e267987581558f16a2be6d5 . Let me take a look tomorrow and coordinate, so you wouldn't both work on the same thing. I will get back to you! Thank you very much for you interest :)

**Comment by Holmistr** [comment] 2020-03-02 08:43
Closing this issue, since it's basically a duplicate of https://github.com/hazelcast/hazelcast/issues/9079 (or subset)

**Closed by Holmistr** 2020-03-02 08:43 UTC
Labels: Module: MultiMap, Priority: Low, Source: Community, Team: Core, Type: Enhancement, good first issue

**Comment by c-attila** [comment] 2024-06-17 13:00
Hi! Does anyone know why was this not implemented in the end?
We would need this feature in our project using Hazelcast 5 Enterprise. A QueryCache for MultiMaps would be also good.
FYI @burakcelebi, @hazelcast, @Holmistr
(see also #3840 and #9079 still open)

**Comment by Holmistr** [comment] 2024-06-18 08:05
@c-attila In general, we never got it prioritized enough. MultiMap is not the most used datastructure (it was way behind Map, Queue, Topic, ...) and we just had bigger fish to fry. I would suggest you to reach through the Hazelcast Support and make a case for your usecase.

Disclaimer: I no longer work at Hazelcast.
