### ISSUE TITLE
Multimap entry listener provides incorrect null values

### ISSUE THREAD

**Issue by purplefox** [hazelcast/hazelcast#5538] opened 2015-06-18 13:11 UTC
There is a serious regression in Hazelcast 3.4.3.

If I create an entry listener on a multimap, and then removing some values from the map, the entry listener gets called with incorrect null values.

This currently causes the Vert.x test suite to fail and means we cannot upgrade to this version in the up-coming Vert.x 3.0 release which is due out in the next few days.

This is an *extremely* serious issue for us as we were counting on the 3.4.3 release to fix another critical issue which is preventing Vert.x users from successfully using Hazelcast for clustering.

I have included a simple reproducer here. To be honest it's a very simple test and I am pretty surprised that you don't already have tests that exercise this basic functionality in your test suite.

I include the reproducer here:

````
@Test
  public void testHZBug() throws Exception {

    HazelcastInstance hazelcast = Hazelcast.newHazelcastInstance();

    MultiMap<String, String> multiMap = hazelcast.getMultiMap("mymap");

    CountDownLatch latch = new CountDownLatch(1);
    AtomicBoolean bool = new AtomicBoolean();

    multiMap.addEntryListener(new EntryListener<String, String>() {
      @Override
      public void entryAdded(EntryEvent<String, String> entryEvent) {

      }

      @Override
      public void entryRemoved(EntryEvent<String, String> entryEvent) {
        System.out.println("Entry removed: " + entryEvent.getKey() + " value " + entryEvent.getValue());

        String value = entryEvent.getValue();
        if (!"blah".equals(value)) {
          System.out.println("!!!!!!!!!!!!!!!!!!! Value is " + value + " and should be 'blah'");
        } else {
          bool.set(true);
        }

        latch.countDown();
      }

      @Override
      public void entryUpdated(EntryEvent<String, String> entryEvent) {

      }

      @Override
      public void entryEvicted(EntryEvent<String, String> entryEvent) {

      }

      @Override
      public void mapEvicted(MapEvent mapEvent) {

      }

      @Override
      public void mapCleared(MapEvent mapEvent) {

      }
    }, true);

    multiMap.put("some-sub1", "blah");
    multiMap.put("some-sub2", "blah");
    multiMap.put("some-sub2", "wibble");

    for (Map.Entry<String, String> entry : multiMap.entrySet()) {
      String v = entry.getValue();
      if ("blah".equals(v)) {
        System.out.println("Removing " + entry.getKey() + " " + entry.getValue());
        multiMap.remove(entry.getKey(), v);
      }
    }

    latch.await(10, TimeUnit.SECONDS);
    Assert.assertTrue(bool.get());


  }


````

The bug only manifests with 3.4.3. If I change the HZ version to 3.4.2 it passes.

**Comment by jerrinot** [comment] 2015-06-18 13:26
Hi @purplefox,
that's embarrassing. I'm on it and I'll keep you updated.

**Comment by jerrinot** [comment] 2015-06-18 13:59
Analysis: 

There was a misjudgement on our side when backporting a behaviour change: https://github.com/hazelcast/hazelcast/pull/5407

I was an unfortunate, but concious decision to back-port it so tests could not catch it as they were changed too. It should have never been backported to a patch release. @gurbuzali is now working on fix to revert the change. We will have an emergency release tomorrow or on Monday latest (depending on our soak tests results)

I am sorry for the complications caused by this.

**Comment by purplefox** [comment] 2015-06-19 09:25
Thanks. Please keep us posted on progress.

**Comment by purplefox** [comment] 2015-06-21 13:37
@gurbuzali @jerrinot Any updates on this?

**Comment by purplefox** [comment] 2015-06-21 13:40
@jerrinot I notice there is a 3.4.4 on the website:

http://hazelcast.org/download/

Is this the one we should use?

**Comment by purplefox** [comment] 2015-06-21 13:41
I also notice a Hazelcast 3.5 was released on Wednesday - does this contain the fixes we need, or does it suffer from the same issue?

**Comment by Donnerbart** [comment] 2015-06-21 14:02
I think 3.4.4 was released because of this issue and AFAIK just contains the fix for this. I don't know exactly about 3.5, but I think the behavior change is still in there, since it is not a patch release (and it was the source for the unlucky backport).

So 3.4.4 should work for you, 3.5 may not (out of the box).

**Comment by purplefox** [comment] 2015-06-21 14:04
Ok thanks, so I guess there will be a 3.5.1 release out soon that fixes the broken multimap behaviour in the 3.5 branch? We don't want to be stuck on the 3.4 branch forever.

**Comment by Donnerbart** [comment] 2015-06-21 14:06
To be honest I have no idea about the intention of that change in 3.5.x. I think @gurbuzali can clarify this next week.

**Comment by gurbuzali** [comment] 2015-06-21 15:44
Hi @purplefox multimap behaviour in 3.5 is not broken, it is changed.
we've changed the way you get removed value in `EntryEvent`, now you need to call `getOldValue()` method of `EntryEvent` to be able to get the value. Our mistake was to backport this behavioral change to 3.4.x release, we've fixed it with 3.4.4.

**Closed by gurbuzali** 2015-06-21 15:44 UTC
Labels: Team: Core, Type: Critical, Type: Defect

**Comment by purplefox** [comment] 2015-06-21 16:29
Um.. ok... So why do we need 3.4.3 at all? ;)

If 3.5 supports what we want to do if we make a simple code change on our side and use getOldValue() instead of getValue(), then surely we could have just used that? Unless there are other breaking changes in it that I am unaware of... or I'm missing something.

BTW I am curious - what is Hazelcast's policy for making breaking changes between releases? Going from 3.4 to 3.5 there are clearly behavioural changes that may break users code when they upgrade (e.g. this multimap change of behaviour).

Do you allow such changes on minor releases (e.g. 3.4 to 3.5) but not on point releases (e.g. 3.4.2 to 3.4.3) ?

**Comment by Donnerbart** [comment] 2015-06-21 16:37
This issue is the reason for 3.4.4 being released so close after 3.4.3. The version 3.4.3 is fine, beside this backport related issue. So if you don't suffer from it, you don't have to upgrade.

I think your assumption on 3.5 is correct. If you can easily adapt to the new multimap interface, you should not have troubles to use this. Maybe there are other important changes, but they should be part of the release notes.

The policy should be that patch/point releases are compatible (I think even binary compatible), so a drop-in-replacement. Minor releases may have changes, although we try to be backward compatible if possible (by enhancing the API, not changing it).

**Comment by purplefox** [comment] 2015-06-21 16:39
Ok thanks for the info.

Could you clarify whether the fix for this: https://github.com/hazelcast/hazelcast/pull/5284#event-307374821 is included in the 3.5 release?

**Comment by purplefox** [comment] 2015-06-21 16:44
I think it's a pretty common (and sane!) policy to try to keep APIs compatible between minor releases and not change behaviour of existing methods. As you say "enhance" the API (e.g. by adding *new* methods and deprecating old methods), but not break the API by changing behaviour of current methods.

That being said, that clearly hasn't happened with the multimap behaviour change, I guess you have your own good reasons for not following good practice here, but it makes things a little scary when when updating nevertheless ;)

**Comment by Donnerbart** [comment] 2015-06-21 16:48
`hazelcast:maintenance-3.x` looks like the 3.5.1 branch, but I cannot say this for sure. I also have no information when the 3.5.1 release is planned. If non of my colleagues answer this today, just poke us again during the week.

**Comment by gurbuzali** [comment] 2015-06-21 16:54
@purplefox 3.5 has the fix, https://github.com/hazelcast/hazelcast/pull/5285

**Comment by purplefox** [comment] 2015-06-21 17:00
Ok thanks Ali, I was looking for the same commit in the 3.5 tag but couldn't see it, but I see now you applied the fix as two different commits in different branches.

I'm currently putting 3.5 through our test suite. If it looks good I guess we just use that.
