### ISSUE TITLE
SQL SINK handling of JSON with whitespace

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#21303] opened 2022-04-23 10:51 UTC
**Describe the bug**
`SINK INTO` gives incorrect results for `HazelcastJsonValue` where whitespace is involved

**Expected behavior**
`SINK INTO` should find matching keys based on fields rather than the full representation.

**To Reproduce**
```
public class Application {
	private static final String SOURCE_MAP = "source";
	private static final String SINK_MAP = "sink";

	public static void main(String[] args) throws Exception {
		Config config = new Config();
		config.getJetConfig().setEnabled(true);
		
		HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);

		for (String mapName : List.of(SOURCE_MAP, SINK_MAP)) {
			String mapping = "CREATE MAPPING " + mapName
                    + " ("
                    + "    \"firstname\" VARCHAR EXTERNAL NAME \"__key.firstname\","
                    + "    \"lastname\" VARCHAR EXTERNAL NAME \"__key.lastname\","
                    + "    \"this\" BIGINT"
                    + ")"
    				+ " TYPE IMap "
                    + " OPTIONS ( "
    		        + " 'keyFormat' = 'json-flat',"
    		        + " 'valueFormat' = 'java',"
    		        + " 'valueJavaClass' = '" + Long.class.getName() + "'"
                    + " )";
    		hazelcastInstance.getSql().execute(mapping);
		}

		String key = "{ \"firstname\": \"John\", \"lastname\": \"Doe\" }"; 
		hazelcastInstance.getMap(SOURCE_MAP).set(new HazelcastJsonValue(key), System.currentTimeMillis());
		hazelcastInstance.getMap(SINK_MAP).set(new HazelcastJsonValue(key), System.currentTimeMillis());
		
		hazelcastInstance.getSql().execute("SINK INTO " + SINK_MAP + " SELECT * FROM " + SOURCE_MAP);
		hazelcastInstance.getSql().execute("SINK INTO " + SINK_MAP + " SELECT firstname, lastname, this FROM " + SOURCE_MAP);
		
		for (String mapName : List.of(SOURCE_MAP, SINK_MAP)) {
			IMap<HazelcastJsonValue, Integer> m = hazelcastInstance.getMap(mapName);
			System.out.printf("'%s'.size()==%d%n", m.getName(), m.size());
			m.keySet().forEach(System.out::println);
		}
		
		hazelcastInstance.shutdown();
	}
}
```

**Additional context**
Tested with `Hazelcast Platform 5.2-SNAPSHOT (20220422 - 5be7255)`
We might equally view the problem here is we hold whitespace in `HazelcastJsonValue`

**Comment by viliam-durina** [comment] 2022-04-25 07:35
Closing this as the root cause is the same as in #21304.

Btw, both of the `SINK .. SELECT` statements are in fact same: the `*` is expanded to all 3 fields. They extract the fields and store them in re-serialized form, without the whitespaces.

**Closed by viliam-durina** 2022-04-25 07:35 UTC
Labels: Type: Defect
