### ISSUE TITLE
NullPointerException ProcessorTasklet.close(ProcessorTasklet.java:629) TopologyChanged member shutdown 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#19368] opened 2021-08-19 11:28 UTC
http://jenkins.hazelcast.com/view/shutdown/job/shutdown-x/68/console

fail HzClient1HZ jobCancle hzcmd.jet.LiteJobAndCancle threadId=1 com.hazelcast.jet.core.TopologyChangedException: Light job coordinator left the cluster 

/disk1/workspace/shutdown-x/5.0-SNAPSHOT/2021_08_19-11_16_38/jet Failed

hz-errors
./output/HZ/HzClient2HZ/exception.txt
./output/HZ/HzClient1HZ/exception.txt

find . -name out.txt | xargs grep Null
./output/HZ/HzMember3HZ/out.txt:java.lang.NullPointerException

```
 cat ./output/HZ/HzMember3HZ/out.txt | grep Null -B10 -A10
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:470)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

Aug 19, 2021 11:18:24 AM com.hazelcast.jet.impl.execution.ExecutionContext
SEVERE: [10.0.0.213]:5701 [HZ] [5.0-SNAPSHOT] job '06ab-c768-2ec9-0001', execution 06ab-c768-2ec9-0001 encountered an exception in Processor.close(), ignoring it
java.lang.NullPointerException
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.close(ProcessorTasklet.java:629)
	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:246)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$559b0d71$1(JobExecutionService.java:524)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:507)
	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:524)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$beginExecution0$14(JobExecutionService.java:572)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
```

**Comment by Danny-Hazelcast** [comment] 2021-08-19 11:42
/disk1/workspace/split-x/5.0-SNAPSHOT/2021_08_19-11_17_20/jet

 find . -name out.txt | xargs grep Null
./output/HZ/HzMember2HZAA/out.txt:java.lang.NullPointerException

```
(base) [ec2-user@ip-10-0-0-252 jet]$ cat ./output/HZ/HzMember2HZAA/out.txt | grep -A10 -B10 Null
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

Aug 19, 2021 11:24:24 AM com.hazelcast.jet.impl.JobExecutionService
INFO: [10.0.0.16]:5701 [HZ] [5.0-SNAPSHOT] Execution plan for jobId=06ab-c791-4187-0002, jobName='06ab-c791-4187-0002', executionId=06ab-c8c7-c448-0003 initialized
Aug 19, 2021 11:24:24 AM com.hazelcast.jet.impl.JobExecutionService
INFO: [10.0.0.16]:5701 [HZ] [5.0-SNAPSHOT] Execution plan for jobId=06ab-c791-4182-0002, jobName='06ab-c791-4182-0002', executionId=06ab-c8c7-c447-0003 initialized
Aug 19, 2021 11:24:24 AM com.hazelcast.jet.impl.JobExecutionService
INFO: [10.0.0.16]:5701 [HZ] [5.0-SNAPSHOT] Execution plan for jobId=06ab-c791-4183-0002, jobName='06ab-c791-4183-0002', executionId=06ab-c8c7-c44a-0003 initialized
Aug 19, 2021 11:24:24 AM com.hazelcast.jet.impl.execution.ExecutionContext
SEVERE: [10.0.0.16]:5701 [HZ] [5.0-SNAPSHOT] job '06ab-c8c7-3309-000a', execution 06ab-c8c7-3309-000a encountered an exception in Processor.close(), ignoring it
java.lang.NullPointerException
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.close(ProcessorTasklet.java:629)
	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:246)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$559b0d71$1(JobExecutionService.java:524)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:507)
	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:524)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$beginExecution0$14(JobExecutionService.java:572)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
```

**Comment by Danny-Hazelcast** [comment] 2021-08-19 11:50
/disk1/workspace/kill-x/5.0-SNAPSHOT/2021_08_19-11_16_11/jet
(base) [ec2-user@ip-10-0-0-252 jet]$ find . -name out.txt | xargs grep -A 10 -B10 Null
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:470)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
./output/HZ/HzMember1HZ/out.txt-
./output/HZ/HzMember1HZ/out.txt-Aug 19, 2021 11:18:36 AM com.hazelcast.jet.impl.execution.ExecutionContext
./output/HZ/HzMember1HZ/out.txt-SEVERE: [10.0.0.205]:5701 [HZ] [5.0-SNAPSHOT] job '06ab-c773-e229-0003', execution 06ab-c773-e229-0003 encountered an exception in Processor.close(), ignoring it
./output/HZ/HzMember1HZ/out.txt:java.lang.NullPointerException
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.jet.impl.execution.ProcessorTasklet.close(ProcessorTasklet.java:629)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:246)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$559b0d71$1(JobExecutionService.java:524)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:507)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:524)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.lambda$beginExecution0$14(JobExecutionService.java:572)
./output/HZ/HzMember1HZ/out.txt-	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
./output/HZ/HzMember1HZ/out.txt-	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
./output/HZ/HzMember1HZ/out.txt-	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)

**Comment by ufukyilmaz** [comment] 2021-09-07 10:42
I can confirm that it is duplicate of the one in #19428.

**Comment by mmedenjak** [comment] 2021-09-07 10:50
Thanks, closing this one then.

**Closed by mmedenjak** 2021-09-07 10:50 UTC
Labels: Type: Defect, Team: Core, Source: Internal, Module: SQL, Module: Jet
