### ISSUE TITLE
hz: 3.11.2--Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: 

### ISSUE THREAD

**Issue by nuriozalp** [hazelcast/hazelcast#14645] opened 2019-03-05 10:52 UTC
Please help for this exception
 pagination query is not working.

```java
//-----model-----


import java.io.IOException;
import java.util.Date;

import com.hazelcast.nio.ObjectDataInput;
import com.hazelcast.nio.ObjectDataOutput;
import com.hazelcast.nio.serialization.DataSerializable;

public class FixtureTotalDto implements DataSerializable{
	private String matchId;
	private int marketId;
	private int sportId;
	private int categoryId;
	private String tournamentId;
	private double totalMatchAmount;
	private double totalUnmacthedAmount;
	private long totalOddCount;
	private long totalMatchedLayCount;
	private long totalMatchedBackCount;
	private long totalUnMatchedLayCount;
	private long totalUnMatchedBackCount;
	private int fixtureType;
	private Date startDate;

	public FixtureTotalDto() {

	}

	public double getTotalMatchAmount() {
		return totalMatchAmount;
	}

	public void setTotalMatchAmount(double totalMatchAmount) {
		this.totalMatchAmount = totalMatchAmount;
	}

	public double getTotalUnmacthedAmount() {
		return totalUnmacthedAmount;
	}

	public void setTotalUnmacthedAmount(double totalUnmacthedAmount) {
		this.totalUnmacthedAmount = totalUnmacthedAmount;
	}

	public long getTotalOddCount() {
		return totalOddCount;
	}

	public void setTotalOddCount(long totalOddCount) {
		this.totalOddCount = totalOddCount;
	}

	public long getTotalMatchedLayCount() {
		return totalMatchedLayCount;
	}

	public void setTotalMatchedLayCount(long totalMatchedLayCount) {
		this.totalMatchedLayCount = totalMatchedLayCount;
	}

	public long getTotalMatchedBackCount() {
		return totalMatchedBackCount;
	}

	public void setTotalMatchedBackCount(long totalMatchedBackCount) {
		this.totalMatchedBackCount = totalMatchedBackCount;
	}

	public long getTotalUnMatchedLayCount() {
		return totalUnMatchedLayCount;
	}

	public void setTotalUnMatchedLayCount(long totalUnMatchedLayCount) {
		this.totalUnMatchedLayCount = totalUnMatchedLayCount;
	}

	public long getTotalUnMatchedBackCount() {
		return totalUnMatchedBackCount;
	}

	public void setTotalUnMatchedBackCount(long totalUnMatchedBackCount) {
		this.totalUnMatchedBackCount = totalUnMatchedBackCount;
	}

	public int getSportId() {
		return sportId;
	}

	public void setSportId(int sportId) {
		this.sportId = sportId;
	}

	public int getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public int getFixtureType() {
		return fixtureType;
	}

	public void setFixtureType(int fixtureType) {
		this.fixtureType = fixtureType;
	}

	public String getMatchId() {
		return matchId;
	}

	public void setMatchId(String matchId) {
		this.matchId = matchId;
	}

	public String getTournamentId() {
		return tournamentId;
	}

	public void setTournamentId(String tournamentId) {
		this.tournamentId = tournamentId;
	}

	public int getMarketId() {
		return marketId;
	}

	public void setMarketId(int marketId) {
		this.marketId = marketId;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public void writeData(ObjectDataOutput out) throws IOException {
		out.writeUTF(matchId);
		out.writeInt(marketId);
		out.writeInt(sportId);
		out.writeInt(categoryId);
		out.writeUTF(tournamentId);
		out.writeDouble(totalMatchAmount);
		out.writeDouble(totalUnmacthedAmount);
		out.writeInt(fixtureType);
		out.writeLong(totalOddCount);
		out.writeLong(totalMatchedLayCount);
		out.writeLong(totalMatchedBackCount);
		out.writeLong(totalUnMatchedLayCount);
		out.writeLong(totalUnMatchedBackCount);
		out.writeLong(startDate.getTime());
	}

	@Override
	public void readData(ObjectDataInput in) throws IOException {

		matchId = in.readUTF();
		marketId = in.readInt();
		sportId = in.readInt();
		categoryId = in.readInt();
		tournamentId = in.readUTF();
		totalMatchAmount = in.readDouble();
		totalUnmacthedAmount = in.readDouble();
		fixtureType = in.readInt();
		totalOddCount = in.readLong();
		totalMatchedLayCount = in.readLong();
		totalMatchedBackCount = in.readLong();
		totalUnMatchedLayCount = in.readLong();
		totalUnMatchedBackCount = in.readLong();
		startDate = new Date(in.readLong());

	}
}
//---------------------query service-------------------------------------
String marketInSql = " marketId IN ('" + StringUtils.join(defaultAllMarketList.toArray(), ",").replace(",", "','") + "')";

Predicate marketIdPredict = new SqlPredicate(marketInSql);
		
Predicate totalUnmacthedAmountPredict = Predicates.greaterThan("totalUnmacthedAmount", 0);
 
 Predicate startTimePredict = Predicates.greaterThan("startDate", new Date());
Predicate<FixtureTotalKey, FixtureTotalDto> fullPredicate = Predicates.and(totalUnmacthedAmountPredict, marketIdPredict, startTimePredict);
 
		Comparator<Map.Entry<FixtureTotalKey, FixtureTotalDto>> descendingComparator = new DescendingUmmactchedComparator();

		PagingPredicate pagingPredicate = new PagingPredicate(fullPredicate, descendingComparator,10);
		pagingPredicate.setPage(0);
		Collection<FixtureTotalDto> list = fixtureTotalMap.values(pagingPredicate);


//--------------------------------------------------------------------------------------------------------------

public class DescendingUmmactchedComparator implements Serializable, Comparator<Map.Entry<FixtureTotalKey, FixtureTotalDto>> {
 
	@Override
	public int compare(Map.Entry<FixtureTotalKey, FixtureTotalDto> e1, Map.Entry<FixtureTotalKey, FixtureTotalDto> e2) {

		FixtureTotalDto s1 = (FixtureTotalDto) e1.getValue();
		FixtureTotalDto s2 = (FixtureTotalDto) e2.getValue();
		return (int) (s2.getTotalUnmacthedAmount() - s1.getTotalUnmacthedAmount());

	}

}


//-------------------------------------------------exception--------------------------------------------------
at com.betex.BetexFixtureServiceApplication.main(BetexFixtureServiceApplication.java:17)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.betex.repository.DescendingUmmactchedComparator
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:86)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:75)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574)
	at com.hazelcast.query.PagingPredicate.readData(PagingPredicate.java:356)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
	at com.hazelcast.client.impl.protocol.task.map.MapValuesWithPagingPredicateMessageTask.getPredicate(MapValuesWithPagingPredicateMessageTask.java:51)
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.call(AbstractMapQueryMessageTask.java:89)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.doRun(AbstractMessageTask.java:111)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.lang.ClassNotFoundException: com.betex.repository.DescendingUmmactchedComparator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:288)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:252)
	at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:646)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:82)
	... 21 common frames omitted

**Comment by sancar** [comment] 2019-03-05 12:52
Hi @nuriozalp,
You need to put `DescendingUmmactchedComparator` and `FixtureTotalDto`  on the classpath of the server.

**Comment by sancar** [comment] 2019-03-07 12:04
@nuriozalp I am closing the issue since it is a misuse and not a bug. Please post your similar questions on https://groups.google.com/forum/#!forum/hazelcast 
Googlegroup has active responders and you are more likely to get a fast response. We can always open a github issue later when we detect your report on googlegroup caused by a bug on our side.

**Closed by sancar** 2019-03-07 12:04 UTC
Labels: Module: Query, Module: Serialization
