### ISSUE TITLE
[map] [index] memory leak on custom attribute with index?

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#10672] opened 2017-05-30 22:36 UTC
HZ 3.8.2, single node deploy, -Xmx=4G. In one of my tests I populate caches with entities and then perform queries against this data. Usually the whole memory allocated for my test data set is ~700M. On the second test phase some temporary data structures created, but then minor-GCed quickly. Now I specified a custom attribute with extractor and an index on this attribute in one of my caches:
```
<hz:map name="xdm-result" in-memory-format="BINARY" async-backup-count="${bdb.schema.query.backup.async}" 
		 backup-count="${bdb.schema.query.backup.sync}" read-backup-data="${bdb.schema.query.backup.read}"
		 eviction-policy="LRU" time-to-live-seconds="0" max-size-policy="USED_HEAP_PERCENTAGE" 
		 max-size="10">
	<hz:indexes>
		<hz:index attribute="docId"/>
	</hz:indexes>
	<hz:attributes>
		<hz:attribute name="docId" extractor="com.bagri.server.hazelcast.predicate.ResultsQueryExtractor" />
	</hz:attributes>
</hz:map>
```
This cache is actively used on the second (query) test phase. Now the first population phase takes usual time and allocates the same amount of memory. But then on the second phase I see abnormal memory allocation activity, in about a minute it alocates the whole 4G and after that I see periodical major GC every ~10 sec. Investigating memory dump I see a lot of int[] (1.7G) and Object[] (1G) allocated, which are not allocated usually. 

The cache with custom attribute has 41666 enities and pass the same amount of keys to collector. So it is not clear why that custom index takes so much memory.

I do not have a reproducer test, but I can explain how to run this scenario with my project quickly. Please have a look.

Thanks, Denis.

**Comment by tombujok** [comment] 2017-09-12 11:58
@dsukhoroslov A couple of questions:

- does your query use this index? 
- is it an ordered index?
- what kind of query is it (equals, range?)
- how complex is your extractors logic? Does it extract 1 object from one entity, or is it N:1?

**Comment by dsukhoroslov** [comment] 2017-09-12 23:11
Hi @tombujok,

this is the corresponding map config:
```
<hz:map name="xdm-result" in-memory-format="BINARY">
	<hz:indexes>
		<hz:index attribute="docId"/>
	</hz:indexes>
	<hz:attributes>
		<hz:attribute name="docId" extractor="com.bagri.server.hazelcast.predicate.ResultsQueryExtractor" />
	</hz:attributes>
</hz:map>
```
The query is very simple: Predicates.equal("docId", docId), where docId is long. So, the index must be used by the query and it is not ordered.
The extractor extracts many objects from one entry, see the implementation here: [ResultsQueryExtractor.java](https://github.com/dsukhoroslov/bagri/blob/master/bagri-server/bagri-server-hazelcast/src/main/java/com/bagri/server/hazelcast/predicate/ResultsQueryExtractor.java)

**Comment by tombujok** [comment] 2017-09-13 09:42
I don't really see any leak. I run the following test:
https://gist.github.com/tombujok/4356366dcce9f7ca0a0b0290d235045b
I didn't see any difference between the code with and without custom extractor. 
The throughput I got was around 99.8% or 99.9% which is not bad...

The issue is that you need to size your heap accordingly. When I didn't set Xms and just Xmx, the JVM resizes (basically shrinks) the committed space, and thus there's more GC processing going on. 

### No -Xms set
The chart looks like this then in the first two minutes (only -Xmx4g set):
![screenshot_2017-09-13_11-33-24](https://user-images.githubusercontent.com/1047469/30370279-cad477f6-987f-11e7-9ab6-591578bb3332.png)

Here's also the GCViewer chart (not necessarily matching the upper one - I'm just pasted one to show the trend in the first two minutes):
<img width="767" alt="screen shot 2017-09-13 at 08 30 56" src="https://user-images.githubusercontent.com/1047469/30370537-98152f4e-9880-11e7-8a24-d2899b8ce548.png">


### -Xms and -Xmx set to the same value of 4g

If you start your JVM with -Xms4g -Xmx4g you can see that everything looks pretty much healthy.
This is the test run with custom extractor, indexes, and eviction with Xmx==Xms==4g
You can see that the chart is different than the previous one:
<img width="1095" alt="screen shot 2017-09-13 at 12 37 19" src="https://user-images.githubusercontent.com/1047469/30370464-5bb9ca5a-9880-11e7-9371-13d17828ceba.png">



Here's also the GCViewer chart:

<img width="1416" alt="screen shot 2017-09-13 at 12 35 53" src="https://user-images.githubusercontent.com/1047469/30370414-310cb75e-9880-11e7-876c-84fb6148d591.png">


Feel free to experiment more and see reopen if there's some more findings on your side. Would be good to have a reproducer based on the gist I pasted in the case you find sth.

I run the test with the following switches, also doing the recording with a custom profile to cover the memory allocation etc.
```
-Xms4G
-Xmx4G
-Xloggc:gc.log
-XX:+PrintGC
-XX:+PrintGCDetails
-XX:+PrintGCTimeStamps
-XX:+PrintGCDateStamps
-XX:+PrintTenuringDistribution
-XX:+UnlockCommercialFeatures
-XX:+FlightRecorder
-XX:StartFlightRecording=duration=3600s,filename=recording.jfr,settings=profile
-XX:+UnlockDiagnosticVMOptions
-XX:+DebugNonSafepoints
```

**Closed by tombujok** 2017-09-13 09:42 UTC
Labels: Team: Core, Type: Defect
