### ISSUE TITLE
com.hazelcast.jet.sql_slow.ComparisonPredicateIntegrationSlowTest

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20182] opened 2021-12-13 18:18 UTC
_master_ (commit f32cb642bee7191c7769876a00b5e1b78f1762cf)

Failed on IBM Jdk8, fips: [failure report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/366/testReport/com.hazelcast.jet.sql_slow/ComparisonPredicateIntegrationSlowTest/com_hazelcast_jet_sql_slow_ComparisonPredicateIntegrationSlowTest/)

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='sad_khorana', node=[127.0.0.1]:5857}]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:46)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testBoolean[mode:GTE] in 0.129 seconds.
07:27:00,670  INFO || - [SimpleTestInClusterSupport] Time-limited test - Terminating instance factory in SimpleTestInClusterSupport.@AfterClass
07:27:00,670  INFO || - [LifecycleService] Thread-470 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
07:27:00,670  WARN || - [Node] Thread-470 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Terminating forcefully...
07:27:00,670  INFO || - [Node] Thread-470 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
07:27:00,670  INFO || - [Node] Thread-470 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down node engine...
07:27:00,672  INFO || - [NodeExtension] Thread-470 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
07:27:00,672  INFO || - [Node] Thread-470 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
07:27:00,672  INFO || - [LifecycleService] Thread-470 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
07:27:00,672  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5857 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5857 is SHUTTING_DOWN
07:27:00,672 DEBUG || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5857 [dev] [5.1-SNAPSHOT] Added a shutting-down member: 380ffc98-02dd-49d7-92c9-2cec02685a0e
07:27:00,672  INFO || - [Node] Time-limited test - [127.0.0.1]:5857 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
07:27:00,672  INFO || - [Node] Time-limited test - [127.0.0.1]:5857 [dev] [5.1-SNAPSHOT] Shutting down node engine...
07:27:00,673  INFO || - [NodeExtension] Time-limited test - [127.0.0.1]:5857 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
07:27:00,673  INFO || - [Node] Time-limited test - [127.0.0.1]:5857 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 1 ms.
07:27:00,673  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5857 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5857 is SHUTDOWN
```

</details>

**Comment by viliam-durina** [comment] 2022-01-25 14:51
Possibly a duplicate of #19638

**Closed** 2022-02-02 10:20 UTC
Labels: Type: Test-Failure, Priority: Low, Source: Internal, Team: SQL
