### ISSUE TITLE
Consider logging new HTTP connections with DEBUG or lower level

### ISSUE THREAD

**Issue by andersenleo** [hazelcast/hazelcast#11196] opened 2017-08-23 07:45 UTC
We're using a custom Hazelcast Discovery Strategy for Hashicorp Consul. We register a health-check with Consul to monitor available nodes - this healthcheck hits the Hazelcast REST endpoint repeatedly.

This results in a lot of

```
2017-08-23 07:05:24,996 [hz.account.IO.thread-Acceptor] INFO  c.h.nio.tcp.SocketAcceptorThread   - [10.132.0.13]:35503 [cluster-name] [3.7.3] Accepting socket connection from /10.132.0.13:43282
```
entries in our log.

Is there a specific reason to log new connections at `INFO` level, or could this changed to a lower logging level?

**Comment by mdogan** [comment] 2017-08-24 13:04
You can set default logging level of `c.h.nio.tcp.SocketAcceptorThread` to a higher level to suppress new connection logs. For example in log4j2;

```xml
<Logger name="com.hazelcast.nio.tcp.SocketAcceptorThread" level="warning" />
```

**Comment by andersenleo** [comment] 2017-08-24 15:02
That is the work-around we're applying now. However, we've got ~50 microservices with individual logback configurations and would obviously like to avoid patching them all. 

Not a big deal, but if there is no explicit reason for logging with INFO it'd make sense to change it in Hazelcast.

**Comment by jerrinot** [comment] 2017-08-30 13:40
The reason for a rather verbose logging here is in a regular member-to-member communication connections are created/closed rarely. 

Logging this at the INFO level massively helps during troubleshooting. Could you configure Consul to open a single connection and re-using it for health checks whenever possible? 

I am moving this ticket to 3.9.1 as this is not a release blocker.

**Comment by andersenleo** [comment] 2017-08-30 17:33
Unfortunately there's no way to configure Consul to re-use connections for health checks. 

We will have to modify our logging configurations until a future release.

**Comment by mmedenjak** [comment] 2017-09-27 07:08
Duplicate of https://github.com/hazelcast/hazelcast/issues/10924

**Closed by mmedenjak** 2017-09-27 07:09 UTC
Labels: Team: Core, Type: Enhancement
