### ISSUE TITLE
Cannot override cache's CacheManager - possible race condition

### ISSUE THREAD

**Issue by angeletos** [hazelcast/hazelcast#12486] opened 2018-03-03 17:14 UTC
During Tomcat's startup if there is a high load (while requests are being queued by Tomcat) we get the following exception when the cache is initialized. The cacheManager (JCache) is injected to the target object and runtime load time weaving (aspectj).

```java
java.lang.IllegalStateException: Cannot overwrite a Cache's CacheManager.
	at com.hazelcast.cache.impl.AbstractInternalCacheProxy.setCacheManager(AbstractInternalCacheProxy.java:120)
	at com.hazelcast.cache.impl.CacheProxy.setCacheManager(CacheProxy.java:80)
	at com.hazelcast.cache.impl.HazelcastServerCacheManager.createCacheProxy(HazelcastServerCacheManager.java:175)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:251)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:186)
```

The error happens when attempting to retrieve the cache from the autowired cacheManager (JCacheCacheManager) within the target's object constructor. 

```java
        this.myCache = cacheManager.getCacheManager().getCache(
            "my-cache",
            String.class,
            MyClass.class);
```

Hazelcast (embedded) is configured using HZ's Spring namespace as in https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/spring-jcache/src/main/resources/applicationContext.xml and only a single HZ member and client is initialised 

Environment: Java SE 8, Spring 4.3.14, Spring Security, Tomcat 8.5.28, Hazelcast 3.9.2 with Spring extension, JCache 1.0.0., Bucket4J 3.1.1. The issue is also observed with Tomcat 7.

Related: https://github.com/hazelcast/hazelcast/pull/11076

Any advice on how I can resolve this would be much appreciated.

Thanks,
George

**Comment by Holmistr** [comment] 2018-03-05 12:03
Hi @angeletos , thanks for reporting this issue.
@vbekiaris Maybe you can take a look?

**Comment by akinny** [comment] 2018-05-24 17:34
@Holmistr/@vbekiaris is there any update on this issue?

**Comment by vbekiaris** [comment] 2018-05-24 19:43
@akinny it's on my radar for next week, I'll keep you posted

**Comment by vbekiaris** [comment] 2018-07-02 15:29
@angeletos I wasn't able to reproduce the issue. Yet, I see that in `SpringHazelcastCachingProvider#getCacheManager` a new instance of the caching provider is created each time. I would expect this method to be called once on Spring context initialization, but maybe this is not the case under high contention so it might be the cause for the issue you experience. If you have a reproducer, it would be great if you could share (or test with `hazelcast-spring` 3.11-SNAPSHOT built off of this experimental branch https://github.com/vbekiaris/hazelcast/tree/fixes/3.11/spring-race).

**Comment by mmedenjak** [comment] 2018-09-06 15:55
@angeletos any updates on the issue? Are you able to post a simple reproducer?

**Comment by mmedenjak** [comment] 2018-09-17 06:50
Closing the issue due to non-activity. @angeletos please open a new issue with the reproducer or more information or if you encounter a new issue.

**Closed by mmedenjak** 2018-09-17 06:50 UTC
Labels: Module: ICache, Source: Community, Team: Core
