### ISSUE TITLE
When minority of members removed from network,  read/write failures occur on cluster 

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#12240] opened 2018-02-01 19:12 UTC
Cluster information
```
Size: 5
Version: Hazelcast 3.10-SNAPSHOT (20180201 - 31dcc3e)
Client Count: 1
Client Docker : FROM openjdk:8-slim (debian)
Member Docker: FROM openjdk:8-jre (debian)
Client log level: DEBUG [slf4j]
Member log level: ALL [jdk]
```
Steps:

1. Sanity check, wait for initial cluster size to be 5
2. Begin generating traffic from client to cluster 

- 10 Threads with Callables each waits defined timeout (200ms-100ms-50ms) after write->read->test predicate verifications
- Client owner connection is on majority side

3. Remove `hz-3` and `hz-4` from network 
4. wait for cluster size to be 3
5. Tear down

Expected no failure during read/write operations to majority of cluster.
However, occasionally we got read/write failures to cluster.
Logs regarding client/members and configurations attached. Logs are organized according to client side timeouts. However, there is no strong correlation observed with timeouts and failure counts.

Data structures that failures observed are:
```
ISemaphore
ISet
MultiMap
IAtomicLong
```

[Archive.zip](https://github.com/hazelcast/hazelcast/files/1686821/Archive.zip)

**Comment by mmedenjak** [comment] 2018-02-02 07:40
Can you share the link to the test? 
> occasionally we got read/write failures
How do these failures manifest? Does the client get some kind of exception?


Can you also cleanup the client logs, as I see lots of logs unrelated to the client instance, e.g.
```
2018-02-01T18:37:14.146058481Z 18:37:14:145 [qtp1201506992-11] DEBUG HttpConnection - HttpConnection@53bdfcee[p=HttpParser{s=START,0 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200
fe{r=1,c=false,a=IDLE,uri=null}<-SocketChannelEndPoint@4506eebd{/172.22.0.1:56050<->/172.22.0.7:4567,OPEN,fill=-,flush=-,to=9/3600000}{io=0/0,kio=0,kro=1}->HttpConnection@53bdfcee[p=HttpParser{s=START,0
 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200fe{r=1,c=false,a=IDLE,uri=null} parsed false HttpParser{s=START,0 of -1}
2018-02-01T18:37:14.146423743Z 18:37:14:146 [qtp1201506992-11] DEBUG HttpConnection - releaseRequestBuffer HttpConnection@53bdfcee[p=HttpParser{s=START,0 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200fe{r=1,c=false,a=IDLE,uri=null}<-SocketChannelEndPoint@4506eebd{/172.22.0.1:56050<->/172.22.0.7:4567,OPEN,fill=-,flush=-,to=10/3600000}{io=0/0,kio=0,kro=1}->HttpConnection@53bdfcee[p=HttpParser{s=START,0 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200fe{r=1,c=false,a=IDLE,uri=null}
2018-02-01T18:37:14.146783361Z 18:37:14:146 [qtp1201506992-11] DEBUG AbstractConnection - fillInterested HttpConnection@53bdfcee[p=HttpParser{s=START,0 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200fe{r=1,c=false,a=IDLE,uri=null}<-SocketChannelEndPoint@4506eebd{/172.22.0.1:56050<->/172.22.0.7:4567,OPEN,fill=-,flush=-,to=10/3600000}{io=0/0,kio=0,kro=1}->HttpConnection@53bdfcee[p=HttpParser{s=START,0 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200fe{r=1,c=false,a=IDLE,uri=null}
2018-02-01T18:37:14.147534295Z 18:37:14:147 [qtp1201506992-11] DEBUG FillInterest - FillInterest@522d6bf0{true,AC.ReadCB@53bdfcee{HttpConnection@53bdfcee[p=HttpParser{s=START,0 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200fe{r=1,c=false,a=IDLE,uri=null}<-SocketChannelEndPoint@4506eebd{/172.22.0.1:56050<->/172.22.0.7:4567,OPEN,fill=FI,flush=-,to=0/3600000}{io=0/0,kio=0,kro=1}->HttpConnection@53bdfcee[p=HttpParser{s=START,0 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200fe{r=1,c=false,a=IDLE,uri=null}}} register AC.ReadCB@53bdfcee{HttpConnection@53bdfcee[p=HttpParser{s=START,0 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200fe{r=1,c=false,a=IDLE,uri=null}<-SocketChannelEndPoint@4506eebd{/172.22.0.1:56050<->/172.22.0.7:4567,OPEN,fill=FI,flush=-,to=1/3600000}{io=0/0,kio=0,kro=1}->HttpConnection@53bdfcee[p=HttpParser{s=START,0 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200fe{r=1,c=false,a=IDLE,uri=null}}
2018-02-01T18:37:14.148006009Z 18:37:14:147 [qtp1201506992-11] DEBUG ChannelEndPoint - changeInterests p=false 0->1 for SocketChannelEndPoint@4506eebd{/172.22.0.1:56050<->/172.22.0.7:4567,OPEN,fill=FI,flush=-,to=1/3600000}{io=0/1,kio=0,kro=1}->HttpConnection@53bdfcee[p=HttpParser{s=START,0 of -1},g=HttpGenerator@74cf1af2{s=START}]=>HttpChannelOverHttp@3f0200fe{r=1,c=false,a=IDLE,uri=null}
```

**Comment by lazerion** [comment] 2018-02-02 09:10
@mmedenjak thanks for the reply.


Test repo can be found [here](https://github.com/lazerion/hz-quorum-it) 
Predicates are build in [this builder](https://github.com/lazerion/hz-quorum-it/blob/master/quorumitclient/src/main/java/com/hazelcast/quorum/it/client/FixtureBuilder.java#L117)
Predicates tested in [this callable](https://github.com/lazerion/hz-quorum-it/blob/master/quorumitclient/src/main/java/com/hazelcast/quorum/it/client/QuorumTask.java#L21)

For each data structure that we built there are simple predicate functions that we verify in `QuorumTask` executions. All data structures are called from an executor service, and therefore, predicates tested in parallel. 

I attached logs for a newer another run that has `IAtomicLong` failures that are reported on `client side`, this time client logs are cleared from noise, and only `com.hazelcast` package has `debug` level. Members log properties are same as before.

[predicate-fails-50ms-2.zip](https://github.com/hazelcast/hazelcast/files/1688661/predicate-fails-50ms-2.zip)

**Comment by lazerion** [comment] 2018-02-12 07:01
Test code repo transfered to https://github.com/hazelcast/hazelcast-qe

**Comment by mmedenjak** [comment] 2018-02-14 14:10
So when it says 
```
2018-02-02T08:55:41.951071809Z 08:55:41:950 [pool-1-thread-6] WARN QuorumTask - com.hazelcast.core.IAtomicLong write fails
2018-02-02T08:55:41.952340493Z 08:55:41:951 [pool-1-thread-6] WARN QuorumTask - com.hazelcast.core.IAtomicLong read fails
2018-02-02T08:55:41.953772932Z 08:55:41:953 [pool-1-thread-6] WARN QuorumTask - com.hazelcast.core.IAtomicLong test fails
```
It means these checks have failed?
```
return QuorumTask.builder()
                .write(it -> atomicLong.incrementAndGet() > 0)
                .read(it -> atomicLong.get() > 0)
                .test(it -> atomicLong.decrementAndGet() == 0)
```
And this is using just one atomic long? 
`final IAtomicLong atomicLong = client.getAtomicLong("default");`

Where is the test code?

**Comment by lazerion** [comment] 2018-02-14 18:29
@mmedenjak added [documentation](https://github.com/hazelcast/hazelcast-qe/blob/master/it/quorum/README.md) for suite.

Regarding your question `yes`.

**Comment by mmedenjak** [comment] 2018-02-14 18:32
Where can I see which test exactly is failing in this issue? There are several of them in `AcceptanceTest`.

**Comment by lazerion** [comment] 2018-02-14 18:34
@mmedenjak you can find it [here](https://github.com/hazelcast/hazelcast-qe/blob/master/it/quorum/quorumitrunner/src/test/java/com/hazelcast/quorum/it/runner/AcceptanceTest.java#L188).

**Comment by mmedenjak** [comment] 2018-02-14 18:38
Can you always add this to the issue description when creating the github issue so the test code is easy to find for someone analysing the failure?

**Comment by metanet** [comment] 2018-03-07 14:24
I have analyzed this failure. For instance, the following code shows how IAtomicLong is tested:

```
    private QuorumTask.QuorumTaskBuilder atomicLong() {
        final IAtomicLong atomicLong = client.getAtomicLong("default");
        atomicLong.set(0);
        return QuorumTask.builder()
                .write(it -> atomicLong.incrementAndGet() > 0)
                .read(it -> atomicLong.get() > 0)
                .test(it -> atomicLong.decrementAndGet() == 0)
                .name(IAtomicLong.class.getName());
    }
```

The client first performs the write -> read -> test loop on the cluster and excepts all steps to return `true` all the time, including the time period where it talks to majority sub-cluster after the split. However, our current replication mechanism is async replication. If the target partition is not owned by a node that will fall into the majority sub-cluster, this can fail because of the mutations either in the write() or test() steps.

For quorum tests, I think we should only test two scenarios:
- do we get a quorum exception when we have a sufficiently large cluster and we shouldn't get the exception?
- do we get a quorum exception when we lose fall below required number of nodes?

@lazerion confirmed that we already have tests for both of these scenarios. Any other correctness test is possibly irrelevant for now. 

I am proposing two options. We can either close this issue or move it to the 3.11. Once we have raft impl behind atomic data structures, we can make proper correctness tests for these stuff. 

cc @jerrinot @mdogan @mmedenjak

**Comment by mmedenjak** [comment] 2018-03-08 07:21
I vote to close it. Once we have our raft impl, we will have a separate test suite for it.

@lazerion can you adapt the tests to work as Basri suggested?

**Comment by lazerion** [comment] 2018-03-08 08:28
@mmedenjak done.

**Comment by metanet** [comment] 2018-03-08 08:28
Closing the issue then. Thx guys

**Closed by metanet** 2018-03-08 08:28 UTC
Labels: Estimation: S, Interface: IAtomicLong, Interface: ISemaphore, Interface: ISet, Interface: MultiMap, Source: Internal, Team: Client
