### ISSUE TITLE
Cluster merge doesn't start in some cases [HZ-1175]

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#18661] opened 2021-05-10 15:23 UTC
During playing around PR #18591 I realized the cluster merge doesn't work in some cases.

The use-case is the following. There is a "master" node that doesn't know the addresses of the other two members. If the other members start before the "master", then the cluster merge doesn't properly kick in after the configured "merge delay".

**Reproducer**
```java
import java.util.concurrent.TimeUnit;

import com.hazelcast.config.Config;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.NetworkConfig;
import com.hazelcast.config.TcpIpConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.instance.impl.HazelcastInstanceFactory;

public class App {

    public static void main(String[] args) throws Exception {
        try {
            HazelcastInstance hz2 = Hazelcast.newHazelcastInstance(createConfig(5801, 5701));
            HazelcastInstance hz3 = Hazelcast.newHazelcastInstance(createConfig(5901, 5701, 5801));
            HazelcastInstance master = Hazelcast.newHazelcastInstance(createConfig(5701));
            TimeUnit.SECONDS.sleep(60);
            assertClusterSize(3, master, hz2, hz3);
            System.out.println(">>> OK");
        } finally {
            HazelcastInstanceFactory.terminateAll();
        }
    }

    protected static Config createConfig(int port, int... otherPorts) {
        Config config = new Config().setProperty("hazelcast.member.naming.moby.enabled", "false")
                .setProperty("hazelcast.merge.first.run.delay.seconds", "30")
                .setProperty("hazelcast.merge.next.run.delay.seconds", "20");
        NetworkConfig networkConfig = config.getNetworkConfig();
        networkConfig.setPortAutoIncrement(false).setPort(port);
        JoinConfig join = networkConfig.getJoin();
        join.getAutoDetectionConfig().setEnabled(false);
        join.getMulticastConfig().setEnabled(false);
        TcpIpConfig tcpIpConfig = join.getTcpIpConfig().setEnabled(true).clear().addMember("localhost:" + port);
        for (int otherPort : otherPorts) {
            tcpIpConfig.addMember("localhost:" + otherPort);
        }
        return config;
    }

    public static void assertClusterSize(int expectedSize, HazelcastInstance... instances) {
        for (int i = 0; i < instances.length; i++) {
            int clusterSize = instances[i].getCluster().getMembers().size();
            if (expectedSize != clusterSize) {
                throw new RuntimeException(String.format("Cluster size is not correct. Expected: %d, actual: %d, instance index: %d",
                        expectedSize, clusterSize, i));
            }
        }
    }
}
```

The log file properly contains info about the merge that should happen, but the merge doesn't start.
```
May 10, 2021 5:11:07 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [localhost]:5701 [dev] [4.2] Initialized new cluster connection between /127.0.0.1:5701 and /127.0.0.1:45337
May 10, 2021 5:11:07 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [localhost]:5801 [dev] [4.2] Initialized new cluster connection between /127.0.0.1:45337 and localhost/127.0.0.1:5701
May 10, 2021 5:11:07 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [localhost]:5701 [dev] [4.2] We should merge to [localhost]:5801 because their data member count is bigger than ours [2 > 1]
May 10, 2021 5:11:07 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [localhost]:5801 [dev] [4.2] [localhost]:5701 should merge to us because our data member count is bigger than theirs [2 > 1]
May 10, 2021 5:11:27 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [localhost]:5701 [dev] [4.2] We should merge to [localhost]:5801 because their data member count is bigger than ours [2 > 1]
May 10, 2021 5:11:27 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [localhost]:5801 [dev] [4.2] [localhost]:5701 should merge to us because our data member count is bigger than theirs [2 > 1]
```

**Comment by Holmistr** [comment] 2021-12-14 10:19
Looks like this is actually a duplicate of https://github.com/hazelcast/hazelcast/issues/17490 . @kwart WDYT?
Moving it to 5.2.

**Comment by kwart** [comment] 2022-01-31 09:18
> Looks like this is actually a duplicate of #17490 . @kwart WDYT?
> Moving it to 5.2.

It's surely related to the #17490, another one with the same or similar root cause is the #20331

**Comment by AyberkSorgun** [comment] 2022-08-10 11:58
https://github.com/hazelcast/hazelcast/pull/21552 https://github.com/hazelcast/hazelcast-enterprise/pull/5055

**Closed** 2022-08-10 12:00 UTC
Labels: Type: Defect, Team: Core, Source: Internal, Module: Network I/O, Module: Cluster, to-jira

**Comment by sasha170261** [comment] 2023-10-08 08:25
I use 5.3.1 version but the issue is still here

**Comment by sasha170261** [comment] 2023-11-01 11:00
Hi, 
We use hazelcast 5.3.1 version but the issue is still here.

26 07:49:27,133 [hz.trusting_gould.priority-generic-operation.thread-0] INFO  c.h.i.c.i.ClusterJoinManager - [10.244.243.91]:5701 [main] [5.3.1] We should merge to [10.244.219.87]:5701 because their data member count is bigger than ours [2 > 1]
26 07:51:27,133 [hz.trusting_gould.priority-generic-operation.thread-0] INFO  c.h.i.c.i.ClusterJoinManager - [10.244.243.91]:5701 [main] [5.3.1] We should merge to [10.244.219.87]:5701 because their data member count is bigger than ours [2 > 1]
26 07:53:27,133 [hz.trusting_gould.generic-operation.thread-0] INFO  c.h.i.c.i.ClusterJoinManager - [10.244.243.91]:5701 [main] [5.3.1] We should merge to [10.244.219.87]:5701 because their data member count is bigger than ours [2 > 1]
26 07:55:27,135 [hz.trusting_gould.priority-generic-operation.thread-0] INFO  c.h.i.c.i.ClusterJoinManager - [10.244.243.91]:5701 [main] [5.3.1] We should merge to [10.244.219.87]:5701 because their data member count is bigger than ours [2 > 1]
