### ISSUE TITLE
SAXParseException: Failed to read schema document 'null'

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10382] opened 2017-04-19 11:17 UTC
```
com.hazelcast.core.HazelcastException: org.xml.sax.SAXParseException: schema_reference.4: Failed to read schema document 'null', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:131)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:384)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:318)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:2541)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:2528)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:1830)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:531)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:556)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:523)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:489)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:224)
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:183)
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:232)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:213)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:206)
	at com.hazelcast.test.TestHazelcastInstanceFactory.initOrCreateConfig(TestHazelcastInstanceFactory.java:317)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:109)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:98)
	at com.hazelcast.map.impl.query.QueryAdvancedTest.testQueryOperationAreNotSentToLiteMembers(QueryAdvancedTest.java:66)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/8373/testReport/junit/com.hazelcast.map.impl.query/QueryAdvancedTest/testQueryOperationAreNotSentToLiteMembers/

I don't think this failure is specific for the test where it occurred, so I created the issue for the exception type, not the test.

**Comment by jerrinot** [comment] 2017-07-06 10:31
it has not happened since April. I believe it was caused by a build configuration.

**Comment by mmedenjak** [comment] 2017-07-07 10:03
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9712/

Appears on com.hazelcast.map.impl.operation.PostJoinMapOperationTest.*

**Comment by jerrinot** [comment] 2017-07-21 15:33
fixed by https://github.com/hazelcast/hazelcast/pull/10903

**Closed by jerrinot** 2017-07-21 15:33 UTC
Labels: Type: Test-Failure
