### ISSUE TITLE
Could not start enterprise version 3.12.6 with JDK 11.0.5

### ISSUE THREAD

**Issue by haixiliu** [hazelcast/hazelcast#16656] opened 2020-02-13 16:50 UTC
**Describe the bug**
Could not start hazelcast enterprise version 3.12.6 when executing start.sh. 
JDK version is 11.0.5 Oracle
OS: CentOS 7

**Expected behavior**
Server should start.

**To Reproduce**

1. unzip the hazelcast-enterprise-3.12.6.tar.gz file to desired location
2. run bin/start.sh

**Additional context**

Error showing below
11:38:45 [main] INFO  com.hazelcast.instance.NodeExtension - [172.20.2.101]:5701 [perf-group] [3.12.6] Destroying node NodeExtension.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.hazelcast.memory.FreeMemoryChecker.checkFreeMemory(FreeMemoryChecker.java:50)
        at com.hazelcast.memory.PoolingMemoryManager.<init>(PoolingMemoryManager.java:88)
        at com.hazelcast.instance.EnterpriseNodeExtension.createMemoryManager(EnterpriseNodeExtension.java:563)
        at com.hazelcast.instance.EnterpriseNodeExtension.beforeStart(EnterpriseNodeExtension.java:201)
        at com.hazelcast.instance.Node.<init>(Node.java:238)
        at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:161)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:229)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:208)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:158)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
        at com.hazelcast.core.server.StartServer.main(StartServer.java:46)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @57c03d88
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
        at com.hazelcast.util.OperatingSystemMXBeanSupport.readLongAttribute(OperatingSystemMXBeanSupport.java:72)
        at com.hazelcast.memory.MemoryStatsSupport.<clinit>(MemoryStatsSupport.java:26)
        ... 12 more

I checked history of com.hazelcast.util.OperatingSystemMXBeanSupport, and it seems a commit on 11/2/2019 (https://github.com/hazelcast/hazelcast/commit/98e2555c9da3c4fdb845d5fe9e6a57ed86e68dcc#diff-c47a6602690aa6ed100b4e3a054a8279) removed a check of

           if (!Modifier.isPublic(method.getModifiers())) {

which caused the invocation of this method for MemoryStatsSupport.TOTAL_PHYSICAL_MEMORY to result in error.

**Comment by nfrankel** [comment] 2020-02-13 16:54
Thanks for your interest in Hazelcast!

I believe the reason for that behavior is the usage of a JDK 9+ without the proper module configuration.

Could you please start the java process with the following parameters?

`--add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED`

**Comment by haixiliu** [comment] 2020-02-13 18:09
I tried the above suggestion and it worked. Hazelcast server was able to start.

I filed this ticket because hazelcast server worked fine for me in 3.12.4 until upgraded to 3.12.6.

Are the above module configuration always recommended when running with JDK9+? I must have missed it if they are included in the Hazelcast Manual. Could  you point me to where to find these recommendations? While on this topic, are there any other recommendations I should be aware of?

Thank you.

**Comment by nfrankel** [comment] 2020-02-13 21:30
> I tried the above suggestion and it worked. Hazelcast server was able to start.

That's great!

> I filed this ticket because hazelcast server worked fine for me in 3.12.4 until upgraded to 3.12.6.

I'm not sure about this. I think the root cause is the upgrade to a newer JDK version that implements the Module system.

> Are the above module configuration always recommended when running with JDK9+? I must have missed it if they are included in the Hazelcast Manual. Could you point me to where to find these recommendations?

If you start Hazelcast without those parameters in a JDK9+, the console log should be riddled with stacktraces. The main information message is the following:

----
WARNING: Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
----

Closing this now.

**Closed by nfrankel** 2020-02-13 21:30 UTC
Labels: Source: Community, Type: Defect, Type: Question

**Comment by mmedenjak** [comment] 2020-02-18 12:55
There are some recommendations about running on JDK9+ here: https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#running-in-modular-java
