### ISSUE TITLE
SelectNow_TcpIpConnection_TransferStressTest.testLargePackets

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7393] opened 2016-01-25 08:13 UTC
```
java.lang.AssertionError: expected:<194583> but was:<188371>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest$1.run(TcpIpConnection_TransferStressBaseTest.java:98)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:850)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:864)
    at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.test(TcpIpConnection_TransferStressBaseTest.java:95)
    at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.testLargePackets(TcpIpConnection_TransferStressBaseTest.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
    at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/739/testReport/junit/com.hazelcast.nio.tcp.nonblocking/SelectNow_TcpIpConnection_TransferStressTest/testLargePackets/

**Comment by serkan-ozal** [comment] 2016-01-25 08:25
I will backport this PR https://github.com/hazelcast/hazelcast/pull/7378 to maintenance branch also

**Comment by serkan-ozal** [comment] 2016-01-26 08:10
Fixed via https://github.com/hazelcast/hazelcast/pull/7396

**Comment by hasancelik** [comment] 2016-06-09 07:18
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:280)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:892)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.testPackets(TcpIpConnection_TransferStressBaseTest.java:101)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.testLargePackets(TcpIpConnection_TransferStressBaseTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/978/testReport/junit/com.hazelcast.nio.tcp.nonblocking/SelectNow_TcpIpConnection_TransferStressTest/testLargePackets/

**Comment by serkan-ozal** [comment] 2016-06-29 07:01
no log available and has not failed since long time. so closing this one.

**Comment by hasancelik** [comment] 2017-03-13 11:40
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:261)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:975)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.testPackets(TcpIpConnection_TransferStressBaseTest.java:119)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.testLargePackets(TcpIpConnection_TransferStressBaseTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1275/testReport/junit/com.hazelcast.internal.networking.nonblocking/SelectNow_TcpIpConnection_TransferStressTest/testLargePackets/

**Comment by Donnerbart** [comment] 2017-06-12 09:01
Should be a duplicate of https://github.com/hazelcast/hazelcast/issues/10660

**Closed by Donnerbart** 2017-06-12 09:01 UTC
Labels: Team: Core, Type: Test-Failure
