### ISSUE TITLE
Hazelcast not closing socket connections

### ISSUE THREAD

**Issue by vishal7038** [hazelcast/hazelcast#8713] opened 2016-08-14 06:39 UTC
Hi,
I am using Hazelcast-3.5 with Spring. I am having cluster configuration for all the Hazelcast. I am using programmatic configuration as follows:

```java
Config config = new Config("dev_instance");
        config.getGroupConfig().setName("dev").setPassword("dev-password");
        config.setProperty("hazelcast.client.invocation.timeout.seconds", "40");
        config.setProperty("hazelcast.client.shuffle.member.list", "true");
        config.setProperty("hazelcast.health.monitoring.level", "SILENT");
        config.setProperty("hazelcast.socket.connect.timeout.seconds", "5");
        config.setProperty("hazelcast.socket.server.bind.any", "false");
        config.setProperty("hazelcast.socket.bind.any", "false");
        config.setProperty("hazelcast.version.check.enabled", "false");

        config.getNetworkConfig().setJoin(prepareJoinConfig(config.getNetworkConfig().getJoin()));
        config.getNetworkConfig().getInterfaces().setEnabled(true);
        config.getNetworkConfig().getInterfaces().addInterface("192.168.1.2");
        config.getNetworkConfig().getInterfaces().addInterface("192.168.1.3");
        config.getNetworkConfig().getInterfaces().addInterface("192.168.1.4");
        config.getNetworkConfig().getInterfaces().addInterface("192.168.1.5");
        config.getNetworkConfig().setPortAutoIncrement(true);
        config.getNetworkConfig().setPort("5701");
        config.getNetworkConfig().setPortCount(5);
        config.getNetworkConfig().addOutboundPortDefinition("5702-5707");
        config.getNetworkConfig().setReuseAddress(true);
        config.getTcpIpConfig().setEnabled(true);
        config.getTcpIpConfig().addMember("192.168.1.2");
        config.getTcpIpConfig().addMember("192.168.1.3");
        config.getTcpIpConfig().addMember("192.168.1.4");
        config.getTcpIpConfig().addMember("192.168.1.5");
        config.getMulticastConfig().setEnabled(false);
        config.getTcpIpConfig().setConnectionTimeoutSeconds(5);

MapConfig mapCacheConfig = new MapConfig("dev_instance").setAsyncBackupCount(0).setBackupCount(1)
                .setInMemoryFormat(InMemoryFormat.OBJECT).setEvictionPercentage(25)
    .setEvictionPolicy(EvictionPolicy.LRU).setTimeToLiveSeconds(TTLSeconds).setMaxIdleSeconds(TTLSeconds).setMergePolicy("com.hazelcast.map.merge.PassThroughMergePolicy");
config.addMapConfig(mapCacheConfig);
```

The same set of configuration deployed for every node. When I start the servers i am getting logs as follows:

```
[com.hazelcast.instance.DefaultAddressPicker] (ServerService Thread Pool -- 59) [LOCAL] [dev] [3.5] Interfaces is enabled, trying to pick one address matching to one of: [192.168.1.5, 192.168.1.4, 192.168.1.3, 192.168.1.2]
[com.hazelcast.instance.DefaultAddressPicker] (ServerService Thread Pool -- 59) [LOCAL] [dev] [3.5] Prefer IPv4 stack is true.
[com.hazelcast.instance.DefaultAddressPicker] (ServerService Thread Pool -- 59) [LOCAL] [dev] [3.5] Picked Address[192.168.1.3]:5703, using socket ServerSocket[addr=/192.168.1.3,localport=5703], bind any local is false
[com.hazelcast.spi.OperationService] (ServerService Thread Pool -- 59) [192.168.1.3]:5703 [dev] [3.5] Backpressure is disabled
[com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor] (ServerService Thread Pool -- 59) [192.168.1.3]:5703 [dev] [3.5] Starting with 2 generic operation threads and 2 partition operation threads.
[com.hazelcast.system] (ServerService Thread Pool -- 59) [192.168.1.3]:5703 [dev] [3.5] Hazelcast 3.5 (20150617 - 4270dc6) starting at Address[192.168.1.3]:5703
[com.hazelcast.system] (ServerService Thread Pool -- 59) [192.168.1.3]:5703 [dev] [3.5] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved.
[com.hazelcast.instance.Node] (ServerService Thread Pool -- 59) [192.168.1.3]:5703 [dev] [3.5] Creating TcpIpJoiner
[com.hazelcast.core.LifecycleService] (ServerService Thread Pool -- 59) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.3]:5703 is STARTING
[com.hazelcast.nio.tcp.SocketConnector] (cached1) [192.168.1.3]:5703 [dev] [3.5] Connecting to /192.168.1.3:5704, timeout: 5000, bind-any: false
[com.hazelcast.nio.tcp.SocketConnector] (cached3) [192.168.1.3]:5703 [dev] [3.5] Connecting to /192.168.1.2:5703, timeout: 5000, bind-any: false
[com.hazelcast.nio.tcp.SocketConnector] (cached1) [192.168.1.3]:5703 [dev] [3.5] Could not connect to: /192.168.1.3:5704. Reason: SocketException[Connection refused to address /192.168.1.3:5704]
[com.hazelcast.nio.tcp.SocketConnector] (cached2) [192.168.1.3]:5703 [dev] [3.5] Connecting to /192.168.1.2:5704, timeout: 5000, bind-any: false
[com.hazelcast.nio.tcp.SocketConnector] (cached2) [192.168.1.3]:5703 [dev] [3.5] Could not connect to: /192.168.1.2:5704. Reason: SocketException[Connection refused to address /192.168.1.2:5704]
[com.hazelcast.nio.tcp.SocketConnector] (cached4) [192.168.1.3]:5703 [dev] [3.5] Connecting to /192.168.1.3:5702, timeout: 5000, bind-any: false
[com.hazelcast.cluster.impl.TcpIpJoiner] (cached1) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.3]:5704 is added to the blacklist.
[com.hazelcast.cluster.impl.TcpIpJoiner] (cached2) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.2]:5704 is added to the blacklist.
[com.hazelcast.nio.tcp.SocketConnector] (cached2) [192.168.1.3]:5703 [dev] [3.5] Connecting to /192.168.1.2:5702, timeout: 5000, bind-any: false
[com.hazelcast.nio.tcp.SocketConnector] (cached1) [192.168.1.3]:5703 [dev] [3.5] Connecting to /192.168.1.5:5704, timeout: 5000, bind-any: false
[com.hazelcast.nio.tcp.SocketConnector] (cached1) [192.168.1.3]:5703 [dev] [3.5] Could not connect to: /192.168.1.5:5704. Reason: SocketException[Connection refused to address /192.168.1.5:5704]
[com.hazelcast.cluster.impl.TcpIpJoiner] (cached1) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.5]:5704 is added to the blacklist.
[com.hazelcast.nio.tcp.SocketConnector] (cached1) [192.168.1.3]:5703 [dev] [3.5] Connecting to /192.168.1.4:5703, timeout: 5000, bind-any: false
[com.hazelcast.nio.tcp.SocketConnector] (cached1) [192.168.1.3]:5703 [dev] [3.5] Could not connect to: /192.168.1.4:5703. Reason: SocketException[Connection refused to address /192.168.1.4:5703]
[com.hazelcast.cluster.impl.TcpIpJoiner] (cached1) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.4]:5703 is added to the blacklist.
[com.hazelcast.nio.tcp.SocketConnector] (cached1) [192.168.1.3]:5703 [dev] [3.5] Connecting to /192.168.1.5:5703, timeout: 5000, bind-any: false
[com.hazelcast.cluster.impl.TcpIpJoiner] (cached6) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.4]:5702 is added to the blacklist.
[com.hazelcast.cluster.impl.TcpIpJoiner] (cached6) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.5]:5702 is added to the blacklist.
[com.hazelcast.cluster.impl.TcpIpJoiner] (cached6) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.4]:5704 is added to the blacklist.
[com.hazelcast.nio.tcp.TcpIpConnectionManager] (cached4) [192.168.1.3]:5703 [dev] [3.5] Established socket connection between /192.168.1.3:5706
[com.hazelcast.nio.tcp.TcpIpConnectionManager] (cached3) [192.168.1.3]:5703 [dev] [3.5] Established socket connection between /192.168.1.3:5704
[com.hazelcast.nio.tcp.TcpIpConnectionManager] (cached1) [192.168.1.3]:5703 [dev] [3.5] Established socket connection between /192.168.1.3:5707
[com.hazelcast.nio.tcp.TcpIpConnectionManager] (cached2) [192.168.1.3]:5703 [dev] [3.5] Established socket connection between /192.168.1.3:5705
[com.hazelcast.nio.tcp.TcpIpConnection] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-1) [192.168.1.3]:5703 [dev] [3.5] Connection [Address[192.168.1.3]:5702] lost. Reason: Socket explicitly closed
[com.hazelcast.nio.tcp.TcpIpConnection] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-0) [192.168.1.3]:5703 [dev] [3.5] Connection [Address[192.168.1.2]:5702] lost. Reason: Socket explicitly closed
[com.hazelcast.cluster] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-0) [192.168.1.3]:5703 [dev] [3.5] Node could not join cluster at node: Address[192.168.1.2]:5702 Cause: the target cluster has a different group-name
[com.hazelcast.cluster.impl.TcpIpJoiner] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-0) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.2]:5702 is added to the blacklist.
[com.hazelcast.cluster] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-1) [192.168.1.3]:5703 [dev] [3.5] Node could not join cluster at node: Address[192.168.1.3]:5702 Cause: the target cluster has a different group-name
[com.hazelcast.cluster.impl.TcpIpJoiner] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-1) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.3]:5702 is added to the blacklist.
[com.hazelcast.cluster] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-1) [192.168.1.3]:5703 [dev] [3.5] Node could not join cluster at node: Address[192.168.1.3]:5702 Cause: the target cluster has a different group-name
[com.hazelcast.cluster.impl.TcpIpJoiner] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-1) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.3]:5702 is added to the blacklist.
[com.hazelcast.cluster] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-0) [192.168.1.3]:5703 [dev] [3.5] Node could not join cluster at node: Address[192.168.1.2]:5702 Cause: the target cluster has a different group-name
[com.hazelcast.cluster.impl.TcpIpJoiner] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-0) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.2]:5702 is added to the blacklist.
[com.hazelcast.cluster.ClusterService] (hz.com.mastercard.citi.hce.cache.generic-operation.thread-1) [192.168.1.3]:5703 [dev] [3.5] 

Members [3] {
    Member [192.168.1.2]:5703
    Member [192.168.1.5]:5703
    Member [192.168.1.3]:5703 this
}

[com.hazelcast.core.LifecycleService] (ServerService Thread Pool -- 59) [192.168.1.3]:5703 [dev] [3.5] Address[192.168.1.2]:5703 is STARTED
```

Now when the application is in ideal state for 3-4 days it started throwing "Too many open files" error in Jboss. Although the Linux "uname" configuration is already increased and set to some standard value for all our UAT and PROD environments. Also, there are other projects too deployed on the same nodes and they don't use Hazelcast. Other projects don'e have this error.

Also when i try to check in linux uing open files command :

`lsof -p <pid> | wc -l
`
its values goes beyond 13K.

Also i can see lots of 

> "can't identify protocol"

(ie. nearly more than 100) in 

> lsof -p <pid>

 command. I came to know that hazelcast is constantly trying to open connections but not closing properly, As "can't identify protocol" shouldn't appear for that <pid> of Jboss.

If i disable Hazelcast from my application i don't see this errors.
Can u please suggest :
1. Whether any issue with my hazelcast configuration.
2. Please suggest how do i fine tune hazelcast settings in my PROD environment.
3. Also want to know whether i am getting error because Hazelcast not closing connection properly.

Please help me to narrow down the issue.
Thanks in advance.

**Comment by mmedenjak** [comment] 2017-07-11 18:44
@vishal7038 can you try with hazelcast 3.8? Or can you enable monitoring with the system property "hazelcast.health.monitoring.level" set to "NOISY" and see if the connection count is increasing?

**Comment by mmedenjak** [comment] 2018-08-29 07:12
@vishal7038 any updates on the issue? You can try with hazelcast 3.10 now.

**Comment by mmedenjak** [comment] 2018-09-06 19:38
Can you also try running with enabled diagnostics?
http://docs.hazelcast.org/docs/latest/manual/html-single/#diagnostics

**Comment by mmedenjak** [comment] 2018-09-17 06:47
Closing the issue due to non-activity. @vishal7038 please open a new issue once you have collected the required information or if you encounter a new issue.

**Closed by mmedenjak** 2018-09-17 06:47 UTC
Labels: Module: Network I/O, Source: Community, Team: Core, Type: Defect

**Comment by rccclr** [comment] 2021-12-10 09:55
Hello, the same problem: "to many open files (tcp sockt)" in Hazelcast 4.0.1, with metrics=false and diagnostics=false , any suggestion or workaround? Its possible relation with configuration default: autoIncrementPort = true? Many thanks

**Comment by mmedenjak** [comment] 2021-12-14 13:57
Hi @rccclr , we cannot be sure what's causing the sockets to be open. Can you create a new issue and can you add a reproducer if possible?

**Comment by mmedenjak** [comment] 2021-12-15 08:26
You'll have to figure out when the new sockets are being opened, and for that you'll have to monitor the logs and diagnostics which is why I've suggested that you enable it and look for any patterns or errors. Unfortunately we have tests running for 2 days and clusters running for even longer, and we haven't observed anything like this.

You'll also need to make sure that the HZ process is the one opening the sockets, and not some other process.

As to the deployment question, I was mostly referring to how you deploy it - on premise, on cloud, which cloud, using docker, kubernetes, ...
