### ISSUE TITLE
[scheduled-executor] scheduled executor scheduledFuture.dispose() hanging / not returning

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11265] opened 2017-08-31 07:29 UTC
from https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-All/63/consoleFull

/disk1/jenkins/workspace/stable-All/3.8.5/2017_08_30-08_28_39/executor/scheduled/schedule-dispose-all Failed
http://54.82.84.143/~jenkins/workspace/stable-All/3.8.5/2017_08_30-08_28_39/executor/scheduled/schedule-dispose-all (edited)

output/HZ/HzClient1HZ/timeout

client1 is hanging (edited)

 ```./output/HZ/HzClient1HZ/out.txt:    at hzcmd.executor.scheduled.DisposeAll.timeStep(DisposeAll.java:25)```

https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/executor/scheduled/DisposeAll.java#L25

stack traces have been taken from all jvm's,  700 seconds after the timeStep method should have returned (edited)

also the GC logs show a leak pattern for the members, http://54.82.84.143/~jenkins/workspace/stable-All/3.8.5/2017_08_30-08_28_39/executor/scheduled/schedule-dispose-all/gc.html  but i think this is a known issue in 3.8.5

**Comment by Danny-Hazelcast** [comment] 2017-08-31 07:30
this is a intermittent / infrequent issue

**Comment by Danny-Hazelcast** [comment] 2017-08-31 07:40
poor GC performance is decussed in this issue  https://github.com/hazelcast/hazelcast/issues/11221#issuecomment-325975920

**Comment by Danny-Hazelcast** [comment] 2017-08-31 08:22
also from https://hazelcast-l337.ci.cloudbees.com/view/multi-version/job/multi-version-stable-All/18/consoleFull

a multi version test 

/disk1/jenkins/workspace/multi-version-stable-All/3.8.5/2017_08_30-08_30_32/stable/executor/scheduled/schedule-dispose-all Failed

 http://54.82.84.143/~jenkins/workspace/multi-version-stable-All/3.8.5/2017_08_30-08_30_32/stable/executor/scheduled/schedule-dispose-all

_executor-scheduled_schedule-all_dispose HzClient2HZ timeout=873 running bench
output/HZ/HzClient2HZ/timeout

```
 find . -name out.txt | xargs grep 'at hzcmd'
./output/HZ/HzClient2HZ/out.txt:	at hzcmd.executor.scheduled.DisposeAll.timeStep(DisposeAll.java:25)
```

**Comment by Danny-Hazelcast** [comment] 2017-08-31 08:57
3rd 
https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-xx/79/console

11:50:59 /disk1/jenkins/workspace/stable-xx/3.8.5/2017_08_31-10_33_23/schedule-dispose-all Failed
11:50:59 http://54.82.84.143/~jenkins/workspace/stable-xx/3.8.5/2017_08_31-10_33_23/schedule-dispose-all

11:50:59  _executor-scheduled_schedule-all_dispose HzClient3HZ timeout=307 running bench
11:50:59 output/HZ/HzClient3HZ/timeout

**Comment by Danny-Hazelcast** [comment] 2017-09-08 11:03
4th occurrence
https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-xx/89/console

http://54.82.84.143/~jenkins/workspace/stable-xx/3.9-SNAPSHOT/2017_09_08-13_26_41/schedule-dispose-all 

```
./output/HZ/HzClient3HZ/out.txt:	at hzcmd.executor.scheduled.DisposeAll.timeStep(DisposeAll.java:25)
```

**Comment by tkountis** [comment] 2017-09-09 10:38
Ok this seems to be related with a change we recently did to avoid leaks https://github.com/mmedenjak/hazelcast/commit/24a06fa0d0387810c46be890746bbac8481c0f90 Will need to verify that though. 

@Danny-Hazelcast would you be able to increase the timeout *a lot* and see if that still appears to hang ?

---

The dispose is not really hanging, but its a locked operation and its considered very slow. Calling it from many tasks, it will be dead slow. I believe increasing the timeout, will give you some extra room to breath, but it appears that its not behaving in an ideal way. Bellow the server stacktrace.
```
hz._hzInstance_1_HZ.partition-operation.thread-3" prio=10 tid=0x00007fbee878d000 nid=0xbda runnable [0x00007fbedd477000]
   java.lang.Thread.State: RUNNABLE
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.remove(ScheduledThreadPoolExecutor.java:967)
        at java.util.concurrent.ThreadPoolExecutor.remove(ThreadPoolExecutor.java:1775)
        at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.cancel(LoggingScheduledExecutor.java:169)
        at com.hazelcast.scheduledexecutor.impl.DelegatingScheduledFutureStripper.cancel(DelegatingScheduledFutureStripper.java:59)
        at com.hazelcast.scheduledexecutor.impl.ScheduledTaskDescriptor.cancel(ScheduledTaskDescriptor.java:159)
        at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorContainer.dispose(ScheduledExecutorContainer.java:158)
        at com.hazelcast.scheduledexecutor.impl.operations.DisposeTaskOperation.run(DisposeTaskOperation.java:44)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:405)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:432)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:544)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:529)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:500)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:201)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
        at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:64)
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
```

I will try to investigate the leak that we fixed, and see if we could prevent it with `ThreadPoolExecutor.purge()` method instead.

**Comment by Danny-Hazelcast** [comment] 2017-09-09 11:19
time out is all ready  873 seconds, all most 15mins before we decide to stop

**Comment by Danny-Hazelcast** [comment] 2017-09-25 09:01
/disk1/jenkins/workspace/stable-All/3.9-SNAPSHOT/2017_09_23-11_40_13/executor/scheduled/schedule-dispose-all Failed

http://54.82.84.143/~jenkins/workspace/stable-All/3.9-SNAPSHOT/2017_09_23-11_40_13/executor/scheduled/schedule-dispose-all

output/HZ/HzClient4HZ/timeout

so this time it hanged on the client side

**Comment by tkountis** [comment] 2017-09-26 16:47
Moving to 3.10. This doesn't appear to be caused by the ScheduledExecutor per se, but rather most likely related to client side communication.

**Comment by tkountis** [comment] 2017-10-19 08:28
The task removal known to cause the hanging, has been removed. The test configuration was also modified to meet the capacity expectation, and this is passing now. A 3.10 item has been added to the backlog, to further improve capacity handling on the member side, by having capacity per member rather than per partition.  (see https://github.com/hazelcast/hazelcast/issues/11629)

**Closed by tkountis** 2017-10-19 08:28 UTC
Labels: Team: Core, Type: Defect
