### ISSUE TITLE
AtomicLongStableReadStressTest.testChangingCluster

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14498] opened 2019-02-18 08:00 UTC
_master_ (commit 92ca85687ad1f9cc2057a7cd3b7a27f22bad8019)

Failed on nightly build: http://jenkins.hazelcast.com/job/Hazelcast-3.x-nightly/25/testReport/com.hazelcast.client.stress/AtomicLongStableReadStressTest/testChangingCluster/

Stacktrace:
```
java.lang.AssertionError: com.hazelcast.client.stress.AtomicLongStableReadStressTest$StressThread6 encountered an error expected null, but was:<java.lang.AssertionError: The value for atomic reference: IAtomicLong{name='atomicreference:9533'} was not consistent expected:<9533> but was:<0>>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.client.stress.StressTestSupport$TestThread.assertNoError(StressTestSupport.java:187)
	at com.hazelcast.client.stress.StressTestSupport.assertNoErrors(StressTestSupport.java:138)
	at com.hazelcast.client.stress.StressTestSupport.joinAll(StressTestSupport.java:159)
	at com.hazelcast.client.stress.AtomicLongStableReadStressTest.test(AtomicLongStableReadStressTest.java:88)
	at com.hazelcast.client.stress.AtomicLongStableReadStressTest.testChangingCluster(AtomicLongStableReadStressTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'testChangingCluster(com.hazelcast.client.stress.AtomicLongStableReadStressTest):'
22:42:55, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:00, accumulated pauses: 47 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:43:05, accumulated pauses: 50 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:43:10, accumulated pauses: 52 ms, max pause: 6 ms, pauses over 1000 ms: 0
22:43:15, accumulated pauses: 106 ms, max pause: 55 ms, pauses over 1000 ms: 0
22:43:20, accumulated pauses: 225 ms, max pause: 73 ms, pauses over 1000 ms: 0
22:43:25, accumulated pauses: 183 ms, max pause: 52 ms, pauses over 1000 ms: 0
22:43:30, accumulated pauses: 395 ms, max pause: 106 ms, pauses over 1000 ms: 0
22:43:35, accumulated pauses: 135 ms, max pause: 55 ms, pauses over 1000 ms: 0
22:43:40, accumulated pauses: 137 ms, max pause: 51 ms, pauses over 1000 ms: 0
22:43:45, accumulated pauses: 195 ms, max pause: 49 ms, pauses over 1000 ms: 0
22:43:50, accumulated pauses: 106 ms, max pause: 43 ms, pauses over 1000 ms: 0
22:43:55, accumulated pauses: 105 ms, max pause: 43 ms, pauses over 1000 ms: 0
22:44:00, accumulated pauses: 149 ms, max pause: 44 ms, pauses over 1000 ms: 0
22:44:05, accumulated pauses: 138 ms, max pause: 50 ms, pauses over 1000 ms: 0
22:44:10, accumulated pauses: 110 ms, max pause: 40 ms, pauses over 1000 ms: 0
22:44:15, accumulated pauses: 73 ms, max pause: 27 ms, pauses over 1000 ms: 0
22:44:20, accumulated pauses: 53 ms, max pause: 14 ms, pauses over 1000 ms: 0
22:44:25, accumulated pauses: 57 ms, max pause: 13 ms, pauses over 1000 ms: 0
22:44:30, accumulated pauses: 58 ms, max pause: 14 ms, pauses over 1000 ms: 0
22:44:35, accumulated pauses: 63 ms, max pause: 12 ms, pauses over 1000 ms: 0
22:44:40, accumulated pauses: 58 ms, max pause: 16 ms, pauses over 1000 ms: 0
22:44:45, accumulated pauses: 55 ms, max pause: 13 ms, pauses over 1000 ms: 0
22:44:50, accumulated pauses: 336 ms, max pause: 241 ms, pauses over 1000 ms: 0
22:44:55, accumulated pauses: 39 ms, max pause: 14 ms, pauses over 1000 ms: 0
```

**Comment by taburet** [comment] 2019-02-21 14:34
I was able to identify the commit that is causing the regression: https://github.com/hazelcast/hazelcast/pull/14351. Looks like there is some kind of a "concurrency" issue in the migration logic, so members think they already (still?) own a partition even if the partition is still (already?) empty (partially empty?). That's just a wild guess from simply observing the output of failing tests, cc @mdogan.

To make the test fail more frequently, `StressTestSupport.KILL_DELAY_SECONDS` may be lowered to 1-3 seconds, in that case the test fails like on every third run. There is also an issue with cluster formation on MacOS under old JVMs, running the test under recent JVMs solves this.

**Comment by olukas** [comment] 2019-03-22 07:23
_master_ (commit c9fd2b48bd1834f0a3b1c1a034c0da7800ceee0a)

Failed again on nightly build: http://jenkins.hazelcast.com/job/Hazelcast-3.x-nightly/56/testReport/com.hazelcast.client.stress/AtomicLongStableReadStressTest/testChangingCluster/

Stacktrace:
```
java.lang.AssertionError: com.hazelcast.client.stress.AtomicLongStableReadStressTest$StressThread6 encountered an error expected null, but was:<java.lang.AssertionError: The value for atomic reference: IAtomicLong{name='atomicreference:9418'} was not consistent expected:<9418> but was:<0>>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.client.stress.StressTestSupport$TestThread.assertNoError(StressTestSupport.java:187)
	at com.hazelcast.client.stress.StressTestSupport.assertNoErrors(StressTestSupport.java:138)
	at com.hazelcast.client.stress.StressTestSupport.joinAll(StressTestSupport.java:159)
	at com.hazelcast.client.stress.AtomicLongStableReadStressTest.test(AtomicLongStableReadStressTest.java:88)
	at com.hazelcast.client.stress.AtomicLongStableReadStressTest.testChangingCluster(AtomicLongStableReadStressTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'testChangingCluster(com.hazelcast.client.stress.AtomicLongStableReadStressTest):'
22:49:45, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:49:50, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:49:55, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:50:00, accumulated pauses: 77 ms, max pause: 30 ms, pauses over 1000 ms: 0
22:50:05, accumulated pauses: 47 ms, max pause: 9 ms, pauses over 1000 ms: 0
22:50:10, accumulated pauses: 221 ms, max pause: 62 ms, pauses over 1000 ms: 0
22:50:15, accumulated pauses: 163 ms, max pause: 49 ms, pauses over 1000 ms: 0
22:50:20, accumulated pauses: 322 ms, max pause: 117 ms, pauses over 1000 ms: 0
22:50:25, accumulated pauses: 97 ms, max pause: 38 ms, pauses over 1000 ms: 0
22:50:30, accumulated pauses: 110 ms, max pause: 46 ms, pauses over 1000 ms: 0
22:50:35, accumulated pauses: 153 ms, max pause: 47 ms, pauses over 1000 ms: 0
22:50:40, accumulated pauses: 94 ms, max pause: 34 ms, pauses over 1000 ms: 0
22:50:45, accumulated pauses: 85 ms, max pause: 30 ms, pauses over 1000 ms: 0
22:50:50, accumulated pauses: 183 ms, max pause: 64 ms, pauses over 1000 ms: 0
22:50:55, accumulated pauses: 89 ms, max pause: 27 ms, pauses over 1000 ms: 0
22:51:00, accumulated pauses: 106 ms, max pause: 28 ms, pauses over 1000 ms: 0
22:51:05, accumulated pauses: 45 ms, max pause: 7 ms, pauses over 1000 ms: 0
22:51:10, accumulated pauses: 62 ms, max pause: 12 ms, pauses over 1000 ms: 0
22:51:15, accumulated pauses: 64 ms, max pause: 12 ms, pauses over 1000 ms: 0
22:51:20, accumulated pauses: 42 ms, max pause: 7 ms, pauses over 1000 ms: 0
22:51:25, accumulated pauses: 82 ms, max pause: 15 ms, pauses over 1000 ms: 0
22:51:30, accumulated pauses: 69 ms, max pause: 15 ms, pauses over 1000 ms: 0
22:51:35, accumulated pauses: 62 ms, max pause: 18 ms, pauses over 1000 ms: 0
22:51:40, accumulated pauses: 61 ms, max pause: 15 ms, pauses over 1000 ms: 0
22:51:45, accumulated pauses: 99 ms, max pause: 14 ms, pauses over 1000 ms: 0
22:51:50, accumulated pauses: 102 ms, max pause: 13 ms, pauses over 1000 ms: 0
22:51:55, accumulated pauses: 98 ms, max pause: 12 ms, pauses over 1000 ms: 0
22:52:00, accumulated pauses: 83 ms, max pause: 10 ms, pauses over 1000 ms: 0
22:52:05, accumulated pauses: 98 ms, max pause: 14 ms, pauses over 1000 ms: 0
22:52:10, accumulated pauses: 92 ms, max pause: 12 ms, pauses over 1000 ms: 0
22:52:15, accumulated pauses: 86 ms, max pause: 11 ms, pauses over 1000 ms: 0
22:52:20, accumulated pauses: 95 ms, max pause: 10 ms, pauses over 1000 ms: 0
22:52:25, accumulated pauses: 377 ms, max pause: 289 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment] 2019-03-22 15:01
Same isolation issue as described [here](https://github.com/hazelcast/hazelcast-enterprise/issues/2862#issuecomment-475517934). Closing as duplicate.

**Closed by mmedenjak** 2019-03-22 15:01 UTC
Labels: Module: IAtomicLong, Team: Client, Team: Core, Type: Test-Failure
