### ISSUE TITLE
MembershipFailureTest_withTCP slave_receives_member_list_from_non_master

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17238] opened 2020-07-18 09:20 UTC
- Fails on `Hazelcast-4.master-nightly`
- Fails on [Build #539 (Jul 17, 2020 5:07:00 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-nightly/539/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/slave_receives_member_list_from_non_master_fd_deadline_/)
- Error
```
Cluster size is not correct. Expected: 2, actual: 3, instance index: 0
```
- Stacktrace
```
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 3, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1029)
	at com.hazelcast.test.HazelcastTestSupport$11.run(HazelcastTestSupport.java:1057)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1242)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1259)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1054)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1042)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.slave_receives_member_list_from_non_master(MembershipFailureTest.java:361)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
```
- It could manifest since hiccups, as also `FailOnTimeoutStatement` in stacktrace.
```
18:09:35, accumulated pauses: 35 ms, max pause: 1 ms, pauses over 1000 ms: 0
18:09:40, accumulated pauses: 60 ms, max pause: 4 ms, pauses over 1000 ms: 0
18:09:45, accumulated pauses: 49 ms, max pause: 6 ms, pauses over 1000 ms: 0
18:09:50, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:09:55, accumulated pauses: 48 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:10:00, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:10:05, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:10:10, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:10:15, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:10:20, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:10:25, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:10:30, accumulated pauses: 31 ms, max pause: 2 ms, pauses over 1000 ms: 0
18:10:35, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:10:40, accumulated pauses: 31 ms, max pause: 1 ms, pauses over 1000 ms: 0
18:10:45, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:10:50, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:10:55, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:11:00, accumulated pauses: 58 ms, max pause: 1 ms, pauses over 1000 ms: 0
18:11:05, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:11:10, accumulated pauses: 44 ms, max pause: 3 ms, pauses over 1000 ms: 0
18:11:15, accumulated pauses: 51 ms, max pause: 2 ms, pauses over 1000 ms: 0
18:11:20, accumulated pauses: 49 ms, max pause: 3 ms, pauses over 1000 ms: 0
18:11:25, accumulated pauses: 49 ms, max pause: 1 ms, pauses over 1000 ms: 0
18:11:30, accumulated pauses: 45 ms, max pause: 3 ms, pauses over 1000 ms: 0
18:11:35, accumulated pauses: 50 ms, max pause: 4 ms, pauses over 1000 ms: 0
18:11:40, accumulated pauses: 71 ms, max pause: 2 ms, pauses over 1000 ms: 0
18:11:45, accumulated pauses: 315 ms, max pause: 285 ms, pauses over 1000 ms: 0
```
- kindly check

**Comment by vbekiaris** [comment] 2020-09-17 13:39
The test starts 4 members, then blocks heartbeat ops and members 3 & 4 suspect members 1 & 2. After members 3 & 4 are split to their own cluster, the expected outcome is that member 1 will receive `ExplicitSuspicionOp` from 3 & 4 and remove them from the cluster. This happens after possibly multiple attempts to re-establish a connection from member 1 to members 3 & 4.
When the test fails:
- member 1 initiates a connection to members 3 and 4, attempting to reconnect. Member 1 does not suspect members 3 & 4 and the heartbeat timeout is set to `MAX_INTEGER`.
- members 3/4 accept the connection but close it immediately because 1 is suspected on their side
- with some unlucky timing, it can be the case that the `MemberHandshake` has not yet been received / processed on member 1, so `Connection#planeIndex` is not set (it is normally set when processing `MemberHandshake` in https://github.com/hazelcast/hazelcast/blob/20d92a7fe67b17a0f1e1fd2f5f049acec1b8125f/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerControl.java#L84).
- member 1 reacts to the remote side having closed the connection by closing its own side too. However, since `planeIndex` was not set, it remains to its default value `-1` -> https://github.com/hazelcast/hazelcast/blob/20d92a7fe67b17a0f1e1fd2f5f049acec1b8125f/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManager.java#L521-L526 does not remove it from `planes[0]#connectionsInProgress`
- later attempts to reconnect on member 1's side find that a connection is already in progress to the given destination address -> no actual attempt is made to re-open a connection -> there is no opportunity for members 3/4 to send the `ExplicitSuspicionOp` to member 1

**Comment by lprimak** [comment] 2020-09-20 06:04
I am seeing these types of errors as a result of https://github.com/hazelcast/hazelcast/pull/17428
This maybe why the tests are failing there

**Comment by slavagithub** [comment] 2022-01-24 09:40
Reproduced again on 5.1, Master, IBM Jdk 8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/36/testReport/com.hazelcast.internal.cluster.impl/MembershipFailureTest/slave_receives_member_list_from_non_master_fd_phi_accrual_/, reopening

**Comment by slavagithub** [comment] 2022-01-26 13:21
failed on `master`, sonar, Oracle JDK11 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1111/testReport/com.hazelcast.internal.cluster.impl/MembershipFailureTest/slave_receives_member_list_from_non_master_fd_phi_accrual_/

**Comment by ufukyilmaz** [comment] 2022-02-01 12:36
Closing this since a new issue for the recent occurrences also reported here: https://github.com/hazelcast/hazelcast/issues/20553 (and I'm tracking this issue). These recent occurrences seems to be caused by my changes on the connection management (The root cause is that the connections to the suspected member were not closed. Fixes to `getAllConnections` should have resolved this issue: https://github.com/hazelcast/hazelcast/commit/0a077a0b79bbc8309c5e994696f6a89f1c77569c (NPE issue in this commit makes this issue more probable, formerly it can only fail in duplicate connections case) and https://github.com/hazelcast/hazelcast/commit/a5414c755a3ded5054863c71f5ec353b931f1fa5). Currently, I'm testing/verifying the fix, I'll close the other issue when I'm fully sure. 

Since the issue also occurs before the NPE issue: http://jenkins.hazelcast.com/job/Hazelcast-master-sonar/1111/, I'm testing this thoroughly in jenkins. See: http://jenkins.hazelcast.com/job/ufuk-test-runner/54/ and http://jenkins.hazelcast.com/job/ufuk-test-runner/56/

**Closed by ufukyilmaz** 2022-02-01 12:36 UTC
Labels: Type: Defect, Team: Core, Type: Test-Failure, Source: Internal, Module: Network I/O, Module: Cluster
