### ISSUE TITLE
Issue with Hazelcast Management center (Hazelcast 3.5.3)

### ISSUE THREAD

**Issue by mukul4u2005** [hazelcast/hazelcast#8515] opened 2016-07-12 15:32 UTC
Hi All

I am trying to login the managment center with default user credential admin/admin but page is refreshing only without any error.  The management center is deployed on tomcat 7

the url is updating with session id as: 
/mancenter-3.5.3/login.jsp;jsessionid=5F668683D4A792C10748D4E8DF9E9003.0

Would you suggest  what can be that issue.

**Comment by emrahkocaman** [comment] 2016-07-13 07:00
Closing this issue as it's duplicate of https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/hazelcast/zlXTb-elcO4/ARkx6vaOAAAJ.

**Closed by emrahkocaman** 2016-07-13 07:00 UTC
