### ISSUE TITLE
com.hazelcast.client.spi.impl.ClientInvocationTest.executionCallback_FailOnShutdown fails on PR

### ISSUE THREAD

**Issue by toktarev** [hazelcast/hazelcast#7462] opened 2016-02-04 12:18 UTC
com.hazelcast.client.spi.impl.ClientInvocationTest.executionCallback_FailOnShutdown fails 
on CI

**Comment by Donnerbart** [comment] 2016-02-04 12:30
Duplicate of https://github.com/hazelcast/hazelcast/issues/7008

**Closed by Donnerbart** 2016-02-04 12:30 UTC
Labels: Team: Client, Type: Defect
