### ISSUE TITLE
Hazelcast client produces OutOfMemoryError when there is no hazelcast server available at startup

### ISSUE THREAD

**Issue by sottos** [hazelcast/hazelcast#13186] opened 2018-05-27 07:52 UTC
I am using hazelcast 3.9, error exists in 3.10, but does not produce OOM there. 
I am using Windows 10 and Java 1.8.0_171

The attached [hazelcast-error.zip](https://github.com/hazelcast/hazelcast/files/2042343/hazelcast-error.zip) contains a project, just unpack and mvn clean install. The unit test logs will normally show OOMs after half a minute..
It is using hazelcast 3.9

Changing the hazelcast version in the pom to 3.10 will not produce OOMs, but the buffer error is still there.

Starting the client when there is **no datagrid to connect** to will produce a buffer,
 which **seems to have a length which is larger than the buffers capacity**. This is certainly an error. 

The error appears in  com.hazelcast.client.impl.protocol.ClientMessage::readFrom, where
the Bits.readIntL(src) returns a length greater then src.capacity(). The length bytes in the buffer seems
to be corrupted somehow (the lengt bytes are actually offseted by 3 bytes in this case)

```java
public boolean readFrom(ByteBuffer src) {

        int frameLength = 0;
        if (this.buffer == null) {
            // init internal buffer
            final int remaining = src.remaining();
            if (remaining < Bits.INT_SIZE_IN_BYTES) {
                // we don't have even the frame length ready
                return false;
            }
            frameLength = Bits.readIntL(src); // In some cases we have frameLength > src.capacity()
                   //, seems like three bytes has been inserted first in buffer and handled as part of length !!
            // we need to restore the position; as if we didn't read the frame-length
            src.position(src.position() - Bits.INT_SIZE_IN_BYTES);
            if (frameLength < HEADER_SIZE) {
                throw new IllegalArgumentException("Client message frame length cannot be smaller than header size.");
            }
            wrap(new byte[frameLength], 0, USE_UNSAFE);
        }
        frameLength = frameLength > 0 ? frameLength : getFrameLength();
        accumulate(src, frameLength - index());
        return isComplete();
    }
```

**Comment by ahmetmircik** [comment] 2018-05-29 12:31
seems same issue with this-> https://github.com/hazelcast/hazelcast-enterprise/issues/1382

**Comment by sancar** [comment] 2018-05-30 10:21
Hi @sottos , 
I am trying to reproduce the issue. When I run your zip itself, it did not go OOME. 
Should I open a cluster with it  to reproduce ? Or may be I should open the cluster  a little bit later ?

When there is no cluster, clientMessage.readFrom is actually never called.

**Comment by sottos** [comment] 2018-05-30 10:44
Hi,

Sorry last question,If you are using the supplied pom.xml you are for sure using 3.9.
I just tested the .zip on a machine (Windows) with 32G mem, it does not produce an OOM as the unit test is set up. There is a loop there which stops, and on the given machine only about 5G was used by the program.

I imported the pom.xml into intellij IDEA as a project, added a logging breakpoint in ClientMessage::readFrom, and started the unit test in debug mode.
I see several lines like this in the log:
Breakpoint reached at com.hazelcast.client.impl.protocol.ClientMessage.readFrom(ClientMessage.java:159)
So readfrom is certainly called.

Since there is no cluster on this machine, readFrom should not be called I think, but for some reason it is.

Regards
sottos




Fra: mustafa sancar koyunlu <notifications@github.com>
Sendt: onsdag 30. mai 2018 12:21
Til: hazelcast/hazelcast <hazelcast@noreply.github.com>
Kopi: Svein Otto Solem <Svein.Otto.Solem@kantega.no>; Mention <mention@noreply.github.com>
Emne: Re: [hazelcast/hazelcast] Hazelcast client produces OutOfMemoryError when there is no hazelcast server available at startup (#13186)


Hi @sottos<https://github.com/sottos> ,
I am trying to reproduce the issue. When I run your zip itself, it did not go OOME.
Should I open a cluster with it to reproduce ? Or may be I should open the cluster a little bit later ?

When there is no cluster, clientMessage.readFrom is actually never called.

**Comment by sancar** [comment] 2018-05-30 12:09
Can you share the logs of your run ?

**Comment by sottos** [comment] 2018-05-30 12:21
Runs unittest in IDEA, machine with 32G, so no OOMs here. I kill the application after reaching the breakpoint in ClientMessage.readFrom
I placed a logging breakpoint at com.hazelcast.client.impl.protocol.ClientMessage.readFrom(ClientMessage.java:168) which prints the framelength and the src.capacity.  See Red text
Below I am using jdk-10, but the same happens 1.8

"C:\Program Files\Java\jdk-10\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:51044,suspend=y,server=n -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:C:\Users\svein\.IntelliJIdea2018.1\system\captureAgent\debugger-agent.jar=file:/C:/Users/svein/AppData/Local/Temp/capture.props -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2018.1\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2018.1\plugins\junit\lib\junit-rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2018.1\plugins\junit\lib\junit5-rt.jar;C:\Users\svein\Downloads\hazelcast-error\hazelcast-error\target\test-classes;C:\Users\svein\Downloads\hazelcast-error\hazelcast-error\target\classes;C:\Users\svein\.m2\repository\com\hazelcast\hazelcast\3.9\hazelcast-3.9.jar;C:\Users\svein\.m2\repository\com\hazelcast\hazelcast-client\3.9\hazelcast-client-3.9.jar;C:\Users\svein\.m2\repository\junit\junit\4.12\junit-4.12.jar;C:\Users\svein\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 no.sottos.ClientSetupTest
Connected to the target VM, address: '127.0.0.1:51044', transport: 'socket'
runtime.freeMemory() = 526446232
mai 30, 2018 2:14:02 P.M. com.hazelcast.core.LifecycleService
INFO: hz.client_0 [document-store] [3.9] HazelcastClient 3.9 (20171023 - b29f549) is STARTING
mai 30, 2018 2:14:03 P.M. com.hazelcast.core.LifecycleService
INFO: hz.client_0 [document-store] [3.9] HazelcastClient 3.9 (20171023 - b29f549) is STARTED
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.hazelcast.internal.networking.nio.SelectorOptimizer (file:/C:/Users/svein/.m2/repository/com/hazelcast/hazelcast/3.9/hazelcast-3.9.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of com.hazelcast.internal.networking.nio.SelectorOptimizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
mai 30, 2018 2:14:03 P.M. com.hazelcast.internal.diagnostics.Diagnostics
INFO: hz.client_0 [document-store] [3.9] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
mai 30, 2018 2:14:03 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.1]:1960 as owner member
mai 30, 2018 2:14:04 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.1]:1960, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:04 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.3]:1959 as owner member
mai 30, 2018 2:14:05 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.3]:1959, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:05 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.1]:1959 as owner member
mai 30, 2018 2:14:06 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.1]:1959, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:06 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.2]:1961 as owner member
mai 30, 2018 2:14:07 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.2]:1961, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:07 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.3]:1960 as owner member
mai 30, 2018 2:14:08 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.3]:1960, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:08 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.2]:1959 as owner member
mai 30, 2018 2:14:09 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.2]:1959, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:09 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.2]:1958 as owner member
mai 30, 2018 2:14:10 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.2]:1958, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:10 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.3]:1961 as owner member
mai 30, 2018 2:14:11 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.3]:1961, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:11 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.1]:1961 as owner member
mai 30, 2018 2:14:12 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.1]:1961, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:12 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.2]:1960 as owner member
mai 30, 2018 2:14:13 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.2]:1960, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:13 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.3]:1958 as owner member
mai 30, 2018 2:14:14 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.3]:1958, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:14 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.1]:1958 as owner member
mai 30, 2018 2:14:15 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.1]:1958, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:15 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Unable to get alive cluster connection, try in 0 ms later, attempt 1 of 2147483647.
mai 30, 2018 2:14:15 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.3]:1961 as owner member
mai 30, 2018 2:14:16 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.3]:1961, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:16 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.1]:1960 as owner member
mai 30, 2018 2:14:17 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.1]:1960, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:17 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.2]:1958 as owner member
mai 30, 2018 2:14:18 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.2]:1958, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:18 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.1]:1959 as owner member
mai 30, 2018 2:14:19 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.1]:1959, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:19 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.1]:1958 as owner member
Breakpoint reached at com.hazelcast.client.impl.protocol.ClientMessage.readFrom(ClientMessage.java:168)
FrameLength: 1177698883 src.capacity: 131072
Memory used since last time =  -595408
mai 30, 2018 2:14:24 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.1]:1958, exception com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: Authentication response did not come back in 5000 millis
mai 30, 2018 2:14:24 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.2]:1961 as owner member
mai 30, 2018 2:14:25 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.2]:1961, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:25 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.3]:1958 as owner member
mai 30, 2018 2:14:26 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.3]:1958, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:26 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.1]:1961 as owner member
Breakpoint reached at com.hazelcast.client.impl.protocol.ClientMessage.readFrom(ClientMessage.java:168)
FrameLength: 1177698883 src.capacity: 131072
mai 30, 2018 2:14:31 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.1]:1961, exception com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: Authentication response did not come back in 5000 millis
mai 30, 2018 2:14:31 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.3]:1959 as owner member
mai 30, 2018 2:14:32 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.3]:1959, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:32 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.2]:1959 as owner member
mai 30, 2018 2:14:33 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.2]:1959, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:33 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.2]:1960 as owner member
mai 30, 2018 2:14:34 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.2]:1960, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:34 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.3]:1960 as owner member
mai 30, 2018 2:14:35 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Exception during initial connection to [127.0.0.3]:1960, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused: no further information
mai 30, 2018 2:14:35 P.M. com.hazelcast.client.connection.ClientConnectionManager
WARNING: hz.client_0 [document-store] [3.9] Unable to get alive cluster connection, try in 0 ms later, attempt 2 of 2147483647.
mai 30, 2018 2:14:35 P.M. com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [document-store] [3.9] Trying to connect to [127.0.0.1]:1961 as owner member
Disconnected from the target VM, address: '127.0.0.1:51044', transport: 'socket'

Process finished with exit code -1

Fra: mustafa sancar koyunlu <notifications@github.com>
Sendt: onsdag 30. mai 2018 14:10
Til: hazelcast/hazelcast <hazelcast@noreply.github.com>
Kopi: Svein Otto Solem <Svein.Otto.Solem@kantega.no>; Mention <mention@noreply.github.com>
Emne: Re: [hazelcast/hazelcast] Hazelcast client produces OutOfMemoryError when there is no hazelcast server available at startup (#13186)


Can you share the logs of your run ?

**Comment by sancar** [comment] 2018-05-30 12:41
It is either because of Windows environment which is very unlikely (I will test this, currently using mac). 
Or I am going to suspect that there is somebody responding from endpoints that client trying to connect 127.0.1-3/1958-1961 . Can you check and confirm nothing is running on these addresses ?

**Comment by sancar** [comment] 2018-05-31 09:54
Since it is not reproduced on our side, and you say that it could be the case that ports are mixed, I am closing the issue for now. Feel free to reopen the issue if you see a related problem.

**Closed by sancar** 2018-05-31 09:54 UTC
Labels: Team: Client

**Comment by sottos** [comment] 2018-08-08 07:28
We have tried it on Mac, produces no error,  the ClientMessage::readFrom is not called.
on Windows and Ubuntu we end up with an OutOfMemory error. 
We are now using port 19580 instead of 1958, no difference actually, OOMs for both.
