### ISSUE TITLE
MapLoader.loadAll(true) doesn't reload after reloading with new keys

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast#9255] opened 2016-11-14 16:11 UTC
Reproducer: https://github.com/amitgsoni/hazelcast

1. Start cache server (Don't load any map) 
2. Load map first time --> Using `com.hazelcast.client.HazelcastClient.getMap().size()` 
3. Reload Update key(s) of given map --> Using `com.hazelcast.client.HazelcastClient getMap().loadAll(keys, true);`

-- Once we do operation of step-3 the getMap().loadAll(true) is not working as expected

ZD 2149

**Comment by jerrinot** [comment] 2016-11-15 16:19
@gAmUssA: I'm looking at the reproducer. Can you please elaborate the "Once we do operation of step-3 the getMap().loadAll(true) is not working as expected" statement? 

What is supposed to happen and what's actually happening?

**Comment by gAmUssA** [comment] 2016-11-15 16:22
use case 1

- map has maploader
- hz.getMap invokes loadAllKeys, loadAll
- hz.getMap.loadAll(true) invokes loadAll

all good here

use case 2

- map has maploader
- hz.getMap invokes loadAllKeys, loadAll
- new set of keys
- hz.getMap.loadAdd(keys, true) invokes loadAll for new set of keys
- hz.getMap.loadAll(true) doesn't work.

Thank you

**Comment by jerrinot** [comment] 2016-11-15 16:26
a further clarification from @gAmUssA: "hz.getMap.loadAll(true) doesn't work." == Map Loader is not invoked

**Comment by gAmUssA** [comment] 2016-11-15 16:42
@jerriot let me know if you need any further clarification

**Comment by jerrinot** [comment] 2016-11-15 17:21
I did a little bit of debugging and when `hz.getMap.loadAdd(keys, true)` is called then the subsequent `loadAll(true)` will be no-op because the [state here](https://github.com/jerrinot/hazelcast/blob/4d0231e20ed8d923bf4f666f0ff279cdf8cdeacc/hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java#L229) will be still `LOADING`.

**Comment by jerrinot** [comment] 2016-12-13 11:33
assigning to Tom as discussed.

**Closed** 2016-12-20 09:04 UTC
Labels: Team: Core, Type: Critical, Type: Defect
