### ISSUE TITLE
Hazelcast out of memory error

### ISSUE THREAD

**Issue by sudheermg** [hazelcast/hazelcast#7271] opened 2016-01-08 08:05 UTC
We are using Websphere Application Server 6.1, in production our 2 nodes are not in sync with the master configuration for some issue. Does this effect the Hazelcast in memory cache (cluster mode) when nodes are not in sync

**Comment by jerrinot** [comment] 2016-01-08 08:18
Hello @sudheermg,

I am not quite sure what issue you are reporting here. Do you have an out of memory error? If so then I'd recommend you to:

- enable verbose garbage collector logs. see this how to do it on JVM running WAS: http://www-01.ibm.com/support/docview.wss?uid=swg21114927#v6 It has very low overhead and it can be extremely helpful when analysis potential memory leak
- if you have heapdump then Eclipse Memory Analyzer is a great  tool to help you to get some insight. You can configure your JVM to create a heapdump on Out of Memory error. I believe you can even use WAS console to enable it. 

Hazelcast configuration should be in sync on all nodes. Otherwise it might lead to surprising behaviour, data inconsistencies and other issues. The exact manifestation depends on a level of your inconsistencies.

**Comment by sudheermg** [comment] 2016-01-08 08:44
Hi Hamala,

Thanks for the quick reply.

The actual issue was, on one of our production node HazelCast instance went down with out of memory error. When this occurred the nodes on the cluster was not in sync, so my question is when nodes are not synced with master configuration, does HazelCast will work ( because it is clusterwide configuration).


Thanks,
Sudheer M

**Comment by jerrinot** [comment] 2016-01-08 08:55
@sudheermg: Each member has its own local configuration if one member dies then other members still have an access to theirs configuration.

When a member goes down then it's a business as usual for Hazelcast and the rest of cluster members will just work. Later on when you start a new member then it will join the existing cluster. This is how Hazelcast has been designed from day one - to be elastic. 

I'm closing this ticket as we use GitHub issues for bug reports / feature requests.

Please feel free to use Hazelcast [user forum](https://groups.google.com/forum/#!forum/hazelcast) if you have other question. [This](http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#sharding-in-hazelcast) is a good starting point to learn more about Hazelcast.

**Closed by jerrinot** 2016-01-08 08:55 UTC

**Comment by sudheermg** [comment] 2016-01-14 11:01
How to restart the hazelcast ( it went down because of out of memory issue).

Thanks,
Sudheer M

**Comment by sudheermg** [comment] 2016-01-14 11:06
How to restart (reinstantiate) when the hazelcast instance is down. We observed that Hazelcast instance is not active ( IllegalStateException) in the logs and the root cause for this is Out of memory issue and because of this the Hazelcast instance went down, all the subsequent requests to hazelcast got failed with IllegalStateException.
How I can reinstantiate the Hazelcast.

**Comment by sudheermg** [comment] 2016-01-18 12:04
Can any one please help me on this.

**Comment by tombujok** [comment] 2016-01-18 12:51
Hi @sudheermg,

You mentioned websphere, so I'm assuming you are using an embedded topology.

To see the difference between embedded and client-server topologies follow the link below: http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#what-is-the-difference-between-client-server-and-embedded-topologies

If you are using an embedded topology it means that your websphere instance died (and the hazelcast died together with it since they are running on a single JVM). In this case follow the websphere instruction no how to start its instance.

If you are using a client-service topology (Hazelcast runs in a separate JVM) you can start it using `bin/server.sh` (or server.bat) script. 

Make sure to analyse memory consumption and/or increase your heap size using (using Xms, Xmx JVM options) if you are sure your runtime needs more memory.

**Comment by sudheermg** [comment] 2016-01-19 10:15
The configuration is as below.

-----------------------


<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-2.5.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>dev</name>
        <password>dev-pass</password>
    </group>
    <management-center enabled="false">http://172.21.33.151:8080/mancenter-2.6.5</management-center>
    <network>
        <port auto-increment="true">5701</port>
        <outbound-ports>
            
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="false">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
            </multicast>
            <tcp-ip enabled="true">
                <hostname>bprodsdgwap1</hostname>
                <hostname>bprodsdgwap2</hostname>
            </tcp-ip>
            <aws enabled="false">
                <access-key>my-access-key</access-key>
                <secret-key>my-secret-key</secret-key>
                
                <region>us-west-1</region>
                
                <hostHeader>ec2.amazonaws.com</hostHeader>
                
                <security-group-name>hazelcast-sg</security-group-name>
                <tag-key>type</tag-key>
                <tag-value>hz-nodes</tag-value>
            </aws>
        </join>
        <interfaces enabled="false">
            <interface>10.10.1.*</interface>
        </interfaces>
        <ssl enabled="false" />
        <socket-interceptor enabled="false" />
        <symmetric-encryption enabled="false">
            
            <algorithm>PBEWithMD5AndDES</algorithm>
            
            <salt>thesalt</salt>
            
            <password>thepass</password>
            
            <iteration-count>19</iteration-count>
        </symmetric-encryption>
        <asymmetric-encryption enabled="false">
            
            <algorithm>RSA/NONE/PKCS1PADDING</algorithm>
            
            <keyPassword>thekeypass</keyPassword>
            
            <keyAlias>local</keyAlias>
            
            <storeType>JKS</storeType>
            
            <storePassword>thestorepass</storePassword>
            
            <storePath>keystore</storePath>
        </asymmetric-encryption>
    </network>
    <partition-group enabled="false"/>
    <executor-service>
        <core-pool-size>16</core-pool-size>
        <max-pool-size>64</max-pool-size>
        <keep-alive-seconds>60</keep-alive-seconds>
    </executor-service>
----------------------------


Java code 
===============

private static HazelcastInstance instance = null;
  static{

		Config cfg;
		try {
			cfg = new XmlConfigBuilder(new FileInputStream(PropertiesManager.getProperty(G2Constants.RUNTIME_PROPFILE, G2Constants.G2_HAZELCAST_CONFIG))).build();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			cfg = new Config();
		}	
	 instance = Hazelcast.newHazelcastInstance(cfg);
  }

**Comment by tombujok** [comment] 2016-01-19 10:17
So just rerun your java code to restart your failed jvm.

**Comment by sudheermg** [comment] 2016-01-19 10:26
jvm did not go down, but the calls to the hazelcast was throwing IllegalStateException(HazelCaste instance is down), the node was processing fine.

**Comment by sudheermg** [comment] 2016-01-19 11:03
how to ensure the Hazelcast instance is active and running ?

**Comment by tombujok** [comment] 2016-01-19 11:27
In case your HZ fails within JVM but the JVM is still running you have two options:
1.) start the node by creating a new instance `instance = Hazelcast.newHazelcastInstance(cfg);`
In this case make sure you do not use the old instance - you also have to renew all the proxies (so you have to make sure that you do not use any old map references taken from the old instance).

2.) the second option and the preferred one is to restart your JVM.

**Please keep in mind that OOME should be thoroughly analysed - you probably have a misconfigured JVM and there is no certainty that the problem is resolved after restarting HZ.**

**Comment by ahmetmircik** [comment] 2016-01-19 15:00
@sudheermg one another option is to implement your own strategy by defining a new `OutOfMemoryHandler` like this example https://gist.github.com/enesakar/8182073, so you can define another behaviour than default.

Also you can see the default handler here https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/instance/DefaultOutOfMemoryHandler.java, it is called when an OOME is caught by HZ managed thread.

**Comment by sudheermg** [comment] 2016-01-20 06:14
The default out of memory handler will be activated automatically ?

**Comment by ahmetmircik** [comment] 2016-01-20 09:00
Yes it is active by default, you can set yours via `Hazelcast#setOutOfMemoryHandler`
