### ISSUE TITLE
Size count different between IMap.size() and Imap.keySet().size()

### ISSUE THREAD

**Issue by manishonline** [hazelcast/hazelcast#7687] opened 2016-03-08 04:03 UTC
Are count values when Invoked on IMap and IMap.keySet() not supposed to be equal? I am seeing a huge difference.
Server version  :3.5.4
client version  :3.5.4

`
         

       private ClientConfig getIPDSClientConfig(){
        GroupConfig groupConfig = new GroupConfig("nxdev-ipds-dev","password");
        ClientConfig clientConfig =  new ClientConfig();
        clientConfig.setGroupConfig(groupConfig);
        ClientNetworkConfig clientNetworkConfig = new ClientNetworkConfig();
        clientNetworkConfig.setAddresses(Lists.newArrayList("127.0.0.1:6701"));
        clientConfig.setNetworkConfig(clientNetworkConfig);
        return clientConfig;
    }

      @Test
        public void testHazelcastClient(){
       ClientConfig clientConfig = getIPDSClientConfig();
        HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);
        final IMap mktEnvCache= client.getMap("marketEnvDSMap");
        System.out.println(" Cache Size:: "+mktEnvCache.size()+" keys size:: "+mktEnvCache.keySet().size());
}

`

Output : 
Cache Size:: 8234 keys size:: 100
__

**Comment by gurbuzali** [comment] 2016-03-08 08:26
I can't reproduce it 
```
        HazelcastInstance instance = Hazelcast.newHazelcastInstance();
        HazelcastInstance client = HazelcastClient.newHazelcastClient();

        IMap<Object, Object> map = client.getMap("map");
        for (int i = 0; i < 5000; i++) {
            map.put(i, i);
        }
        System.err.println("size: " + map.size() + " keySetSize: " + map.keySet().size());
```
`size: 5000 keySetSize: 5000`

**Comment by ahmetmircik** [comment] 2016-03-08 08:30
@gurbuzali i remember one case that may cause this problem when used with expiration since a background task is cleaning expired ones, till the end of cleaning, size may differ

**Comment by manishonline** [comment] 2016-03-08 08:45
It's fairly consistent at my end.

The TradeCache has a mapstore configured. Following is the configuration :

```
 <hz:map name="marketEnvDSMap" backup-count="1" eviction-policy="NONE" in-memory-format="BINARY">
                <hz:map-store enabled="true" write-delay-seconds="0" implementation="marketEnvMapStore"/>
                <hz:near-cache time-to-live-seconds="0" eviction-policy="LRU" max-size="1000" invalidate-on-change="true"/>
            </hz:map>
```

**Comment by gurbuzali** [comment] 2016-03-08 08:48
can you share a reproducer code ?

**Comment by manishonline** [comment] 2016-03-08 09:40
Ok. Will try to update by tomorrow.

**Comment by ahmetmircik** [comment] 2016-05-30 09:13
any update @manishonline ?

**Comment by ahmetmircik** [comment] 2016-06-16 09:29
@manishonline, closing this issue now, please reopen it with a reproducer test, thanks.

**Closed by ahmetmircik** 2016-06-16 09:29 UTC
Labels: Team: Client, Team: Core, Type: Defect
