### ISSUE TITLE
PartitionAssignmentsCorrectnessTest testPartitionAssignments_whenNodesStartedTerminated

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17021] opened 2020-05-30 05:45 UTC
- Fails on `Hazelcast-4.maintenance-OracleJDK8`
- Fails on [Build #77 (May 28, 2020 2:16:44 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-OracleJDK8/77/testReport/junit/com.hazelcast.internal.partition/PartitionAssignmentsCorrectnessTest/testPartitionAssignments_whenNodesStartedTerminated_backups_2_nodes_3_/)

- Error 
```
On Member [127.0.0.1]:5702 - 1b5af6ca-a423-4473-839f-2787cf8fddd4 this, Replica 1 is not found in Partition [9]{
 0:[127.0.0.1]:5702 - 1b5af6ca-a423-4473-839f-2787cf8fddd4
 3:[127.0.0.1]:5701 - 1534ca12-e1df-4e80-bd14-bc56ca07ed6e
}
```
- Stacktrace
```
java.lang.AssertionError: 
On Member [127.0.0.1]:5702 - 1b5af6ca-a423-4473-839f-2787cf8fddd4 this, Replica 1 is not found in Partition [9]{
	0:[127.0.0.1]:5702 - 1b5af6ca-a423-4473-839f-2787cf8fddd4
	3:[127.0.0.1]:5701 - 1534ca12-e1df-4e80-bd14-bc56ca07ed6e
}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionAssignments(PartitionCorrectnessTestSupport.java:193)
	at com.hazelcast.internal.partition.AbstractPartitionAssignmentsCorrectnessTest$1.run(AbstractPartitionAssignmentsCorrectnessTest.java:83)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.internal.partition.AbstractPartitionAssignmentsCorrectnessTest.assertPartitionAssignmentsEventually(AbstractPartitionAssignmentsCorrectnessTest.java:80)
	at com.hazelcast.internal.partition.AbstractPartitionAssignmentsCorrectnessTest.assertPartitionAssignmentsEventually(AbstractPartitionAssignmentsCorrectnessTest.java:76)
	at com.hazelcast.internal.partition.AbstractPartitionAssignmentsCorrectnessTest.testPartitionAssignments_whenNodesStartedTerminated(AbstractPartitionAssignmentsCorrectnessTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
- Found in logs
```
Caused by: com.hazelcast.spi.exception.RetryableHazelcastException: Cannot set active migration to MigrationInfo{uuid=2ab99685-ff47-4cec-8ec8-27c66be95a27, partitionId=9, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5701 - 1534ca12-e1df-4e80-bd14-bc56ca07ed6e, destinationCurrentReplicaIndex=3, destinationNewReplicaIndex=1, master=[127.0.0.1]:5701, initialPartitionVersion=945, partitionVersionIncrement=2, processing=false, status=ACTIVE}. Current active migration is MigrationInfo{uuid=22c84cb8-c0e5-497e-8592-fea4f79dd7fd, partitionId=89, source=[127.0.0.1]:5704 - cbe65351-e53c-47e4-96d9-de2d0929aca6, sourceCurrentReplicaIndex=2, sourceNewReplicaIndex=3, destination=[127.0.0.1]:5702 - 1b5af6ca-a423-4473-839f-2787cf8fddd4, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=2, master=[127.0.0.1]:5701, initialPartitionVersion=608, partitionVersionIncrement=2, processing=false, status=INVALID}
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.setActiveMigration(BaseMigrationOperation.java:225) ~[classes/:?]
	at com.hazelcast.internal.partition.operation.MigrationRequestOperation.call(MigrationRequestOperation.java:88) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:433) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123) ~[classes/:?]
```

kindly check.

**Comment by mmedenjak** [comment] 2020-09-01 08:21
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2135

**Comment by mdogan** [comment] 2020-09-01 12:19
There's a serialization issue in the failure but I couldn't figure out yet the cause.

```
08:10:57,634 ERROR |testPartitionData_whenBackupNodesStartedTerminated[backups:3,nodes:4,fragmented:false]| - [OperationExecutorImpl] hz.youthful_tu.generic-operation.thread-11 - [127.0.0.1]:5703 [dev] [4.1-SNAPSHOT] Failed to process: Packet{partitionId=-1, frameLength=10617, conn=MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5701, alive=true}, rawFlags=10001, isUrgent=true, packetType=OPERATION, typeSpecificFlags=[isResponse=false, isOpControl=false]} on: hz.youthful_tu.generic-operation.thread-11
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: -2, ID: 1, class: 'null', exception: Illegal Capacity: -511
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_251]
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233) ~[classes/:?]
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138) ~[classes/:?]
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114) ~[classes/:?]
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73) ~[classes/:?]
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:459) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: -2, ID: 1, class: 'null', exception: Illegal Capacity: -511
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException(DataSerializableSerializer.java:183) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:164) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:286) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:567) ~[classes/:?]
	at com.hazelcast.internal.cluster.impl.operations.MembersUpdateOp.readInternalImpl(MembersUpdateOp.java:117) ~[classes/:?]
	at com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOp.readInternalImpl(FinalizeJoinOp.java:169) ~[classes/:?]
	at com.hazelcast.internal.cluster.impl.operations.MembersUpdateOp.readInternal(MembersUpdateOp.java:123) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.readData(Operation.java:750) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:205) ~[classes/:?]
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:346) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:437) ~[classes/:?]
	... 4 more
Caused by: java.lang.IllegalArgumentException: Illegal Capacity: -511
	at java.util.ArrayList.<init>(ArrayList.java:157) ~[?:1.8.0_251]
	at com.hazelcast.internal.serialization.impl.SerializationUtil.readList(SerializationUtil.java:380) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.SerializationUtil.readNullableList(SerializationUtil.java:348) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.SerializationUtil.readNullableCollection(SerializationUtil.java:330) ~[classes/:?]
	at com.hazelcast.internal.partition.PartitionRuntimeState.readData(PartitionRuntimeState.java:230) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:286) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:567) ~[classes/:?]
	at com.hazelcast.internal.cluster.impl.operations.MembersUpdateOp.readInternalImpl(MembersUpdateOp.java:117) ~[classes/:?]
	at com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOp.readInternalImpl(FinalizeJoinOp.java:169) ~[classes/:?]
	at com.hazelcast.internal.cluster.impl.operations.MembersUpdateOp.readInternal(MembersUpdateOp.java:123) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.readData(Operation.java:750) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:205) ~[classes/:?]
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:346) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:437) ~[classes/:?]
	... 4 more
```

**Comment by mmedenjak** [comment] 2020-09-07 09:02
@mdogan can we close this issue now that the PR has been merged?

**Comment by mdogan** [comment] 2020-09-07 09:20
@mmedenjak: No, that PR was only for the serialization issue. But I think serialization issue is not the cause of the test failure.

**Closed** 2020-09-22 13:32 UTC
Labels: Module: Partitioning, Source: Internal, Team: Core, Type: Test-Failure
