### ISSUE TITLE
Tests fail with 'Instances haven't been shut down' [HZ-1693]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19638] opened 2021-09-27 07:35 UTC
_master_ (commit 886628968ce05e1cd9073f9147b0f7e0c080a48f)

Failed on Sonar (Oracle JDK 11): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/989/testReport/

It happens more times, for example also here - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/987/testReport/

Stacktrace (for `com.hazelcast.jet.sql.SqlBasicClientTest.com.hazelcast.jet.sql.SqlBasicClientTest` as an example):
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='quirky_lalande', node=[127.0.0.1]:6401}]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:46)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output (for `com.hazelcast.jet.sql.SqlBasicClientTest.com.hazelcast.jet.sql.SqlBasicClientTest` as an example):
```
04:11:08,599  INFO || - [LifecycleService] Thread-2286 - hz.client_69 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20210926 - 8866289) is SHUTTING_DOWN
04:11:08,600  INFO || - [ClientConnectionManager] Thread-2286 - hz.client_69 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702:aeff2ef1-496b-41c7-9640-515bc49169b5, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2021-09-27 04:11:08.588, lastWriteTime=2021-09-27 04:11:08.588, closedTime=2021-09-27 04:11:08.600, connected server version=5.1-SNAPSHOT}}
04:11:08,600  INFO || - [MockServer] pool-227-thread-1 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:40001, connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5702, connectionId = 1}
04:11:08,601  INFO || - [ClientConnectionManager] Thread-2286 - hz.client_69 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:5a8ad93f-f227-4bda-a07c-d5a4f481bd4e, connection: MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2021-09-27 04:11:08.047, lastWriteTime=2021-09-27 04:11:08.047, closedTime=2021-09-27 04:11:08.600, connected server version=5.1-SNAPSHOT}}
04:11:08,601  INFO || - [LifecycleService] Thread-2286 - hz.client_69 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20210926 - 8866289) is CLIENT_DISCONNECTED
04:11:08,601  INFO || - [MockServer] pool-229-thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:40002, connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5701, connectionId = 2}
04:11:08,601  INFO || - [ClientEndpointManager] hz.nostalgic_lalande.event-3277 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5702, connectionId = 1}, clientUuid=eedc2b49-846e-43b7-8eda-5503a32d69fc, clientName=hz.client_69, authenticated=true, clientVersion=5.1-SNAPSHOT, creationTime=1632715856701, latest clientAttributes=lastStatisticsCollectionTime=1632715856707,enterprise=false,clientType=JVM,clientVersion=5.1-SNAPSHOT,clusterConnectionTimestamp=1632715856701,clientAddress=127.0.0.1,clientName=hz.client_69,credentials.principal=null,os.committedVirtualMemorySize=21202321408,os.freePhysicalMemorySize=710739845120,os.freeSwapSpaceSize=4294963200,os.maxFileDescriptorCount=1048576,os.openFileDescriptorCount=322,os.processCpuTime=6407100000000,os.systemLoadAverage=3.63,os.totalPhysicalMemorySize=811309408256,os.totalSwapSpaceSize=4294963200,runtime.availableProcessors=8,runtime.freeMemory=440947520,runtime.maxMemory=2147483648,runtime.totalMemory=1047527424,runtime.uptime=2076367,runtime.usedMemory=606579904, labels=[]}
04:11:08,601  INFO || - [ClientEndpointManager] hz.nervous_lalande.event-3276 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5701, connectionId = 2}, clientUuid=eedc2b49-846e-43b7-8eda-5503a32d69fc, clientName=hz.client_69, authenticated=true, clientVersion=5.1-SNAPSHOT, creationTime=1632715856704, latest clientAttributes=lastStatisticsCollectionTime=1632715866707,enterprise=false,clientType=JVM,clientVersion=5.1-SNAPSHOT,clusterConnectionTimestamp=1632715856704,clientAddress=127.0.0.1,clientName=hz.client_69,credentials.principal=null,os.committedVirtualMemorySize=21212057600,os.freePhysicalMemorySize=710888136704,os.freeSwapSpaceSize=4294963200,os.maxFileDescriptorCount=1048576,os.openFileDescriptorCount=322,os.processCpuTime=6445420000000,os.systemLoadAverage=3.38,os.totalPhysicalMemorySize=811309408256,os.totalSwapSpaceSize=4294963200,runtime.availableProcessors=8,runtime.freeMemory=333159688,runtime.maxMemory=2147483648,runtime.totalMemory=1047527424,runtime.uptime=2086366,runtime.usedMemory=714367736, labels=[]}
04:11:08,603  INFO || - [LifecycleService] Thread-2286 - hz.client_69 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20210926 - 8866289) is SHUTDOWN
04:11:08,603  INFO || - [LifecycleService] Thread-2286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
04:11:08,603  WARN || - [Node] Thread-2286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Terminating forcefully...
04:11:08,603  INFO || - [Node] Thread-2286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
04:11:08,603  INFO || - [MockServer] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
04:11:08,603  INFO || - [MockServer] Thread-2286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
04:11:08,603  INFO || - [MembershipManager] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Removing Member [127.0.0.1]:5702 - aeff2ef1-496b-41c7-9640-515bc49169b5
04:11:08,603  INFO || - [PartitionStateManager] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Storing snapshot of partition assignments while removing UUID aeff2ef1-496b-41c7-9640-515bc49169b5
04:11:08,604  INFO || - [ClusterService] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - 5a8ad93f-f227-4bda-a07c-d5a4f481bd4e this
]

04:11:08,604  INFO || - [Node] Thread-2286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Shutting down node engine...
04:11:08,604  INFO || - [TransactionManagerService] hz.nervous_lalande.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: aeff2ef1-496b-41c7-9640-515bc49169b5
04:11:08,607  INFO || - [NodeExtension] Thread-2286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
04:11:08,607  INFO || - [Node] Thread-2286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
04:11:08,607  INFO || - [LifecycleService] Thread-2286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
04:11:08,607  INFO || - [LifecycleService] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
04:11:08,607  WARN || - [Node] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Terminating forcefully...
04:11:08,607  INFO || - [Node] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
04:11:08,607  INFO || - [Node] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down node engine...
04:11:08,608  WARN || - [Invocation] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.internal.partition.operation.PromotionCommitOperation{serviceName='hz:core:partitionService', identityHash=1214934170, partitionId=-1, replicaIndex=0, callId=-18383, invocationTime=1632715868604 (2021-09-27 04:11:08.604), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=2147483647, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1632715868604, firstInvocationTime='2021-09-27 04:11:08.604', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, current value: true, offered value: ExceptionalResult{cause=com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!}
java.lang.Exception: null
	at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1253) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1230) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.completeExceptionallyInternal(AbstractInvocationFuture.java:1223) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.completeExceptionally(Invocation.java:679) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.notifyThrowable(Invocation.java:385) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.notifyError(Invocation.java:329) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.shutdown(InvocationRegistry.java:229) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.shutdownInvocations(OperationServiceImpl.java:534) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:540) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.instance.impl.Node.shutdownServices(Node.java:591) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.instance.impl.Node.shutdown(Node.java:530) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:101) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.instance.impl.LifecycleServiceImpl.terminate(LifecycleServiceImpl.java:89) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.shutdown(TestNodeRegistry.java:123) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.terminate(TestNodeRegistry.java:113) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at com.hazelcast.test.TestHazelcastInstanceFactory.terminateAll(TestHazelcastInstanceFactory.java:374) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.test.TestHazelcastFactory.terminateAll(TestHazelcastFactory.java:183) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$supportAfterClass$2(SimpleTestInClusterSupport.java:119) ~[hazelcast-5.1-SNAPSHOT-tests.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
04:11:08,612  INFO || - [NodeExtension] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
04:11:08,612  INFO || - [Node] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
04:11:08,612  INFO || - [LifecycleService] Thread-2286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
04:11:08,613  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:6401 [dev] [5.1-SNAPSHOT] [127.0.0.1]:6401 is SHUTTING_DOWN
04:11:08,613 DEBUG || - [JobCoordinationService] Time-limited test - [127.0.0.1]:6401 [dev] [5.1-SNAPSHOT] Added a shutting-down member: 90526d39-0041-4ba6-ac70-32edf0b9cc2a
04:11:08,614  INFO || - [Node] Time-limited test - [127.0.0.1]:6401 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
04:11:08,614  INFO || - [Node] Time-limited test - [127.0.0.1]:6401 [dev] [5.1-SNAPSHOT] Shutting down node engine...
04:11:08,616  INFO || - [NodeExtension] Time-limited test - [127.0.0.1]:6401 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
04:11:08,616  INFO || - [Node] Time-limited test - [127.0.0.1]:6401 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
04:11:08,616  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:6401 [dev] [5.1-SNAPSHOT] [127.0.0.1]:6401 is SHUTDOWN
```

**Comment by slavagithub** [comment] 2021-11-29 11:31
The same on Master, Sonar for
- com.hazelcast.jet.sql.SqlUnionTest.com.hazelcast.jet.sql.SqlUnionTest
- com.hazelcast.jet.sql.impl.connector
- com.hazelcast.jet.sql.impl.expression
- com.hazelcast.jet.sql.impl.parse
- com.hazelcast.jet.sql_slow
See http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/lastCompletedBuild/testReport/

**Comment by slavagithub** [comment] 2021-12-03 13:31
The same for ImbJDK8-fips - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/362/testReport/

**Comment by slavagithub** [comment] 2021-12-13 18:44
The same on Zulu, JDK16 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/30/#showFailuresLink

**Comment by slavagithub** [comment] 2021-12-17 18:41
Still fails for sonar, 5.0.z, for ;
com.hazelcast.jet.sql_slow.MapIndexScanPMigrationStressTest.com.hazelcast.jet.sql_slow.MapIndexScanPMigrationStressTest
com.hazelcast.jet.sql_slow.JetSqlSlowIndexTest.com.hazelcast.jet.sql_slow.JetSqlSlowIndexTest
see http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/80/testReport/

**Comment by slavagithub** [comment] 2021-12-28 10:55
51 test still fail on Sonar, Oracle JDK11 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1082/testReport/

**Comment by slavagithub** [comment] 2021-12-28 11:02
167 non-sql tests are also failed - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-EE-master-ZuluJDK11/168/testReport/

**Comment by viliam-durina** [comment] 2021-12-29 08:43
I looked into this issue, at the last case reported [here](https://github.com/hazelcast/hazelcast/issues/19638#issuecomment-1002018541), it looks like some issue with parallel test execution. In 3 test failures, the instance that haven't been shut down is an instance created by `testBouncingClusterAddsWanReplication`. The funny part is that the `testBouncingClusterAddsWanReplication` is from `WanAddConfigTest`. This method name is logged in all three instances of failures that occurred in other classes that I checked. Anyone more familiar with the test runners who might know the cause?

**Comment by viliam-durina** [comment] 2021-12-29 20:20
Same seems to have occurred here: https://github.com/hazelcast/hazelcast/issues/19884#issuecomment-981523613. Here the `SqlOrderBySlowTest` is accused of not shutting down its instances, but the leftover instance was created by `MapScanMigrationStressTest.stressTest_sortedIndex()`. However there are other issues in that issue, so I can't close it as a duplicate.

**Comment by slavagithub** [comment] 2021-12-31 16:58
currently, 6 tests are failed for Master, Oracle JDK8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8-nightly/877/testReport/

**Comment by slavagithub** [comment] 2021-12-31 17:08
around 50 fail with the master, sonar - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1085/#showFailuresLink

**Comment by olukas** [comment] 2022-01-03 09:40
Failed again on Sonar build: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1088/testReport/

**Comment by slavagithub** [comment] 2022-01-25 07:53
Fails on 5.0.z, sonar for com.hazelcast.jet.sql_slow.MapIndexScanPMigrationStressTest.com.hazelcast.jet.sql_slow.MapIndexScanPMigrationStressTest - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/119/testReport/com.hazelcast.jet.sql_slow/MapIndexScanPMigrationStressTest/com_hazelcast_jet_sql_slow_MapIndexScanPMigrationStressTest/

**Comment by slavagithub** [comment] 2022-01-25 07:58
failed on 5.0.z, Oracle, JDK8 - com.hazelcast.jet.sql_slow.MapIndexScanPMigrationStressTest.com.hazelcast.jet.sql_slow.MapIndexScanPMigrationStressTest

**Comment by olukas** [comment] 2022-02-01 07:21
Failed on `5.0.z` branch on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/126/testReport/

**Comment by olukas** [comment] 2022-02-01 07:22
Failed on `5.0.z` branch with Oracle JDK 8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK8-nightly/19/testReport/

**Comment by olukas** [comment] 2022-02-08 13:52
Reopening this for `5.0.3` milestone since it's still failing on `5.0.z` branch, for example on Sonar build: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/133/testReport/com.hazelcast.jet.sql_slow/JetSqlSlowIndexTest/com_hazelcast_jet_sql_slow_JetSqlSlowIndexTest/

@viliam-durina can you please backport the fix to `5.0.z` branch?

**Comment by viliam-durina** [comment] 2022-02-09 17:22
@olukas  done in #20662

**Comment by slavagithub** [comment] 2022-02-21 10:21
failed still for 5.0.z, IBM JDK8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8-nightly/22/testReport/junit/com.hazelcast.jet.sql_slow/JetSqlSlowIndexTest/com_hazelcast_jet_sql_slow_JetSqlSlowIndexTest/

**Comment by viliam-durina** [comment] 2022-02-22 13:18
In this case it seems the leaked instance was started by `SqlSplitBrainTest#test_indexScan`. But studying the code, I couldn't find how an instance could leak there...

**Comment by olukas** [comment] 2022-02-25 07:23
Failed on `5.0.z` branch with Zulu JDK 16: 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK16-nightly/22/testReport/com.hazelcast.jet.sql_slow/JetSqlSlowIndexTest/com_hazelcast_jet_sql_slow_JetSqlSlowIndexTest/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK16-nightly/22/testReport/com.hazelcast.jet.sql/SqlSplitBrainTest/test_indexScan/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK16-nightly/22/testReport/com.hazelcast.jet.sql_slow/SqlOrderBySlowTest/testSelectWithOrderByDescDescAsc_serializationMode_SERIALIZABLE__inMemoryFormat_OBJECT__membersCount_3_/

**Comment by olukas** [comment] 2022-03-29 06:01
`com.hazelcast.sql.impl.schema.IMapResolverTest.com.hazelcast.sql.impl.schema.IMapResolverTest` also failed with `Instances haven't been shut down`. It failed on `5.1.z` branch on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/177/testReport/com.hazelcast.sql.impl.schema/IMapResolverTest/com_hazelcast_sql_impl_schema_IMapResolverTest/

**Comment by olukas** [comment] 2022-05-31 16:59
`com.hazelcast.sql.impl.schema.IMapResolverTest` failed on `5.1.z` branch on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/239/testReport/com.hazelcast.sql.impl.schema/IMapResolverTest/com_hazelcast_sql_impl_schema_IMapResolverTest/

**Comment by olukas** [comment] 2022-08-25 06:18
`com.hazelcast.sql.impl.schema.IMapResolverTest` failed on `5.1.z` branch on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/310/testReport/com.hazelcast.sql.impl.schema/IMapResolverTest/com_hazelcast_sql_impl_schema_IMapResolverTest/

**Comment by viliam-durina** [comment] 2022-11-25 13:22
Last happened 3 months ago.

**Closed by viliam-durina** 2022-11-25 13:22 UTC
Labels: Type: Test-Failure, Source: Internal, Team: SQL, to-jira
