### ISSUE TITLE
CPMemberAddRemoveTest.when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#14550] opened 2019-02-22 12:25 UTC
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/547/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown/

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest$25.run(CPMemberAddRemoveTest.java:952)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown(CPMemberAddRemoveTest.java:948)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tezc** [comment] 2019-02-26 09:08
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK7/9/testReport/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown/

**Comment by tezc** [comment] 2019-02-28 10:13
_master_ (commit 358724cfa52179609f38bb2c245f7bc310cf4ab4)

http://jenkins.hazelcast.com/job/Hazelcast-3.x-OracleJDK11/9/testReport/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown/

**Stacktrace**
```
java.lang.AssertionError: Future has not completed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport$7.run(HazelcastTestSupport.java:1023)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1307)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1333)
	at com.hazelcast.test.HazelcastTestSupport.assertCompletesEventually(HazelcastTestSupport.java:1020)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown(CPMemberAddRemoveTest.java:973)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by PavloBida** [comment] 2021-01-14 10:50
Got this test [failing](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-CorrettoJDK11/101/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown/) again but since the root cause is different - closing current issue again and will report another one.

**Closed by PavloBida** 2021-01-14 10:50 UTC
Labels: Module: CP Subsystem, Source: Internal, Team: Core, Type: Test-Failure
