### ISSUE TITLE
Test failure MapLockTest.testLockTTLKey

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#15521] opened 2019-09-05 12:57 UTC
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2489/testReport/junit/com.hazelcast.map/MapLockTest/testLockTTLKey/

```
Error Message
TTL of KEY has expired, KEY is locked, we expect VAL expected:<val> but was:<null>
Stacktrace
java.lang.AssertionError: TTL of KEY has expired, KEY is locked, we expect VAL expected:<val> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.map.MapLockTest.testLockTTLKey(MapLockTest.java:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by devozerov** [comment] 2019-09-06 08:06
I failed to reproduce it locally. Analysis of expiration path doesn't show any suspicious places - entry should not be evicted while the lock is held (`AbstractEvictableRecordStore.getOrNullIfExpired`).

However, the test itself is inherently racy - it first puts the value, then acquires the lock. In principle, it is possible that tasks would be scheduled to the partition thread as follows:
1) `PutOperation`
2) `ClearExpiredOperation`
3) `LockOperation`

This is unlikely provided the default delay of `ClearExpiredOpeartion` of 5 seconds, but if for some reason the system became slow for several seconds, it is possible. Now if we look at test time distribution [1], we will see that the faulty test run took 5.7s to complete, much longer than normally. So I suppose that some hiccup might be the cause of the failure. The suggested change is to switch `map.put` and `map.lock` operations. In this case, expiration could never happen before the lock is acquired.

@petrpleshachkov Do you have any objections on that change?

[1] http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2489/testReport/junit/com.hazelcast.map/MapLockTest/testLockTTLKey/history/

**Comment by petrpleshachkov** [comment] 2019-09-06 08:24
@devozerov, I am fine with the change. Also, please notice that since we run the tests in parallel the delays are unpredictable and my experience shows that even 10 secs delays are not rare.

**Comment by tezc** [comment] 2019-09-06 08:29
Just fyi : 
```
Hiccups measured while running test 'testLockTTLKey(com.hazelcast.map.MapLockTest):'
11:39:20, accumulated pauses: 1388 ms, max pause: 446 ms, pauses over 1000 ms: 0
11:39:25, accumulated pauses: 2284 ms, max pause: 819 ms, pauses over 1000 ms: 0
11:39:30, accumulated pauses: 89 ms, max pause: 25 ms, pauses over 1000 ms: 0
```

**Comment by devozerov** [comment] 2019-09-06 08:56
PR: #15525

**Comment by Holmistr** [comment] 2019-09-09 08:00
Fixed by https://github.com/hazelcast/hazelcast/pull/15525

**Closed by Holmistr** 2019-09-09 08:00 UTC
Labels: Module: IMap, Source: Internal, Team: Core, Type: Test-Failure
