### ISSUE TITLE
Can no longer override serialization for ArrayList

### ISSUE THREAD

**Issue by markathomas** [hazelcast/hazelcast#7413] opened 2016-01-27 19:40 UTC
Hazelcast 3.6 fails to start with 

Factory method 'newHazelcastInstance' threw exception; nested exception is java.lang.IllegalArgumentException: [class java.util.ArrayList] serializer cannot be overridden!

this is a huge problem for us since we use Kryo to serialize our objects and if an ArrayList is not serialized using Kryo the de-serialization will fail.  Has Hazelcast changed how it has done serialization such that this should now work?  Is there some workaround or do I have to custom build Hazelcast now?

**Comment by markathomas** [comment] 2016-01-27 19:54
Looking at the code it seems all should be well seeing as how the SerializationService is used for each element in the ArrayList.  Am I reading this correctly?

**Comment by sancar** [comment] 2016-01-27 20:56
Yes, we made it so that can not be overridden anymore.
As workaround, you should register Serializer for the type that ArrayList will hold instead of whole ArrayList.

**Comment by markathomas** [comment] 2016-01-27 22:26
And why was this change made?  As a paying customer I don't appreciate apparently random changes which are not documented and break my app.  After removing the serializer for ArrayList deserialization fails with 

2016-01-27 15:58:43,413 [CallStationWM-10.1.8.12-thread-1] ERROR: RealtimeCallDAOImpl: Error searching for cache objects with predicate (status IN (Ringing) AND DispatchGroupPredicate[
  dispatchGroupNames=[bay-village-pd]
])
com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.EOFException
>---at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:61)
>---at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:176)
>---at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:234)
>---at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:378)
>---at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184)
>---at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137)
>---at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
>---at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
>---at ------ End remote and begin local stack-trace ------.(Unknown Source)
>---at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:385)
>---at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:335)
>---at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223)
>---at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
>---at com.hazelcast.map.impl.query.MapQueryEngineImpl.addResultsOfPredicate(MapQueryEngineImpl.java:528)
>---at com.hazelcast.map.impl.query.MapQueryEngineImpl.invokeQueryAllPartitions(MapQueryEngineImpl.java:434)
>---at com.hazelcast.map.impl.tx.TransactionalMapProxy.values(TransactionalMapProxy.java:364)
>---at com.clj2.business.lib.grid.cache.HazelcastCacheDelegate.values(HazelcastCacheDelegate.java:435)
>---at com.clj2.business.dao.impl.AbstractGridObjectDAOSupport.query(AbstractGridObjectDAOSupport.java:686)
>---at com.clj2.business.dao.impl.AbstractGridObjectDAOSupport.query(AbstractGridObjectDAOSupport.java:669)
>---at com.clj2.business.dao.impl.AbstractGridObjectDAOSupport.query(AbstractGridObjectDAOSupport.java:654)
>---at com.clj2.business.dao.impl.RealtimeCallDAOImpl.findCallsByStatus(RealtimeCallDAOImpl.java:214)
>---at com.clj2.business.dao.impl.RealtimeCallDAOImpl.findRingingCalls(RealtimeCallDAOImpl.java:206)
>---at com.clj2.business.service.impl.CallServiceImpl.getHighestPriorityCallToAnswer_aroundBody20(CallServiceImpl.java:558)
>---at com.clj2.business.service.impl.CallServiceImpl$AjcClosure21.run(CallServiceImpl.java:1)
>---at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:59)
>---at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:65)
>---at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
>---at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:63)
>---at com.clj2.business.service.impl.CallServiceImpl.getHighestPriorityCallToAnswer_aroundBody22(CallServiceImpl.java:516)
>---at com.clj2.business.service.impl.CallServiceImpl$AjcClosure23.run(CallServiceImpl.java:1)
>---at org.dellroad.stuff.spring.RetryTransactionAspect.ajc$around$org_dellroad_stuff_spring_RetryTransactionAspect$1$878f3a34proceed(RetryTransactionAspect.aj:106)
>---at org.dellroad.stuff.spring.RetryTransactionAspect$RetryTransactionAspect$1.run(RetryTransactionAspect.aj:179)
>---at org.dellroad.stuff.java.ThreadLocalHolder.invoke(ThreadLocalHolder.java:111)
>---at org.dellroad.stuff.spring.RetryTransactionAspect.ajc$around$org_dellroad_stuff_spring_RetryTransactionAspect$1$878f3a34(RetryTransactionAspect.aj:176)
>---at com.clj2.business.service.impl.CallServiceImpl.getHighestPriorityCallToAnswer(CallServiceImpl.java:516)
>---at com.clj2.ui.app.call.command.AnswerCommand$1.run(AnswerCommand.java:33)
>---at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
>---at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>---at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
>---at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
>---at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>---at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>---at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.EOFException
>---at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readByte(ByteArrayObjectDataInput.java:145)
>---at com.hazelcast.map.impl.query.QueryPartitionOperation.readInternal(QueryPartitionOperation.java:68)
>---at com.hazelcast.spi.Operation.readData(Operation.java:557)
>---at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
>---at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
>---at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
>---at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)
>---at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:234)
>---at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:378)
>---at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184)
>---at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137)
>---at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
>---at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)

as well as these

2016-01-27 16:09:05,021 [hz.e911.response] ERROR: [10.1.3.10]:5701 [e911] [3.6] Failed to process response: Packet{header=3, isResponse=true, isOperation=true, isEvent=false, partitionId=-1, conn=Connection [/10
com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type 410514492. This exception is likely to be caused by differences in the serialization configuration bet
>---at com.hazelcast.internal.serialization.impl.AbstractSerializationService.newHazelcastSerializationException(AbstractSerializationService.java:183)
>---at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:210)
>---at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
>---at com.hazelcast.internal.serialization.impl.ArrayListStreamSerializer.read(ArrayListStreamSerializer.java:49)
>---at com.hazelcast.internal.serialization.impl.ArrayListStreamSerializer.read(ArrayListStreamSerializer.java:31)
>---at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
>---at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:214)
>---at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
>---at com.hazelcast.spi.impl.operationservice.impl.responses.NormalResponse.readData(NormalResponse.java:102)
>---at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
>---at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
>---at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
>---at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)
>---at com.hazelcast.spi.impl.operationservice.impl.ResponsePacketHandlerImpl.handle(ResponsePacketHandlerImpl.java:44)
>---at com.hazelcast.spi.impl.operationservice.impl.AsyncResponsePacketHandler$ResponseThread.process(AsyncResponsePacketHandler.java:130)
>---at com.hazelcast.spi.impl.operationservice.impl.AsyncResponsePacketHandler$ResponseThread.doRun(AsyncResponsePacketHandler.java:122)
>---at com.hazelcast.spi.impl.operationservice.impl.AsyncResponsePacketHandler$ResponseThread.run(AsyncResponsePacketHandler.java:99)
2016-01-27 16:09:05,073 [hz.e911.response] ERROR: [10.1.3.10]:5701 [e911] [3.6] Failed to process response: Packet{header=3, isResponse=true, isOperation=true, isEvent=false, partitionId=-1, conn=Connection [/10
com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type -2064529738. This exception is likely to be caused by differences in the serialization configuration b
>---at com.hazelcast.internal.serialization.impl.AbstractSerializationService.newHazelcastSerializationException(AbstractSerializationService.java:183)
>---at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:210)
>---at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
>---at com.hazelcast.internal.serialization.impl.ArrayListStreamSerializer.read(ArrayListStreamSerializer.java:49)
>---at com.hazelcast.internal.serialization.impl.ArrayListStreamSerializer.read(ArrayListStreamSerializer.java:31)
>---at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
>---at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:214)
>---at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
>---at com.hazelcast.spi.impl.operationservice.impl.responses.NormalResponse.readData(NormalResponse.java:102)
>---at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
>---at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
>---at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
>---at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)
>---at com.hazelcast.spi.impl.operationservice.impl.ResponsePacketHandlerImpl.handle(ResponsePacketHandlerImpl.java:44)
>---at com.hazelcast.spi.impl.operationservice.impl.AsyncResponsePacketHandler$ResponseThread.process(AsyncResponsePacketHandler.java:130)
>---at com.hazelcast.spi.impl.operationservice.impl.AsyncResponsePacketHandler$ResponseThread.doRun(AsyncResponsePacketHandler.java:122)
>---at com.hazelcast.spi.impl.operationservice.impl.AsyncResponsePacketHandler$ResponseThread.run(AsyncResponsePacketHandler.java:99)

all of this was working in versions previous to 3.6

**Comment by markathomas** [comment] 2016-01-27 22:27
I should note that we have serializers registered for all objects that go over the grid.

**Comment by sancar** [comment] 2016-02-17 11:48
Since it is not a bug but a design decision I am closing the issue.

**Closed by sancar** 2016-02-17 11:48 UTC
Labels: Team: Client
