### ISSUE TITLE
java.io.NotSerializableException in 3.6-EA3

### ISSUE THREAD

**Issue by manishonline** [hazelcast/hazelcast#7292] opened 2016-01-11 16:06 UTC
Has it been mandatory for all classes to implement Serializable interface in Hazelcast 3.6-EA3?

My current version is using 3.5.2 and quite a few of my classes don't implement Serializable while they are being serialized using StreamSerliazer. After upgrading to 3.6-EA2, ConfigBean and couple other classes that don't implement Serializable throw below exception.
```
Caused by: java.io.NotSerializableException: ConfigBean
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at java.util.ArrayList.writeObject(ArrayList.java:742)
	at sun.reflect.GeneratedMethodAccessor1107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by jerrinot** [comment] 2016-01-11 16:28
Hello @manishonline,

thank you for reporting this issue. It's absolutely not mandatory to implement `j.i.Serializable`. Can you please share your domain class and StreamSerialize implementaion?

**Comment by manishonline** [comment] 2016-01-12 02:45
///Domain Class ::
public class ConfigBean {
    private String fieldName;
    private String displayName;
    private String fieldType;
    private String description;
    private String displayFormat;
    private String uiControlName;
    private String datasourceControlName;
    private String categoryControlName;
    private String filterControlType;
    private String guiValidation;
    private List<String> values;
    private String dropdownType;
    private boolean isFilter;

    public String getFieldName() {
        return this.fieldName;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    public String getFieldType() {
        return this.fieldType;
    }

    public String getDescription() {
        return this.description;
    }

    public String getDisplayFormat() {
        return this.displayFormat;
    }

    public String getUiControlName() {
        return this.uiControlName;
    }

    public String getDatasourceControlName() {
        return this.datasourceControlName;
    }

    public String getCategoryControlName() {
        return this.categoryControlName;
    }

    public String getFilterControlType() {
        return this.filterControlType;
    }

    public String getGuiValidation() {
        return this.guiValidation;
    }

    public List<String> getValues() {
        return this.values;
    }

    public String getDropdownType() {
        return this.dropdownType;
    }

    public boolean isFilter() {
        return this.isFilter;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public void setFieldType(String fieldType) {
        this.fieldType = fieldType;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setDisplayFormat(String displayFormat) {
        this.displayFormat = displayFormat;
    }

    public void setUiControlName(String uiControlName) {
        this.uiControlName = uiControlName;
    }

    public void setDatasourceControlName(String datasourceControlName) {
        this.datasourceControlName = datasourceControlName;
    }

    public void setCategoryControlName(String categoryControlName) {
        this.categoryControlName = categoryControlName;
    }

    public void setFilterControlType(String filterControlType) {
        this.filterControlType = filterControlType;
    }

    public void setGuiValidation(String guiValidation) {
        this.guiValidation = guiValidation;
    }

    public void setValues(List<String> values) {
        this.values = values;
    }

    public void setDropdownType(String dropdownType) {
        this.dropdownType = dropdownType;
    }

    public void setFilter(boolean isFilter) {
        this.isFilter = isFilter;
    }

    public ConfigBean() {
    }
}

**Comment by manishonline** [comment] 2016-01-12 02:46
//Serializer
public class ConfigBeanSerializer implements StreamSerializer<ConfigBean> {
    @Override
    public void write(ObjectDataOutput out, ConfigBean object) throws IOException {
        out.writeObject(object.getDisplayName());
        out.writeObject(object.getDatasourceControlName());
        out.writeObject(object.getFieldName());
        out.writeObject(object.getFieldType());
        out.writeObject(object.getUiControlName());
        out.writeObject(object.getCategoryControlName());
        out.writeObject(object.getFilterControlType());
        out.writeObject(object.getValues());
        out.writeObject(object.getDropdownType());
        out.writeObject(object.getDescription());
        out.writeObject(object.getDisplayFormat());
        out.writeObject(object.isFilter());
    }

    @Override
    public ConfigBean read(ObjectDataInput in) throws IOException {
        ConfigBean configBean = new ConfigBean();
        configBean.setDisplayName((String)in.readObject());
        configBean.setDatasourceControlName((String) in.readObject());
        configBean.setFieldName((String) in.readObject());
        configBean.setFieldType((String) in.readObject());
        configBean.setUiControlName((String) in.readObject());
        configBean.setCategoryControlName((String) in.readObject());
        configBean.setFilterControlType((String) in.readObject());
        configBean.setValues((List<String>) in.readObject());
        configBean.setDropdownType((String)in.readObject());
        configBean.setDescription((String)in.readObject());
        configBean.setDisplayFormat((String)in.readObject());
        configBean.setFilter((boolean)in.readObject());
        return configBean;
    }

    @Override
    public int getTypeId() {
        return IpdsHazelcastSerializerTypeIds.CONFIG_BEAN_SERIALIZER;
    }

    @Override
    public void destroy() {

    }

**Comment by manishonline** [comment] 2016-01-12 02:46
Exception :+1: 
Caused by: java.io.NotSerializableException: com.numerix.ipds.common.util.bean.ConfigBean
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at java.util.ArrayList.writeObject(ArrayList.java:742)
	at sun.reflect.GeneratedMethodAccessor1346.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at java.util.HashMap.writeObject(HashMap.java:1129)
	at sun.reflect.GeneratedMethodAccessor471.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.writeUnshared(ObjectOutputStream.java:414)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:244)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:41)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:197)
	... 22 more

**Comment by manishonline** [comment] 2016-01-12 02:48
//Serialization config :

            <hz:serialization>
                <hz:serializers>
                    <hz:serializer type-class="ConfigBean" class-name="ConfigBeanSerializer"/>
                </hz:serializers>
            </hz:serialization>

**Comment by asimarslan** [comment] 2016-01-12 08:35
Hi @manishonline,

The problem is just a configuration issue. You should register your ConfigBeanSerializer with package names in your config as;
``` 
       <hz:serialization>
            <hz:serializers>
                <hz:serializer type-class="THE_PACKAGE_NAME_OF_CONFIG_BEAN.ConfigBean" class-name="THE_PACKAGE_NAME_OF_SERIALIZER.ConfigBeanSerializer"/>
            </hz:serializers>
        </hz:serialization>
```

Note: As you cannot register your ConfigBeanSerializer, the default java serializer is used and the ones without the serializable interface cause this.

**Comment by jerrinot** [comment] 2016-01-12 08:39
@asimarslan: has there been any behaviour change on our side since 3.5.2?

**Comment by asimarslan** [comment] 2016-01-12 08:49
3.6 has major serialization improvement and bug fixes. This includes some behaviour changes explained in the documentation. But this issue is clearly a configuration issue. The explanation in my previous comment is valid for the previous  hazelcast versions too.

**Comment by noctarius** [comment] 2016-01-12 08:54
But shouldn't an invalid configuration being rejected and startup of the node stopped immediately?

**Comment by asimarslan** [comment] 2016-01-12 09:02
@noctarius yes you are right. I tested 3.6, it does not start.

**Comment by noctarius** [comment] 2016-01-12 09:05
Ah ok, so now it stops, perfect :)

**Comment by noctarius** [comment] 2016-01-12 09:08
PS: @Serdaro is there no migration guide for 3.6 anymore or a separate document? (just looked at the documentation, this would clearly be something to add)

**Comment by manishonline** [comment] 2016-01-12 09:30
Hi Asim,

I have removed the package name in the issue for brevity sake. The same
setup works pretty well with 3.5.2 and 3.5.4 now.

Right now I have my serliazer implementation for ArrayList and HashMap. 3.6
gave  me error about these serializers can't be overridden. So I had to
comment them out.

I'll check and see if i can post the full domain model and serializers with
full package name. But am sure that is not causing the issue.



On Tuesday, January 12, 2016, Asım Arslan <notifications@github.com> wrote:

> Hi @manishonline <https://github.com/manishonline>,
>
> The problem is just a configuration issue. You should register your
> ConfigBeanSerializer with package names in your config as;
>
>        <hz:serialization>
>             <hz:serializers>
>                 <hz:serializer type-class="THE_PACKAGE_NAME_OF_CONFIG_BEAN.ConfigBean" class-name="THE_PACKAGE_NAME_OF_SERIALIZER.ConfigBeanSerializer"/>
>             </hz:serializers>
>         </hz:serialization>
>
> Note: As you cannot register your ConfigBeanSerializer, the default java
> serializer is used and the ones without the serializable interface cause
> this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hazelcast/hazelcast/issues/7292#issuecomment-170837783>
> .
>


-- 
Sent from MetroMail

**Comment by asimarslan** [comment] 2016-01-12 09:36
@manishonline ,

Hazelcast has built in serializer for ArrayList and LinkedList but not for HashMap.

**Comment by jerrinot** [comment] 2016-01-18 09:46
hello @manishonline: is there any update on your side?

**Comment by manishonline** [comment] 2016-01-20 14:13
Hi Jaromir,

I will get back to you on this.

I had to rollback the hazelcast 3.6 upgrade and with 3.5.4, my current
application is working fine.

I'll try 3.6 upgrade in the coming week when I get time. I'll update this
thread the with my observations.

Thanks,
Manish

On Monday, January 18, 2016, Jaromir Hamala <notifications@github.com>
wrote:

> hello @manishonline <https://github.com/manishonline>: is there any
> update on your side?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hazelcast/hazelcast/issues/7292#issuecomment-172480551>
> .
>


-- 
Sent from MetroMail

**Comment by jerrinot** [comment] 2016-04-25 09:28
hi @manishonline,

do you have any update you could share?

**Comment by jerrinot** [comment] 2016-05-23 06:46
I'm closing this issue as there has not been an update from the reported.
@manishonline: feel free to re-open it if you have an update.

**Closed by jerrinot** 2016-05-23 06:46 UTC
Labels: Team: Core, Type: Defect
