### ISSUE TITLE
Hazelcast 3.5.x Memory Leak using IMap

### ISSUE THREAD

**Issue by jocelynlepage** [hazelcast/hazelcast#6317] opened 2015-09-29 18:00 UTC
We are experimenting memory leaks when using IMaps.

Based on our observations, the leak seems related to the fact that we're regularly destroying maps.
Based on Heap analysis, the culprit seems to be around com.hazelcast.map.impl.MapServiceContextImpl.

Setup: 
- Hazelcast 3.5.2, JDK 1.7/1.8, reproduced on Linux/Windows 7 and Mac OSX 10.9.5
- 2 nodes with embedded Hazelcast (e.g. not using separate client JVMs)

Scenario:
- One of our node is creating a new IMap roughly once per minute and put stuff in it at regular interval (few hundreds to few thousands per minute).
- Few seconds/minutes later, the other node is removing data from the map, and if the map is empty, destroys the map. 
- We do notice a steady growth of the heap usage, which seems related to Hazelcast IMaps internal management.

We did run a couple of variants with the following observations:
- Hazelcast versions 3.5.1 and 3.5.2 exhibits the same memory leak behavior
- We tested both with JMX/ManCenter enabled and disabled, without changes on the results.
- We disable Map "rotation" (e.g. a single map is used instead) and we didn't noticed the memory leak.
- We also tested with version 3.4.6, problem is NOT present - seems something introduced in 3.5.x

We wanted to update from 3.4.x since as our production system is affected by another memory leak documented here: https://github.com/hazelcast/hazelcast/issues/4888

Please find a small project on GitHub which demonstrates the problem: https://github.com/jocelynlepage/hz-map-leak
This project includes a couple of heap dump files (produced with jmap) provided for analysis.

Thanks,
Jocelyn

**Comment by jerrinot** [comment] 2015-09-30 10:32
@jocelynlepage: Thank you for reporting the issue and for a great reproducer!

I managed to reproduce it. I can see that approximately half of partitions on each member are cleaned, but the other half still retains data. I reckon it's related to backups.

**Comment by jerrinot** [comment] 2015-09-30 10:54
Heapdump: http://54.87.52.100/~jara/dumps/issue6317/java_pid14221.0001_.hprof.gz
For whoever will fix it: Please ping me so can delete the dump.

**Comment by jerrinot** [comment] 2015-09-30 20:40
I believe it's a side-effect of #5649

Because of [this check](https://github.com/hazelcast/hazelcast/pull/5649/files#diff-3c46796ecaec736f1ba18e382ec50a00R189) it `MapPartitionDestroyOperation` is executed on partition owners only -> The backup are not touched at all. I believe the `MapPartitionDestroyOperation` should implement the `BackupAwareOperation` interface.

**Comment by bwzhang2011** [comment] 2015-10-02 14:11
@jerrinot, any update with such issue ? does it only occur under the specific scenery as the one described above ?

**Comment by jerrinot** [comment] 2015-10-02 14:22
@bwzhang2011: PRs fixing the leak in both master and maintenance branches are pending. This fix will be part of Hazelcast 3.5.3 which should be released soon.

**Closed** 2015-10-02 15:08 UTC
Labels: Team: Core, Type: Critical, Type: Defect, VERIFIED

**Comment by bwzhang2011** [comment] 2015-10-02 15:56
@jerrinot, thanks for feed back and make quick fix and backported plan. looking forward to new hz3.5.3 releasing and more issues to be fixed afterwards.

**Comment by jocelynlepage** [comment] 2015-10-05 12:46
Thanks guys for the quick turnaround. 
Looking forward to update to 3.5.3 once available.

**Comment by IsuraD** [comment] 2016-02-22 23:33
HI jerrinot,

Is this issue is fixed in 3.5.3 ?

**Comment by jerrinot** [comment] 2016-02-23 08:28
@IsuraD: Hi, it is. See #6400

**Comment by dushaniw** [comment] 2018-09-04 11:55
Can I whether anyone faced the similar issue in 3.0.1 version?

**Comment by jerrinot** [comment] 2018-09-04 12:02
@dushaniw 3.10.1 or 3.0.1?

**Comment by dushaniw** [comment] 2018-09-04 12:16
Its 3.0.x version?

**Comment by fayaz-rvce** [comment] 2019-10-09 11:25
We are facing a similar bug in Production. Even after removing entry from IMap, it can be still seen in heapdump.  We are using hazelcast 3.7.2 version? Did anyone face this issue with latest version?
