### ISSUE TITLE
Cache.put always returning null

### ISSUE THREAD

**Issue by amit2103** [hazelcast/hazelcast#9214] opened 2016-11-03 19:40 UTC
Hey All,

We have a cache with the following config 

`  <map name="xyz-abc">
      <time-to-live-seconds>300</time-to-live-seconds>
      <max-size policy="PER_NODE">50</max-size>
      <eviction-policy>LRU</eviction-policy>
    </map>

And then we have try to use getMap to get an instance of the above map.

However when we are putting any data in  using set or put no value is actually set (verified by trying get). We are upgrading from 3.4.1 any ideas why this can happen?

**Comment by ahmetmircik** [comment] 2016-11-03 20:19
Hi,
Seems the cause is eviction. In your configuration, max-size is 50 and default partition count is 271 imap translates this to partition max-size and simply calculates it like this: `50*member-count/271`. This means translated partition max-size will be around 1 and eviction will be triggered for every put.

Lower partition count or higher max-size can solve this issue. You can play values of them.

**Comment by ahmetmircik** [comment] 2016-11-04 10:38
Hi, 
It is 271. You can set it for 3.4.1 like this:

```
Config config = new Config();
config.setProperty("hazelcast.partition.count", "100");
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
```

**Comment by ahmetmircik** [comment] 2016-11-04 10:38
Hi, 
It is 271. You can set it for 3.4.1 like this:

```
Config config = new Config();
config.setProperty("hazelcast.partition.count", "100");
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
```

**Comment by amit2103** [comment] 2016-11-04 13:56
Sorry I didnt expplain correctly, we want to use 3.7 so is there any other
config to do something similar?

**Comment by ahmetmircik** [comment] 2016-11-04 14:12
no other config, it is same in 3.7

**Comment by amit2103** [comment] 2016-11-04 20:45
Thanks one last question.

Also I wanted to understand one thing. 

if I set use this <max-size policy="PER_NODE">60000</max-size>, and I have five nodes then eveiction will occur after 1100 odd data is in cache right?

**Comment by ahmetmircik** [comment] 2016-11-04 20:53
yes when a partition reaches 1100, subsequent put-s will trigger eviction.

**Comment by amit2103** [comment] 2016-11-04 21:16
Okay...thanks that helps a lot. If we dont provide this config whats the
behaviour in that case?

**Comment by ahmetmircik** [comment] 2016-11-05 09:49
In that case, partition max-size will be calculated against default partition count like this: `60000*member-count/271`

**Comment by enesakar** [comment] 2016-11-08 14:13
I guess I can close the issue.

**Closed by enesakar** 2016-11-08 14:13 UTC
