### ISSUE TITLE
Ignored MapConfig after cluster recovering (down and restarted)

### ISSUE THREAD

**Issue by mumukiller** [hazelcast/hazelcast#14859] opened 2019-04-10 16:04 UTC
Hi all!

I'm using 3.10.6!
I haven't found similar issue (i'm not even sure that this is an issue)
So i'll try to explain by steps what's going on:

- run hazelcast cluster
- cluster is up
- spring boot app connects to this cluster using MapConfig (TTL is set to some value N)
- cluster is down (all nodes are stopped manually or by unknown reason)
- cluster restarted
- new entries which are placed by spring boot application after restart do not contain TTL which is specified by MapConfig and will not be evicted

Is it correct behaviour?

I will try to provide an example if it's not correct

**Comment by ahmetmircik** [comment] 2019-04-11 07:25
Hi @mumukiller,

MapConfig changes during runtime is not persisted. After a runtime change, if you restart cluster, you lose the runtime changes. We have plans to support this but not yet supported.

**Comment by mumukiller** [comment] 2019-04-11 07:26
MapConfig has not changed during cluster down and up process

**Comment by ahmetmircik** [comment] 2019-04-11 07:29
can you please provide an example?

**Comment by mumukiller** [comment] 2019-04-11 07:40
Is it enough to provide a java app which checks that TTL is invalid or i should provide a some king of docker compose file with hazelcast instance and application instance?

**Comment by ahmetmircik** [comment] 2019-04-11 07:49
a simple java app will be enough.

**Comment by mumukiller** [comment] 2019-04-11 10:54
If you have any questions regarding this, please let me know
https://github.com/mumukiller/hazelcast-14859-demo/blob/master/steps-to-reproduce

**Comment by ahmetmircik** [comment] 2019-04-11 11:16
Thanks for the example, it made things clear. 

The problem is, the added MapConfig at this [line](https://github.com/mumukiller/hazelcast-14859-demo/blob/5992cf9c6bf2f5f92f25c2c15f9869acf27dfcf5/steps-to-reproduce#L20) was not persisted on cluster side so upon restart it was lost. Therefore the map you use [here](https://github.com/mumukiller/hazelcast-14859-demo/blob/5992cf9c6bf2f5f92f25c2c15f9869acf27dfcf5/steps-to-reproduce#L56) was created silently with default MapConfig and that default config has no expiration set on it. So entries put after this point were not expirable any more. 
This is the reason of what you saw. 

We have plans to persist config after a runtime change but this is not supported yet.

**Comment by mumukiller** [comment] 2019-04-11 11:43
Will you mark this as bug or add some explanation in documentation? It's pretty tricky behaviour which can cause unexpected consequences.

**Comment by ahmetmircik** [comment] 2019-04-11 11:59
Filed a documentation enhancement issue: https://github.com/hazelcast/hazelcast-reference-manual/issues/677

I will keep this issue open till we fix it. Thanks.

**Comment by Holmistr** [comment] 2021-12-14 09:37
This issue is kept in the 5.1 scope as it will be addressed by the dynamic configuration persistence feature.

**Comment by ramizdundar** [comment] 2022-01-17 08:38
Dynamic Configuration Persistence is implemented. You need to enable from the Hazelcast config to use it. This feature will be included in `5.1`. 

https://docs.hazelcast.com/hazelcast/5.1-beta-1/configuration/dynamic-config-options

**Closed by ramizdundar** 2022-01-17 08:38 UTC
Labels: Type: Enhancement, Team: Core, Source: Community, Module: Config
