### ISSUE TITLE
[cluster] MembershipFailureTest_withTCP.secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10939] opened 2017-07-17 14:05 UTC
```
java.lang.AssertionError: expected:<[127.0.0.1]:5702> but was:<[127.0.0.1]:5701>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddress(HazelcastTestSupport.java:924)
	at com.hazelcast.test.HazelcastTestSupport$14.run(HazelcastTestSupport.java:934)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1066)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1083)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddressEventually(HazelcastTestSupport.java:929)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted(MembershipFailureTest.java:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1563/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted/

**Comment by hasancelik** [comment] 2017-07-24 10:54
```
java.lang.AssertionError: expected:<[127.0.0.1]:5702> but was:<[127.0.0.1]:5701>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddress(HazelcastTestSupport.java:924)
	at com.hazelcast.test.HazelcastTestSupport$14.run(HazelcastTestSupport.java:934)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1066)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1083)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddressEventually(HazelcastTestSupport.java:929)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted(MembershipFailureTest.java:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1565/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted/

**Comment by mdogan** [comment] 2017-09-06 12:43
Fixed by https://github.com/hazelcast/hazelcast/commit/3315eec44f5d7fe719d7c3984d0d6a93a5222615

**Comment by hasancelik** [comment] 2017-10-30 07:58
```
java.lang.AssertionError: expected:<[127.0.0.1]:5702> but was:<[127.0.0.1]:5701>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddress(HazelcastTestSupport.java:969)
	at com.hazelcast.test.HazelcastTestSupport$14.run(HazelcastTestSupport.java:978)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1133)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1150)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddressEventually(HazelcastTestSupport.java:974)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted(MembershipFailureTest.java:660)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1518/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted_fd_deadline_/

**Comment by mdogan** [comment] 2018-02-15 08:39
I have tried to reproduce this issue (for a few hours, alongside with https://github.com/hazelcast/hazelcast/issues/10658) but not able to yet. Closing for now, there are no    recurring failures.

**Comment by hasancelik** [comment] 2018-02-19 09:53
*maintenance*
```
java.lang.AssertionError: expected:<[127.0.0.1]:5702> but was:<[127.0.0.1]:5701>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddress(HazelcastTestSupport.java:979)
	at com.hazelcast.test.HazelcastTestSupport$14.run(HazelcastTestSupport.java:989)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1145)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1162)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddressEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted(MembershipFailureTest.java:659)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Lab/job/Hazelcast-3.maintenance-nightly-lab/10/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted_fd_deadline_/

https://hazelcast-l337.ci.cloudbees.com/view/Lab/job/Hazelcast-3.maintenance-nightly-lab/11/testReport/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted_fd_deadline_/

**Comment by jerrinot** [comment] 2018-02-27 09:37
another failure: https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly-lab/7/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted_fd_deadline_/

**Comment by jerrinot** [comment] 2018-02-27 10:10
interestingly enough I can see 
`21:46:29,292  INFO |secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted[fd:deadline]| - [system] secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted - [127.0.0.1]:5701 [dev] [3.10-SNAPSHOT] Hazelcast 3.10-SNAPSHOT (20180226 - b5de3f7) starting at [127.0.0.1]:5701
` 
and
 `21:46:30,311  INFO |secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted[fd:deadline]| - [system] secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted - [127.0.0.1]:5702 [dev] [3.10-SNAPSHOT] Hazelcast 3.10-SNAPSHOT (20180226 - b5de3f7) starting at [127.0.0.1]:5702` 

in the log. but I don't see the other 2 members starting.

**Comment by jerrinot** [comment] 2018-02-27 10:15
I managed to reproduce the failure locally, just after 24 iterations. I was running this testcase in isolation -> it's not caused by some other test forgetting to clean it.

**Comment by jerrinot** [comment] 2018-02-27 10:57
I can see this exception right at the end of the test:
```
11:53:07,767 DEBUG |secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted[fd:deadline]| - [MembershipManager] hz._hzInstance_50_dev.cached.thread-7 - [127.0.0.1]:5702 [dev] [3.10-SNAPSHOT] MemberInfo{address=[127.0.0.1]:5703, uuid=31b2fc59-f24b-4fe4-9baf-cec8d943fa46, liteMember=false, memberListJoinVersion=3} is excluded because I don't know its response
11:53:07,768 DEBUG |secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted[fd:deadline]| - [MembershipManager] hz._hzInstance_50_dev.cached.thread-7 - [127.0.0.1]:5702 [dev] [3.10-SNAPSHOT] MemberInfo{address=[127.0.0.1]:5704, uuid=0c364557-5181-468e-85eb-5c17d3dbdd9e, liteMember=false, memberListJoinVersion=4} is excluded because I couldn't get its acceptance
java.util.concurrent.ExecutionException: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:92) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147) ~[classes/:?]
	at com.hazelcast.internal.cluster.impl.MembershipManager.decideNewMembersView(MembershipManager.java:698) [classes/:?]
	at com.hazelcast.internal.cluster.impl.MembershipManager.access$100(MembershipManager.java:78) [classes/:?]
	at com.hazelcast.internal.cluster.impl.MembershipManager$DecideNewMembersViewTask.run(MembershipManager.java:1087) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67) [classes/:?]
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [classes/:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [classes/:?]
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.shutdown(InvocationRegistry.java:198) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.shutdownInvocations(OperationServiceImpl.java:477) ~[classes/:?]
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:462) ~[classes/:?]
	at com.hazelcast.instance.Node.shutdownServices(Node.java:489) ~[classes/:?]
	at com.hazelcast.instance.Node.shutdown(Node.java:453) ~[classes/:?]
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98) ~[classes/:?]
	at com.hazelcast.instance.LifecycleServiceImpl.terminate(LifecycleServiceImpl.java:86) ~[classes/:?]
	at com.hazelcast.instance.HazelcastInstanceFactory.shutdownAll(HazelcastInstanceFactory.java:286) ~[classes/:?]
	at com.hazelcast.instance.HazelcastInstanceFactory.terminateAll(HazelcastInstanceFactory.java:262) ~[classes/:?]
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest_withTCP.tearDown(MembershipFailureTest_withTCP.java:42) ~[test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) ~[junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) ~[junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33) ~[junit-4.12.jar:4.12]
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37) ~[test-classes/:?]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) ~[junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) ~[junit-4.12.jar:4.12]
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50) ~[test-classes/:?]
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29) ~[test-classes/:?]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) ~[junit-4.12.jar:4.12]
	at org.junit.runners.Suite.runChild(Suite.java:128) ~[junit-4.12.jar:4.12]
	at org.junit.runners.Suite.runChild(Suite.java:27) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) ~[junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) ~[junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) ~[junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) ~[junit-rt.jar:?]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:67) ~[junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) ~[junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) ~[junit-rt.jar:?]
	at ------ submitted from ------.(Unknown Source) ~[?:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79) ~[classes/:?]
	... 12 more
```

perhaps the member view (and master) is never updated because it's dead-locking? `MembershipManager.decideNewMembersView` in the stacktrace is suspicious. The future is only resolved (with `HazelcastInstanceNotActiveException`) when the instance is terminated after a test timeout.

**Comment by jerrinot** [comment] 2018-02-28 09:36
unassigned myself as Mehmet is working on a fix too.

**Comment by Holmistr** [comment] 2018-03-05 14:25
@mdogan Any update on this?

**Comment by mdogan** [comment] 2018-03-05 14:33
Investigation of this issue leaded to a chain of other issues. I have already a fix for this specific issue but I'm still working on another one. I'll send fixes when all completed.

**Comment by Holmistr** [comment] 2018-03-05 14:37
@mdogan Awesome, thanks!

**Comment by Holmistr** [comment] 2018-04-04 08:25
*maintenance*

Reopening as it failed on maintenance: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly-lab/66/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted_fd_deadline_/

Stacktrace:
```
java.lang.AssertionError: expected:<[127.0.0.1]:5702> but was:<[127.0.0.1]:5701>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddress(HazelcastTestSupport.java:985)
	at com.hazelcast.test.HazelcastTestSupport$14.run(HazelcastTestSupport.java:995)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1151)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1168)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddressEventually(HazelcastTestSupport.java:990)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted(MembershipFailureTest.java:674)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by mdogan** [comment] 2018-04-04 08:47
Unfortunately, we can't fix this issue in 3.9.x because of RU compatibility. On 3.9.x, mastership claim is not idempotent but fix requires it to be. If this fails frequently on maintenance, I can ignore the test.

See https://github.com/hazelcast/hazelcast/pull/12508 & https://github.com/hazelcast/hazelcast/pull/12526

**Closed by mdogan** 2018-04-04 08:47 UTC
Labels: Team: Core, Type: Test-Failure

**Comment by Holmistr** [comment] 2018-04-04 08:53
@mdogan Thanks for the explanation. Could you please prepare the @Ignore PR? I'm quite overloaded today.

**Comment by mdogan** [comment] 2018-04-04 09:39
@Holmistr: See https://github.com/hazelcast/hazelcast/pull/12783
