### ISSUE TITLE
GracefulShutdownCorrectnessTest.testPartitionData_whenNodesStartedShutdown_whileOperationsOngoing[backups:2,nodes:3,shutdown:1]

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8065] opened 2016-05-02 07:38 UTC
```
java.lang.AssertionError: Replica version mismatch! Owner: Address[127.0.0.1]:7308, Backup: Address[127.0.0.1]:7302, Partition: Partition [22]{
    0:Address[127.0.0.1]:7308
    1:Address[127.0.0.1]:7307
    2:Address[127.0.0.1]:7302
}, Replica: 2 owner versions: [38, 38, 0, 0, 0, 0] backup versions: [0, 36, 0, 0, 0, 0] expected:<38> but was:<36>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndData(PartitionCorrectnessTestSupport.java:205)
    at com.hazelcast.internal.partition.GracefulShutdownCorrectnessTest.testPartitionData_whenNodesStartedShutdown_whileOperationsOngoing(GracefulShutdownCorrectnessTest.java:173)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/894/testReport/junit/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest/testPartitionData_whenNodesStartedShutdown_whileOperationsOngoing_backups_2_nodes_3_shutdown_1_/

**Comment by hasancelik** [comment] 2016-05-02 07:39
possibly related to https://github.com/hazelcast/hazelcast/issues/8064

**Comment by mdogan** [comment] 2016-05-04 12:48
fixed by https://github.com/hazelcast/hazelcast/commit/b7b7168da4c37fb2059c7f78477200e5ffc82526

**Comment by mmedenjak** [comment] 2021-03-12 07:31
**GracefulShutdownCorrectnessTest.testPartitionData_whenNodesStartedShutdown_whileOperationsOngoing[backups:1,nodes:2,shutdown:1]**

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4248

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at com.hazelcast.internal.partition.AbstractGracefulShutdownCorrectnessTest.testPartitionData_whenNodesStartedShutdown_whileOperationsOngoing(AbstractGracefulShutdownCorrectnessTest.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment] 2021-07-26 09:36
Possibly this has the same root cause as https://github.com/hazelcast/hazelcast/issues/18163.

**Closed** 2021-09-03 07:15 UTC
Labels: Team: Core, Type: Test-Failure, Source: Internal, Module: Partitioning
