### ISSUE TITLE
IMap.tryLock deadlock when client gets TargetDisconnectedException

### ISSUE THREAD

**Issue by efic1** [hazelcast/hazelcast#7475] opened 2016-02-06 09:41 UTC
We are using hz version 3.5.4 in client / server mode and in some rare cases seeing the below behavior in which a IMap.tryLock fails with TargetDisconnectedException but the server lock was actually acquired. This leaves our flow in a deadlock situation as the client have no way of knowing that the server lock was actually acquired.

Seems like a bug, as the server lock should have been released when the client disconnects from the server.

We are working on creating a reproducible test.

```
class com.hazelcast.spi.exception.TargetDisconnectedException-null
com.hazelcast.spi.exception.TargetDisconnectedException
at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:121)
at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:102)
at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:130)
at com.hazelcast.client.proxy.ClientMapProxy.tryLock(ClientMapProxy.java:478)
at com.company.core.model.system.DistributedMap.tryLock(DistributedMap.java:128)
at com.company.landingzone.service.message.MainLzQueueMessageListener$MainLzQueueWorker.process(MainLzQueueMessageListener.java:35)
at com.company.core.service.message.AbstractQueueListener$AbstractQueueRunnable.run(AbstractQueueListener.java:139)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
at ------ End remote and begin local stack-trace ------.(Unknown Source)
at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveException(ClientInvocationFuture.java:175)
at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:160)
at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:127)
at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:102)
at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:130)
at com.hazelcast.client.proxy.ClientMapProxy.tryLock(ClientMapProxy.java:478)
at com.company.core.model.system.DistributedMap.tryLock(DistributedMap.java:128)
at com.company.landingzone.service.message.MainLzQueueMessageListener$MainLzQueueWorker.process(MainLzQueueMessageListener.java:35)
at com.company.core.service.message.AbstractQueueListener$AbstractQueueRunnable.run(AbstractQueueListener.java:139)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by sancar** [comment] 2016-02-17 11:46
In case of exception, you can call (`isLockedByCurrentThread` ) to see if client is able to get lock or not. 

Or you can call tryLock with lease time to avoid a lock staying forever. Even though a connection problem occurs, lock will be released eventually.

**Comment by efic1** [comment] 2016-02-17 11:55
I'm using the IMap lock and can't find the isLockedByCurrentThread method in that interface. As you can see in the above stacktrace, the exception is a client disconnect so I can't really communicate with the server at this point.

**Comment by sancar** [comment] 2016-02-17 12:05
Sorry, I was thinking that you are using ILock. `isLockedByCurrentThread ` is available there.
There is `isLocked` method on IMap, but it could be the case that somebody else locked it in the meantime. Not sure if this is useful in your case.
It seems second option is more suitable for you.

**Comment by efic1** [comment] 2016-03-30 19:56
We are still seeing many of those errors but failed to reproduce it in a lab

[30 Mar 2016 19:34:14,580] [WARN ] [hz.client_0_dev.response-] [com.hazelcast.client.spi.impl.ClientInvocationFuture] - The Future.set() method can only be called once. Request: com.hazelcast.map.impl.client.MapLockRequest@162fe9f8, current response: com.hazelcast.spi.exception.TargetDisconnectedException, new response: DefaultData{type=-4, hashCode=535970202, partitionHash=535970202, totalSize=6, dataSize=1, heapCost=26}

**Comment by pveentjer** [comment] 2016-04-27 07:16
The 'shallow' cause of this exception is that the invocation future was already completed by TargetDisconnectedException, but the MockLockRequest came in later. So then you get this error message.

The big question of course is why the client get disconnected in the first place.

A smaller question is: why did the client not give some time for responses to come in and after some time try to complete the remaining futures with a TargetDisconnectException.

**Comment by sancar** [comment] 2017-12-28 08:35
Closing the issue since it is too old and we are not able to reproduce. 
@efic1 If you think there are still problems please comment.

**Closed by sancar** 2017-12-28 08:35 UTC
Labels: Team: Client, Type: Defect
