### ISSUE TITLE
Number of tests fails with "Instances haven't been shut down" error

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19002] opened 2021-06-29 17:42 UTC
_master_ / _3.0-maintenance_ (commit INSERT_COMMIT_ID_HERE)

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-EE-4.maintenance-OracleJDK11/6/testReport/

There are 21 failures with the same error.
Failed tests:
com.hazelcast.cache.CacheNativeMemoryLicenseTest.com.hazelcast.cache.CacheNativeMemoryLicenseTest
com.hazelcast.cache.CacheNativeMemoryListenerTest.com.hazelcast.cache.CacheNativeMemoryListenerTest
com.hazelcast.cache.HiDensityCacheClearTest.com.hazelcast.cache.HiDensityCacheClearTest
com.hazelcast.cache.HiDensityCacheExpiryPolicyBackupTest.com.hazelcast.cache.HiDensityCacheExpiryPolicyBackupTest
com.hazelcast.cache.HiDensityCachePutAllTest.com.hazelcast.cache.HiDensityCachePutAllTest
com.hazelcast.cache.HiDensityCacheReadWriteThroughTest.com.hazelcast.cache.HiDensityCacheReadWriteThroughTest
com.hazelcast.cache.HiDensityCacheSetExpiryPolicyLeakTest.com.hazelcast.cache.HiDensityCacheSetExpiryPolicyLeakTest
com.hazelcast.cache.OnHeapCacheClearTest.com.hazelcast.cache.OnHeapCacheClearTest
com.hazelcast.cache.eviction.HiDensityCacheEvictionPolicyComparatorTest.com.hazelcast.cache.eviction.HiDensityCacheEvictionPolicyComparatorTest
com.hazelcast.cache.impl.EnterpriseCacheConfigPropagationTest.com.hazelcast.cache.impl.EnterpriseCacheConfigPropagationTest
com.hazelcast.cache.impl.hidensity.nativememory.HiDensityNativeMemoryCacheRecordAccessorTest.com.hazelcast.cache.impl.hidensity.nativememory.HiDensityNativeMemoryCacheRecordAccessorTest
com.hazelcast.cache.instance.HiDensityCacheHazelcastInstanceAwareTest.com.hazelcast.cache.instance.HiDensityCacheHazelcastInstanceAwareTest
com.hazelcast.cache.instance.HiDensityCacheThroughHazelcastInstanceTest.com.hazelcast.cache.instance.HiDensityCacheThroughHazelcastInstanceTest
com.hazelcast.cache.journal.AdvancedHDCacheJournalTest.com.hazelcast.cache.journal.AdvancedHDCacheJournalTest
com.hazelcast.cache.journal.HDCacheEventJournalBasicTest.com.hazelcast.cache.journal.HDCacheEventJournalBasicTest
com.hazelcast.cache.recordstore.HiDensityNativeMemoryCacheRecordStoreTest.com.hazelcast.cache.recordstore.HiDensityNativeMemoryCacheRecordStoreTest
com.hazelcast.cache.recordstore.HiDensityNativeMemoryCacheRecordTest.com.hazelcast.cache.recordstore.HiDensityNativeMemoryCacheRecordTest
com.hazelcast.wan.WanClearQueuesSideEffectTest.com.hazelcast.wan.WanClearQueuesSideEffectTest
com.hazelcast.wan.WanCounterSyncClearTest.com.hazelcast.wan.WanCounterSyncClearTest
com.hazelcast.wan.WanQueueMigrationTest.com.hazelcast.wan.WanQueueMigrationTest

Stacktrace:
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e2', node=[127.0.0.1]:5804}, HazelcastInstance{name='ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e0', node=[127.0.0.1]:5805}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:313)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at com.hazelcast.enterprise.EnterpriseParallelJUnitClassRunner.run(EnterpriseParallelJUnitClassRunner.java:48)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

Standard output:
```
Finished Running Test: testQueueMigration in 0.840 seconds.
15:07:29,325  INFO |testCountersReachZeroAfterHealingFullSplit[cluster:3 isolated:1 backup:2]| - [WanCounterTestSupport$WanCounterDumper] pool-3551-thread-1 - ===[wanReplication(B)]=======================================================
15:07:29,325  INFO |testCountersReachZeroAfterHealingFullSplit[cluster:3 isolated:1 backup:2]| - [WanCounterTestSupport$WanCounterDumper] pool-3551-thread-1 - Sum of total events by the members: 0
15:07:29,459  INFO |testBouncingClusterAddsWanReplication| - [MockServer] Thread-9564 - [127.0.0.1]:5805 [A] [4.2.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5804, connection: MockConnection{localEndpoint=[127.0.0.1]:5805, remoteEndpoint=[127.0.0.1]:5804, alive=true}
15:07:29,459  INFO |testBouncingClusterAddsWanReplication| - [LifecycleService] Thread-9564 - [127.0.0.1]:5805 [A] [4.2.2-SNAPSHOT] [127.0.0.1]:5805 is STARTED
15:07:29,460  INFO || - [LifecycleService] main - [127.0.0.1]:5805 [A] [4.2.2-SNAPSHOT] [127.0.0.1]:5805 is SHUTTING_DOWN
15:07:29,460  INFO |testBouncingClusterAddsWanReplication| - [WanAddConfigTest] Thread-9564 - Source cluster WAN config counts after bouncing: {ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e2=1}
15:07:29,460  INFO |testBouncingClusterAddsWanReplication| - [WanAddConfigTest] Thread-9564 - Source cluster WAN config counts before bouncing: {ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e2=1}
15:07:29,460  INFO || - [Node] main - [127.0.0.1]:5805 [A] [4.2.2-SNAPSHOT] Shutting down connection manager...
15:07:29,460  INFO || - [MockServer] main - [127.0.0.1]:5788 [A] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5805, connection: MockConnection{localEndpoint=[127.0.0.1]:5788, remoteEndpoint=[127.0.0.1]:5805, alive=false}
15:07:29,460  INFO || - [MockServer] main - [127.0.0.1]:5805 [A] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5788, connection: MockConnection{localEndpoint=[127.0.0.1]:5805, remoteEndpoint=[127.0.0.1]:5788, alive=false}
15:07:29,460  INFO || - [MockServer] main - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5805, connection: MockConnection{localEndpoint=[127.0.0.1]:5804, remoteEndpoint=[127.0.0.1]:5805, alive=false}
15:07:29,460  INFO || - [MockServer] main - [127.0.0.1]:5805 [A] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5804, connection: MockConnection{localEndpoint=[127.0.0.1]:5805, remoteEndpoint=[127.0.0.1]:5804, alive=false}
15:07:29,460  WARN || - [MembershipManager] main - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] Member [127.0.0.1]:5805 - a5050ff1-483b-4bbd-b40a-373c36a14a16 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5805 - a5050ff1-483b-4bbd-b40a-373c36a14a16 this
15:07:29,460  INFO || - [MembershipManager] main - [127.0.0.1]:5788 [A] [4.2.2-SNAPSHOT] Removing Member [127.0.0.1]:5805 - a5050ff1-483b-4bbd-b40a-373c36a14a16
15:07:29,460  INFO |testBouncingClusterAddsWanReplication| - [MetricsConfigHelper] Thread-9564 - [LOCAL] [A] [4.2.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
15:07:29,460  INFO || - [ClusterService] main - [127.0.0.1]:5788 [A] [4.2.2-SNAPSHOT] 

Members {size:2, ver:164} [
	Member [127.0.0.1]:5788 - 5468effd-dba6-4b7e-993f-a9b17753f3d9 this
	Member [127.0.0.1]:5804 - 0a5a4a79-509d-4ae8-9c74-4dd4d9d71f12
]

15:07:29,460  INFO |testBouncingClusterAddsWanReplication| - [TransactionManagerService] hz.ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e1.cached.thread-6 - [127.0.0.1]:5788 [A] [4.2.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5805, UUID: a5050ff1-483b-4bbd-b40a-373c36a14a16
15:07:29,460  INFO || - [Node] main - [127.0.0.1]:5805 [A] [4.2.2-SNAPSHOT] Shutting down node engine...
15:07:29,460  INFO |testBouncingClusterAddsWanReplication| - [ClusterService] hz.ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e2.priority-generic-operation.thread-0 - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] 

Members {size:2, ver:164} [
	Member [127.0.0.1]:5788 - 5468effd-dba6-4b7e-993f-a9b17753f3d9
	Member [127.0.0.1]:5804 - 0a5a4a79-509d-4ae8-9c74-4dd4d9d71f12 this
]

15:07:29,460  INFO |testBouncingClusterAddsWanReplication| - [TransactionManagerService] hz.ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e2.cached.thread-1 - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5805, UUID: a5050ff1-483b-4bbd-b40a-373c36a14a16
15:07:29,461  INFO |testBouncingClusterAddsWanReplication| - [system] Thread-9564 - [127.0.0.1]:5806 [A] [4.2.2-SNAPSHOT] Hazelcast Enterprise 4.2.2-SNAPSHOT (20210626 - a362709, 08c4c81) starting at [127.0.0.1]:5806
15:07:29,461  INFO |testBouncingClusterAddsWanReplication| - [NodeExtension] Thread-9564 - [127.0.0.1]:5806 [A] [4.2.2-SNAPSHOT] Checking Hazelcast Enterprise license...
15:07:29,461  INFO |testBouncingClusterAddsWanReplication| - [NodeExtension] Thread-9564 - [127.0.0.1]:5806 [A] [4.2.2-SNAPSHOT] License{allowedNumberOfNodes=99, expiryDate=08/11/2099 23:59:59, featureList=[ Management Center, Clustered JMX, Clustered Rest, Security, Wan Replication, High Density Memory, Hot Restart, Rolling Upgrade, Cluster Client Filtering ], type=Enterprise HD, companyName=null, ownerEmail=null, keyHash=OsLh4O6vqDuKhn8lOANQuuAaRnmDf8fRPrFSEhA7T3Y=, No Version Restriction}
15:07:29,462  INFO || - [NodeExtension] main - [127.0.0.1]:5805 [A] [4.2.2-SNAPSHOT] Destroying node NodeExtension.
15:07:29,462  INFO || - [Node] main - [127.0.0.1]:5805 [A] [4.2.2-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
15:07:29,462  INFO || - [LifecycleService] main - [127.0.0.1]:5805 [A] [4.2.2-SNAPSHOT] [127.0.0.1]:5805 is SHUTDOWN
15:07:29,462  INFO || - [LifecycleService] main - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] [127.0.0.1]:5804 is SHUTTING_DOWN
15:07:29,462  INFO || - [Node] main - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] Shutting down connection manager...
15:07:29,462  INFO || - [MockServer] main - [127.0.0.1]:5788 [A] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5804, connection: MockConnection{localEndpoint=[127.0.0.1]:5788, remoteEndpoint=[127.0.0.1]:5804, alive=false}
15:07:29,462  INFO || - [MockServer] main - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5788, connection: MockConnection{localEndpoint=[127.0.0.1]:5804, remoteEndpoint=[127.0.0.1]:5788, alive=false}
15:07:29,462  INFO || - [MembershipManager] main - [127.0.0.1]:5788 [A] [4.2.2-SNAPSHOT] Removing Member [127.0.0.1]:5804 - 0a5a4a79-509d-4ae8-9c74-4dd4d9d71f12
15:07:29,463  INFO || - [ClusterService] main - [127.0.0.1]:5788 [A] [4.2.2-SNAPSHOT] 

Members {size:1, ver:165} [
	Member [127.0.0.1]:5788 - 5468effd-dba6-4b7e-993f-a9b17753f3d9 this
]

15:07:29,463  INFO |testBouncingClusterAddsWanReplication| - [TransactionManagerService] hz.ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e1.cached.thread-8 - [127.0.0.1]:5788 [A] [4.2.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5804, UUID: 0a5a4a79-509d-4ae8-9c74-4dd4d9d71f12
15:07:29,463  INFO || - [Node] main - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] Shutting down node engine...
15:07:29,464  INFO || - [NodeExtension] main - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] Destroying node NodeExtension.
15:07:29,464  INFO || - [Node] main - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
15:07:29,464  INFO || - [LifecycleService] main - [127.0.0.1]:5804 [A] [4.2.2-SNAPSHOT] [127.0.0.1]:5804 is SHUTDOWN
15:07:29,464  INFO |testBouncingClusterAddsWanReplication| - [MetricsConfigHelper] Thread-9564 - [127.0.0.1]:5806 [A] [4.2.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled```

**Comment by mmedenjak** [comment] 2021-08-04 14:07
This is a duplicate of https://github.com/hazelcast/hazelcast-enterprise/issues/2777. All three instances were created in the `WanAddConfigTest.testBouncingClusterAddsWanReplication` test which hanged and didn't clean up its' instances.
```
ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e0
ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e1
ClusterA-3e5ace72-076a-4537-9c5e-6c9f3ed0959e2
```

Closing as the issue needs to be addressed there.

**Closed by mmedenjak** 2021-08-04 14:07 UTC
Labels: Source: Internal, Team: Core, Type: Test-Failure
