### ISSUE TITLE
IMap: custom HashEntry

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#3451] opened 2014-08-30 14:15 UTC
Currently the map is inefficient from a memory usage point of view since there is quite some object wrapping going on. Lot of this wrapping can be removed; this will not only reduce memory usage but also make things faster since you will get trips to memory. 

The basis would be to either extend the ConcurrentMap or fork it and create our own HashEntry that will directly contain all additional fields. So instead of adding behavior/fields by wrapping and wrapping.. we immediately add it on the map entry.

Probably we need to move away from the ConcurrentHashMap since we need to have an 'iterator position'. With this iterator position we can jump into the 'ConcurrentHashMap' and continue iterating where we left. We need to behavior for operations that require long iterations like Map.values.

**Comment by dbrimley** [comment] 2018-01-10 10:31
Duplicate of https://github.com/hazelcast/hazelcast/issues/2548

**Closed** 2018-01-10 10:30 UTC
Labels: Source: Internal, Team: QuSP, Type: Enhancement
