### ISSUE TITLE
HazelcastHttpSession getAttributeNames returns entries that were only read but not written

### ISSUE THREAD

**Issue by eysegal** [hazelcast/hazelcast#6868] opened 2015-11-25 16:40 UTC
This issue was already fixed in 3.2.3 and looks like it reproduces in 3.5.3.
See https://github.com/hazelcast/hazelcast/issues/2434

**Comment by kobalski** [comment] 2015-11-27 10:01
@eysegal There is test for issue #2434 in here : https://github.com/hazelcast/hazelcast/blob/master/hazelcast-wm/src/test/java/com/hazelcast/wm/test/WebFilterSlowTests.java#L80

Also fix for the issue is still in the code base as far as I can see : https://github.com/hazelcast/hazelcast/blob/master/hazelcast-wm/src/main/java/com/hazelcast/web/HazelcastHttpSession.java#L308

I am closing the issue because I could not reproduce, Please feel free to reopen and if you provide simple test to reproduce the issue, it would be so great.

**Closed by kobalski** 2015-11-27 10:01 UTC
Labels: Team: Integration

**Comment by eysegal** [comment] 2015-11-29 08:23
I am able to reproduce it.
How do I attach a sample project?

This is the test code that reproduces it ("test" is printed even though it was only read, not write):
				
				package test;
				
				import java.util.Enumeration;
				
				import javax.servlet.FilterConfig;
				import javax.servlet.ServletContext;
				import javax.servlet.ServletException;
				
				import org.eclipse.jetty.servlet.ServletContextHandler;
				import org.eclipse.jetty.servlet.ServletContextHandler.Context;
				
				import com.hazelcast.web.HazelcastHttpSession;
				import com.hazelcast.web.WebFilter;
				
				public class HazelcastSessionParamCheck {
					public static void main(String[] args) throws ServletException {
						
						WebFilter filter = new WebFilter();
						final Context servletContext = new ServletContextHandler().new Context(); 
						
						FilterConfig filterConfig = new FilterConfig() {
							
							public ServletContext getServletContext() {
								// TODO Auto-generated method stub
								return servletContext;
							}
							
							public Enumeration<String> getInitParameterNames() {
								// TODO Auto-generated method stub
								return null;
							}
							
							public String getInitParameter(String name) {
								// TODO Auto-generated method stub
								return null;
							}
							
							public String getFilterName() {
								// TODO Auto-generated method stub
								return null;
							}
						};
						filter.init(filterConfig);
						HazelcastHttpSession hazelcastHttpSession = new HazelcastHttpSession(filter, "sessionId", null, true, true); 
						hazelcastHttpSession.getAttribute("test");
						Enumeration<String> sessionAttributeNames = hazelcastHttpSession.getAttributeNames();
						while (sessionAttributeNames.hasMoreElements()) {
							System.out.println(sessionAttributeNames.nextElement());
						}
						System.exit(1);
						
					}
				}

With this maven configuration:
				  
				<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
				  <modelVersion>4.0.0</modelVersion>
				  <groupId>test</groupId>
				  <artifactId>test</artifactId>
				  <version>0.0.1-SNAPSHOT</version>
				  <name>test</name>
				  
				  <dependencies>
				  	<dependency>
						<groupId>com.hazelcast</groupId>
						<artifactId>hazelcast-wm</artifactId>
						<version>3.5.4</version>
					</dependency>
					
					<dependency>
						<groupId>javax.servlet</groupId>
						<artifactId>javax.servlet-api</artifactId>
						<version>3.0.1</version>
					</dependency>
					
					<dependency>
						<groupId>org.eclipse.jetty</groupId>
						<artifactId>jetty-webapp</artifactId>
						<version>8.1.18.v20150929</version>
					</dependency>
				  </dependencies>
				</project>

How can I reopen the issue?
