### ISSUE TITLE
Distributed Executor service blocks when submitting large number of async tasks

### ISSUE THREAD

**Issue by driseley** [hazelcast/hazelcast#13170] opened 2018-05-22 11:57 UTC
We have noticed that if we attempt to submit a large number of Async tasks to a Hazelcast (3.8.4 - although looks to be present in all recent versions) Distributed Executor:

http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Computing/Executor_Service/Executing-Code_in_the_Cluster.html

either using the java client or as a full Java member of the cluster, the submissions block.

Here is some example code:
```java
	@Autowired
	private ExecutorService executorService;

	@Override
	public void run() {
		logger.info("AsyncJob started");

		List<Future<String>> results = new ArrayList<>();
		long submissionStartTime = System.currentTimeMillis();
		for (int i=0; i<5000; i++) {
			Future<String> result = executorService.submit(new JobTask(i));
			results.add(result);
			if ( i%50 == 0 ) {
				logger.info("{} tasks submitted",i);
			}
		}
		long submissionEndTime=System.currentTimeMillis();

		int doneCount=0;
		long workStartTime = System.currentTimeMillis();
		while (doneCount < results.size() ) {
			List<Future<String>> complete = results.stream()
					.filter(r -> r.isDone())
					.collect(Collectors.toList());
			doneCount = complete.size();
			logger.info ("{} done, performing useful work", doneCount);
			try {
				TimeUnit.MILLISECONDS.sleep(1000);
			} catch (InterruptedException e) {
				logger.warn("Sleep interrupted");
			}
		}
		long workEndTime=System.currentTimeMillis();

		logger.info("All tasks complete");

		logger.info("Submission took {} ms", (submissionEndTime-submissionStartTime));
		logger.info("Time for useful work {} ms", (workEndTime-workStartTime));
	}
```

The JobTask in this case is:

```java
public class JobTask implements Callable<String>, Serializable {
	
	private static final long serialVersionUID = 8945413768030936835L;

	private static final Logger logger = LoggerFactory.getLogger(JobTask.class);
	
	private int requestId;
	
	public JobTask(int requestId) {
		super();
		this.requestId = requestId;
	}

	@Override
	public String call() throws Exception {	
		logger.debug("Invoking task for {}", requestId);
		TimeUnit.MILLISECONDS.sleep(250);
		logger.debug("Task complete for {}", requestId);
		return requestId + " complete";
	}
}
```
Using a local task executor (no Hazelcast at all) I get:

```
2018-04-26 17:09:34.885  INFO 14420 --- [Thread-5] c.e.async.AsyncControllerComponent : Submission took 14 ms
2018-04-26 17:09:34.886  INFO 14420 --- [Thread-5] c.e.async.AsyncControllerComponent : Time for useful work 64043 ms
```

Using a full cluster member I get:

```
2018-04-26 17:12:32.566  INFO 16916 --- [Thread-5] c.e.async.AsyncControllerComponent : Submission took 70463 ms
2018-04-26 17:12:32.566  INFO 16916 --- [Thread-5] c.e.async.AsyncControllerComponent : Time for useful work 2009 ms
```

Using a Hazelcast client to a remote cluster I get:

```
2018-04-26 17:15:40.649  INFO 7336 --- [Thread-5] c.e.async.AsyncControllerComponent : Submission took 68252 ms
2018-04-26 17:15:40.649  INFO 7336 --- [Thread-5] c.e.async.AsyncControllerComponent : Time for useful work 2011 ms
```

In each case, I have configured the executor as follows, to have a pool size of 25 threads and queue capacity of 10,000 (larger than the 5,000 submitted tasks) :

```java
		// Configure the executor pool
		config.getExecutorConfig(hazelcastExecutorName)
			.setPoolSize(hazelcastExecutorPoolSize)
			.setQueueCapacity(hazelcastExecutorQueueCapacity)
			.setStatisticsEnabled(true);
```

The full reproducer for this can be found at: https://github.com/driseley/async-blocking-client

To spin up the Cluster run: `com.example.async.AsyncWorkerApplication`
To spin up the Client run: `com.example.async.AsyncControllerApplication -Dspring.profiles.active=client`

Looking at the cluster member case, a thread dump during task submission shows:

```
"Thread-5" #79 daemon prio=5 os_prio=0 tid=0x0000000030dda800 nid=0x4f78 waiting on condition [0x0000000037c8f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
        at com.hazelcast.executor.impl.ExecutorServiceProxy.submitToPartitionOwner(ExecutorServiceProxy.java:245)
        at com.hazelcast.executor.impl.ExecutorServiceProxy.submit(ExecutorServiceProxy.java:227)
        at com.example.async.AsyncControllerComponent.run(AsyncControllerComponent.java:34)
        at java.lang.Thread.run(Thread.java:748)
```

Looking at https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/executor/impl/ExecutorServiceProxy.java#L273 code there is a method:

```java
    /**
     * This is a hack to prevent overloading the system with unprocessed tasks. Once backpressure is added, this can
     * be removed.
     */
    private boolean checkSync() {
        boolean sync = false;
        long last = lastSubmitTime;
        long now = Clock.currentTimeMillis();
        if (last + SYNC_DELAY_MS < now) {
            CONSECUTIVE_SUBMITS.set(this, 0);
        } else if (CONSECUTIVE_SUBMITS.incrementAndGet(this) % SYNC_FREQUENCY == 0) {
            sync = true;
        }
        lastSubmitTime = now;
        return sync;
    }
```

which makes every 100th (SYNC_FREQUENCY) task submission synchronous, causing the blocking behavior.  Similar code exists in the ClientExecutorServiceProxy.java ( MAX_CONSECUTIVE_SUBMITS ).

Could it be made configurable so that if you have large enough queue the limit could be raised or disabled?  In it's current form, submission is synchronous, even when the executor has a large enough queue to prevent overload.

This was originally raised at: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/hazelcast/3WHwnSOPUpE

**Comment by pveentjer** [comment] 2018-05-23 07:08
The current mechanism should be replaced by a better approach.

One possible solution is to get rid of this caller side syncing completely. And just send the task to the node that is going to execute it; if the executor on the receiving node has more tasks than are allowed according to the high water mark, the task is bounced back to the caller. And retrying of the task is delayed. This process if re-executing and increased delay is repeated till there is space in the executor, or until there is some kind of timeout.

**Comment by mmedenjak** [comment] 2018-05-30 11:01
Thank you for your report @driseley ! 

We will consider improving the backpressure implementation in future releases but for now we cannot guarantee when it will be released.

**Comment by driseley** [comment] 2018-05-30 11:07
Many thanks for looking at it!  I'll watch this ticket for progress :->

**Comment by JamesChenX** [comment] 2020-05-13 13:39
Hi, I need to check whether the problem can be fixed on v4.1 since the problem hasn't been fixed for a long time.

**Comment by mmedenjak** [comment] 2020-05-14 07:22
Hi @JamesChenX ! The problem is fixable but we're not planning on investing time in it in 4.1. Still, we're open to a contribution if you feel like it. I assume some kind of backpressure will still be needed so the fix cannot be simply removing the code.

**Comment by JamesChenX** [comment] 2020-05-14 10:12
Hi @mmedenjak . Rather than implementing the backpressure now I think there is a more performance-friendly way to avoid sync tasks and other developers would be happy with it.

We can cache a bunch of tasks submitted in a specified time (should be able to be specified by developers. e.g. 200ms) and then send they as a single "Data" in a MemberCallableTaskOperation, which can also eliminate the overhead of metadata for each task and avoid sending a lot of tasks in a moment. To not confuse other developers, we can disable the feature by default.

The draft for the implementation should work similarly like this:
1. When submitToMember is invoked
2. Check whether the developers hope to cache the tasks submitted in a specified time.
3. If yes, use a map like Map<Address, LinkedList<Data>> to store the target address as the key and the data as the value.
4. Then, use a WheelTimer to check whether it's the time (specified by developers. e.g. 200ms) to send the bundle of the tasks regularly.
5. If yes, we poll the entries of the map. And, for each unique address, we bundle the LinkedList<Data> as a MemberCallableTaskOperation and execute it asynchronously.
(Of course the implementation should be thread-safe)

What do you think about the implementation?

**Comment by mmedenjak** [comment] 2020-05-21 06:58
I see it as a possible performance improvement but its' benefits are not guaranteed and it's slightly over-engineered. Batching tasks can also lead to overloading the receiver as the receiver can again be slow and sending batches does not help much. In addition to this, it can also overload the sender if the user produces the tasks so fast that he exhausts memory before the period elapses. Then, we can say "let's add another setting where we send a batch after enough time has passed or enough tasks have been collected" but that adds another setting which still doesn't guarantee anything if the size of the tasks is huge. In the end, feels like this only introduces more complexity than actually solves the problem.

Instead, since doing these "sync" tasks hasn't proven to be useful, I'd consider simply removing it and later we can think about introducing proper backpressure. There are other ways the cluster can get overloaded and none of them have something as simple as blocking every N tasks.

**Comment by mmedenjak** [comment] 2020-09-22 09:54
Related: 
https://github.com/hazelcast/hazelcast/issues/9117
https://github.com/hazelcast/hazelcast/issues/17587

**Closed** 2021-02-23 19:05 UTC
Labels: Estimation: L, Module: IExecutor, Priority: Medium, Source: Community, Team: Core, Type: Perf. Defect
