### ISSUE TITLE
IllegalStateException: Node failed to start! with version 3.8.2

### ISSUE THREAD

**Issue by arushi315** [hazelcast/hazelcast#13162] opened 2018-05-21 15:47 UTC
Here is the scenario where I am getting 'Node failed to start' exception and unable to start one node:
 
I started one node (call it NODE1) with clustering disabled (with no join method) and it starts fine with following logs, 
```java
2018-05-21 10:56:35.970 WARN (vert.x-worker-thread-0) [c.h.i.Node] - [x.x.x.x]:5701 [e535b5ba-0598-448d-9faa] [3.8.2] No join method is enabled! Starting standalone.
2018-05-21 10:56:35.970 INFO (vert.x-worker-thread-0) [c.h.system] - [x.x.x.x]:5701 [e535b5ba-0598-448d-9faa] [3.8.2] Cluster version set to 3.8
2018-05-21 10:56:36.033 INFO (vert.x-worker-thread-0) [c.h.c.LifecycleService] - [x.x.x.x]:5701 [e535b5ba-0598-448d-9faa] [3.8.2] [x.x.x.x]:5701 is STARTED
```

Now, started another node (NODE2) with clustering enabled for NODE1 and NODE2. I get following exception when trying to start NODE2, 
```java
Caused by: java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:135)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$join$0(HazelcastClusterManager.java:159)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:278)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:80)
```

I would expect NODE2 to start successfully irrespective of NODE1. Sure NODE1 will be unreachable however I expect NODE2 to not fail at startup. 

Let me know if more information is needed. Also, I can provide reproducer if needed.

**Comment by vbekiaris** [comment] 2018-05-22 06:27
@arushi315 thanks for the issue report. Is it reproducible on your side with latest stable release (3.10.1)? Also, can you post the Hazelcast configs for both nodes?

**Comment by arushi315** [comment] 2018-05-22 13:32
Hi @vbekiaris, I will try with the latest and let you know. Meanwhile, here is the configuration. 
Configuration on NODE1.
`HazelcastClusterManager clusterManager = new HazelcastClusterManager();
     Config config = clusterManager.loadConfig().setNetworkConfig(new NetworkConfig());   
           
      JoinConfig joinConfig = new JoinConfig()
                .setTcpIpConfig(new TcpIpConfig()
                                       .setEnabled(false))
                .setMulticastConfig(
                        new MulticastConfig()
                                .setEnabled(false));
     config.getNetworkConfig()
                .setPort(5701)
                .setPortAutoIncrement(false)
                .setJoin(joinConfig);`

Configuration on NODE2.
`HazelcastClusterManager clusterManager = new HazelcastClusterManager();
     Config config = clusterManager.loadConfig().setNetworkConfig(new NetworkConfig());   
           
      JoinConfig joinConfig = new JoinConfig()
                .setTcpIpConfig(new TcpIpConfig()
                                       .setEnabled(true)
                                       .addMember(NODE1)
                                       .addMember(NODE2))
                .setMulticastConfig(
                        new MulticastConfig()
                                .setEnabled(false));
     config.getNetworkConfig()
                .setPort(5701)
                .setPortAutoIncrement(false)
                .setJoin(joinConfig);`

**Comment by arushi315** [comment] 2018-05-24 14:37
Hi @vbekiaris Do you have any update regarding this issue, were you able to reproduce it? Let me know if any more information is needed.

**Comment by vbekiaris** [comment] 2018-05-24 14:41
@arushi315 no, I couldn't reproduce this issue. Can you please attach the complete logs from NODE2, in particular the entries preceding the `Caused by: java.lang.IllegalStateException: Node failed to start!`? Most probably the cause should be there.

**Comment by arushi315** [comment] 2018-05-25 12:52
@vbekiaris I was able to reproduce with 3.10.1 as well. Here is the reproducer with the instructions as well as the error trace, 
https://github.com/arushi315/cluster-test
Let me know if anything else is needed. 

Another thing that I want to highlight if this helps, we were looking at the hazelcast codebase and see 
`com.hazelcast.internal.cluster.impl.ConfigCheck#verifyJoiner` is the place where exception is initialized and thrown.
`private void verifyJoiner(ConfigCheck found) {
        if (!equals(joinerType, found.joinerType)) {
            throw new ConfigMismatchException("Incompatible joiners! expected: " + joinerType + ", found: " + found.joinerType);
        }
    }`
Here the exception is handled at `com.hazelcast.internal.cluster.impl.operations.ConfigMismatchOperation#run` method, where this node is shutdown and as the node gets shutdown during compatibility check, it throws `IllegalStateException("Node failed to start!")` in HazelcastInstanceImpl contructor.

**Comment by ramtech123** [comment] 2018-05-29 02:33
@vbekiaris Any update on this? Thanks.

**Comment by vbekiaris** [comment] 2018-05-29 09:45
Thanks for the reproducer, I can now see the exception on node2. This does not look unexpected to me:
- Node1 is configured without any joiner nor any known members -> starts standalone as a master of its single-node cluster.
- Node2 is configured with a joiner and node1 as a known member. On startup, it establishes a connection with node1 and attempts to join node1; however node1 identifies the config discrepancy (node1 has no joiner configured, node2 has tcp-ip joiner) and drops the join request as invalid.

I think this is the expected outcome and in accordance with fail-fast principle: node2 attempts to join a well-known member and fails due to a config mismatch -> instead of allowing node2 to continue operation misconfigured, shut it down. Does this make sense?

**Comment by ramtech123** [comment] 2018-05-29 10:36
Thanks for the response @vbekiaris 

While this may be expected outcome as of now, what we are looking for is a way to keep the node2 alive as a standalone master in itself, so that other nodes can join it in the future to create a tcp-ip based cluster. 

I believe, such a behavior would specifically useful to maintain High Availability, with at least one node always up and running during upgrades, in case of incompatible/breaking changes. Consider below scenario:
1. Node1 and node2 are running in clustered mode
2. Bring node1 down for upgrade, node2 will continue to serve the traffic.
3. Upgrade node1 with breaking changes, and restart without any joiners (letting node1 join the cluster would result in failure due to incompatible changes)
4. Now bring down node2 (while node1 continues to serve traffic), upgrade and start with joiner enabled
5. Once node2 starts successfully, restart node1 also with joiners enabled, so that it can join the cluster.

As per the current behavior, the process fails at step#4, and there is no way to upgrade the cluster without downtime, as per my knowledge.
If changing the overall behavior is not an option, we are looking for some configurable flag using which we can achieve this.

Thanks.

**Comment by ramtech123** [comment] 2018-05-29 14:52
Hi @vbekiaris ,
We are open to any alternate approaches as well, if available, to achieve cluster upgrade with zero downtime in above scenario. Kindly suggest.

Thanks.

**Comment by mmedenjak** [comment] 2018-05-30 07:47
Hi @ramtech123 ! 
If you want to stop two members from joining a cluster, you don't need to disable the joiner configuration. You can simply have two different group names.
So an older member would have some group name (e.g. `groupName1`) and during upgrade, you would assign a new group name (e.g. `groupName2`). Once all members are upgraded, they will all have the new group name (e.g. `groupName2`) and be part of one cluster.
This would prevent members from joining but it would not throw an exception.

Otherwise, if the group names are the same, we expect the configurations to match. Mismatching configurations are a big issue if two members are allowed to join a cluster. It may seem simple but subtle issues may arise during runtime if two members have different configuration.

**Comment by ramtech123** [comment] 2018-05-30 15:32
Hi @mmedenjak ,

While we already use group names to keep our different clusters segregated, but for a given application, the group name used to remain static. However, I never thought of a dynamic group name which can include clustering (join config flag) info as well, to achieve what we need.

Following is the approach what we are working on now - say `AppClusterGroup` is the group name that we have. Based on if node is started with clustering disabled or enabled, we will append 0 or 1 to the group name.
- When node is started with join config disabled: `AppClusterGroup-0`
- When node is started with join config enabled: `AppClusterGroup-1`

This helps us to successfully complete step#4 described in my previous comment.

Thanks team for all the support. Appreciate it.

**Comment by mmedenjak** [comment] 2018-06-05 16:24
Glad the workaround works. I realize it would have been more convenient for instances to join, even though they have different configurations but for now, we discourage it (and prevent it in some cases).

I'm closing this issue, feel free to open a new one or reopen this one for further discussion or new issues.

**Closed by mmedenjak** 2018-06-05 16:24 UTC
Labels: Team: Core, To Triage
