### ISSUE TITLE
Streaming SQL not shown by `getJobs()` or on Management Center

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#21288] opened 2022-04-21 14:35 UTC
**Describe the bug**
`HazelcastInstance.getJet().getJobs()` does not include streaming SQL jobs.
Streaming SQL are not shown in the jobs panel of Management Center.

**Expected behavior**
Something should be shown.
A job ID isn't much use, perhaps the job name could be the SQL itself.

**To Reproduce**
```
                        String sql = "SELECT * FROM mykafkatopic";
			int count = 0;
			Iterator<SqlRow> iterator = hazelcastInstance.getSql().execute(sql).iterator();
			while (iterator.hasNext() & ++count < 5) {
				for (Job job : hazelcastInstance.getJet().getJobs()) {
					System.out.println("??" + job);
				}
				System.out.println(iterator.next());
			}
```
while iterating, jobs should exist.

**Additional context**
Tried on 5.1.1
@neilstevenson has a reproducer, too big to cut&paste here.

**Comment by viliam-durina** [comment] 2022-04-22 11:55
I tried this test:
```java
public class FooTest extends SqlTestSupport {
    @Test
    public void test() {
        HazelcastInstance inst = createHazelcastInstance();
        inst.getSql().execute("SELECT * FROM table(generate_stream(1))").iterator();
        assertTrueAllTheTime(() -> assertEquals(1, inst.getJet().getJobs().size()), 5);
    }
}
```
And it passes...

**Comment by viliam-durina** [comment] 2022-04-22 12:42
I've checked also the large reproducer shared privately, it seems to be user error (there were only batch jobs that have completed at the time `getJobs()` was called). Closing for now, reopen, if you can reproduce.

**Closed by viliam-durina** 2022-04-22 12:42 UTC
Labels: Type: Defect
