### ISSUE TITLE
JDK9 + issues

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#15626] opened 2019-09-27 07:42 UTC
When running with JDK9, we'll get exceptions like

```
Sep 27, 2019 10:31:49 AM com.hazelcast.internal.metrics.impl.MetricsService
WARNING: [10.212.1.102]:5701 [workers] [4.0-SNAPSHOT] Error when rendering 'memory.totalPhysical'
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.internal.metrics.impl.MethodProbe$LongMethodProbe.get(MethodProbe.java:107)
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.render(MetricsRegistryImpl.java:322)
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.render(MetricsRegistryImpl.java:270)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:155)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:150)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.hazelcast.internal.memory.MemoryStatsSupport
	at com.hazelcast.internal.memory.DefaultMemoryStats.getTotalPhysical(DefaultMemoryStats.java:34)
	... 16 more
```

Instead of getting all of this noise, we should clean it up.

**Comment by mmedenjak** [comment] 2019-10-29 14:10
Duplicate of: https://github.com/hazelcast/hazelcast/issues/15884

**Closed by mmedenjak** 2019-10-29 14:10 UTC
Labels: Team: Core, Type: Defect
