### ISSUE TITLE
MapStore: Map init gets blocked during MapStore initialization on cluster join

### ISSUE THREAD

**Issue by artem-emelin** [hazelcast/hazelcast#11776] opened 2017-11-10 17:02 UTC
[thread.txt](https://github.com/hazelcast/hazelcast/files/1462078/thread.txt)
Hi,
We've just encountered a deadlock problem on Hazelcast 3.9 version, Spring 4.3.10.RELEASE
When a node starts, tries to join a cluster and concurrently initializing MapStore class as a Spring bean we are getting a deadlock.

Could you please check this out?

Thanks, Artem

**Comment by ahmetmircik** [comment] 2017-11-13 13:32
Seems `MapLoaderLifecycleSupport#init` blocked the progress. Init can be done lazily.
Thanks for reporting this.

**Comment by artem-emelin** [comment] 2017-11-13 16:17
> Seems MapLoaderLifecycleSupport#init blocked the progress. Initialization can be done lazily.
> Thanks for reporting this.

Yes, as I looked further it looks like when Spring Context starts up, one of the beans has a Hazelcast instance as a dependency, and Spring starts to initialize HazelcastInstance to inject it as dependency, during initialization Hazelcast initializes inner Working Pool and tries to connect to a cluster, but concurrently HZ working pool tries to initialize a MapLoader which has a Spring dependency and during initialization HZ can not execute _com.hazelcast.core.MapLoaderLifecycleSupport#init_ because Spring still holds the lock but this working thread acquires another inner HZ lock which is needed further in the _Spring_ start up thread, so we get a deadlock.

**Comment by tombujok** [comment] 2017-11-22 08:54
You can change the InitialLoadMode to LAZY. It should help avoid the deadlock. Spring will be able to get the map-reference, without loading the entries on init(). Could you retest?

**Comment by artem-emelin** [comment] 2017-11-22 15:40
I've just tried it like this:
```xml
<map name="market.details">
        <time-to-live-seconds>3600</time-to-live-seconds>
        <backup-count>0</backup-count>
        <map-store initial-mode="LAZY">
            <class-name>Long class name</class-name>
        </map-store>
    </map>
```

Setting _LAZY_ and Hazelcast does not call `loadAllKeys` method but when a new node tries to join a cluster still getting a _Deadlock_.
It looks like when there is a set up of `MapStore`, Hazelcast tries to initialize a `MapStore` instance.

**Comment by artem-emelin** [comment] 2017-12-08 21:46
The best viable option as a dirty workaround which solves the problem of EAGER _MapLoader_ instance initialization is the next one (Eg. from my MapLoader):
```java
public class MarketTypeMapLoader implements 
MapLoader<String, MarketType>, MapLoaderLifecycleSupport {

.....................

  @Override
  public void init(HazelcastInstance hazelcastInstance, Properties properties, String mapName) {
      this.hazelcastInstance = hazelcastInstance;
  }

  private MarketDetailsRepository getMarketDetailsRepository()  {
      if (isNull(marketDetailsRepository)) {
          hazelcastInstance.getConfig().getManagedContext().initialize(this);
      }
      return marketDetailsRepository;
  }
}
```

And later call ` getMarketDetailsRepository()` which will be LAZY initialized but this looks really dirty.

**Comment by StephenOTT** [comment] 2020-06-13 16:28
This seems very similar to the issue i get with: https://github.com/micronaut-projects/micronaut-data/issues/464

**Comment by ahmetmircik** [comment] 2022-08-23 15:27
Hi @artem-emelin and @StephenOTT, the deadlock should be fixed by latest changes, please try with latest 5.2 beta.
I'm closing this issue, if you still see any problem, we can reopen it.

**Closed by ahmetmircik** 2022-08-23 15:27 UTC
Labels: Type: Defect, Team: Core, Priority: High, Source: Community, Module: IMap

**Comment by wind57** [comment] 2025-10-28 20:22
We get the same issue also. We have implemented a Blocking @SpringAware, where we wait for the spring context to be refreshed before we wire all the dependencies. The problem is that this is called by partition threads, which means all of them are blocked until the context is refreshed. 

On the other hand, we have a CQC created as a `@Bean` that internally calls: 

```
private void doRunOnPartitionThreads(Query query, PartitionIdSet partitionIds, Result result) { .... }
```

So a CQC to progress needs a partition thread available, and to properly wire things, the blocking `@SpringAware` needs the context refreshed. This results in a deadlock. 

Unfortunately, the hazelcast spring integration is plain terrible and what is worse, no one seems to care, really.
