### ISSUE TITLE
[TEST-FAILURE]  com.hazelcast.client.cache.CacheBasicClientTest.testIteratorDuringInsertion

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#6234] opened 2015-09-17 08:35 UTC
```
Tests run: 29, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.03 sec <<< FAILURE! - in com.hazelcast.client.cache.CacheBasicClientTest
testIteratorDuringInsertion(com.hazelcast.client.cache.CacheBasicClientTest)  Time elapsed: 0.188 sec  <<< ERROR!
java.lang.NullPointerException: null
    at com.hazelcast.cache.CacheBasicAbstractTest.testIteratorDuringInsertion(CacheBasicAbstractTest.java:338)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:134)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:47)
    at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:144)
    at java.lang.Thread.run(Thread.java:744)
```

Reported by @dbrimley

**Comment by Donnerbart** [comment] 2015-09-17 08:41
In the test there is
```
        // Give chance to thread for starting
        sleepSeconds(1);
```
which looks suspicious. Maybe we should replace this with a `CountdownLatch` to be sure that the thread is in a correct state.

**Comment by Donnerbart** [comment] 2015-09-17 08:45
Let me prepare a PR for this :)

**Comment by serkan-ozal** [comment] 2015-09-17 08:47
I can assign this one to you @Donnerbart if you are OK :)
I have not looked at yet this issue.
Can you reproduce it on your local?

**Comment by Donnerbart** [comment] 2015-09-17 08:55
Not yet, but it looks quite suspicious (spurious failure and a sleep). I'll make a PR to get rid of this, so we can see if there is another issue with those tests.

**Comment by enesakar** [comment] 2015-09-17 09:17
@Donnerbart can you reproduce the issue?

**Comment by dbrimley** [comment] 2015-09-17 09:23
As a general rule, doing any kind of sleep in a test isn't a very good idea.  Better to act on concrete state.

**Comment by Donnerbart** [comment] 2015-09-17 09:32
I can't reproduce it yet, but as David said, the sleep() should not be there. This has to be gone for sure, since it's the most obvious reason for a race condition we have. And since the issue doesn't occur on every run, this is a racy test.

**Comment by Donnerbart** [comment] 2015-09-17 09:55
I can reproduce it when I sleep longer, so the second Thread can insert more data.

Since the key is valid and the value is `null` I suspect some kind of race between the iterator and either
* cache eviction or
* overwriting the existing cache record

**Comment by Donnerbart** [comment] 2015-09-17 10:09
If I limit the random number to the predefined size no eviction should happen, since we override just existing values. In this case the error doesn't occur. So I think we can rule out overwriting as cause for this.

So the main cause seems to be eviction vs. iterator. If this behavior is okay the test can be fixed easily. Otherwise there may be a problem with concurrent usage of cache entries.

**Comment by Donnerbart** [comment] 2015-09-17 10:41
I made a PR to fix the immediate test failure. @serkan-ozal and me figured out that the root cause is most probably a race between the cache eviction and cache iterator. This will be investigated further by Serkan.

**Comment by dbrimley** [comment] 2015-09-17 10:43
Super, thanks for the speedy response.

**Closed** 2015-10-20 16:15 UTC
Labels: Team: Integration, Type: Defect
