### ISSUE TITLE
Near cache invalidation does not work on change

### ISSUE THREAD

**Issue by china-silence-chen** [hazelcast/hazelcast#19108] opened 2021-07-16 05:58 UTC
### My config (hazelcast-all 4.2.1)

        Config config = new Config();
        NetworkConfig networkConfig = new NetworkConfig();
        JoinConfig joinConfig = new JoinConfig();
        TcpIpConfig tcpIpConfig = new TcpIpConfig();
        tcpIpConfig.setEnabled(true);
        tcpIpConfig.setMembers(Arrays.asList(member.split(",")));
        joinConfig.setTcpIpConfig(tcpIpConfig);
        networkConfig.setJoin(joinConfig);
        config.setNetworkConfig(networkConfig);

        MapConfig mapConfig = new MapConfig();
        mapConfig.setName("distinctHazelcastMap");

        EvictionConfig evictionConfig = new EvictionConfig();
        evictionConfig.setEvictionPolicy(EvictionPolicy.LRU);
        evictionConfig.setSize(50000);
        evictionConfig.setMaxSizePolicy(MaxSizePolicy.PER_NODE);
        mapConfig.setEvictionConfig(evictionConfig);

        evictionConfig = new EvictionConfig();
        evictionConfig.setEvictionPolicy(EvictionPolicy.LRU);
        evictionConfig.setMaxSizePolicy(MaxSizePolicy.ENTRY_COUNT);
        evictionConfig.setSize(50000);
        mapConfig.setNearCacheConfig(new NearCacheConfig()
                .setEvictionConfig(evictionConfig));

        mapConfig.setTimeToLiveSeconds(60);
        config.addMapConfig(mapConfig);

### The member's near cache is never invalidate after a long time of display in Management Center
![image](https://user-images.githubusercontent.com/47130394/125897893-9736f753-400a-47a0-85fd-96a49eca8130.png)

### Configuration of display in Management Center
![image](https://user-images.githubusercontent.com/47130394/125898770-1185f862-5cbf-4196-a330-4a0e624b87c5.png)

### Near cache documentation
![image](https://user-images.githubusercontent.com/47130394/125900298-a49db152-b5d3-43ba-8d2f-5b4c36ee06f7.png)

**Comment by mmedenjak** [comment] 2021-07-19 09:25
Thank you for the report @china-silence-chen ! @emre-aydin @ahmetmircik can you check?

**Comment by ahmetmircik** [comment] 2021-07-26 18:53
(related/linked issues: https://github.com/hazelcast/hazelcast/issues/10975)

Seems the cause is expirations(ttl). Currently we don't generate near-cache invalidations if cause of removal is expiry. Near-cache also has ttl configuration and it can be set to fix this.

**Comment by china-silence-chen** [comment] 2021-08-02 06:36
But according to the document description:

**Comment by ahmetmircik** [comment] 2021-08-02 08:58
Seems docs must be fixed. Expiration and eviction don't generate near-cache invalidations.

**Comment by ahmetmircik** [comment] 2021-08-06 12:03
I have updated docs: https://github.com/hazelcast/imdg-docs/commit/4de690beccfd745275b7e7ca6d9b3328825e9958

Can we close this issue @china-silence-chen?

**Comment by china-silence-chen** [comment] 2021-08-09 03:21
ok! @ahmetmircik

**Comment by ahmetmircik** [comment] 2021-08-09 06:37
Yes, it is. 
I'm closing this issue now in favor of https://github.com/hazelcast/hazelcast/issues/10975, you can watch latest state from there.

**Closed by ahmetmircik** 2021-08-09 06:37 UTC
Labels: Team: Core, Source: Community, Module: IMap, Module: Near Cache
