### ISSUE TITLE
LossToleranceTest.whenLossTolerant_andOwnerCrashes_thenContinue

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#16430] opened 2020-01-08 05:00 UTC
There was a `LossToleranceTest` test failure on `master` branch in PR builder:

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5431/

```
java.lang.AssertionError: Collection [item1, item2] (2) didn't contain expected 'newItem'
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertContains(HazelcastTestSupport.java:934)
	at com.hazelcast.topic.impl.reliable.LossToleranceTest$4.run(LossToleranceTest.java:148)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.topic.impl.reliable.LossToleranceTest.whenLossTolerant_andOwnerCrashes_thenContinue(LossToleranceTest.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vojtechtoman** [comment] 2020-01-08 07:22
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5423/testReport/junit/com.hazelcast.topic.impl.reliable/LossToleranceTest/whenLossTolerant_andOwnerCrashes_thenContinue/

**Comment by mmedenjak** [comment] 2020-01-08 08:43
This might be caused by this change - https://github.com/hazelcast/hazelcast/pull/16303

**Comment by mmedenjak** [comment] 2020-01-08 15:30
The issue is caused by the change. Basically, before, if we detected that the sequence requested by the listener was too far in the future, we threw a `StaleSequenceException` and the loss-tolerant listener would take the `headSequence` (smallest/oldest sequence) and start listening again.

Now, with the updated code, [we choose the `tailSequence + 1` instead](https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java#L453-L457).

Both cases indicate that we completely lost the ringbuffer with all of its' items but the question now is - what behaviour do we actually want then? The requested sequence being too far in the future might mean two things:
• the entire ringbuffer was lost and now we want to read from some new partition owner. In this case, it makes sense to start reading from `headSequence()` (like in 3.x) because all of the items in the new ringbuffer are new to to the listener (as the test expects)
• not everything was lost. Maybe the partition owner was terminated before some items were replicated to the backups but after the listener got those new items. In this case, it makes sense to start reading from `tailSequence() + 1` (like in the latest change) since the listener already observed items from `headSequence()` to `tailSequence() + 1`

So between the two, there is no right choice. This problem would be solved if we introduced unique IDs for ringbuffers and where we could detect if a ringbuffer was completely lost (see https://github.com/hazelcast/hazelcast/issues/11857#issuecomment-352401655).

WDYT @cangencer @jbartok

**Comment by cangencer** [comment] 2020-01-08 16:25
@mmedenjak originally I clamped values `> tailSequence` to head sequence but that seems rather unintuitive - i.e. you ask for 10, head is 0 and tail is 8 but you get 0, which is rather counterintuitive. I guess the test is racy and that's why it fails. Agree proper solution would be to introduce unique IDs but this would be a rather large change, including changes to client protocol. Maybe it's just enough to fix the test so that the publish is inside the assert? (so it repeatedly publishes and eventually the messages should get to the client?) Either way it's losing data and since it's marked as loss-tolerant, it doesn't care about it.

**Comment by mmedenjak** [comment] 2020-01-08 16:27
True, we might change the test for now but we'll also see if we have time to squeeze the unique ID into 4.0.

**Closed** 2020-01-09 11:23 UTC
Labels: Module: ITopic, Source: Internal, Team: Core, Type: Test-Failure
