### ISSUE TITLE
MapPutAllWithBouncingMemberTest.testPutAll_whenAddingAndTerminatingMembers_thenPutAllShouldNotFail_withBatching

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15582] opened 2019-09-20 07:31 UTC
_master_ (commit 2c27b161fd91249884cb1005b30c5faaccde88b9)

Failed on IbmJDK8 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8-fips-nightly/77/testReport/com.hazelcast.map/MapPutAllWithBouncingMemberTest/testPutAll_whenAddingAndTerminatingMembers_thenPutAllShouldNotFail_withBatching/

**Stacktrace**

```
java.lang.AssertionError: The map size should be 1000 expected:<1000> but was:<999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.MapPutAllWithBouncingMemberTest.testPutAll(MapPutAllWithBouncingMemberTest.java:110)
	at com.hazelcast.map.MapPutAllWithBouncingMemberTest.testPutAll_whenAddingAndTerminatingMembers_thenPutAllShouldNotFail_withBatching(MapPutAllWithBouncingMemberTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:811)

```

**Comment by tezc** [comment] 2019-09-27 06:42
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-EE-3.maintenance-sonar/244/testReport/com.hazelcast.map/HDMapPutAllWithBouncingMemberTest/testPutAll_whenAddingAndTerminatingMembers_thenPutAllShouldNotFail_withBatching/

**Comment by tezc** [comment] 2019-10-11 06:23
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8-fips-nightly/84/testReport/com.hazelcast.map/MapPutAllWithBouncingMemberTest/testPutAll_whenAddingAndTerminatingMembers_thenPutAllShouldNotFail_withBatching/

**Comment by ahmetmircik** [comment] 2019-11-19 15:48
closing this one, since it is duplicate of #3342.

**Closed by ahmetmircik** 2019-11-19 15:48 UTC
Labels: Module: IMap, Source: Internal, Team: Core, Type: Test-Failure

**Comment by tezc** [comment] 2019-11-19 16:07
@ahmetmircik are you sure this is duplicate of that issue? It's quite old and looks completely different

**Comment by tezc** [comment] 2019-11-19 16:13
Oh I see, link was pointing OS #3342 instead of EE
