### ISSUE TITLE
WrongTargetException: operation: com.hazelcast.map.impl.operation.MapSizeOperation

### ISSUE THREAD

**Issue by eviltoylet** [hazelcast/hazelcast#8159] opened 2016-05-12 21:21 UTC
hazelcast version: `3.6.1`
nodes in this cluster: `10`

```
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

callstack:

```
Caused by: com.hazelcast.spi.exception.WrongTargetException: WrongTarget! this: Address[xxx.xxx.xxx.xxx]:5701, target: Address[xxx.xxx.xxx]:5701, partitionId: 190, replicaIndex: 0, operation: com.hazelcast.map.impl.operation.MapSizeOperation, service: hz:impl:mapService
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureNoPartitionProblems(OperationRunnerImpl.java:323)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:162)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:393)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
        at ------ End remote and begin local stack-trace ------.(Unknown Source)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:385)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:335)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
        at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:131)
        at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:67)
        at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:368)
        at com.hazelcast.map.impl.proxy.MapProxySupport.size(MapProxySupport.java:557)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.size(MapProxyImpl.java:80)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
        ... 29 more
```

Background:
We're using Spring to initialize a singleton that uses Hazelcast. In the constructor, we call `map.size()`. What it looks like is that the `size()` operation is invoked while nodes are being added to the cluster, and therefore the partitions are getting rebalanced.

**Comment by tombujok** [comment] 2016-07-04 08:23
Why do you need to call size in the constructor? 
Basically as you said the partitions get rebalanced so the `ensureNoPartitionProblems` method failes.
But the `WrongTargetException extends RetryableHazelcastException ` so the operation will be retried, thus your invocation should succeed eventually.

**Comment by metanet** [comment] 2018-03-01 10:33
There is not much info about the cause of this failure and the reported version is quite old. Closing this one.

**Closed by metanet** 2018-03-01 10:33 UTC
Labels: Estimation: S, Interface: IMap, Team: Core
