### ISSUE TITLE
Classloader issue with javax.cache.api and Hazelcast 3.3.1

### ISSUE THREAD

**Issue by dschmitz** [hazelcast/hazelcast#3792] opened 2014-10-08 13:19 UTC
With latest Hazelcast 3.3.1 i get a classloader error stating java.lang.NoClassDefFoundError: javax/cache/configuration/CompleteConfiguration. Even though the bundle javax.cache.api is loaded.

**Comment by enflout** [comment] 2015-04-20 14:58
Hi guys, what's about the status of this task? I have got the same error in equinox osgi-container when try to run my application on the more than one computers. It may be an error in configuration, but I have no idea...

**Comment by serkan-ozal** [comment] 2015-05-01 17:05
Hi @enflout, 

Sorry for late response. I was very busy for 3.5-EA release. I haven't looked at the issue detailed and not tried to reproduce the issue yet. But I will take it before 3.5 release and will inform you from here. 

Regards.

**Comment by serkan-ozal** [comment] 2015-05-06 18:36
Hi @enflout @dschmitz

* Does this error occur with the latest Hazelcast release **3.4.2** ?

* Do you specify config classloader in `com.hazelcast.config.Config` while creating instance ?

* Do you set TCCL before creating instance ?

* Is it possible sharing `com.here.phoenix.hazelcast.HazelcastActivator` code ?

* Can you try this case by setting TCCL to application classloader as
``` java
ClassLoader appClassLoader = getClass().getClassLoader();
ClassLoader tccl = Thread.currentThread().getContextClassLoader();
try {
    Thread.currentThread().setContextClassLoader(appClassLoader);
    HazelcastInstance instance = Hazelcast.newHazelcastInstance();
    ...
} finally {
    Thread.currentThread().setContextClassLoader(tccl);
}
```

* Can you try this case by setting config classloader to application classloader as
``` java
ClassLoader appClassLoader = getClass().getClassLoader();
Config config = new Config();
...
config.setClassLoader(appClassLoader);
HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
...
```

**Comment by dschmitz** [comment] 2015-05-12 11:36
@serkan-ozal 

Hi I have given this investigative task to one of my team mates he will evaluate the latest version and your suggestions on a dedicated feature branch. We will come back with feedback to you soon. 
And we will share the activator code soon.

Regards
David

**Comment by serkan-ozal** [comment] 2015-05-12 12:48
Hi @dschmitz 

Thanks, I got your `HazelcastActivator` code.
As far as I see from the logs, `CacheService` is loaded by `org.eclipse.osgi.internal.loader.ModuleClassLoader` even though config classloader is set to your custom `CombinedClassLoader`. Because when `CacheService` class is loading in `ServiceManager`, it is first looked up via `CombinedClassLoader`, then it is not found and since it is also Hazelcast internal class, loaded via classloader (which is `org.eclipse.osgi.internal.loader.ModuleClassLoader`) of `ClassLoaderUtil` as here https://github.com/hazelcast/hazelcast/blob/v3.3.1/hazelcast/src/main/java/com/hazelcast/nio/ClassLoaderUtil.java#L107

Then since `CacheService` is loaded by `org.eclipse.osgi.internal.loader.ModuleClassLoader`, the other class loading in this class is done via `org.eclipse.osgi.internal.loader.ModuleClassLoader`. But as I suspected, `JCache` classes in not known by `org.eclipse.osgi.internal.loader.ModuleClassLoader` but by `CombinedClassLoader`.

So I think, can you also try with setting parent classloader of your custom `CombinedClassLoader`. In your `CombinedClassLoader`, can you try this issue by updating the `public Class<?> findClass(String name)` method like this:

``` java
public class CombinedClassLoader extends ClassLoader {

    ...
    private ClassLoader parent;

    public CombinedClassLoader(ClassLoader parent) {
        this.parent = parent;
    }

    ...

    @Override
    public Class<?> findClass(String name) throws ClassNotFoundException {
        // Search in bundles ...

        return parent.findClass(name);
    }

    ...

}
```

**Comment by serkan-ozal** [comment] 2015-05-12 13:23
Hi @dschmitz,

By the way, do you need JCache in your application? As far as I understand you don't need it. If not needed, why you add it to your classpath?

**Comment by mtopolnik** [comment] 2015-06-02 09:15
Refer to dschmitz's earlier comment; https://github.com/hazelcast/hazelcast/issues/3792#issuecomment-66549543

**Comment by serkan-ozal** [comment] 2015-06-04 17:39
Hi @dschmitz,

I have investigated the issue logs and your sample code and I think the problem is that JCache library (or module) is found by `CombinedClassLoader` in bundles but Hazelcast's cache service (`com.hazelcast.cache.impl.CacheService`) is found by `org.eclipse.osgi.internal.loader.ModuleClassLoader` (couldn't found by `CombinedClassLoader`).

1.
------
In your `CombinedClassLoader`, I see that you search request class in `ACTIVE` or `STARTING` stated bundles.

``` java
for (Map.Entry<Long, Bundle> entry : bundles.entrySet()) {
    try {
        Bundle bundle = entry.getValue();
        if (bundle.getState() == Bundle.ACTIVE || bundle.getState() == Bundle.STARTING) {
            return bundle.loadClass(name);
        }
    } catch (ClassNotFoundException cnfe) {
        // Try next
    }
}
```

Are you sure that, Hazelcast bundle is in `ACTIVE` or `STARTING` state? Maybe it is in `RESOLVED` state because as I seen, you are starting Hazelcast instance yourself not started automatically. So I thought that it may be passive at startup and so its state may be just `RESOLVED`. In this case, Hazelcast classes are ignored by your `CombinedClassLoader` and loaded by application classloader `org.eclipse.osgi.internal.loader.ModuleClassLoader`. 

Maybe you can add `Bundle.RESOLVED` and/or `Bundle.INSTALLED` states to mentioned `if` statement above.

2.
------
And also to be sure that Hazelcast can be found as bundle, in your `HazelcastActivator`, can you add also all installed bundles to your `CombinedClassLoader` like this:

``` java
...
public class HazelcastActivator {

    ...

    public void activate() {
        ...
        for (Bundle bundle : context.getBundles()) {
		combinedClassLoader.addBundle(bundle);
        }
        ...
    }

    ...

}
```

And as the last thing, are you sure that you define the Hazelcast as bundle (not just dependency) in your project?

Regards.

**Comment by serkan-ozal** [comment] 2015-06-05 05:56
@dschmitz 
On more thing, if you don't need to JCache API, can you remove JCache dependency and run your application with newer Hazelcast version such as `3.4.2` or `3.5-EA`

**Comment by serkan-ozal** [comment] 2015-06-08 18:48
I have tested on both `3.3.1`, `3.4.2` and current master branch with/without JCache support (JCache library as dependency) on  `Eclipse Equinox` with mentioned `HazelcastActivator` and `CombinedClassLoader` but didn't see any issue. I think it is related with user's environment or invalid bundle configuration. So I am closing the issue.

**Closed by serkan-ozal** 2015-06-08 18:48 UTC
Labels: Team: Core, Type: Critical, Type: Defect
