### ISSUE TITLE
Support instance profile in AWS joiner

### ISSUE THREAD

**Issue by adamskogman** [hazelcast/hazelcast#476] opened 2013-05-08 06:41 UTC
Launching an EC2 instance with an instance profile allows EC2 API access w/o an explicit access/secret key (it reads a session token from the instance metadata). This greatly simplifies configuring the java app.

Please look into supporting this in Hazelcast. It is supported OOTB in the AWS Java SDK, so switching to that library instead of using your own for AWS would be a possible way forward.

**Comment by mesutcelik** [comment] 2015-02-17 12:47
I am closing that one. I see that this is duplicate of https://github.com/hazelcast/hazelcast/issues/2630

**Closed by mesutcelik** 2015-02-17 12:47 UTC
Labels: Team: Integration, Type: Enhancement
