### ISSUE TITLE
Management Center Map screen does not show throughput info for TransactionalMap

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast#11640] opened 2017-10-19 12:51 UTC
on version 3.8.4, when populating a TransactionalMap from a client, I see the size is growing but throughput table is zero.
<img width="1432" alt="screen shot 2017-10-19 at 13 42 43" src="https://user-images.githubusercontent.com/3787862/31771575-4c30c198-b4e5-11e7-9488-4cec9144f7d9.png">

**Comment by emre-aydin** [comment] 2017-10-19 14:04
It seems the problem is not related to Management Center but rather the member does not increment the counts on `LocalMapStatsImpl` when doing put, get or remove operations on a transactional map.

**Comment by mesutcelik** [comment] 2017-11-21 11:30
@tombujok 

There is no stats for TransactionalMap on the member side so we don't display them on MC. When you provide stats then we can also implement MC part. 
I am also not sure this can be done in patch release because it is not actually a fix but adding complete set of stats for TransactionalMap

**Comment by burakcelebi** [comment] 2018-01-02 13:16
Closed as internal request.

**Closed by burakcelebi** 2018-01-02 13:16 UTC
Labels: Internal-Request, Team: Core, Team: Integration, Type: Enhancement
