### ISSUE TITLE
Node IP gets added to blacklist

### ISSUE THREAD

**Issue by LinaSchad** [hazelcast/hazelcast#13857] opened 2018-09-28 08:17 UTC
We ran into an issue when using Hazelcast indirectly through Apache Karaf Cellar. Sometimes the two nodes we started would be able to build a cluster and sometimes not. We then found a log message that the IP Adress of the second node was added to a Hazelcast blacklist automatically. After a little while it appears to be delisted, since the connection was being established after a while in that we didn't do anything but printing the node list with the command `cluster:node-list`.

We'd really appreciate any help with this problem. Thanks :)

- Hazelcast version: 3.8.9 (due to all newer versions not being able to solve all dependencies for OSGi)
- Cluster size: 2 Nodes
- Number of clients: 2
- Java version: 1.8
- Operating system: macOs High Sierra 10.13.5 und 10.13.6
- Log:
 ```
09:38:37.027 WARN [pool-10-thread-1] Name of the hazelcast schema location incorrect using default
09:38:37.244 INFO [pool-10-thread-1] [LOCAL] [cellar] [3.8.5] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [172.16.45.22]
09:38:37.244 INFO [pool-10-thread-1] [LOCAL] [cellar] [3.8.5] Prefer IPv4 stack is true.
09:38:37.245 WARN [pool-10-thread-1] [LOCAL] [cellar] [3.8.5] Could not find a matching address to start with! Picking one of non-loopback addresses.
09:38:37.249 INFO [pool-10-thread-1] [LOCAL] [cellar] [3.8.5] Picked [172.16.34.155]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
09:38:37.257 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Hazelcast 3.8.5 (20170906 - e424927) starting at [172.16.34.155]:5701
09:38:37.257 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
09:38:37.257 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Configured Hazelcast Serialization version : 1
09:38:37.390 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Backpressure is disabled
09:38:37.722 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Creating TcpIpJoiner
09:38:37.848 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Starting 8 partition threads
09:38:37.849 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Starting 5 generic threads (1 dedicated for priority tasks)
09:38:37.855 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] [172.16.34.155]:5701 is STARTING
09:38:37.881 INFO [hz.cellar.cached.thread-3] [172.16.34.155]:5701 [cellar] [3.8.5] Connecting to /172.16.45.22:5703, timeout: 0, bind-any: true
09:38:37.881 INFO [hz.cellar.cached.thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Connecting to /172.16.45.22:5701, timeout: 0, bind-any: true
09:38:37.881 INFO [hz.cellar.cached.thread-2] [172.16.34.155]:5701 [cellar] [3.8.5] Connecting to /172.16.45.22:5702, timeout: 0, bind-any: true
09:38:37.904 INFO [hz.cellar.cached.thread-3] [172.16.34.155]:5701 [cellar] [3.8.5] Could not connect to: /172.16.45.22:5703. Reason: SocketException[Connection refused to address /172.16.45.22:5703]
09:38:37.904 INFO [hz.cellar.cached.thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Could not connect to: /172.16.45.22:5701. Reason: SocketException[Connection refused to address /172.16.45.22:5701]
09:38:37.905 INFO [hz.cellar.cached.thread-3] [172.16.34.155]:5701 [cellar] [3.8.5] [172.16.45.22]:5703 is added to the blacklist.
09:38:37.905 INFO [hz.cellar.cached.thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] [172.16.45.22]:5701 is added to the blacklist.
09:38:37.905 INFO [hz.cellar.cached.thread-2] [172.16.34.155]:5701 [cellar] [3.8.5] Could not connect to: /172.16.45.22:5702. Reason: SocketException[Connection refused to address /172.16.45.22:5702]
09:38:37.905 INFO [hz.cellar.cached.thread-2] [172.16.34.155]:5701 [cellar] [3.8.5] [172.16.45.22]:5702 is added to the blacklist.
09:38:38.882 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Cluster version set to 3.8
09:38:38.883 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5]
Members [1] {
	Member [172.16.34.155]:5701 - b4ed8157-ffea-4d1f-88ad-76afbfbbff11 this
}
09:38:38.903 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] [172.16.34.155]:5701 is STARTED
09:38:38.952 INFO [pool-10-thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] Initializing cluster partition table arrangement...
09:38:39.037 INFO [pool-10-thread-1] Registering commands for bundle org.apache.karaf.cellar.kar/4.1.1
09:38:39.038 INFO [pool-10-thread-1] Registering commands for bundle org.apache.karaf.cellar.config/4.1.1
09:38:39.039 INFO [pool-10-thread-1] Registering commands for bundle org.apache.karaf.cellar.bundle/4.1.1
09:38:39.042 INFO [pool-10-thread-1] Registering commands for bundle org.apache.karaf.cellar.features/4.1.1
09:38:39.047 INFO [pool-10-thread-1] Registering commands for bundle org.apache.karaf.cellar.core/4.1.1
09:38:39.063 INFO [pool-10-thread-1] Registering commands for bundle org.apache.karaf.cellar.shell/4.1.1
09:43:49.196 INFO [hz.cellar.cached.thread-2] [172.16.34.155]:5701 [cellar] [3.8.5] Established socket connection between /172.16.34.155:62099 and /172.16.45.22:5701
09:43:49.253 INFO [hz.cellar.cached.thread-1] [172.16.34.155]:5701 [cellar] [3.8.5] [172.16.45.22]:5701 should merge to us , both have the same data member count: 1
09:45:42.094 INFO [hz.cellar.IO.thread-in-0] [172.16.34.155]:5701 [cellar] [3.8.5] Connection[id=1, /172.16.34.155:62099->/172.16.45.22:5701, endpoint=[172.16.45.22]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
09:45:49.155 INFO [hz.cellar.cached.thread-7] [172.16.34.155]:5701 [cellar] [3.8.5] Established socket connection between /172.16.34.155:62134 and /172.16.45.22:5701
09:45:55.176 INFO [hz.cellar.priority-generic-operation.thread-0] [172.16.34.155]:5701 [cellar] [3.8.5]
```
- Apache Karaf Cellar 4.1.1

**Comment by mmedenjak** [comment] 2018-10-24 06:42
Hi @LinaSchad !

Looks like the `172.16.34.155` node is having issues connecting to `172.16.45.22`:
```
Connection refused to address /172.16.45.22:5703
Connection refused to address /172.16.45.22:5701
Connection refused to address /172.16.45.22:5702
```

It also seems to me that other nodes have the same connection issues as they are starting as single node clusters:
`[172.16.45.22]:5701 should merge to us , both have the same data member count: 1`

Can you turn on DEBUG logging and try again? Is the IP address for `172.16.34.155` correct? Are the nodes behind some kind of NAT or do they have multiple IP addresses?
Can you show us the logs from the other nodes from the time this happened?
`09:45:42.094 INFO [hz.cellar.IO.thread-in-0] [172.16.34.155]:5701 [cellar] [3.8.5] Connection[id=1, /172.16.34.155:62099->/172.16.45.22:5701, endpoint=[172.16.45.22]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side`.

What do you mean by `Hazelcast version: 3.8.9 (due to all newer versions not being able to solve all dependencies for OSGi)`? @googlielmo is this something we need to address?

**Comment by uditkumawat** [comment] 2018-12-19 12:45
@LinaSchad  @mmedenjak  Any update on this issue ? We are also facing the same issue.. Can you please tell us what is the current stable version ?

**Comment by LinaSchad** [comment] 2018-12-19 12:49
@mmedenjak Sorry, your answer must have somehow slipped through, I can't remember that I read it. Unfortunately we adjusted our technology stack a bit and I'm not working with Hazelcast anymore, so I can't remember what the setting was besides what I initially posted and I'm not able to reproduce it.

@uditkumawat Sorry, no update from me. Hope you get help!

**Comment by tjuchniewicz** [comment] 2019-01-03 14:13
I experience the same issue in my environment:
```
[cached.thread-1] c.h.i.cluster.impl.DiscoveryJoiner       : [127.0.0.1]:5701 [3.11.1] Returning null timeout<0, -10
[cached.thread-1] c.h.i.cluster.impl.DiscoveryJoiner       : [127.0.0.1]:5701 [3.11.1] Sending SplitBrainJoinMessage to [10.1.0.110]:5701
[cached.thread-3] c.h.nio.tcp.TcpIpConnectionManager       : [127.0.0.1]:5701 [3.11.1] Established socket connection between /10.1.0.109:56711 and /10.1.0.110:5701
[.IO.thread-in-0] com.hazelcast.nio.tcp.TcpIpConnection    : [127.0.0.1]:5701 [3.11.1] Initialized new cluster connection between /10.1.0.109:56711 and /10.1.0.110:5701
[.IO.thread-in-0] com.hazelcast.nio.tcp.TcpIpConnection    : [127.0.0.1]:5701 [3.11.1] Connection[id=121, /10.1.0.109:56711->/10.1.0.110:5701, endpoint=[10.1.0.110]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side

java.io.EOFException: Remote socket closed!
        at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:116)
        at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368)
        at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353)
        at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279)
        at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234)

[vdocker.event-1] c.h.internal.cluster.ClusterService      : [127.0.0.1]:5701 [simple-service:default,devdocker] [3.11.1] Removed connection to [10.1.0.110]:5701
```

I have no idea how to debug.  Which endpoint are we trying to access here? For example I can access 10.1.0.110:5701/hazelcast/rest endpoint from 10.1.0.109 pod.

**Comment by tjuchniewicz** [comment] 2019-01-07 13:53
My issue has been fixed. The reason was invalid network interfaces configuration.

**Comment by mmedenjak** [comment] 2019-10-25 12:46
Closing as one occurrence was caused by invalid configuration while we are lacking information for the other occurrence. Please open a new issue if it occurs again.

**Closed by mmedenjak** 2019-10-25 12:46 UTC
Labels: Priority: High, Source: Community, Team: Core, Team: Integration
