### ISSUE TITLE
IMap.evict() doesn't work when using MapStore with write-behind

### ISSUE THREAD

**Issue by fschuh** [hazelcast/hazelcast#6246] opened 2015-09-18 04:39 UTC
On Hazelcast 3.5.2, I found that calling IMap.evict() or IMap.evictAll() won't have any effect if we're using a MapStore with write-behind on that map.
The entries will still stay on the map, even though evict() returns true.
The expected behavior is the entry should be evicted __immediately__ after evict() returns - any get() operation that follows should never be able to reach the evicted data.

Here's a code sample to reproduce the issue:

	package hazelcast;

	import com.hazelcast.config.Config;
	import com.hazelcast.config.MapStoreConfig;
	import com.hazelcast.core.Hazelcast;
	import com.hazelcast.core.HazelcastInstance;
	import com.hazelcast.core.IMap;
	import com.hazelcast.core.MapStore;

	import java.util.Collection;
	import java.util.Map;

	public class TestEvictMapStore {
		static class DummyMapStore<K, V> implements MapStore<K, V> {
			public void store(K key, V value) {}
			public void storeAll(Map<K, V> map) {}
			public void delete(K key) {}
			public void deleteAll(Collection<K> keys) {}
			public V load(K key) { return null; }
			public Map<K, V> loadAll(Collection<K> keys) { return null; }
			public Iterable<K> loadAllKeys() { return null; }
		}

		public static void main(String[] s) throws Exception {

			Config config = new Config();
			MapStoreConfig mapStoreConfig = new MapStoreConfig()
					.setEnabled(true)
					.setClassName("hazelcast.TestEvictMapStore$DummyMapStore")
					.setWriteDelaySeconds(1);

			config.getMapConfig("test_mapstore").setMapStoreConfig(mapStoreConfig);

			HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);

			IMap<String, String> map = instance.getMap("test_mapstore");
			map.put("key", "value");

			boolean evicted = map.evict("key");
			System.out.println("Evicting: " + evicted);

			System.out.println("Value after eviction: " + map.get("key"));

			Thread.sleep(2000);

			System.out.println("Value after eviction and waiting: " + map.get("key"));

			map.flush();

			System.out.println("Value after flushing: " + map.get("key"));

			instance.shutdown();
		}
	}

At the end of this sample code, the entry is still present even after flushing the map.
Note that if we disable the MapStore or set writeDelaySeconds to 0, the entry is evicted immediately and everything works as expected.

**Comment by jerrinot** [comment] 2015-09-18 16:43
Just an observation: if you call `evict()` immediately followed  by `flush()` then the subsequent `get()` will return `null` as expected. I am not sure if the current behaviour is buggy or not, this is merely just an observation. 

I assume the `evict()` removes entry from a Hazelcast RecordStore and place it into a queue of write behind store. The subsequent `get()` will NOT find the entry in a RecordStore, but it will check the write-behind queue. The item is found in the queue and it's revived and placed back into `RecordStore`. 

@ahmetmircik can provides details and describe what's the expected behaviour.

**Comment by ahmetmircik** [comment] 2015-11-26 09:56
Hi @fschuh, first of all, we can not distinguish a `MapStore` implementation than a `MapLoader` one, since `MapLoader` is extended by `MapStore`. So there is not a `store only MapStore`, means you also have to implement `MapLoader` methods as in your implementation.

Secondly, for your test code, an immediate `get` after `evict` tries to load value from store and if it finds that it is still in the write-behind waiting queue, it loads that value from there and returns. But if you wait until the end of write-behind delay time, you can see that `get` will return null because your implementation is returning null from `MapStore#load` method. This is needed to prevent potential data inconsistencies by assuming that latest value for a key is in write-behind queue and it first should be loaded from there. Returning back my first explanation, if we had a `store only MapStore` implementation, it would be easy to make it as in your expectations. But now it seems not possible. Given that current behaviour is not causing any data inconsistencies, closing this issue by stating that it is the expected behaviour at the moment.

**Closed by ahmetmircik** 2015-11-26 09:56 UTC
Labels: Team: Core, Type: Defect
