### ISSUE TITLE
JMX calls querying the "size" attribute of a distributed map are stuck

### ISSUE THREAD

**Issue by tobiasfriedrich** [hazelcast/hazelcast#5104] opened 2015-04-20 08:04 UTC
In a basic cluster consisting of two nodes, RMI threads querying the "size" attribute of a distributed map are stuck waiting for a response. A thread dump shows that they are all at:

```
"RMI TCP Connection(400)-127.0.1.1" daemon prio=10 tid=0x00007f91e400c000 nid=0x36af in Object.wait() [0x00007f915508c000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000c68b7398> (a com.hazelcast.spi.impl.BasicInvocation$InvocationFuture)
	at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.waitForResponse(BasicInvocation.java:723)
	- locked <0x00000000c68b7398> (a com.hazelcast.spi.impl.BasicInvocation$InvocationFuture)
	at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:697)
	at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:676)
	at com.hazelcast.spi.impl.BasicOperationService.invokeOnPartitions(BasicOperationService.java:594)
	at com.hazelcast.spi.impl.BasicOperationService.invokeOnAllPartitions(BasicOperationService.java:549)
	at com.hazelcast.map.proxy.MapProxySupport.size(MapProxySupport.java:420)
	at com.hazelcast.map.proxy.MapProxyImpl.size(MapProxyImpl.java:40)
	at com.hazelcast.jmx.MapMBean.getSize(MapMBean.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.jmx.HazelcastMBean.getAttribute(HazelcastMBean.java:85)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1464)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:97)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1328)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1420)
	at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:657)
	at sun.reflect.GeneratedMethodAccessor260.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
	at sun.rmi.transport.Transport$2.run(Transport.java:202)
	at sun.rmi.transport.Transport$2.run(Transport.java:199)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:198)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.access$400(TCPTransport.java:619)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:684)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:681)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

This is Hazelcast v3.2.4 with two nodes in the cluster. The same call is working instantly when being executed from the other node. The affected map's backup count is set to 1, further map config is as follows:

```
MapConfig{name='sessionId2token-1', inMemoryFormat=BINARY', backupCount=1, asyncBackupCount=0, timeToLiveSeconds=0, maxIdleSeconds=300, evictionPolicy='NONE', evictionPercentage=25, maxSizeConfig=MaxSizeConfig{maxSizePolicy='PER_NODE', size=2147483647}, readBackupData=true, nearCacheConfig=null, mapStoreConfig=null, mergePolicyConfig='com.hazelcast.map.merge.PutIfAbsentMapMergePolicy', wanReplicationRef=null, listenerConfigs=[], mapIndexConfigs=[]}
```

**Comment by metanet** [comment] 2015-05-21 07:49
Closing this one since I couldn't reproduce this issue on either 3.2.4 or current master.

**Closed by metanet** 2015-05-21 07:49 UTC
Labels: Team: Core, Team: Integration, Type: Defect
