### ISSUE TITLE
Poor performance of "containsKey()" when near-cache is enabled and cluster size > 1

### ISSUE THREAD

**Issue by francesco-hz** [hazelcast/hazelcast#16458] opened 2020-01-09 15:04 UTC
ZD5849
 
Running a simple application performing sustained `containsKey()` calls against a map shows a performance degradation when at least two members are defined, despite having `near-cache` defined for the map. We suspect the root cause is that `containsKey()` does not honour near cache contents, and reads remotely even if the key is already in the near cache. 

**Expected behavior**
Near cache contents should be honoured. This is the behaviour seen when replacing `containsKey()` with `get()`. 

**To Reproduce**
Start a two member cluster. Preload a map with some values (or keep empty)
Run a tight loop performing `containsKey(key1)` against the same key. Observe performance degradation once second member is started

**Additional context**
This was reproduced with Java 1.8 and Hazelcast 3.12.4 (edited). The call was done from a member. 

Thank you.

**Comment by ahmetmircik** [comment] 2020-01-09 15:14
Is your near cache is on member side? If yes, is the issue happening even you set `NearCacheConfig#setCacheLocalEntries` to `true`? Normally, `containsKey` does a near-cache lookup before doing a remote call.

**Comment by francesco-hz** [comment] 2020-01-09 15:23
Thank you for the tip. I am using the following configuration snippet for near cache

```
        <near-cache>
            <time-to-live-seconds>0</time-to-live-seconds>
            <max-idle-seconds>60</max-idle-seconds>
            <invalidate-on-change>true</invalidate-on-change>
            <in-memory-format>BINARY</in-memory-format>
            <cache-local-entries>true</cache-local-entries>
            <eviction size="5000" max-size-policy="ENTRY_COUNT" eviction-policy="LRU"/>
        </near-cache>
```

I am pasting the log once the second member is started. Note the performance degradation. 

>
> ...
 ContainsKey time:756 Ratio:0.0
 ContainsKey time:762 Ratio:0.0
 ContainsKey time:759 Ratio:0.0
Jan 09, 2020 4:20:29 PM com.hazelcast.internal.cluster.ClusterService
INFO: [127.0.0.1]:5701 [dev] [3.12.4] 
Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - d62e6270-dae6-4ff0-97c8-ab65fbd8c67e this
	Member [127.0.0.1]:5702 - 44420a7d-e7ea-4e8e-96f7-dd6f7f35a4e4
]
Jan 09, 2020 4:20:29 PM com.hazelcast.internal.partition.impl.MigrationManager
INFO: [127.0.0.1]:5701 [dev] [3.12.4] Re-partitioning cluster data... Migration queue size: 271
Jan 09, 2020 4:20:31 PM com.hazelcast.internal.partition.impl.MigrationThread
INFO: [127.0.0.1]:5701 [dev] [3.12.4] All migration tasks have been completed. (lastRepartitionTime=Thu Jan 09 16:20:29 CET 2020, completedMigrations=271, totalCompletedMigrations=271, elapsedMigrationTime=365ms, totalElapsedMigrationTime=365ms)
 ContainsKey time:3281 Ratio:0.0
 ContainsKey time:5772 Ratio:0.0
 ContainsKey time:5752 Ratio:0.0
>  ContainsKey time:6440 Ratio:0.0
> 

Thank you.

**Comment by francesco-hz** [comment] 2020-01-09 15:26
Also, yes, this is an embedded application. Cache is on the member side. 
Thank you.

**Comment by ahmetmircik** [comment] 2020-01-09 15:33
One more thing, `containsKey` doesn't populate near cache, you have to do a first `get` to have it in near cache. But even you do this, eviction or expiration can kick in and can remove some already near cached entries. To be safe from this effect, a test by disabling eviction and expiration would be better.

**Comment by francesco-hz** [comment] 2020-01-09 15:50
I changed the configuration to the following
```
       <near-cache>
            <time-to-live-seconds>0</time-to-live-seconds>
            <max-idle-seconds>0</max-idle-seconds>
            <invalidate-on-change>true</invalidate-on-change>
            <in-memory-format>BINARY</in-memory-format>
            <cache-local-entries>true</cache-local-entries>
            <eviction size="5000" max-size-policy="ENTRY_COUNT" eviction-policy="NONE"/>
        </near-cache>
```
and performed a `get()` before entering the `containsKey()` loop. 
I can see a much better performance initially, but then it degrades to the same response time. 

> ...
> ContainsKey time:25 Ratio:0.0
 ContainsKey time:23 Ratio:0.0
 ContainsKey time:23 Ratio:0.0
 ContainsKey time:22 Ratio:0.0
 ContainsKey time:23 Ratio:0.0
 ContainsKey time:23 Ratio:0.0
 ContainsKey time:2768 Ratio:0.0
 ContainsKey time:5694 Ratio:0.0
 ContainsKey time:5846 Ratio:0.0
 ContainsKey time:6261 Ratio:0.0
 ContainsKey time:5547 Ratio:0.0
> ...

Please note, I see the same type of behaviour (performance degradation with 2+ members) even if I run the test on  an empty map. Problem does not occur with `get()` (same near-cache settings). 

Thank you

**Comment by ahmetmircik** [comment] 2020-01-09 15:54
is it possible to share your test?

**Comment by francesco-hz** [comment] 2020-01-09 15:58
Sure. I am just trying to simulate a customer issue. See ZD5849 for details. 

```
    public static void main(String[] args) throws InterruptedException {

        HazelcastInstance h = Hazelcast.newHazelcastInstance();
        IMap<String, String> customerMap = h.getMap("customers");

        //preload map and then clear it
//        customerMap.put("key", "value");
//        Thread.sleep(1000);
//        customerMap.clear();
//        String value = customerMap.get("key");

        int count = 100000;
        while (true) {
            long time1 = System.currentTimeMillis();
            for (int i = 0; i < count; i++) {
                Boolean found = customerMap.containsKey("key");
//                String value = customerMap.get("key");
            }
            long time2 = System.currentTimeMillis();
            System.out.println( " ContainsKey time:" + (time2 - time1) + " Ratio:" + (double) ((time2 - time1)/count));
        }
    }
```

Thank you.

**Comment by ahmetmircik** [comment] 2020-01-09 16:29
I ran the test after doing a first `get` as in below, response times seemed ok.

Please, keep in mind that `containsKey` doesn't populate near cache. But `get` does. Even on an empty map, with `get`, near cache knows key doesn't exist and doesn't do remote call(after first one). But this not the case for `containsKey`, it always does a remote call even map is empty.

```
public static void main(String[] args) throws InterruptedException {
        Config config = new Config();

        NearCacheConfig nearCacheConfig = new NearCacheConfig();
        nearCacheConfig
                .setCacheLocalEntries(true)
                .getEvictionConfig()
                .setEvictionPolicy(EvictionPolicy.NONE);

        config.getMapConfig("customers").setNearCacheConfig(nearCacheConfig);

        HazelcastInstance h = Hazelcast.newHazelcastInstance(config);

        IMap<String, String> customerMap = h.getMap("customers");

        // preload map
        customerMap.put("key", "value");
        // here we cache key into near cache
        customerMap.get("key");

        int count = 100000;
        while (true) {
            long time1 = System.currentTimeMillis();
            for (int i = 0; i < count; i++) {
                customerMap.containsKey("key");
            }
            long time2 = System.currentTimeMillis();
            System.out.println(" ContainsKey time:" + (time2 - time1) + " Ratio:" + (double) ((time2 - time1) / count));
        }
    }
```

**Comment by pveentjer** [comment] 2020-01-10 07:51
The issue came from the client code. @sancar confirmed it was a bug.

And imho containsKey should be cached as well. So a containsKey should forward to a get. The fact that we don't cache the 'containsKey' is another bug.

**Comment by ahmetmircik** [comment] 2020-01-10 08:46
Client side near cache is missing a conversion if `serializeKeys` setting is not default. This is a bug.
 
But in the scope of this issue, near cache is server side near cache, it is not on client side and there is no bug related to containsKey on server side as far as i can see.

Caching `containsKey` is never implemented, this can a new feature to add.

**Comment by sancar** [comment] 2020-01-10 12:17
I have send the fixes to master and the maintenance to fix containsKey to do the proper conversion. 
I did not implement the caching part since it is being discussed.

**Comment by ahmetmircik** [comment] 2020-01-13 07:08
Closing this issue, since `containsKey` is working as designed. 
But during investigations of this issue, another issue was found: #16472
For further info please check my comment [here](https://github.com/hazelcast/hazelcast/issues/16458#issuecomment-572933360).

**Closed by ahmetmircik** 2020-01-13 07:08 UTC
Labels: Module: IMap, Module: Near Cache, Team: Core, Type: Defect
