### ISSUE TITLE
Global serializer is only called for entries that don't implement java.io.Serializable

### ISSUE THREAD

**Issue by fschuh** [hazelcast/hazelcast#6287] opened 2015-09-25 05:08 UTC
On Hazelcast 3.5.2, I found that global serializers will be ignored unless your serializing entry's class does NOT implement *java.io.Serializable*.
For entries that implement *java.io.Serializable*, the default Java serialization seems to be used instead.

The issue can be reproduced with the sample code below (depends on Kryo):

	package hazelcast;

	import com.esotericsoftware.kryo.Kryo;
	import com.esotericsoftware.kryo.io.Input;
	import com.esotericsoftware.kryo.io.Output;
	import com.hazelcast.config.Config;
	import com.hazelcast.config.GlobalSerializerConfig;
	import com.hazelcast.config.SerializationConfig;
	import com.hazelcast.config.SerializerConfig;
	import com.hazelcast.core.Hazelcast;
	import com.hazelcast.core.HazelcastInstance;
	import com.hazelcast.core.IMap;
	import com.hazelcast.nio.ObjectDataInput;
	import com.hazelcast.nio.ObjectDataOutput;
	import com.hazelcast.nio.serialization.StreamSerializer;
	import com.ubi.sngs.util.KryoThreadSafe;

	import java.io.IOException;
	import java.io.InputStream;
	import java.io.OutputStream;
	import java.io.Serializable;

	/**
	 * Created by fschuh on 9/25/2015.
	 */
	public class TestGlobalSerializer {

		static class SimpleKryoSerializer<T> implements StreamSerializer<T> {
			private Kryo kryo;

			public SimpleKryoSerializer() {
				// not thread safe, just for testing
				kryo = new Kryo();
			}

			@Override
			public int getTypeId() {
				return 1;
			}

			@Override
			public void write(ObjectDataOutput objectDataOutput, T object) throws IOException {
				System.out.println("Kryo Serializer: write instance of " + object.getClass());
				Output output = new Output((OutputStream) objectDataOutput);
				kryo.writeClassAndObject(output, object);
				output.flush();
			}

			@Override
			@SuppressWarnings("unchecked")
			public T read(ObjectDataInput objectDataInput) throws IOException {
				System.out.println("Kryo Serializer: read");

				InputStream in = (InputStream) objectDataInput;
				Input input = new Input(in);

				return (T)kryo.readClassAndObject(input);
			}

			@Override
			public void destroy() {
			}
		}

		static class TestPojoSerializable implements Serializable {
			String name;
			String value;
		}

		static class TestPojoNotSerializable  {
			String name;
			String value;
		}

		public static void main(String[] s) throws Exception {
			Config config = new Config();

			GlobalSerializerConfig globalSerializerConfig = new GlobalSerializerConfig()
					.setImplementation(new SimpleKryoSerializer());

			SerializationConfig serializationConfig = new SerializationConfig()
					.setGlobalSerializerConfig(globalSerializerConfig);

			config.setSerializationConfig(serializationConfig);

			HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);

			IMap<String, Object> map = instance.getMap("test");
			map.put("key1", new TestPojoSerializable());
			map.put("key2", new TestPojoNotSerializable());

			instance.shutdown();
		}
	}

If the global serializer worked correctly, the code above would print *"Kryo Serializer: write instance of..."* twice.
However it only prints it once, and only for the object that doesn't implement *java.io.Serializable*.

If I add a specific custom serializer for *TestPojoSerializable* then the serializer is called as expected.
The issue only applies to global serializers.

**Comment by jerrinot** [comment] 2015-09-25 09:03
Hi @fschuh,

I'm not sure whether this behaviour is a bug or not. As a contract of the `setGlobalSerializerConfig()` method says:
`globalSerializerConfig configuration of serializer that will be used if no other serializer is applicable`.

Obviously when your object implements `j.i.Serializable` then there is other serializer available. @gurbuzali could probably clarify what's the intended behaviour. 

I believe you could achieve your desired behaviour registering a serializer specific for your type. (=not a global one)

**Comment by fschuh** [comment] 2015-09-29 14:02
Hi jerrinot,
I believe one of the reasons one would set a global serializer is to avoid the default Java serializer entirely.
For things like EntryProcessors, for example, I would have to explicitly define every single one of them in my Hazelcast configure file, and that may not even be possible as some of them may be anonymous classes or lambda expressions.
It this is indeed the right behavior and not a bug, Hazelcast should at least provide a way to disable the default Java serializer so our custom global serializer would not be ignored.

**Comment by jerrinot** [comment] 2015-09-30 06:56
@fschuh: I understand your use-case and I agree it could be useful to have it. We'll treat this as a Feature Request as it's a different scenario than what Global Serializers were intended to be used for. 

We register [bunch of serializers](https://github.com/jerrinot/hazelcast/blob/30224d288563aa130dc5323bc9dea56d282eb49c/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/SerializationServiceImpl.java#L160) for types built in JVM:  We would need to define a strategy how to overwrite (some of?) them. 

The obvious workaround for now is to not implement java `j.i.Serializable` interface. I appreciate this is not always possible. Also if you implement an interface such as [DataSerializable](https://github.com/jerrinot/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/nio/serialization/DataSerializable.java#L33-33) or [IdentifiedDataSerializable](https://github.com/jerrinot/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/nio/serialization/IdentifiedDataSerializable.java#L30-30) then this takes a precedence over the build-in Serializable serializer.

**Comment by fschuh** [comment] 2015-10-06 06:24
Fair enough, hopefully this feature can make it into a future release.
I'd be eager to use it. Being able to override the hardcoded default serializers for those built in JVM types would do it perfectly.

**Comment by asimarslan** [comment] 2016-06-10 14:52
This issue is already fixed by https://github.com/hazelcast/hazelcast/pull/6841.
In order to configure GlobalSerializer to handle  java Serializables one should configure global serialiser as:

```
Config config = new Config();
GlobalSerializerConfig globalSerializerConfig = new GlobalSerializerConfig()
 .setImplementation(new TheGlobalSerializer())
 .setOverrideJavaSerialization(true);

SerializationConfig serializationConfig = new SerializationConfig()
 .setGlobalSerializerConfig(globalSerializerConfig);
```

Please note that if OverrideJavaSerialization is set then this global serializer should handle all java serializables which means you should delegate any java serializable object that you're not interested in to jvm serialization.

**Closed by asimarslan** 2016-06-10 14:52 UTC
Labels: Team: Client, Type: Enhancement
