### ISSUE TITLE
EntryListenerOnReconnectTest.testListenersSmartRoutingMultipleServer & testListenersNonSmartRoutingMultipleServer

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8244] opened 2016-05-25 09:33 UTC
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
    at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:156)
    at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:153)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:147)
    at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:452)
    at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:446)
    at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:247)
    at com.hazelcast.client.listeners.EntryListenerOnReconnectTest.produceEvent(EntryListenerOnReconnectTest.java:49)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/228/testReport/junit/com.hazelcast.client.listeners/EntryListenerOnReconnectTest/testListenersSmartRoutingMultipleServer/

**Comment by hasancelik** [comment] 2016-05-26 08:53
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:156)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:153)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:147)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:452)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:446)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:247)
	at com.hazelcast.client.listeners.EntryListenerOnReconnectTest.produceEvent(EntryListenerOnReconnectTest.java:49)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1070/testReport/junit/com.hazelcast.client.listeners/EntryListenerOnReconnectTest/testListenersSmartRoutingMultipleServer/

**Comment by hasancelik** [comment] 2016-05-30 10:11
**testListenersNonSmartRoutingMultipleServer**
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:156)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:153)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:147)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:452)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:446)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:247)
	at com.hazelcast.client.listeners.EntryListenerOnReconnectTest.produceEvent(EntryListenerOnReconnectTest.java:49)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/818/testReport/junit/com.hazelcast.client.listeners/EntryListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

**Comment by hasancelik** [comment] 2016-06-03 07:26
**testListenersNonSmartRoutingMultipleServer**
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:156)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:153)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:147)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:452)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:446)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:247)
	at com.hazelcast.client.listeners.EntryListenerOnReconnectTest.produceEvent(EntryListenerOnReconnectTest.java:49)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/241/testReport/junit/com.hazelcast.client.listeners/EntryListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

**Comment by cangencer** [comment] 2016-07-18 13:11
This, #8254 and #8286 only failed between May 25 and Jun 3, even though there were no changes on client side between these dates regarding listener registration. I looked at the server logs and it looks like this might be due to commit 877798010c6fcaafb92a4456607f1fe9f2acb409 by @metanet, which was merged on May 24 and reverted by b406815d3ad99d4b399fac188d4c211b65d1bde6
on Jun 3.

The test failures were related to not getting partition response from server and the changes were related to partition table initialisation. The failure could not be reproduced locally and no failures have been detected since the revert, I will be closing all three issues. If this failure ever happens again, the issues should be reopened.

**Comment by hasancelik** [comment] 2016-11-16 11:05
**testListenersSmartRoutingMultipleServer**
```
java.lang.AssertionError: expected:<3> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$3.run(AbstractListenersOnReconnectTest.java:152)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:905)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:919)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrations(AbstractListenersOnReconnectTest.java:146)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersInternal(AbstractListenersOnReconnectTest.java:95)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersSmartRoutingMultipleServer(AbstractListenersOnReconnectTest.java:501)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast-client/140/testReport/junit/com.hazelcast.client.listeners/EntryListenerOnReconnectTest/testListenersSmartRoutingMultipleServer/

**Comment by Donnerbart** [comment] 2016-11-21 17:05
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersForHeartbeat(AbstractListenersOnReconnectTest.java:256)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testClusterReconnectDueToHeartbeatSmartRouting(AbstractListenersOnReconnectTest.java:339)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/5800/testReport/junit/com.hazelcast.client.listeners/EntryListenerOnReconnectTest/testClusterReconnectDueToHeartbeatSmartRouting/

**Comment by ihsandemir** [comment] 2016-11-24 11:04
I submitted a PR https://github.com/hazelcast/hazelcast/pull/9312 which may have caused https://github.com/hazelcast/hazelcast/issues/8244#issuecomment-262000805

**Closed** 2016-12-30 09:00 UTC
Labels: Team: Client, Type: Test-Failure
