### ISSUE TITLE
 ItemListener on IList dosen't recognize remove(<ordinal>)

### ISSUE THREAD

**Issue by helmut-at-work** [hazelcast/hazelcast#5470] opened 2015-06-09 07:22 UTC
A remove(0) triggers  itemAdded instead of itemRemoved.

```java
public class Sample implements ItemListener {

	public static void main(String[] args) {
		Sample sample = new Sample();
		HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
		IList<String> list = hazelcastInstance.getList("default");
		list.addItemListener(sample, true);

		String firstString = "firstString";
		list.add(firstString);
		//This works fine: list.remove(firstString);
		list.remove(0); // This triggers itemAdded. Why?
	}

	@Override
	public void itemAdded(ItemEvent ie) {
		System.out.println("Item added = " + ie);
	}

	@Override
	public void itemRemoved(ItemEvent ie) {
		System.out.println("Item removed = " + ie);
	}
}
```
Output:
Item added = ItemEvent{event=ADDED, item=firstString, member=Member [192.168.0.86]:5702} 
Item added = **ItemEvent{event=ADDED, item=null,** member=Member [192.168.0.86]:5702}

**Comment by eminn** [comment] 2015-06-09 07:38
Can you please share your hazelcast version ?

**Comment by helmut-at-work** [comment] 2015-06-09 07:41
Testet with 3.4.2 and 3.5-EA

**Comment by eminn** [comment] 2015-06-09 07:43
The issue seems the duplicate of https://github.com/hazelcast/hazelcast/issues/5386 which must be solved by https://github.com/hazelcast/hazelcast/pull/5387 . The fix will be available with 3.5 and 3.4.3 releases. You can test it against snapshot versions

**Comment by helmut-at-work** [comment] 2015-06-09 07:52
Ok Thanks. Didn't found that issue. Snapshot works

**Comment by eminn** [comment] 2015-06-09 08:26
Glad that is worked, I'm closing the issue, thanks for reporting.

**Closed by eminn** 2015-06-09 08:26 UTC
Labels: PENDING, Team: Core
