### ISSUE TITLE
com.hazelcast.jet.sql_nightly.SqlSplitBrainTest.test_indexScan [HZ-1696]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22216] opened 2022-09-14 07:16 UTC
_master_ (commit e9e1f0dc32a4d896c003030fb9449a0bbd685bde)

Failed on IbmJDK8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/461/testReport/com.hazelcast.jet.sql_nightly/SqlSplitBrainTest/test_indexScan/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: some threads were stuck
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.jet.sql_nightly.SqlSplitBrainTest.test_indexScan(SqlSplitBrainTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

</details>

**Comment by olukas** [comment] 2022-12-05 09:54
Failed again on _5.2.z_ with IbmJDK8-nightly: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8-nightly/61/testReport/com.hazelcast.jet.sql_nightly/SqlSplitBrainTest/test_indexScan/

**Comment by k-jamroz** [comment] 2023-02-07 11:45
Artifacts for last build: [Hazelcast-5.maintenance-IbmJDK8-nightly-61.tar](https://s3.console.aws.amazon.com/s3/object/j-artifacts?region=us-east-1&prefix=Hazelcast-5.maintenance-IbmJDK8-nightly/61/Hazelcast-5.maintenance-IbmJDK8-nightly-61.tar)

**Comment by k-jamroz** [comment] 2023-02-07 16:37
I suspect that this may be a problem with surefire plugin. Test results are reported incorrectly. In the latter run:
* `SqlSplitBrainTest` is reported 2 times in `TEST-com.hazelcast.sql.impl.client.SqlResubmissionStreamTest.xml` and addtitionally in `TEST-com.hazelcast.jet.sql_nightly.SqlSplitBrainTest.xml`
* `SqlResubmissionStreamTest` reports some instances that were not shut down, but the code seems to be closing everything it creates correctly
```xml
  <testcase name="com.hazelcast.sql.impl.client.SqlResubmissionStreamTest" classname="com.hazelcast.sql.impl.client.SqlResubmissionStreamTest" time="0.001">
    <error message="Instances haven&apos;t been shut down: [HazelcastInstance{name=&apos;quizzical_jones&apos;, node=[127.0.0.1]:5701}, HazelcastInstance{name=&apos;sharp_jones&apos;, node=[127.0.0.1]:5702}]" type="java.lang.IllegalStateException">java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='quizzical_jones', node=[127.0.0.1]:5701}, HazelcastInstance{name='sharp_jones', node=[127.0.0.1]:5702}]
        at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:47)
        at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
        at java.util.concurrent.FutureTask.run(FutureTask.java:277)
        at java.lang.Thread.run(Thread.java:825)
```
* `AfterClassesStatement` terminates instances if it finds any running. There is error for `SqlSplitBrainTest` which may be caused by the prematurely terminated instances (could belong to execution of next test?). The test crashes in `@After` method because instances it created do not exist anymore.

```xml
<testcase name="test_indexScan" classname="com.hazelcast.jet.sql_nightly.SqlSplitBrainTest" time="0.001">
    <error message="HazelcastInstance[[127.0.0.1]:5702] is not active!" type="com.hazelcast.spi.exception.RetryableHazelcastException">com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[127.0.0.1]:5702] is not active!
        at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:441)
        at com.hazelcast.jet.core.JetTestSupport.shutdownJobsAndGetLeakedClassLoaders(JetTestSupport.java:139)
        at com.hazelcast.jet.core.JetTestSupport.shutdownFactory(JetTestSupport.java:106)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
        at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
        at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
        at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
        at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:40)
        at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
        at java.util.concurrent.FutureTask.run(FutureTask.java:277)
        at java.lang.Thread.run(Thread.java:825)
```

* it is hard to tell why there is antother `SqlSplitBrainTest` failure reported in `SqlResubmissionStreamTest.xml`. But time reported is clearly wrong. `some threads were stuck` cannot happen after 0.001s.

```xml
  <testcase name="test_indexScan" classname="com.hazelcast.jet.sql_nightly.SqlSplitBrainTest" time="0.001">
    <failure message="some threads were stuck" type="java.lang.AssertionError">java.lang.AssertionError: some threads were stuck
```

* the only execution reported in correct file hung during shutdown in `@After` method. Probably there was permanent error when closing jobs (maybe instance unreachable or terminated):

```xml
  <testcase name="com.hazelcast.jet.sql_nightly.SqlSplitBrainTest" classname="com.hazelcast.jet.sql_nightly.SqlSplitBrainTest" time="900.01">
    <error message="test timed out after 900 seconds" type="org.junit.runners.model.TestTimedOutException">org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1718)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3345)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1753)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1958)
        at com.hazelcast.jet.Job.join(Job.java:78)
        at com.hazelcast.jet.core.JetTestSupport.ditchJob0(JetTestSupport.java:452)
        at com.hazelcast.jet.core.JetTestSupport.ditchJob(JetTestSupport.java:408)
        at com.hazelcast.jet.core.JetTestSupport.shutdownJobsAndGetLeakedClassLoaders(JetTestSupport.java:134)
        at com.hazelcast.jet.core.JetTestSupport.shutdownFactory(JetTestSupport.java:106)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
        at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
        at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
        at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
        at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:40)
        at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
        at java.util.concurrent.FutureTask.run(FutureTask.java:277)
        at java.lang.Thread.run(Thread.java:825)
```

**Comment by k-jamroz** [comment] 2023-02-07 19:42
There are 2 timeouts:
* `AbstractHazelcastClassRunner.DEFAULT_TEST_TIMEOUT_IN_SECONDS`- 300s, applies only to test method
* `JetTestSupport.globalTimeout` - 900s, applies to entire execution, including `@After`, `@Before` etc.

I managed to get similar exceptions (likely this is `MultipleFailureException` - maybe it is not supported correctly by surefire?) when the test hangs due to problems with the cluster in `@After` method (`shutdownFactory`) after failing. 

Both timeouts interrupt main test thread which can cause strange consequences. Also the test method runs in different thread than `@After`. Race condition is possible between them if test method does something non-trival after InterruptedException.

**Comment by k-jamroz** [comment] 2023-02-08 10:05
`CompletableFuture.join()` is not interruptible, it ignores `Thread.interrupt()`, unlike `CompletableFuture.get()`. We use it in some places, like `Job.join()`. If we hit one of the test timeouts (both interrupt a thread) a few things can happen:
* test thread will not finish immediately but will continue to be running, doing for example some cleanup concurrently with next test
* test thread will hang without doing proper cleanup at all which can impact subsequent tests

Both timeouts (out own and from JUnit) do not wait for the completion of the test thread.

**Comment by k-jamroz** [comment] 2023-02-08 10:42
Additional observation: `ThreadDumpAwareRunAfters.evaluate()` swallows `InterruptedException` for `@After` methods, adds it only to errors list.

Maybe something like that happened:
1. SqlSplitBrainTest hung during split brain healing
2. first timeout (300s) interrupted waiting in split brain method (maybe in `waitAllForSafeState`) for healing
3. split brain was not healed so threads were struck
4. `@After` method hung and was interrupted by second timeout (900s)

Or:
1. threads in SqlSplitBrainTest really were struck, maybe something was not ok after split brain healed
2. @After` method hung and was interrupted by second timeout (900s) because there were hanging jobs

**Comment by olukas** [comment] 2023-05-26 06:12
Failed again on _master_ with openj9-11 (FIPS mode): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11-fips-nightly/544/testReport/com.hazelcast.jet.sql_nightly/SqlSplitBrainTest/test_indexScan/

**Comment by olukas** [comment] 2023-05-29 08:27
Failed again on _master_ with zing-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK11-nightly/33/testReport/com.hazelcast.jet.sql_nightly/SqlSplitBrainTest/test_indexScan/

**Comment by Patras3** [comment] 2023-06-05 10:49
Failed again on _master_ with zing-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK11-nightly/33/testReport/com.hazelcast.jet.sql_nightly/SqlSplitBrainTest/test_indexScan/

**Comment by Patras3** [comment] 2023-07-03 17:12
Failed again on _master_ with zing-11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11-nightly/39/testReport/com.hazelcast.jet.sql_nightly/SqlSplitBrainTest/test_indexScan/

**Comment by Patras3** [comment] 2023-08-01 09:49
Failed again on _5.0.z_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/12/testReport/com.hazelcast.jet.sql/SqlSplitBrainTest/

**Comment by sumnerib** [comment] 2023-08-21 12:58
Failed again on _master_ with zing-11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11-nightly/46/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSplitBrainTest/test_indexScan/

**Comment by Patras3** [comment] 2023-09-07 15:24
Failed again on _master_ with OpenJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK11-arm64-nightly/29/testReport/com.hazelcast.jet.sql_nightly/SqlSplitBrainTest/test_indexScan/

**Comment by Patras3** [comment] 2023-12-12 17:44
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/114/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSplitBrainTest/___/

**Comment by AyberkSorgun** [comment] 2024-03-25 07:45
Unable to reproduce, set as not doing

**Closed by AyberkSorgun** 2024-03-25 07:45 UTC
Labels: Type: Test-Failure, Source: Internal, Team: SQL, to-jira
