### ISSUE TITLE
ClientIndexStatsTest.testIndexStatsAfterMapDestroy

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#16252] opened 2019-12-13 12:02 UTC
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5043

```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.map.ClientIndexStatsTest.combineStats(ClientIndexStatsTest.java:142)
	at com.hazelcast.client.map.ClientIndexStatsTest.stats(ClientIndexStatsTest.java:119)
	at com.hazelcast.map.LocalIndexStatsTest.valueStats(LocalIndexStatsTest.java:657)
	at com.hazelcast.map.LocalIndexStatsTest.testIndexStatsAfterMapDestroy(LocalIndexStatsTest.java:602)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by devozerov** [comment] 2019-12-23 07:11
Closing as a duplicate to https://github.com/hazelcast/hazelcast-enterprise/issues/3445
Was fixed in https://github.com/hazelcast/hazelcast/pull/16296

**Comment by petrpleshachkov** [comment] 2019-12-23 08:31
The https://github.com/hazelcast/hazelcast/pull/16296 tries to fix https://github.com/hazelcast/hazelcast-enterprise/issues/3445 increasing the destroy timeout from 30 seconds to 60 seconds. However, we don't see huge hiccups running the test. This is why I doubt that 30 seconds timeout is a real reason for the test failure. 

```
Hiccups measured while running test 'testIndexStatsAfterMapDestroy[format:OBJECT](com.hazelcast.client.map.ClientIndexStatsTest):'
09:47:05, accumulated pauses: 589 ms, max pause: 61 ms, pauses over 1000 ms: 0
09:47:10, accumulated pauses: 1315 ms, max pause: 256 ms, pauses over 1000 ms: 0
09:47:15, accumulated pauses: 581 ms, max pause: 341 ms, pauses over 1000 ms: 0
```

**Comment by devozerov** [comment] 2019-12-23 08:37
Since this ticket is duplicate, I propose to continue the discussion in https://github.com/hazelcast/hazelcast/pull/16296

**Comment by devozerov** [comment] 2019-12-25 09:17
The first attempt to fix the problem was performed at https://github.com/hazelcast/hazelcast/pull/16296. But additional analysis has shown that the problem has nothing to do with proxy timeouts, so we may rollback that commit as unnecessary. 

In order to reliably reproduce the issue, you should induce a very high load on the system. That is, load all cores with high priority tasks. On my 8 core machine with 32Gb RAM I did it as follows:
`sudo nice -n -19 stress --cpu 8 --vm 8 --vm-bytes 3.5G --timeout 60`

The whole flow to reproduce:
1) Add `Repeat(100)` to the test and start it execution
2) When first iterations have completed, execute the command above
3) Observe the test failure with high probability. If it didn't fail, re-execute the stress command again.

Debugging shows that the issue is caused by numerous race conditions in our metrics infrastructure. The key problem is that we use the patter "putIfAbsent" in several places without checking that actual data structures exist. Examples:
`MapServiceContextImpl.getMapContainer`
`LocalMapStatsProvider.getLocalMapStatsImpl`

Exact flow:
1) An `IMap` is created and its metrics are registered
2) T1: The map is about to be destroyed, and it's metrics are cleared in `MapServiceContextImpl.destroyMap` *BEFORE* the container is destroyed.
3) T2: Concurrent background thread, e.g. `MetricsService.collectMetrics` calls to `LocalMapStatsProvider.getLocalMapStatsImpl` and re-registers metrics again with index, since the container is not destroyed yet.
4) T1: Destroys the container

As a result, outdated metrics, as well as a non-existing container, are stuck in the member forever.

**Comment by sumnerib** [comment] 2023-10-09 15:18
Reopening as issue occurred again on: _master_ (commit 0b787f893fc4fb58956c5b0a741ebfe65098a149)
with redhat-17: https://jenkins.hazelcast.com/job/Hazelcast-EE-master-RedHatJDK17/87/testReport/junit/com.hazelcast.map/HDLocalIndexStatsTest/testIndexStatsAfterMapDestroy/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<1> but was:<0>
	at com.hazelcast.map.LocalIndexStatsTest.testIndexStatsAfterMapDestroy(LocalIndexStatsTest.java:673)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testUpdateTracking[format:NATIVE globalIndex:true] in 1.158 seconds.
23:03:17,138  INFO |testIndexStatsAfterMapDestroy[format:NATIVE globalIndex:true]| - [HazelcastTestSupport] Thread-4631 - Shutting down node factory as @After action
23:03:17,139  INFO |testIndexStatsAfterMapDestroy[format:NATIVE globalIndex:true]| - [LifecycleService] Thread-4631 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
23:03:17,139  WARN |testIndexStatsAfterMapDestroy[format:NATIVE globalIndex:true]| - [Node] Thread-4631 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Terminating forcefully...
23:03:17,139  INFO |testIndexStatsAfterMapDestroy[format:NATIVE globalIndex:true]| - [Node] Thread-4631 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
23:03:17,139  INFO |testIndexStatsAfterMapDestroy[format:NATIVE globalIndex:true]| - [Node] Thread-4631 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
Started Running Test: testMemoryCostTracking[format:NATIVE globalIndex:true]
23:03:17,149  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [MetricsConfigHelper] Thread-4644 - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
23:03:17,150  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [logo] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
23:03:17,150  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [system] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
23:03:17,150  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [system] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Enterprise 5.4.0-SNAPSHOT (20231008 - 0b787f8, 1443956) starting at [127.0.0.1]:5701
23:03:17,150  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [system] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
23:03:17,150  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [system] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
23:03:17,150  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [system] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
23:03:17,150  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [NodeExtension] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Checking Hazelcast Enterprise license...
23:03:17,150  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [NodeExtension] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] License{allowedNumberOfNodes=9999, expiryDate=Dec/30/2099 23:59:59, featureList=[ Management Center, Streaming Management Center, Clustered JMX, Clustered REST, Security, WAN Replication, High Density Memory, Persistence, Streaming Lossless Cluster Restart, Rolling Upgrade, Streaming Job Upgrades, Cluster Client Filtering, CP Subsystem Persistence, Dynamic Configuration, Tiered Storage ], type=null, companyName=null, ownerEmail=null, keyHash=f/LQGMjwh3TUaWM6uhcc56Ev0KHfZWbxlrtm0G+GvIw=, No Version Restriction}
23:03:17,150  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [NodeExtension] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Creating POOLED native memory manager with 256 MB size
23:03:17,153  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [MetricsConfigHelper] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
23:03:17,153  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [TpcServerBootstrap] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
23:03:17,154  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [WanThrottlingAcknowledger] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Using throttling WAN acknowledgement strategy with pending invocation threshold 50000
23:03:17,156  WARN |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [CPSubsystem] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
23:03:17,160  INFO |testIndexStatsAfterMapDestroy[format:NATIVE globalIndex:true]| - [NodeExtension] Thread-4631 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
23:03:17,160  INFO |testMemoryCostTracking[format:NATIVE globalIndex:true]| - [EnterpriseJetServiceBackend] Thread-4644 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
23:03:17,160  INFO |testIndexStatsAfterMapDestroy[format:NATIVE globalIndex:true]| - [Node] Thread-4631 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 21 ms.
23:03:17,160  INFO |testIndexStatsAfterMapDestroy[format:NATIVE globalIndex:true]| - [LifecycleService] Thread-4631 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testIndexStatsAfterMapDestroy[format:NATIVE globalIndex:true](com.hazelcast.map.HDLocalIndexStatsTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20231008', buildNumber=20231008, revision=0b787f8, enterprise=true, serializationVersion=1, upstream=BuildInfo{version='5.4.0-SNAPSHOT', build='20231005', buildNumber=20231005, revision=1443956, enterprise=false, serializationVersion=1}}
Hiccups measured while running test 'testIndexStatsAfterMapDestroy[format:NATIVE globalIndex:true](com.hazelcast.map.HDLocalIndexStatsTest):'
23:03:15, accumulated pauses: 1062 ms, max pause: 1049 ms, pauses over 1000 ms: 1


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-EE-master-RedHatJDK17/87/

**Comment by olukas** [comment] 2024-05-02 06:53
Failed again on _5.4.z_ with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/389/testReport/com.hazelcast.client.map/ClientIndexStatsTest/shouldUseIndexFromClient_whenClusterRestartedInFrozenState_format_OBJECT_/

**Comment by olukas** [comment] 2024-08-02 11:28
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.

**Closed by olukas** 2024-08-02 11:28 UTC
Labels: Team: Core, Type: Test-Failure, Source: Internal, Module: Query
