### ISSUE TITLE
MapStore write behind stores OOME,  if MapStore implementation throws exception, with low prob

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11389] opened 2017-09-18 12:00 UTC
I have a test run that results in a OOME hprof,  using 'exceptionProb=0.01'
https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x3/12/console

the GC shows a leak pattern http://54.82.84.143/~jenkins/workspace/stable-x3/3.9-SNAPSHOT/2017_09_18-07_35_38/map-store/gc.html

http://54.82.84.143/~jenkins/workspace/stable-x3/3.9-SNAPSHOT/2017_09_18-07_35_38/map-store/output/HZ/HzClient3HZ/exception.txt

zipped hprof http://54.82.84.143/~jenkins/workspace/stable-x3/3.9-SNAPSHOT/2017_09_18-07_35_38/map-store/output/HZ/HzMember2HZ/

I have MapStore enabled for the above failing test,
If i disable mapStore for the above test, it passes

the config for the map store is http://54.82.84.143/~jenkins/workspace/stable-x3/3.9-SNAPSHOT/2017_09_18-07_35_38/map-store/config-hz/hazelcast.xml  with the name `mapBak1HDStore*` and `mapBak1HDStoreThrough*`

both `mapBak1HDStore*` and `mapBak1HDStoreThrough*` use <class-name>hzcmd.map.store.PersonMapStore</class-name>

looks like the write behind stores are holding up to 882MB of heap
for the `mapBak1HDStore-store`

I see that if we do not throw any exceptions for the MapStore imple,  we do not get this issue.
exceptionProb=0.0
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/store/PersonMapStore.java#L18

**Comment by mmedenjak** [comment] 2017-09-18 12:29
I analysed the heap dump, seems like the `WriteBehindStore#writeBehindQueue` and `WriteBehindStore#stagingArea` took up most space. One particular queue had 16k elements. 
I'm suspecting the cause of the OOME is the unbounded queue size of the WB queue. The node doesn't crash if the store implementation doesn't throw exceptions. This could mean that there is either a leak in the exception handling logic or that the exception just adds additional pressure on the map store because of retries.

**Comment by mmedenjak** [comment] 2017-09-18 12:53
Also, the map store implementation `store` throws an exception with a probability of 0.01 on each invocation. Given that it is called 1000 times per write behind batch, it is possible that it throws an exception on each batch. Since the batch retry is "heavy" - it deserializes 1000 keys and waits for 1 second before retrying, this could cause the WB queue to grow out of control.

**Comment by Danny-Hazelcast** [comment] 2017-09-19 06:02
using the settings

```
<write-delay-seconds>1</write-delay-seconds>
<write-batch-size>10</write-batch-size>
<write-coalescing>true</write-coalescing>
<property name="exceptionProb">0.001</property>
```

we did not get an OOME in 1 hour,  but GC very bad from members

![image](https://user-images.githubusercontent.com/5988678/30577795-411fceba-9d30-11e7-8e64-c803b8f81b57.png)

**Comment by ahmetmircik** [comment] 2017-09-25 08:12
@Danny-Hazelcast Currently, if there is an exception from map-store during write-behind processing of an item, that failed item is retried indefinitely. This grows write-behind queue. We already have an [issue](https://github.com/hazelcast/hazelcast/issues/9265) related to this.  

As a workaround you can catch exception in map-store implementation and can control/prevent retries with your own implementation for now.

**Comment by mmedenjak** [comment] 2017-10-03 07:57
I am moving this to 3.9.1 as it is a known issue that might be addressed later

**Comment by mmedenjak** [comment] 2018-01-04 12:44
Closing this as it is a known issue and we have an enhancement issue already opened.

**Closed by mmedenjak** 2018-01-04 12:44 UTC
Labels: Team: Core, Type: Critical, Type: Defect
