### ISSUE TITLE
[TEST-FAILURE] ClientCacheEventJournalBasicTest>AbstractEventJournalBasicTest.allowReadingWithFutureSeq

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#16964] opened 2020-05-07 08:54 UTC
Failed here: https://github.com/hazelcast/hazelcast/pull/16961#issuecomment-625114772

The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/572/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/572/Hazelcast-pr-builder-572.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientCacheEventJournalBasicTest>AbstractEventJournalBasicTest.allowReadingWithFutureSeq:512->HazelcastTestSupport.assertOpenEventually:1108->HazelcastTestSupport.assertOpenEventually:1123 CountDownLatch failed to complete within 30 seconds, count left: 1
[INFO] 
[ERROR] Tests run: 27737, Failures: 1, Errors: 0, Skipped: 1001
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by vbekiaris** [comment] 2020-06-05 17:22
This test failure is due to reordering of operations. In failed test executions:
- the client sends out the read event journal & cache put tasks before it receives the partition table. So each task is sent over a random connection (instead of using the partition table to identify the partition owner and send both over the same connection).
- cache put is received first on the partition owner
- read event journal task follows, its `shouldWait()` returns `true` and waits to be notified until test times out

Changing the client config to disable smart routing fixes the test.

**Comment by vbekiaris** [comment] 2020-06-15 16:40
The root cause of the test failures is the delay in sending partition table to clients introduced in #16939 . The corresponding `ClientMapEventJournalBasicTest` is also failing sometimes due to the same issue.

Removing the delay from the first partition table delivery fixes the test failures (as in https://github.com/vbekiaris/hazelcast/commit/12481624fc095e63c1558faa8ccf5aec984ea926) _does not fail the tests_.

However I am not sure we should merge this change because it just makes the issue less likely to appear in the specific tests (probably as likely as before #16939 was merged). A fix should actually introduce a "partition table is received" happens-before "any smart client invocation" and probably we don't want to enforce such a rigid prerequisite. So I am leaning towards changing the test code to ensure that the client has received a partition table before sending the invocations. Alternatively, we could switch the test to a unisocket client which should have the same ordering effect (given that with mock network no member failures should be observed). wdyt @sancar @mdogan ?

**Comment by mdogan** [comment] 2020-06-16 07:19
Afaik, client may have a stale partition table (or even may not have any partition table) at any time. And it's able to sent partition specific requests even with a stale or missing partition table. 

So to me, a test should not assume and rely on this. Or the test should ensure that the client has the most recent partition table, as you said.

**Comment by sancar** [comment] 2020-06-16 10:28
@vbekiaris Not delaying the initial partition push make sense but not enough. The test can still fail in an unlucky timing. Instead of verifying partition table on the client side via accessing the internal API, I think we can change the test to see if event journal works eventually. We will not do a single put but continuous puts until event journal picks up one of them.

**Closed** 2020-06-23 07:29 UTC
Labels: Module: IMap, Source: Internal, Team: Client, Team: Core, Type: Defect, Type: Test-Failure
