### ISSUE TITLE
NullpointerException in hibernate integration in LOCAL mode

### ISSUE THREAD

**Issue by george-007** [hazelcast/hazelcast#4456] opened 2015-01-20 14:58 UTC
NullpointerException on second node when updating an entity. Hibernate (3.6.5)  with Hazelcast (3.4) as the 2nd level cache provider - LOCAL mode.

```code
14:52:37.982 [hz._hzInstance_1_czcdev.event-3] WARN  com.hazelcast.spi.EventService (Slf4jFactory.java:90) - [192.168.10.99]:5701 [czcdev] [3.4] Error while logging processing event
com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.IOException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.NullPointerException
    at com.hazelcast.nio.serialization.SerializationServiceImpl.handleException(SerializationServiceImpl.java:419) ~[SerializationServiceImpl.class:3.4]
	at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:315) ~[SerializationServiceImpl.class:3.4]
	at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:439) ~[ByteArrayObjectDataInput.class:3.4]
	at com.hazelcast.hibernate.local.Invalidation.readData(Invalidation.java:56) ~[Invalidation.class:3.4]
	at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:111) ~[DataSerializer.class:3.4]
	at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39) ~[DataSerializer.class:3.4]
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.toObject(StreamSerializerAdapter.java:65) ~[StreamSerializerAdapter.class:3.4]
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:260) ~[SerializationServiceImpl.class:3.4]
	at com.hazelcast.topic.impl.DataAwareMessage.getMessageObject(DataAwareMessage.java:44) ~[DataAwareMessage.class:3.4]
	at com.hazelcast.hibernate.local.LocalRegionCache$3.onMessage(LocalRegionCache.java:152) ~[LocalRegionCache$3.class:3.4]
	at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:136) ~[TopicService.class:3.4]
	at com.hazelcast.spi.impl.EventServiceImpl$EventPacketProcessor.process(EventServiceImpl.java:549) ~[EventServiceImpl$EventPacketProcessor.class:3.4]
	at com.hazelcast.spi.impl.EventServiceImpl$RemoteEventPacketProcessor.run(EventServiceImpl.java:630) ~[EventServiceImpl$RemoteEventPacketProcessor.class:3.4]
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:190) [StripedExecutor$Worker.class:3.4]
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:174) [StripedExecutor$Worker.class:3.4]
Caused by: java.io.IOException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.NullPointerException
	at com.hazelcast.hibernate.serialization.Hibernate3CacheKeySerializer.read(Hibernate3CacheKeySerializer.java:116) ~[Hibernate3CacheKeySerializer.class:3.4]
	at com.hazelcast.hibernate.serialization.Hibernate3CacheKeySerializer.read(Hibernate3CacheKeySerializer.java:35) ~[Hibernate3CacheKeySerializer.class:3.4]
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44) ~[StreamSerializerAdapter.class:3.4]
	at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:309) ~[SerializationServiceImpl.class:3.4]
	... 13 common frames omitted
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.NullPointerException
	at com.hazelcast.nio.serialization.SerializationServiceImpl.handleException(SerializationServiceImpl.java:419) ~[SerializationServiceImpl.class:3.4]
	at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:315) ~[SerializationServiceImpl.class:3.4]
	at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:439) ~[ByteArrayObjectDataInput.class:3.4]
	at com.hazelcast.hibernate.serialization.Hibernate3CacheKeySerializer.read(Hibernate3CacheKeySerializer.java:99) ~[Hibernate3CacheKeySerializer.class:3.4]
	... 16 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333) ~[na:1.7.0_67]
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988) ~[na:1.7.0_67]
	at org.hibernate.impl.SessionFactoryObjectFactory.getNamedInstance(SessionFactoryObjectFactory.java:159) ~[SessionFactoryObjectFactory.class:3.6.5.Final]
	at org.hibernate.impl.SessionFactoryImpl.readResolve(SessionFactoryImpl.java:753) ~[SessionFactoryImpl.class:3.6.5.Final]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1104) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1807) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_67]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_67]
	at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:196) ~[DefaultSerializers$ObjectSerializer.class:3.4]
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44) ~[StreamSerializerAdapter.class:3.4]
	at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:309) ~[SerializationServiceImpl.class:3.4]
	... 18 common frames omitted
```

The exception is thrown in the following code from SessionFactoryImpl in Hibernate 3.6: 

```code
    private Object readResolve() throws ObjectStreamException {
		log.trace("Resolving serialized SessionFactory");
		// look for the instance by uuid
		Object result = SessionFactoryObjectFactory.getInstance(uuid);
		if (result==null) {
			// in case we were deserialized in a different JVM, look for an instance with the same name
			// (alternatively we could do an actual JNDI lookup here....)
            
            result = SessionFactoryObjectFactory.getNamedInstance(name); 
            
			if (result==null) {
				throw new InvalidObjectException("Could not find a SessionFactory named: " + name);
			}
			else {
				log.debug("resolved SessionFactory by name");
			}
		}
		else {
			log.debug("resolved SessionFactory by uid");
		}
		return result;
	}
```

First ```SessionFactoryObjectFactory.getInstance(uuid);``` returns ```null```, then ```SessionFactoryObjectFactory.getNamedInstance(name);``` for ```null``` name throws ```NullPointerException```.

Configuration
--------------
hibernate.cfg.xml
```code
   <property name="hibernate.cache.use_second_level_cache">true</property>
   <property name="hibernate.cache.use_query_cache">true</property>
```

Spring
```code
   <hz:hazelcast id="instance">
        <hz:config>
            <hz:group name="dev" password="dev" />

            <hz:properties>
                <hz:property name="hazelcast.jmx">true</hz:property>
                <hz:property name="hazelcast.logging.type">slf4j</hz:property>           
            </hz:properties>
            <hz:network port="5701" port-auto-increment="true">
                <hz:join>
                    <hz:multicast enabled="true" />
                </hz:join>
            </hz:network>
        </hz:config>
    </hz:hazelcast>

    <hz:hibernate-region-factory id="regionFactory" instance-ref="instance" mode="LOCAL" />

    <bean id="sessionFactory"
        class="org.springframework.orm.hibernate3.LocalSessionFactoryBean">
        <property name="dataSource" ref="mainDataSource" />
        <property name="cacheRegionFactory" ref="regionFactory" />
        <property name="configLocation" value="classpath:hibernate.cfg.xml" />
        <property name="configurationClass" value="org.hibernate.cfg.AnnotationConfiguration" />
        <property name="namingStrategy">
            <bean class="org.hibernate.cfg.ImprovedNamingStrategy" />
        </property>
        <property name="hibernateProperties" ref="hibernateProperties" />        
    </bean>

```

**Comment by george-007** [comment] 2015-01-20 14:59
This issue is similar to https://groups.google.com/forum/#!topic/hazelcast/8ra4B3VepI8

**Comment by cmuramoto** [comment] 2015-01-26 23:19
I believe I had this issue once.

I added:

<prop key="hibernate.session_factory_name">F</prop>

to Spring config and voila!

There's another detail: If you are using serialization mode OBJECT instead of BINARY, you might get exceptions when a node is joining because partitions will start to migrate and deserialization starts to happen before your session factory will not be initialized yet.

**Comment by kobalski** [comment] 2015-07-15 08:56
I think it is not hazelcast issue too, same exception can be seen EhCache 2nd Level Cache impl too when used in distributed mode with RMI replication. As @cmuramoto  explains solution to the problem is to give a session factory name in hibernate config. (http://forums.terracotta.org/forums/posts/list/7881.page) I am closing this issue for now, please feel free to reopen the issue, if provided work around does not work.

**Closed by kobalski** 2015-07-15 08:56 UTC
Labels: Team: Integration, Type: Defect

**Comment by Serdaro** [comment] 2015-08-03 08:46
@kobalski , Does this have any documentation impact?

**Comment by kobalski** [comment] 2015-08-03 12:06
@Serdaro I created a PR for this issue. I listed necessary config under optional settings part. https://github.com/hazelcast/hazelcast-reference-manual/pull/23

**Comment by Serdaro** [comment] 2015-08-04 07:54
Great, thank you.
