### ISSUE TITLE
OperationService asyncInvokeOnPartition sometimes fails

### ISSUE THREAD

**Issue by ajermakovics** [hazelcast/hazelcast#5069] opened 2015-04-15 11:30 UTC
Some of the async invocations fail when running this test

```java
    static CountDownLatch latch = new CountDownLatch(270);

    @Test
    public void testAsyncInvocation_DifferentPartition() throws Exception {
        TestHazelcastInstanceFactory nodes = createHazelcastInstanceFactory(2);
        HazelcastInstance hz[] = nodes.newInstances();

        Node node = getNode(hz[0]);
        NodeEngineImpl nodeEngine = node.nodeEngine;
        InternalOperationService opService = nodeEngine.getOperationService();

        Operation op = new MyOp();
        opService.invokeOnPartition(SERVICE_NAME, op, 1).get();

        assertTrue("No responses from: " + latch.getCount(), latch.await(1L, TimeUnit.SECONDS) );
    }

    static class MyOp extends AbstractMapOperation implements PartitionAwareOperation, ExecutionCallback {

        public MyOp() {
            super("map");
        }

        @Override
        public void run() throws Exception {
            NodeEngine ne = mapService.getMapServiceContext().getNodeEngine();
            InternalOperationService opService = (InternalOperationService) ne.getOperationService();

            for(int i = 0; i < 271; i++) {
                PartitionCheckIfLoadedOperation op = new PartitionCheckIfLoadedOperation("map");
                if (i != getPartitionId())
                    opService.asyncInvokeOnPartition(SERVICE_NAME, op, i, this);
            }
        }

        @Override
        public void onResponse(Object response) {
            latch.countDown();
        }

        @Override
        public void onFailure(Throwable t) {
            t.printStackTrace();
        }

    }
```

**Comment by pveentjer** [comment] 2015-04-15 12:30
Can you slap a repeat around it and see how many runs you need to get it to fail?

**Comment by pveentjer** [comment] 2015-04-15 12:31
Ahh... I think I know the cause.. perhaps sometimes the call is remote.. sometimes local :)

**Comment by ajermakovics** [comment] 2015-04-15 13:22
fails for me on each run. afaik it should work for both remote and local, or?

**Comment by pveentjer** [comment] 2015-04-15 16:14
He Andrejs. 

You can't use invocations in combination with responsehandlers because the responsehandler you set, is not used. 

For local invocations, the invocation itself is the response handler.

For remote invocation, on the remote side a special kind of response handler is set that sends the result back to the caller.

You can only use the response handler if you use e.g. operationservice.executeOperation. Call me on slack for more info.

**Comment by ajermakovics** [comment] 2015-04-15 16:34
Wasn't planning on using a response handler here. Perhaps thats a different issue

**Comment by pveentjer** [comment] 2015-04-15 18:01
Why are you using ExecutionCallback?

**Comment by ajermakovics** [comment] 2015-04-15 18:25
How do you mean? It's required in asyncInvokeOnPartition

**Comment by gurbuzali** [comment] 2015-04-16 11:57
Hi @ajermakovics the fixer PR was not yet merged, that's why it was not working properly I guess.
I've just merged it https://github.com/hazelcast/hazelcast/pull/4997

**Comment by gurbuzali** [comment] 2015-05-13 08:04
Hi @ajermakovics can you verify if the issue still valid ?

**Comment by gurbuzali** [comment] 2015-05-13 12:21
I've tried the test, it is passing

**Closed by gurbuzali** 2015-05-13 12:21 UTC
Labels: Team: Core, Type: Defect
