### ISSUE TITLE
RepartitioningStressTest.callWithBackups

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#3066] opened 2014-07-24 06:09 UTC
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/248/testReport/junit/com.hazelcast.spi/RepartitioningStressTest/callWithBackups/

```
java.lang.AssertionError: value not the same expected:<5889> but was:<5891>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at com.hazelcast.spi.RepartitioningStressTest.callWithBackups(RepartitioningStressTest.java:127)
```

**Comment by Holmistr** [comment] 2018-02-08 19:04
@mdogan Can we close this? It's a very old issue. I looked at the test, it's ignored. I tried to run it on my local and also in Docker with image from the PR builder and the test seems to pass.

**Comment by mdogan** [comment] 2018-02-09 08:43
@Holmistr: Afaik, this was failing occasionally. We did many fixes regarding graceful shutdown, it may not fail anymore. Best to remove the `@Ignored` and see.

**Comment by Holmistr** [comment] 2018-02-12 10:38
Ok, I have re-enabled the test in the PR and we'll see if the issue is fixed or not.

**Comment by Holmistr** [comment] 2018-02-13 07:48
I re-enabled the test with https://github.com/hazelcast/hazelcast/pull/12318 , it's possible that the issue is already fixed. Closing for now, we'll reopen it if the test failure occurs again.

**Closed by Holmistr** 2018-02-13 07:48 UTC
Labels: DR3, Team: Core, Type: Test-Failure
