### ISSUE TITLE
All Topic messages are processed by a single thread

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#7443] opened 2016-02-01 21:46 UTC
I have a single HZ 3.5.4 server. There is a Topic. Both publisher and subscriber are within the server and they're singletons. The rate of messages published to the topic is quite high, it is > 1000 per sec. But all of them are consumed by only one HZ event thread, as I see in my logs. My EventService pool size is default = 5. So it is not clear why only one thread handles all the load. Look like you assign thread per subscriber? Is it possible to improve the situation somehow?

Thanks, Denis.

**Comment by jerrinot** [comment] 2016-02-02 09:11
Hi @dsukhoroslov,

the same topic use the same thread. I agree this could be relaxed when ordering is not important. The workaround would be to either use multiple topics or offload message processing to another thread.

**Comment by dsukhoroslov** [comment] 2016-02-02 09:56
Hi @jerrinot, 

I like this new label :). Ok, I'll think about it. Besides ordering do you have any other concens using the full EventService thread pool for message processing?

**Comment by jerrinot** [comment] 2016-02-02 10:03
I am glad you like the label! ;-)

as far as I know ordering is the only reason for this. 

[This could be a good starting point](https://github.com/jerrinot/hazelcast/blob/46d5aa590f0598b7fa226f448b99bc8c2ca4f330/hazelcast/src/main/java/com/hazelcast/topic/impl/TopicService.java#L148-L148)  See the last argument - `name.hashCode())` 
Also please try to read the [documentation on this](http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#topic first). It's quite interesting. I didn't know about the `globalOrderEnabled` flag.

**Comment by dsukhoroslov** [comment] 2016-02-02 16:29
@jerrinot, I looked at the code around TopicService and EventService. The improvement looks pretty clear:

<code>
add Registration.isOrdered() property, set it at construntion from nodeEngine.getHzInstance().getConfig().getTopicConfig(topic).isGlobalOrderingEnabled();

make two new classes which are not StrippedRunable, move most of LocalEventDispatcher/EventPacketPubliser fields to them (except orderKey);
inherit LocalEventDispatcher/EventPacketPubliser from these two classes, leave StrippedRunable implementation only;

in eventService.executeLocal construct LocalEventDisparcher or its non-StrinnedRunable parent depending on the reg.isOrdered() flag;

do the same for remote events with EventPacketPublisher/it's parent class;
</code>

the question is: do you want this behaviour be configurable or not? It is possible to add a new config property to topic (single-threaded true/false?) and use it as a flag instead of isOrdered(); with default value: true to leave current single-threaded behaviour as it is.

**Comment by dsukhoroslov** [comment] 2016-02-03 10:43
@jerrinot, if you agree with this implementation plan I'll do PR. I can add the new configuration element too. This will imply changes in HZ/HZ-Spring XSDs. Which HZ version should I fork, 3.7-SHAPSHOT?

**Comment by jerrinot** [comment] 2016-02-03 12:15
Hi @dsukhoroslov,

looks good to me! Please make it's configurable with single-threaded default  (=the current behaviour).

Base it on 3.7-SNAPSHOT I would prefer not to backport it to avoid possible regressions in patch releases. 

Many thanks for your effort & idea!

**Comment by noctarius** [comment] 2016-02-03 13:07
I guess ordered=true and multi-threaded is mutually exclusive, anyhow there might be people that still want single-threaded behavior but just don't care for the order, what do you think?

**Comment by dsukhoroslov** [comment] 2016-02-03 13:18
I agree. And yes, they'll get it with single-threaded=true, ordered = false config.

**Comment by vertex-github** [comment] 2016-02-03 13:36
@noctarius Changing ordered processing to multi-threaded could break existing code (since everyone is expecting single thread behavior - or at least relying on that behavior even if they dont realize).

**Comment by dsukhoroslov** [comment] 2016-02-03 14:59
TopicConfig hashCode/equals methods implementation is confusing:
<code>

    public int hashCode() {
        return (globalOrderingEnabled ? 1231 : 1237)
                + 31 * (name != null ? name.hashCode() : 0);
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof TopicConfig)) {
            return false;
        }
        TopicConfig other = (TopicConfig) obj;
        return
                (this.name != null ? this.name.equals(other.name) : other.name == null)
                        && this.globalOrderingEnabled == other.globalOrderingEnabled;
    }
</code>

Shouldn't it take into account the Topic name only? I don't beleive you want to have several topics with the same name but different ordering config. TopicService does not expect this, afaik.

**Comment by gurbuzali** [comment] 2016-02-03 15:55
Hi @dsukhoroslov you are right about your findings but since we hold the topicConfigs as name/TopicConfig map in `Config`, it is not likely that this causes any problem. it should be fixed nevertheless

**Comment by dsukhoroslov** [comment] 2016-02-03 16:04
Ok, I'll fix it as part of this PR.

**Comment by dsukhoroslov** [comment] 2016-02-05 15:04
Done. Please see PR #7472

**Comment by dsukhoroslov** [comment] 2016-02-18 12:50
The new PR for this issue: #7546

**Comment by jerrinot** [comment] 2016-04-20 14:39
fixed by #7546

**Closed by jerrinot** 2016-04-20 14:39 UTC
Labels: Contribution-Welcome, Team: Core, Type: Enhancement
