### ISSUE TITLE
[TEST-FAILURE] Spinning_TcpIpConnection_BasicTest.lastReadTimeMillis

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6233] opened 2015-09-17 08:06 UTC
```
java.lang.AssertionError: nowMs = 1442463721002 lastReadTimeMs:1442463719998
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.nio.tcp.TcpIpConnection_BasicTest.lastReadTimeMillis(TcpIpConnection_BasicTest.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/242/testReport/junit/com.hazelcast.nio.tcp.spinning/Spinning_TcpIpConnection_BasicTest/lastReadTimeMillis/

**Comment by hasancelik** [comment] 2015-09-17 08:09
**spinning.Spinning_TcpIpConnection_BasicTest** timeout problem:

```
05:58:20 Running com.hazelcast.nio.tcp.spinning.Spinning_TcpIpConnection_BasicTest
08:23:32 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/681/console

**Comment by mdogan** [comment] 2015-09-22 06:57
A similar failure on my local build:

```
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 59.898 sec <<< FAILURE! - in com.hazelcast.nio.tcp.spinning.Spinning_TcpIpConnection_BasicTest
lastReadTimeMillis(com.hazelcast.nio.tcp.spinning.Spinning_TcpIpConnection_BasicTest)  Time elapsed: 11.933 sec  <<< FAILURE!
java.lang.AssertionError: nowMs = 1442850653871 lastReadTimeMs:1442850651488
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.nio.tcp.TcpIpConnection_BasicTest.lastReadTimeMillis(TcpIpConnection_BasicTest.java:155)
```

There's a comment on `marginOfErrorMs` variable:

```java
// make sure that the lastWrite time is within the given marginOfErrorMs.
// if we make this marginOfError very small, there is a high chance of spurious failures
int marginOfErrorMs = 1000;
```
It seems test is still failing spuriously.

**Comment by hasancelik** [comment] 2015-09-28 09:58
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/715/testReport/junit/com.hazelcast.nio.tcp.nonblocking/SelectNow_TcpIpConnection_BasicTest/lastReadTimeMillis/

**Comment by hasancelik** [comment] 2015-10-19 11:38
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/727/testReport/junit/com.hazelcast.nio.tcp.spinning/Spinning_TcpIpConnection_BasicTest/lastReadTimeMillis/

**Comment by hasancelik** [comment] 2015-10-23 07:07
```
03:54:03 Running com.hazelcast.nio.tcp.spinning.Spinning_TcpIpConnection_BasicTest
06:26:58 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/719/console


```
java.lang.AssertionError: nowMs = 1445563466642 lastReadTimeMs:1445563465641
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.nio.tcp.TcpIpConnection_BasicTest.lastReadTimeMillis(TcpIpConnection_BasicTest.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/6/testReport/junit/com.hazelcast.nio.tcp.nonblocking/SelectNow_TcpIpConnection_BasicTest/lastReadTimeMillis/

**Comment by Donnerbart** [comment] 2015-11-10 12:41
Duplicate of https://github.com/hazelcast/hazelcast/issues/6154

Since this test seems to fail more often than expected I increased the allowed margin of error to 3 seconds (was 1 second before). The largest difference I saw in all logs was about 2.5 seconds, so we should be quite safe with this change. I aligned the sleep time of the write and read test to 5 seconds, so we should nevertheless get a valid test result.

https://github.com/hazelcast/hazelcast/commit/dd8c45abcaff36085e5214a58bf15f508bb39588

**Comment by hasancelik** [comment] 2015-12-03 10:43
```
03:50:39 Running com.hazelcast.nio.tcp.spinning.Spinning_TcpIpConnection_BasicTest
06:26:57 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/766/console

**Comment by mesutcelik** [comment] 2015-12-17 15:10
I don't see any failure on our master build since the fixes above.
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/4194/testReport/com.hazelcast.nio.tcp.spinning/Spinning_TcpIpConnection_BasicTest/lastReadTimeMillis/history/

 @hasancelik ,
Can we check if the other builds at the same time frame timeout as well?
I remember there was a page where all builds are listed sorted by time.

**Comment by mesutcelik** [comment] 2015-12-21 12:44
I think there is no enough log to see what has been happening. `Build Artifacts` are cleaned up already. I am closing this. please reopen and contact me if you see the problem again.

**Closed by mesutcelik** 2015-12-21 12:44 UTC
Labels: Team: Core, Type: Test-Failure
