### ISSUE TITLE
com.hazelcast.concurrent.lock.operations.LockOperation tryLock callTimeout and waitTimeout

### ISSUE THREAD

**Issue by frapana** [hazelcast/hazelcast#14535] opened 2019-02-21 10:55 UTC
We have an Embedded deployment with several members and instances. 
Hazelcast 3.11
hazelcast.max.no.heartbeat.seconds=1800
hazelcast.event.thread.count=100

When we call tryLock(lockName, 15, TimeUnit.SECONDS) sometimes we randomly get an OperationTimeoutException:

`com.hazelcast.core.OperationTimeoutException: LockOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2019-02-20 00:12:24.860. Start time: 2019-02-20 00:12:08.940. Total elapsed time: 15920 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2019-02-20 00:12:00.068. Invocation{op=com.hazelcast.concurrent.lock.operations.LockOperation{serviceName='hz:impl:lockService', identityHash=1082634633, partitionId=96, replicaIndex=0, callId=-4027912, invocationTime=1550617654295 (2019-02-20 00:07:34.295), waitTimeout=0, callTimeout=15000, namespace=DefaultObjectNamespace{service='hz:impl:mapService', objectName=locks}, threadId=528}, tryCount=250, tryPauseMillis=500, invokeCount=0, callTimeoutMillis=15000, firstInvocationTimeMs=1550617928940, firstInvocationTime='2019-02-20 00:12:08.940', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 01:00:00.000', target=[...]:52629, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=1, /10.224.2.25:52628->/10.224.2.25:39165, endpoint=[...]:52629, alive=true, type=MEMBER]}`

Although hazelcast.operation.call.timeout.millis default value is 60000, callTimeout and waitTimeout are set to 15000. Is this the normal behaviour? This causes to get an undocumented Exception instead of the boolean result: [Lock.html#tryLock](https://docs.hazelcast.org/docs/3.11/javadoc/com/hazelcast/core/ILock.html#tryLock-long-java.util.concurrent.TimeUnit-) 
~~The timeout itself can be related to LRO (#8831) that is enabled at the moment, we are going to disable it asap.~~ EDIT: there's only GRO and it is already disabled.
Note that both side of the connection are under the same JBoss, we upgraded a few months ago from 2.6.9 and noted an high increase in bandwidth usage between members deployed on different hosts.

**Comment by mmedenjak** [comment] 2019-11-06 15:03
Closing as a duplicate of https://github.com/hazelcast/hazelcast/issues/15328.

An operation timeout means the member responsible for running the operation is unresponsive. You might want to try and see why the member is unresponsive by profiling and monitoring it. Or, if you expect such pauses, you might want to increase the heartbeat timeout by increasing the `com.hazelcast.spi.properties.GroupProperty#OPERATION_CALL_TIMEOUT_MILLIS`.

**Closed by mmedenjak** 2019-11-06 15:03 UTC
Labels: Module: Lock, Source: Community, Team: Core

**Comment by frapana** [comment] 2019-11-07 09:55
I don't think this is a duplicate of #15328.

In this case I had the default OPERATION_CALL_TIMEOUT_MILLIS value (60 seconds) and a tryLock with a timeout of 15 secs. I think that it could be ok for the tryLock method to wait only 15secs before return (callTimeout and waitTimeout are set to 15000), but it should return false as documented and not OperationTimeoutException, because the OPERATION_CALL_TIMEOUT_MILLIS has not been reached yet. I think that raising OPERATION_CALL_TIMEOUT_MILLIS value will not change this behaviour.

**Comment by mmedenjak** [comment] 2019-11-07 10:23
True but there is a distinction - if the member is unresponsive and does not send heartbeats, we can't conclude anything - is the lock available? Maybe. Is the lock already locked? Maybe. Should we return true or false?
In that case, the best option is to return - unknown response or - operation heartbeat timeout.
