### ISSUE TITLE
MapStoreDataLoadingContinuesWhenNodeJoins.testLoadingFinishes_whenMemberJoinsWhileLoading

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#12371] opened 2018-02-19 09:24 UTC
```
java.lang.AssertionError: expected:<1000> but was:<993>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapStoreDataLoadingContinuesWhenNodeJoins$5.run(MapStoreDataLoadingContinuesWhenNodeJoins.java:213)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1158)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1175)
	at com.hazelcast.map.impl.mapstore.MapStoreDataLoadingContinuesWhenNodeJoins.testLoadingFinishes_whenMemberJoinsWhileLoading(MapStoreDataLoadingContinuesWhenNodeJoins.java:210)
```

https://hazelcast-l337.ci.cloudbees.com/view/Lab/job/Hazelcast-3.x-nightly-lab/490/testReport/junit/com.hazelcast.map.impl.mapstore/MapStoreDataLoadingContinuesWhenNodeJoins/testLoadingFinishes_whenMemberJoinsWhileLoading_LAZY_/

**Comment by blazember** [comment] 2018-03-01 20:07
I could not reproduce this failure with thousands of executions, but have identified a couple of findings based on local (successful) executions:

1. Loading had completed before `IMap.size()` was queried on node2. `IMap.size()` gets executed on node2 either after 5mins (`node1FinishedLoading` latch timeout) or after loading completed on node1 (`node1FinishedLoading` opens). Given that `assertEventually()` waits only for 2 mins and the test failed with non-zero actual value, the latch opened and `IMap.size()` was executed on node2 on a thought-to-be-loaded map, but resulted in an incorrect value. -> At least one partition's records were lost around the migration.
2. Loading completes only if both keys are known and the records are put into the record stores. `IMap.size()` doesn't return before that.
3. If loading completes before migration, loading will not be triggered on the target node. In this test, loading is not expected to be completed before migration happens because of the added sleep in the `MapLoader` test implementation.
4. `IMap.size()` may return an incorrect value if the new member joins the cluster while it executes. This is always true in this test: `IMap.size()` returns <1000 in all executions. -> Should it be re-executed if the cluster changes during its execution?
	4.1. `PutFromLoadAllOperation` waits for migration to complete.
	4.2. `IMap.size()` execution overlaps with the ongoing migration and it completes before the migration completes.
	4.3. `MapSizeOperation` for the randomly chosen partition 59 executes on both nodes, and because of `4.1.` it results in 0 value on both nodes.

Example log output with some extra logging for the randomly chosen `partition 59`:
```
===[Getting the map size and trigger map loading on node1]===================================================================
14:27:25,422  INFO || - [MapStoreDataLoadingContinuesWhenNodeJoins] Thread 1 - Getting the size of the map on node1 -> load is triggered
14:27:25,423  INFO || - [system] Thread 2 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Hazelcast 3.10-SNAPSHOT (20180227 - 34c6f65) starting at [127.0.0.1]:5002
14:27:25,424  INFO || - [system] Thread 2 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Copyright (c) 2008-2018, Hazelcast, Inc. All Rights Reserved.
14:27:25,424  INFO || - [system] Thread 2 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Configured Hazelcast Serialization version: 1
14:27:25,424  INFO || - [Node] Thread 2 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] A non-empty group password is configured for the Hazelcast member. Starting with Hazelcast version 3.8.2, members with the same group name, but with different group passwords (that do not use authentication) form a cluster. The group password configuration will be removed completely in a future release.
14:27:25,427  INFO || - [BackpressureRegulator] Thread 2 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Backpressure is disabled
14:27:25,427  INFO || - [PartitionStateManager] Thread 1 - [127.0.0.1]:5001 [dev] [3.10-SNAPSHOT] Initializing cluster partition table arrangement...
14:27:25,460  INFO || - [OperationExecutorImpl] Thread 2 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
14:27:25,513  INFO || - [Diagnostics] Thread 2 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
14:27:25,513  INFO || - [LifecycleService] Thread 2 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] [127.0.0.1]:5002 is STARTING

===[Node2 joins]============================================================================================
14:27:25,524  INFO || - [MockConnectionManager] Thread 2 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5001, connection: MockConnection{localEndpoint=[127.0.0.1]:5002, remoteEndpoint=[127.0.0.1]:5001}
14:27:25,536  INFO || - [MockConnectionManager] hz._hzInstance_1_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5001 [dev] [3.10-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5002, connection: MockConnection{localEndpoint=[127.0.0.1]:5001, remoteEndpoint=[127.0.0.1]:5002}
14:27:25,571  INFO || - [ClusterService] hz._hzInstance_1_dev.generic-operation.thread-1 - [127.0.0.1]:5001 [dev] [3.10-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5001 - 545143ef-3be8-4148-a06a-a93c254e7ac7 this
	Member [127.0.0.1]:5002 - 14f0b220-839e-4b7d-b2dc-73ae33907325
]

14:27:25,579  INFO || - [system] hz._hzInstance_2_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Cluster version set to 3.10
14:27:25,581  INFO || - [ClusterService] hz._hzInstance_2_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5001 - 545143ef-3be8-4148-a06a-a93c254e7ac7
	Member [127.0.0.1]:5002 - 14f0b220-839e-4b7d-b2dc-73ae33907325 this
]

===[Node1 sends the keys to load for partition 59]========================================================================
14:27:25,597  WARN || - [MapKeyLoader] hz._hzInstance_1_dev.cached.thread-4 - Sending 1 keys for the owner to load the records for partition 59 from the map store 

===[We're before migration, node1 receives the keys to load for partition 59]=========================================================
14:27:25,605  WARN || - [DefaultRecordStore] hz._hzInstance_1_dev.partition-operation.thread-3 - [127.0.0.1]:5001 [dev] [3.10-SNAPSHOT] Received 1 keys to load the records from the map store for partition 59
14:27:25,858  INFO || - [MigrationManager] hz._hzInstance_1_dev.migration - [127.0.0.1]:5001 [dev] [3.10-SNAPSHOT] Re-partitioning cluster data... Migration queue size: 271
14:27:26,039  INFO || - [LifecycleService] Thread 2 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] [127.0.0.1]:5002 is STARTED
14:27:26,039  INFO || - [MapStoreDataLoadingContinuesWhenNodeJoins] Thread 2 - Getting the map testMap

===[We're in the middle of  repartitioning, both node1 & node2 executes size operation for partition 59]========================================
14:27:26,199  INFO || - [DefaultRecordStore] hz._hzInstance_1_dev.partition-operation.thread-3 - [127.0.0.1]:5001 [dev] [3.10-SNAPSHOT] Size of partition 59 = 0
14:27:26,664  INFO || - [DefaultRecordStore] hz._hzInstance_2_dev.partition-operation.thread-3 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Size of partition 59 = 0

===[Migration completed]======================================================================================
14:27:27,633  INFO || - [MigrationThread] hz._hzInstance_1_dev.migration - [127.0.0.1]:5001 [dev] [3.10-SNAPSHOT] All migration tasks have been completed, queues are empty.

===[Node2 puts the record into its record store for partition 59]================================================================
14:27:28,603  WARN || - [DefaultRecordStore] hz._hzInstance_2_dev.partition-operation.thread-3 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Putting 1 record from load for partition 59
14:27:46,222  INFO || - [MapStoreDataLoadingContinuesWhenNodeJoins] Thread 1 - Map loading has been completed by now

===[IMap.size() issued against node1 before the migration started reports incorrect value for the map's size]======================================
14:27:46,222  INFO || - [MapStoreDataLoadingContinuesWhenNodeJoins] Thread 1 - Map size on node 1: 521
14:27:46,222  INFO || - [MapStoreDataLoadingContinuesWhenNodeJoins] Thread 2 - Node1 finished loading in time: true
14:27:46,222  INFO || - [MapStoreDataLoadingContinuesWhenNodeJoins] Thread 2 - Getting the size of the map on node2
14:27:46,223  INFO || - [DefaultRecordStore] hz._hzInstance_2_dev.partition-operation.thread-3 - [127.0.0.1]:5002 [dev] [3.10-SNAPSHOT] Size of partition 59 = 1

===[IMap.size() issued against node2 after the migration completed reports correct value for the map's size]=======================================
14:27:46,232  INFO || - [MapStoreDataLoadingContinuesWhenNodeJoins] Thread 2 - Map size on node 2: 1000
```

**Comment by blazember** [comment] 2018-03-05 10:29
### Explanation of the failure

The root cause behind the test failure is that both `IMap.size()` invocations return prematurely on the two test threads, before map loading completed. This is because of a known issue in map loading reported in issues #11544 and #12384: there is a race between the load and the operation executions during migration; the operations may not be aware of the ongoing load and execute on top of a not fully loaded map.

**Comment by blazember** [comment] 2018-04-23 14:12
The execution of this test with `LAZY` initial load mode is ignored with [`assumeThat`](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreDataLoadingContinuesWhenNodeJoins.java#L167) in the test method, since it is a known issue as mentioned in the previous comment. The referenced issues should remove the assumption when implemented.

Closing this test failure issue with the explanation above.

**Closed** 2018-04-23 14:12 UTC
Labels: Estimation: M, Interface: IMap, Team: Core, Type: Test-Failure
