### ISSUE TITLE
Add IMap.putAllAsync

### ISSUE THREAD

**Issue by alexturc** [hazelcast/hazelcast#569] opened 2013-07-17 20:08 UTC
A putAllAsync which puts entries in a distributed map in an true asynchronous manner, like putAsync implementation does for single entry in 3.0 version of Hazelcast, would be especially helpful when there are peak demands. It can happen that data accumulates in one place and there is opportunity for batching, which could be nicely done with putAllAsync. Doing repeated N putAsync with small bits of data where N is big enough should take more time and use more network traffic than doing one putAllAsync.

**Comment by brunolellis** [comment] 2015-03-09 22:09
I have tried to implement this issue but I don't know how to test/guarantee it is really asynchronous.

How can I test it?

**Comment by mmedenjak** [comment] 2020-02-04 10:52
`putAllAsync` is now available as private API and we might promote it to public API in a future release - https://github.com/hazelcast/hazelcast/issues/16449. Promoting this into a public API method is a simple PR so feel free to send it.

**Comment by mmedenjak** [comment] 2020-02-04 11:21
Closing as a duplicate of https://github.com/hazelcast/hazelcast/issues/5337. Still, feel free to send the PR.

**Closed by mmedenjak** 2020-02-04 11:21 UTC
Labels: Module: IMap, Priority: Low, Source: Community, Team: Core, Type: Enhancement, good first issue
