### ISSUE TITLE
Local topic stats publish and receive operation count returns Zero [HZ-2844]

### ISSUE THREAD

**Issue by shandilya22** [hazelcast/hazelcast#21356] opened 2022-05-04 12:03 UTC
**Describe the bug**
Any subscriber of Hazelcast reliable topic always shows publishOperationCount receiveOperationCount as zero.

**Expected behavior**
It should show actual data published or received by that node on the respective topic

We are fetching stats using below API:
`hz.getReliableTopic(topic-name).getLocalTopicStats().getPublishOperationCount()`
`hz.getReliableTopic(topic-name).getLocalTopicStats().getReceiveOperationCount()`

We are using Hz v-5.0.2. And, we have enabled topic stats for default topic configs in hz.xml

`<reliable-topic name="default">`
    `<read-batch-size>10</read-batch-size>`
    `<topic-overload-policy>BLOCK</topic-overload-policy>`
    `<statistics-enabled>true</statistics-enabled>`
`</reliable-topic>`

**Comment by gbarnett-hz** [comment] 2023-08-07 09:39
@shandilya22 I created a test with your configuration against 5.0.2 and couldn't reproduce -- publish and receive operation count are what I expect. Would it be possible to provide the example reproduction please?

**Comment by gbarnett-hz** [comment] 2023-08-07 16:57
Hi @shandilya22 , I added quick test [here](https://github.com/gbarnett-hz/hazelcast/blob/fix/5.4/hz-2844-rt-localstat-counts/hazelcast/src/test/java/com/hazelcast/topic/impl/reliable/Issue21356Test.java). The counts appear to be working as expected.

**Comment by gbarnett-hz** [comment] 2023-08-08 08:19
Closing - if the scenario is outside of what is tested we can re-open.

**Closed by gbarnett-hz** 2023-08-08 08:19 UTC
Labels: Type: Defect, Team: Core, Source: Community, to-jira
