### ISSUE TITLE
ServerQueryCacheRecreationTest query_cache_recreates_itself_after_server_restart

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#16663] opened 2020-02-15 08:21 UTC
- Fails on `Hazelcast-4..maintenance-ZingJDK8`
- Fails on [Build #138 (Feb 13, 2020 10:57:13 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4..maintenance-ZingJDK8/138/testReport/junit/com.hazelcast.map.impl.querycache/ServerQueryCacheRecreationTest/query_cache_recreates_itself_after_server_restart/)
- Error
```
expected:<300> but was:<292>
```
- Stack
```
junit.framework.AssertionFailedError: expected:<300> but was:<292>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.hazelcast.map.impl.querycache.ServerQueryCacheRecreationTest.lambda$query_cache_recreates_itself_after_server_restart$0(ServerQueryCacheRecreationTest.java:102)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.map.impl.querycache.ServerQueryCacheRecreationTest.query_cache_recreates_itself_after_server_restart(ServerQueryCacheRecreationTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```
- Observed high hiccups
```
Hiccups measured while running test 'query_cache_recreates_itself_after_server_restart(com.hazelcast.map.impl.querycache.ServerQueryCacheRecreationTest):'
19:07:20, accumulated pauses: 4944 ms, max pause: 13 ms, pauses over 1000 ms: 0
19:07:25, accumulated pauses: 4954 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:07:30, accumulated pauses: 4942 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:07:35, accumulated pauses: 4951 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:07:40, accumulated pauses: 4950 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:07:45, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:07:50, accumulated pauses: 4948 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:07:55, accumulated pauses: 4948 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:00, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:05, accumulated pauses: 4950 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:10, accumulated pauses: 4950 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:15, accumulated pauses: 4950 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:20, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:25, accumulated pauses: 4950 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:30, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:35, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:40, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:45, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:50, accumulated pauses: 4950 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:08:55, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:09:00, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:09:05, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:09:10, accumulated pauses: 4949 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:09:15, accumulated pauses: 4948 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:09:20, accumulated pauses: 2274 ms, max pause: 10 ms, pauses over 1000 ms: 0

```

- looks related https://github.com/hazelcast/hazelcast/pull/16438

kindly check.

**Comment by ahmetmircik** [comment] 2020-02-17 07:30
This is a flaky test and has same root cause with #16438, closing this one in favor of #16438.

**Closed by ahmetmircik** 2020-02-17 07:30 UTC
Labels: Source: Internal, Team: Core, Type: Test-Failure
