### ISSUE TITLE
Feature request: support bulk ops for TransactionalMap

### ISSUE THREAD

**Issue by dmitrymz** [hazelcast/hazelcast#9080] opened 2016-10-10 21:08 UTC
It will be great to add support for bulk operations for TransactionalMap: getAll, getAllForUpdate, putAll(), same as IMap.getAll(Set keys), and putAll().

Absence of this feature makes use of transactional map ineficcient

**Comment by mahsumdemir** [comment] 2020-02-10 17:34
I would like to work on this issue if that's okay.

**Comment by Holmistr** [comment] 2020-02-10 19:09
Hi @mahsumdemir , glad to see you here! And the issue is yours! :tada:  I believe that the linked issues and PRs provide you already a lot of information, so I don't want to take the fun out of you. However, feel free to ask more questions on Gitter, if you want more details :) There are no bad questions, I'm here for you!

**Comment by Holmistr** [comment] 2020-02-26 11:15
Hi @mahsumdemir , just checking in - is there anything we can help you out with? I just want to make sure that you're not stuck on something and just afraid to ask :)

**Comment by avirlrma** [comment] 2020-04-20 05:57
Hey, Can I start working on this?

**Comment by Holmistr** [comment] 2020-04-20 07:03
Hi @avirlrma , glad to see you here! :) Absolutely, I have just assigned you the issue.

We have Hazelcast Gitter channel: https://gitter.im/hazelcast/hazelcast . This is the fastest way to get feedback or do technical discussion. Please join there. But we'll be monitoring the issue as well, so you can here also.

Regarding some starting points, there was a pull request in the past that should show you the direction: https://github.com/hazelcast/hazelcast/pull/6705 . However, as this comment https://github.com/hazelcast/hazelcast/pull/6705#issuecomment-162892501 states, it was quite inefficient since it didn't use any batching. Therefore, it needs to be solved in a bit of different way. I will get in touch with our experts to give you some pointers there.

Looking forward to your contribution! :tada: :fist_oncoming:

**Comment by avirlrma** [comment] 2020-04-20 07:31
Thanks for the quick response, I am setting up the project and meanwhile going through the linked PR as well.

**Comment by mmedenjak** [comment] 2020-04-20 13:38
Hi @avirlrma ! After some internal discussion, we've decided that we will not be investing any time into transactions in Hazelcast in the near future. This is because transactions fundamentally have consistency issues and adding features on top of the current implementation, such as adding bulk operations, would encourage its' usage, which is not what we want.
So, we will leave the implementation now as-is. Once we decide to invest time to redesign transactions from the ground up, we can consider adding bulk operations again.

Sorry for the confusion, we came to this conclusion only hours ago. I'll unassign you from this issue and let me recommend that you pick another issue from one of these lists:
• https://github.com/hazelcast/hazelcast/contribute
• https://github.com/hazelcast/hazelcast/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Thank you again for your interest and my apologies for taking this issue away from you.

**Comment by Holmistr** [comment] 2020-04-21 06:33
Hey @avirlrma , sorry about this. However, we really appreciate your enthusiasm and I wouldn't like it to be wasted :) Is there any other issue you would like to work on? I'm happy to discuss or help you pick one, feel free to ping me on Gitther under "Holmistr" nickname :)

**Comment by Holmistr** [comment] 2020-04-21 06:34
@mmedenjak Given that we don't really want to invest time in this, WDYT about closing this issue with your explanation above? We can reopen it whenever we fix the transactional map. Otherwise, it will be sitting here forever.

**Comment by mmedenjak** [comment] 2020-04-21 11:29
Yes, closing.

**Closed by mmedenjak** 2020-04-21 11:29 UTC
Labels: Module: IMap, Module: Transactions, Priority: Low, Source: Community, Team: Core, Type: Enhancement

**Comment by avirlrma** [comment] 2020-04-23 05:36
@Holmistr No problem, I guess these things happen. I will go through the issue list and code base for better understanding. Will ping if I need help.
Thanks for such encouraging response. :smile:
