### ISSUE TITLE
HazelcastSerializationException java.io.UTFDataFormatException: malformed byte sequence

### ISSUE THREAD

**Issue by mayukhghoraihm** [hazelcast/hazelcast#12027] opened 2017-12-19 10:14 UTC
Getting `java.io.UTFDataFormatException: malformed byte sequence`. 
Model class implemented `DataSerializable` for serialization. 
`writeData(ObjectDataOutput)` and `readData(ObjectDataOutput)` methods has been overridden. 
Sequence is correct. 
Now I am getting `java.io.UTFDataFormatException: malformed byte sequence` exception while client is trying to get the IMap.

**Comment by sancar** [comment] 2018-01-16 13:00
Hi @mayukhghoraihm , 
Can you share your model class or a simple reproducer test ?

**Comment by sancar** [comment] 2018-01-29 13:13
Hi @mayukhghoraihm ,
Are you still suffering from same problem ?

**Comment by sancar** [comment] 2018-01-31 11:30
Hi @mayukhghoraihm , 
I am closing the issue, because we could not get a feedback form you.
If you still have a similar problem, please ask at our google group mail list. 
https://groups.google.com/forum/#!forum/hazelcast

**Closed by sancar** 2018-01-31 11:30 UTC
Labels: Team: Client, Team: Core

**Comment by bhushanvadgave** [comment] 2019-12-24 10:34
@sancar 
We are using Hazelcast (server version 3.12.4 with the latest Java and NodeJS clients) as Write-behind cache to manage user sessions. The values in the maps are Strings and we are not using any custom serializer.  We are seeing below errors in Hazelcast server multiple times. 

```
10:13:23.773 [hz._hzInstance_1_dev.cached.thread-9] ERROR c.h.m.i.m.w.DefaultWriteBehindProcessor - [10.240.1.158]:5701 [dev] [3.12.4] Number of entries which could not be stored is = [3], Hazelcast will indefinitely retry to store them
com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.UTFDataFormatException: Malformed byte sequence
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:70)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:193)
	at com.hazelcast.map.impl.mapstore.writebehind.AbstractWriteBehindProcessor.toObject(AbstractWriteBehindProcessor.java:55)
	at com.hazelcast.map.impl.mapstore.writebehind.DefaultWriteBehindProcessor.convertToObject(DefaultWriteBehindProcessor.java:227)
	at com.hazelcast.map.impl.mapstore.writebehind.DefaultWriteBehindProcessor.access$200(DefaultWriteBehindProcessor.java:41)
	at com.hazelcast.map.impl.mapstore.writebehind.DefaultWriteBehindProcessor$3.run(DefaultWriteBehindProcessor.java:246)
	at com.hazelcast.map.impl.mapstore.writebehind.DefaultWriteBehindProcessor.retryCall(DefaultWriteBehindProcessor.java:368)
	at com.hazelcast.map.impl.mapstore.writebehind.DefaultWriteBehindProcessor.callBatchStoreWithListeners(DefaultWriteBehindProcessor.java:240)
	at com.hazelcast.map.impl.mapstore.writebehind.DefaultWriteBehindProcessor.callHandler(DefaultWriteBehindProcessor.java:152)
	at com.hazelcast.map.impl.mapstore.writebehind.DefaultWriteBehindProcessor.processInternal(DefaultWriteBehindProcessor.java:99)
	at com.hazelcast.map.impl.mapstore.writebehind.DefaultWriteBehindProcessor.process(DefaultWriteBehindProcessor.java:70)
	at com.hazelcast.map.impl.mapstore.writebehind.StoreWorker.runInternal(StoreWorker.java:148)
	at com.hazelcast.map.impl.mapstore.writebehind.StoreWorker.run(StoreWorker.java:102)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.io.UTFDataFormatException: Malformed byte sequence
	at com.hazelcast.internal.memory.impl.EndiannessUtil.readUtf8Char(EndiannessUtil.java:335)
	at com.hazelcast.nio.Bits.readUtf8Char(Bits.java:204)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readUTF(ByteArrayObjectDataInput.java:564)
	at com.hazelcast.internal.serialization.impl.ConstantSerializers$StringSerializer.read(ConstantSerializers.java:219)
	at com.hazelcast.internal.serialization.impl.ConstantSerializers$StringSerializer.read(ConstantSerializers.java:210)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
```

**Comment by NitishDeshpande** [comment] 2019-12-24 10:43
I am also facing the same issue. Looking for help.
