### ISSUE TITLE
Clarify contract of Portable Factories (Class Definition?)

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#9813] opened 2017-02-07 10:38 UTC
A customer is reporting that if exchanging data between .NET and Java, the PortableFactories for each must define the fields in the same order particularly for the key. If they are not the key appears not to exist in the other language. 

The solution is to define the fields in the same order in each. Is that a bug? If not it should be clearly documented.

**Comment by sancar** [comment] 2017-02-07 11:03
It is not a bug, order needs to be same in all platforms. It needs be to be documented.

**Comment by sancar** [comment] 2017-02-07 11:20
To avoid confusion, I want to add more detail:

A portable object does not have to be read in order they are written. One can read in any order, or one can read only one field. There is no problem with that.
`writePortable` and `readPortable` does not have to be consistent.

But when same class defined in two different place, their write methods inside `writePortable` method needs to be in same order. 
`writePortable` from dotnet and `writePortable` from java has to be consistent.

**Comment by jerrinot** [comment] 2017-02-07 11:24
@sancar: thanks for clarification. could this be avoided by explicitly registered `ClassDefinition` ?

**Comment by sancar** [comment] 2017-02-07 11:32
@jerrinot 
That means you are gonna create ClassDefinition via `ClassDefinitionBuilder` right  ?
If you create ClassDefinitions in different orders, then again you have same problem.

 ``` 
new ClassDefinitionBuilder(1, 2).addBooleanField("a").addCharField("b").build();
new ClassDefinitionBuilder(1, 2).addCharField("b").addBooleanField("a").build();  
```

**Comment by sancar** [comment] 2017-02-09 08:27
Closing. We updated the doc.

**Closed by sancar** 2017-02-09 08:27 UTC
Labels: Team: Client, Team: Documentation, Type: Defect
