### ISSUE TITLE
com.hazelcast.jet.sql_slow.JetSqlSlowIndexTest.com.hazelcast.jet.sql_slow.JetSqlSlowIndexTest

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19987] opened 2021-11-29 10:05 UTC
_5.0.z_ (commit 63251231d6077ba4b1991573fdef8c0a46a7e88b)

Failed on sonar: [test failure report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/66/testReport/junit/com.hazelcast.jet.sql_slow/JetSqlSlowIndexTest/com_hazelcast_jet_sql_slow_JetSqlSlowIndexTest/)

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='optimistic_jones', node=[127.0.0.1]:5881}]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:46)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test[indexType:HASH, composite:false, field1:Character, field2:Character] in 1.427 seconds.
02:18:40,109  INFO || - [SimpleTestInClusterSupport] Time-limited test - Terminating instance factory in SimpleTestInClusterSupport.@AfterClass
02:18:40,110  INFO || - [LifecycleService] Thread-1623 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
02:18:40,110  WARN || - [Node] Thread-1623 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Terminating forcefully...
02:18:40,110  INFO || - [Node] Thread-1623 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Shutting down connection manager...
02:18:40,110  INFO || - [MockServer] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
02:18:40,110  INFO || - [MockServer] Thread-1623 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
02:18:40,110  INFO || - [MembershipManager] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Removing Member [127.0.0.1]:5702 - a9095de0-b002-47a8-ab2c-6368ce203021
02:18:40,110  INFO || - [PartitionStateManager] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Storing snapshot of partition assignments while removing UUID a9095de0-b002-47a8-ab2c-6368ce203021
02:18:40,111  INFO || - [ClusterService] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - a4a79a4e-30fc-478e-a2d3-0832bd3cf584 this
]

02:18:40,111  INFO || - [Node] Thread-1623 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Shutting down node engine...
02:18:40,111  INFO || - [TransactionManagerService] hz.vigilant_khorana.cached.thread-18 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: a9095de0-b002-47a8-ab2c-6368ce203021
02:18:40,113  INFO || - [MigrationManager] hz.vigilant_khorana.migration - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Partition balance is ok, no need to repartition.
02:18:40,114  INFO || - [NodeExtension] Thread-1623 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Destroying node NodeExtension.
02:18:40,114  INFO || - [Node] Thread-1623 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
02:18:40,114  INFO || - [LifecycleService] Thread-1623 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
02:18:40,114  INFO || - [LifecycleService] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
02:18:40,114  WARN || - [Node] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Terminating forcefully...
02:18:40,114  INFO || - [Node] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Shutting down connection manager...
02:18:40,114  INFO || - [Node] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Shutting down node engine...
02:18:40,115  INFO || - [NodeExtension] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Destroying node NodeExtension.
02:18:40,116  INFO || - [Node] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
02:18:40,116  INFO || - [LifecycleService] Thread-1623 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
02:18:40,118  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5881 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5881 is SHUTTING_DOWN
02:18:40,118 DEBUG || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5881 [dev] [5.0.1-SNAPSHOT] Added a shutting-down member: 4ab7fe62-aa21-4a7b-ac51-64ce6b52657d
02:18:40,118  INFO || - [Node] Time-limited test - [127.0.0.1]:5881 [dev] [5.0.1-SNAPSHOT] Shutting down connection manager...
02:18:40,118  INFO || - [Node] Time-limited test - [127.0.0.1]:5881 [dev] [5.0.1-SNAPSHOT] Shutting down node engine...
02:18:40,119  INFO || - [NodeExtension] Time-limited test - [127.0.0.1]:5881 [dev] [5.0.1-SNAPSHOT] Destroying node NodeExtension.
02:18:40,119  INFO || - [Node] Time-limited test - [127.0.0.1]:5881 [dev] [5.0.1-SNAPSHOT] Hazelcast Shutdown is completed in 1 ms.
02:18:40,119  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5881 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5881 is SHUTDOWN
```

</details>

**Comment by slavagithub** [comment] 2021-12-13 11:07
com.hazelcast.jet.sql_slow.MapIndexScanPMigrationStressTest.com.hazelcast.jet.sql_slow.MapIndexScanPMigrationStressTest fails with the same error on sonar - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/76/testReport/junit/com.hazelcast.jet.sql_slow/MapIndexScanPMigrationStressTest/com_hazelcast_jet_sql_slow_MapIndexScanPMigrationStressTest/

**Comment by olukas** [comment] 2022-01-21 07:28
Failed on `5.0.z` branch on Sonar (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/114/testReport/com.hazelcast.jet.sql_slow/JetSqlSlowIndexTest/com_hazelcast_jet_sql_slow_JetSqlSlowIndexTest/

**Comment by slavagithub** [comment] 2022-01-24 07:56
Failed on 5.0.z IBM, Jdk 8 - com.hazelcast.jet.sql_slow.MapIndexScanPMigrationStressTest.com.hazelcast.jet.sql_slow.MapIndexScanPMigrationStressTest

**Comment by slavagithub** [comment] 2022-01-25 07:55
failed again on 5.0z, Oracle, JDK8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK8-nightly/18/testReport/junit/com.hazelcast.jet.sql_slow/JetSqlSlowIndexTest/com_hazelcast_jet_sql_slow_JetSqlSlowIndexTest/

**Comment by viliam-durina** [comment] 2022-01-25 15:09
Possibly a duplicate of #19638

**Closed** 2022-02-02 10:20 UTC
Labels: Type: Test-Failure, Priority: Low, Source: Internal, Team: SQL, Module: Jet
