### ISSUE TITLE
Enhancement: logo

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#25788] opened 2023-10-23 08:39 UTC
Using 5.4.0-SNAPSHOT 
```
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o    
```

Doesn't match branding

**Comment by vbekiaris** [comment] 2023-10-23 08:43
see #25518

**Comment by nilnullneil** [comment] 2023-10-23 08:53
Close as duplicate of known issue

**Closed by nilnullneil** 2023-10-23 08:53 UTC
Labels: Type: Enhancement
