### ISSUE TITLE
[scheduled-executor] IScheduledExecutorService scheduleAtFixedRate not expected behavior

### ISSUE THREAD

**Issue by kadkaz** [hazelcast/hazelcast#11371] opened 2017-09-15 06:40 UTC
I have Spring boot application and want to have a running distributed job task each period of time and not more often than this period for all nodes. When I use scheduleAtFixedRate I have behavior like:
each node runs a job each period of time and do not look at another node that's been already run inside this period of time

Here is example of two nodes with period of 5 seconds:
The first node
```
2017-09-14 16:54:23,089 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-6] [] - Scheduler service triggered - fetching users from database for asynchronous validation
2017-09-14 16:54:28,101 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-4] [] - Scheduler service triggered - fetching users from database for asynchronous validation
2017-09-14 16:54:33,104 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-1] [] - Scheduler service triggered - fetching users from database for asynchronous validation
2017-09-14 16:54:38,093 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-3] [] - Scheduler service triggered - fetching users from database for asynchronous validation
2017-09-14 16:54:43,102 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-1] [] - Scheduler service triggered - fetching users from database for asynchronous validation
2017-09-14 16:54:48,096 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-1] [] - Scheduler service triggered - fetching users from database for asynchronous validation
```

The second node:
```
2017-09-14 16:54:23,358 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-4] [] - Scheduler service triggered - fetching users from database for asynchronous validation
2017-09-14 16:54:28,359 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-1] [] - Scheduler service triggered - fetching users from database for asynchronous validation
2017-09-14 16:54:33,368 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-1] [] - Scheduler service triggered - fetching users from database for asynchronous validation
2017-09-14 16:54:38,361 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-4] [] - Scheduler service triggered - fetching users from database for asynchronous validation
2017-09-14 16:54:43,370 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-3] [] - Scheduler service triggered - fetching users from database for asynchronous validation
2017-09-14 16:54:48,356 [INFO] c.u.b.s.b.SchedulerService [hz._hzInstance_1_ci1.1.0.cached.thread-3] [] - Scheduler service triggered - fetching users from database for asynchronous validation
```

As you see the both nodes are executing inside 5 seconds period and intersect 5 seconds period.

Why? Do you have another API for my requirement?
You solution is just a lock which helps to do not run a task at the same time but the task runs many times (how many nodes you have) inside period of time.

**Comment by mmedenjak** [comment] 2017-09-15 06:46
Hi @kadkaz !

Are you using the `scheduleAtFixedRate` method or some other method like `scheduleOnAllMembersAtFixedRate`, `scheduleOnKeyOwnerAtFixedRate`, `scheduleOnMemberAtFixedRate` or `scheduleOnMembersAtFixedRate`?

Are there network issues in the cluster? Do the two nodes see each other and do they form a cluster?

**Comment by kadkaz** [comment] 2017-09-15 08:48
Hi, @mmedenjak! no. it's not brain-split issue. I could find two nodes in a cluster. I'm using just scheduleAtFixedRate. tried to use scheduleOnAllMembersAtFixedRate the same behavior. (5 secs period is for testing, hazelcast version 3.8.4 and 3.8.5)

one node has:
`Members [2] {
	Member [localhost]:9472 - fd09e1ab-23e6-46a1-afce-7443d3c745dc this
	Member [localhost]:9473 - 2ee5e7f4-0e12-4c5b-ad7e-8187206c5a55
}`

the second node has:
`Members [2] {
	Member [localhost]:9472 - fd09e1ab-23e6-46a1-afce-7443d3c745dc
	Member [localhost]:9473 - 2ee5e7f4-0e12-4c5b-ad7e-8187206c5a55 this
}`

Sometimes I got 
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com....SchedulerServiceTask': Injection of autowired dependencies failed; nested exception is java.util.ConcurrentModificationException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBean(AbstractAutowireCapableBeanFactory.java:303)
	at com.hazelcast.spring.context.SpringManagedContext.initializeIfSpringAwareIsPresent(SpringManagedContext.java:61)
	at com.hazelcast.spring.context.SpringManagedContext.initialize(SpringManagedContext.java:46)
	at com......SchedulerServiceTask.setHazelcastInstance(SchedulerServiceTask.java:58)
	at com.hazelcast.instance.HazelcastManagedContext.initialize(HazelcastManagedContext.java:41)`

I use HazelcastInstanceAware with the code like:
@Override
public void setHazelcastInstance(HazelcastInstance hazelcastInstance) {
	hazelcastInstance.getConfig().getManagedContext().initialize(this);
}

I use it because @SpringAware does not work using SpringManagedContext

**Comment by kadkaz** [comment] 2017-09-15 20:48
Do you have examples how to use it? I guess I should register the task on the one node and then it will be distributed to all. So I will check this idea and tell you how it works. Because all nodes register the same task when they starting up.

**Comment by mmedenjak** [comment] 2017-09-18 07:29
There are some examples in the hazelcast code samples project : https://github.com/hazelcast/hazelcast-code-samples/tree/master/distributed-executor.
If you want to run just one instance of the task in the entire cluster, only one member should call the `scheduleAtFixedRate`, not every member on startup. If it is as you say : 
> all nodes register the same task when they're starting up 

then you can expect as many running tasks as there are members in the cluster.
Also, the fix for the injection of spring beans has been backported so 3.8.6 should include the fix once it is released in a week or two.

**Comment by kadkaz** [comment] 2017-09-18 09:17
I've cloned the last example sources, but couldn't find any example of scheduleAtFixedRate function.
and regarding 

> If you want to run just one instance of the task in the entire cluster, only one member should call the scheduleAtFixedRate, not every member on startup.

This what I expected hazelcast will understand it already registered and will not register it again but will move a task to new node when any a node crashed. So will do extra code who will check it's been already registered on not but it's boilerplate code you should have

**Comment by mmedenjak** [comment] 2017-09-18 09:21
It will register the task only once if you call `scheduleAtFixedRate` only once. If you call `scheduleAtFixedRate` multiple times (e.g. on each member startup), there will be multiple tasks.
The task will be "moved" to an another node if the node that is running it has crashed. But you don't need to call `scheduleAtFixedRate` multiple times to achieve this.

**Comment by kadkaz** [comment] 2017-09-18 14:33
ok. I did only one registration per cluster. but when I stop one node who runs a task then it does not try to run it on another node. and quit often I have exception:
`
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.....SchedulerServiceTask': Injection of autowired dependencies failed; nested exception is java.util.ConcurrentModificationException
`
do you know why?

**Comment by kadkaz** [comment] 2017-09-18 14:58
I've removed Autowired fields and implement ApplicationContextAware instead so no exception anymore, but when I stop a running task node it does not recover on another node. I have workaround to check in schedule was it registered or not. Please explain why it does not recovered on the second node?

**Comment by mmedenjak** [comment] 2017-09-18 17:49
It should have started on the second node if the durability for the scheduled executor is greater than 0. Can you send me your configuration? Also, can you raise the log level to `DEBUG`, reproduce this behaviour and send us logs from both members?

Regarding the `ConcurrentModificationException`, it's possible your object is initialised from different threads concurrently. It's very hard to draw some conclusions at this point. Can you make a minimal reproducer with Spring boot, your configuration and just the scheduled task so we can determine the cause?

**Comment by kadkaz** [comment] 2017-09-19 08:51
yes you are right. I forgot to change durability back more than 0 when I test another behavior. 
so let's close the jira. so conclusion is to use on start up only one registration of the task.

I could solve ConcurrentModificationException to change Autowired to use ApplicationContextAware.

**Closed** 2017-09-19 08:52 UTC
Labels: Team: Core, To Triage

**Comment by tkountis** [comment] 2017-09-19 11:28
@kadkaz To add on what @mmedenjak said, you can use a distributed lock to make sure just one member schedules it, or you can used `NamedTask` which allows you to have a unique name for a task, therefore any attempt to schedule the same task (=same name), it will throw a `DuplicateTaskException` which you can safely ignore.
