### ISSUE TITLE
HazelcastOSGiIntegrationTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#9537] opened 2016-12-28 09:59 UTC
The test was never picked up, due to a missing category. I just added it and ignored it, since it constantly fails:
```
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:127)
	at java.util.jar.JarFile.<init>(JarFile.java:136)
	at java.util.jar.JarFile.<init>(JarFile.java:115)
	at org.ops4j.pax.runner.platform.internal.PlatformImpl.validateBundle(PlatformImpl.java:716)
	at org.ops4j.pax.runner.platform.internal.PlatformImpl.download(PlatformImpl.java:603)
	at org.ops4j.pax.runner.platform.internal.PlatformImpl.downloadBundles(PlatformImpl.java:357)
	at org.ops4j.pax.runner.platform.internal.PlatformImpl.start(PlatformImpl.java:162)
	at org.ops4j.pax.runner.Run.startPlatform(Run.java:677)
	at org.ops4j.pax.runner.Run.start(Run.java:207)
	at org.ops4j.pax.runner.Run.start(Run.java:163)
	at org.ops4j.pax.exam.container.def.internal.PaxRunnerTestContainer.start(PaxRunnerTestContainer.java:114)
	at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:67)
	at org.ops4j.pax.exam.junit.JUnit4TestRunner$2.evaluate(JUnit4TestRunner.java:285)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.ops4j.pax.exam.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:94)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/6427/testReport/junit/com.hazelcast.osgi/HazelcastOSGiIntegrationTest/serviceRetrievedSuccessfully_com_hazelcast_osgi_HazelcastOSGiIntegrationTest_serviceRetrievedSuccessfully_PaxRunnerTestContainer_felix_/

**Comment by Holmistr** [comment] 2019-02-04 10:48
@blazember Very weird. However, it wasn't failing before, something had to change. I don't understand why it should create a file in this location. I will have to take a look.

**Comment by mmedenjak** [comment] 2019-02-06 14:30
Another failure: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/154

Error Message
com.hazelcast.osgi.HazelcastOSGiService not found by PAXEXAM-PROBE-e9c6ae2c-732b-4d06-8047-bd0788d071cd [17]

Stacktrace
java.lang.ClassNotFoundException: com.hazelcast.osgi.HazelcastOSGiService not found by PAXEXAM-PROBE-e9c6ae2c-732b-4d06-8047-bd0788d071cd [17]

**Comment by Holmistr** [comment] 2019-02-06 14:57
Looking into it.

**Comment by Holmistr** [comment] 2019-02-07 14:48
@taburet nailed the root cause. It's about Jenkins producing "@" in the workspace path. This also explains why it happens (almost) every second time - the "@" sign workspace is in place, when two PR builders run concurrently to differentiate the workspace. I'm looking into how to fix it, possibly by changing "@" to something less harmful.

**Comment by Holmistr** [comment] 2019-02-07 15:02
I believe I have found the solution by changing the delimiter to something else using "-Dhudson.slaves.WorkspaceList=<something>". I will try it tomorrow evening when less people are working, since it requires Jenkins restart.

**Comment by Holmistr** [comment] 2019-02-10 20:16
Fixed by changing the delimiter to "_".

**Closed by Holmistr** 2019-02-10 20:16 UTC
Labels: Team: Integration, Type: Test-Failure
