### ISSUE TITLE
[TEST-FAILURE] LocalRegionFactoryDefaultTest.testQuery

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3373] opened 2014-08-24 09:17 UTC
this test fails 3.x problematic tests.
also this test failed maintenance see: https://github.com/hazelcast/hazelcast/issues/3068

```
java.lang.AssertionError: expected:<1> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.hibernate.HibernateStatisticsTestSupport.testQuery(HibernateStatisticsTestSupport.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-problematicTest/com.hazelcast$hazelcast-hibernate3/229/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by mesutcelik** [comment] 2015-02-20 08:39
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/393/com.hazelcast$hazelcast-hibernate3/testReport/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by mesutcelik** [comment] 2015-03-02 09:06
@kobalski ,

I am closing that right now. Fix attempt at 43966bf and 4f4c09d9cc18638b36bc80c8824ce946cd64408d

**Comment by mesutcelik** [comment] 2015-03-17 08:22
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-hibernate3/418/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by Donnerbart** [comment] 2015-03-18 09:32
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/12280/com.hazelcast$hazelcast-hibernate3/testReport/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by kobalski** [comment] 2015-03-19 07:56
I am closing that right now. Fix attempt for master : https://github.com/hazelcast/hazelcast/pull/4836 and for maintenance : https://github.com/hazelcast/hazelcast/pull/4820.

**Comment by mesutcelik** [comment] 2015-03-21 10:44
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/60/com.hazelcast$hazelcast-hibernate3/testReport/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by mesutcelik** [comment] 2015-03-25 09:41
fixed via https://github.com/hazelcast/hazelcast/pull/4836

**Comment by bilalyasar** [comment] 2015-04-05 22:28
new failure: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-hibernate4/438/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by bilalyasar** [comment] 2015-04-05 22:33
also master failed: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-hibernate3/499/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by mesutcelik** [comment] 2015-04-15 16:07
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3016/com.hazelcast$hazelcast-hibernate4/testReport/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by mesutcelik** [comment] 2015-04-16 06:37
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7-Quality-Outreach/31/com.hazelcast$hazelcast-hibernate4/testReport/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by bilalyasar** [comment] 2015-04-20 07:07
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-hibernate4/3026/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by bilalyasar** [comment] 2015-04-20 07:24
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-hibernate4/594/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by bilalyasar** [comment] 2015-04-21 00:09
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-hibernate3/597/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by bilalyasar** [comment] 2015-04-21 13:50
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-hibernate4/3046/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by bilalyasar** [comment] 2015-04-24 09:39
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-hibernate4/38/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by bilalyasar** [comment] 2015-04-25 12:15
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast-hibernate4/527/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by bilalyasar** [comment] 2015-04-27 06:22
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-hibernate4/459/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by bilalyasar** [comment] 2015-04-28 06:49
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast-hibernate4/543/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by serkan-ozal** [comment] 2015-04-30 07:57
Hi, last two days, I was working on this issue. As I remember this issue is occurred since I have joined Hazelcast.

At first, I thought that the issue is only about same timestamp values at sequential calls. Yes this is one of the problems but it is not the only problem since sleeping between calls with `sleepAtLeastSeconds` doesn't solve the problem. 

The another problem is that replacing invalidated timestamp value with pre-invalidated timestamp value at commit. Let me explain this.

In Hibernate, there is a pre-invalidation and invalidation mechanism at commit. Pre-invalidation is triggered by `org.hibernate.impl.SessionImpl.flush()` and invalidation is triggered by `org.hibernate.impl.SessionImpl.afterTransactionCompletion()`. In Hibernate logic, while pre-invalidating, timestamp value is used as `next_timestamp + timeout` but while invalidating timestamp is used as `next_timestamp`. So the last value is `next_timestamp` after commit finished. 

In our Hibernate integration, default `timeout` value is `3.600.000` milliseconds (1 hour). Also we send message via topics for updating timestamp values on other nodes. But our topic listener also listens itself and sometimes can replace invalidated timestamp with pre-invalidated timestamp value since listener may get topic message after timestamp value is updated with invalidated timestamp value. In this case, because of pre-invalidated timestamp value is bigger than invalidated timestamp value (since there is also timeout value addition at pre-invalidated timestamp value), last value becomes bigger value than `next_timestamp` value (as mentioned before `next_timestamp` is used as invalidated timestamp value). So at `org.hibernate.cache.UpdateTimestampsCache.isUpToDate()`, since `next_timestamp` value is smaller than timestamp of region (because it is updated at topic listen with pre-invalidated timestamp value which contains timeout value also), query cache is considered as not up to date.

As solution, at first we should keep `sleepAtLeastSeconds(1)` between query calls and after insert. Then also I think, we should ignore local event at topic message listener in `com.hazelcast.hibernate.local.TimestampsRegionCache` by

```
if (message.getPublishingMember().localMember()) {
    return;
}
```

But when we run this test on multiple nodes, I am not sure this solves the problem at all cases. The optimal solution may be keeping and using Hibernate transaction id, invalidation type (pre-invalidate or invalidate) in `com.hazelcast.hibernate.local.Timestamp` by considering them while replacing with local timestamp value at topic listen. Anyway, I am not the person that decides this, I have just found the problem.

Maybe all of these explanations are not explained by me in clean way, so feel free for asking about more details.

**Comment by bilalyasar** [comment] 2015-05-01 01:47
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-hibernate4/3095/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by bilalyasar** [comment] 2015-05-02 23:45
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-hibernate4/3104/testReport/junit/com.hazelcast.hibernate/LocalRegionFactoryDefaultTest/testQuery/

**Comment by serkan-ozal** [comment] 2015-05-03 12:56
I think, adding 

``` java
if (message.getPublishingMember().localMember()) {
    return;
}
```
to ```TimestampsRegionCache``` in **Hibernate-3** ("https://github.com/hazelcast/hazelcast/blob/master/hazelcast-hibernate/hazelcast-hibernate3/src/main/java/com/hazelcast/hibernate/local/TimestampsRegionCache.java#L43") and **Hibernate-4** (https://github.com/hazelcast/hazelcast/blob/master/hazelcast-hibernate/hazelcast-hibernate4/src/main/java/com/hazelcast/hibernate/local/TimestampsRegionCache.java#L43) 

should fix the test failure as I mentioned at my previous comment.

**Closed** 2015-05-04 07:40 UTC
Labels: Team: Integration, Type: Defect

**Comment by kobalski** [comment] 2015-05-04 07:44
@serkan-ozal I applied your fixes. I also tested your fix on aws with large machine with 1000 repeats, it seems to fix the issue. Also, I agree with you that a member should not act events triggered locally. This fix should also improve performance in our L2 cache.
