### ISSUE TITLE
Improper eviction with max-size policy=PER_NODE

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#6418] opened 2015-10-09 18:13 UTC
Map configuration as follows:

               <map name="Cache1">
                                                <in-memory-format>BINARY</in-memory-format>      
                                                <backup-count>0</backup-count>        
                                                <async-backup-count>0</async-backup-count>              
                                                <max-size policy="PER_NODE">400</max-size>
                                                <eviction-policy>LFU</eviction-policy>
                                                <eviction-percentage>10</eviction-percentage>              
                                                <merge-policy> com.hazelcast.map.merge.HigherHitsMapMergePolicy</merge-policy>             
                </map>           
 
The map was populated with 380 entries. We could see that,  eviction happens even if 380 entries are added. The following are the values of important counters.
 
localPutOperationCount = 380
totalEvictedEntryCount = 2
size = 378
 
After this step I added 10 more entries in the cache. After this counter value looks as follows
 
localPutOperationCount=390
totalEvictedEntryCount=11
size=379
 
Another 10 more entries are added. After this counter value looks as follows
 
localPutOperationCount=400
totalEvictedEntryCount=21
size=379
 
Eviction should not have triggered before 400 entries in the cluster but it gets fired even at 380 entries. This is consistently reproducible, just use the above configurations and try putting entries as mentioned above.

**Comment by wildnez** [comment] 2015-10-12 03:40
Adding "Critical" as it is indeed a critical issue for a customer.

**Comment by mdogan** [comment] 2015-10-12 06:57
doesn't look like a **Critical** issue. it's even hard to categorize it as bug. For instance see Guava's size-based eviction, it's very similar:

> Warning: the cache may evict entries before this limit is exceeded -- typically when the cache size is approaching the limit.

https://github.com/google/guava/wiki/CachesExplained#Size-based-Eviction.md

**Comment by wildnez** [comment] 2015-10-12 09:56
Well on a contrary, there are other competitors which provide precise eviction. Lets keep the tickets opened for the PRD.

**Comment by mdogan** [comment] 2015-10-12 10:58
At least let's agree on this is not a bug but a design decision.

**Comment by enesakar** [comment] 2015-11-12 15:11
already fixed by #6547

**Closed by enesakar** 2015-11-12 15:11 UTC
Labels: Team: Core, Team: Documentation, Type: Defect
