### ISSUE TITLE
AdvancedNetworkClientIntegrationTest.testClientMembershipEvent

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15104] opened 2019-05-29 11:06 UTC
_master_ (commit e0da55e65df6d696535dfd27f02e029bea14e7ad)

Failed on CorrettoJDK8 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-CorrettoJDK8/11/testReport/com.hazelcast.client.io/AdvancedNetworkClientIntegrationTest/testClientMembershipEvent/

**Stacktrace**
```
java.lang.NullPointerException
	at com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testClientMembershipEvent(AdvancedNetworkClientIntegrationTest.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Standard output :** 
```
09:09:15,866  INFO |testClientMembershipEvent| - [PartitionStateManager] hz._hzInstance_4272_dev.client.thread-1 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Initializing cluster partition table arrangement...
09:09:15,867  INFO |testClientMembershipEvent| - [ClientMembershipListener] hz.client_2979.event-34018 - hz.client_2979 [dev] [4.0-SNAPSHOT] 

Members [3] {
	Member [127.0.0.1]:9090 - 2c21661d-d8f4-414b-8575-cf051f960926
	Member [127.0.0.1]:9091 - 140a1859-144a-4df8-8ff1-fccc6f708212
	Member [127.0.0.1]:9092 - d465568f-7494-49bd-9568-31aa749d32ef
}

09:09:15,867  INFO |testClientMembershipEvent| - [LifecycleService] hz.client_2979.cluster- - hz.client_2979 [dev] [4.0-SNAPSHOT] HazelcastClient 4.0-SNAPSHOT (20190529 - e0da55e) is CLIENT_CONNECTED
09:09:15,867  INFO |testClientMembershipEvent| - [Diagnostics] testClientMembershipEvent - hz.client_2979 [dev] [4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
09:09:15,867  INFO |testClientMembershipEvent| - [LifecycleService] testClientMembershipEvent - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
09:09:15,868  INFO |testClientMembershipEvent| - [MigrationManager] hz._hzInstance_4272_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5703 - d465568f-7494-49bd-9568-31aa749d32ef is handled
09:09:15,869  INFO |testClientMembershipEvent| - [MigrationManager] hz._hzInstance_4272_dev.migration - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Re-partitioning cluster data... Migration queue size: 7
09:09:15,876  INFO |testClientMembershipEvent| - [Node] testClientMembershipEvent - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Shutting down connection manager...
09:09:15,877  INFO |testClientMembershipEvent| - [TcpIpConnection] testClientMembershipEvent - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Connection[id=1, /127.0.0.1:50172->/127.0.0.1:5701, qualifier=EndpointQualifier{type='MEMBER'}, endpoint=[127.0.0.1]:5701, alive=false, type=MEMBER] closed. Reason: EndpointManager is stopping
09:09:15,877  INFO |testClientMembershipEvent| - [TcpIpConnection] testClientMembershipEvent - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Connection[id=2, /127.0.0.1:34600->/127.0.0.1:5702, qualifier=EndpointQualifier{type='MEMBER'}, endpoint=[127.0.0.1]:5702, alive=false, type=MEMBER] closed. Reason: EndpointManager is stopping
09:09:15,877  INFO |testClientMembershipEvent| - [Node] testClientMembershipEvent - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Shutting down node engine...
09:09:15,877  WARN |testClientMembershipEvent| - [TcpIpConnection] hz._hzInstance_4273_dev.IO.thread-in-2 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Connection[id=2, /127.0.0.1:5702->/127.0.0.1:34600, qualifier=EndpointQualifier{type='MEMBER'}, endpoint=[127.0.0.1]:5703, alive=false, type=MEMBER] closed. Reason: Exception in Connection[id=2, /127.0.0.1:5702->/127.0.0.1:34600, qualifier=EndpointQualifier{type='MEMBER'}, endpoint=[127.0.0.1]:5703, alive=true, type=MEMBER], thread=hz._hzInstance_4273_dev.IO.thread-in-2
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_202]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_202]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_202]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_202]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_202]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:113) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369) [hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354) [hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280) [hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235) [hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
09:09:15,877  WARN |testClientMembershipEvent| - [TcpIpConnection] hz._hzInstance_4272_dev.IO.thread-in-0 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Connection[id=2, /127.0.0.1:5701->/127.0.0.1:50172, qualifier=EndpointQualifier{type='MEMBER'}, endpoint=[127.0.0.1]:5703, alive=false, type=MEMBER] closed. Reason: Exception in Connection[id=2, /127.0.0.1:5701->/127.0.0.1:50172, qualifier=EndpointQualifier{type='MEMBER'}, endpoint=[127.0.0.1]:5703, alive=true, type=MEMBER], thread=hz._hzInstance_4272_dev.IO.thread-in-0
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_202]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_202]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_202]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_202]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_202]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:113) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369) [hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354) [hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280) [hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235) [hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
09:09:15,878  INFO |testClientMembershipEvent| - [TcpIpConnector] hz._hzInstance_4273_dev.cached.thread-1 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Connecting to /127.0.0.1:5703, timeout: 0, bind-any: true
09:09:15,878  INFO |testClientMembershipEvent| - [TcpIpConnector] hz._hzInstance_4272_dev.cached.thread-5 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Connecting to /127.0.0.1:5703, timeout: 0, bind-any: true
09:09:15,878  INFO |testClientMembershipEvent| - [TcpIpConnector] hz._hzInstance_4273_dev.cached.thread-1 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Could not connect to: /127.0.0.1:5703. Reason: SocketException[Connection refused to address /127.0.0.1:5703]
09:09:15,878  INFO |testClientMembershipEvent| - [TcpIpConnector] hz._hzInstance_4272_dev.cached.thread-5 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Could not connect to: /127.0.0.1:5703. Reason: SocketException[Connection refused to address /127.0.0.1:5703]
```

**Comment by lazerion** [comment] 2019-07-01 12:47
- Failed on [Hazelcast-3.maintenance-Windows-OracleJDK8](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-Windows-OracleJDK8/55/testReport/junit/com.hazelcast.client.io/AdvancedNetworkClientIntegrationTest/testClientMembershipEvent/)
- There seems to be no recent change since June 10, however, this test failed today, therefore I could not provide `commit` hash. Also, assigned as `low` priority, I will update issue with higher priority if stable reproducible.
- Stack trace same
```
Stacktrace
java.lang.NullPointerException
	at com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testClientMembershipEvent(AdvancedNetworkClientIntegrationTest.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vbekiaris** [comment] 2019-07-02 11:16
Fixed in `maintenance-3.x` branch by #15246

**Comment by olukas** [comment] 2021-06-07 07:38
Reopen. Failed again with `master` branch and IBM JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/3/testReport/com.hazelcast.client.io/AdvancedNetworkClientIntegrationTest/testClientMembershipEvent/

Stacktrace:
```
java.lang.NullPointerException
	at com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testClientMembershipEvent(AdvancedNetworkClientIntegrationTest.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

**Closed** 2021-09-14 07:16 UTC
Labels: Team: Core, Type: Test-Failure, Source: Internal, Module: Network I/O
