### ISSUE TITLE
com.hazelcast.client.TcpClientConnectionTest.testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=UNISOCKET] [HZ-4804]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26368] opened 2024-06-25 15:17 UTC
_master_ (commit d20a471245471d2cd90d8aaac10403417eb9f279)

Failed on Windows - OracleJDK21: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK21/9/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice_0__routingMode_UNISOCKET_/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.client.TcpClientConnectionTest.lambda$testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice$8(TcpClientConnectionTest.java:241)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1216)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1321)
	at com.hazelcast.client.TcpClientConnectionTest.testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice(TcpClientConnectionTest.java:238)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-OracleJDK21/9/

**Comment by AleksPeychev** [comment] 2024-07-01 18:29
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/122/testReport/junit/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice_0__routingMode_UNISOCKET_/

**Comment by olukas** [comment] 2024-07-10 07:54
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/26330

**Closed by olukas** 2024-07-10 07:54 UTC
Labels: Team: Client, Team: Core, Type: Test-Failure, Source: Internal, to-jira
