### ISSUE TITLE
com.hazelcast.jet.config.ResourceConfigTest.when_addResourcesWithNonExistingPackage

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23857] opened 2023-03-07 08:15 UTC
_master_ (commit 83371a644146617653c1e5a83c72a04264b4175c)

Failed on openjdk-20: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-ea/25/testReport/junit/com.hazelcast.jet.config/ResourceConfigTest/when_addResourcesWithNonExistingPackage/
<details><summary>Stacktrace:</summary>

```
java.lang.RuntimeException: Cannot use reflection after ScanResult has been closed
	at nonapi.io.github.classgraph.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:241)
	at io.github.classgraph.ModuleRef.<init>(ModuleRef.java:91)
	at nonapi.io.github.classgraph.classpath.ModuleFinder.findModuleRefs(ModuleFinder.java:189)
	at nonapi.io.github.classgraph.classpath.ModuleFinder.findModuleRefsFromCallstack(ModuleFinder.java:258)
	at nonapi.io.github.classgraph.classpath.ModuleFinder.<init>(ModuleFinder.java:284)
	at nonapi.io.github.classgraph.classpath.ClasspathFinder.<init>(ClasspathFinder.java:168)
	at io.github.classgraph.Scanner.<init>(Scanner.java:166)
	at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1531)
	at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1559)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1584)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1623)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1636)
	at com.hazelcast.jet.impl.util.ReflectionUtils.resourcesOf(ReflectionUtils.java:258)
	at com.hazelcast.jet.config.JobConfig.addPackage(JobConfig.java:337)
	at com.hazelcast.jet.config.ResourceConfigTest.when_addResourcesWithNonExistingPackage(ResourceConfigTest.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1591)

```
</details>

<details><summary>Standard output:</summary>

```

No metrics recorded during the test
Finished Running Test: when_attachNonexistentDirectoryWithUrl_then_throwsException in 0.223 seconds.
Started Running Test: when_addZipOfJarWithFile
Started Running Test: when_addResourceWithFileAndId

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK-ea/25/

Similar issues: 
https://github.com/hazelcast/hazelcast/issues/23838 
https://github.com/hazelcast/hazelcast-enterprise/issues/5786

**Comment by orcunc** [comment] 2023-04-12 10:36
The same problem happens for https://github.com/hazelcast/hazelcast/issues/23838

The problem is this exception coming from classgraph library
Cannot use reflection after ScanResult has been closed

It seems the race condition in the classgraph library has been fixed with
https://github.com/classgraph/classgraph/issues/757

We are using version 4.8.157 of the classgraph library now. I hope the new version of the library fixes everything. Therefore I am going to close this ticket

**Closed by orcunc** 2023-04-12 10:36 UTC
Labels: Type: Test-Failure, Source: Internal, Module: Jet, Team: Platform
