### ISSUE TITLE
High CPU usage on specific node.

### ISSUE THREAD

**Issue by JiseongKim** [hazelcast/hazelcast#7073] opened 2015-12-15 06:11 UTC
Hi,
I'm using HazelCast. And I had performance test with it.
But CPU usage of 1 node among the cluster, is too high.
And when I check it with AppDynamics, it looks like try publish event on `publishEvent` function.
Q1) What kind of data is published(all of our published messages? or some hazel cast data)
Q2) If it publish our own data, can we load-balance it with proper way?

**Comment by eminn** [comment] 2015-12-15 07:42
Hi @JiseongKim ,

Can you share your test scenario ? Which hazelcast version are you using ? 

Do you have any local map/entry listeners which might cause additional CPU usage for a particular node where local listeners are ?

**Comment by JiseongKim** [comment] 2015-12-15 08:10
Hi @eminn. Thank you for quick answer.
hazelcast version is `3.5.3`.
Actually we are work for game server. And there are several nodes which perform each task.
When each service on the node have some important data, the data publishes to the other nodes to backup.
Based on our investigation, many times `baseputoperation.afterrun`->`mapeventpublisherimpl.publishevent` is called on just 1 node(the node is changed by server execution) with high network I/O and high CPU usage.
And we don't use map/entry listeners for particular node.

**Comment by eminn** [comment] 2015-12-15 08:17
That method is called for map listeners/events but if you don't have any registered listener, there won't be any events fired. How do you update the map ? Do you use entry processors ?

**Comment by JiseongKim** [comment] 2015-12-15 08:29
Actually, we are using hazelcast with Akka plugin. 
There are several services(on each node) which use hazelcast. 
But I don't know why network I/O of particulat node is too high with the function calling.

**Comment by ghostdogpr** [comment] 2015-12-15 08:48
(I'm working with Jiseong)
We are using a simple IMap and just call the "put" method to add items.
We didn't register any listener in our code. Are there any listener setup by default?

**Comment by ghostdogpr** [comment] 2015-12-15 09:21
To summarize:
- we have a cluster of 24 application nodes with embedded Hazelcast, which is configured with 2 sync backups
- we use lots of different IMap instances (~2000), each IMap has a few entries
- we do lots of "put" and more rarely "get"
- we noticed that one of those nodes had a higher CPU usage and network IO (mostly writing)
- by profiling the application, most of this CPU time was spent in BasePutOperation.afterRun which itself was calling MapEventPublisherImpl.publishEvent (and this was spending lots of time in Tcp.write)
- we didn't register any listener

Any idea what could cause the high CPU/network usage?
Is it not recommended to have lots of IMap?

Thanks.

**Comment by pveentjer** [comment] 2015-12-15 09:31
Are you using near cache? Map listeners?

Many maps is not a problem.

**Comment by ghostdogpr** [comment] 2015-12-15 09:37
No near cache nor map listener (unless there is something by default).

Our calls to Hazelcast API are really basic: newHazelcastInstance, getMap, shutdown and on the IMap: get, put, remove, destroy, entrySet, keySet.

**Comment by eminn** [comment] 2015-12-15 09:52
There are no listeners registered by default. I have no idea how hazelcast akka plugin works internally, may be they are using listeners.

**Comment by ghostdogpr** [comment] 2015-12-15 09:55
No that's our own plugin, it uses only what I mentioned just above.

What does the "master" member do exactly? I can see that even when we're not using our application, that node has a Network IO KB writes/sec about 3 times higher than the other nodes.

**Comment by ghostdogpr** [comment] 2015-12-15 10:07
Just a random idea but could it be caused by the heartbeat?
Is the master node managing the heartbeat to all the other nodes?

**Comment by jerrinot** [comment] 2016-01-05 14:09
Hello @ghostdogpr,

I do not think it's caused by heartbeats - they are running only so often and it's unlikely they would cause a performance issue. 

You finding around `MapEventPublisherImpl.publishEvent` is interesting. Do you have stracktraces you could share?

**Comment by ghostdogpr** [comment] 2016-01-06 09:45
Sorry I didn't keep it. It seems it's solved anyhow, I will close this issue.

**Comment by jerrinot** [comment] 2016-01-06 09:49
@ghostdogpr: Thanks for an update. I'm closing the issue now. Please feel free to re-open it if you experience it again.

**Closed by jerrinot** 2016-01-06 09:49 UTC
