### ISSUE TITLE
Hazelcast Client Memory Leak

### ISSUE THREAD

**Issue by pramodterdale** [hazelcast/hazelcast#7851] opened 2016-03-28 01:11 UTC
I am using Hazelcast 3.6 and running 2 node cluster with 16GB of memory on each for hazelcast. The hazelcast server seems to be fine with memory usage, however on the client end (my application) it is causing out of memory and not able to find the root cause. I am using HazelcastClient to connect to cluster and get/containsKey/put/remove data from Map and Multimap  with key as Long value and value as custom objects, getting OOM after storing about 1 -2 mil objects(each object is  of 2-4KB in size) in each Map and Mulitmap. We also use lot of atomic variable to maintain the counter of each activity, I am getting this behavior consistently and at the end getting OOM error. Attached is the graph of heap usage over a period of 20min. It always trends upwards and it stops when OOM error comes, i have analyzed the heap dump for multiple occurrences and the heap usage is mainly because of hazelcast object, below are the main leak suspects from MAT, i verified and reviewed our code multiple times and there is nothing that causes a memory leak. 

Here is the code, i am using singleton pattern to initialize Hazelcast client instance and using the same for all other usage.

    ClientConfig clientConfig = null;
    HazelcastProvider provider = null;
     if (hzInstance == null)
      {
        synchronized (CacheHelper.class)
        {
          if (hzInstance == null)
          {
            Config hzCfg = new Config();
            GroupConfig groupConfig = getGroupConfig(smCfg);
            hzCfg.setGroupConfig(groupConfig);
            hzCfg.setInstanceName(instanceName);
            PartitionGroupConfig partitionGroupConfig = new PartitionGroupConfig();
            partitionGroupConfig.setEnabled(RTUtils.getPropertyValue(smCfg,                           PARTITION_GROUP_ENABLED, false));
            hzCfg.setPartitionGroupConfig(partitionGroupConfig);

            NetworkConfig network = cfg.getNetworkConfig();
           JoinConfig join = network.getJoin();
           join.getMulticastConfig().setEnabled(false);
           join.getTcpIpConfig().setEnabled(true);
           List<String> addresses = RTUtils.getMultiValToList(RTUtils.getPropertyValue(stromConfig, TCPIP_MEMBERS));
           addresses.add(reqMem);
            join.getTcpIpConfig().setMembers(addresses);
            join.getTcpIpConfig().setRequiredMember(reqMem);
            hzInstance = HazelcastClient.newHazelcastClient(_clientConfig)
          }
        }
      }

I am attaching few screenshots

![histogram sampling](https://cloud.githubusercontent.com/assets/5994348/14068758/793a199c-f45b-11e5-9d47-0ee858585058.JPG)
![histogram](https://cloud.githubusercontent.com/assets/5994348/14068761/794087c8-f45b-11e5-896d-ccd984541e5c.JPG)
![leask suspects](https://cloud.githubusercontent.com/assets/5994348/14068762/7942d852-f45b-11e5-993f-21a71b90444a.JPG)
![leask suspects1](https://cloud.githubusercontent.com/assets/5994348/14068763/7943f32c-f45b-11e5-894d-ff811712a360.JPG)
![leask suspects2](https://cloud.githubusercontent.com/assets/5994348/14068760/793f5006-f45b-11e5-928f-d28751e3046b.JPG)
![oom](https://cloud.githubusercontent.com/assets/5994348/14068759/793eb3bc-f45b-11e5-9034-c60c25228e07.JPG)

The thread com.hazelcast.util.executor.StripedExecutor$Worker @ 0x6ffd45bd8 hz.client_0_dev.event-1 keeps local variables with total size 647,087,896 (18.97%) bytes.

The thread com.hazelcast.util.executor.StripedExecutor$Worker @ 0x6ffd80118 hz.client_0_dev.event-2 keeps local variables with total size 629,825,296 (18.47%) bytes.

The thread com.hazelcast.util.executor.StripedExecutor$Worker @ 0x6fff13750 hz.client_0_dev.event-4 keeps local variables with total size 612,568,016 (17.96%) bytes.

**Comment by bwzhang2011** [comment] 2016-03-30 06:04
@sancar, any update with such issue ? is it confirmed in 3.6 branch ?

**Comment by sancar** [comment] 2016-04-04 08:17
Hi, the OOME seems to be caused by listeners in your case. Listeners is the only place that we use `StripedExecutor`

Default of "hazelcast.client.event.queue.capacity" is 1.000,000. You have 500,000 packages. My theory is that since your objects does not fit to your jvm for listeners. 

One thing to check is "# of bytes of an object in listener" times "hazelcast.client.event.queue.capacity"   should easily fit to JVM heap. Other thing to check is that why listener queue is piling up.  It seems like listener threads can not keep up with incoming packages. We see that when user operation takes too long time inside listener implementation.

**Comment by pramodterdale** [comment] 2016-04-04 20:06
The flow is very simple in my use case, i have a multi-map and a map, first i check if the key exists in multi-map if yes get the first value (which is key for a map) and then remove the entry both from multi-map and map, if the key does not exists in multi map then add it to multi-map as well as to map. The incoming data rate is very high about 5 to 10K per second but it varies throughout the day. Which client operation is taking time or not keeping up is difficult to find out, just check/insert/remove is taking long time that means something is not right, either i am doing something wrong or there is some issue with the client API. can u please help me to fix the issue.

**Comment by sancar** [comment] 2016-04-05 08:19
Anything about listeners ? This graphs that you shared is pointing to listeners as the source of problem. Can you confirm that you are using listeners in your code ? For example, `addEntryListener ` .
If not,  it might be the nearcache adding a listener also. Are you using nearcache ? 

If you are using listeners, please make sure you configure client according to my suggestions my comment above. https://github.com/hazelcast/hazelcast/issues/7851#issuecomment-205186071

**Comment by sancar** [comment] 2016-04-13 07:59
@pramodterdale I am closing the ticket since we could not reproduce it. If you have time to give further information about this please continue to add comments here so that we can find the issue if there is any.

**Closed by sancar** 2016-04-13 07:59 UTC
Labels: Team: Client, Type: Defect

**Comment by golart** [comment] 2019-06-14 11:39
I have the same problem. Heap.memiomy.used increasing slowly, but suddenly I catched OOM
