### ISSUE TITLE
, reason com.hazelcast.core.HazelcastException: java.io.IOException: null

### ISSUE THREAD

**Issue by bugbugmaker** [hazelcast/hazelcast#21083] opened 2022-03-29 11:00 UTC
hz.client_1 [dev] [4.2.2] Could not connect to member c21827f4-8059-4b90-b6ab-ed84aadde297, reason com.hazelcast.core.HazelcastException: java.io.IOException: null to address /localhost:5702

**Comment by vbekiaris** [comment] 2022-03-30 09:46
duplicate of #21096

**Closed by vbekiaris** 2022-03-30 09:46 UTC
Labels: Type: Defect
