### ISSUE TITLE
Cluster join hangs with multi-homed hosts

### ISSUE THREAD

**Issue by lprimak** [hazelcast/hazelcast#18828] opened 2021-06-02 16:34 UTC
This is a continuation of #17834
Even though the test failures are fixed, the issue of cluster join in multi-homed hosts described there remains.
This is demonstrated by PR #17835

**Describe the bug**
On Multi-homed hosts, i.e. mac w/Ethernet and WiFi networks enabled,
if listener is listening on all interfaces, but a public address is fixed,
connections to the "other interface" hang indefinitely instead of connected.

**Expected behavior**
Hazelcast should work correctly on hosts with multiple NICs no matter which IP / interface is connected to.

**To Reproduce**
Run test in the above attached PR

**Additional context**
JDK 8, Mac w/multiple NICs, Hazelcast 5.0-SNAPSHOT checked out from master as of Jun e2, 2021

Active NICs:
- 10.0.1.2 (Ethernet)
- 10.0.1.3 (WiFi)

**Comment by lprimak** [comment] 2021-06-02 16:35
@mmedenjak Added a new, separate issue for multi-homed cluster join failures

**Comment by kwart** [comment] 2022-02-21 17:23
@lprimak I guess the issue is fixed by networking changes (a.k.a hostnames fixes) introduced in 5.1. 
Could you verify your scenarios with the 5.1-SNAPSHOT (or 5.1-DR8 in https://repository.hazelcast.com/devel/)?

**Comment by lprimak** [comment] 2022-02-21 18:20
@kwart I guess your team is checking the reproducer PR. Let me know if you still want me to do it.
The PR reproduces this issue precisely.

Thanks!

**Comment by kwart** [comment] 2022-02-21 18:40
I got all the tests in the `MultiHomedJoinerTest` green with 5.1-SNAPSHOT (and 2 network connections enabled) in my local environment. So I will close this and if you experience any problem in 5.1, feel free to reopen.
Thank you.

**Closed by kwart** 2022-02-21 18:40 UTC
Labels: Type: Defect, Team: Core, Source: Community, Module: Network I/O
