### ISSUE TITLE
Paging predicate not working properly when map has over a spesific number of entries

### ISSUE THREAD

**Issue by hkilimci** [hazelcast/hazelcast#13900] opened 2018-10-04 08:52 UTC
Using C# client.

I am trying to get hazelcast data and show it in a datatable. So I definitely need to use Paging for huge maps. I have come across with PagingPredicate. And adapted my models and repository code. However and bizarrely, it works only when there are less than some specific number of entries. The error is "Could not found Portable Factory for factory-id: 5"

I actually setting the factory Id on startup with code below.

clientConfig.GetSerializationConfig().AddPortableFactory(classId, portableInstance);
My CommInfoImdb implements IPortable and the model has factory Id and class Id.

As you can see from the images below, paging is successfully completed when the map has 21 entries. (I know that's bizarre but the number was 36 before, and yes I have already checked the data, nothing related with it) However, it throws the portable factory exception if there are more than 21 entries.

Please see the images below for some cases.

https://i.stack.imgur.com/rFGgc.png

https://i.stack.imgur.com/2K9Wx.png

https://i.stack.imgur.com/UiBZe.png

And below exception throws when I set the Page property of PagingPredicate.

https://i.stack.imgur.com/sVS4m.png

So, as far as I realized when I debug the code, it does enter in SerializeableFactory method and creates the instance if the number of entries lower than 21 (in this case) and also if I use Map.Values() without PagingPredicate, however it doesn't enter in SerializeableFactory method so not create the instance when I use Map.Values(pagingPredicate), sometimes, well if entry count is bigger than 21, in this case.

**Comment by burakcelebi** [comment] 2019-02-20 10:36
Closing as it is a duplicate of https://github.com/hazelcast/hazelcast-csharp-client/issues/212.

**Closed by burakcelebi** 2019-02-20 10:36 UTC
Labels: Module: IMap, Module: Query, Source: Community, Team: Client, Type: Question
