### ISSUE TITLE
NullPointerException RaftSessionService after Hazelcast upgrade from 5.2.1 to 5.2.2

### ISSUE THREAD

**Issue by clude86** [hazelcast/hazelcast#23687] opened 2023-02-17 07:39 UTC
After we updated hazelcast from 5.2.1 to 5.2.2, we get the following error:

**Exception:**
`2023-02-17 08:24:11.931 WARN  [::] c.h.i.m.i.MetricsCollectionCycle - Collecting metrics from source com.hazelcast.cp.internal.session.RaftSessionService failed [[hz.ecstatic_mcclintock.cached.thread-3]]
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at com.hazelcast.internal.metrics.impl.MetricDescriptorImpl.withTag(MetricDescriptorImpl.java:68)
	at com.hazelcast.internal.metrics.impl.MetricDescriptorImpl.withTag(MetricDescriptorImpl.java:38)
	at com.hazelcast.cp.internal.session.RaftSessionService.provideDynamicMetrics(RaftSessionService.java:528)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:94)
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:320)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)`

**Configuration (local dev):**

- multicast: false
- cluster member: localhost

**Comment by mmichalowicznuix** [comment] 2023-02-27 22:26
Experiencing same issue with 5.2.2 with tag == "endpointName" whose value is null.

withTag("endpointName":String, null:value):MetricDescriptorImpl
group == p2dQueueLock

**Comment by canthony** [comment] 2023-05-11 11:24
Same issue on 5.1.6, using hazelcast-default.xml:
```
2023-05-11 11:14:35.630 UTC  INFO 35500 --- [           main] c.h.i.config.AbstractConfigLocator       : Loading 'hazelcast-default.xml' from the classpath.
2023-05-11 11:14:36.810 UTC  INFO 35500 --- [           main] com.hazelcast.system                     : [10.235.121.94]:5701 [dev] [5.1.6] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
2023-05-11 11:14:36.810 UTC  INFO 35500 --- [           main] com.hazelcast.system                     : [10.235.121.94]:5701 [dev] [5.1.6] Hazelcast Platform 5.1.6 (20230510 - 029cff5) starting at [10.235.121.94]:5701
2023-05-11 11:14:36.810 UTC  INFO 35500 --- [           main] com.hazelcast.system                     : [10.235.121.94]:5701 [dev] [5.1.6] Cluster name: dev
2023-05-11 11:14:38.473 UTC  INFO 35500 --- [           main] com.hazelcast.system.security            : [10.235.121.94]:5701 [dev] [5.1.6] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see security recommendations and the status of current config.
2023-05-11 11:14:38.762 UTC  INFO 35500 --- [           main] com.hazelcast.instance.impl.Node         : [10.235.121.94]:5701 [dev] [5.1.6] Using Multicast discovery
2023-05-11 11:14:38.776 UTC  WARN 35500 --- [           main] com.hazelcast.cp.CPSubsystem             : [10.235.121.94]:5701 [dev] [5.1.6] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2023-05-11 11:14:39.655 UTC  INFO 35500 --- [           main] c.h.internal.diagnostics.Diagnostics     : [10.235.121.94]:5701 [dev] [5.1.6] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2023-05-11 11:14:39.668 UTC  INFO 35500 --- [           main] com.hazelcast.core.LifecycleService      : [10.235.121.94]:5701 [dev] [5.1.6] [10.235.121.94]:5701 is STARTING

...

2023-05-11 11:15:05.671 UTC  WARN 35500 --- [cached.thread-3] c.h.i.m.impl.MetricsCollectionCycle      : Collecting metrics from source com.hazelcast.cp.internal.session.RaftSessionService failed

java.lang.NullPointerException: null

java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at com.hazelcast.internal.metrics.impl.MetricDescriptorImpl.withTag(MetricDescriptorImpl.java:69)
	at com.hazelcast.internal.metrics.impl.MetricDescriptorImpl.withTag(MetricDescriptorImpl.java:39)
	at com.hazelcast.cp.internal.session.RaftSessionService.provideDynamicMetrics(RaftSessionService.java:528)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:88)
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:317)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by fogninid** [comment] 2023-11-23 12:29
@arodionov I suppose this is a duplicate of #24272 

I am having this issue on version 5.1.7, are there plans to backport also there?

**Comment by arodionov** [comment] 2023-11-23 14:37
@fogninid 5.1.x is close to EOL, so we will not provide new releases. 
Please move to 5.2.x version

**Closed by arodionov** 2023-11-23 14:37 UTC
Labels: Type: Defect, Module: CP Subsystem
