### ISSUE TITLE
CacheSplitBrainTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9335] opened 2016-11-28 11:54 UTC
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:820)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:813)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:805)
	at com.hazelcast.cache.merge.CacheSplitBrainTest.testPassThroughCacheMergePolicy(CacheSplitBrainTest.java:260)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/1302/#showFailuresLink

**Comment by vbekiaris** [comment] 2016-11-28 16:59
Fixed by #9328

**Comment by mmedenjak** [comment] 2018-02-01 13:48
**com.hazelcast.cache.merge.CacheSplitBrainTest.testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.PassThroughMergePolicy]**
**com.hazelcast.cache.merge.CacheSplitBrainTest.testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.PutIfAbsentMergePolicy]**

```
java.lang.AssertionError: expected:<PutIfAbsentValue2> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cache.merge.CacheSplitBrainTest.afterMergePutIfAbsentMergePolicy(CacheSplitBrainTest.java:362)
	at com.hazelcast.cache.merge.CacheSplitBrainTest.onAfterSplitBrainHealed(CacheSplitBrainTest.java:182)
```

**Comment by Donnerbart** [comment] 2018-02-02 12:18
**com.hazelcast.cache.merge.CacheSplitBrainTest.testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.PassThroughMergePolicy]**
```java
org.junit.ComparisonFailure: expected:<[PassThroughV]alue1> but was:<[v]alue1>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cache.merge.CacheSplitBrainTest.afterMergePassThroughMergePolicy(CacheSplitBrainTest.java:329)
	at com.hazelcast.cache.merge.CacheSplitBrainTest.onAfterSplitBrainHealed(CacheSplitBrainTest.java:179)
```

**Comment by ahmetmircik** [comment] 2018-02-05 10:19
New failure: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13214/

**Comment by Donnerbart** [comment] 2018-02-05 13:59
Just a note: the test content has completely changed since the new merge policies have been implemented. The old test is `LegacyCacheSplitBrainTest` now (and I assume the fix of Vassilis is still working). The failures since the re-opening from Matko are belonging to the new test.

**Comment by Donnerbart** [comment] 2018-02-06 19:10
I did over 2000 local runs with the `PassThroughMergePolicy`, no failure...

**Comment by mmedenjak** [comment] 2018-02-06 19:39
The `PassThroughMergePolicy` was failing only on my PR so it might have been related to the changes in that PR. It may be interesting to look at why this policy is failing as the changes in the PR are not directly related to either split brain healing nor cache: https://github.com/hazelcast/hazelcast/pull/10416

**Comment by Donnerbart** [comment] 2018-02-07 04:17
The `PassThroughMergePolicy` is also the one failing in the `MapSplitBrainTest` issue. But it's also the first policy which actually merges data in the `@Parameters` list (after the `DiscardMergePolicy`, which has a shortcuts). So if there's a failure scenario, it might just be the first merge policy which is picked up.

**Comment by Donnerbart** [comment] 2018-02-07 12:41
The test is failing very frequently in the PR builder now.

Ignored via https://github.com/hazelcast/hazelcast/commit/0deab3e1b33a5ccaea5439776f6b0cf248dd62a0

**Comment by Donnerbart** [comment] 2018-02-15 11:25
Should be fixed via https://github.com/hazelcast/hazelcast/pull/12348

Test will be re-enabled with the improved SPI design.

**Comment by sancar** [comment] 2018-02-21 08:53
@Donnerbart Tests started to fail again.

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13723/testReport/junit/com.hazelcast.cache.merge/CacheSplitBrainTest/testSplitBrain_format_BINARY__mergePolicy_class_com_hazelcast_spi_merge_PassThroughMergePolicy_/
```

com.hazelcast.cache.merge.CacheSplitBrainTest.testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.PutIfAbsentMergePolicy]

Error Message
expected:<PutIfAbsentValue2> but was:<null>
Stacktrace
java.lang.AssertionError: expected:<PutIfAbsentValue2> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cache.merge.CacheSplitBrainTest.afterMergePutIfAbsentMergePolicy(CacheSplitBrainTest.java:358)
	at com.hazelcast.cache.merge.CacheSplitBrainTest.onAfterSplitBrainHealed(CacheSplitBrainTest.java:175)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13723/

```
com.hazelcast.cache.merge.CacheSplitBrainTest.testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.PassThroughMergePolicy]


Error Message
expected:<[PassThroughV]alue1> but was:<[v]alue1>
Stacktrace
org.junit.ComparisonFailure: expected:<[PassThroughV]alue1> but was:<[v]alue1>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cache.merge.CacheSplitBrainTest.afterMergePassThroughMergePolicy(CacheSplitBrainTest.java:323)
	at com.hazelcast.cache.merge.CacheSplitBrainTest.onAfterSplitBrainHealed(CacheSplitBrainTest.java:173)
```

**Comment by Donnerbart** [comment] 2018-02-21 08:57
See https://github.com/hazelcast/hazelcast/issues/12263#issuecomment-367042697, same root cause. Jaromir will prepare a fix today.

**Closed** 2018-02-21 16:54 UTC
Labels: Interface: ICache, SUPPRESSED, Team: Core, Type: Test-Failure
