### ISSUE TITLE
NullPointerException com.hazelcast.spi.Operation.sendResponse(Operation.java:345)

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11443] opened 2017-09-26 05:25 UTC
Version
INFO: [10.0.0.205]:5701 [HZ] [3.9-SNAPSHOT] Hazelcast Enterprise 3.9-SNAPSHOT (20170925 - 1678248, c2eac8a) starting at [10.0.0.205]:5701

/disk1/jenkins/workspace/freeze-all/3.9-SNAPSHOT/2017_09_25-20_32_09/lock/try-lock
HzMember1HZ/out.txt
```
WARNING: [10.0.0.205]:5701 [HZ] [3.9-SNAPSHOT] While sending op error... op: com.hazelcast.spi.impl.operationparker.impl.ParkedOperation{serviceName='hz:impl:lockService', identityHash=558685333, partitionId=69, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, op=com.hazelcast.concurrent.lock.operations.LockOperation{serviceName='hz:impl:lockService', identityHash=119501154, partitionId=69, replicaIndex=0, callId=-2087233, invocationTime=1506401887394 (2017-09-26 04:58:07.394), waitTimeout=1, callTimeout=10000, namespace=InternalLockNamespace{service='hz:impl:lockService', objectName=try-lock_lock3}, threadId=79}, expirationTime=1506402096790, valid=true}, error: com.hazelcast.spi.exception.WrongTargetException: WrongTarget! this: [10.0.0.205]:5701, target: [10.0.0.237]:5701, partitionId: 69, replicaIndex: 0, operation: com.hazelcast.spi.impl.operationparker.impl.ParkedOperation, service: hz:impl:lockService
java.lang.NullPointerException
	at com.hazelcast.spi.Operation.sendResponse(Operation.java:345)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.sendResponseAfterOperationError(OperationRunnerImpl.java:367)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleOperationError(OperationRunnerImpl.java:361)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:198)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)

Sep 26, 2017 5:04:08 AM com.hazelcast.spi.impl.operationparker.impl.ParkedOperation
WARNING: [10.0.0.205]:5701 [HZ] [3.9-SNAPSHOT] Op: com.hazelcast.concurrent.lock.operations.LockOperation{serviceName='hz:impl:lockService', identityHash=119501154, partitionId=69, replicaIndex=0, callId=-2087233, invocationTime=1506401887394 (2017-09-26 04:58:07.394), waitTimeout=1, callTimeout=10000, namespace=InternalLockNamespace{service='hz:impl:lockService', objectName=try-lock_lock3}, threadId=79}, com.hazelcast.spi.exception.WrongTargetException: WrongTarget! this: [10.0.0.205]:5701, target: [10.0.0.237]:5701, partitionId: 69, replicaIndex: 0, operation: com.hazelcast.spi.impl.operationparker.impl.ParkedOperation, service: hz:impl:lockService
Sep 26, 2017 5:04:08 AM com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl
WARNING: [10.0.0.205]:5701 [HZ] [3.9-SNAPSHOT] While sending op error... op: com.hazelcast.spi.impl.operationparker.impl.ParkedOperation{serviceName='hz:impl:lockService', identityHash=558685333, partitionId=69, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, op=com.hazelcast.concurrent.lock.operations.LockOperation{serviceName='hz:impl:lockService', identityHash=119501154, partitionId=69, replicaIndex=0, callId=-2087233, invocationTime=1506401887394 (2017-09-26 04:58:07.394), waitTimeout=1, callTimeout=10000, namespace=InternalLockNamespace{service='hz:impl:lockService', objectName=try-lock_lock3}, threadId=79}, expirationTime=1506402096790, valid=true}, error: com.hazelcast.spi.exception.WrongTargetException: WrongTarget! this: [10.0.0.205]:5701, target: [10.0.0.237]:5701, partitionId: 69, replicaIndex: 0, operation: com.hazelcast.spi.impl.operationparker.impl.ParkedOperation, service: hz:impl:lockService
java.lang.NullPointerException
	at com.hazelcast.spi.Operation.sendResponse(Operation.java:345)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.sendResponseAfterOperationError(OperationRunnerImpl.java:367)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleOperationError(OperationRunnerImpl.java:361)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:198)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
```

**Comment by mdogan** [comment] 2017-09-26 07:01
Duplicate of #11375

**Closed by mdogan** 2017-09-26 07:01 UTC
Labels: Team: Core, To Triage, Type: Critical, Type: Defect
