### ISSUE TITLE
IMap.set not using Compact Serializer

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast#19323] opened 2021-08-13 14:42 UTC
Tried to use Compact Serialization in my app, but once I call IMap.set, the exception if thrown:
```
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.myapp.SomeClass'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:235)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:211)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:196)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:151)
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:382)
	at com.hazelcast.spi.impl.AbstractDistributedObject.toData(AbstractDistributedObject.java:78)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:251)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:242)
```

Expected behaviour: IMap.set should use compact serializer as well, if one is configured.

My serialization configuration is as simple as:
```
		return new SerializationConfig()
				.setCompactSerializationConfig(new CompactSerializationConfig()
						.setEnabled(true))
```
System: Java 16, Windows 10, IntelliJ IDEA.

Reproduction code:
```java
package com.myexample;

import java.io.Serializable;

import com.hazelcast.config.CompactSerializationConfig;
import com.hazelcast.config.Config;
import com.hazelcast.config.MapConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.map.IMap;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import static com.hazelcast.config.CacheDeserializedValues.NEVER;
import static com.hazelcast.config.InMemoryFormat.BINARY;

public class Test {

	public static void main(String[] args) {
		Config conf = new Config();
		conf.getSerializationConfig().setCompactSerializationConfig(new CompactSerializationConfig().setEnabled(true));

		conf.addMapConfig(dataCacheConf(Entity1.class));
		conf.addMapConfig(dataCacheConf(Entity2.class));
		var hz = Hazelcast.newHazelcastInstance(conf);

		IMap<Integer, Entity1> entity1 = hz.getMap("Entity1");
		IMap<Integer, Entity2> entity2 = hz.getMap("Entity2");

		entity1.set(1, new Entity1(1, "s"));
		entity2.set(1, new Entity2(1, "s2", new Entity3NotSerializable(1)));

		System.out.println(entity1.get(1));
		System.out.println(entity2.get(1));
	}

	private static MapConfig dataCacheConf(Class<?> entityClass) {
		String mapName = entityClass.getSimpleName();
		return new MapConfig(mapName)
				.setCacheDeserializedValues(NEVER)
				.setReadBackupData(true)
				.setInMemoryFormat(BINARY);
	}

	@Data @NoArgsConstructor @AllArgsConstructor
	public static class Entity1 {
		private int id;
		private String s;
	}
	@Data @NoArgsConstructor @AllArgsConstructor
	public static class Entity2 implements Serializable {
		private int id;
		private String s2;
		private Entity3NotSerializable obj;
	}

	@Data @NoArgsConstructor @AllArgsConstructor
	public static class Entity3NotSerializable {
		private int id;
	}

}

```

Results in:
```
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.myexample.Test$Entity2'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:236)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:212)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:197)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:152)
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:382)
	at com.hazelcast.spi.impl.AbstractDistributedObject.toData(AbstractDistributedObject.java:78)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:251)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:242)
	at com.myexample.Test.main(Test.java:40)
```

**Comment by sancar** [comment] 2021-08-13 14:50
Hi @TomaszGaweda There must be something wrong with the configuration. 
This is the most basic setup. It should work. Can you may be share a full reproducer so that we can find the where the problem is ?

**Comment by TomaszGaweda** [comment] 2021-08-13 15:07
Hi @sancar :)

I'm debugging it right now, looks like if type is Serializable, then default Java serialization is used.  When I do ``	.getCompactSerializationConfig().register(clazz);``, then it works for the data classes (still fails on Callables send to all nodes).

**Comment by TomaszGaweda** [comment] 2021-08-16 11:35
Hi @sancar I've included reproduction code. When debugging I discovered that Java Serialization has higher priority than Compact Serialization. I've made proper change in my PR

**Comment by sancar** [comment] 2021-08-16 14:09
@TomaszGaweda Thanks for the pr but Java Serialization is higher priority on purpose. Otherwise it would mean a non-backward compatible change.

**Comment by TomaszGaweda** [comment] 2021-08-16 14:18
I kind of agree, but how it differs from setting other global serializer? If someone used eg. Kryo with SubZero, it was priority no 1. Now she/he wants to switch to Compact and it's just not working, despite declaring in configuration that it should work. It's new global switch, so if user wants backward compatibility, he would stick to compact=false, isn't he?

**Comment by sancar** [comment] 2021-08-16 14:27
The difference is the global serializer will not be enabled by default, by the compact serialization will be enabled by default when it is finalized. 

This would mean that a in 5.0  a serializable class was using java serialization. If we made the change that is proposed here, in
5.x(where the compact is finalized) it will serialized via compact serialization. Imagine a 5.0 member working with a 5.x client. They will not match, and it is not correct. Rolling upgrades will not work in this case either.

**Comment by TomaszGaweda** [comment] 2021-08-16 14:29
Ok, I get it. Is it possible to add some flag for Compact to be new global serializer for every class (just like we can now set global serializer)? For example option `useAsDefault`? If it's ok, I will adjust my PR

**Comment by sancar** [comment] 2021-08-16 14:33
This request came up in the design as well. 
We were kind of hesitant to do that because `Compact` can not really serialize every type of class. Example, if there are maps/collections inside users POJO for example it will not work. Giving this option sounds too promising. But this request is still on the table and we may introduce it at the end.

**Comment by TomaszGaweda** [comment] 2021-08-16 14:35
Makes sense. For now I'll revert that changes from my PR

**Comment by sancar** [comment] 2021-08-16 14:42
Closing this issue for now.

**Closed by sancar** 2021-08-16 14:42 UTC
Labels: Type: Defect, Team: Client, Team: Core, Module: Serialization
