### ISSUE TITLE
healthcheck logs should be disabled by system property

### ISSUE THREAD

**Issue by kloia-hz-daas** [hazelcast/hazelcast#13662] opened 2018-08-29 15:32 UTC
in kubernetes in order to check health of the hazelcast pods we use:

```
          httpGet:
            path: /hazelcast/health/node-state
          periodSeconds: 10
```
then hazelcast prints following logs every 10 seconds:

```
INFO: [10.40.0.8]:30143 [test] [3.10.4] Established socket connection between /10.40.0.8:30143 and /10.40.0.0:50912
INFO: [10.40.0.8]:30143 [test] [3.10.4] Accepting socket connection from /10.40.0.0:50912
INFO: [10.40.0.8]:30143 [test] [3.10.4] Connection[id=109452, /10.40.0.8:30143->/10.40.0.0:50912, endpoint=null, alive=false, type=REST_CLIENT] closed. Reason: Connection closed by the other side
```

generally most libraries/frameworks support silent health check. hazelcast should support it also.

**Comment by mmedenjak** [comment] 2018-08-30 06:27
Duplicate of https://github.com/hazelcast/hazelcast/issues/13537

**Comment by jerrinot** [comment] 2018-09-10 12:27
closing as a duplicate

**Closed by jerrinot** 2018-09-10 12:27 UTC
Labels: Source: Community, Team: Integration
