### ISSUE TITLE
ClientMapStoreTest Timeout

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7011] opened 2015-12-07 10:31 UTC
```
02:37:41 Running com.hazelcast.client.map.ClientMapStoreTest
04:02:32 Build timed out (after 360 minutes). Marking the build as failed.
```

Main reason of aboreted failures is this timeout problem.

Here is the trend for this build:

<img width="332" alt="screen shot 2015-12-07 at 12 27 37" src="https://cloud.githubusercontent.com/assets/6005622/11624642/dd02a960-9cdd-11e5-84ba-b9072aa7d67d.png">

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/686/console

**Comment by mesutcelik** [comment] 2015-12-17 10:25
I think it is back to stable right now. closing.
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/

**Comment by hasancelik** [comment] 2016-01-13 09:46
```
02:28:14 Running com.hazelcast.client.map.ClientMapStoreTest
04:02:36 Build timed out (after 360 minutes). Marking the build as failed.
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/727/console

**Comment by sancar** [comment] 2016-01-14 09:47
Ignoring this failure since new client on maintenance branch is idle and we are not applying fixes there.

**Comment by Donnerbart** [comment] 2017-02-06 23:54
We seem to have this issue back in the current master
```
21:13:28 Running com.hazelcast.client.map.ClientMapStoreTest
02:37:28 Build timed out (after 480 minutes). Marking the build as failed.
02:37:28 
02:37:28 Results :
02:37:28 
02:37:28 Tests run: 1305, Failures: 0, Errors: 0, Skipped: 14
02:37:28 
02:37:28 [ERROR] There was a timeout or other error in the fork
02:37:28 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 6 iota=17
02:37:28 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 6 iota=17
02:37:28 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 9 iota=17
```
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/1394/consoleFull

**Comment by hasancelik** [comment] 2017-02-07 07:59
*from zing builds*

```
16:41:08 Running com.hazelcast.client.map.ClientMapStoreTest
20:39:29 Build timed out (after 600 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/9/consoleFull#269004068748982c6-417b-4fda-b62b-1178aba1bd90

**Comment by sancar** [comment] 2017-02-07 12:47
Test failed because of map store stuck. I am sharing my findings here.

Client stuck on map.get

```
"Thread-1104" 
	java.lang.Thread.State: WAITING, cpu=8782261 nsecs, usr=0 nsecs, blocked=0 msecs, waited=299932 msecs
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:311)
		at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
		at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:351)
		at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:307)
		at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:288)
		at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:647)
		at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getMap(HazelcastClientInstanceImpl.java:462)
		at com.hazelcast.client.impl.HazelcastClientProxy.getMap(HazelcastClientProxy.java:118)
		at com.hazelcast.client.map.ClientMapStoreTest$ClientThread.run(ClientMapStoreTest.java:296)
```

on server map.get stuck on mapstore load for 300 seconds 

```
"hz._hzInstance_1309_dev.client.thread-2" 
	java.lang.Thread.State: TIMED_WAITING, cpu=30681960 nsecs, usr=30000000 nsecs, blocked=0 msecs, waited=299855 msecs
		at java.lang.Thread.sleep(Native Method)
		at java.lang.Thread.sleep(Thread.java:321)
		at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:356)
		at com.hazelcast.map.impl.proxy.MapProxySupport.waitAllTrue(MapProxySupport.java:609)
		at com.hazelcast.map.impl.proxy.MapProxySupport.waitUntilLoaded(MapProxySupport.java:587)
		at com.hazelcast.map.impl.proxy.MapProxyImpl.waitUntilLoaded(MapProxyImpl.java:102)
		at com.hazelcast.map.impl.proxy.MapProxySupport.initializeMapStoreLoad(MapProxySupport.java:220)
		at com.hazelcast.map.impl.proxy.MapProxySupport.initialize(MapProxySupport.java:212)
		at com.hazelcast.map.impl.proxy.MapProxyImpl.initialize(MapProxyImpl.java:102)
		at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:177)
		at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:167)
		at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.initializeDistributedObject(ProxyServiceImpl.java:133)
		at com.hazelcast.spi.impl.proxyservice.impl.operations.InitializeDistributedObjectOperation.run(InitializeDistributedObjectOperation.java:44)
		at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
		at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:382)
		at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:409)
		at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:534)
		at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:519)
		at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:490)
		at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:200)
		at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
		at com.hazelcast.client.impl.protocol.task.AbstractInvocationMessageTask.processMessage(AbstractInvocationMessageTask.java:42)
		at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
		at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:701)
		at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
		at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

**Comment by sancar** [comment] 2017-02-07 12:52
Setting label core to take core teams attention about my mapstore findings.

**Comment by Donnerbart** [comment] 2017-02-07 12:53
Thanks a lot! I'll have a look at the failure.

**Comment by sancar** [comment] 2017-02-07 13:12
Reason of failure is logged here
```
16:43:09,124  INFO |testOneClientKickOffMapStoreLoad_ThenNodeJoins| - [InvocationMonitor] hz._hzInstance_1314_dev.InvocationMonitorThread - [127.0.0.1]:6246 [dev] [3.8-SNAPSHOT] Invocations:15 timeouts:15 backup-timeouts:0
THREAD DUMP FOR TEST FAILURE: "test timed out after 300000 milliseconds" at "testOneClientKickOffMapStoreLoad_ThenNodeJoins"
```

**Comment by Donnerbart** [comment] 2017-02-08 08:48
My findings from yesterday are that `testOneClient_KickOffMapStoreLoad()` will spuriously not finish, but only if all test methods are executed. If I add some debugging output in `MapProxySupport.waitAllTrue()` I can see that the `retrySet` doesn't get smaller:
```
retrySet: [134, 7, 92, 93, 95, 97, 34, 104, 43, 111, 112, 113, 50, 122, 125]
retrySet: [134, 7, 92, 93, 95, 97, 34, 104, 43, 111, 112, 113, 50, 122, 125]
retrySet: [134, 7, 92, 93, 95, 97, 34, 104, 43, 111, 112, 113, 50, 122, 125]
retrySet: [134, 7, 92, 93, 95, 97, 34, 104, 43, 111, 112, 113, 50, 122, 125]
retrySet: [134, 7, 92, 93, 95, 97, 34, 104, 43, 111, 112, 113, 50, 122, 125]
```
I couldn't find the root cause for this though.

**Closed** 2017-02-09 10:01 UTC
Labels: Team: Client, Team: Core, Type: Test-Failure
