### ISSUE TITLE
ClusterViewListener is causing OOME issues in Jet soak test

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#16484] opened 2020-01-15 13:17 UTC
Related to #16482 

Connections are not cleaned up properly and reference to them from `com.hazelcast.client.impl.ClusterViewListenerService.clusterListeningEndpoints` are kept. The keys in the `clusterListeningEndpoints` are `ClientEndpointImpl` instances which have the `connection` field. Majority of these connections is not `alive` anymore.

Each connection keeps a reference to a channel instance, which then holds inbound and outbound pipelines with its buffers.

![image](https://user-images.githubusercontent.com/962661/72435766-eccec600-37af-11ea-8c7a-d39f9f1ebead.png)

![image](https://user-images.githubusercontent.com/962661/72435790-feb06900-37af-11ea-9d0b-8b3408e51c55.png)

I don't know where exactly is the problem with not cleaning the connections properly.

What I expect can go wrong is an exception in processing `pushView` which sends messages to all client endpoints:
https://github.com/hazelcast/hazelcast/blob/fdc6a205b2b6f50e01d21a263c373a0894ad2e67/hazelcast/src/main/java/com/hazelcast/client/impl/ClusterViewListenerService.java#L83-L92

Once it fails (e.g. connection is closed before the write is called), the executor will stop to work:
https://github.com/hazelcast/hazelcast/blob/fdc6a205b2b6f50e01d21a263c373a0894ad2e67/hazelcast/src/main/java/com/hazelcast/client/impl/ClusterViewListenerService.java#L61

**Comment by sancar** [comment] 2020-01-20 06:56
I don't see any problem with the scheduled pushView task. 
If connection is closed, we will simply will not send the message to that connection. Note that `connection.write` does not throw exception. It will return false if it is not able to write to connection.

**Comment by sancar** [comment] 2020-01-23 09:25
We are following the problem in https://github.com/hazelcast/hazelcast/issues/16482. I am closing this one, since this description seems not to be the cause.

**Closed by sancar** 2020-01-23 09:25 UTC
Labels: Team: Client, Team: Core, Type: Defect
