### ISSUE TITLE
Cannot use JCache with existing Hazelcast instance using programmatic configuration when using non default ports

### ISSUE THREAD

**Issue by shahr** [hazelcast/hazelcast#17900] opened 2020-11-28 23:04 UTC
**Describe the bug**
Cannot use JCache with existing Hazelcast instance using programmatic configuration when using non default ports.

**Expected behavior**
According to the [documentation](https://docs.hazelcast.org/docs/latest/manual/html-single/#reusing-an-existing-named-hazelcastinstance), providing the instance name should allow configure the CacheManager correctly to pick up the existing Hazelcast instance.

**To Reproduce**
A simple test as follows:
```
Config config = new Config("my-hz-instance");
config.getNetworkConfig().setPort(5555);
Hazelcast.newHazelcastInstance(config);

CachingProvider cachingProvider = Caching.getCachingProvider();
cachingProvider.getCacheManager(new URI("my-hz-instance"), null);
```
Running that will cause failures. I see SocketExceptions whilst it tries to connect to 5701, 5702 and 5703. Ultimately an exception is thrown `javax.cache.CacheException: Error opening URI [my-hz-instance] ... Caused by: java.lang.IllegalStateException: Unable to connect to any cluster.`

I have also tried using the instance directly as documented [here](https://docs.hazelcast.org/docs/latest/manual/html-single/#binding-to-an-existing-hazelcast-instance-object) but this throw a different exception:
`javax.cache.CacheException: Error opening URI [my-hz-instance] ... Caused by: java.lang.ClassCastException: com.hazelcast.instance.impl.HazelcastInstanceProxy cannot be cast to com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl`
```
Config config = new Config("my-hz-instance");
config.getNetworkConfig().setPort(5555);
HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
Properties properties = new Properties();
properties.put(HazelcastCachingProvider.HAZELCAST_INSTANCE_ITSELF, instance);
CachingProvider cachingProvider = Caching.getCachingProvider();
cachingProvider.getCacheManager(new URI("my-hz-instance"), null, properties);
```

**Additional context**
Note: I'm not using any hazelcast.xml file as I want to manage all the configuration programatically.
I am using hazelcast 4.1 and javax.cache.api 1.1.1 running on Windows with Java 11.

When I do remove the custom ports - everything seems to work fine

**Comment by vbekiaris** [comment] 2020-11-30 11:05
@shahr thanks for the excellent issue report. There are a few different issues at play which result in the behaviour you observe. The short summary is that the code above works as designed but documentation needs to be updated to reflect some subtle changes in Hazelcast 4.0. Read on for the full details:

1. Since Hazelcast 4.0, the client artifact (`hazelcast-client.jar`) was merged into a single binary`hazelcast.jar` which includes code for both Hazelcast member and client. As a result, `Caching.getCachingProvider()` will by default return a client-side `CachingProvider` (as was the case in 3.x when both `hazelcast` and `hazelcast-client` artifacts were in the classpath).

2. Additionally, since 4.0 the `URI` is no longer resolved as instance name (see #15995 for reasoning behind this). It seems documentation still suggests otherwise, I will create an issue to track this on the [ref manual repos](https://github.com/hazelcast/hazelcast-reference-manual/).

Going back to your original code:

- if your intent is to obtain a member-side `CachingProvider` backed by a named member-side `HazelcastInstance`, then you should use `Caching.getCachingProvider(HazelcastCachingProvider.MEMBER_CACHING_PROVIDER)` (supplying explicitly the class name of the member-side caching provider implementation). Then obtain the named instance using `cachingProvider.getCacheManager(null, null, HazelcastCachingProvider.propertiesByInstanceName("my-hz-instance")`. There are a few more options for configuring whether to use the member- or client-side `CachingProvider` documented [here](https://docs.hazelcast.org/docs/latest/manual/html-single/#configuring-jcache-provider). Your full code would look like this:

```
Config config = new Config("my-hz-instance");
config.getNetworkConfig().setPort(5555);
Hazelcast.newHazelcastInstance(config);

CachingProvider cachingProvider = Caching.getCachingProvider(HazelcastCachingProvider.MEMBER_CACHING_PROVIDER);
cachingProvider.getCacheManager(null, null, HazelcastCachingProvider.propertiesByInstanceName("my-hz-instance"));
```

- if you want to obtain a client-side `CachingProvider` that connects to the member started on port 5555, then you need to create a named `ClientConfig`, start the client-side `HazelcastInstance`, then use properties to specify the client-side instance name when getting the `CacheManager`. Full source code:

```
Config config = new Config("my-hz-instance");
config.getNetworkConfig().setPort(5555);
Hazelcast.newHazelcastInstance(config);

// configure & start client-side HazelcastInstance
ClientConfig clientConfig = new ClientConfig();
clientConfig.setInstanceName("client-instance");
clientConfig.getNetworkConfig().addAddress("127.0.0.1:5555");

// the line below by default returns the client-side CachingProvider
CachingProvider cachingProvider = Caching.getCachingProvider();
// obtain a CacheManager backed by the named client instance
CacheManager cacheManager = cachingProvider.getCacheManager(null, null, HazelcastCachingProvider.propertiesByInstanceName("client-instance"));
```

Finally, the `ClassCastException` you notice when using the `HazelcastInstance` object itself, is due to the fact that the client-side `CachingProvider` is attempting to use a member-side `HazelcastInstance`. This is due to mixing member-/client-side `HazelcastInstance` with a client-/member-side `CachingProvider` respectively.

**Closed by vbekiaris** 2020-11-30 11:05 UTC
Labels: Type: Defect

**Comment by vbekiaris** [comment] 2020-11-30 11:09
Created https://github.com/hazelcast/hazelcast-reference-manual/issues/903 to track documentation updates.

**Comment by shahr** [comment] 2020-11-30 15:01
@vbekiaris Thank you very much for the detailed response and examples. This makes perfect sense and I was able to get things working.
