### ISSUE TITLE
[TEST-FAILURE] MapReadQuorumTest Timeout

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5438] opened 2015-06-03 06:53 UTC
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/553/console

**Comment by bilalyasar** [comment] 2015-06-04 10:20
seems cloudbees logs are corrupted, couldn't reproduce it locally.
i am closing this until new failure.

**Closed by bilalyasar** 2015-06-04 10:20 UTC
Labels: Team: Core, Type: Defect
