### ISSUE TITLE
Invocation_NetworkSplitTest

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7931] opened 2016-04-11 06:47 UTC
**testWaitNotifyService_whenNodeSplitFromCluster**
```
java.lang.AssertionError: expected:<0> but was:<89>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest$2.run(Invocation_NetworkSplitTest.java:169)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:871)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:166)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:125)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/171/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitNotifyService_whenNodeSplitFromCluster/

**Comment by Donnerbart** [comment] 2016-04-27 04:20
**testWaitNotifyService_whenNodePartiallySplitFromCluster**

**Error Message**
expected:<4> but was:<3>

**Stacktrace**
```
java.lang.AssertionError: expected:<4> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:178)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodePartiallySplitFromCluster(Invocation_NetworkSplitTest.java:131)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2769/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitNotifyService_whenNodePartiallySplitFromCluster/

**Comment by Donnerbart** [comment] 2016-04-27 07:15
Duplicate of https://github.com/hazelcast/hazelcast/issues/8026

**Closed by Donnerbart** 2016-04-27 07:15 UTC
Labels: Team: Core, Type: Test-Failure
