### ISSUE TITLE
Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7196] opened 2015-12-28 08:54 UTC
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 2
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:694)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:713)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:709)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:704)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:106)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:61)
```

https://hazelcast-l337.ci.cloudbees.com/view/Quality-Outreach/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/283/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by hasancelik** [comment] 2016-01-03 21:56
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/670/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by hasancelik** [comment] 2016-01-04 09:38
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/73/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by muratayan** [comment] 2016-01-11 14:29
I am not able to reproduce the issue, not even with a special build @sancar introduced: 
https://hazelcast-l337.ci.cloudbees.com/job/Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster/

Yet, someone else can look at it or we can close it for now. Because I am going nowhere with this.

**Comment by eminn** [comment] 2016-01-13 14:58
fixed via 5fedbbc66678ae81c24bbfae5aa9c04f965f5d29

**Comment by hasancelik** [comment] 2016-02-08 15:40
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:696)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:715)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:711)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:706)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:108)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:61)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/708/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by hasancelik** [comment] 2016-05-11 09:36
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:67)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:118)
	at com.hazelcast.instance.Node.join(Node.java:639)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:113)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:302)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:105)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:62)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/199/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by mdogan** [comment] 2016-05-11 09:39
merged into https://github.com/hazelcast/hazelcast/issues/8026

**Closed by mdogan** 2016-05-11 09:39 UTC
Labels: Team: Core, Type: Test-Failure
