### ISSUE TITLE
ClientRegressionWithMockNetworkTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7133] opened 2015-12-21 10:22 UTC
**testOperationRedo
testDeadlock_WhenDoingOperationFromLifecycleListener
testNearCache_WhenRegisteredNodeIsDead
testDeadlock_WhenDoingOperationFromLifecycleListener
testDeadlock_WhenDoingOperationFromLifecycleListener_and_NearCache
testClientReconnect_thenCheckRequestsAreRetriedWithoutException**

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/71/

**ClientRegressionWithMockNetworkTest.testClientReconnect_thenCheckRequestsAreRetriedWithoutException**

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/72/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientReconnect_thenCheckRequestsAreRetriedWithoutException/

**Comment by cangencer** [comment] 2015-12-21 10:46
This is the same issue as #6153, so closing this one as a duplicate.

**Comment by cangencer** [comment] 2015-12-21 15:30
On closer inspection,  not all test failures in this were related to classloader deadlock in #6153. However they seem to have the same cause as #7134, so reopening the issue

**Comment by hasancelik** [comment] 2015-12-23 08:15
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/74/

**Comment by cangencer** [comment] 2015-12-23 08:18
Looks like some of these are still failing:

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-ZuluJDK7/lastCompletedBuild/com.hazelcast$hazelcast-client-legacy/testReport/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testDeadlock_WhenDoingOperationFromLifecycleListener_and_NearCache/

**Comment by sancar** [comment] 2015-12-25 09:39
Issue seems to be different. New failures are related to `testDeadLock.*` tests. 
And after the fix #7159, they are also not failing.

**Comment by hasancelik** [comment] 2015-12-29 08:29
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/4279/

**Comment by ihsandemir** [comment] 2015-12-31 11:18
Submitted PR for fixing the last issue: https://github.com/hazelcast/hazelcast/pull/7215

**Closed** 2015-12-31 13:24 UTC
Labels: Team: Client, Type: Test-Failure
