### ISSUE TITLE
IMap's `set` method blocks other unrelated maps

### ISSUE THREAD

**Issue by felipeek** [hazelcast/hazelcast#15979] opened 2019-11-11 16:56 UTC
Hello developers,

We have a `MapStore` that have a `store` implementation that might take some time to run. We did some tests and found out that, for some reason, while the `store` method is being executed, we are not able to access elements of other maps. Hazelcast locks the operation until the `store` is completed.

For instance, if you run the following code: 

```java
HazelcastInstance clientInstance = HazelcastClient.newHazelcastClient(new ClientConfig());
IMap<String, String> map = clientInstance.getMap("MYMAP");
map.set("1", "value");
```

And, in another thread, you run the following code: 

```java
HazelcastInstance clientInstance2 = HazelcastClient.newHazelcastClient(new ClientConfig());
IMap<String, String> map2 = clientInstance2.getMap("MYMAP_DIFFERENT");
map2.get("2");
```

The call `map2.get("2")` is blocked while `map.set` is running.

Also, note that we are accessing two different maps, which makes the behaviour very strange.

In the bottom, I am attaching an example that shows the mentioned behaviour.

We wanted to be able to have access to the distributed memory while `map.set` is running. Shouldn't this be possible?

Thanks!
Felipe

```java
import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.config.Config;
import com.hazelcast.config.MapConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

public class ServerNode {
    private static final String IMMUTABLE_MAP_LOADER_CLASS = "MyMapLoader";

    public static void main(String args[]) throws InterruptedException {
        Config cfg = new Config();
        HazelcastInstance instance = Hazelcast.newHazelcastInstance(cfg);
        HazelcastInstance clientInstance = HazelcastClient.newHazelcastClient(new ClientConfig());

        MapConfig mapWithLoaderConfig = new MapConfig("*");
        mapWithLoaderConfig.getMapStoreConfig().setEnabled(true).setClassName(IMMUTABLE_MAP_LOADER_CLASS);
        cfg.addMapConfig(mapWithLoaderConfig);

        Thread t = new Thread(() -> {
          IMap<String, String> map = clientInstance.getMap("MYMAP");
          System.out.println("********** ADDING VALUE 1 ************ [1]");
          map.set("1", "value");
        });

        t.start();
        Thread.sleep(5000);
        System.out.println("************* DONE SLEEPING... ************* [2]");

        System.out.println("************* GETTING MAP... ************* [3]");
        IMap<String, String> map2 = clientInstance.getMap("MYMAP_DIFFERENT");
        System.out.println("************** GETTING MAP ELEMENT ************ [4]");
        map2.get("2");
        System.out.println("************** DONE GETTING MAP ELEMENT ************ [5]");
    }
}
```

```java
import com.hazelcast.core.MapStore;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

public class MyMapLoader implements MapStore<String, String> {
  @Override
  public String load(String s) {
    return s;
  }

  @Override
  public Map<String, String> loadAll(Collection<String> collection) {
    HashMap<String, String> properties = new HashMap<>();
    for (String key : collection) {
      properties.put(key, load(key));
    }
    return properties;
  }

  @Override
  public Iterable<String> loadAllKeys() {
    return null;
  }

  @Override
  public void store(String s, String s2) {
    while(true){}
  }

  @Override
  public void storeAll(Map<String, String> map) {}
  @Override
  public void delete(String s) {}
  @Override
  public void deleteAll(Collection<String> collection) {}
}
```

Output:
```
********** ADDING VALUE 1 ************ [1]
************* DONE SLEEPING... ************* [2]
************* GETTING MAP... ************* [3]
************** GETTING MAP ELEMENT ************ [4]
```

Hazelcast Version: 3.12.3

**Comment by felipeek** [comment] 2019-11-11 20:17
We did some tests and it seems that this behaviour was introduced in version `3.6`. We tested the code in version `3.5.5` and it worked fine

**Comment by felipeek** [comment] 2019-11-12 13:59
Also, we just found out that if we do a `map2.set` instead of `map2.get`, we are still locked, even with old versions. So moving to an old version is not a possible workaround for us.

Calling `IMap.set` always blocks if another `IMap.set` is running, even for different maps

**Comment by tkountis** [comment] 2019-11-12 14:28
@felipeek have you considered to enable write-behind settings on your map-store?
Effectively you are doing write-though at this point (default behaviour) and if you have a slow store at the very least you will slow down the partition thread that handles the write. This also means that any other operation that must go through the same partition thread will also get delayed (regardless of map).

**Comment by tkountis** [comment] 2019-11-13 16:25
@felipeek any update on that?

**Comment by felipeek** [comment] 2019-11-15 04:20
@tkountis We really needed a way of working with other maps while `map.set` was running, using write-through. Since this does not seem to be possible, we decided to change our design to avoid this situation. So, this is not an issue for us anymore (at least for now).

**Comment by tkountis** [comment] 2019-11-15 10:30
I am closing this issue since this behaviour is by design. The request is noted, and it's a valid concern that we will be most likely address in our future roadmap.

**Closed by tkountis** 2019-11-15 10:30 UTC
Labels: Module: IMap, Team: Core, To Triage

**Comment by felipeek** [comment] 2020-11-11 02:00
@tkountis any update on this? We ran into this problem again

**Comment by mmedenjak** [comment] 2020-11-17 18:16
No change, @felipeek . If you have a "slow" operation (like writing/reading to database), it's best offloaded onto some other thread and not run on the partition thread. We have a diagnostics plugin which can show the latency of some store operations (https://docs.hazelcast.org/docs/latest/manual/html-single/#storelatency) and which can hint at issues like this one.
