### ISSUE TITLE
cp system split brain lock try lock test member OOME 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#22135] opened 2022-09-02 13:21 UTC
Enterprise 5.2-SNAPSHOT (20220901 - c2e4a59, 9ccfa0d) 

http://jenkins.hazelcast.com/view/cp-system/job/cp-all-split/17/console

/disk1/workspace/cp-all-split/5.2-SNAPSHOT/2022_09_02-12_04_46/cp/lock/tryLocker

(base) [ec2-user@ip-10-0-0-252 tryLocker]$ hz-errors

./output/HZ/HzMember5HZBB/HzMember5HZBB.hprof

```
One instance of "com.hazelcast.internal.networking.nio.NioOutboundPipeline" loaded by "jdk.internal.loader.ClassLoaders$AppClassLoader @ 0x80400000" occupies 865,043,896 (45.88%) bytes. The memory is accumulated in one instance of "java.util.concurrent.ConcurrentLinkedQueue$Node", loaded by "<system class loader>", which occupies 191,094,552 (10.14%) bytes.
```

```
One instance of "com.hazelcast.internal.networking.nio.NioOutboundPipeline" loaded by "jdk.internal.loader.ClassLoaders$AppClassLoader @ 0x80400000" occupies 838,033,968 (44.45%) bytes. The memory is accumulated in one instance of "java.util.concurrent.ConcurrentLinkedQueue$Node", loaded by "<system class loader>", which occupies 188,485,008 (10.00%) bytes.
```

**Comment by AyberkSorgun** [comment] 2022-09-02 13:54
@Danny-Hazelcast are you able to reproduce this with 5.1?

**Comment by Danny-Hazelcast** [comment] 2022-09-02 14:30
@AyberkSorgun i think is quite are rare issue,  would need some one to look maybe they can investigate the content of the NioOutboundPipeline see what ops are piling up there ?

**Comment by arodionov** [comment] 2022-09-15 16:18
There are 933 com.hazelcast.internal.nio.Packet instances in a NioOutboundPipeline, that takes 1.7 GB
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1538227/190454649-05011ea8-74dd-4495-a40f-afb97b97769a.png">
but the space wastage comes from ~50 Packet instances 
<img width="698" alt="image" src="https://user-images.githubusercontent.com/1538227/190455131-4e505f8d-f091-4101-a3a5-b81022f1f68f.png">

It seems that inside those Packets are serialised some large object(s) (possible Map - ?)

**Comment by arodionov** [comment] 2022-09-16 09:24
@vbekiaris yes, it looks exactly the same, thanks for the links!
I'll try to deserialize the Packet content, but I should google how to do this ;)
I will write a more detailed analysis of the mechanics of this issue.

**Comment by arodionov** [comment] 2022-09-16 09:49
The `SnaphotEntry` object is the following:
![image](https://user-images.githubusercontent.com/1538227/190611543-ab302f3c-4d5f-4bb1-affb-db603e5a01b7.png)

**Comment by vbekiaris** [comment] 2022-09-16 10:13
thanks @arodionov. Closing as duplicate of #17709 so the issue is tracked in a single place.

**Closed by vbekiaris** 2022-09-16 10:13 UTC
Labels: Type: Defect, Team: Core, Module: CP Subsystem
