### ISSUE TITLE
LocalMapStatsTest.testGetAsyncAndHitsGenerated

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#6885] opened 2015-11-26 14:19 UTC
```
Error Message

expected:<100> but was:<99>
Stacktrace

java.lang.AssertionError: expected:<100> but was:<99>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.LocalMapStatsTest$2.run(LocalMapStatsTest.java:100)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
	at com.hazelcast.map.LocalMapStatsTest.testGetAsyncAndHitsGenerated(LocalMapStatsTest.java:95)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/17122/testReport/junit/com.hazelcast.map/LocalMapStatsTest/testGetAsyncAndHitsGenerated/

**Comment by jerrinot** [comment] 2015-11-27 12:01
It could be caused by async update at https://github.com/jerrinot/hazelcast/blob/d9a67366036b46de5eec5e51088e56d4ce98098e/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxySupport.java#L260

**Comment by metanet** [comment] 2015-11-27 12:02
Are you sure? That line doesn't update hit count

**Comment by jerrinot** [comment] 2015-11-27 12:47
not yet 100%. however when I comment this line out then the test is consistently failing.

**Comment by gurbuzali** [comment] 2015-11-27 12:58
I've an idea, when you call `map.getLocalMapStats()` it will create onDemandStats which has `hits` in it.
So while creating those onDemandStats `IncrementStatsExecutionCallback` isn't run yet ?
and since we don't call `map.getLocalMapStats()` for each check, it will never get updated ?

**Comment by jerrinot** [comment] 2015-11-27 12:59
yeah, that's the rough idea.

**Comment by gurbuzali** [comment] 2015-11-27 13:01
so just move `map.getLocalMapStats()` call into assert eventually block ?

**Comment by jerrinot** [comment] 2015-11-27 13:02
that would help to fix the test failure. but is it what we want (contract-wise)? eventually consistent local stats?

**Comment by metanet** [comment] 2015-11-27 13:07
I don't think that there is something like "strongly consistent stats". While some parts of the stats are being calculated, other parts are likely to be updated already. Locking the whole map for just calculating stats is not an option to me, unless it is required explicitly. 

You are right about ``map.getLocalStats()``. I will move it into the ``assertTrueEventually`` block. Other than that, I have found another thread safety issue. Some fields in ``RecordStatisticsImpl`` and ``AbstractRecord`` are not being read in a thread-safe manner. 

I will send a PR fixing these issues.

**Comment by gurbuzali** [comment] 2015-11-27 13:09
I also think we shouldn't try to provide a strict local-stats for an `async` call. The thing we can do is mentioning this in documentation

**Comment by jerrinot** [comment] 2015-11-27 13:12
@metanet I was thinking about something like quiescent consistency -> we could probably guarantee that without locking. anyway, I agree the current semantic is sufficient. I'm assigning this to @metanet as he is working on the PR.

**Closed** 2015-11-29 21:25 UTC
Labels: Team: Core, Type: Test-Failure
