### ISSUE TITLE
Client is shutting down exception in hazelcast 3.3.3

### ISSUE THREAD

**Issue by sgulati89** [hazelcast/hazelcast#4665] opened 2015-02-24 09:16 UTC
Hi, 

We are receiving following exception in hazelcast 3.3.3

java.lang.RuntimeException: com.hazelcast.core.HazelcastException: Client is shutting down!!! at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:128) at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:99) at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) at backtype.storm.daemon.executor$fn__3441$fn__3453$fn__3500.invoke(executor.clj:748) at backtype.storm.util$async_loop$fn__464.invoke(util.clj:463) at clojure.lang.AFn.run(AFn.java:24) at java.lang.Thread.run(Thread.java:744) Caused by: com.hazelcast.core.HazelcastException: Client is shutting down!!! at com.hazelcast.client.connection.nio.ClientConnection.innerClose(ClientConnection.java:302) at com.hazelcast.client.connection.nio.ClientConnection.close(ClientConnection.java:355) at com.hazelcast.client.connection.nio.ClientConnection.close(ClientConnection.java:230) at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.shutdown(ClientConnectionManagerImpl.java:248) at com.hazelcast.client.ClientOutOfMemoryHandler$ClientHelper.closeSockets(ClientOutOfMemoryHandler.java:54) at com.hazelcast.client.ClientOutOfMemoryHandler$ClientHelper.cleanResources(ClientOutOfMemoryHandler.java:45) at com.hazelcast.client.ClientOutOfMemoryHandler.onOutOfMemory(ClientOutOfMemoryHandler.java:34) at com.hazelcast.instance.OutOfMemoryErrorDispatcher.onOutOfMemory(OutOfMemoryErrorDispatcher.java:143) at com.hazelcast.nio.serialization.SerializationServiceImpl.handleException(SerializationServiceImpl.java:348) at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:268) at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl$ResponseThread.process(ClientInvocationServiceImpl.java:225) at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl$ResponseThread.doRun(ClientInvocationServiceImpl.java:218) at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl$ResponseThread.run(ClientInvocationServiceImpl.java:195) at ------ End remote and begin local stack-trace ------.(Unknown Source) at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:194) at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:136) at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:113) at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:110) at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:180) at com.aeris.storm.components.alert.DeviceFeederBolt.execute(DeviceFeederBolt.java:124) at backtype.storm.daemon.executor$fn__3441$tuple_action_fn__3443.invoke(executor.clj:633) at backtype.storm.daemon.executor$mk_task_receiver$fn__3364.invoke(executor.clj:401) at backtype.storm.disruptor$clojure_handler$reify__1447.onEvent(disruptor.clj:58) at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:125) ... 6 more

Also , we have observed that memory consumption increases on hazelcast with number of connections and also with sql predicate.

There is another observation that memory usage does not come down even if all connections are killed.

Please provide some insights on this

**Comment by hasancelik** [comment] 2015-02-25 08:04
Thanks for reporting your issue. Please share with us the following information, to help us resolve your issue quickly and efficiently.
* **Hazelcast configuration** (hazelcast.xml or programmatic configuration)
* **Cluster topology**
  * Number of Hazelcast member nodes
  * Number of Hazelcast clients
* **Java version** (also JVM parameters can be added)
* **Operating System** (for Linux kernel version will be helpful)
* **Logs and Stack Traces** (if available)
* **Steps to reproduce** (detailed description of steps to reproduce your issue)
  * Unit Test (if you can include a unit test which reproduces your issue, we would be grateful)

**Comment by sgulati89** [comment] 2015-02-25 10:23
Thanks for your response. Here are the details:

**Hazelcast Configuration:**

```xml
     <tcp-ip enabled="true">
                                  <member>node1</member>
                                <member>node2</member>
                        </tcp-ip>
 <executor-service>
                <core-pool-size>16</core-pool-size>
                <max-pool-size>64</max-pool-size>
                <keep-alive-seconds>60</keep-alive-seconds>
        </executor-service>
   <properties>
                <property name="hazelcast.executor.client.thread.count">200</property>
                <property name="hazelcast.jmx">true</property>
        </properties>
<map name="hazelMap">
                <near-cache>
                        <invalidate-on-change>true</invalidate-on-change>
                        <max-size>1000000</max-size>
                </near-cache>
                <backup-count>0</backup-count>
                <async-backup-count>1</async-backup-count>
                <read-backup-data>true</read-backup-data>
                <eviction-policy>NONE</eviction-policy>
        </map>

```

**Cluster topology:**

Number of Hazelcast member nodes : 2
Number of Hazelcast clients: 50 +

**Java version :**  1.7.0_51
**Jvm parameters: ** java -Xmx25g -XX:+UseConcMarkSweepGC -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60


**Operating System :**  Ubuntu 14.04.1 LTS(kernel 3.13.0-40-generic )

**Logs and Stack Traces:**  Exception is already added in description

**Steps to reproduce:**  We have around 4 million entries in map. We are seeing this exception when we try to execute some sql predicates.

We have implemented kryo serilization in hazelcast

**Comment by pveentjer** [comment] 2015-03-02 06:49
Have you made a heap dump and made some analysis where there could be a memory leak? I'm a lazy guy and like good tooling. I normally use JProfiler for heap dumps since it allows for aggregation options so quickly discover the path to a memory leak.

**Comment by sancar** [comment] 2015-11-20 15:48
@sgulati89 
Closing this one. If you have more information to provide, please reopen.

**Closed by sancar** 2015-11-20 15:48 UTC
Labels: Team: Client, Team: Core
