### ISSUE TITLE
SQL Sink handling of JSON field ordering

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#21304] opened 2022-04-23 17:09 UTC
**Describe the bug**
Keys that are JSON composites are not tested for equivalence

An SQL Sink  constructs a key with fields in the order defined in the mapping.
A key is created with `field1` then `field2`.

However, this does not detect if the same key exists with `field2` then `field1`

**Expected behavior**
Existing key should be overwritten

**To Reproduce**

```
	private static final String SOURCE_MAP = "source";
	private static final String SINK_MAP = "sink";

	public static void main(String[] args) throws Exception {
		Config config = new Config();
		config.getJetConfig().setEnabled(true);
		
		HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);

		for (String mapName : List.of(SOURCE_MAP, SINK_MAP)) {
			String mapping = "CREATE MAPPING " + mapName
                    + " ("
                    + "    \"firstname\" VARCHAR EXTERNAL NAME \"__key.firstname\","
                    + "    \"lastname\" VARCHAR EXTERNAL NAME \"__key.lastname\","
                    + "    \"this\" VARCHAR"
                    + ")"
    				+ " TYPE IMap "
                    + " OPTIONS ( "
    		        + " 'keyFormat' = 'json-flat',"
    		        + " 'valueFormat' = 'java',"
    		        + " 'valueJavaClass' = '" + String.class.getName() + "'"
                    + " )";
    		hazelcastInstance.getSql().execute(mapping);
		}

		String key = "{\"lastname\":\"Doe\",\"firstname\":\"John\"}"; 
		hazelcastInstance.getMap(SOURCE_MAP).set(new HazelcastJsonValue(key), "written-to-" + SOURCE_MAP);
		hazelcastInstance.getMap(SINK_MAP).set(new HazelcastJsonValue(key), "written-to-" + SINK_MAP);
		
		hazelcastInstance.getSql().execute("SINK INTO " + SINK_MAP + " SELECT * FROM " + SOURCE_MAP);
		
		String sql = "SELECT COUNT(1) FROM " + SINK_MAP
				+ " WHERE firstname = 'John' AND lastname = 'Doe'";
		System.out.println(hazelcastInstance.getSql().execute(sql).iterator().next().getObject(0).toString());
		
		hazelcastInstance.getMap(SINK_MAP).entrySet().forEach(System.out::println);

		hazelcastInstance.shutdown();
	}
```

then try
```
		hazelcastInstance.getSql().execute("SINK INTO " + SINK_MAP + " SELECT lastname, firstname, this FROM " + SOURCE_MAP);
```

**Additional context**
Tested with Hazelcast Platform 5.2-SNAPSHOT (20220422 - 5be7255)
Related https://github.com/hazelcast/hazelcast/issues/21303

**Comment by neilstevenson** [comment] 2022-04-23 17:10
Map keys are considered distinct at the binary level.

However, you can have two entries with the same key fields created and viewed as different objects.

`SELECT * FROM m WHERE keyField1 = x AND keyField2 = y` should not return greater than 1 SqlRow

**Comment by viliam-durina** [comment] 2022-04-25 07:19
This follows from the fact that:
```java
        System.out.println(
                new HazelcastJsonValue("{\"a\":0}")
                        .equals(new HazelcastJsonValue("{\"a\":0}")));
        System.out.println(
                new HazelcastJsonValue("{\"a\":0}")
                        .equals(new HazelcastJsonValue("{\"a\": 0}")));
```
Prints:
```
true
false
```
In the 2nd case, the objects differ only in whitespace.

There is no canonical representation of JSON, instead, it is compared char by char. Even in javascript `{} == {}` returns false; the `==` operator for objects compares references, not values. For example, 
```
o1 = {};
o2 = {}; 
o3 = o1;
console.log(o1 == o2);
console.log(o1 == o3);
```
prints:
```
false
true
```

So I think this behavior in SQL is "as designed".

**Comment by viliam-durina** [comment] 2022-04-25 07:27
More reasoning why we can't fix this: Imagine that in SQL we implemented that JSON values with the same fields and values will be equal. Then it could happen that a SELECT by `__key` would return multiple rows, because the user can insert two entries with same fields and values, but a different string representation, through different API. UPDATE by that key will update multiple entries too.

In this context I reaffirm the design principle of SQL in HZ: we should not fix issues of the underlying structures in SQL. If we want to fix this, then we have to fix it in the IMap implementation, and then SQL will reflect it.

Another note: if you inserted all the data through SQL, then I think the objects will be always serialized in the same way, and your use case will work. However, through SQL you still can do `INSERT INTO foo(__key, ...) VALUES (CAST('whatever string' AS JSON), ...)` and break this assumption.

I'm closing this issue now, reopen, if you don't agree.

**Closed by viliam-durina** 2022-04-25 07:27 UTC
Labels: Type: Defect, Source: Internal, Team: SQL
