### ISSUE TITLE
Member is not started correctly when AWS join + public IP is configured for advanced network

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14709] opened 2019-03-18 11:17 UTC
In case when AWS join and public IP (through `<public-address>`) is used for member endpoint (`member-server-socket-endpoint-config`) in advanced network on AWS then member is not able to start correctly.

**Comment by vbekiaris** [comment] 2019-03-20 10:38
Actually this issue is not related to advanced network config. It seems related to this change https://github.com/hazelcast/hazelcast/commit/21cf7b8ea9b7b9ce5b9098b7d3d4e46725072a2a#diff-fb245e855ae859c129d6876ed8160ddbL136

- with 3.11.x when all join addresses have been (re-)tried , then member starts standalone
- with current `master` member keeps retrying endlessly
- with https://github.com/hazelcast/hazelcast/commit/8b0a17f574591f61440d9ac8a2b37f0f3977aa09 (parent of above commit), member starts standalone as in 3.11.x

**Comment by mmedenjak** [comment] 2019-03-20 11:12
The behaviour of the TcpIpJoiner was aligned with the multicast joiner. Now, it will actually give up but after a much longer time (`GroupProperty#MAX_JOIN_SECONDS`).

Would you say that the combination of a AWS joiner and a public address is a valid one? What I'm aiming at, if it is invalid, we have agreed that the behaviour change to retry for `GroupProperty#MAX_JOIN_SECONDS` before shutting down is ok (in difference to 3.11.x where the member would start standalone).

**Comment by vbekiaris** [comment] 2019-03-20 12:53
> Would you say that the combination of a AWS joiner and a public address is a valid one?

No, I thought it was unexpected that the member did not start standalone. Since this is the intended behavior, I am happy to close this issue.

**Closed by vbekiaris** 2019-03-20 12:53 UTC
Labels: Module: Network I/O, Source: Internal, Team: Core

**Comment by mmedenjak** [comment] 2019-03-20 13:04
Yes, in the case of misconfiguration for a cluster (e.g. incompatible join mechanisms...) we agreed it is ok to change the behaviour to shut down.
