### ISSUE TITLE
ClientMapNearCacheBasicTest.testNearCacheMemoryCostCalculation

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10420] opened 2017-04-24 08:30 UTC
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 987) (NearCacheStatsImpl{ownedEntryCount=987, ownedEntryMemoryCost=146976, creationTime=1492693160925, hits=0, misses=1000, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<987>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:271)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$2.run(NearCacheTestUtils.java:291)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:288)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.testNearCacheMemoryCostCalculation(AbstractNearCacheBasicTest.java:959)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.testNearCacheMemoryCostCalculation(AbstractNearCacheBasicTest.java:924)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/362/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheBasicTest/testNearCacheMemoryCostCalculation_format_BINARY_/

**Comment by Donnerbart** [comment] 2017-04-24 08:43
Duplicate of https://github.com/hazelcast/hazelcast/issues/10420

**Closed by Donnerbart** 2017-04-24 08:43 UTC
Labels: Team: Client, Team: Core, Type: Test-Failure
