### ISSUE TITLE
NPE in Processor.close()

### ISSUE THREAD

**Issue by gierlachg** [hazelcast/hazelcast#19209] opened 2021-07-28 12:06 UTC
```
14:04:51,114 ERROR || - [ExecutionContext] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] job '068f-7f0f-a46c-0001', execution 068f-7f0f-a46c-0001 encountered an exception in Processor.close(), ignoring it
java.lang.NullPointerException: null
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.close(ProcessorTasklet.java:628) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:246) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$559b0d71$1(JobExecutionService.java:524) ~[classes/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[classes/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:498) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:524) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.lambda$beginExecution0$14(JobExecutionService.java:572) ~[classes/:?]
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) [?:1.8.0_281]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_281]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) [?:1.8.0_281]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) [?:1.8.0_281]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) [?:1.8.0_281]
```

**Comment by viliam-durina** [comment] 2021-07-28 12:22
`ProcessorTasklet.close()` called from non-processor thread. I can imagine this happening only if the processor thread was concurrently running this tasklet, but that should not happen.

Any chance you have a reproducer? Or a thread dump?

**Comment by gierlachg** [comment] 2021-07-28 12:28
Unfortunately, experienced just once so far while testing one thing so don't have neither of them...

**Comment by gierlachg** [comment] 2021-08-19 11:30
Another occurrence https://github.com/hazelcast/hazelcast/issues/19368

**Comment by Danny-Hazelcast** [comment] 2021-08-19 11:41
easily reproducible  with https://github.com/hazelcast/hazelcast/issues/19368

**Comment by mmedenjak** [comment] 2021-08-23 18:53
Closing as a duplicate of https://github.com/hazelcast/hazelcast/issues/19368 which seems to have a reproducer.

**Closed by mmedenjak** 2021-08-23 18:53 UTC
Labels: Type: Defect, Team: Core, Source: Internal, Module: Jet
