### ISSUE TITLE
com.hazelcast.map.BackupTest.testBackupRemoveWhenOwnerNodeDead

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18806] opened 2021-05-31 06:38 UTC
_4.2.z_ (commit e22aab3cffbb36863a91276dd2506b4fcf4a7f6c)

Failed on IBM JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-IbmJDK8/148/testReport/com.hazelcast.map/BackupTest/testBackupRemoveWhenOwnerNodeDead/

This happened even if `CPU shares = 8` was configured.

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1048)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1339)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:288)
	at com.hazelcast.map.BackupTest.testBackupRemoveWhenOwnerNodeDead(BackupTest.java:344)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

Standard output:
```
13:46:57,668  INFO |testBackupRemoveWhenOwnerNodeDead| - [InvocationMonitor] hz.cocky_cannon.InvocationMonitorThread - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Invocations:1 timeouts:1 backup-timeouts:0
13:49:54,673  INFO |testBackupRemoveWhenOwnerNodeDead| - [LifecycleService] Thread-25358 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
13:49:54,673  WARN |testBackupRemoveWhenOwnerNodeDead| - [Node] Thread-25358 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Terminating forcefully...
13:49:54,673  INFO |testBackupRemoveWhenOwnerNodeDead| - [Node] Thread-25358 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Shutting down connection manager...
13:49:54,673  INFO |testBackupRemoveWhenOwnerNodeDead| - [Node] Thread-25358 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Shutting down node engine...
13:49:57,675  INFO |testBackupRemoveWhenOwnerNodeDead| - [NodeExtension] Thread-25358 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Destroying node NodeExtension.
13:49:57,675  INFO |testBackupRemoveWhenOwnerNodeDead| - [Node] Thread-25358 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Hazelcast Shutdown is completed in 3002 ms.
13:49:57,676  INFO |testBackupRemoveWhenOwnerNodeDead| - [LifecycleService] Thread-25358 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
13:49:57,676  INFO |testBackupRemoveWhenOwnerNodeDead| - [LifecycleService] Thread-25358 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
13:49:57,676  INFO |testBackupRemoveWhenOwnerNodeDead| - [Node] Thread-25358 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
13:49:57,676  INFO |testBackupRemoveWhenOwnerNodeDead| - [LifecycleService] Thread-25358 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testBackupRemoveWhenOwnerNodeDead(com.hazelcast.map.BackupTest): BuildInfo{version='4.2.1-SNAPSHOT', build='20210530', buildNumber=20210530, revision=e22aab3, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testBackupRemoveWhenOwnerNodeDead(com.hazelcast.map.BackupTest):'
13:44:50, accumulated pauses: 98 ms, max pause: 57 ms, pauses over 1000 ms: 0
13:44:55, accumulated pauses: 456 ms, max pause: 74 ms, pauses over 1000 ms: 0
13:45:00, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:05, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:10, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:15, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:20, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:25, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:30, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:35, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:40, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:45, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:50, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:45:55, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:00, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:05, accumulated pauses: 51 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:10, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:15, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:20, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:25, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:30, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:35, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:40, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:45, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:50, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:46:55, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:47:00, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:47:05, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:47:10, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:47:15, accumulated pauses: 51 ms, max pause: 11 ms, pauses over 1000 ms: 0
13:47:20, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:47:25, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:47:30, accumulated pauses: 45 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:47:35, accumulated pauses: 51 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:47:40, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:47:45, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:47:50, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:47:55, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:48:00, accumulated pauses: 42 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:48:05, accumulated pauses: 50 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:48:10, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:48:15, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:48:20, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:48:25, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:48:30, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:48:35, accumulated pauses: 48 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:48:40, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:48:45, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:48:50, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:48:55, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:49:00, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:49:05, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:49:10, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:49:15, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:49:20, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:49:25, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:49:30, accumulated pauses: 515 ms, max pause: 479 ms, pauses over 1000 ms: 0
13:49:35, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:49:40, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:49:45, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:49:50, accumulated pauses: 55 ms, max pause: 19 ms, pauses over 1000 ms: 0
13:49:55, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment] 2021-08-04 07:17
Closing as a duplicate of https://github.com/hazelcast/hazelcast/issues/1325. Basically these tests are almost identical. I don't understand if we really need both tests.

**Closed by mmedenjak** 2021-08-04 07:17 UTC
Labels: Module: IMap, Source: Internal, Team: Core, Type: Test-Failure
