### ISSUE TITLE
Failed to connect to: http://hazelcast-dev-new-mancenter:8080/hazelcast-mancenter/collector.do

### ISSUE THREAD

**Issue by Srinivasa381224** [hazelcast/hazelcast#16239] opened 2019-12-12 07:12 UTC
Hi, am sri I have installed hazelcast using helm in my eks cluster in dev namespace previously its running 2 members and 1 mancentre after we are try to deploy another 2 members and 1 mancentre with some different name in same namespace But i getting some errors in the members log files Please help me for this

Hazelcast Member logs are
`
 exec java -server -javaagent:/opt/hazelcast/lib/jmx_prometheus_javaagent.jar=8080:/opt/hazelcast/jmx_agent_config.yaml -Dhazelcast.mancenter.enabled=false -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/opt/hazelcast/logging.properties -Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=hazelcast-dev-new -Dnamespace=dev -Dhazelcast.mancenter.enabled=true -Dhazelcast.mancenter.url=http://hazelcast-dev-new-mancenter:8080/hazelcast-mancenter -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=600 -Dhazelcast.jmx=true com.hazelcast.core.server.StartServer
`

```
Dec 12, 2019 6:18:39 AM com.hazelcast.config.AbstractConfigLocator
INFO: Loading configuration '/data/hazelcast/hazelcast.yaml' from System property 'hazelcast.config'
Dec 12, 2019 6:18:39 AM com.hazelcast.config.AbstractConfigLocator
INFO: Using configuration file at /data/hazelcast/hazelcast.yaml
Dec 12, 2019 6:18:40 AM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.12] Prefer IPv4 stack is true, prefer IPv6 addresses is false
Dec 12, 2019 6:18:40 AM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.12] Picked [10.30.59.125]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
Dec 12, 2019 6:18:40 AM com.hazelcast.system
INFO: [10.30.59.125]:5701 [dev] [3.12] Hazelcast 3.12 (20190409 - 915d83a) starting at [10.30.59.125]:5701
Dec 12, 2019 6:18:40 AM com.hazelcast.system
INFO: [10.30.59.125]:5701 [dev] [3.12] Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
Dec 12, 2019 6:18:40 AM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [10.30.59.125]:5701 [dev] [3.12] Backpressure is disabled
Dec 12, 2019 6:18:40 AM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [10.30.59.125]:5701 [dev] [3.12] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: hazelcast-dev-new, service-port: 0, service-label: null, service-label-value: true, namespace: dev, resolve-not-ready-addresses: true, kubernetes-master: https://kubernetes.default.svc}
Dec 12, 2019 6:18:40 AM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [10.30.59.125]:5701 [dev] [3.12] Kubernetes Discovery activated resolver: KubernetesApiEndpointResolver
Dec 12, 2019 6:18:40 AM com.hazelcast.instance.Node
INFO: [ip]:5701 [dev] [3.12] Activating Discovery SPI Joiner
Dec 12, 2019 6:18:41 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [ip]:5701 [dev] [3.12] Starting 2 partition threads and 3 generic threads (1 dedicated for priority tasks)
Dec 12, 2019 6:18:41 AM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [ip]:5701 [dev] [3.12] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Dec 12, 2019 6:18:41 AM com.hazelcast.core.LifecycleService
INFO: [ip]:5701 [dev] [3.12] [ip]:5701 is STARTING
Dec 12, 2019 6:18:41 AM com.hazelcast.kubernetes.KubernetesClient
WARNING: Cannot fetch public IPs of Hazelcast Member PODs, you won't be able to use Hazelcast Smart Client from outside of the Kubernetes network
Dec 12, 2019 6:18:47 AM com.hazelcast.internal.cluster.ClusterService
INFO: [ip]:5701 [dev] [3.12] 

Members {size:1, ver:1} [
        Member [ip]:5701 - 45c847bc-cd06-43eb-b2bb-709f2e849e3f this
]

Dec 12, 2019 6:18:47 AM com.hazelcast.internal.management.ManagementCenterService
INFO: [ip]:5701 [dev] [3.12] Hazelcast will connect to Hazelcast Management Center on address: 
http://hazelcast-dev-new-mancenter:8080/hazelcast-mancenter
Dec 12, 2019 6:18:47 AM com.hazelcast.internal.jmx.ManagementService
INFO: [ip]:5701 [dev] [3.12] Hazelcast JMX agent enabled.
Dec 12, 2019 6:18:47 AM com.hazelcast.core.LifecycleService
INFO: [ip]:5701 [dev] [3.12] [ip]:5701 is STARTED
Dec 12, 2019 6:18:52 AM com.hazelcast.internal.management.ManagementCenterService
INFO: [ip]:5701 [dev] [3.12] Failed to connect to: http://hazelcast-dev-new-mancenter:8080/hazelcast-mancenter/collector.do
Dec 12, 2019 6:18:52 AM com.hazelcast.client.impl.ClientEngine
INFO: [ip]:5701 [dev] [3.12] Applying a new client selector :ClientSelector{any}
Dec 12, 2019 6:19:20 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [ip]:5701 [dev] [3.12] Initialized new cluster connection between /ip:5701 and /10.30.39.9:44171
Dec 12, 2019 6:19:20 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [ip]:5701 [dev] [3.12] Connection[id=4, /ip:5701->/ip:43528, qualifier=null, endpoint=null, alive=false, type=NONE] closed. Reason: Unsupported command received on REST API handler.
Dec 12, 2019 6:19:26 AM com.hazelcast.internal.cluster.ClusterService
INFO: [ip]:5701 [dev] [3.12] 

Members {size:2, ver:2} [
        Member [ip]:5701 - 45c847bc-cd06-43eb-b2bb-709f2e849e3f this
        Member [ip]:5701 - c95eae99-b779-42a5-bf34-d21dd4bc64ae
]

Dec 12, 2019 6:19:37 AM com.hazelcast.internal.management.ManagementCenterService
INFO: [ip]:5701 [dev] [3.12] Connection to Management Center restored.
Dec 12, 2019 6:19:37 AM com.hazelcast.client.impl.ClientEngine
INFO: [ip]:5701 [dev] [3.12] Applying a new client selector :ClientSelector{any}
Dec 12, 2019 6:20:20 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [ip]:5701 [dev] [3.12] Connection[id=17, /10.30.59.125:5701->/ip:44708, qualifier=null, endpoint=null, alive=false, type=NONE] closed. Reason: Unsupported command received on REST API handler.
Dec 12, 2019 6:20:57 AM com.hazelcast.internal.management.ManagementCenterService
INFO: [ip]:5701 [dev] [3.12] Failed to pull tasks from Management Center
Dec 12, 2019 6:21:20 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [ip]:5701 [dev] [3.12] Connection[id=30, /ip:5701->/ip:46236, qualifier=null, endpoint=null, alive=false, type=NONE] closed. Reason: Unsupported command received on REST API handler.
Dec 12, 2019 6:22:20 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [ip]:5701 [dev] [3.12] Connection[id=43, /ip:5701->/ip:47788, qualifier=null, endpoint=null, alive=false, type=NONE] closed. Reason: Unsupported command received on REST API handler.
Dec 12, 2019 6:23:20 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [ip]:5701 [dev] [3.12] Connection[id=56, /ip:5701->/ip:49416, qualifier=null, endpoint=null, alive=false, type=NONE] closed. Reason: Unsupported command received on REST API handler.
Dec 12, 2019 6:24:20 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [ip]:5701 [dev] [3.12] Connection[id=69, /ip:5701->/10.30.52.177:51034, qualifier=null, endpoint=null, alive=false, type=NONE] closed. Reason: Unsupported command received on REST API handler.
```

**Comment by mesutcelik** [comment] 2019-12-12 11:48
duplicate of https://github.com/hazelcast/charts/issues/86

**Closed by mesutcelik** 2019-12-12 11:48 UTC
Labels: Team: Integration, Team: Management Center
