### ISSUE TITLE
SlowOperationDetector_EntryProcessorTest.testSlowEntryProcessor

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16108] opened 2019-11-26 10:33 UTC
maintenance (commit f9c7665b6c207f385536e02af5f0cee258874d48)

Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-sonar/305/testReport/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetector_EntryProcessorTest/testSlowEntryProcessor/

**Stacktrace**
```
java.lang.AssertionError: Expected 4 total invocations, but was 3. Log: {"operation":"com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperation","stackTrace":"java.lang.Thread.sleep(Native Method)\n\tjava.lang.Thread.sleep(Thread.java:340)\n\tjava.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)\n\tcom.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:413)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest$SlowEntryProcessor.process(SlowOperationDetectorAbstractTest.java:212)\n\tcom.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:337)\n\tcom.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:185)\n\tcom.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:169)\n\tcom.hazelcast.map.impl.operation.PartitionWideEntryOperation.run(PartitionWideEntryOperation.java:83)\n\tcom.hazelcast.spi.Operation.call(Operation.java:170)\n\tcom.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)\n\tcom.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)\n\tcom.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)\n\tcom.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:177)\n\tcom.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:131)\n\tcom.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)","totalInvocations":3,"invocations":[{"id":1985468806,"details":"com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperation{serviceName='hz:impl:mapService', identityHash=1985468806, partitionId=80, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, name=dc72f795-6549-42b3-b266-0db3f0ed0da7, entryProcessor=SlowEntryProcessor{instance=22, sleepSeconds=3}, predicate=TruePredicate{}}","startedAt":1574725044696,"durationMs":2001},{"id":2091889398,"details":"com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperation{serviceName='hz:impl:mapService', identityHash=2091889398, partitionId=80, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, name=dc72f795-6549-42b3-b266-0db3f0ed0da7, entryProcessor=SlowEntryProcessor{instance=18, sleepSeconds=3}, predicate=TruePredicate{}}","startedAt":1574725038692,"durationMs":2004},{"id":861227304,"details":"com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperation{serviceName='hz:impl:mapService', identityHash=861227304, partitionId=80, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, name=dc72f795-6549-42b3-b266-0db3f0ed0da7, entryProcessor=SlowEntryProcessor{instance=23, sleepSeconds=6}, predicate=TruePredicate{}}","startedAt":1574725047698,"durationMs":5000}]} expected:<4> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsStringFormat(HazelcastTestSupport.java:1437)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.assertTotalInvocations(SlowOperationDetectorAbstractTest.java:129)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector_EntryProcessorTest.testSlowEntryProcessor(SlowOperationDetector_EntryProcessorTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by petrpleshachkov** [comment] 2019-11-27 14:23
I made an analysis of this test failure and concluded that it relates to the slow/unresponsive environment. The `SlowOperationDetector_EntryProcessorTest` runs a few tests in parallel in the same JVM. The failing test instantiates `hzInstance_3696`.

`23:37:25,697  WARN |testSlowEntryProcessor| - [SlowOperationDetector] hz._hzInstance_3696_dev.SlowOperationDetectorThread - [127.0.0.1]:5701 [dev] [3.12.5-SNAPSHOT] Slow operation detected: com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperation (2 invocations)
`
We see in the stack traces output that  `SlowOperationDetectorThread` of this instance is in a TIMED_WAITING state for 15247 msecs. So, the thread is sleeping much more than expected. But the test sets this value to 1 second and the default value is 10 secs. 
```
"hz._hzInstance_3696_dev.SlowOperationDetectorThread" 
	java.lang.Thread.State: TIMED_WAITING, cpu=11747322 nsecs, usr=10000000 nsecs, blocked=0 msecs, waited=15247 msecs
		at java.lang.Thread.sleep(Native Method)
		at java.lang.Thread.sleep(Thread.java:340)
		at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
		at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.sleepInterval(SlowOperationDetector.java:290)
		at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.run(SlowOperationDetector.java:154)
```
There are some other threads sleeping for 15+ seconds. Though, I don't see high hiccups in the report I still suspect the environment is a culprit. I am not able to reproduce the failure on my local machine. 
I incline to close the issue. @tezc , @mmedenjak WDYT, guys?

**Comment by mmedenjak** [comment] 2019-11-27 14:37
Yes, I'm inclined to do so as well. You can also make the test use small instances. But overall, I'm disheartened by the amount of tests failing because of large pauses. Other examples (not to mention the TTL and expiration tests I see failing on a daily basis on the PR builder):

https://github.com/hazelcast/hazelcast-enterprise/issues/3353#issuecomment-555622967
https://github.com/hazelcast/hazelcast-enterprise/issues/2837#issuecomment-549773097

**Comment by tezc** [comment] 2019-11-27 22:47
Isn't that sleep time accumulated value? That 15 seconds sleeps are expected as we are sleeping intentionally 3 times 3 seconds + 1 time 6 seconds = 15 seconds in the test. So, it looks normal to me.

I feel like issue is in somewhere else, still might be related with timing but I don't see high hiccups in the logs.

**Closed** 2019-11-28 08:05 UTC
Labels: Source: Internal, Team: Core, Type: Test-Failure
