### ISSUE TITLE
ClientXATest.testRecovery

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14739] opened 2019-03-22 07:25 UTC
_master_ (commit c9fd2b48bd1834f0a3b1c1a034c0da7800ceee0a)

Failed on nightly build: http://jenkins.hazelcast.com/job/Hazelcast-3.x-nightly/56/testReport/com.hazelcast.client.txn/ClientXATest/testRecovery/

Stacktrace:
```
java.lang.AssertionError: expected:<value> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.txn.ClientXATest.testRecovery(ClientXATest.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment] 2019-03-22 07:52
Similar behaviour as [here](https://github.com/hazelcast/hazelcast-enterprise/issues/2862#issuecomment-475517934). I'm suspecting an isolation issue with tests running multicast.

**Comment by mmedenjak** [comment] 2019-03-22 09:45
Closing as duplicate of the above. Please see the explanation in the other issue.

**Closed by mmedenjak** 2019-03-22 09:45 UTC
Labels: Team: Core, Type: Test-Failure
