### ISSUE TITLE
Null value on compute remove

### ISSUE THREAD

**Issue by ffortier** [hazelcast/hazelcast#7020] opened 2015-12-07 18:57 UTC
We have 2 hazelcast instances running on a cron job. If the cron fires the two operations in the same time, I get a race conditions that breaks hazelcast.

```
java.lang.NullPointerException: Null value is not allowed!
	at com.hazelcast.util.Preconditions.checkNotNull(Preconditions.java:41) ~[hazelcast-3.5.3.jar!/:3.5.3]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.remove(MapProxyImpl.java:186) ~[hazelcast-3.5.3.jar!/:3.5.3]
	at java.util.concurrent.ConcurrentMap.compute(ConcurrentMap.java:426) ~[na:1.8.0_45]
```

It looks like when the compute get the `oldValue`, that value is null, then my operation returns null and hazelcast check the value again and determine it's a remove. The `containsKey` is now true with a `oldValue` still null and it fails.

**Comment by pveentjer** [comment] 2015-12-07 19:48
Can you create a test that reproduces the problem?

The exception itself is valid since you are no allowed to call remove with a null value.

**Comment by ffortier** [comment] 2015-12-07 21:00
I can try, but to comment on the validity of this exception, I would like to draw you attention on the line 424 of ConcurentMap:

```java
                if (oldValue != null || containsKey(key)) { // line 424
                    // something to remove
                    if (remove(key, oldValue)) {
                        // removed the old value as expected
                        return null;
                    }
```

if `oldValue` was null on the last get (which is possible because because it was done few line above) and `containsKey` now returns true (which is also possible if another process adds an entry in the map after the current thread has gotten null) then if will remove a null value and fail. Maybe the exception is valid, but it's not working with this function.

**Comment by pveentjer** [comment] 2015-12-08 07:45
Which class are you referring to? ConcurrentMap is an interface.

**Comment by jerrinot** [comment] 2015-12-08 09:58
This sounds like a bug in default implementation of ConcurrentMap::compute.

According to its contract the default method implementation assumes the map implementation does not support null values - this is indeed case of Hazelcast map. 

This is the start of the default implementation of `compute()` from `ConcurrentMap` : 
```java
default V compute(K key,
            BiFunction<? super K, ? super V, ? extends V> remappingFunction) {
        Objects.requireNonNull(remappingFunction);
        V oldValue = get(key);
        for(;;) {
            V newValue = remappingFunction.apply(key, oldValue);
            if (newValue == null) {
                // delete mapping
                if (oldValue != null || containsKey(key)) {
                    // something to remove
                    if (remove(key, oldValue)) {
[...]
```

Let's say we have an empty map and 2 threads: 
T1 is calling the `compute('foo', someFunction)`
T2 is concurrently calling calling `put('foo', 'bar');`

so the T1 will get `oldValue = null`, but `containsKey()` will return `true` - because T2 already created the mapping `foo -> bar`. Hence T1 will call `remove('foo', null)` !

Contract of `remove()` says: `throws NullPointerException if the specified key or value is null, and this map does not permit null keys or values optional.` -> the `compute()` method will result in NPE. 

I'll send an email to the (Java) core-libs mailing list and let's see what people over there think about it. In any case: Many thanks for reporting this issue!

**Comment by jerrinot** [comment] 2015-12-08 11:50
http://mail.openjdk.java.net/pipermail/core-libs-dev/2015-December/037372.html

**Comment by jerrinot** [comment] 2015-12-09 11:26
Paul Sandoz [confirmed](http://mail.openjdk.java.net/pipermail/core-libs-dev/2015-December/037432.html) it's a bug in JDK 8.

I'm closing this issue as it has to be fixed in OpenJDK project. 

@ffortier: I do not know your use-case, but I'd recommend to use entry processor to update values if you can.

**Closed by jerrinot** 2015-12-09 11:26 UTC
Labels: Team: Core

**Comment by jerrinot** [comment] 2015-12-15 11:56
upstream bug: https://bugs.openjdk.java.net/browse/JDK-8145164
