### ISSUE TITLE
NodeJs App Fails When Main Member Dies

### ISSUE THREAD

**Issue by markserrano915** [hazelcast/hazelcast#14868] opened 2019-04-13 18:12 UTC
I have followed the map example in the Hazelcast intro page for NodeJs, Python, and Java.
I got a cluster of Hazelcast with two nodes running under Docker.

All apps work fine. When I kill the main member in the cluster, Python and Java is able to recognize the remaining member and is able to return the distributed map value. But the NodeJs app throws an exception. It's complaining that it can't see the `address: '127.0.0.1', port: 5701` which is understandable since I killed it. But it fails to see the other member.

NodeJs app
```
var Client = require('hazelcast-client').Client;

const distributeMapName = 'my-distributed-map';
const key = "todays-date";

Client.newHazelcastClient().then(function (hz) {
    hz.getMap(distributeMapName).then(function (map) {
        return Promise.resolve(map);
    }).then(function (map) {
        return map.get(key);
    }).then(function (value) {
        console.log(value)
        hz.shutdown();
    });
});

```

Python app
```
import hazelcast
import logging

if __name__ == '__main__':
    logging.basicConfig(format='%(asctime)s%(msecs)03d [%(name)s] %(levelname)s: %(message)s', datefmt="%H:%M%:%S,")
    logging.getLogger().setLevel(logging.INFO)
    logger = logging.getLogger("main")

    distribute_map_name = 'my-distributed-map'
    key = 'todays-date'

    hz = hazelcast.HazelcastClient()
    map = hz.get_map(distribute_map_name)
    value = map.get(key).result()
    print(value)
    hz.shutdown()    
```

Java app
```
package sample.app;

import com.hazelcast.client.HazelcastClient;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

public class App {
    
    public static void main(String[] args) {

        String distributedMapName = "my-distributed-map";
        String key = "todays-date";

        HazelcastInstance hz = HazelcastClient.newHazelcastClient();
        IMap<String, String> map = hz.getMap(distributedMapName);
        String value = map.get(key);
        System.out.println(value);
        hz.shutdown();
    }
}
```

Here's the NodeJS exception:
```
[DefaultLogger] WARN at ClientConnectionManager: Could not connect to address localhost:5701
{ Error: connect ECONNREFUSED 127.0.0.1:5701
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5701 }
[DefaultLogger] WARN at ClusterService: Error: connect ECONNREFUSED 127.0.0.1:5701
[DefaultLogger] WARN at ClientConnectionManager: Could not connect to address localhost:5701
{ Error: connect ECONNREFUSED 127.0.0.1:5701
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5701 }
[DefaultLogger] WARN at ClusterService: Error: connect ECONNREFUSED 127.0.0.1:5701
[DefaultLogger] ERROR at HazelcastClient: Client failed to start
{ Error: Unable to connect to any of the following addresses: localhost:5701
    at new IllegalStateError (/Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/hazelcast-client/lib/HazelcastError.js:73:28)
    at ClusterService.tryConnectingToAddresses (/Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/hazelcast-client/lib/invocation/ClusterService.js:217:29)
    at /Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/hazelcast-client/lib/invocation/ClusterService.js:240:30
    at tryCatcher (/Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mserrano/Documents/workspaces/simple-apps/simple-hazelcast/node-app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
  cause: 
   { Error: connect ECONNREFUSED 127.0.0.1:5701
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 5701 } }
```

Python logs
```
python main.py 
Apr 13, 2019 01:08:50 PM HazelcastClient
INFO: [3.11] [dev] [hz.client_0] A non-empty group password is configured for the Hazelcast client. Starting with Hazelcast IMDG version 3.11, clients with the same group name, but with different group passwords (that do not use authentication) will be accepted to a cluster. The group password configuration will be removed completely in a future release.
13:08:50,085 [HazelcastClient] INFO: [dev] [hz.client_0] A non-empty group password is configured for the Hazelcast client. Starting with Hazelcast IMDG version 3.11, clients with the same group name, but with different group passwords (that do not use authentication) will be accepted to a cluster. The group password configuration will be removed completely in a future release.
Apr 13, 2019 01:08:50 PM HazelcastClient.LifecycleService
INFO: [3.11] [dev] [hz.client_0] (20190319 - 3b38a46) HazelcastClient is STARTING
13:08:50,085 [HazelcastClient.LifecycleService] INFO: [dev] [hz.client_0] (20190319 - 3b38a46) HazelcastClient is STARTING
Apr 13, 2019 01:08:50 PM HazelcastClient.ClusterService
INFO: [3.11] [dev] [hz.client_0] Connecting to Address(host=127.0.0.1, port=5701)
13:08:50,091 [HazelcastClient.ClusterService] INFO: [dev] [hz.client_0] Connecting to Address(host=127.0.0.1, port=5701)
Apr 13, 2019 01:08:50 PM HazelcastClient.ClusterService
WARNING: [3.11] [dev] [hz.client_0] Error connecting to Address(host=127.0.0.1, port=5701) 
Traceback (most recent call last):
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/cluster.py", line 124, in _connect_to_cluster
    self._connect_to_address(address)
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/cluster.py", line 171, in _connect_to_address
    connection = f.result()
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/future.py", line 227, in result
    six.reraise(self._exception.__class__, self._exception, self._traceback)
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/six.py", line 689, in reraise
    raise value
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/connection.py", line 114, in get_or_connect
    network_config=self._client.config.network_config)
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/reactor.py", line 100, in new_connection
    connection_closed_callback, message_callback, network_config, self._logger_extras)
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/reactor.py", line 140, in __init__
    self.connect(self._address)
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/asyncore.py", line 342, in connect
    raise OSError(err, errorcode[err])
ConnectionRefusedError: [Errno 61] ECONNREFUSED
13:08:50,428 [HazelcastClient.ClusterService] WARNING: [dev] [hz.client_0] Error connecting to Address(host=127.0.0.1, port=5701) 
Traceback (most recent call last):
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/cluster.py", line 124, in _connect_to_cluster
    self._connect_to_address(address)
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/cluster.py", line 171, in _connect_to_address
    connection = f.result()
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/future.py", line 227, in result
    six.reraise(self._exception.__class__, self._exception, self._traceback)
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/six.py", line 689, in reraise
    raise value
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/connection.py", line 114, in get_or_connect
    network_config=self._client.config.network_config)
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/reactor.py", line 100, in new_connection
    connection_closed_callback, message_callback, network_config, self._logger_extras)
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/site-packages/hazelcast/reactor.py", line 140, in __init__
    self.connect(self._address)
  File "/Users/mserrano/.pyenv/versions/3.7.2/lib/python3.7/asyncore.py", line 342, in connect
    raise OSError(err, errorcode[err])
ConnectionRefusedError: [Errno 61] ECONNREFUSED
Apr 13, 2019 01:08:50 PM HazelcastClient.ClusterService
INFO: [3.11] [dev] [hz.client_0] Connecting to Address(host=127.0.0.1, port=5702)
13:08:50,466 [HazelcastClient.ClusterService] INFO: [dev] [hz.client_0] Connecting to Address(host=127.0.0.1, port=5702)
Apr 13, 2019 01:08:50 PM HazelcastClient.ConnectionManager
INFO: [3.11] [dev] [hz.client_0] Authenticated with <hazelcast.reactor.AsyncoreConnection connected 127.0.0.1:5702 at 0x103801518>
13:08:50,517 [HazelcastClient.ConnectionManager] INFO: [dev] [hz.client_0] Authenticated with <hazelcast.reactor.AsyncoreConnection connected 127.0.0.1:5702 at 0x103801518>
Apr 13, 2019 01:08:50 PM HazelcastClient.ClusterService
INFO: [3.11] [dev] [hz.client_0] New member list:

Members [1] {
        Member [192.168.1.15]:5702 - ac8811ab-b687-467e-8ea4-5b7994c69847
}

13:08:50,520 [HazelcastClient.ClusterService] INFO: [dev] [hz.client_0] New member list:

Members [1] {
        Member [192.168.1.15]:5702 - ac8811ab-b687-467e-8ea4-5b7994c69847
}

Apr 13, 2019 01:08:50 PM HazelcastClient.LifecycleService
INFO: [3.11] [dev] [hz.client_0] (20190319 - 3b38a46) HazelcastClient is CONNECTED
13:08:50,520 [HazelcastClient.LifecycleService] INFO: [dev] [hz.client_0] (20190319 - 3b38a46) HazelcastClient is CONNECTED
Apr 13, 2019 01:08:50 PM HazelcastClient
INFO: [3.11] [dev] [hz.client_0] Client started.
13:08:50,520 [HazelcastClient] INFO: [dev] [hz.client_0] Client started.
foo
Apr 13, 2019 01:08:50 PM HazelcastClient.LifecycleService
INFO: [3.11] [dev] [hz.client_0] (20190319 - 3b38a46) HazelcastClient is SHUTTING_DOWN
13:08:50,526 [HazelcastClient.LifecycleService] INFO: [dev] [hz.client_0] (20190319 - 3b38a46) HazelcastClient is SHUTTING_DOWN
Apr 13, 2019 01:08:50 PM HazelcastClient.AsyncoreReactor
WARNING: [3.11] [dev] [hz.client_0] Connection closed by server
13:08:50,526 [HazelcastClient.AsyncoreReactor] WARNING: [dev] [hz.client_0] Connection closed by server
Apr 13, 2019 01:08:50 PM HazelcastClient.LifecycleService
INFO: [3.11] [dev] [hz.client_0] (20190319 - 3b38a46) HazelcastClient is SHUTDOWN
13:08:50,526 [HazelcastClient.LifecycleService] INFO: [dev] [hz.client_0] (20190319 - 3b38a46) HazelcastClient is SHUTDOWN
Apr 13, 2019 01:08:50 PM HazelcastClient
INFO: [3.11] [dev] [hz.client_0] Client shutdown.
13:08:50,526 [HazelcastClient] INFO: [dev] [hz.client_0] Client shutdown.
```

Java logs
```
./gradlew clean ru
n

> Task :run
Apr 13, 2019 1:08:54 PM com.hazelcast.config.AbstractConfigLocator
INFO: Loading 'hazelcast-client-default.xml' from the classpath.
Apr 13, 2019 1:08:54 PM com.hazelcast.client.HazelcastClient
INFO: hz.client_0 [dev] [3.12] A non-empty group password is configured for the Hazelcast client. Starting with Hazelcast version 3.11, clients with the same group name, but with different group passwords (that do not use authentication) will be accepted to a cluster. The group password configuration will be removed completely in a future release.
Apr 13, 2019 1:08:54 PM com.hazelcast.client.spi.ClientInvocationService
INFO: hz.client_0 [dev] [3.12] Running with 2 response threads, dynamic=false
Apr 13, 2019 1:08:54 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [3.12] HazelcastClient 3.12 (20190409 - 915d83a) is STARTING
Apr 13, 2019 1:08:54 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [3.12] HazelcastClient 3.12 (20190409 - 915d83a) is STARTED
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.hazelcast.internal.networking.nio.SelectorOptimizer (file:/Users/mserrano/.gradle/caches/modules-2/files-2.1/com.hazelcast/hazelcast/3.12/26d682f8f01024c2f2992b08ffb241ff3ca098e5/hazelcast-3.12.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of com.hazelcast.internal.networking.nio.SelectorOptimizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Apr 13, 2019 1:08:55 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [dev] [3.12] Trying to connect to cluster with name: dev
Apr 13, 2019 1:08:55 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [dev] [3.12] Trying to connect to [127.0.0.1]:5701 as owner member
Apr 13, 2019 1:08:55 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [dev] [3.12] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5701
Apr 13, 2019 1:08:55 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [dev] [3.12] Trying to connect to [127.0.0.1]:5703 as owner member
Apr 13, 2019 1:08:55 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [dev] [3.12] Exception during initial connection to [127.0.0.1]:5703: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5703
Apr 13, 2019 1:08:55 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [dev] [3.12] Trying to connect to [127.0.0.1]:5702 as owner member
Apr 13, 2019 1:08:55 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [dev] [3.12] Setting ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:58759->/127.0.0.1:5702}, remoteEndpoint=[192.168.1.15]:5702, lastReadTime=2019-04-13 13:08:55.098, lastWriteTime=2019-04-13 13:08:55.096, closedTime=never, connected server version=3.12} as owner with principal ClientPrincipal{uuid='31644906-f9a4-4f90-8398-bdde587416ab', ownerUuid='ac8811ab-b687-467e-8ea4-5b7994c69847'}
Apr 13, 2019 1:08:55 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [dev] [3.12] Authenticated with server [192.168.1.15]:5702, server version:3.12 Local address: /127.0.0.1:58759
Apr 13, 2019 1:08:55 PM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: hz.client_0 [dev] [3.12] 

Members [1] {
        Member [192.168.1.15]:5702 - ac8811ab-b687-467e-8ea4-5b7994c69847
}

Apr 13, 2019 1:08:55 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [3.12] HazelcastClient 3.12 (20190409 - 915d83a) is CLIENT_CONNECTED
Apr 13, 2019 1:08:55 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: hz.client_0 [dev] [3.12] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
foo
Apr 13, 2019 1:08:55 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [3.12] HazelcastClient 3.12 (20190409 - 915d83a) is SHUTTING_DOWN
Apr 13, 2019 1:08:55 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [dev] [3.12] Removed connection to endpoint: [192.168.1.15]:5702, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:58759->/127.0.0.1:5702}, remoteEndpoint=[192.168.1.15]:5702, lastReadTime=2019-04-13 13:08:55.240, lastWriteTime=2019-04-13 13:08:55.239, closedTime=2019-04-13 13:08:55.245, connected server version=3.12}
Apr 13, 2019 1:08:55 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [3.12] HazelcastClient 3.12 (20190409 - 915d83a) is SHUTDOWN
```

Is this a problem with the NodeJs Hazelcast library or it's a problem of the given hello-world "map" example?

**Comment by sancar** [comment] 2019-04-15 16:12
This is because port guessing feature is not available on nodejs client yet. 
You can set the number of possible member addresses via config beforehand as a workaround.

**Comment by markserrano915** [comment] 2019-04-15 16:15
Thanks @sancar for the info

**Comment by mdumandag** [comment] 2019-04-16 08:23
Port guessing feature is available on the nodejs client but other ports are not tried because DefaultAddressProvider pushes `localhost:5701` to the address list. [See here.](https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/src/connection/DefaultAddressProvider.ts#L39) It should be just the `localhost`. I will send a fix for that

**Comment by mdumandag** [comment] 2021-02-11 15:36
Closing this since the issue is related to the Node.js client (and it is already fixed there)

**Closed by mdumandag** 2021-02-11 15:36 UTC
Labels: Priority: High, Source: Community, Team: Client, Type: Defect
