### ISSUE TITLE
[TEST-FAILURE] ClientMapNearCacheTest.testServerMapExpiration_doesNotInvalidateClientNearCache

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6486] opened 2015-10-18 16:54 UTC
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.map.ClientMapNearCacheTest$6.run(ClientMapNearCacheTest.java:541)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:828)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:842)
	at com.hazelcast.client.map.ClientMapNearCacheTest.testServerMapExpiration_doesNotInvalidateClientNearCache(ClientMapNearCacheTest.java:536)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast-client-new/3903/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testServerMapExpiration_doesNotInvalidateClientNearCache/

**Comment by hasancelik** [comment] 2015-10-18 17:15
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/com.hazelcast$hazelcast-client/692/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testServerMapExpiration_doesNotInvalidateClientNearCache/

**Comment by ahmetmircik** [comment] 2015-10-19 08:03
Fix attempt via https://github.com/hazelcast/hazelcast/commit/11be05660a096922893c51683a25e11fba923193

**Comment by hasancelik** [comment] 2015-10-26 11:52
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-client-legacy/704/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testServerMapExpiration_doesNotInvalidateClientNearCache/

**Comment by hasancelik** [comment] 2015-11-02 07:34
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast-client-legacy/240/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testServerMapExpiration_doesNotInvalidateClientNearCache/

**Comment by ahmetmircik** [comment] 2015-11-02 20:08
closed via https://github.com/hazelcast/hazelcast/commit/cd2204fcc3926acfa532860be390015a4bf82cc9

**Comment by hasancelik** [comment] 2015-11-16 08:40
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.client.map.ClientMapNearCacheTest.testServerMapExpiration_doesNotInvalidateClientNearCache(ClientMapNearCacheTest.java:639)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast-client-legacy/21/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testServerMapExpiration_doesNotInvalidateClientNearCache/

**Comment by hasancelik** [comment] 2015-11-17 13:36
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast-client/301/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testServerMapExpiration_doesNotInvalidateClientNearCache/

**Comment by hasancelik** [comment] 2015-11-17 13:40
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client-legacy/624/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testServerMapExpiration_doesNotInvalidateClientNearCache/

**Comment by ahmetmircik** [comment] 2015-11-17 17:43
it should be fixed by https://github.com/hazelcast/hazelcast/commit/2940f76485c8accfcc43137829bc601e9972f250

**Comment by hasancelik** [comment] 2015-11-18 08:24
@ahmetmircik  It failed again despite the fix.
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.client.map.ClientMapNearCacheTest.testServerMapExpiration_doesNotInvalidateClientNearCache(ClientMapNearCacheTest.java:639)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/lab-fast-pr/74/testReport/junit/com.hazelcast.client.partitionservice/ClientPartitionLostListenerTest/test_partitionLostListener_removed/

**Comment by hasancelik** [comment] 2015-11-19 13:13
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/626/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testServerMapExpiration_doesNotInvalidateClientNearCache/

**Comment by hasancelik** [comment] 2015-11-20 08:28
https://hazelcast-l337.ci.cloudbees.com/view/Quality-Outreach/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-client/246/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testServerMapExpiration_doesNotInvalidateClientNearCache/

**Comment by Donnerbart** [comment] 2015-11-20 09:27
Hopefully fixed permanently via #6733.

**Comment by hasancelik** [comment] 2015-12-09 15:09
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.testServerMapExpiration_doesNotInvalidateClientNearCache(ClientMapNearCacheTest.java:593)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/59/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/testServerMapExpiration_doesNotInvalidateClientNearCache/

**Comment by Donnerbart** [comment] 2015-12-15 11:56
I enhanced the assert message a bit, but I have no clue why the test was failing. I inserted a pause of 31 Minutes before the failed assert, and the test still passed. Could not reproduce it with high repeat count either. Please re-open if it fails again.

**Closed by Donnerbart** 2015-12-15 11:56 UTC
Labels: Team: Client, Type: Test-Failure
