### ISSUE TITLE
com.hazelcast.config.ConfigurationException: Cannot add a dynamic configuration 

### ISSUE THREAD

**Issue by shashanka981** [hazelcast/hazelcast#17016] opened 2020-05-27 18:53 UTC
**Describe the bug**

Our application is running hazelcast  in C/S mode, both client and server with hazelcast-enterprise-3.11.5 version. Application version is being rolling upgraded from v1 to v2 - note app is being upgraded, not the hazelcast.  While one of the app servers in cluster is being rolled over from v1 to v2, we see below exception while doing **clientInstance.getConfig().addMapConfig** .  I do not see any change in difference for mapConfiguration across application versions

Caused by: com.hazelcast.config.ConfigurationException: Cannot add a dynamic configuration 'MapConfig{name='PresenceDataGrid', inMemoryFormat=BINARY', backupCount=1, asyncBackupCount=0, timeToLiveSeconds=0, maxIdleSeconds=0, evictionPolicy='NONE', mapEvictionPolicy='null', evictionPercentage=25, minEvictionCheckMillis=100, maxSizeConfig=MaxSizeConfig{maxSizePolicy='PER_NODE', size=2147483647}, readBackupData=false, hotRestart=HotRestartConfig{enabled=false, fsync=false}, nearCacheConfig=null, mapStoreConfig=MapStoreConfig{enabled=false, className='null', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}, wanReplicationRef=null, entryListenerConfigs=[], mapIndexConfigs=[], mapAttributeConfigs=[MapAttributeConfig{name='presenceattribute'extractor='com.pega.pegarules.cluster.internal.presence.holders.PresenceUserAttributeExtractor'}], quorumName=null, queryCacheConfigs=null, cacheDeserializedValues=INDEX_ONLY}' as there is already a conflicting configuration 'MapConfig{name='PresenceDataGrid', inMemoryFormat=BINARY', backupCount=1, asyncBackupCount=0, timeToLiveSeconds=0, maxIdleSeconds=0, evictionPolicy='NONE', mapEvictionPolicy='null', evictionPercentage=25, minEvictionCheckMillis=100, maxSizeConfig=MaxSizeConfig{maxSizePolicy='PER_NODE', size=2147483647}, readBackupData=false, hotRestart=HotRestartConfig{enabled=false, fsync=false}, nearCacheConfig=null, mapStoreConfig=MapStoreConfig{enabled=false, className='null', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}, wanReplicationRef=null, entryListenerConfigs=[], mapIndexConfigs=[], mapAttributeConfigs=[MapAttributeConfig{name='presenceattribute'extractor='com.pega.platform.presence.datastore.hz.PresenceUserAttributeExtractor'}], quorumName=null, queryCacheConfigs=[], cacheDeserializedValues=INDEX_ONLY}'
"	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.checkCurrentConfigNullOrEqual(ClusterWideConfigurationService.java:410) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.registerConfigLocally(ClusterWideConfigurationService.java:368) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.internal.dynamicconfig.AddDynamicConfigOperation.run(AddDynamicConfigOperation.java:48) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.spi.Operation.call(Operation.java:170) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:413) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at ------ submitted from ------.(Unknown Source) ~[?:?]"
"	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_171]"
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_171]"
"	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_171]"
"	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at ------ submitted from ------.(Unknown Source) ~[?:?]"
"	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96) ~[hazelcast-enterprise-client-3.11.5.jar:3.11.5]"
"	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33) ~[hazelcast-enterprise-client-3.11.5.jar:3.11.5]"
"	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162) ~[hazelcast-enterprise-3.11.5.jar:3.11.5]"
"	at com.hazelcast.client.impl.clientside.ClientDynamicClusterConfig.invoke(ClientDynamicClusterConfig.java:1239) ~[hazelcast-enterprise-client-3.11.5.jar:3.11.5]"
"	at com.hazelcast.client.impl.clientside.ClientDynamicClusterConfig.addMapConfig(ClientDynamicClusterConfig.java:159) ~[hazelcast-enterprise-client-3.11.5.jar:3.11.5]"

**Expected behavior**
I see some issues in GitHub which are similar to this. https://github.com/hazelcast/hazelcast/issues/12222 

I would like to understand if this is a known issue with hazelcast and if so, a fix is already fixed in 3.11.5 version or not

**Comment by vbekiaris** [comment] 2020-05-28 09:14
@shashanka981 thanks for reporting this issue. I can see there is a problem with `null` vs empty `QueryCacheConfig`s in the output you posted.

While we analyze the root cause and consider potential fixes, if you are absolutely certain that your map configs are same, you can workaround the issue by starting your hazelcast members JVM with the option `-Dhazelcast.dynamicconfig.ignore.conflicts=true`. Notice that this option will make Hazelcast assume there is never a conflict between dynamic config and existing configs, so use with care.

**Comment by vbekiaris** [comment] 2020-05-29 07:16
@shashanka981 actually the new map config does conflict the existing one. Notice that the name of the extractor class was changed:

original: 
MapAttributeConfig{name='presenceattribute'extractor='com.pega.pegarules.cluster.internal.presence.holders.PresenceUserAttributeExtractor'}

modified:
MapAttributeConfig{name='presenceattribute'extractor='com.pega.platform.presence.datastore.hz.PresenceUserAttributeExtractor'}

so the Hazelcast member properly rejects the conflicting config. Closing this issue.

**Closed by vbekiaris** 2020-05-29 07:16 UTC
Labels: Module: Config, Team: Core, Type: Defect
