### ISSUE TITLE
com.hazelcast.jet.config.JobConfigTest.when_mutatingLockedJobConfig_then_fail

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23838] opened 2023-03-06 11:00 UTC
_master_ (commit 83371a644146617653c1e5a83c72a04264b4175c)

Failed on openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/121/testReport/junit/com.hazelcast.jet.config/JobConfigTest/when_mutatingLockedJobConfig_then_fail/
<details><summary>Stacktrace:</summary>

```
junit.framework.AssertionFailedError: 
Unexpected io.github.classgraph.ClassGraphException exception type thrown with message:
Uncaught exception during scan
	at com.hazelcast.test.HazelcastTestSupport.assertThrows(HazelcastTestSupport.java:1479)
	at com.hazelcast.jet.config.JobConfigTest.when_mutatingLockedJobConfig_then_fail(JobConfigTest.java:276)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_jobConfigForLightJob in 0.168 seconds.
BuildInfo right after when_mutatingLockedJobConfig_then_fail(com.hazelcast.jet.config.JobConfigTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230304', buildNumber=20230304, revision=83371a6, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_mutatingLockedJobConfig_then_fail(com.hazelcast.jet.config.JobConfigTest):'
07:18:10, accumulated pauses: 81 ms, max pause: 31 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11/121/

**Comment by orcunc** [comment] 2023-03-24 09:01
The same problem happens for https://github.com/hazelcast/hazelcast-enterprise/issues/5786. 
The problem is this exception coming from classgraph library
`Cannot use reflection after ScanResult has been closed`

It seems the race condition in the classgraph library has been fixed with
https://github.com/classgraph/classgraph/issues/757

We are using version 4.8.157 of the classgraph library now. I hope the new version of the library fixes everything. Therefore I am going to close this ticket

**Closed by orcunc** 2023-03-24 09:01 UTC
Labels: Type: Test-Failure, Source: Internal, Module: Jet, Team: Platform
