### ISSUE TITLE
IdGenerator may be reset if creating node is lost

### ISSUE THREAD

**Issue by markathomas** [hazelcast/hazelcast#7051] opened 2015-12-10 19:43 UTC
We use an IdGenerator in our product in lieu of a database sequence value.  Today at a customer the value of the IdGenerator appeared to randomly reset.  I have written a simple test case to reproduce this issue.  Here are the steps to reproduce:
1. Compile and run test case with an integer argument (e.g. java -cp . TestIdGenerator 184699)
2. Run a second instance with a smaller number (e.g. java -cp . TestIdGenerator 1)
3. Stop the first instance
The second instance has now reverted to a value lower than the previous value. I expect that the second instance would continue with incremental ids since the entire cluster was not restarted as is detailed in the docs but this is not the case at all.

[TestIdGenerator.java.txt](https://github.com/hazelcast/hazelcast/files/58623/TestIdGenerator.java.txt)

**Comment by markathomas** [comment] 2015-12-10 19:43
Note: this test was performed with Hazelcast 3.4.6

**Comment by gurbuzali** [comment] 2015-12-10 22:26
I couldn't reproduce it with the given setup, can you share your logs ?

**Comment by markathomas** [comment] 2015-12-11 14:26
It's related to the block size.  We desire less than 1,000,000 ids at a
time so we changed the block size from 10,000 to 100 which makes the issue
reproduce quicker but it still manifests as soon as node 2 runs out of ids
and attempts to fetch more.  Node 2 ends the test when the bug manifests
with the following output:

New id = 1909999
New id = 20000
Dec 11, 2015 8:21:19 AM com.hazelcast.core.LifecycleService
INFO: [10.7.7.97]:5702 [dev] [3.5.3] Address[10.7.7.97]:5702 is
SHUTTING_DOWN

I can provide logs if you want but there is nothing special.  You can
reproduce it but you have to let it run for about 15 minutes.  Take out the
Thread.sleep(50) to make it manifest in about 5 seconds.

**Comment by jerrinot** [comment] 2016-05-01 08:49
I believe this had the same root cause as #7290 and therefore it was fixed by #7304
Feel free to re-open this issue if you reproduce it with 3.5.5 or 3.6.x

**Closed by jerrinot** 2016-05-01 08:49 UTC
Labels: Team: Core, Type: Defect
