### ISSUE TITLE
RaftCountDownLatchAdvancedTest.testNewRaftGroupMemberSchedulesTimeoutsWithSnapshot

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#15532] opened 2019-09-09 10:58 UTC
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3022

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.cp.internal.datastructures.countdownlatch.RaftCountDownLatchAdvancedTest.lambda$testNewRaftGroupMemberSchedulesTimeoutsWithSnapshot$6(RaftCountDownLatchAdvancedTest.java:197)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1308)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1410)
	at com.hazelcast.cp.internal.datastructures.countdownlatch.RaftCountDownLatchAdvancedTest.testNewRaftGroupMemberSchedulesTimeoutsWithSnapshot(RaftCountDownLatchAdvancedTest.java:187)
```

**Comment by mmedenjak** [comment] 2019-09-09 16:47
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3023/testReport/

**Comment by mdogan** [comment] 2019-10-15 14:38
`RaftCountDownLatchAdvancedTest` was renamed to `CountDownLatchAdvancedTest`. Duplicate of #15708

**Closed by mdogan** 2019-10-15 14:38 UTC
Labels: Module: CP Subsystem, Team: Core, Type: Test-Failure
