### ISSUE TITLE
Hazelcast exception putting bool value into map

### ISSUE THREAD

**Issue by APIANT** [hazelcast/hazelcast#16651] opened 2020-02-12 18:18 UTC
We started using Hazelcast a couple of months ago. We recently began testing it in our production environments and are now seeing this exception about once a week:

```
2020-02-11 12:10:00,084 com.hazelcast.partition.NoDataMemberInClusterException: Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members. 
at com.hazelcast.spi.impl.operationservice.impl.PartitionInvocation.newTargetNullException(PartitionInvocation.java:90) 
at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:269) 
at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:556) 
at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:534) 
at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:236) 
at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) 
at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:467) 
at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:406) 
at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:121) 
at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:111)
```

This is from Hazelcast 4.0 GA released 2/4/20. This also happened to us running 3.12.x versions. We were hoping the exception would go away each time we upgraded to newer versions.

Our setup is very simple. Hazelcast is running on a single server with tons of free memory and Java 8. All we are doing is putting a true/false value into a map that only has a single integer key with a value of zero. Really, this is like the smallest map possible! The server runs fine for many days, but eventually this exception gets thrown from the map.put(0, bool).

Other portions of our code are heavily using Hazelcast's executors. We have had no trouble with that so far.

We configure Hazelcast like so:

```java
config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
config.getNetworkConfig().getJoin().getAwsConfig().setEnabled(false);
config.getNetworkConfig().getJoin().getTcpIpConfig().setEnabled(true);
config.getNetworkConfig().setPortAutoIncrement(true);
config.getNetworkConfig().setPort(5701);
config.getNetworkConfig().getJoin().getTcpIpConfig().addMember(AppConfig.getConfigSetting("/config/server/ip_address"));

hazelcastInstance = Hazelcast.newHazelcastInstance(config);
```

I can't find any information about this exception other than this: https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/partition/NoDataMemberInClusterException.html

It seems that hazelcast is somehow crashing.  We have hazelcast configured to use Log4J at the ERROR level, but only the above exception is logged.

**Comment by mdogan** [comment] 2020-02-13 07:43
@APIANT: Did I understand correct? You are using a single member Hazelcast instance and at some point `map.put(0, bool)` starts to throw `NoDataMemberInClusterException`.  

Do you use any _lite_ members? (https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#enabling-lite-members)

Can you please try to reproduce this issue with a lower logging level enabled?

**Comment by kwart** [comment] 2020-02-13 12:50
Thanks for the report @APIANT.

Could you describe more precisely the usage and your environment (OS, exact java version, CPUs, memory).
* How your IMap calls look like?
* How many calls per time unit do you have?
* How many days it took to fail?
* Do the executors run in the same Hazelcast member?
* Is your application running standalone or as a web-app for instance?
* Do you customize data structures config (e.g.MapLoader/MapStore or TTL used)? 

@mdogan There seems to be just one standard member in their environment. See https://stackoverflow.com/questions/60170696/hazelcast-exception-putting-bool-value-into-map#comment106464143_60170696

**Comment by APIANT** [comment] 2020-02-13 13:56
Hi @mdogan,

Yes, our setup is just a single server.  No clustering at all is involved.  The exception has occurred at least 3 times on 3 different servers on 3 of the latest hazelcast releases over the course of the last month or two.  Each server runs in a separate Amazon AWS account, these are totally isolated incidents happening on single isolated servers.  We are new to hazelcast, started testing it in December.  It worked great during our initial development and testing (we did use 2 test instances clustered for multi-server testing of maps and executors), but is not surviving on our monolithic production servers under load.

Once that exception happens, every map put() afterwards causes the same exception and hazelcast seems to be dead until the server is restarted.

We are not using a declarative config file.  The config code I pasted above is how we configure hazelcast.  We are not configuring it to be a lite member.  Didn't even know about that.

We have been unable to correlate the exception with anything.  The servers have had plenty of free memory, many GB free.  Our own code is rock solid, having been developed over the course of 15 years.  Our systems have not recently crashed for any unknown reasons until the recent introduction of hazelcast.

I will configure our servers to do full hazelcast logging and see if the exception happens again.  It seems to happen about once a week or so.

===============================================

@kwart your message came in as I was finishing this.

Here is the code to update the map value:

// Constructor where we save a reference to the map
    public ThreadNativeWorkQueue()
    {
        this.mapWorkerSaturated = AppHazelcast.hazelcastInstance.getMap("hazelcast_map_worker_saturated");
    }

// The line of code where we put a value into the map
this.mapWorkerSaturated.put(AppCluster.workerId, processingThreads >= this.ceilingActiveThreads*0.75);

All this is doing is indicating if this server's processing threads are considered to be saturated or not.  We need to reserve 25% of the threads for other things.  Again, currently this is all on a single server, but the idea is that in the future work will be routed to servers in a cluster that are not considered to be saturated. 

Don't know how exactly many calls per unit time, but should not be too crazy.  Funny enough we have had the exception happen only on our most lightly loaded servers, not the highest loaded ones.  My guess would be no more than 10 calls per second on these lightly loaded servers.  The load is spiky, in that this code is kicking off work routines based mostly on cron at the top of each minute.  Otherwise it is idle.

On average it took less than 7 days to fail.  I would install our system upgrades over a weekend and before the end of the following week a machine would crash with that exception.  We have it installed on 7 separate machines.

Yes, executors are also running in the same server.  We are in test mode with hazelcast and currently have installed it in environments that consist of just single servers.  One Amazon machine.  Multiple Amazon AWS accounts, each with one machine.  No server-to-server communication at all.  These single machines contain everything, MySQL, Apache, etc.  Yes they are web apps.

No, we are not customizing any data structures.  This is a dead simple test, I have pasted virtually all of the code involved.  We use the hazelcast config code I pasted above, we put() a simple single value into a map, we fetch that value.  And hazelcast sometimes throws that exception on the put() and the house falls down.

Since we are heavily using executors, is it possible that the real problem is with those and the map.put() exception is just a downstream side effect?

Thanks for the help, hazelcast immediately impressed us with its packaging as a Java library and its design and functionality.  We were looking at redis and other competing solutions before giving hazelcast a try.  Would really like to get this resolved b/c hazelcast is the ideal solution for us, but it has to be rock solid.  I'm the one who has had to get out of bed 3 times in the middle of the night to restart our servers after hazelcast crashed (funny how failures love to happen in the middle of the night).  So I am motivated to get our production servers back to being rock solid once again asap, one way or another.

**Comment by kwart** [comment] 2020-02-14 20:23
Thanks for sharing the details, @APIANT .

I guess the problem is related to the other usage of Hazelcast - i.e. probably the executors - and you only see side-effects. Log files will be really helpful to identify the cause.

**Comment by APIANT** [comment] 2020-02-14 20:26
Have enabled full logging on all servers running hazelcast, now just waiting for the exception to happen again...

**Comment by APIANT** [comment] 2020-02-19 10:10
Ugh, why does software like to fail late at night?  The exception has been caught, crashed our primary production server around 4:30am my time, waking me up.

This happened with Hazelcast 4.0 GA released 2/4/20.

Attached are 2 log files.  The "initialize.log" is the first log when the system was booted after turning on all hazelcast logging on Feb 13.

The "exception.log" file contains the crash.  Here is the first exception:

2020-02-19 09:28:16,571 [Thread-1012] ERROR appServer - User [System]  method /appServer.ThreadActiveMQConsumeWebhooksToProcess.run(ThreadActiveMQConsumeWebhooksToProcess.java:255) -> com.hazelcast.partition.NoDataMemberInClusterException: Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.
	at com.hazelcast.spi.impl.operationservice.impl.PartitionInvocation.newTargetNullException(PartitionInvocation.java:90)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:269)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:556)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.access$400(Invocation.java:98)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation$InvocationRetryTask.run(Invocation.java:778)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

This exception is from trying to invoke an executor, which is different from the exception I caught and posted above in my initial trouble report.  But I also see that map.put() exception in this crash log:

2020-02-19 09:29:00,054 [APIANTappServer.ThreadExecAutomation] ERROR appServer - User [System]  method /appServer.ThreadExecAutomation.run(ThreadExecAutomation.java:74) -> com.hazelcast.partition.NoDataMemberInClusterException: Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.
	at com.hazelcast.spi.impl.operationservice.impl.PartitionInvocation.newTargetNullException(PartitionInvocation.java:90)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:269)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:556)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:236)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:467)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:406)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:121)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:111)
	at appServer.ThreadNativeWorkQueue.updateHazelcastWorkerSaturationValue(ThreadNativeWorkQueue.java:96)
	at appServer.ThreadNativeWorkQueue.execute(ThreadNativeWorkQueue.java:83)
	at appServer.ThreadExecAutomation.run(ThreadExecAutomation.java:69)

So it seems to be a general hazelcast failure.  I've quickly scanned the log looking for what has caused this, but nothing jumps out to me.  I see lots of socket timeouts, but those are throughout the log.

I have all logs from Feb 13 thru Feb 19.  Let me know if you need me to provide to help your troubleshooting.

[initialize.log.zip](https://github.com/hazelcast/hazelcast/files/4224346/initialize.log.zip)
[exception.log.zip](https://github.com/hazelcast/hazelcast/files/4224344/exception.log.zip)

**Comment by kwart** [comment] 2020-02-19 10:39
Thank you for the logs, I'll go through them.

**Comment by mdogan** [comment] 2020-02-19 12:21
```
2020-02-19 09:28:16,239 [hz.master.cached.thread-38] DEBUG com.hazelcast.internal.nio.tcp.TcpIpEndpointManager - [172.30.0.192]:5701 [dev] [4.0] Established socket connection between /0.0.0.0:5703 and /52.37.38.181:5703
```
It looks like `[172.30.0.192]:5701` is listening on all local ports at `0.0.0.0:5703` and it's same server as `52.37.38.181:5703`. So, it's connecting to itself... 🤔 

```
2020-02-19 09:28:16,281 [hz.master.priority-generic-operation.thread-0] INFO  com.hazelcast.internal.cluster.ClusterService - [172.30.0.192]:5701 [dev] [4.0] 

Members {size:0, ver:2} [
]
```
😱

**Comment by kwart** [comment] 2020-02-19 14:17
@APIANT, is the IP address `52.37.38.181` from the same host? Is there some port mapping involved in your environment (e.g. docker host mapping port 5703 to container's port 5701)?

This problem could be related to other `Address`-ing related issues (#12334, #15722).

Could you try the following configuration changes? They should result in safer environment:

* Don't use port autoincrement. I.e. bind to a single predefined port;
* If You are running just a single member, you don't need to add member to the `TcpIpConfig`. If you still want to define some members, it's safer to add also their port numbers;
* Bind to a single IP address - suppress the Hazelcast default address picking algorithm by setting configuration properties or defining network interfaces;

Your `Config` could look like following:
```java
String ipAddress = AppConfig.getConfigSetting("/config/server/ip_address");
Config config = new Config()
    .setProperty("hazelcast.socket.bind.any", "false")
    .setProperty("hazelcast.local.localAddress", ipAddress)
    .setProperty("hazelcast.local.publicAddress", ipAddress);
config.getNetworkConfig()
    .setPortAutoIncrement(false)
    .setPort(5701);
JoinConfig joinConfig = config.getNetworkConfig().getJoin();
joinConfig.getMulticastConfig().setEnabled(false);
joinConfig.getTcpIpConfig().setEnabled(true);
```

**Comment by APIANT** [comment] 2020-02-19 18:43
@kwart 52.37.38.181 is the public IP address for the server that went down this morning.  172.30.0.192 is its private IP internal to Amazon AWS.

The public IP address 52.37.38.181 is the value configured with this line:

config.getNetworkConfig().getJoin().getTcpIpConfig().addMember(AppConfig.getConfigSetting("/config/server/ip_address"));

The server is just a bare Amazon EC2 instance, no Docker or other container.  Nothing should be interfering with ports.

Is it wrong for us to configure hazelcast with the server's public IP address?  Should we be using the private IP instead?

I've found some more logged stdout entries, have attached relevant snippets.

[catalina.out.zip](https://github.com/hazelcast/hazelcast/files/4226722/catalina.out.zip)

**Comment by APIANT** [comment] 2020-02-19 19:28
@kwart or since it is a single server, should we configure hazelcast with 127.0.0.1 loopback?

**Comment by kwart** [comment] 2020-02-19 19:34
Great, we are getting closer.

If you don't need to have the Hazelcast member available from outside the AWS subnet, then you don't need to configure the public address. In such case, don't call the `addMember` method with the external address!

If you want to access it by clients or other members outside the AWS subnet, then you have to define the public address in Hazelcast configuration.

Either:
```java
config.setProperty("hazelcast.local.publicAddress", ipAddress);
```

Or:
```java
config.getNetworkConfig().setPublicAddress(ipAddress)
```

WRT your latest question. For the single-member cluster, you can use the loopback too, but then your Management center needs to run on the same machine.

**Comment by APIANT** [comment] 2020-02-19 20:47
@kwart based on your suggestions I have come up with this config logic:

    com.hazelcast.config.Config config = new com.hazelcast.config.Config();
    
    config.setProperty("hazelcast.logging.type", "log4j");
    
    String name = AppCluster.isWorkerServer ? "worker "+AppHTTP.getSystemDomainAndContext() : "master"; 
    
    config.setInstanceName(name);        
    
    config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
    config.getNetworkConfig().getJoin().getAwsConfig().setEnabled(false);
    config.getNetworkConfig().getJoin().getTcpIpConfig().setEnabled(true);
    config.getNetworkConfig().setPort(5701);
    config.getNetworkConfig().setPortAutoIncrement(false);
    config.setProperty("hazelcast.socket.bind.any", "false");

    // Default value to use when a single server
    String hazelcastIP = "127.0.0.1";
    if (AppCluster.isWorkerServer || AppCluster.totalServers > 1)
    {
        if (AppConfig.getConfigSetting("/config/server/ec2_private_ip").length() > 0)
        {
            // If clustered and in Amazon AWS, use the server's private IP address
            hazelcastIP = AppConfig.getConfigSetting("/config/server/ec2_private_ip");
        }
        else
        {
            // If clustered and not in Amazon AWS, use the server's public IP address
            hazelcastIP = AppConfig.getConfigSetting("/config/server/ip_address");
        }
    }
    
    config.getNetworkConfig().setPublicAddress(hazelcastIP);
    config.setProperty("hazelcast.local.localAddress", hazelcastIP);
        
    hazelcastInstance = Hazelcast.newHazelcastInstance(config);


Seems to work ok on a test server.  We have the hazelcast management center running on the same machine and its dashboard loads ok.

So the main change vs. before is to use 127.0.0.1 instead of the server's public IP, since these are currently all non-clustered single servers.

Will start installing this change into our servers hopefully starting this weekend.  Then will wait and see if the hazelcast exception happens again or not.

Thank you for your help!

**Comment by kwart** [comment] 2020-02-19 20:55
It's still not clear to me from where the port `5703` connection comes. I will try to look into the logs again tomorrow.

**Comment by APIANT** [comment] 2020-02-19 21:01
@kwart maybe from the management center?  As I was troubleshooting the code changes I just wrote about I was seeing these log entries in our stdout log:

2020-02-19 20:35:54 [MC-Client-dev.internal-1] INFO  c.h.c.i.c.ClientConnectionManager - MC-Client-dev [dev] [4.0] Trying to connect to cluster: dev
2020-02-19 20:35:54 [MC-Client-dev.internal-1] INFO  c.h.c.i.c.ClientConnectionManager - MC-Client-dev [dev] [4.0] Trying to connect to [localhost]:5701
2020-02-19 20:35:54 [MC-Client-dev.internal-1] WARN  c.h.c.i.c.ClientConnectionManager - MC-Client-dev [dev] [4.0] Exception during initial connection to [localhost]:5701: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address localhost/127.0.0.1:5701
2020-02-19 20:35:54 [MC-Client-dev.internal-1] INFO  c.h.c.i.c.ClientConnectionManager - MC-Client-dev [dev] [4.0] Trying to connect to [localhost]:5702
2020-02-19 20:35:54 [MC-Client-dev.internal-1] WARN  c.h.c.i.c.ClientConnectionManager - MC-Client-dev [dev] [4.0] Exception during initial connection to [localhost]:5702: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address localhost/127.0.0.1:5702
2020-02-19 20:35:54 [MC-Client-dev.internal-1] INFO  c.h.c.i.c.ClientConnectionManager - MC-Client-dev [dev] [4.0] Trying to connect to [localhost]:5703
2020-02-19 20:35:54 [MC-Client-dev.internal-1] WARN  c.h.c.i.c.ClientConnectionManager - MC-Client-dev [dev] [4.0] Exception during initial connection to [localhost]:5703: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address localhost/127.0.0.1:5703
2020-02-19 20:35:54 [MC-Client-dev.internal-1] WARN  c.h.c.i.c.ClientConnectionManager - MC-Client-dev [dev] [4.0] Unable to get live cluster connection, retry in 1000 ms, attempt: 1 , cluster connect timeout: 9223372036854775807 seconds , max backoff millis: 32000

Seems the management center was trying to find hazelcast on ports 5701, 5702, and 5703.  We have the management center WAR running on each server in tomcat.  So maybe when the hazelcast instance disappeared you saw log entries related to management center trying to reconnect.

**Comment by kwart** [comment] 2020-02-19 21:31
I don't think it's related to the Management center.

As you had the public IP address listed as cluster member address the member periodically tried to connect to it (on ports 5701-5703).

You can see in the your log these lines:
```
$ grep 52.37.38.181:5703 exception.log
2020-02-19 00:00:16,236 [hz.master.cached.thread-24] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Connecting to /52.37.38.181:5703, timeout: 10000, bind-any: true
2020-02-19 00:00:26,246 [hz.master.cached.thread-24] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Could not connect to: /52.37.38.181:5703. Reason: SocketTimeoutException[null]
2020-02-19 00:02:16,236 [hz.master.cached.thread-24] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Connecting to /52.37.38.181:5703, timeout: 10000, bind-any: true
2020-02-19 00:02:26,246 [hz.master.cached.thread-24] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Could not connect to: /52.37.38.181:5703. Reason: SocketTimeoutException[null]
2020-02-19 00:04:16,236 [hz.master.cached.thread-38] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Connecting to /52.37.38.181:5703, timeout: 10000, bind-any: true
2020-02-19 00:04:26,244 [hz.master.cached.thread-38] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Could not connect to: /52.37.38.181:5703. Reason: SocketTimeoutException[null]
2020-02-19 00:06:16,236 [hz.master.cached.thread-43] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Connecting to /52.37.38.181:5703, timeout: 10000, bind-any: true
2020-02-19 00:06:26,246 [hz.master.cached.thread-43] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Could not connect to: /52.37.38.181:5703. Reason: SocketTimeoutException[null]
2020-02-19 00:08:16,235 [hz.master.cached.thread-21] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Connecting to /52.37.38.181:5703, timeout: 10000, bind-any: true
2020-02-19 00:08:26,243 [hz.master.cached.thread-21] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Could not connect to: /52.37.38.181:5703. Reason: SocketTimeoutException[null]
...
```

And at one point the 5703 is suddenly open:
```
2020-02-19 09:28:16,236 [hz.master.cached.thread-38] TRACE com.hazelcast.internal.nio.tcp.TcpIpConnector - [172.30.0.192]:5701 [dev] [4.0] Connecting to /52.37.38.181:5703, timeout: 10000, bind-any: true
2020-02-19 09:28:16,236 [hz.master.cached.thread-38] TRACE com.hazelcast.internal.networking.nio.NioChannel - Successfully connected to: /52.37.38.181:5703 using socket Socket[addr=/52.37.38.181,port=5703,localport=5703]
```

The interesting thing is, the `localport` is equal to the target `port`. Maybe the `5703` is picked by system as an ephemeral outbound port and it triggers all the problems. 
Hazelcast has configuration options to specify outbound ports. E.g.:

```java
config.getNetworkConfig().addOutboundPortDefinition("35000-35100");
```

The key point is, the bind port range (5701-5703) must not overlap with outbound ports.

**Comment by APIANT** [comment] 2020-02-19 21:48
@kwart here's the remaining hazelcast trace logs for Feb 14 thru Feb 18, in case they contain anything helpful.

[tomcat.20200214.log.zip](https://github.com/hazelcast/hazelcast/files/4227601/tomcat.20200214.log.zip)
[tomcat.20200215.log.zip](https://github.com/hazelcast/hazelcast/files/4227602/tomcat.20200215.log.zip)
[tomcat.20200216.log.zip](https://github.com/hazelcast/hazelcast/files/4227603/tomcat.20200216.log.zip)
[tomcat.20200217.log.zip](https://github.com/hazelcast/hazelcast/files/4227604/tomcat.20200217.log.zip)
[tomcat.20200218.log.zip](https://github.com/hazelcast/hazelcast/files/4227605/tomcat.20200218.log.zip)

**Comment by kwart** [comment] 2020-02-21 16:00
It's really related to outbound ports.
I was able to reproduce the problem in EC2 with this config:

```
JoinConfig joinConfig = config.getNetworkConfig().getJoin();
joinConfig.getMulticastConfig().setEnabled(false);
joinConfig.getTcpIpConfig().setEnabled(true).addMember(ipAddress);
config.getNetworkConfig().addOutboundPort(16703);
config.getNetworkConfig().addOutboundPort(16704);
config.getNetworkConfig().addOutboundPort(16705);
config.getNetworkConfig().addOutboundPort(5703);
```

I've tried it in the Docker first, but without success - probably due to the different behavior of published ports.

@APIANT Could you add the outbound port range to your configuration?

E.g.
```java
config.getNetworkConfig().addOutboundPortDefinition("30000-60000");
```

I will think about what we can do on the Hazelcast side to prevent such errors.

**Comment by APIANT** [comment] 2020-02-21 17:39
@kwart happy to hear you found a way to reproduce the issue!

We will add that to our configuration and hopefully get it installed onto all our servers this weekend.  Then will wait and see if the exception happens again.  Will report back either way after a week.

Thanks for all your help!

**Comment by mmedenjak** [comment] 2020-02-28 13:41
@APIANT any updates on the issue?

**Comment by APIANT** [comment] 2020-02-28 16:24
@mmedenjak We have not experienced a crash this week, so we're pretty confident the issue has been resolved via the new config settings.

**Comment by kwart** [comment] 2021-08-02 11:10
Closing this issue for now. Feel free to reopen if you experience the issue in Hazelcast 5.0 which should be released in the next months.

**Notes**
* The logic will be improved in Hazelcast 5 by fixing some hostnames related issues.
* Explicitly defined port numbers without autoincrement allowed is a safe way to avoid loopback binds (to self).

**Closed by kwart** 2021-08-02 11:10 UTC
Labels: Module: Cluster, Source: Community, Team: Core, Type: Defect
