### ISSUE TITLE
QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8046] opened 2016-04-29 09:06 UTC
```
java.lang.AssertionError: expected:<30> but was:<29>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating(QueryIndexMigrationTest.java:157)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/892/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating/

**Comment by vbekiaris** [comment] 2016-06-21 08:09
Fixed by #8403

**Comment by hasancelik** [comment] 2016-07-01 08:53
**maintenance**
```
java.lang.AssertionError: expected:<30> but was:<29>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating(QueryIndexMigrationTest.java:157)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/395/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating/

**Comment by tombujok** [comment] 2016-07-01 09:46
@hasancelik Vassilis fixed it in 3.7, but it's too complex to backport it to 3.6, so it's a won't fix on the maintenance branch.

**Comment by hasancelik** [comment] 2016-07-25 11:28
```
java.lang.AssertionError: expected:<30> but was:<29>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating(QueryIndexMigrationTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/980/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating/

**Comment by vbekiaris** [comment] 2016-07-25 16:13
I can reliably reproduce this issue by executing the test repetitively and increasing GC pressure with each iteration (eg. adding several strings to a queue) within the first 20-30 repetitions.
The issue must have been already there but is observed more frequently due to more frequent execution of full-table scans during `QueryOperation`s, due to added safety in https://github.com/vbekiaris/hazelcast/commit/227d93278e55aeb2ca8077a9f60b4cd51640f0af: this results in doing partition access from non-partition threads, resulting in the `QueryOperation` omitting a result. The code path in `MapQueryEngineImpl` is:
* `queryLocalPartitions` -> fails to query using indexes due to migrations/partition state version changes
* `queryUsingFullTableScan`
* `querySequential`
* `queryTheLocalPartition` in the same thread (instead of a partition thread).

**Comment by hasancelik** [comment] 2016-07-26 08:52
```
java.lang.AssertionError: expected:<30> but was:<29>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating(QueryIndexMigrationTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/276/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating/

**Comment by hasancelik** [comment] 2016-10-10 07:55
```
java.lang.AssertionError: expected:<30> but was:<29>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating(QueryIndexMigrationTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1228/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating/

**Comment by mdogan** [comment] 2017-01-16 11:12
most probably related to https://github.com/hazelcast/hazelcast/issues/8931

**Closed** 2017-01-19 07:25 UTC
Labels: Team: Core, Type: Test-Failure
