### ISSUE TITLE
Hazelcast Client shutdowned, but doesnt kill opened threads in tomcat

### ISSUE THREAD

**Issue by talipkorkmaz** [hazelcast/hazelcast#4378] opened 2015-01-03 15:52 UTC
Hi all,

There is a lifcylelistener of hazelcast client and it logs as below.

```
client.getLifecycleService().addLifecycleListener(new LifecycleListener() {

                @Override
                public void stateChanged(LifecycleEvent event) {

                    logger.error("Hazelcast instance state changed to " + event.getState().name());

                }
            });
```

As you can see from log file hazelcast threads are still open and not closing.
I shoutdown the hazelcast instance by accessing the cache manager in spring context.
I didnt used HazelcastManger because there is not get Method of hazelcast intance.
So I totally copied HazelcastManager and added a get method.
Than in contextDestroyed method of Listener, I injected the cache manager bean and shutdown the client.
But it still couldnt close the connections.
Any idea?

```
Oca 03, 2015 5:51:18 PM org.apache.catalina.core.StandardServer await
INFO: A valid shutdown command was received via the shutdown port. Stopping the Server instance.
Oca 03, 2015 5:51:18 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-bio-8080"]
Oca 03, 2015 5:51:18 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["ajp-bio-8009"]
Oca 03, 2015 5:51:18 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Catalina
03 Oca 2015 17:51:18 816ms INFO  [localhost-startStop-1] - Closing WebApplicationContext for namespace 'mvc-servlet': startup date [Sat Jan 03 17:51:13 EET 2015]; parent: Root WebApplicationContext
03 Oca 2015 17:51:18 816ms INFO  [localhost-startStop-1] - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@501074be: defining beans [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping#0,org.springframework.format.support.FormattingConversionServiceFactoryBean#0,org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter#0,org.springframework.web.servlet.handler.MappedInterceptor#0,org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver#0,org.springframework.web.servlet.mvc.annotation.ResponseStatusExceptionResolver#0,org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver#0,org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping,org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter,org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter,appCacheConfig,homeController,testService,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.web.servlet.resource.ResourceHttpRequestHandler#0,org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#0,org.springframework.web.servlet.resource.ResourceHttpRequestHandler#1,org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#1,viewResolver,org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter#0,jacksonObjectMapper,org.springframework.context.annotation.ConfigurationClassPostProcessor$ImportAwareBeanPostProcessor#0,org.springframework.aop.config.internalAutoProxyCreator,proxyCachingConfiguration,org.springframework.cache.config.internalCacheAdvisor,cacheOperationSource,cacheInterceptor,cacheManager]; parent: org.springframework.beans.factory.support.DefaultListableBeanFactory@74082edf
Oca 03, 2015 5:51:18 PM org.apache.catalina.core.ApplicationContext log
INFO: Destroying Spring FrameworkServlet 'mvc'
03 Oca 2015 17:51:20 227ms ERROR [localhost-startStop-1] - Hazelcast instance state changed to SHUTTING_DOWN
Oca 03, 2015 5:51:20 PM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_dev][3.4] is SHUTTING_DOWN
Oca 03, 2015 5:51:20 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: Connection [null] lost. Reason: Socket explicitly closed
Oca 03, 2015 5:51:20 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: Connection [/192.168.0.15:5701] lost. Reason: Socket explicitly closed
Oca 03, 2015 5:51:20 PM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_dev][3.4] is CLIENT_DISCONNECTED
03 Oca 2015 17:51:20 243ms ERROR [hz.client_0_dev.cluster-listener] - Hazelcast instance state changed to CLIENT_DISCONNECTED
03 Oca 2015 17:51:20 251ms ERROR [localhost-startStop-1] - Hazelcast instance state changed to SHUTDOWN
as
Oca 03, 2015 5:51:20 PM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_dev][3.4] is SHUTDOWN
03 Oca 2015 17:51:20 252ms INFO  [localhost-startStop-1] - Closing Root WebApplicationContext: startup date [Sat Jan 03 17:51:10 EET 2015]; root of context hierarchy
03 Oca 2015 17:51:20 253ms INFO  [localhost-startStop-1] - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@74082edf: defining beans [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping#0,org.springframework.format.support.FormattingConversionServiceFactoryBean#0,org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter#0,org.springframework.web.servlet.handler.MappedInterceptor#0,org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver#0,org.springframework.web.servlet.mvc.annotation.ResponseStatusExceptionResolver#0,org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver#0,org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping,org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter,org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter,appCacheConfig,homeController,testService,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.web.servlet.resource.ResourceHttpRequestHandler#0,org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#0,org.springframework.web.servlet.resource.ResourceHttpRequestHandler#1,org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#1,viewResolver,org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter#0,jacksonObjectMapper,org.springframework.context.annotation.ConfigurationClassPostProcessor$ImportAwareBeanPostProcessor#0,org.springframework.aop.config.internalAutoProxyCreator,proxyCachingConfiguration,org.springframework.cache.config.internalCacheAdvisor,cacheOperationSource,cacheInterceptor,cacheManager]; root of factory hierarchy
Oca 03, 2015 5:51:20 PM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.event-6] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.event-7] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.event-8] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.event-9] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.event-10] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [InSelector] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [OutSelector] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.scheduled] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.cluster-listener] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.internal-1] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.cached-1] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.internal-2] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/spring-hazelcast-example] appears to have started a thread named [hz.client_1_dev.cached-2] but has failed to stop it. This is very likely to create a memory leak.
Oca 03, 2015 5:51:20 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/spring-hazelcast-example] created a ThreadLocal with key of type [com.hazelcast.util.UuidUtil$1] (value [com.hazelcast.util.UuidUtil$1@3032bedb]) and a value of type [java.util.Random] (value [java.util.Random@53903495]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Oca 03, 2015 5:51:20 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-bio-8080"]
Oca 03, 2015 5:51:20 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["ajp-bio-8009"]
Oca 03, 2015 5:51:20 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-bio-8080"]
Oca 03, 2015 5:51:20 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["ajp-bio-8009"]
```

**Comment by hasancelik** [comment] 2015-02-10 14:31
Thanks for reporting your issue. Please share with us the following information, to help us resolve your issue quickly and efficiently.
* **Hazelcast version** that you are using  (e.g. 3.4, also specify minor release or latest snapshot)
* **Hazelcast configuration** (hazelcast.xml or programmatic configuration)
* **Cluster topology**
  * Number of Hazelcast member nodes
  * Number of Hazelcast clients
* **Java version** (also JVM parameters can be added)
* **Operating System** (for Linux kernel version will be helpful)
* **Unit Test** (if you can include a unit test which reproduces your issue, we would be grateful)

**Comment by ChandranMuthu** [comment] 2018-11-22 05:42
I am getting the below error in my application. Could you please advise on this?

`2018-11-22 11:02:56.051  WARN 16496 --- [ost-startStop-1] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [hz.hazelcastInstance.scheduled.thread-] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
 com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
 com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
2018-11-22 11:02:56.052  WARN 16496 --- [ost-startStop-1] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [hz.hazelcastInstance.event-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
 com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:207)
2018-11-22 11:02:56.055  WARN 16496 --- [ost-startStop-1] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [hz.hazelcastInstance.event-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)`

**Comment by ChandranMuthu** [comment] 2018-11-22 05:43
I am gettting this error when i run the application from an specific windows 10 machine. I am not getting this error in another machine.

**Comment by Hyunsuk-Baek** [comment] 2020-07-22 05:43
why this error closed?

**Comment by sancar** [comment] 2020-07-22 07:05
We have closed the issue in 2015 because it was unresponsive. The report by @ChandranMuthu seems to be skipped by accident. 
@Hyunsuk-Baek, @ChandranMuthu Can we get more details on the problem that you are seeing?
Which version you are seeing? 
Do you have a unit test to reproduce?
Is it the client or the member which leaves a thread open? 
Do you have stack-trace or logs regarding the problem?
If you have a candidate fix, we would be glad to accept and merge your solution.

**Comment by sancar** [comment] 2020-07-27 07:54
We are unable to investigate the issue further. I am closing the issue. If you still having problems please reopen an issue with details provided.  @Hyunsuk-Baek @ChandranMuthu

**Closed by sancar** 2020-07-27 07:54 UTC
Labels: Source: Community, Team: Client, Type: Question
