### ISSUE TITLE
hazelcast map - slow load on startup - 2 seconds for each map

### ISSUE THREAD

**Issue by sarvesh279** [hazelcast/hazelcast#5983] opened 2015-08-17 08:12 UTC
Class:
class HazelcastUserAssignmentStore implements MapStore<String, UserAssignmentCache>, MapLoader<String, UserAssignmentCache>, MapLoaderLifecycleSupport

the above class has all necessary overridden methods.

On server startup, there is 2 sec time lag after data load to each map.
The sequence of methods called,
1) init
2) loadAllKeys
3) loadAll

All the three methods are executed less than 5ms. Then the system waits for 2 sec to load the next map. How to avoid this delay?

**Comment by jerrinot** [comment] 2015-08-17 09:36
Hi @sarvesh279, 
thank you for reporting the issue. It seems like a duplicate of #5349. The fix is already pending, we are aiming to include it in the 3.5.2 release.

**Comment by jerrinot** [comment] 2015-08-17 10:24
I'm closing this one in favour of #5349. Feel free to re-open it if you feel it's not a duplicate.

**Comment by sarvesh279** [comment] 2015-08-26 11:51
release date for 3.5.2?

**Comment by jerrinot** [comment] 2015-08-26 12:01
Hi @sarvesh279: It's out, but be careful, it's still hot! ;-)
http://hazelcast.org/download/
https://github.com/hazelcast/hazelcast/tree/v3.5.2

(It might take a while until it's available Maven central)

**Comment by sarvesh279** [comment] 2015-09-08 09:41
I get the same issue in 3.5.2 version.

On server startup, there is 2 sec time lag after data load to each map.
The sequence of methods called,
1) init
2) loadAllKeys
3) loadAll

All the three methods are executed less than 5ms. Then the system waits for 2 sec to load the next map.

**Comment by sarvesh279** [comment] 2015-09-21 08:27
@jerrinot is the issue fixed in 3.5.2?

**Comment by jerrinot** [comment] 2015-09-21 08:29
hm, it's fixed in 3.5.2. 
Maybe there is another source of lag. @ajermakovics: Can you please look at this?

**Comment by sarvesh279** [comment] 2015-09-30 10:50
@ajermakovics Any updates?

**Comment by ajermakovics** [comment] 2015-09-30 11:11
This test case passes and doesn't have a delay: https://github.com/hazelcast/hazelcast/issues/5632 
@sarvesh279 Perhaps you have a test case or can create one?

**Closed** 2015-11-10 09:03 UTC
Labels: Team: Core
