### ISSUE TITLE
Hazelcast (3.6) fails to create ObjectName for an Instance created with JCache API

### ISSUE THREAD

**Issue by kenitra** [hazelcast/hazelcast#7548] opened 2016-02-18 13:57 UTC
Dear All,
I have posted this issue on Stackoverflow, where  I described the problem and also pointed to the code fragement that produce this issue.

http://stackoverflow.com/questions/35461382/hazelcast-failed-to-create-an-objectname-when-using-filehttps-protocol

Best Regards,

talbi

**Comment by muratayan** [comment] 2016-02-19 15:44
@kenitra Thanks for the report, it's a small bug which will be fixed immediately. I also answered in StackOverflow.

**Comment by serkan-ozal** [comment] 2016-02-19 15:46
Seems that it is caused by unquoted name property by instance name in `ConnectionManagerMBean`

``` java
properties.put("name", hazelcastInstance.getName());
```

**Closed** 2016-02-22 14:46 UTC
Labels: Team: Integration, Type: Defect
