### ISSUE TITLE
Test failure com.hazelcast.cache.CacheTest.testIteratorDuringInsertion

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#16450] opened 2020-01-09 11:13 UTC
http://jenkins.hazelcast.com/job/Hazelcast-EE-pr-builder/1908/testReport/junit/com.hazelcast.cache/CacheTest/testIteratorDuringInsertion/

```
Error Message
test timed out after 300000 milliseconds

Stacktrace
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.hazelcast.cache.CacheTest.testIteratorDuringInsertion(CacheTest.java:492)

```

**Comment by vojtechtoman** [comment] 2020-01-09 14:51
Encountered this one as well. Quite easy to reproduce in IDEA with running the test repeatedly ("Repeat: Until failure")

**Comment by mmedenjak** [comment] 2020-01-11 18:51
The failure is actually caused because we returned the wrong iteration pointers - the pointers which were requested instead of the updated pointers. This causes an infinite loop in the case where there is even a single table expansion and was fixed here - https://github.com/hazelcast/hazelcast-enterprise/pull/3488/files#diff-7ea3f9bfae34f461414b165bcb468d2cR202.

**Comment by petrpleshachkov** [comment] 2020-01-13 11:03
@mmedenjak , shall we close this issue then?

**Comment by mmedenjak** [comment] 2020-01-14 06:30
Yes, I think we can close it. I'll add more cache iterator tests in a separate PR.

**Closed by mmedenjak** 2020-01-14 06:30 UTC
Labels: Source: Internal, Team: Core, Type: Test-Failure
