### ISSUE TITLE
QueryOperationHandlerTest test_participant_E_L_B

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#16929] opened 2020-04-25 10:49 UTC
- Fails on `Hazelcast-4.master-ZingJDK8`
- Fails on [Build #165 (Apr 25, 2020 5:18:34 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-ZingJDK8/165/testReport/junit/com.hazelcast.sql.impl.operation/QueryOperationHandlerTest/test_participant_E_L_B/)
- Error
```
Failed to serialize QueryBatchExchangeOperation: Hazelcast instance is not active! (code=-1)
```
- Stacktrace
```
com.hazelcast.sql.impl.QueryException: Failed to serialize QueryBatchExchangeOperation: Hazelcast instance is not active! (code=-1)
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:61)
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:45)
	at com.hazelcast.sql.impl.operation.QueryOperationHandlerImpl.serializeOperation(QueryOperationHandlerImpl.java:369)
	at com.hazelcast.sql.impl.operation.QueryOperationHandlerImpl.submitRemote(QueryOperationHandlerImpl.java:121)
	at com.hazelcast.sql.impl.operation.QueryOperationChannelImpl.submit(QueryOperationChannelImpl.java:40)
	at com.hazelcast.sql.impl.operation.QueryOperationHandlerTest.send(QueryOperationHandlerTest.java:538)
	at com.hazelcast.sql.impl.operation.QueryOperationHandlerTest.sendToParticipant(QueryOperationHandlerTest.java:530)
	at com.hazelcast.sql.impl.operation.QueryOperationHandlerTest.test_participant_E_L_B(QueryOperationHandlerTest.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.instance.impl.DefaultNodeExtension$1.get(DefaultNodeExtension.java:250)
	at com.hazelcast.instance.impl.DefaultNodeExtension$1.get(DefaultNodeExtension.java:247)
	at com.hazelcast.internal.serialization.impl.bufferpool.BufferPoolThreadLocal.get(BufferPoolThreadLocal.java:107)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:157)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:149)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:140)
	at com.hazelcast.sql.impl.operation.QueryOperationHandlerImpl.serializeOperation(QueryOperationHandlerImpl.java:367)
```
- Hiccups
```
Hiccups measured while running test 'test_participant_E_L_B(com.hazelcast.sql.impl.operation.QueryOperationHandlerTest):'
07:58:05, accumulated pauses: 2159 ms, max pause: 18 ms, pauses over 1000 ms: 0
```

kindly check.

**Comment by devozerov** [comment] 2020-09-01 07:08
I analyzed what could be the potential root cause of the failure. It seems that the organization of the test is not reliable: it may happen that a message is sent from an inactive member, which could lead to the error in the stack trace.

**Comment by devozerov** [comment] 2020-09-01 07:10
To summarize, here are the problems with the tests:
1. It may send messages from the stopped member. The fix - submit messages directly to the executor of the remote member
1. It does not properly check for non-started queries. Instead, it should wait for some time, ensuring that no queries are started

**Comment by devozerov** [comment] 2020-09-04 13:11
As discussed with @lazerion, closing this issue for the following reasons:
1. We haven't seen the failure since the initial report on Apr 25
1. The test doesn't look good, and it makes sense to fix it. However, the fix is not trivial, so it is better to do together with the planned protocol fixes https://github.com/hazelcast/hazelcast/issues/16868 (the test in question checks the protocol)

**Closed by devozerov** 2020-09-04 13:11 UTC
Labels: Module: SQL, Source: Internal, Team: Core, Type: Test-Failure

**Comment by lazerion** [comment] 2020-09-27 09:04
@devozerov regarding test fails recently on `Hazelcast-4.master-ZingJDK8` [Build #218 (Sep 25, 2020 5:18:24 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-ZingJDK8/218/testReport/junit/com.hazelcast.sql.impl.operation/QueryOperationHandlerTest/test_participant_E_L_B/). 
Not re-opening per your comment please let me know otherwise.

**Comment by devozerov** [comment] 2020-09-28 07:02
I will create a PR to ignore this test for now. The test will be removed soon in the scope of https://github.com/hazelcast/hazelcast/issues/17563
