### ISSUE TITLE
Map.get(K) retuns null on a object that was just added.

### ISSUE THREAD

**Issue by gfelisberto** [hazelcast/hazelcast#7568] opened 2016-02-22 09:54 UTC
This is related to #6517 . The original issue was marked as solved but when I tried the fixed version problems still persisted.

In #6517 I posted my notes but the issue remained open so I'm opening a new one.

The GIST with the tests is available at: https://gist.github.com/gfelisberto/1075ea5428920c9a2746

I was testing my code with 3.5.5 and results were strange, I was getting null values from cache for things previously added.
I changed my code a bit to detect those issues (the GIST has the new version) and tested with several versions.

3.5.5
After just 16 insertions into the cache it starts triggering eviction of objects that were just added and get(K) returns a null instead of the expected value.

3.6-EA
No eviction is seen in the last loop and it crashes:
Feb 12, 2016 6:45:25 PM com.hazelcast.map.impl.operation.ContainsKeyOperation
SEVERE: [172.18.0.38]:5701 [dev] [3.6-EA] Java heap space
java.lang.OutOfMemoryError: Java heap space
at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.ensureAvailable(ByteArrayObjectDataOutput.java:360)

3.6-EA2
No eviction is seen in the last loop and it crashes:
Feb 12, 2016 7:35:43 PM com.hazelcast.map.impl.operation.ContainsKeyOperation
SEVERE: [172.18.0.38]:5701 [dev] [3.6-EA2] Java heap space
java.lang.OutOfMemoryError: Java heap space
at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.ensureAvailable(ByteArrayObjectDataOutput.java:360)

3.6-RC1
This does not crash with OutOfMemoryError nor does it return null values. But as with version 3.5.5 it starts eviction really early on and releases values that were just added to the cluster not following the LRU policy.

**Comment by gurbuzali** [comment] 2016-02-22 12:14
As I've mentioned in my comment to the other issue https://github.com/hazelcast/hazelcast/issues/6517#issuecomment-166248819, the problem is you are using default partition-count (271). You configure max size as 300 per node and it means 2 per partition (300/271 ceiled ). If more than 2 keys falls into the same partition you end up having eviction. You have set partition-count to 1 (or something small compared to your max-size) for testing.

As for the null returning from `get`, that's a known issue. It happens when the loaded value is picked for eviction. I've tried to address it in this PR but it still needs more work https://github.com/hazelcast/hazelcast/pull/7296

PS: since we've released 3.6 already can you do your testings on it
Thank you for your contributions

**Comment by gfelisberto** [comment] 2016-02-25 09:24
Hi,

I modified the test to have a larger MaxSizeConfig I tested with 3.6 and all went ok.  

I then added a final test where I called map.remove(key) and I get a null value instead of the value that was stored. The logs show:

> Free Memory (MB) = 215
> STORE-LOADING: 0
> STORE-LOADED: 0
> STORE-DELETING: 0
> REMOVED: 0
> STORE-LOADING: 0
> STORE-NOT LOADED: 0
> java.lang.RuntimeException: Clean up loop and remove(key) returns null.

Seems like the value is loaded from the store, them it is removed and then it tries to load it again to return, at that point the value has been removed.

**Comment by gurbuzali** [comment] 2016-06-21 10:41
Sorry for late response, you have a mistake in remove-records loop. you don't increment the keyCount.
So for the first loop you do remove the key:0, for the second loop you again try to remove the key:0 which will return null obviously.
```
        keyCount = 0;
	while (keyCount < limit) {
		String removed = cache.remove(keyCount);
		if (removed == null) {
			throw new RuntimeException("Clean up loop and remove(key) returns null.");
		}
        }
```
I'm goning to close this issue, please feel free to re-open it if you think there is still an issue

**Closed by gurbuzali** 2016-06-21 10:41 UTC
Labels: Team: Core
