### ISSUE TITLE
OutOfMemoryError - Hazelcast v3.6.4

### ISSUE THREAD

**Issue by kirankum** [hazelcast/hazelcast#8827] opened 2016-09-02 08:18 UTC
We're seeing nodes in the cluster hitting OOME every now and then. The logs from the machine (XX.XX.XX.187) which hit this issue recently is attached . The communication problem between XX.XX.XX.187 and XX.XX.XX.184 (which is another node in the cluster) seems to be causing the problem but we're not very sure of it. Once the machine hits OOME, the Hazelcast is shutdown.

```
Following logs are of interest:
2016-08-28T10:30:44:715+0200 - com.hazelcast.cluster.impl.operations.MasterConfirmationOperation WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] Address[XX.XX.XX.184]:45000 has sent MasterConfirmation, but this node is not master!
2016-08-28T10:31:14:715+0200 - com.hazelcast.cluster.impl.operations.MasterConfirmationOperation WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] Address[XX.XX.XX.184]:45000 has sent MasterConfirmation, but this node is not master!
2016-08-28T10:31:44:715+0200 - com.hazelcast.cluster.impl.operations.MasterConfirmationOperation WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] Address[XX.XX.XX.184]:45000 has sent MasterConfirmation, but this node is not master!
2016-08-28T10:31:51:986+0200 - com.hazelcast.nio.tcp.TcpIpConnection INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Connection [Address[XX.XX.XX.184]:45000] lost. Reason: Socket explicitly closed
2016-08-28T10:31:51:987+0200 - com.hazelcast.cluster.ClusterService INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Removing Member [XX.XX.XX.184]:45000
2016-08-28T10:31:51:987+0200 - com.hazelcast.partition.InternalPartitionService INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Removing Member [XX.XX.XX.184]:45000
2016-08-28T10:31:51:988+0200 - com.hazelcast.cluster.ClusterService INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] 

Members [3] {
    Member [XX.XX.XX.186]:45000
    Member [XX.XX.XX.187]:45000 this
    Member [XX.XX.XX.185]:45000
}

2016-08-28T10:31:51:988+0200 - com.hazelcast.transaction.TransactionManagerService INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Committing/rolling-back alive transactions of Member [XX.XX.XX.184]:45000, UUID: 3fb9cff4-a33d-4ca1-b51d-6b387fbb0856
2016-08-28T10:31:52:497+0200 - com.hazelcast.nio.tcp.SocketAcceptorThread INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Accepting socket connection from /XX.XX.XX.184:54655
2016-08-28T10:31:52:497+0200 - com.hazelcast.nio.tcp.TcpIpConnectionManager INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Established socket connection between /XX.XX.XX.187:45000 and /XX.XX.XX.184:54655
2016-08-28T10:32:14:715+0200 - com.hazelcast.cluster.impl.operations.MasterConfirmationOperation WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] MasterConfirmation has been received from Address[XX.XX.XX.184]:45000, but it is not a member of this cluster!
2016-08-28T10:32:14:718+0200 - com.hazelcast.nio.tcp.TcpIpConnection INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Connection [Address[XX.XX.XX.184]:45000] lost. Reason: java.io.EOFException[Remote socket closed!]
2016-08-28T10:32:14:718+0200 - com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] hz._hzInstance_1_dev.IO.thread-in-1 Closing socket to endpoint Address[XX.XX.XX.184]:45000, Cause:java.io.EOFException: Remote socket closed!
2016-08-28T10:32:30:801+0200 - com.hazelcast.nio.tcp.SocketAcceptorThread INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Accepting socket connection from /XX.XX.XX.184:34362
2016-08-28T10:32:30:802+0200 - com.hazelcast.nio.tcp.TcpIpConnectionManager INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Established socket connection between /XX.XX.XX.187:45000 and /XX.XX.XX.184:34362
2016-08-28T10:32:30:812+0200 - com.hazelcast.cluster.impl.operations.JoinCheckOperation INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Ignoring join check from Address[XX.XX.XX.184]:45000, because this node is not master...
2016-08-28T10:34:30:801+0200 - com.hazelcast.cluster.impl.operations.JoinCheckOperation INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Ignoring join check from Address[XX.XX.XX.184]:45000, because this node is not master...
2016-08-28T10:36:30:800+0200 - com.hazelcast.cluster.impl.operations.JoinCheckOperation INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Ignoring join check from Address[XX.XX.XX.184]:45000, because this node is not master...
2016-08-28T10:38:30:802+0200 - com.hazelcast.cluster.impl.operations.JoinCheckOperation INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Ignoring join check from Address[XX.XX.XX.184]:45000, because this node is not master...
2016-08-28T10:38:30:845+0200 - com.hazelcast.nio.tcp.TcpIpConnection INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Connection [Address[XX.XX.XX.184]:45000] lost. Reason: java.io.EOFException[Remote socket closed!]
2016-08-28T10:38:30:845+0200 - com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] hz._hzInstance_1_dev.IO.thread-in-1 Closing socket to endpoint Address[XX.XX.XX.184]:45000, Cause:java.io.EOFException: Remote socket closed!
2016-08-28T10:38:36:857+0200 - com.hazelcast.cluster.ClusterService INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] 

Members [4] {
    Member [XX.XX.XX.186]:45000
    Member [XX.XX.XX.187]:45000 this
    Member [XX.XX.XX.185]:45000
    Member [XX.XX.XX.184]:45000
}

2016-08-28T10:38:36:857+0200 - com.hazelcast.nio.tcp.InitConnectionTask INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Connecting to /XX.XX.XX.184:45000, timeout: 0, bind-any: true
2016-08-28T10:38:36:858+0200 - com.hazelcast.nio.tcp.TcpIpConnectionManager INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Established socket connection between /XX.XX.XX.187:58928 and /XX.XX.XX.184:45000
......
....
2016-08-28T23:07:44:727+0200 - com.hazelcast.cluster.impl.ClusterHeartbeatManager WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] Ignoring heartbeat from Member [XX.XX.XX.186]:45000 since it is expired (now: Sun Aug 28 23:07:47 CEST 2016, timestamp: Sun Aug 28 23:05:12 CEST 2016)
2016-08-28T23:07:44:727+0200 - com.hazelcast.cluster.impl.ClusterHeartbeatManager WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] Ignoring heartbeat from Member [XX.XX.XX.186]:45000 since it is expired (now: Sun Aug 28 23:07:47 CEST 2016, timestamp: Sun Aug 28 23:05:07 CEST 2016)
2016-08-28T23:07:45:056+0200 - com.hazelcast.cluster.impl.ClusterHeartbeatManager WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] Ignoring heartbeat from Member [XX.XX.XX.186]:45000 since it is expired (now: Sun Aug 28 23:07:48 CEST 2016, timestamp: Sun Aug 28 23:05:17 CEST 2016)
2016-08-28T23:07:52:793+0200 - com.hazelcast.cluster.impl.ClusterHeartbeatManager INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] System clock apparently jumped from 2016-08-28T23:05:03.295 to 2016-08-28T23:07:52.792 since last heartbeat (+164497 ms)
2016-08-28T23:07:52:794+0200 - com.hazelcast.cluster.impl.ClusterHeartbeatManager WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] Resetting heartbeat timestamps because of huge system clock jump! Clock-Jump: 164497 ms, Heartbeat-Timeout: 300000 ms
2016-08-28T23:09:34:960+0200 - com.hazelcast.nio.tcp.TcpIpConnection INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Connection [Address[XX.XX.XX.185]:45000] lost. Reason: Socket explicitly closed
2016-08-28T23:09:34:960+0200 - com.hazelcast.nio.tcp.TcpIpConnection INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Connection [Address[XX.XX.XX.186]:45000] lost. Reason: Socket explicitly closed
2016-08-28T23:09:34:961+0200 - com.hazelcast.nio.tcp.TcpIpConnection INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Connection [Address[XX.XX.XX.184]:45000] lost. Reason: Socket explicitly closed
2016-08-28T23:09:34:962+0200 - com.hazelcast.instance.Node WARNING: [XX.XX.XX.187]:45000 [dev] [3.6.4] Terminating forcefully...
2016-08-28T23:09:34:962+0200 - com.hazelcast.instance.Node INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Shutting down connection manager...
2016-08-28T23:09:34:963+0200 - com.hazelcast.instance.Node INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Shutting down node engine...
2016-08-28T23:09:35:291+0200 - com.hazelcast.instance.NodeExtension INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Destroying node NodeExtension.
2016-08-28T23:09:35:291+0200 - com.hazelcast.instance.Node INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] Hazelcast Shutdown is completed in 329 ms.
```

The OutOfMemoryException is caused by NonBlockingSocketWriter.writeQueue which grows to consume around 6GB. 

Could some one please go through the logs and suggest what might be causing this issue? Any help or guidance is appreciated.

Full log: [hazelcast_issue.txt](https://github.com/hazelcast/hazelcast/files/451455/hazelcast_issue.txt)

**Comment by metanet** [comment] 2016-09-02 08:41
It seems 187 is under high load.

Please note this:

`[XX.XX.XX.187]:45000 [dev] [3.6.4] System clock apparently jumped from 2016-08-28T23:05:03.295 to 2016-08-28T23:07:52.792 since last heartbeat (+164497 ms)`

It is supposed to make a heartbeat every 5 secs (by default) but it hasn't made on for more than 2 minutes. Because of this, it ignores heartbeats sent from master and closes the connection. I couldn't see 186's logs here but possibly it is having a similar issue because other nodes in the cluster thinks that 187 is the master, but 187 is not aware of it yet. That is why 187 is complaining about master confirmations, join requests etc.

**Comment by kirankum** [comment] 2016-09-02 08:53
Thanks @metanet, your help is really appreciated. 

Our understanding is that around time 2016-08-28T23:07:52:793+0200 (when you see the system clock jump log), the JVM was dumping the heap into the heap dump file because of high GC overhead OutOfMemory error condition. That, we think, is the reason for the two minute gap before the instance shuts down. We're trying to find out why the server reached the high GC overhead OutOfMemory error. The load was as usual, nothing out of ordinary when compared to when the nodes are working fine. 

During our heap dump analysis of 187, we figured that the OutOfMemoryException is caused by NonBlockingSocketWriter.writeQueue which grows to consume around 6GB. Any guess why this queue might be growing so big?

Also, from the logs, is it safe to infer that only 184 thinks that 187 is the master (which it is not) as we don't see any similar error logs from other two nodes in the cluster? As a result, it might have to do something with node 184?

**Comment by metanet** [comment] 2016-09-02 09:14
187 doesn't seem to be receiving any other suspicious requests from others. Please also see in your log file that the operations sent from 187 to 184 are constantly timing out. As 184 tries to send a split brain join request to 187, it should be having connection problems to all other nodes in the cluster.

**Comment by kirankum** [comment] 2016-09-02 10:00
Thanks for your reply @ahmetmircik 

A snapshot of heap dump at the time of OOM: 
![image](https://cloud.githubusercontent.com/assets/8511651/18200210/6046915c-7121-11e6-8f00-cc72b3380824.png)

We don't have exact repro steps yet, but we suspect if an active node in the cluster reboots (for whatever reasons) and rejoins the cluster, we might hit this issue. This is only a guess. But we're hitting this issue very frequently at most of our customer setups.

We're using Hazelcast as L2 cache with Hibernate. In this particular case, there were four nodes in the cluster. 

This is in response to your comment at https://groups.google.com/forum/#!topic/hazelcast/tga3JzMBiNU

**Comment by kirankum** [comment] 2016-09-02 10:28
@metanet Thanks for your reply.

I didn't notice the time out to 185, thanks for pointing it out. The log line "2016-08-28T00:06:28:208+0200 - com.hazelcast.spi.OperationService INFO: [XX.XX.XX.187]:45000 [dev] [3.6.4] **Invocations:5** timeouts:1 backup-timeouts:0" implies the retries and timeouts? Please correct me if I'm wrong.

In the case of a problem with the network, and assuming that is causing the issue we're seeing, shouldn't the size of 'writeQueue' be restricted to a max size to avoid the OOM error?

**Comment by kormillivijay** [comment] 2016-09-07 21:43
I work with Kiran and investigating on the same issue. Could you please let us know if there is a way to avoid the memory issues? We do see network connectivity issues on node 184 around the same time.  Please find the logs for 184 attached as well. As Kiran mentioned these should not cause OOM errors and Hazelcast should handle network partitioning issues gracefully. Could you please advise if there is any configuration we are missing? When I search online for these problem, I do not find much references, so I am not sure if we there are some basic configuration settings we are missing.

[node 184 log.txt](https://github.com/hazelcast/hazelcast/files/460396/node.184.log.txt)

**Comment by enesakar** [comment] 2016-11-23 11:38
very broad request regarding network and memory management. closing the issue. when you have a reproducer code, please re-open it.

**Closed by enesakar** 2016-11-23 11:38 UTC
