### ISSUE TITLE
hazelcast client java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by shahbour** [hazelcast/hazelcast#14540] opened 2019-02-21 14:21 UTC
Hello , i am running hazelcast 3.11 server and client. Every thing was working good for more than 3 month . Yesterday we had increase of objects to be cached , I started getting OOM errors at the client side inside my JVM application. I tried increasing the memory for the JVM but i am still getting OOM even some time i am getting it when trying to put first object . 

Can you please help me check how to set the heap memory for hazelcast client , also how can i tell what is leading to OOM when we just started the client .

Below is my configuration 

```
    @Bean
    public HazelcastInstance getHazelcastInstance() {
        ClientConfig config = new ClientConfig();

        config.getNetworkConfig().addAddress(serviceIp);
        /*config.setNativeMemoryConfig(config.getNativeMemoryConfig()
                .setEnabled(true)
                .setSize(new MemorySize(1536))); //Set Memory to 1.5GB instead of default 512*/

        EvictionConfig evictionConfig = new EvictionConfig()
                .setMaximumSizePolicy(EvictionConfig.MaxSizePolicy.ENTRY_COUNT)
                .setSize(500)
                .setEvictionPolicy(EvictionPolicy.LFU);


        NearCacheConfig rateSheet = new NearCacheConfig()
                .setName("cdr-import-ratesheet-*")
                .setTimeToLiveSeconds(3600)
                .setMaxIdleSeconds(1800)
                .setInMemoryFormat(InMemoryFormat.OBJECT)
                .setEvictionConfig(evictionConfig);

        NearCacheConfig cdrImport = new NearCacheConfig()
                .setName("cdr-import*")
                .setTimeToLiveSeconds(600)
                .setMaxIdleSeconds(300)
                .setInMemoryFormat(InMemoryFormat.OBJECT)
                .setEvictionConfig(evictionConfig);



        config.addNearCacheConfig(rateSheet);
        config.addNearCacheConfig(cdrImport);

        return HazelcastClient.newHazelcastClient(config);
    }
```

and the error i am getting

```
2019-02-21 10:38:25.166 [               ] DEBUG 1 --- [   scheduling-1] c.t.config.WarehouseConfiguration        : Aggregator message expired with count 34
2019-02-21 10:38:28.517 [               ] ERROR 1 --- [    container-1] o.s.a.r.l.SimpleMessageListenerContainer : Consumer thread error, thread abort.
java.lang.OutOfMemoryError: Java heap space
	at ------ submitted from ------.(Unknown Source) ~[na:na]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:225) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:219) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.client.proxy.ClientMapProxy.setInternal(ClientMapProxy.java:727) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.client.proxy.NearCachedClientMapProxy.setInternal(NearCachedClientMapProxy.java:353) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.client.proxy.ClientMapProxy.set(ClientMapProxy.java:705) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.client.proxy.ClientMapProxy.set(ClientMapProxy.java:1682) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.spring.cache.HazelcastCache.put(HazelcastCache.java:114) ~[hazelcast-spring-3.11.jar!/:3.11]
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doPut(AbstractCacheInvoker.java:87) ~[spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport$CachePutRequest.apply(CacheAspectSupport.java:820) ~[spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:429) ~[spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at com.teltacworldwide.serviceImpl.RateSellServiceImpl$$EnhancerBySpringCGLIB$$e1eb134f.findByRateSheetId(<generated>) ~[classes!/:0.1.11-SNAPSHOT]
	at com.teltacworldwide.utility.EnrichCDR.doTransform(EnrichCDR.java:162) ~[classes!/:0.1.11-SNAPSHOT]
	at org.springframework.integration.transformer.AbstractTransformer.transform(AbstractTransformer.java:33) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.transformer.MessageTransformingHandler.handleRequestMessage(MessageTransformingHandler.java:108) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:162) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:451) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:400) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:415) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:334) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:225) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:129) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:162) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:451) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:400) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:415) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:334) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:225) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:129) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:162) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:451) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:400) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203) ~[spring-integration-core-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$600(AmqpInboundChannelAdapter.java:58) ~[spring-integration-amqp-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.createAndSend(AmqpInboundChannelAdapter.java:237) ~[spring-integration-amqp-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:204) ~[spring-integration-amqp-5.1.0.RELEASE.jar!/:5.1.0.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1477) ~[spring-rabbit-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1400) ~[spring-rabbit-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1387) ~[spring-rabbit-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1366) ~[spring-rabbit-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:848) ~[spring-rabbit-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:832) ~[spring-rabbit-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:78) ~[spring-rabbit-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1073) ~[spring-rabbit-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

```

I did a heapdump but I do not know how to look into it

**Comment by jerrinot** [comment] 2019-02-21 14:39
hello @shahbour,

are you allowed to share the heapdump? I could have a look. Also please be aware heapdump contains a complete content of your Java heap memory so please make sure it does not contain any secret before sharing it. 

Cheers,
Jaromir

**Comment by jerrinot** [comment] 2019-02-21 14:41
also it's quite suspicious you are getting this on the first put. are your Hazelcast servers running fine?

**Comment by shahbour** [comment] 2019-02-21 14:41
@jerrinot yes it is ok with me, how can I share it with you ? it is 22 MB

**Comment by jerrinot** [comment] 2019-02-21 14:43
upload it somewhere and send me a link to `jaromir@hazelcast.com`. 

however if the client heapdump is just 22MB then it's very likely NOT caused by a memory pressure on the client. please check memory utilization of your Hazelcast servers too.

**Comment by shahbour** [comment] 2019-02-21 14:46
> also it's quite suspicious you are getting this on the first put. are your Hazelcast servers running fine?

This is not happening all the time, but yes when trying several options some times it did happen at the first beginning.

and yes the server is running perfectly, I am using kuberentes and it is not having any error .

```
INFO: [10.35.0.19]:5701 [dev] [3.11] processors=12, physical.memory.total=23.4G, physical.memory.free=1.6G, swap.space.total=0, swap.space.free=0, heap.memory.used=714.0M, heap.memory.free=6.5M, heap.memory.total=720.5M, heap.memory.max=910.5M, heap.memory.used/total=99.10%, heap.memory.used/max=78.42%, minor.gc.count=13260, minor.gc.time=184130ms, major.gc.count=1111, major.gc.time=383454ms, load.process=0.13%, load.system=19.43%, load.systemAverage=0.81, thread.count=69, thread.peakCount=122, cluster.timeDiff=-16, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=69736812, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=2, connection.active.count=3, client.connection.count=2, connection.count=1
```

for heap dump , it is 90 mb , 22 mb after compression

**Comment by jerrinot** [comment] 2019-02-21 14:53
Did you grap the heapdump right after the OOM incident? It's not very useful from a happy run. 

See e.g. [this post](https://dzone.com/articles/how-to-capture-java-heap-dumps-7-options) how to grab a heapdump right after the OOM. The #2 `-XX:+HeapDumpOnOutOfMemoryError` would be great. 


How many servers you have in your cluster? Verbose GC logs would help a lot. The should be enabled on both client(s) and server(s). GC logs have very low overhead, the exact configuration depends on your JVM. You can use this as an example: https://blog.codecentric.de/2014/01/nutzliche-jvm-flags-teil-8/

**Comment by jerrinot** [comment] 2019-02-21 15:37
Hi,

I couldnt see anything suspicious in the heapdump. In the fact it's pretty much empty - as expected given its size. 

If you have just 1 server and start another one than (by default) it won't increase your capacity - as with the extra server Hazelcast will start creating a backup of each entry you store. There is no backup when you have just a single server. The simplest thing you can do is to disable backups. See this for details: https://docs.hazelcast.org/docs/3.11.2/manual/html-single/index.html#backing-up-maps

**Comment by shahbour** [comment] 2019-02-25 05:59
Hello @jerrinot , I already had two and what I did was I increased the memory of each POD (i am using kubernetes) from that time till now I did not face any OOM error so mostly it was a server issue as it is working now perfectly as before.

I did not see any error on the Server Pod logs, is this how it should work?

**Comment by jerrinot** [comment] 2019-02-25 13:13
yeah, you should see an error in server logs. Also I'd recommend you to always run your servers with verbose gc logs enabled. I am closing this issue for now, feel free to-open it in the future.

**Closed by jerrinot** 2019-02-25 13:13 UTC

**Comment by boroda4436** [comment] 2019-03-29 09:20
Hi guys, faced with a similar issue. Please see screenshot.
Seems like com.hazelcast.web.spring.SpringAwareWebFilter occupies too much heap memory.
Any ideas?

Heap dump was created using this command:
jmap -dump:format=b,file=/home/my/dump/all_7 <MY_PID>

I have used [Eclipce Memory Analyzer](https://www.eclipse.org/mat/downloads.php)

![image](https://user-images.githubusercontent.com/13794896/55222194-f765a200-5213-11e9-9524-ac3d488019fb.png)

**Comment by siva-vs** [comment] 2020-07-01 07:19
Hi, I am seeing a similar issue in my env as well. 

We are using a 3.11.2 version. The following are the Heapdump details. Could you please review and suggest how to resolve this


![image](https://user-images.githubusercontent.com/67679080/86214635-09fa2400-bb99-11ea-9992-b754c1fae010.png)


![image](https://user-images.githubusercontent.com/67679080/86214723-25652f00-bb99-11ea-8ed2-b8e8f8d49279.png)


![image](https://user-images.githubusercontent.com/67679080/86214762-34e47800-bb99-11ea-9e57-b3e2143475f5.png)
