### ISSUE TITLE
Cluster is locking when node is down 

### ISSUE THREAD

**Issue by chernser** [hazelcast/hazelcast#9321] opened 2016-11-25 11:41 UTC
Issue is well described in Cluster is locking when node is down #1688 (https://github.com/hazelcast/hazelcast/issues/1688)

When one node goes down or becomes slow - whole cluster timeouts.

**Comment by chernser** [comment] 2016-11-25 12:28
It is also not clear how to handle timeouted operations like this: 

com.hazelcast.core.OperationTimeoutException: LockOperation invocation failed to complete due to operation-heartbeat-timeout. 
Current time: 2016-11-25 09:25:23.688. 
Total elapsed time: 97940 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2016-11-25 09:25:16.733. Invocation{op=com.hazelcast.concurrent.lock.operations.LockOperation{serviceName='hz:impl:lockService', identityHash=736537881, partitionId=93, replicaIndex=0, callId=0, invocationTime=1480065825698 (2016-11-25 09:23:45.698), waitTimeout=37000, callTimeout=37000, namespace=com.hazelcast.concurrent.lock.InternalLockNamespace@ce6cf218, threadId=2310}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=37000, firstInvocationTimeMs=1480065825748, firstInvocationTime='2016-11-25 09:23:45.748', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.11.132.241]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=5, /10.11.132.97:39761->/10.11.132.241:5701, endpoint=[10.11.132.241]:5701, alive=true, type=MEMBER]


In this case heartbeat has not been ever sent. So node is actually down, but not removed from the list.

**Comment by enesakar** [comment] 2016-11-25 12:46
which version? any test code to reproduce?

**Comment by chernser** [comment] 2016-11-25 12:49
Good day, 
the version is 3.7.2 
Unfortunately there is no code to reproduce the problem.

**Comment by mozotom** [comment] 2017-06-20 19:58
Here's something similar we've seen in our logs that locked up entire cluster, when one node had problems with RAID controller. (xxx.xxx.xxx.xxx was a valid IP)
```
com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [xxx.xxx.xxx.xxx]:5701
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:63)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:83)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:156)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:148)
	at com.hazelcast.client.proxy.ClientMapProxy.getInternal(ClientMapProxy.java:291)
	at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:286)
 ```
we're using
```
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>3.8</version>
        </dependency>
```

**Comment by mmedenjak** [comment] 2017-07-11 18:48
@mozotom that looks like an exception on the client (that there is no connection to the IP). Can you provide the member logs from the time the cluster was locked up?

**Comment by mmedenjak** [comment] 2017-07-11 18:54
@chernser can you try lowering down the property `hazelcast.max.no.heartbeat.seconds` to something like 60 seconds? It controls the time that a member waits before declaring a node dead. You can lower it to get better responsiveness to crashed nodes but lowering it too much will destabilise your cluster and cause members to be kicked out even when they are alive but temporarily not responding.

**Comment by memnoth** [comment] 2017-11-02 14:22
This problem is ongoing in 3.9.

# TEST CASE
2 nodes, one of them is on Host, other is on a container of Docker.
An application I made runs on both environment and all code lines and hazelcast version are same.
## Environment information
Docker
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
Host
```
Ubuntu 16.04.3
Kernel : 4.4.0-98
Java 8
```
## What I did
While the application is running on both, I let the container stop, not the application. (like a unexpected situation.)
Since the situation has happened, other node still lived gets into locking and a heartbeat timeout raised.
The log is as following,
```
Members {size:2, ver:6} [
	Member [172.17.0.1]:5701 - ded69740-c1a2-4051-b3f8-43c407cbebe7 this
	Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc
]

11월 02, 2017 10:31:40 오후 com.hazelcast.internal.partition.impl.MigrationManager
정보: [172.17.0.1]:5701 [dev] [3.9] Re-partitioning cluster data... Migration queue size: 271
11월 02, 2017 10:31:42 오후 com.hazelcast.internal.partition.impl.MigrationThread
정보: [172.17.0.1]:5701 [dev] [3.9] All migration tasks have been completed, queues are empty.
11월 02, 2017 10:31:50 오후 com.hazelcast.nio.tcp.TcpIpConnection
정보: [172.17.0.1]:5701 [dev] [3.9] Connection[id=3, /172.17.0.1:5701->/172.17.0.2:55822, endpoint=[172.17.0.2]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
11월 02, 2017 10:31:50 오후 com.hazelcast.nio.tcp.TcpIpConnector
정보: [172.17.0.1]:5701 [dev] [3.9] Connecting to /172.17.0.2:5701, timeout: 0, bind-any: true
11월 02, 2017 10:31:50 오후 com.hazelcast.nio.tcp.TcpIpConnector
정보: [172.17.0.1]:5701 [dev] [3.9] Could not connect to: /172.17.0.2:5701. Reason: SocketException[Connection refused to address /172.17.0.2:5701]
11월 02, 2017 10:31:50 오후 com.hazelcast.nio.tcp.TcpIpConnector
정보: [172.17.0.1]:5701 [dev] [3.9] Connecting to /172.17.0.2:5701, timeout: 0, bind-any: true
11월 02, 2017 10:32:39 오후 com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
경고: [172.17.0.1]:5701 [dev] [3.9] This node does not have a connection to Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc
11월 02, 2017 10:32:44 오후 com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
경고: [172.17.0.1]:5701 [dev] [3.9] This node does not have a connection to Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc
11월 02, 2017 10:32:49 오후 com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
경고: [172.17.0.1]:5701 [dev] [3.9] This node does not have a connection to Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc
11월 02, 2017 10:32:49 오후 com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
경고: [172.17.0.1]:5701 [dev] [3.9] Suspecting Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc because it has not sent any heartbeats since 2017-11-02 22:31:49.265. Now: 2017-11-02 22:32:49.285, heartbeat timeout: 60000 ms, suspicion level: 1.00
11월 02, 2017 10:32:49 오후 com.hazelcast.internal.cluster.impl.MembershipManager
정보: [172.17.0.1]:5701 [dev] [3.9] Removing Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc
11월 02, 2017 10:32:49 오후 com.hazelcast.transaction.TransactionManagerService
정보: [172.17.0.1]:5701 [dev] [3.9] Committing/rolling-back alive transactions of Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc, UUID: a1330d2f-998f-46e4-b8ad-ca5a76f514cc
11월 02, 2017 10:32:49 오후 com.hazelcast.internal.cluster.ClusterService
정보: [172.17.0.1]:5701 [dev] [3.9] 

Members {size:1, ver:7} [
	Member [172.17.0.1]:5701 - ded69740-c1a2-4051-b3f8-43c407cbebe7 this
]

11월 02, 2017 10:32:49 오후 com.hazelcast.internal.partition.impl.MigrationManager
정보: [172.17.0.1]:5701 [dev] [3.9] Partition balance is ok, no need to re-partition cluster data... 
11월 02, 2017 10:32:56 오후 com.hazelcast.nio.tcp.TcpIpConnector
정보: [172.17.0.1]:5701 [dev] [3.9] Could not connect to: /172.17.0.2:5701. Reason: SocketException[호스트로 갈 루트가 없음 to address /172.17.0.2:5701]
```
But this doesn't happen when I run the same application in different jvm on the same **Host**.
Open 2 terminal, then run it on each terminal.
## What I am going to do
1. Make another container with ``--net=host`` option, I have heard that there was a network issue from a Hazelcast Engineer.
2. Test this problem in wired network environment with a few physical nodes as Raspberry Pi 3.

I run Hazelcast in local wireless network environment for my experiment and I need to solve the problem for next step.
I hope this logs can be helped for it and will be fixed it as soon as possible.
Thank you!

**Comment by artem-zinnatullin** [comment] 2018-06-20 23:14
Can confirm, still a problem with `3.10.2`, client just freezes indefinitely (def more than 30 seconds which is enough for our k8s setup to kill the client) even though I have lowered all network related timeouts:

```kotlin
private fun initHazelcastInstance(): HazelcastInstance {
    val clientNetworkConfig = ClientNetworkConfig()
            .addAddress(hazelcastClusterHostname)
            .setConnectionAttemptLimit(3)
            .setConnectionAttemptPeriod(2 * 1000)
            .setConnectionTimeout(7 * 1000)
            .setRedoOperation(true)

    val connectionStrategyConfig = ClientConnectionStrategyConfig()
            .setReconnectMode(ReconnectMode.ASYNC)
            .setAsyncStart(false)

    val clientConfig = ClientConfig()
            .setNetworkConfig(clientNetworkConfig)
            .setConnectionStrategyConfig(connectionStrategyConfig)
            .setProperty("hazelcast.max.no.heartbeat.seconds", "8") // How long to wait before declaring HZ node dead.

    val newHazelcastInstance = HazelcastClient.newHazelcastClient(clientConfig)

    newHazelcastInstance.lifecycleService.addLifecycleListener { lifeCycleEvent ->
        L.i("Hazelcast lifecycle event: $lifeCycleEvent")
    }

    return newHazelcastInstance
}
```

Reinstantiating it doesn't help either, however when k8s restarts the client, it works fine with downscaled cluster, so some bad state is likely kept in memory.

Not very good for system advertized as HA heh, do we miss something in the setup?

**Comment by jerrinot** [comment] 2018-06-22 09:01
hi @artem-zinnatullin what is your scenario? how exactly are you down-scaling the cluster?

**Comment by googlielmo** [comment] 2018-06-26 11:56
Hi @artem-zinnatullin do you have more details to share? This issue was added to the 3.11 milestone.

**Comment by artem-zinnatullin** [comment] 2018-07-05 21:22
Sorry for delay, I was on vacation, here is the scenario

Environment:

- Testing on local k8s setup with minikube 0.28.0, k8s 1.10.0
- Official Hazelcast k8s docker image https://hub.docker.com/r/hazelcast/hazelcast-kubernetes/
- Nodes are able to autodiscover each other
- 3 Nodes are running by default (doesn't really matter)
- Java service using Hazelcast client lib 3.10.2 uses Hazelcast cluster as JCache cache

#### Scenario 1 (works ok):

- Upscale with `kubectl scale deployment --replicas 4`
- All nodes and the Java service report that new node is discovered and joined cluster in logs

#### Scenario 2 (breaks Hazelcast client lib in the Java service):

- Downscale with `kubectl scale deployment --replicas 2` (looks like downscaling to any amount of nodes less than before can cause same behavior, but for sake of reproducibility let's downscale to below than default)
- Hazelcast nodes report new set of cluster nodes in logs 
- In few seconds after that all attempts to work with Hazelcast cluster from the Java service result in calls getting blocked and basically hang up the Java service threads
- Hazelcast nodes however seem to work
- My attempts to handle calls to Hazelcast with timeouts and reinstantiating JCache setup with new `HazelcastInstance` obj don't help, it connects to downscaled cluster but still hangs the calls, looks like some bad static state is saved in memory
- **When k8s restarts the Java service instance due to bad health check, new instance of Java service is able to work just fine with downscaled Hazelcast cluster**

So it doesn't seem to be Hazelcast cluster issue but rather problem of Hazelcast java client lib.

**Comment by leszko** [comment] 2018-11-08 10:54
@artem-zinnatullin, in your configuration, you have: 
```
val clientNetworkConfig = ClientNetworkConfig().addAddress(hazelcastClusterHostname)
```
This looks like you're using a static IP configuration to connect to a Hazelcast member (even if you pass a hostname of a k8 service, it's still a static configuration). That's not correct, since the IPs of Hazelcast members can change. That can happen during scaling down (some IPs do not exist anymore).

What you should do instead is to use the [Kubernetes Discovery Strategy](https://github.com/hazelcast/hazelcast-kubernetes) for the client which is run in the same k8 cluster. The configuration would look something like:
```
 val clientNetworkConfig = ClientNetworkConfig().getDiscoveryConfig().addDiscoveryStrategyConfig(new DiscoveryStrategyConfig(new HazelcastKubernetesDiscoveryStrategyFactory(), properties));
```

I verified yesterday and scaling (up/down) works fine with such approach. No client disconnections.

**Note 1**: While scaling down too fast, you may lose some Hazelcast data (if you have a lot of data and killing Hazelcast node is faster than migrating the data). We'll publish soon a blog post on how to make sure your data is not lost during scale-down.

**Note 2**: If you use a client which is outside of your k8 cluster, then you need to use a Dumb Client (`clientConfig.getNetworkConfig().setSmartRouting(false)`). This client may disconnect while scaling down. We're working on a solution for the external Smart Client. You can check a [related GH issue](https://github.com/hazelcast/hazelcast-kubernetes/issues/77).

**Comment by leszko** [comment] 2018-12-21 10:21
Closing due to inactivity. Feel free to reopen if needed.

**Closed by leszko** 2018-12-21 10:21 UTC
Labels: Priority: High, Source: Community, Team: Client, Team: Core, Team: Integration, Type: Defect

**Comment by Boiarshinov** [comment] 2021-02-19 11:31
@artem-zinnatullin I think that problem also in the property name.
You add property `hazelcast.max.no.heartbeat.seconds`, but in the client configuration there is no property with such name. You should use property name `hazelcast.client.heartbeat.timeout` to configure how long to wait before declaring HC node dead.

Property `hazelcast.max.no.heartbeat.seconds` appliable only for hazelcast node configuration.

Look at the `com.hazelcast.client.spi.properties.ClientProperty` class to find all possible client properties.  

Note: actual for v.3.11.1 and I checked also for v.3.10.2
