### ISSUE TITLE
can't access cache from partition thread

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#5710] opened 2015-07-15 10:06 UTC
Hi,

Hazelcast 3.5. A single node HZ cluster, two distibuted caches. At app statup I register listener on one of the caches:

			String uuid = xdmCache.addEntryListener(this, this, false);

the MapListener and Predicate are implemented in the same bean. The Predicate.apply method is:

	@Override
	public boolean apply(Entry<XDMDataKey, XDMElements> mapEntry) {  

		return idxCache.containsKey(mapEntry.getKey().getPathId());
	}

when I perform putAll on xdmCache the apply method was invoked many times in a row, but when it tries to check key in another idxCache HZ throws the following exception:

```
2015-07-14 17:36:27.901 [hz.test.partition-operation.thread-2] ERROR com.hazelcast.map.impl.operation.PutOperation - [localhost]:10000 [test] [3.5] Thread[hz.test.partition-operation.thread-2,5,test] cannot make remote call: ContainsKeyOperation{}
java.lang.IllegalThreadStateException: Thread[hz.test.partition-operation.thread-2,5,test] cannot make remote call: ContainsKeyOperation{}
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:196) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:168) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:268) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.map.impl.proxy.MapProxySupport.containsKeyInternal(MapProxySupport.java:624) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.containsKey(MapProxyImpl.java:206) ~[hazelcast-all-3.5.jar:3.5]
	at com.bagri.xdm.cache.hazelcast.impl.IndexManagementImpl.apply(IndexManagementImpl.java:344) ~[classes/:na]
	at com.hazelcast.map.impl.QueryEventFilter.eval(QueryEventFilter.java:47) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.map.impl.MapEventPublisherImpl.processQueryEventFilter(MapEventPublisherImpl.java:296) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.map.impl.MapEventPublisherImpl.applyEventFilter(MapEventPublisherImpl.java:216) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.map.impl.MapEventPublisherImpl.publishEvent(MapEventPublisherImpl.java:112) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.map.impl.MapEventPublisherImpl.publishEvent(MapEventPublisherImpl.java:95) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.map.impl.MapEventPublisherImpl.publishEvent(MapEventPublisherImpl.java:89) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.map.impl.operation.BasePutOperation.afterRun(BasePutOperation.java:57) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.afterRun(OperationRunnerImpl.java:209) [hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:139) [hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:154) [hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:110) [hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101) [hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76) [hazelcast-all-3.5.jar:3.5]
```

The cache idxCache has also near cache configured. Please have a look,

Thanks, Denis

**Comment by pveentjer** [comment] 2015-07-15 13:40
Can you make a test that reproduces the problem? This makes it a lot easier for us to figure out what is happening.

**Comment by dsukhoroslov** [comment] 2015-07-15 15:53
Hi Peter. Ok, will try to prepare a test. Actually, the issue is also discussed here: https://groups.google.com/forum/#!topic/hazelcast/KntjlJTDOTQ, may be it is a correct behaviour and just needs an update in documentation.

**Comment by pveentjer** [comment] 2015-07-15 18:32
It could be.. but it could also be illegal behavior. If you make me a test case, I can quickly figure out what is happening.

**Comment by dsukhoroslov** [comment] 2015-07-16 06:54
I did a simple test and I can't reproduce the issue from it. The test behaves very similair to what I see from the real system, except one thing: in the ClassicOperationExecutor.isInvocationAllowedFromCurrentThread method the test passes the last check, but in run-time it does not:

    public boolean isInvocationAllowedFromCurrentThread(Operation op, boolean isAsync) {
        ...........
        // we are only allowed to invoke from a PartitionOperationThread if the operation belongs to that
        // PartitionOperationThread.
        PartitionOperationThread partitionThread = (PartitionOperationThread) currentThread;
        return toPartitionThreadIndex(op.getPartitionId()) == partitionThread.threadId;
    }

What can I do to assign operation to a thread in runtime properly?

**Comment by pveentjer** [comment] 2015-07-16 07:01
My guess is that there is an issue in the checking mechanism. So there is nothing on your side you can do. 

For me it would be extremely helpful if I can get a test; even though it is hard to reproduce.

**Comment by dsukhoroslov** [comment] 2015-07-16 09:22
Ok, here is the test. The issue is in different partitioning between these two caches:

<code>
public class PartitionDeadlockTest implements EntryAddedListener<String, String>, Predicate<String, String> {

	private IMap<Integer, String> idxCache;
	private boolean applied = false;
	
	@Test
	public void testPartitionOperation() throws Exception {
		
		Config config = new Config();
		NetworkConfig network = config.getNetworkConfig();
		JoinConfig join = network.getJoin();
		join.getMulticastConfig().setEnabled(false);

		MapConfig xConfig = new MapConfig();
		xConfig.setName("data-cache").setInMemoryFormat(InMemoryFormat.OBJECT); 
		config.addMapConfig(xConfig);
		
		MapConfig iConfig = new MapConfig();
		iConfig.setName("idx-cache");
		NearCacheConfig nConfig = new NearCacheConfig();
		nConfig.setInMemoryFormat(InMemoryFormat.OBJECT).
			setEvictionPolicy("LRU").
			setMaxIdleSeconds(0).
			setTimeToLiveSeconds(0).
			setMaxSize(0).
			setInvalidateOnChange(true);
		iConfig.setNearCacheConfig(nConfig);
		config.addMapConfig(iConfig);

		config.setProperty("hazelcast.logging.type", "slf4j");
		
		HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
		
		IMap<String, String> dataCache = hz.getMap("data-cache");
		String uuid = dataCache.addEntryListener(this, this, false);

		idxCache = hz.getMap("idx-cache");
		idxCache.put(5, "value5");
		
		HashMap<String, String> data = new HashMap<>();
		for (int i=0; i < 10; i++) {
			data.put(String.valueOf(i), "value" + i);
		}
		dataCache.putAll(data);
		
		Thread.sleep(1000); //000);
		hz.shutdown();
		assertTrue(applied);
	}

	@Override
	public boolean apply(Entry<String, String> mapEntry) {
		return idxCache.containsKey(Integer.parseInt(mapEntry.getKey()));
	}

	@Override
	public void entryAdded(EntryEvent<String, String> event) {
		applied = true;
	}
}
</code>

**Comment by pveentjer** [comment] 2015-07-18 12:10
Thanks for your test. I have been playing with it. One thing I have observed is that the exception thrown in the apply method is thrown away. If you slap a try/catch(RuntimeException) around it and you print the stacktrace you see the following exception:

```
java.lang.IllegalThreadStateException: Thread[hz._hzInstance_1_dev.partition-operation.thread-0,5,_hzInstance_1_dev] cannot make remote call: ContainsKeyOperation{}
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:200)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:172)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:277)
	at com.hazelcast.map.impl.proxy.MapProxySupport.containsKeyInternal(MapProxySupport.java:623)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.containsKey(MapProxyImpl.java:206)
	at com.hazelcast.PartitionDeadlockTest$MyPredicate.apply(PartitionDeadlockTest.java:85)
	at com.hazelcast.map.impl.QueryEventFilter.eval(QueryEventFilter.java:46)
	at com.hazelcast.map.impl.MapEventPublisherImpl.processQueryEventFilter(MapEventPublisherImpl.java:296)
	at com.hazelcast.map.impl.MapEventPublisherImpl.applyEventFilter(MapEventPublisherImpl.java:216)
	at com.hazelcast.map.impl.MapEventPublisherImpl.publishEvent(MapEventPublisherImpl.java:112)
	at com.hazelcast.map.impl.MapEventPublisherImpl.publishEvent(MapEventPublisherImpl.java:95)
	at com.hazelcast.map.impl.MapEventPublisherImpl.publishEvent(MapEventPublisherImpl.java:89)
	at com.hazelcast.map.impl.operation.BasePutOperation.afterRun(BasePutOperation.java:56)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.afterRun(OperationRunnerImpl.java:232)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:162)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:180)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:130)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:122)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:97)
```

**Comment by pveentjer** [comment] 2015-07-18 12:30
The cause of your problem is the following. Your idxCache uses a Integer as key and your dataCache uses a String as key. Integer 1 will be mapped to a different partition than String "1". If you convert them so they use the same type as key, the exception is not thrown anymore.

**Comment by pveentjer** [comment] 2015-07-18 13:03
I have created a new ticket for eating the exception:

https://github.com/hazelcast/hazelcast/issues/5710

I'm going to close this ticket since the cause is incorrect usage of the API.

**Closed by pveentjer** 2015-07-18 13:03 UTC
