### ISSUE TITLE
PhoneHomeIntegrationTest.testMapLatenciesWithMapStore test fails on Windows Oracle JDK8

### ISSUE THREAD

**Issue by PavloBida** [hazelcast/hazelcast#18933] opened 2021-06-18 12:01 UTC
**Failing test**
com.hazelcast.internal.util.phonehome.PhoneHomeIntegrationTest.testMapLatenciesWithMapStore

**Error message**
```
Expected 'mpgtlams' to be greater than or equal to 200, but was 199
```

**Stacktrace**
```
java.lang.AssertionError: Expected 'mpgtlams' to be greater than or equal to 200, but was 199
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.test.HazelcastTestSupport.assertGreaterOrEquals(HazelcastTestSupport.java:1398)
	at com.hazelcast.internal.util.phonehome.PhoneHomeIntegrationTest.testMapLatenciesWithMapStore(PhoneHomeIntegrationTest.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
**Jenkins build:**
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-Windows-OracleJDK8/311/

**Comment by olukas** [comment] 2021-06-21 09:09
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/18724 (this also failed on `4.2.z` branch hence it should have milestone `4.2.2` as it is in original issue). Feel free to reopen this issue if I missed something.

**Closed by olukas** 2021-06-21 09:09 UTC
Labels: Source: Internal, Team: Management Center, Type: Test-Failure
