### ISSUE TITLE
Predicate that is `IndexAwarePredicate` doesnt have its `apply` method invoked

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast#12352] opened 2018-02-14 16:32 UTC
When using Indexes, an `IndexAwarePredicate` doesnt have its `apply` method invoked - so despite whatever code maybe present in there its not used - only the index operation is performed and the apply filter is silently ignored.  

It would be helpful if the apply method was invoked since we could get different runtime results when an index is present or not - and I dont believe that data results should change simply due to a HZ configuration change.

**Comment by jerrinot** [comment] 2018-02-15 08:37
I believe this is a feature, not a bug. 

When the `IndexAwarePredicate::isIndexed` returns true then Hazelcast will call just the `filter()` method and not `apply()`. The `apply()` is meant to be used when the predicate cannot be evaluated via accessing an index. 

The `apply()` of `IndexAwarePredicate` still should be used when `isIndexed()` returns false. 

I suppose you are using a custom predicate and you want to use the index to pre-filter and then use the `apply()` for further filtering? Is it so? If yes then you can always compose 2 predicate with `Predicates.and()` <- the first one will pre-select entries with an index and the 2nd one with do further filtering.

**Comment by pveentjer** [comment] 2018-02-15 08:46
To me it smells like a bug. If a predicate is index aware, the it is a marker that one or more indices can be used. But whatever is found using an index, still needs to be validated using the predicate.

**Comment by jerrinot** [comment] 2018-02-15 08:56
That is a contract of `IndexAwarePredicate`. We have to make this contract explciit. 

Think of `EqualsPredicate`: It is `IndexAware` because it can leverage an index when available. but when the index is NOT available then it will use the `apply()` method.

Now if we change this behaviour as @vertex-github  would like to then `A = foo` would first use the index to get all matching entries and then iterate over them again and call the `apply()` method?

**Comment by pveentjer** [comment] 2018-02-15 08:57
If I just look at the name, IndexAware, it means that it support indices. It doesn't mean that whatever logic is implemented in the predicate should be skipped. 

So it isn't intuitive.

**Comment by vertex-github** [comment] 2018-02-15 11:56
This behaviour means that business logic changes when you toggle Indexing.
That's extremely odd behavior and totally unexpected.

**Comment by jerrinot** [comment] 2018-02-15 11:59
the strategy for a predicate evaluation changes when an index is unavailable. that's the whole point of having an index, isn't it?

**Comment by vertex-github** [comment] 2018-02-15 12:07
I don't believe so. I view Indexing as purely for performance - I do not
expect any busines logic changes. This can and will lead to bad data
selections in queries. Throw a poll out there and ask the devs :-)



On Feb 15, 2018 06:59, "Jaromir Hamala" <notifications@github.com> wrote:

the strategy for a predicate evaluation changes when an index is
unavailable. that's the whole point of having an index, isn't it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hazelcast/hazelcast/issues/12352#issuecomment-365906548>,
or mute the thread

**Comment by mmedenjak** [comment] 2018-02-15 12:39
I see no issue here other than the contract is unclear and should be documented.

It is the responsibility (a non-intuitive and non-trivial one) of the implementer to implement a correct `filter` method that acts accordingly. One can always invoke the `apply` method from the `filter` method. Sometimes you need to call `apply`, sometimes you don't. I don't think we need to impose the necessity to call the `apply` method in all cases. If the user can simply leverage the methods on the index, he may implement an `IndexAwarePredicate`.

Thus said, we will improve the javadoc to make this clear.

**Comment by vertex-github** [comment] 2018-02-15 13:09
If I enable Indexing on a database, I get the same resultset, just faster.

If I put higher grade gas in my car, I dont expect different car behavior other than performance changes.

If I write a query to select all entries from an IMap that selects entries by account that occurred in the last 24 hours, I do *NOT* expect to get a different result when I enable an optimization, like Indexing.

If I write a query to select all entries from an IMap where a flag on the entry is true, I do *NOT* expect to get a different result when I enable an optimization, like indexing.

If I write a query to select all entries from an IMap where I'm selecting the top-N most recent, I do *NOT* expect to get a different result when I enable an optimization.

Making this a documentation issue is just hiding a real problem - it's either a defect or a very bad API.  I believe the former is the case.  If its the latter, then I should not be able to implement the `apply` method on an `IndexAwarePredicate` (or any of its related classes).  However, if you take the latter approach, then why on earth wouldn't I want to filter a second time (why would you prevent your users from doing this)- this is the whole point of Predicates!  

Indexing is not business logic - its an optimization.  It's been viewed that way for ever.  Sweeping it under the rug and simply documenting it will not prevent incorrect data selections for you customers.

I'll take a poll here of the devs at two team stand-ups this morning to see if Im off the mark on this.

**Comment by jerrinot** [comment] 2018-02-15 13:13
"If I write a query to select all entries from an IMap where a flag on the entry is true, I do NOT expect to get a different result when I enable an optimization, like indexing." <-- that's obviously the right expectation. If you get a different result then it means your predicate impl is buggy"

**Comment by vertex-github** [comment] 2018-02-15 13:19
I don't know how else to frame this problem:  If I enable something in Hazelcast, then I get different data values.  That goes against decades of expectations of indexing (or any performance toggle)

That has nothing to do with buggy Predicate implementations - Hazelcast isnt running the code we gave it when we turn on indexing.

**Comment by jerrinot** [comment] 2018-02-15 13:50
Just to be extra sure: This is happening only when you use your custom predicate. Your implementation of the `filter()` returns entries not matching the `apply()` method. Is this correct?

**Comment by vertex-github** [comment] 2018-02-15 14:04
Correct - the expectation is that the *same* business logic would be run (hence the `apply` method) whether I'm running with indexes or not (this way I can toggle the Index and test system performance). 

The problem here is that end users have to implement duplicate filter logic to use an Index correctly.  I cant think of a reason where we would want *different* filter logic when I enable indexing (if you have use cases where this is beneficial Im "all-ears").  I enable indexing for a performance boost at the expense of the `put`/`set` cost and some additional memory usage.  Having to make code changes to enable an optimization is just counter intuitive and it's too easy to miss.  

Could we not have Hazelcast call the `apply` method (with the Index filtered entries) after the `filter` ?

**Comment by vertex-github** [comment] 2018-02-15 14:44
I understand how its working - I just haven't met a developer that *expects* different behavior when enabling an Index.

If you can provide a real-world use-case where the business logic needs to be different when using the Index vs not, then I'll agree this could be a 'feature'.  I just don't know of one (and nobody here could come up with one) and I think this leads to silent defects when enabling Indexes for performance gains, hence the usage pattern is defective.

I asked around here:
Enabling an Index is *viewed* as a performance optimization, no business logic changes are *expected*.  

While Id rather not can discuss the semantics of defect vs feature, absent a valid use-case where index filtering should be different than non-index filtering, I think this behavior should be changed/fixed/altered/updated.

While I fully understand the implications of changing/fixing/updating/(insert your view point here..) this behavior I do think you should poll your clients & users to see if there are valid use cases for different business logic scenarios when running with/without indexes or indeed if this is expected by them.  At the very least, Id expect the current default behavior to be inverted (Indexes should also `apply`) but allow an end user to override that default behavior.

**Comment by pveentjer** [comment] 2018-02-15 15:45
I'm on nicks side. IndexAwarePredicate is just a performance optimization, and it should not impact the outcome. If it does, it is a bug. The fact that with certain predicate we know we can skip the apply method is nice; but it is a broken assumption it can be applied to just any predicate.

**Comment by mmedenjak** [comment] 2018-02-15 18:05
Jaromir and I are not questioning should the results change if the index is enabled or not. We all agree on this - the results must not change whether you use index or not. 
The only question here is if we should implicitly call `apply` after the index has returned the results from `filter`. I don't think we should. We will document this and the implementer has to implement the `filter` method with this in mind. If the implementer is lazy, he may just call `apply` on all entries of the index. He may call `apply` only on some. He may not call `apply` at all since the results are indexed by the queried value.

Think of it this way - we keep a lazy view of the map entry in the index - it might be a 100MB off heap object. If you are a reasonable developer, you may simply use the index to return the results. But if we implicitly call `apply` for you after that - well the `apply` method may just bring the entire object on-heap, deserialise it, just to confirm that that one query value that you already checked in the index is, in fact, what you want. And repeat this for every indexed entry.

The query must not return different results, the contract of `IndexAwarePredicate` must be clear and the implementer must know how to properly implement the `filter` method.

**Comment by vertex-github** [comment] 2018-02-15 18:13
Whether you call it lazy or an extremely unexpected behavior, the result is the same - potentially bad data from a query when we enable indexing.  Documenting this fact doesnt fix or prevent the problem. I've yet to meet a developer that reads all Javadocs of all API calls all the time.  

There's something very simple that Hazelcast could do in this situation to prevent such silent bad data, and not just document it in an API call that most folks don't read.

This problem is even worse for Enterprise users since most IDEs cant auto-pull the source/javadocs for the enterprise.jar because they don't exist, and they cant/wont link the OSS sources to the Enterprise binary.  Most people Ive seen using IntelliJ/Eclipse in corporate environments also dont know how to link URLs to the online Javadocs - even then, that only works when connected to a network.

**Closed** 2018-03-01 05:33 UTC
Labels: Estimation: S, Interface: IMap, Team: Core, Team: Documentation, Type: Defect
