### ISSUE TITLE
ClientExecutorServiceTest.testCancelFutureAfterCancellationAwareTaskTimeOut

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4199] opened 2014-12-01 11:53 UTC
```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.client.executor.ClientExecutorServiceTest.testCancelFutureAfterCancellationAwareTaskTimeOut(ClientExecutorServiceTest.java:157)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK8/com.hazelcast$hazelcast-client/72/testReport/junit/com.hazelcast.client.executor/ClientExecutorServiceTest/testCancelFutureAfterCancellationAwareTaskTimeOut/

**Comment by hasancelik** [comment] 2015-08-21 09:58
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.executor.ClientExecutorServiceTest.testCancelFutureAfterCancellationAwareTaskTimeOut(ClientExecutorServiceTest.java:164)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast-client-new/635/testReport/junit/com.hazelcast.client.executor/ClientExecutorServiceTest/testCancelFutureAfterCancellationAwareTaskTimeOut/

**Comment by sancar** [comment] 2015-11-20 13:50
Related to https://github.com/hazelcast/hazelcast/issues/4677

**Comment by Holmistr** [comment] 2018-03-07 10:42
I'm closing this issue, since the test is ignored. The root cause is https://github.com/hazelcast/hazelcast/issues/4677 , so the test should be enabled and fixed, once the root cause is fixed. I created a PR just to link the issue also to the test https://github.com/hazelcast/hazelcast/pull/12522

**Closed** 2018-03-07 11:41 UTC
Labels: Interface: IExecutor, Team: Client, Type: Test-Failure
