### ISSUE TITLE
Losing data from cluster when node is terminated

### ISSUE THREAD

**Issue by riverwinddk** [hazelcast/hazelcast#5388] opened 2015-05-27 13:39 UTC
Scenario:
1. Start first node, and let it populate a map with 100k entries
2. Start second node, and let it start joining cluster
3. Terminate second node during join
4. Observe that data is lost seen from first node.

Note, however, that data is *not* lost in 3.3(.x), only in 3.4(.x) and 3.5-EA.
Code below produces the following result after the scenario above:
3.3 result:
Node1: Size of map is 100000
Node1: Members:
       Member [172.29.120.20]:5701 this

3.3.3 result:
Node1: Size of map is 100000
Node1: Members:
       Member [172.29.120.20]:5701 this

3.4.2 result:
Node1: Size of map is 61482
Node1: Members:
       Member [172.29.120.20]:5701 this

3.5-EA result:
Node1: Size of map is 61151
Node1: Members:
       Member [172.29.120.20]:5701 this

Code for reproduction:
package com.saabgroup.tacticall.test;
    
    import com.hazelcast.config.Config;
    import com.hazelcast.config.GroupConfig;
    import com.hazelcast.config.MapConfig;
    import com.hazelcast.config.XmlConfigBuilder;
    import com.hazelcast.core.*;
    import org.apache.log4j.Logger;
    
    import java.util.Map;
    import java.util.Properties;
    import java.util.Random;
    import java.util.Scanner;
    import java.util.concurrent.Executors;
    import java.util.concurrent.ScheduledExecutorService;
    import java.util.concurrent.TimeUnit;
    
    public class Node {
        protected static Logger logger = Logger.getLogger(Node.class);
        protected final ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();
        private final String name;
    
        protected HazelcastInstance hazelcast;
    
        protected  String clientListenerKey;
    
        public Node(String name)
        {
            this.name = name;
        }
    
        protected Config configure()
        {
            XmlConfigBuilder configBuilder = new XmlConfigBuilder();
            Config config = configBuilder.build();
    
            // Set group config to default values (username, password)
            if(config.getGroupConfig().getName().equalsIgnoreCase(GroupConfig.DEFAULT_GROUP_NAME))
            {
                // No group config provided - add default
                config.getGroupConfig().setName("mygroup");
                config.getGroupConfig().setPassword("password");
            }
    
            config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(true);
            config.getNetworkConfig().getJoin().getMulticastConfig().setMulticastGroup("239.255.1.63");
            config.getNetworkConfig().getJoin().getMulticastConfig().setMulticastPort(30002);
    
            Properties properties = config.getProperties();
            config.setProperty("hazelcast.version.check.enabled", "false");
            config.setProperty("hazelcast.logging.type", "jdk");
            if(!properties.containsKey("hazelcast.heartbeat.interval.seconds"))
                config.setProperty("hazelcast.heartbeat.interval.seconds", "1");
            if(!properties.containsKey("hazelcast.max.no.heartbeat.seconds"))
                config.setProperty("hazelcast.max.no.heartbeat.seconds", "8");
    
            if(!properties.containsKey("hazelcast.icmp.enabled"))
                config.setProperty("hazelcast.icmp.enabled", "true");
            if(!properties.containsKey("hazelcast.icmp.timeout"))
                config.setProperty("hazelcast.icmp.timeout", "3000");
            if(!properties.containsKey("hazelcast.icmp.ttl"))
                config.setProperty("hazelcast.icmp.ttl", "10");
    
            if(!properties.containsKey("hazelcast.merge.first.run.delay.seconds"))
                config.setProperty("hazelcast.merge.first.run.delay.seconds", "1");
            if(!properties.containsKey("hazelcast.merge.next.run.delay.seconds"))
                config.setProperty("hazelcast.merge.next.run.delay.seconds", "10");
    
            Map<String, MapConfig> mapConfigs = config.getMapConfigs();
            MapConfig mapConfig = mapConfigs.get("I am your father");
            if(null == mapConfig)
            {
                mapConfig = new MapConfig("I am your father");
            }
    
            mapConfig.setBackupCount(1);
            mapConfig.setAsyncBackupCount(0);
    
            config.addMapConfig(mapConfig);
    
            return config;
        }
    
        public void start()
        {
            hazelcast = Hazelcast.newHazelcastInstance(configure());
    
            scheduler.scheduleAtFixedRate(new Runnable() {
                @Override
                public void run()
                {
                    dump();
    
                    IMap<Object, Object> map = hazelcast.getMap("I am your father");
    
                    if (map.isEmpty())
                    {
                        // Add 100k entries to map
                        Random rd = new Random();
                        for (int i = 0; i < 100000; i++)
                        {
                            map.put(String.valueOf(rd.nextDouble()), String.valueOf(i));
                        }
                    }
                }
            }, 2, 2, TimeUnit.SECONDS);
    
            lifecycleListenerKey = hazelcast.getLifecycleService().addLifecycleListener(lifecycleListener);
            clientListenerKey = hazelcast.getClientService().addClientListener(new ClientListener() {
                @Override
                public void clientConnected(Client client) {
                    System.out.println("Client connected: "+client.getSocketAddress());
                    dump();
                }
    
                @Override
                public void clientDisconnected(Client client) {
                    System.out.println("Client disconnected: "+client.getSocketAddress());
                    dump();
                }
            });
        }
    
        public void stop()
        {
            hazelcast.getClientService().removeClientListener(clientListenerKey);
            hazelcast.getLifecycleService().removeLifecycleListener(lifecycleListenerKey);
    
            // Force the node down
            hazelcast.getLifecycleService().terminate();
        }
    
        public static void main(String[] args) {
    
            Node node1 = new Node("Node1");
            node1.start();
    
            try
            {
                Thread.sleep(10000);
            }
            catch (InterruptedException e)
            {
                e.printStackTrace();
            }
    
            Node node2 = new Node("Node2");
            node2.start();
    
            try
            {
                Thread.sleep(5000);
            }
            catch (InterruptedException e)
            {
                e.printStackTrace();
            }
            System.out.println("Stopping node2");
            node2.stop();
    
            System.out.println("Press ENTER to stop node1");
            Scanner sc = new Scanner(System.in);
            sc.nextLine();
            System.out.println("Stopping node1");
    
            node1.stop();
        }
    
        protected LifecycleListener getLifecycleListener()
        {
            return new LifecycleListener() {
                @Override
                public void stateChanged(LifecycleEvent event) {
                    switch (event.getState())
                    {
                        case STARTED:
                        case CLIENT_CONNECTED:
                            //System.out.println("Lifecycle " + event.getState().name());
                            break;
    
                        case SHUTTING_DOWN:
                        case CLIENT_DISCONNECTED:
                            //System.out.println("Lifecycle " + event.getState().name());
                            break;
    
                        default:
                            //System.out.println("Lifecycle Event " + event.getState().name());
                            break;
                    }
    
                    dump();
                }
            };
        }
    
        protected String lifecycleListenerKey;
        protected final LifecycleListener lifecycleListener = getLifecycleListener();
    
        protected void dump() {
            System.out.println(name + ": Size of map is " + hazelcast.getMap("I am your father").size());
    
            System.out.println(name + ": Members:");
            for (Member member : hazelcast.getCluster().getMembers())
            {
                System.out.println("       " + member);
            }
        }
    }

**Comment by metanet** [comment] 2015-06-01 13:31
Hello @riverwinddk,

First of all, I can reproduce it with the code you provide with both 3.3, 3.4 and master (3.5). 

Your case isn't specific to node join. You are terminating your node-2 while there are ongoing migration operations in your cluster and your nodes are not in safe state. 

After node-2 joins the cluster, node-1 transfers ownership of some of its partitions to node-2 by executing migration operations. After a partition is moved to node-2, node-1 clears its own data of that partition since it is no longer owner of it. Before clearing data for the partition, node-1 does not check if it is still a backup for it or not. After this step, node-2 is responsible for all backup / replica operations. 

In your code, you shutdown node-2 before it successfully sends its backups to other nodes in the cluster (only node-1 for your case). You can verify this by calling `node1.instance.getPartitionService().isClusterSafe()` just before `node2.stop()`. It will return false. If you increase the sleep time after `node2.start()` you will see that there won't be a data loss in your map since all the backups are successfully populated for the partitions that are transferred to node-2. 

Closing this one since it behaves expectedly.

**Closed by metanet** 2015-06-01 13:31 UTC
Labels: PENDING, Team: Core

**Comment by riverwinddk** [comment] 2015-06-05 06:34
Hi @metanet 

I understand this is not a small feat.

I've now seen #5444 and it's excactly the same behaviour. Actually we're experiencing this when emulating network issues, where the nodes are split while the cluster is unsafe.

I believe that 3.5 tries to address the issue by introducing the PartitionLostListener. I guess this would allow the application to load from persistent storage.

However I'm pretty sure that 3.3 seems more robust in this regard, at least in my test.

**Comment by metanet** [comment] 2015-06-05 06:42
Hi @riverwinddk 

Yes, with 3.5 you can listen partition lost events with PartitionLostListener and reload your data for that partition.

**Comment by riverwinddk** [comment] 2015-06-11 13:10
But is there any explanation as to why the migration process takes (a lot) longer on 3.4/3.5 compared to 3.3?

**Comment by ChristerF** [comment] 2015-11-07 07:57
+1

**Comment by nick7ikin** [comment] 2015-11-10 16:27
Hi @metanet 

Could you please expand a bit how it is possible to restore lost data using PartitionLostEvent? 

After catching PartitionLostEvent I can reload ALL cluster data to hazelcast, but it seems to be overkill. Cause data in partitions that aren't lost also will be reloaded and it may take quite a long time.

It's better way to reload only those peaces of data that are really lost. In this case I need ids of items that were in lost partitions. I can't figure out is there the way how to get ID list of lost items. Please share your ideas as for this.

**Comment by burakcelebi** [comment] 2016-04-07 13:50
Our engineering team has finished their “Solution Design" for the issue. 

Your input is always appreciated. You can review and comment on our design here:

[Avoid Data Loss on Migration - Solution Design](https://hazelcast.atlassian.net/wiki/display/COM/Avoid+Data+Loss+on+Migration+-+Solution+Design)
PR: https://github.com/hazelcast/hazelcast/pull/7911

Thanks in advance for any feedback you can provide!
