### ISSUE TITLE
com.hazelcast.client.bluegreen.ClientSelectorRaceTest.testConcurrency

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#15738] opened 2019-10-11 07:41 UTC
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3746/testReport/junit/com.hazelcast.client.bluegreen/ClientSelectorRaceTest/testConcurrency/

```
Stacktrace
java.lang.NullPointerException
	at com.hazelcast.client.test.TestHazelcastFactory.terminateAll(TestHazelcastFactory.java:145)
	at com.hazelcast.client.bluegreen.ClientSelectorRaceTest.cleanup(ClientSelectorRaceTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:402)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ihsandemir** [comment] 2019-10-15 13:06
This is a duplicate of https://github.com/hazelcast/hazelcast/issues/15739 hence closing this issue. Please follow #15739 .

**Closed by ihsandemir** 2019-10-15 13:06 UTC
Labels: Team: Client, Type: Test-Failure
