### ISSUE TITLE
com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null] [HZ-1888]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18943] opened 2021-06-21 09:48 UTC
_master_ (commit b80b074928b3cd452b166d8cf69cc5813120f32f)

Failed on Zulu JDK 15: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK15/50/testReport/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/testIssue859And863_WhenQueuesAreOnFirstInstance_comparatorClassName__null_/

It can have the same cause as https://github.com/hazelcast/hazelcast/issues/17462

Stacktrace:
```
java.lang.AssertionError: expected:<3000> but was:<2999>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.lambda$testIssue859And863$4(TransactionQueueTest.java:414)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1247)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1349)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.testIssue859And863(TransactionQueueTest.java:413)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.testIssue859And863_WhenQueuesAreOnFirstInstance(TransactionQueueTest.java:337)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Standard output:
```
11:56:36,807  INFO |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [InvocationMonitor] hz.determined_agnesi.InvocationMonitorThread - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Invocations:1 timeouts:1 backup-timeouts:0
11:56:36,822  INFO |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [LifecycleService] Thread-50329 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
11:56:36,822  INFO |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [Node] Thread-50329 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
11:56:36,822  INFO |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [LifecycleService] Thread-50329 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
11:56:36,822  INFO |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [LifecycleService] Thread-50329 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
11:56:36,822  WARN |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [Node] Thread-50329 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Terminating forcefully...
11:56:36,822  INFO |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [Node] Thread-50329 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Shutting down connection manager...
11:56:36,822  INFO |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [Node] Thread-50329 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Shutting down node engine...
11:56:36,823  INFO |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [NodeExtension] Thread-50329 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Destroying node NodeExtension.
11:56:36,824  INFO |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [Node] Thread-50329 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
11:56:36,824  INFO |testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null]| - [LifecycleService] Thread-50329 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null](com.hazelcast.collection.impl.txnqueue.TransactionQueueTest): BuildInfo{version='4.2.1-SNAPSHOT', build='20210619', buildNumber=20210619, revision=b80b074, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testIssue859And863_WhenQueuesAreOnFirstInstance[comparatorClassName: null](com.hazelcast.collection.impl.txnqueue.TransactionQueueTest):'
11:54:35, accumulated pauses: 54 ms, max pause: 10 ms, pauses over 1000 ms: 0
11:54:40, accumulated pauses: 53 ms, max pause: 17 ms, pauses over 1000 ms: 0
11:54:45, accumulated pauses: 53 ms, max pause: 17 ms, pauses over 1000 ms: 0
11:54:50, accumulated pauses: 43 ms, max pause: 5 ms, pauses over 1000 ms: 0
11:54:55, accumulated pauses: 40 ms, max pause: 2 ms, pauses over 1000 ms: 0
11:55:00, accumulated pauses: 64 ms, max pause: 14 ms, pauses over 1000 ms: 0
11:55:05, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
11:55:10, accumulated pauses: 48 ms, max pause: 7 ms, pauses over 1000 ms: 0
11:55:15, accumulated pauses: 38 ms, max pause: 1 ms, pauses over 1000 ms: 0
11:55:20, accumulated pauses: 64 ms, max pause: 18 ms, pauses over 1000 ms: 0
11:55:25, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
11:55:30, accumulated pauses: 43 ms, max pause: 7 ms, pauses over 1000 ms: 0
11:55:35, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
11:55:40, accumulated pauses: 64 ms, max pause: 14 ms, pauses over 1000 ms: 0
11:55:45, accumulated pauses: 41 ms, max pause: 6 ms, pauses over 1000 ms: 0
11:55:50, accumulated pauses: 42 ms, max pause: 1 ms, pauses over 1000 ms: 0
11:55:55, accumulated pauses: 76 ms, max pause: 16 ms, pauses over 1000 ms: 0
11:56:00, accumulated pauses: 43 ms, max pause: 4 ms, pauses over 1000 ms: 0
11:56:05, accumulated pauses: 37 ms, max pause: 4 ms, pauses over 1000 ms: 0
11:56:10, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
11:56:15, accumulated pauses: 94 ms, max pause: 51 ms, pauses over 1000 ms: 0
11:56:20, accumulated pauses: 41 ms, max pause: 3 ms, pauses over 1000 ms: 0
11:56:25, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
11:56:30, accumulated pauses: 93 ms, max pause: 51 ms, pauses over 1000 ms: 0
11:56:35, accumulated pauses: 507 ms, max pause: 496 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment] 2021-08-30 12:47
Yes, it's the same cause as https://github.com/hazelcast/hazelcast/issues/17462 since both tests delegate to the same method for testing. The cause is explained [here](https://github.com/hazelcast/hazelcast/issues/11647#issuecomment-686505783). Moving to backlog.

**Comment by bpoplawski** [comment] 2022-04-27 07:15
Failed on Master, Sonar http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1199/testReport/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/testIssue859And863_WhenQueuesAreOnFirstInstance_comparatorClassName__null_/

**Comment by arodionov** [comment] 2022-08-09 08:46
Failed again [build log](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12426/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12426/Hazelcast-pr-builder-12426.zip)

**Comment by ahmetmircik** [comment] 2022-12-12 05:53
After more than 7000 runs in 4 hours, no failure has been seen on 5.3 master branch. 
Closing this issue as not reproducible.

**Closed by ahmetmircik** 2022-12-12 05:53 UTC
Labels: Team: Core, Type: Test-Failure, Source: Internal, Module: IQueue, Module: Transactions, to-jira
