### ISSUE TITLE
ClassCastException at com.hazelcast.map.proxy.MapProxySupport$1.onResponse

### ISSUE THREAD

**Issue by th0rb3n** [hazelcast/hazelcast#5389] opened 2015-05-27 13:41 UTC
We're using Hazelcast v3.2.4. Maybe already fixed in a later version...

```
com.hazelcast.logging.Slf4jFactory$Slf4jLogger.log(Slf4jFactory$Slf4jLogger.java:92)
[10.20.30.221]:5701 [appsuite-dev-gws] [3.2.4] Failed to async for BasicInvocation{ serviceName='hz:impl:mapService', op=GetOperation{}, partitionId=231, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=5, callTimeout=5000, target=Address[10.20.30.222]:5701}
java.lang.ClassCastException: com.hazelcast.spi.impl.BasicInvocation$InternalResponse cannot be cast to com.hazelcast.nio.serialization.Data
	at com.hazelcast.map.proxy.MapProxySupport$1.onResponse(MapProxySupport.java:193)
	at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture$1.run(BasicInvocation.java:624)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.PoolExecutorThreadFactory$ManagedThread.run(PoolExecutorThreadFactory.java:59)
```

**Comment by pveentjer** [comment] 2015-06-01 08:53
Can you create a test that reproduces the problem?

**Comment by th0rb3n** [comment] 2015-06-01 13:32
> Can you create a test that reproduces the problem?

Unfortunately not. We saw that error in log files in a customer setup and my hope was that the stack trace is sufficient

**Comment by eminn** [comment] 2015-06-04 09:29
Do you have any indication of the operations are timing out or retrying in the logs ?

**Comment by pveentjer** [comment] 2015-06-17 10:24
Please upgrade to 3.5 (will be released shortly). Probably this issue is gone since a lot of work has been done on the invocation.

**Comment by th0rb3n** [comment] 2015-06-17 10:44
> Please upgrade to 3.5 (will be released shortly). Probably this issue is gone since a lot of work has
> been done on the invocation.

Is there a v3.4.x counterpart? The v3.4.x would be the next version we are able to upgrade to.

**Comment by Donnerbart** [comment] 2015-06-17 10:50
3.4.3 has been released yesterday: http://hazelcast.org/download/

But I cannot say by heart if this issue has been resolved.

**Comment by enesakar** [comment] 2015-11-02 09:28
closing the issue. you can reopen if still issue exists.

**Closed by enesakar** 2015-11-02 09:28 UTC
Labels: PENDING, Team: Core, Type: Defect
