### ISSUE TITLE
NullPointerException while invoking IMap.removeAll(predicate) with InPredicate

### ISSUE THREAD

**Issue by ohadpinch** [hazelcast/hazelcast#15018] opened 2019-05-12 13:07 UTC
This is how I'm using removeAll (the UUIDs are strings)
```
Predicate predicate = Predicates.in("__key",uuids);
mymap.removeAll(predicate);
```

I have 2 nodes and the operation working successful but I receive the following exception in the log:

```
12 12:52:09,780 [hz._hzInstance_1_topology.partition-operation.thread-0] ERROR c.h.m.i.o.PartitionWideEntryWithPredicateBackupOperation - [10.244.0.31]:5701 [topology] [3.12] null
java.lang.NullPointerException: null
        at com.hazelcast.map.AbstractEntryProcessor$EntryBackupProcessorImpl.processBackup(AbstractEntryProcessor.java:83) ~[hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:314) ~[hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181) ~[hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166) ~[hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.map.impl.operation.PartitionWideEntryBackupOperation.run(PartitionWideEntryBackupOperation.java:48) ~[hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.spi.impl.operationservice.impl.operations.Backup.run(Backup.java:159) [hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.spi.Operation.call(Operation.java:170) ~[hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210) [hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199) [hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416) [hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153) [hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123) [hazelcast-all-3.12.jar!/:3.12]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) [hazelcast-all-3.12.jar!/:3.12]
```

**Comment by ahmetmircik** [comment] 2019-05-22 08:48
I can't manage to reproduce this NPE. Is it possible to share a reproducer?

**Comment by ohadpinch** [comment] 2019-05-22 09:15
Sorry, I am unable to share, but I can elaborate:
1) I have 2 peers
2) the IMap created like that:
IMap<String,ComplexObject>mymap = instance.getMap("xx");
3) I fill the map
4) I create the Predicate like this:
Predicate<String, ComplexObject> predicate = Predicates.in("__key",uuids);
mymap.removeAll(predicate);
5) the uuids are around 80 characters long each
6) it is reproduced ALWAYS
7) I didn't see any impact of this exception, everything looks fine to me, If you know that something is not working I will appreciate if you can tell me the impact

**Comment by ahmetmircik** [comment] 2019-05-22 09:53
NPE happens on backup node. If you lose owner node, backup may not have latest state when it is promoted to owner. This is the potential impact. Better to have your reproducer here because i repeated exact steps that you elaborate but couldn't reproduce it.

**Comment by ohadpinch** [comment] 2019-05-22 11:27
Ok, I'll work on a reproducer and get back to you.

**Comment by ohadpinch** [comment] 2019-05-22 12:47
Hi,

I was able to narrow it down, it is only happening when I use:
info.jerrinot.sub zero.serializer 0.0.7 as global serializable and I have non-serialzable objects.

**Comment by ohadpinch** [comment] 2019-05-22 12:48
And this is the very small project

[Spring.zip](https://github.com/hazelcast/hazelcast/files/3207379/Spring.zip)

**Comment by mustafaiman** [comment] 2019-05-23 19:41
I looked a little bit into this issue. Problem is Kryo is not able to deserialize EntryBackupProcessor for EntryRemovingProcessor. When kryo deserializes the backup processor, its reference to outer class(this$0) is null. Therefore backup processor's process method throws NullPointerException. Serialization is offloaded to subzero in the sample project. Hazelcast exchanges messsages without a problem but subzero cannot return a proper backup processor. Most probably problem is with either subzero or kryo itself.

**Comment by jerrinot** [comment] 2019-07-07 11:43
I am closing this as it's not really caused by Hazelcast. 

It seems it's Kryo having issues with non-static inner classes. I will handle it in the [Subzero project](https://github.com/jerrinot/subzero/issues/33)

**Closed by jerrinot** 2019-07-07 11:43 UTC
Labels: Module: IMap, Module: Query, Type: Defect
