### ISSUE TITLE
Can't query map with full stop in name

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19915] opened 2021-11-08 11:47 UTC
Using Hazelcast Platform 5.0.1-SNAPSHOT (20211105 - 74bf4d8)

I define two maps, with no exceptions raised:
```
CREATE OR REPLACE MAPPING "neilstevenson" EXTERNAL NAME "neilstevenson" (    __key VARCHAR,    this VARCHAR) TYPE IMap  OPTIONS (  'keyFormat' = 'java', 'keyJavaClass' = 'java.lang.String', 'valueFormat' = 'java', 'valueJavaClass' = 'java.lang.String' )
CREATE OR REPLACE MAPPING "neil.stevenson" EXTERNAL NAME "neil.stevenson" (    __key VARCHAR,    this VARCHAR) TYPE IMap  OPTIONS (  'keyFormat' = 'java', 'keyJavaClass' = 'java.lang.String', 'valueFormat' = 'java', 'valueJavaClass' = 'java.lang.String' )
```

and `SHOW MAPPINGS` lists them both:
```
[name VARCHAR=neil.stevenson]
[name VARCHAR=neilstevenson]
```

But these two queries don't execute the same: 
```
SELECT * FROM neilstevenson
SELECT * FROM neil.stevenson
```

The first works, the second fails
```
com.hazelcast.sql.HazelcastSqlException: Object 'neil' not found, did you forget to CREATE MAPPING? If you want to use the IMap named 'neil', execute this command first: CREATE MAPPING "neil" EXTERNAL NAME "neil"
TYPE IMap
OPTIONS (
  'keyFormat' = 'java',
  'keyJavaClass' = 'java.lang.String',
  'valueFormat' = 'java',
  'valueJavaClass' = 'java.lang.String'
)

```

Related https://github.com/hazelcast/hazelcast/issues/19912

**Comment by neilstevenson** [comment] 2021-11-08 12:00
Use of `EXTERNAL NAME` is superfluous here, but removing it makes no difference

**Comment by viliam-durina** [comment] 2021-11-12 09:17
You should use 
```
SELECT * FROM neilstevenson
SELECT * FROM "neil.stevenson"
```
`"` quotes identifiers, the `.` is the interpreted literally. Without it, the parser considers `neil` to be a schema and `stevenson` to be a table name.

But the error you get for when not quoting is wrong I think - we should not offer IMap creation when the schema name is unknown...

**Comment by viliam-durina** [comment] 2021-11-12 10:08
I tried to fix the misleading error, however the error is throw by calcite and we replace it in a little hacky way - and in the place where it's done we don't know whether the missing object was a table or schema name. So if you do `select * from mySchema.map`, and a map with name `mySchema` exists, the error will provide you a CREATE MAPPING command to create `mySchema` mapping...

**Comment by viliam-durina** [comment] 2021-11-12 10:09
Closing the error as the issue is pretty obvious and the behavior is correct. Reopen if you disagree.

**Closed by viliam-durina** 2021-11-12 10:09 UTC
Labels: Type: Defect
