### ISSUE TITLE
CPMemberAddRemoveTest testRemoveMemberFromMajorityLostRaftGroup

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#16930] opened 2020-04-25 10:55 UTC
- Fails on `Hazelcast-4.master-ZuluJDK9`
- Fails on [Build #71 (Apr 25, 2020 4:07:56 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-ZuluJDK9/71/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/testRemoveMemberFromMajorityLostRaftGroup/)
- Stacktrace
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.lambda$testRemoveMemberFromMajorityLostRaftGroup$0(CPMemberAddRemoveTest.java:211)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1242)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1344)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.testRemoveMemberFromMajorityLostRaftGroup(CPMemberAddRemoveTest.java:210)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

- Noticed below in logs
```
Cannot execute leadership rebalance at the moment
java.util.concurrent.CompletionException: com.hazelcast.spi.exception.TargetNotMemberException: Not Member! target: [127.0.0.1]:5703, partitionId: -1, operation: com.hazelcast.cp.internal.operation.GetLeadedGroupsOp, service: hz:core:raft
	at com.hazelcast.spi.impl.AbstractInvocationFuture.returnOrThrowWithJoinConventions(AbstractInvocationFuture.java:769) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowWithJoinConvention(AbstractInvocationFuture.java:785) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:537) ~[classes/:?]
	at com.hazelcast.cp.internal.RaftGroupMembershipManager$RaftGroupLeadershipBalanceTask.getLeadershipsMap(RaftGroupMembershipManager.java:533) ~[classes/:?]
	at com.hazelcast.cp.internal.RaftGroupMembershipManager$RaftGroupLeadershipBalanceTask.rebalanceLeaderships(RaftGroupMembershipManager.java:480) ~[classes/:?]
	at com.hazelcast.cp.internal.RaftGroupMembershipManager$RaftGroupLeadershipBalanceTask.run(RaftGroupMembershipManager.java:452) [classes/:?]
	at 
```

kindly check

**Comment by lazerion** [comment] 2020-05-27 13:05
- Continues to fail `Hazelcast-4.master-ZuluJDK9`
- Fails on [Build #75 (May 23, 2020 2:08:01 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-ZuluJDK9/lastCompletedBuild/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/testRemoveMemberFromMajorityLostRaftGroup/)

**Comment by lazerion** [comment] 2020-07-05 13:42
- Continues to fail different jdk though `Hazelcast-4.master-ZuluJDK9`
- Fails on [Build #81 (Jul 4, 2020 6:50:28 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-ZuluJDK9/81/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/testRemoveMemberFromMajorityLostRaftGroup/)
- Notice below in logs 
```
com.hazelcast.cp.exception.NotLeaderException: RaftEndpoint{uuid='cf3e5d5b-18b7-463f-b126-888947a4b256'} is not LEADER of CPGroupId{name='test', seed=0, groupId=4442}. Known leader is: N/A
```
kindly check

**Comment by lazerion** [comment] 2020-10-14 13:48
- Continues to fails occasionally on `Hazelcast-4.master-CorrettoJDK8`
- Fails on [Build #94 (Oct 14, 2020 6:14:00 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-CorrettoJDK8/94/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/testRemoveMemberFromMajorityLostRaftGroup/)

**Comment by jerrinot** [comment] 2021-10-14 07:57
the
```
Cannot execute leadership rebalance at the moment
java.util.concurrent.CompletionException: com.hazelcast.spi.exception.TargetNotMemberException: Not Member! target: [127.0.0.1]:5703, partitionId: -1, operation: com.hazelcast.cp.internal.operation.GetLeadedGroupsOp, service: hz:core:raft
	at com.hazelcast.spi.impl.AbstractInvocationFuture.returnOrThrowWithJoinConventions(AbstractInvocationFuture.java:769) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowWithJoinConvention(AbstractInvocationFuture.java:785) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:537) ~[classes/:?]
	at com.hazelcast.cp.internal.RaftGroupMembershipManager$RaftGroupLeadershipBalanceTask.getLeadershipsMap(RaftGroupMembershipManager.java:533) ~[classes/:?]
	at com.hazelcast.cp.internal.RaftGroupMembershipManager$RaftGroupLeadershipBalanceTask.rebalanceLeaderships(RaftGroupMembershipManager.java:480) ~[classes/:?]
	at com.hazelcast.cp.internal.RaftGroupMembershipManager$RaftGroupLeadershipBalanceTask.run(RaftGroupMembershipManager.java:452) [classes/:?]
	at 
```
will be fixed by https://github.com/hazelcast/hazelcast/pull/19633.
I have yet explore whether it's the real root cause of this failure. The test is rather complex.

**Comment by jerrinot** [comment] 2021-10-15 07:24
so the leadership rebalancing is unrelated to this failure. The last failure is 1+ years old, there are no logs left, no even in the archive. Closing this, feel free to re-open it if there is another failure.

**Closed by jerrinot** 2021-10-15 07:24 UTC
Labels: Team: Core, Type: Test-Failure, Source: Internal, Module: CP Subsystem
