### ISSUE TITLE
ClientRegressionWithMockNetworkTest.*

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#6991] opened 2015-12-04 12:25 UTC
This is a failure from my local runs, so no CloudBees link is available.

```
java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:582)
    at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenDummyClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:563)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:46)
    at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
```

https://gist.github.com/Donnerbart/aaed8a5ed47ea92d327f

The failing assert is this one:

```
assertTrue(lock.tryLock(1, TimeUnit.MINUTES));
```

**Comment by enesakar** [comment] 2015-12-24 09:53
because it is not reproduced in our builds, I am closing it.

**Comment by Donnerbart** [comment] 2016-01-16 09:28
Failed again on a local run with 3.6 branch and new client:
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:581)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenSmartClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:567)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hasancelik** [comment] 2016-02-03 10:12
**ClientRegressionWithMockNetworkTest.testClientConnectionEvents**

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:315)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/810/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-03-25 10:00
```
java.lang.AssertionError: null
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport.shutdown(ClientInvocationServiceSupport.java:173)
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.shutdown(ClientSmartInvocationServiceImpl.java:30)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.doShutdown(HazelcastClientInstanceImpl.java:590)
	at com.hazelcast.client.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:108)
	at com.hazelcast.client.impl.LifecycleServiceImpl.terminate(LifecycleServiceImpl.java:114)
	at com.hazelcast.client.test.TestHazelcastFactory.terminateAll(TestHazelcastFactory.java:126)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.cleanup(ClientRegressionWithMockNetworkTest.java:80)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast-client/60/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/861/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-04-07 08:19
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:270)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast-client/366/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-05-16 13:04
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:272)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast-client/1302/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-05-17 08:49
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:272)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast-client/1302/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-05-30 10:29
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:272)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast-client/383/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-06-27 09:15
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:272)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZuluJDK7/com.hazelcast$hazelcast-client/92/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-07-25 14:04
**master**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast-client/409/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**maintenance**

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast-client/409/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-08-02 07:57
**testClientConnectionEvents**
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/988/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by ihsandemir** [comment] 2016-08-02 10:29
I examined the test testClientConnectionEvents. It checks for the events but event service does not guarantee the order of the events, it is an asynch executor that delivers the events. Hence, the test may be changed to check for the existence of the events but not the order of them.

**Comment by hasancelik** [comment] 2016-08-03 12:19
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/284/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/989/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-08-08 12:16
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/307/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-08-15 13:56
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/1001/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-08-16 12:03
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast-client/110/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-08-19 08:17
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast-client/108/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-08-22 12:25
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/1007/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-08-22 13:46
**maintenance**
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast-client/112/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-08-24 12:51
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/323/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-09-07 07:57
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-ee-IbmJDK1.8/com.hazelcast$hazelcast-enterprise/178/testReport/junit/com.hazelcast.spi.hotrestart.cluster/HotRestartClusterStartTest/test_cannotChangeClusterState_beforeHotRestartProcessCompletes/

**Comment by hasancelik** [comment] 2016-09-21 13:36
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:271)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/352/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-09-29 14:53
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:271)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/1048/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-10-12 07:57
```
java.lang.AssertionError: LifecycleState failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClientConnectionEvents(ClientRegressionWithMockNetworkTest.java:269)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast-client/437/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientConnectionEvents/

**Comment by hasancelik** [comment] 2016-11-16 11:07
**testLock_WhenSmartClientAndOwnerNodeDiesTogether**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:527)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenSmartClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:513)
```
**testLock_WhenDummyClientAndOwnerNodeDiesTogether**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:527)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenDummyClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:507)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/1140/

**Comment by hasancelik** [comment] 2016-12-26 07:58
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1181/#showFailuresLink

**Closed** 2016-12-29 09:01 UTC
Labels: Team: Client, Type: Test-Failure
