### ISSUE TITLE
Hazelcast instance name with Hibernate still creates multiple instances

### ISSUE THREAD

**Issue by chandreshp** [hazelcast/hazelcast#4388] opened 2015-01-07 06:28 UTC
Please refer to below issue that was closed but should be reopened. I have posted a comment as reply for reopening purpose. I am unable to reopen it myself probably due to restricted access.

https://github.com/hazelcast/hazelcast/issues/4374

**Comment by mdogan** [comment] 2015-01-07 07:41
duplicate of #4374

**Closed by mdogan** 2015-01-07 07:41 UTC
