### ISSUE TITLE
RestTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11046] opened 2017-08-07 14:28 UTC
*testMap_PutGet_withLargeValue_chunked*
*testMap_PutGet_withLargeKey_chunked*
*testMapPutGet_chunked*
```
java.io.IOException: Invalid Http response
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1588)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doGet(HTTPCommunicator.java:226)
	at com.hazelcast.internal.ascii.HTTPCommunicator.mapGet(HTTPCommunicator.java:69)
	at com.hazelcast.internal.ascii.RestTest.testMap_PutGet_withLargeValue0(RestTest.java:263)
	at com.hazelcast.internal.ascii.RestTest.testMap_PutGet_withLargeValue_chunked(RestTest.java:247)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/1261/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/1263/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/658/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/660/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/654/

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/1585/

**Comment by hasancelik** [comment] 2017-08-14 11:27
*maintenance*
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:129)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:258)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:317)
	at java.io.FilterInputStream.read(FilterInputStream.java:116)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:2707)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:2702)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doGet(HTTPCommunicator.java:233)
	at com.hazelcast.internal.ascii.HTTPCommunicator.mapGet(HTTPCommunicator.java:73)
	at com.hazelcast.internal.ascii.RestTest.testMap_PutGet_withLargeKey0(RestTest.java:276)
	at com.hazelcast.internal.ascii.RestTest.testMap_PutGet_withLargeKey_chunked(RestTest.java:262)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/196/testReport/junit/com.hazelcast.internal.ascii/RestTest/testMap_PutGet_withLargeKey_chunked/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/200/

**Comment by ahmetmircik** [comment] 2017-08-14 12:02
merged a fix-attempt: https://github.com/hazelcast/hazelcast/commit/6c4e3add85db21cfb554f84c584c6e57fc5bec35

**Comment by Donnerbart** [comment] 2017-08-16 20:53
Failed again on a local test run.

**testMap_PutGet_withLargeValue_chunked()**
```java
java.io.IOException: Invalid Http response

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1588)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doGet(HTTPCommunicator.java:240)
	at com.hazelcast.internal.ascii.HTTPCommunicator.mapGet(HTTPCommunicator.java:73)
	at com.hazelcast.internal.ascii.RestTest.testMap_PutGet_withLargeValue0(RestTest.java:264)
	at com.hazelcast.internal.ascii.RestTest.testMap_PutGet_withLargeValue_chunked(RestTest.java:248)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Donnerbart** [comment] 2017-08-17 10:18
Also failed on Jenkins:
**com.hazelcast.internal.ascii.RestTest.testMap_PutGet_withLargeValue_chunked**
```java
java.io.IOException: Invalid Http response
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1588)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doGet(HTTPCommunicator.java:240)
	at com.hazelcast.internal.ascii.HTTPCommunicator.mapGet(HTTPCommunicator.java:73)
	at com.hazelcast.internal.ascii.RestTest.testMap_PutGet_withLargeValue0(RestTest.java:264)
	at com.hazelcast.internal.ascii.RestTest.testMap_PutGet_withLargeValue_chunked(RestTest.java:248)
```
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/lastCompletedBuild/com.hazelcast$hazelcast/testReport/com.hazelcast.internal.ascii/RestTest/testMap_PutGet_withLargeValue_chunked/

**Comment by hasancelik** [comment] 2017-08-21 07:45
*testMapPutGet_chunked*
```
java.io.IOException: Invalid Http response
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1343)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doGet(HTTPCommunicator.java:240)
	at com.hazelcast.internal.ascii.HTTPCommunicator.mapGet(HTTPCommunicator.java:73)
	at com.hazelcast.internal.ascii.RestTest.testMapPutGet0(RestTest.java:127)
	at com.hazelcast.internal.ascii.RestTest.testMapPutGet_chunked(RestTest.java:117)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1445/testReport/junit/com.hazelcast.internal.ascii/RestTest/testMapPutGet_chunked/

**Comment by mesutcelik** [comment] 2017-08-23 19:23
I tried to reproduce this by repeating tests but no success. It looks like response returned by hazelcast is malformed. I was able to reproduce the same exception by playing with response byte array.

The only pattern I see from above exceptions is first a PUT then GET called and GET response is malformed.

**Comment by mdogan** [comment] 2017-08-24 07:11
I'm able to reproduce on a Linux machine. I've tried to analyze the packets using Wireshark. But it shows http response as valid.
One solution might be to drop our http server and replace it with a real one.

**Comment by mdogan** [comment] 2017-08-24 11:37
Converted RestTest to use Apache HttpClient: https://github.com/hazelcast/hazelcast/pull/11213

**Closed** 2017-08-24 12:39 UTC
Labels: Team: Core, Team: Integration, Type: Test-Failure
