### ISSUE TITLE
Hazelcast-all 3.6.1 fails in OSGi

### ISSUE THREAD

**Issue by flyaruu** [hazelcast/hazelcast#7910] opened 2016-04-05 11:36 UTC
It imports package com.hazelcast.client.impl.protocol.codec, which (I guess) it's supposed to supply itself.

    org.osgi.framework.BundleException: Unable to resolve com.hazelcast [6](R 6.0): 
    missing requirement [com.hazelcast [6](R 6.0)] osgi.wiring.package; (osgi.wiring.package=com.hazelcast.client.impl.protocol.codec) 
    Unresolved requirements: [[com.hazelcast [6](R 6.0)] osgi.wiring.package;
    (osgi.wiring.package=com.hazelcast.client.impl.protocol.codec)]

**Comment by flyaruu** [comment] 2016-04-05 11:39
3.6.0 works fine.

**Comment by jerrinot** [comment] 2016-04-05 11:43
Hi @flyaruu, 
thanks for reporting the issue. It's a duplicate of https://github.com/hazelcast/hazelcast/issues/7772
The issue is fixed in 3.6.2 which should be released very soon. and by soon I mean hours rather than days:)

**Closed by jerrinot** 2016-04-05 11:43 UTC
