### ISSUE TITLE
[TEST-FAILURE] EvictionTest Timeout

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4894] opened 2015-03-25 08:28 UTC
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/492/console

**Comment by ahmetmircik** [comment] 2015-03-25 13:31
Seems a CI system internal error, closing now.

**Comment by bilalyasar** [comment] 2015-03-25 13:38
@ahmetmircik according to logs, there are some exceptions in this test class logs, is this expected behaviour?
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/492/artifact/hazelcast/target/surefire-reports/com.hazelcast.map.EvictionTest-output.txt

**Comment by mesutcelik** [comment] 2015-03-27 12:08
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/503/console

**Closed** 2015-04-10 08:09 UTC
Labels: Team: Core, Type: Defect

**Comment by metanet** [comment] 2015-04-10 08:26
Related failures (ResponseAlreadySentException) are here: 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/503/artifact/hazelcast/target/surefire-reports/com.hazelcast.map.EvictionTest-output.txt

Closed since not failed recently.
