### ISSUE TITLE
com.hazelcast.topic.impl.reliable.ReliableTopicCreateTest.testConfiguredListenerClassAndHazelcastInstanceAware [HZ-3584]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25817] opened 2023-10-24 08:21 UTC
_master_ (commit 3add9ce32d59c58f1cb9fdf09a253eb21e67e7ed)

Failed on corretto-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK11/246/testReport/com.hazelcast.topic.impl.reliable/ReliableTopicCreateTest/testConfiguredListenerClassAndHazelcastInstanceAware/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.core.OperationTimeoutException: GenericOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2023-10-24 05:15:25.480. Start time: 2023-10-24 05:14:20.743. Total elapsed time: 64737 ms. Invocation{op=com.hazelcast.ringbuffer.impl.operations.GenericOperation{serviceName='hz:impl:ringbufferService', identityHash=1187393905, partitionId=98, replicaIndex=0, callId=-1, invocationTime=1698124460743 (2023-10-24 05:14:20.743), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=_hz_rb_foo}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1698124460743, firstInvocationTime='2023-10-24 05:14:20.743', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[127.0.0.1]:5701, targetMember=Member [127.0.0.1]:5701 - 0cee7c12-a166-49b7-a33d-3240ed9f3af3 this, memberListVersion=1, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:203)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.toExceptionalResult(InvocationFuture.java:165)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:131)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:597)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:577)
	at com.hazelcast.ringbuffer.impl.RingbufferProxy.tailSequence(RingbufferProxy.java:112)
	at com.hazelcast.topic.impl.reliable.MessageRunner.<init>(MessageRunner.java:83)
	at com.hazelcast.topic.impl.reliable.ReliableMessageRunner.<init>(ReliableMessageRunner.java:37)
	at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.addMessageListener(ReliableTopicProxy.java:243)
	at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.addMessageListener(ReliableTopicProxy.java:131)
	at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.<init>(ReliableTopicProxy.java:104)
	at com.hazelcast.topic.impl.reliable.ReliableTopicService.createDistributedObject(ReliableTopicService.java:63)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:261)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:235)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxyFuture(ProxyRegistry.java:202)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxy(ProxyRegistry.java:182)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:153)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:366)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.getReliableTopic(HazelcastInstanceImpl.java:206)
	at com.hazelcast.instance.impl.HazelcastInstanceProxy.getReliableTopic(HazelcastInstanceProxy.java:114)
	at com.hazelcast.topic.impl.reliable.ReliableTopicCreateTest.testConfiguredListenerClassAndHazelcastInstanceAware(ReliableTopicCreateTest.java:249)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:348)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapRuntimeException(AbstractInvocationFuture.java:1975)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1956)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1438)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:601)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:577)
	at com.hazelcast.ringbuffer.impl.RingbufferProxy.tailSequence(RingbufferProxy.java:112)
	at com.hazelcast.topic.impl.reliable.MessageRunner.<init>(MessageRunner.java:83)
	at com.hazelcast.topic.impl.reliable.ReliableMessageRunner.<init>(ReliableMessageRunner.java:37)
	at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.addMessageListener(ReliableTopicProxy.java:243)
	at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.addMessageListener(ReliableTopicProxy.java:131)
	at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.<init>(ReliableTopicProxy.java:104)
	at com.hazelcast.topic.impl.reliable.ReliableTopicService.createDistributedObject(ReliableTopicService.java:63)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:261)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:235)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxyFuture(ProxyRegistry.java:202)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxy(ProxyRegistry.java:182)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:153)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:366)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.getReliableTopic(HazelcastInstanceImpl.java:206)
	at com.hazelcast.instance.impl.HazelcastInstanceProxy.getReliableTopic(HazelcastInstanceProxy.java:114)
	at com.hazelcast.topic.impl.reliable.ReliableTopicCreateTest.testConfiguredListenerClassAndHazelcastInstanceAware(ReliableTopicCreateTest.java:249)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-CorrettoJDK11/246/

**Comment by gareth-johnston** [comment] 2023-10-27 14:46
_NOTE - Not reproducible._ 

Analyzed the logs - There seems to be a general pause of about 64 seconds - caused by logging. At this time the failing test has just submitted its Operation and is attempting to access the logger.  

It is unknown what is causing a pause, but there seems to be some contention around this moment of time between tests testConfiguredListenerInstance & testConfiguredListenerInstanceHazelcastInstanceAware  & testWildcardConfig you can see this below & the logging takes an excessive amount of time - consistent with the timeout of the `GenericOperation`. 


```
05:14:20,939  INFO |testConfiguredListenerInstance| - [HazelcastTestSupport] Thread-43745 - Shutting down node factory as @After action
05:14:20,932  INFO |testConfiguredListenerInstanceHazelcastInstanceAware| - [HazelcastTestSupport] Thread-43747 - Shutting down node factory as @After action
05:14:20,752  INFO |testConfiguredListenerInstance| - [ReliableMessageListenerMock] hz.ReliableTopicCreateTest_thirsty_proskuriakova.async.thread-1 - Received: item
05:14:20,748  INFO |testConfiguredListenerClass| - [NodeExtension] Thread-43748 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
05:14:20,744  INFO |testWildcardConfig| - [HazelcastTestSupport] Thread-43744 - Shutting down node factory as @After action
05:15:25,474  WARN |testConfiguredListenerInstanceHazelcastInstanceAware| - [HazelcastTestSupport] Thread-43747 - Logging took 64542 ms.
05:15:25,475  WARN |testConfiguredListenerClass| - [NodeExtension] Thread-43748 - Logging took 64726 ms.
05:14:20,743  INFO |testConfiguredListenerInstanceHazelcastInstanceAware| - [ReliableMessageListenerMock] hz.ReliableTopicCreateTest_stupefied_proskuriakova.async.thread-1 - Received: item
05:14:20,743  INFO |testConstruction| - [MetricsConfigHelper] testConstruction - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
05:15:25,475  INFO |testConfiguredListenerInstanceHazelcastInstanceAware| - [LifecycleService] Thread-43747 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
05:15:25,475  WARN |testWildcardConfig| - [HazelcastTestSupport] Thread-43744 - Logging took 64730 ms.
05:15:25,475  WARN |testConstruction| - [MetricsConfigHelper] testConstruction - Logging took 64731 ms.
```

**Core issue :** 

`05:15:25,474  WARN |testConfiguredListenerInstanceHazelcastInstanceAware| - [HazelcastTestSupport] Thread-43747 - Logging took 64542 ms.`

Closing this one and will see if we can get metrics of the IOWait for the Jenkins executor.

**Closed by gareth-johnston** 2023-10-27 14:46 UTC
Labels: Team: Core, Type: Test-Failure, Source: Internal, to-jira
