### ISSUE TITLE
IMap entry eviction not called on time

### ISSUE THREAD

**Issue by ati90ati** [hazelcast/hazelcast#6118] opened 2015-09-03 10:27 UTC
Hi,
I have an IMap and I've adding entries in it. I put 5 seconds ttl for each newly added entry. This should be changeable so I use the put operation with ttl parameter.

map.put(key, value, 5, TimeUnit.SECONDS);
The 5 seconds could be changed runtime to other (ex. 10).

I created an entry listener and process the evicted entry.
On startup:
        localEntryListenerId = map.addLocalEntryListener((MapListener) this);

My problem is:
I had an older version (3.2-RC1). The eviction is called for an entry exactly when the 5 seconds expired.
I've change the Hazelcast version to 3.5.2. After this my entries started to evict later with a few seconds. Sometimes the eviction delays with several milliseconds but other times it delays until a max of 5 seconds. So the eviction is not called exactly when the ttl expires in the new version.

Shorter:
Ex. 1: if I add an entry with 5 seconds ttl it will be evicted between 5-10 seconds and not exactly after 5 seconds.
Ex. 2: if I add an entry with 60 seconds ttl it will be evicted between 60-65 seconds and not exactly after 60 seconds.

Could you tell my why this happens in the new version?
It is a bug or it is a sacrifice for some performance boost?

Thank you for help.
Regards,
Attila

**Comment by jerrinot** [comment] 2015-10-02 18:31
Hello @ati90ati: This is by design and it's indeed a performance optimization - it's more scalable than the previous approach. 

If you do an explicit `get()` then expiration is checked with a millisecond resolution, but when an entry is not touched then there is a batched expiration processing - the event might be delayed. From outside it's the same behaviour as when JVM is stopped due e.g. GC pause. 

I'm closing this ticket for now, feel free to re-open it if you think the behaviour you are observing can't be explain by this.

**Closed by jerrinot** 2015-10-02 18:31 UTC

**Comment by ati90ati** [comment] 2015-10-09 11:45
You helped me a lot with the idea to call the get() method in order to make a force evict for the entry.
Thank you very much for your help!

**Comment by sli-cs** [comment] 2016-03-22 15:01
Is there any estimate on the upper bound of the delay between an entry got expired and the "entryExpired(EntryEvent<K,V> event)" got called back? For example, is 5 seconds is a good estimate? or should it be 10 seconds?

**Comment by ati90ati** [comment] 2016-03-23 09:16
I've called the get() operation and it's resolves my problems.
For me when I'm waited for expiration the delay was between a few seconds to several hours. Depends on the number of entries in map.

**Comment by sli-cs** [comment] 2016-03-23 11:05
@ati90ati Thanks for sharing the experience. I guess a few seconds of delay is fine but several hours of delay is not good if I want to rely on the "entryExpired()" callback to trigger something near real time. Maybe I'll just have to trigger the 'get()' on the each "perishable" objects in my own thread. It would be really nice that this 'performance optimization' can be disabled via config so that expiration can be notified near real time.

**Comment by varunsrinath** [comment] 2017-06-07 21:20
at this point do we have any option other than calling the get() function ?. I am afraid I can't update to the latest version.  we are currently using version 3.5.1
