### ISSUE TITLE
com.hazelcast.jet.impl.connector.WriteJdbcPTest (2) [HZ-1710]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22673] opened 2022-11-02 14:24 UTC
_master_ (commit 8f8caf5580b7f05172c7323a14a22d48dab2f340)

Failed on OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8-nightly/921/testReport/com.hazelcast.jet.impl.connector/WriteJdbcPTest/

Various failures with similar stacktrace:

```
java.lang.Exception: Unexpected exception, expected<java.util.concurrent.CompletionException> but was<com.hazelcast.core.HazelcastInstanceNotActiveException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:30)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.instance.impl.HazelcastInstanceProxy.getOriginal(HazelcastInstanceProxy.java:322)
	at com.hazelcast.instance.impl.HazelcastInstanceProxy.getJet(HazelcastInstanceProxy.java:306)
	at com.hazelcast.jet.impl.connector.WriteJdbcPTest.testFailJob_whenGetConnection_withNonTransientException(WriteJdbcPTest.java:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 4 more
```

**Comment by ldziedziul** [comment] 2022-11-07 11:47
Could be a duplicate of https://github.com/hazelcast/hazelcast/issues/22670

**Closed** 2022-11-10 15:21 UTC
Labels: Type: Test-Failure, Source: Internal, Module: Jet, to-jira, Team: Platform
