### ISSUE TITLE
Node is not connected to the Management Center

### ISSUE THREAD

**Issue by dimas** [hazelcast/hazelcast#10482] opened 2017-05-03 21:23 UTC
Hazelcast 3.7.3

MC shows some nodes are not connected and ("Instance Connection Warning! Please make sure that all cluster members have the same.......")

tcpdump on one of these nodes shows zero traffic towards MC node - not even connection attempts unlike healthy nodes that chat a lot in that direction.

Thread dump (kill -3) shows NO signs of these three threads:
* ...MC.State.Sender
* ...MC.State.Sender
* ...MC.Task.Poller
which are present on a healthy node.

Apart from not reporting to MC the node seems healthy.

Found this in the logs (logged by com.hazelcast.internal.management.ManagementCenterService):
```
[3.7.3] Hazelcast Management Center Service will be shutdown due to exception.

java.lang.IllegalArgumentException: Invalid connection type: NONE
	at com.hazelcast.client.impl.ClientEndpointImpl.getClientType(ClientEndpointImpl.java:175)
	at com.hazelcast.internal.management.dto.ClientEndPointDTO.<init>(ClientEndPointDTO.java:40)
	at com.hazelcast.internal.management.TimedMemberStateFactory.createMemberState(TimedMemberStateFactory.java:142)
	at com.hazelcast.internal.management.TimedMemberStateFactory.createTimedMemberState(TimedMemberStateFactory.java:110)
	at com.hazelcast.internal.management.ManagementCenterService$PrepareStateThread.run(ManagementCenterService.java:305)
```

The exception message looks similar to https://github.com/hazelcast/hazelcast/issues/10480 but these can be different issues - this one about MC connection dying.

The only solution I found is restarting the node.

**Comment by sancar** [comment] 2017-05-04 06:49
It should be impossible to get a connection without NONE type.
It is caused by changes here #9183
It changes the logic of how connections handled on server side.
These issues are fixed in 3.7.6.

**Closed by sancar** 2017-05-04 06:49 UTC
