### ISSUE TITLE
[Management Center] 4.5G deleted files, disk full

### ISSUE THREAD

**Issue by brzler** [hazelcast/hazelcast#16952] opened 2020-05-04 09:54 UTC
**Describe the bug**
Deployed Management Center months ago. Today the disk went full and after analyzing the cause I discovered that the Hazelcast Management Center process still had hundreds of deleted files open which caused the disk to run full even though no files could be found with linux "df -f", some "lsof" output:

> java        1517           hzman   95u      REG              253,2 1578721280   12586273 /apps/hazelcast-management-center_myapp/myapp-t-202004.db (deleted)
java        1517           hzman   97u      REG              253,2 3253018624   12583348 /apps/hazelcast-management-center_myapp/myapp-t-202003.db (deleted)
java        1517   1942    hzman   95u      REG              253,2 1578721280   12586273 /apps/hazelcast-management-center_myapp/myapp-t-202004.db (deleted)
java        1517   1942    hzman   97u      REG              253,2 3253018624   12583348 /apps/hazelcast-management-center_myapp/myapp-t-202003.db (deleted)
java        1517   1984    hzman   95u      REG              253,2 1578721280   12586273 /apps/hazelcast-management-center_myapp/myapp-t-202004.db (deleted)
java        1517   1984    hzman   97u      REG              253,2 3253018624   12583348 /apps/hazelcast-management-center_myapp/myapp-t-202003.db (deleted)
java        1517   1988    hzman   95u      REG              253,2 1578721280   12586273 /apps/hazelcast-management-center_myapp/myapp-t-202004.db (deleted)
java        1517   1988    hzman   97u      REG              253,2 3253018624   12583348 /apps/hazelcast-management-center_myapp/myapp-t-202003.db (deleted)
java        1517   2098    hzman   95u      REG              253,2 1578721280   12586273 /apps/hazelcast-management-center_myapp/myapp-t-202004.db (deleted)
java        1517   2098    hzman   97u      REG              253,2 3253018624   12583348 /apps/hazelcast-management-center_myapp/myapp-t-202003.db (deleted)
java        1517   2129    hzman   95u      REG              253,2 1578721280   12586273 /apps/hazelcast-management-center_myapp/myapp-t-202004.db (deleted)
java        1517   2129    hzman   97u      REG              253,2 3253018624   12583348 /apps/hazelcast-management-center_myapp/myapp-t-202003.db (deleted)
java        1517   2164    hzman   95u      REG              253,2 1578721280   12586273 /apps/hazelcast-management-center_myapp/myapp-t-202004.db (deleted)
java        1517   2164    hzman   97u      REG              253,2 3253018624   12583348 /apps/hazelcast-management-center_myapp/myapp-t-202003.db (deleted)

After a restart 4.5GB of data were freed up and the disk was mostly empty again.

**Expected behavior**
Proper housekeeping.

**To Reproduce**
Don't know?!

**Additional context**
Hazelcast Management Center v3.12.7
Most basic setup.

**Comment by mmedenjak** [comment] 2020-05-04 10:23
Hi @brzler ! Thank you for the report. I'm not sure about the cause but I have some hunch. cc @puzpuzpuz @emre-aydin

**Comment by emre-aydin** [comment] 2020-05-04 15:14
Hi @brzler. Could you please share the command you use to start Management Center? I'm especially interested in whether you pass any parameters related to disk usage or not (https://docs.hazelcast.org/docs/management-center/3.12.7/manual/html/index.html#disk-usage-config).

**Comment by brzler** [comment] 2020-05-04 16:42
@emre-aydin I start it as systemd service with:

> WorkingDirectory=/apps/hazelcast-management-center_myapp
> ExecStart=/usr/bin/java -Djetty.base=/apps/hazelcast-management-center_myapp -Djetty.home=/apps/hazelcast-management-center_myapp -Dlogback.configurationFile=/apps/hazelcast-management-center_myapp/logback.xml -Dhazelcast.mc.home=/apps/hazelcast-management-center_myapp  -jar /apps/hazelcast-management-center_myapp/hazelcast-mancenter-3.12.7.war 10666 myapp

**Comment by emre-aydin** [comment] 2020-05-05 10:31
@brzler do you see any log entries that contain `Could not delete .lg file for ...` or `Could not delete file ... . This DB file might be open by Time Travel.`?

**Comment by emre-aydin** [comment] 2020-05-18 10:44
@brzler I have looked into the issue and I think I found the cause. It seems that we do not check whether we have an open file handle to the file we're deleting and close it. Unfortunately, we're a bit loaded at the moment preparing for our next minor release (4.1), so it will be a while before we get to working on the fix. I will keep you posted.

**Comment by mmedenjak** [comment] 2021-01-15 18:13
@emre-aydin can this issue be closed?

**Comment by emre-aydin** [comment] 2021-01-20 07:33
@mmedenjak yes, closing it now. It was fixed in Management Center version 3.12.11.

**Closed by emre-aydin** 2021-01-20 07:33 UTC
Labels: Source: Community, Team: Management Center, Type: Defect
