### ISSUE TITLE
ClassNotFoundException when using war classes with JCache api

### ISSUE THREAD

**Issue by smillidge** [hazelcast/hazelcast#4775] opened 2015-03-09 19:24 UTC
When Hazelcast is installed as an OSGI bundle on GlassFish (i.e. on the System classpath) and you deploy a war file that uses Hazelcast. A ClassNotFoundException is thrown when trying to put an object in the cache using the JCache api when that object is an instance of a class contained in the war.

When using the Hazelcast api raw it is possible to place an object into the Hazelcast cache. It is only the JCache api that fails.

JCache fails even if you specify the ClassLoader when creating the CacheManager e.g.

```java
        ClassLoader tccl = Thread.currentThread().getContextClassLoader();
        Thread.currentThread().setContextClassLoader(HazelcastInstance.class.getClassLoader());
        HazelcastInstance instance = Hazelcast.newHazelcastInstance();
        Thread.currentThread().setContextClassLoader(tccl);
        cp = HazelcastServerCachingProvider.createCachingProvider(instance);
        CacheManager cm = cp.getCacheManager(cp.getDefaultURI(), Thread.currentThread().getContextClassLoader());
```

Exception is;
```
  StandardWrapperValve[TestServlet]: Servlet.service() for servlet TestServlet threw exception
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: fish.payara.jsr107.test.TestPojo not found by com.hazelcast [304]
	at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:201)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.toObject(StreamSerializerAdapter.java:65)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:260)
	at com.hazelcast.cache.impl.CacheRecordStore.dataToValue(CacheRecordStore.java:112)
	at com.hazelcast.cache.impl.CacheRecordStore.recordToValue(CacheRecordStore.java:124)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.get(AbstractCacheRecordStore.java:766)
	at com.hazelcast.cache.impl.operation.CacheGetOperation.run(CacheGetOperation.java:50)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:733)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:709)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:560)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)
Caused by: java.lang.ClassNotFoundException: fish.payara.jsr107.test.TestPojo not found by com.hazelcast [304]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:124)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:113)
	at com.hazelcast.nio.IOUtil$1.resolveClass(IOUtil.java:113)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:196)
	... 12 more
|#]
```
It looks like the ClassLoader is not carried over in the CacheGetOperation and therefore is not setup correctly on the BasicOperationScheduler thread before attempting to load the object.

**Comment by smillidge** [comment] 2015-03-09 21:05
A little clarification JCache works if I bootstrap the HazelcastInstance in the same classloader as the war. However this means I have to have a Hazelcast cluster per deployed war (not ideal). 
The resetting of the TCCL in the code above is to force the bootstrap to happen with the System classloader as a test case.

Seems like the JCache api internally in Hazelcast does not use the ClassLoader set on the CacheManager.

**Comment by serkan-ozal** [comment] 2015-05-04 18:10
Hi @smillidge 
Sorry for late response. I have not tried to reproduce the issue yet but could you try also by setting TCCL to application classloader (`getClass().getClassLoader()`) instead of `HazelcastInstance.class.getClassLoader()` like this:

``` java
ClassLoader appClassLoader = getClass().getClassLoader();
ClassLoader tccl = Thread.currentThread().getContextClassLoader();
try {
    Thread.currentThread().setContextClassLoader(appClassLoader);
    HazelcastInstance instance = Hazelcast.newHazelcastInstance();
    CachingProvider cp = HazelcastServerCachingProvider.createCachingProvider(instance);
    CacheManager cm = cp.getCacheManager(cp.getDefaultURI(), appClassLoader));
} finally {
    Thread.currentThread().setContextClassLoader(tccl);
}
```

Regards.

**Comment by serkan-ozal** [comment] 2015-05-15 12:34
Hi @smillidge 

Setting application classloader as config classloader in `Config` object while getting `HazelcastInstance` worked for me on `Glassfish 4.1` as:

``` java
ClassLoader appClassLoader = getClass().getClassLoader();
Config config = new Config();
config.setClassLoader(appClassLoader);
HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
CachingProvider cp = HazelcastServerCachingProvider.createCachingProvider(instance);
CacheManager cm = cp.getCacheManager(cp.getDefaultURI(), appClassLoader));
```

However, yes there is an issue (https://github.com/hazelcast/hazelcast/issues/4632) about unnecessary deserialization at cache operation which is also one of the reasons of this issue. As you mentioned there is no `ClassNotFoundException` problem with `IMap` usage in this case since there is no unnecessary deserialization and no need to try for loading user class (`fish.payara.jsr107.test.TestPojo`).

Can you also verify that my advice fixes your case?

Regards.

**Comment by smillidge** [comment] 2015-05-15 15:37
Hi yes I will go back an test. I thought I had tried that but will revisit it to make sure.

In my test case we also have created the HazelcastCache outside of the web application.

**Comment by serkan-ozal** [comment] 2015-05-18 15:39
I am closing this issue since I think it is not problem that unknown class from Hazelcast side. Because the user should configure a classloader that knows the associated class (`fish.payara.jsr107.test.TestPojo`) especially in case of Hazelcast is defined as different module on OSGI environment. It is expected that Hazelcast cannot know a class outside of its module if there is not a configured classloader knows the associated class.

However, it is obvious that there is an unnecessary deserialization operation at cache and it will be fixed with this PR https://github.com/hazelcast/hazelcast/pull/5326.

Anyway, I am closing this issue because the real issue is this https://github.com/hazelcast/hazelcast/issues/4632

@smillidge thanks for reporting the issue.

**Closed by serkan-ozal** 2015-05-18 15:39 UTC
Labels: Team: Core, Type: Defect

**Comment by smillidge** [comment] 2015-05-18 21:09
I agree #4632 is the main issue
