### ISSUE TITLE
com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex [HZ-2369]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24342] opened 2023-04-24 05:57 UTC
_master_ (commit b2b4e628040928f6c81146d0695114919c0cbffe)

Failed on oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-little-endian/250/testReport/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: isIndexed should have located an index expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.lambda$testPostJoinMapOperation_mapWithIndex$0(PostJoinMapOperationTest.java:127)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1288)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1392)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex(PostJoinMapOperationTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-little-endian/250/

**Comment by JamesHazelcast** [comment] 2023-05-02 14:15
I am unable to reproduce this issue at all on my local machine (Windows laptop) with >5,000 test iterations over several testing sessions. There were also no reported failures when running this test on a 1,000x iteration loop in Jenkins, using the same JDK and OS as this test failure.

I conducted a deep dive comparison between the output logs of build #249 (success) and this failing build (#250), but there were no clear differences, even with the `TRACE` logging added to the `MapMigrationAwareService` and `DefaultRecordStore` by Ahmet back in 2020.

Based on this, I will close this issue as we await another test failure to re-open investigation.

**Comment by arodionov** [comment] 2023-05-03 09:58
Duplicate https://github.com/hazelcast/hazelcast/issues/17453

**Comment by olukas** [comment] 2023-05-15 06:11
Reopening as issue occurred again on: _master_ (commit f1f6e5efe9ebf76a9ebc02b791d7bd77a4854426)
with oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-little-endian/253/testReport/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: isIndexed should have located an index expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.lambda$testPostJoinMapOperation_mapWithIndex$0(PostJoinMapOperationTest.java:127)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1285)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1389)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex(PostJoinMapOperationTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-little-endian/253/

**Comment by JamesHazelcast** [comment] 2023-05-22 11:18
I ran dozens of Jenkins test jobs over the course of last week; with jobs repeatedly looping this specific test, as well as clones of the entire original job running in their entirety. Unfortunately I have not had any reproductions, and given the fact this test has only failed on JDK 8 here (which we no longer support in 5.4), I am going to kick back this issue to await another test failure before we conduct further investigation.

**Closed by JamesHazelcast** 2023-05-22 11:18 UTC
Labels: Team: Core, Type: Test-Failure, Source: Internal, Module: IMap, to-jira, waiting-for-next-failure
