### ISSUE TITLE
Performance regression in BaseIndexStore

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#11280] opened 2017-09-03 20:08 UTC
Current implementation of BaseIndexStore.copyToMultiResultSet(..) is:
```
    final void copyToMultiResultSet(MultiResultSet resultSet, Map<Data, QueryableEntry> records) {
        resultSet.addResultSet(new HashMap<Data, QueryableEntry>(records));
    }
```
is it really necessary to create a new Map here? I see a serious bottleneck in this line. After changing it to:
```
    final void copyToMultiResultSet(MultiResultSet resultSet, Map<Data, QueryableEntry> records) {
    	resultSet.addResultSet(records);
    }
```
I see performance improve in ~2.5 times on range queries over indexed attribute. All tests are still passed, and I don't see any issues in HZ behaviour.

Please have a look.

Thanks, Denis.

**Comment by tombujok** [comment] 2017-10-13 11:30
The regression is caused by this correctness fix:
https://github.com/hazelcast/hazelcast/pull/9688

**Comment by tombujok** [comment] 2017-10-13 11:30
Will be addressed in 3.8.7 and 3.9.1

**Comment by dsukhoroslov** [comment] 2017-10-13 13:51
Thanks @tombujok,
BTW, do you have unit tests where network partitioning/partition migration cases tested? I'd like to add this kind of tests to my test suite..

**Comment by mdogan** [comment] 2017-10-13 14:09
[QueryBounceTest](https://github.com/hazelcast/hazelcast/blob/3574d57d936154c45322e9ab0fe8449f7b6fbd8f/hazelcast/src/test/java/com/hazelcast/map/QueryBounceTest.java) is to test query with and without index while bouncing members. So, it tests effects of member shutdown/restart and partition migrations.

[IndexSplitBrainTest](https://github.com/hazelcast/hazelcast/blob/53b3a92c153439ae04eeacf2cf9d8f3d891922c8/hazelcast/src/test/java/com/hazelcast/query/impl/IndexSplitBrainTest.java) is to test indexed query during network partition.

**Comment by tombujok** [comment] 2017-11-03 19:59
Fixed via https://github.com/hazelcast/hazelcast/pull/11705

The fixes enables the users to choose: performance vs. correctness.

**Closed by tombujok** 2017-11-03 19:59 UTC
Labels: Team: Core, Type: Enhancement, Type: Perf. Defect

**Comment by dsukhoroslov** [comment] 2017-11-15 05:49
Hi @tombujok, 
I just tried this new option with HZ 3.8.7. Tried all 3 values. With COPY_ON_READ I see no performance improvement, it works like it was in HZ 3.8.6. With NEVER the performance for reads increased in 2..3 times, very good, but not sure this value can be used safely. With COPY_ON_WRITE I see the same improve for reads, but there is huge performance degradation on inserts, they become 30..50 times slower. Have a look, please.
