### ISSUE TITLE
hz-cli submit failure: intermittent and rare "Invalid lambda deserialization" [HZ-1173]

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#20019] opened 2021-12-03 09:23 UTC
Using `hz-cli` from _hazelcast5.0.zip_, against `Hazelcast Platform 5.1-SNAPSHOT (20211202 - c03d61a) `

Job submission mainly works. 10 attempts, 1 gave:

```
picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.client.console.HazelcastCommandLine.submit(com.hazelcast.client.console.HazelcastCommandLine$Verbosity,com.hazelcast.client.console.HazelcastCommandLine$TargetsMixin,java.lang.String,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.reflect.InvocationTargetException
	at picocli.CommandLine.execute(CommandLine.java:1207)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.client.console.HazelcastCommandLine.runCommandLine(HazelcastCommandLine.java:553)
	at com.hazelcast.client.console.HazelcastCommandLine.main(HazelcastCommandLine.java:133)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.instance.impl.HazelcastBootstrap.executeJar(HazelcastBootstrap.java:170)
	at com.hazelcast.client.console.HazelcastCommandLine.submit(HazelcastCommandLine.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
	... 18 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: com.hazelcast.jet.JetException: java.io.InvalidObjectException: ReflectiveOperationException during deserialization
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:111)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:276)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:66)
	at com.hazelcast.jet.impl.JobCoordinationService.deserializeJobDefinition(JobCoordinationService.java:1063)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:238)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$52(JobCoordinationService.java:1234)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$53(JobCoordinationService.java:1255)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: com.hazelcast.jet.JetException: java.io.InvalidObjectException: ReflectiveOperationException during deserialization
	at com.hazelcast.jet.impl.util.ExceptionUtil.peeledAndUnchecked(ExceptionUtil.java:134)
	at com.hazelcast.jet.impl.util.ExceptionUtil.rethrow(ExceptionUtil.java:145)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:533)
	at com.hazelcast.jet.impl.pipeline.transform.StreamSourceTransform.readObject(StreamSourceTransform.java:147)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2408)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at java.util.HashMap.readObject(HashMap.java:1544)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2408)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:92)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:85)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:270)
	... 12 more
Caused by: java.io.InvalidObjectException: ReflectiveOperationException during deserialization
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:280)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1321)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2251)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2142)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1730)
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at com.hazelcast.jet.impl.pipeline.transform.StreamSourceTransform.lambda$readObject$0(StreamSourceTransform.java:149)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:531)
	... 42 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:278)
	... 58 more
Caused by: java.lang.IllegalArgumentException: Invalid lambda deserialization
	at com.hazelcast.platform.demos.banking.trademonitor.PythonAnalysis.$deserializeLambda$(PythonAnalysis.java:1)
	... 63 more
```

**Comment by mmedenjak** [comment] 2022-01-03 11:57
@frant-hartm does this need to go into 5.1?

**Comment by mmedenjak** [comment] 2022-01-03 12:11
@neilstevenson is this a duplicate of https://github.com/hazelcast/hazelcast-enterprise/issues/4364?

**Comment by frant-hartm** [comment] 2022-01-03 12:26
> Using hz-cli from hazelcast5.0.zip, against Hazelcast Platform 5.1-SNAPSHOT (20211202 - c03d61a) 

The `hz-cli` and server versions must match, don't mix them. I am not aware of any breaking changes in 5.1, @neilstevenson can you verify this issue happens with matching version of hz-cli and the server?

**Comment by neilstevenson** [comment] 2022-01-10 10:58
If `hz-cli` and server versions must match, shouldn't it fail fast ?  Ie. `hz-cli` rejects conecting

**Comment by frant-hartm** [comment] 2022-01-17 13:02
@neilstevenson yes, this is a good point. We will add a check that the minor version matches. You should be able to use a different patch version, e.g. for 5.0.2 cluster, using 5.0 `hz-cli` should work fine.

**Closed** 2022-09-16 07:55 UTC
Labels: Type: Defect, Source: Internal, Module: Jet, to-jira, Team: Platform
