### ISSUE TITLE
ClientMaxAllowedInvocationTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10952] opened 2017-07-19 11:21 UTC
**com.hazelcast.client.ClientMaxAllowedInvocationTest.testMaxAllowed_andThenInternal**
```java
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:317)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:179)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:137)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:128)
	at com.hazelcast.client.ClientMaxAllowedInvocationTest.testMaxAllowed(ClientMaxAllowedInvocationTest.java:162)
	at com.hazelcast.client.ClientMaxAllowedInvocationTest.testMaxAllowed_andThenInternal(ClientMaxAllowedInvocationTest.java:115)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9845/testReport/junit/com.hazelcast.client/ClientMaxAllowedInvocationTest/testMaxAllowed_andThenInternal/

**Comment by ihsandemir** [comment] 2017-07-31 08:54
I analysed the log and here are my findings:

We see that there are 10 threads at the server for executor service and only 8 of them are waiting at sleep call com.hazelcast.client.ClientMaxAllowedInvocationTest$SleepyProcessor.call(ClientMaxAllowedInvocationTest.java:105)

The names of these threads are start with: "hz._hzInstance_20_dev.cached.thread-" Just look for this pattern at the attached output
[com.hazelcast.client.ClientMaxAllowedInvocationTest-output.txt](https://github.com/hazelcast/hazelcast/files/1186954/com.hazelcast.client.ClientMaxAllowedInvocationTest-output.txt)
 log file.

In the test we have 9 executorService.submit(new SleepyProcessor(Integer.MAX_VALUE)); calls, hence we do not see the 9th one.

The test seems fails at future.get(); call with timeout. Some possible reasons:

1. executorService.submit(new SleepyProcessor(0)) never run at the server. 
2. executorService.submit(new SleepyProcessor(0)) run but response is not received.
3. client request is never sent for executorService.submit(new SleepyProcessor(0)) call.

We could not reason for any of these possibilities. We can not also generate the case.

**Comment by ihsandemir** [comment] 2017-07-31 15:18
The issue could not be reproduced locally. Closing the issue for now. I added some more logs for diagnosis. I will examine the logs next time the test fails.

**Comment by mdogan** [comment] 2017-09-11 15:21
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:349)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:179)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:137)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:128)
	at com.hazelcast.client.ClientMaxAllowedInvocationTest.testMaxAllowed(ClientMaxAllowedInvocationTest.java:167)
	at com.hazelcast.client.ClientMaxAllowedInvocationTest.testMaxAllowed_andThen(ClientMaxAllowedInvocationTest.java:130)
```


https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10670/testReport/junit/com.hazelcast.client/ClientMaxAllowedInvocationTest/testMaxAllowed_andThen/

**Comment by ihsandemir** [comment] 2017-09-25 13:15
I could not reproduce the issue. It does not show failed on nightly runs but only at the PR builder. I did setup a jenkins build for this specific test and I ran it 70 times and could not observe the failure.

We examined the logs in detail. The request seems to have been processed at the client but the server side processor logs are missing for 3 threads, which we could not reason why and the client waits on the response (future.get()) which times out. I am closing the issue until it occurs again.

Not directly related to this issue but submitted and enhancement PR for client backpressure code here: https://github.com/hazelcast/hazelcast/pull/11419

**Comment by mdogan** [comment] 2017-10-02 06:55
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.hazelcast.client.ClientMaxAllowedInvocationTest.testMaxAllowed(ClientMaxAllowedInvocationTest.java:167)
	at com.hazelcast.client.ClientMaxAllowedInvocationTest.testMaxAllowed_andThenExecutor(ClientMaxAllowedInvocationTest.java:140)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10986/testReport/junit/com.hazelcast.client/ClientMaxAllowedInvocationTest/testMaxAllowed_andThenExecutor/

**Comment by ihsandemir** [comment] 2017-10-09 10:25
I analysed the problem further. I put a number of debugs in the logs and run the case at a jenkins build and after some run, we can reproduce the case. The filtered log is here: 
[com.hazelcast.client.ClientMaxAllowedInvocationTest-output_filtered_test_Case.txt](https://github.com/hazelcast/hazelcast/files/1368134/com.hazelcast.client.ClientMaxAllowedInvocationTest-output_filtered_test_Case.txt)

When CachedExecutorServiceDelegate.execute is called, it enqueues a runnable in the task queue and tries to fork a Worker thread if under capacity. The default capacity is up to 16 threads. For our test case I expect to see 9 such long lasting threads and one thread which exits after 0 seconds (immediately). The problem is that for some CachedExecutorServiceDelegate.execute calls, the addNewWorkerIfRequired fails to add a worker since it can not get the lock in 1 msecs while the other thread is holding it and hence no thread is spawn. And since our sleepyprocessors sleep indefinitely, there is no exit to trigger addNewWorkerIfRequired method. Hence, the runnable is waiting the task queue but since there is no worker, it is not being processed. 

Please grep 
"addNewWorkerIfRequired.  name:668fddee-f768-4c92-aafa-5bd3a5482afd"
and 
"addNewWorkerIfRequired.  name:668fddee-f768-4c92-aafa-5bd3a5482afdCOULD NOT get LOCK."
to see the related logs.

So, what is the solution? Some options:
1. Run a periodically scheduled task (e.g. 1 sec) which will trigger the addNewWorkerIfRequired method.
2. keep the lock.tryLock(TIME, TimeUnit.MILLISECONDS) duration longer, e.g. 10 seconds.

**Comment by mdogan** [comment] 2017-10-09 10:37
@ihsandemir: I think we can acquire the lock without a timeout, `lock.lock()`, because the task done under lock is not time consuming.

```java
    private void addNewWorkerIfRequired() {
        if (size < maxPoolSize) {
            try {
                lock.lockInterruptibly();
                try {
                    if (size < maxPoolSize && getQueueSize() > 0) {
                        size++;
                        cachedExecutor.execute(new Worker());
                    }
                } finally {
                    lock.unlock();
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }
    }
```

**Closed** 2017-10-09 15:16 UTC
Labels: Team: Client, Type: Test-Failure
