### ISSUE TITLE
Eviction is not triggering with FREE_HEAP_PERCENTAGE eviction policy

### ISSUE THREAD

**Issue by manojPenupothu** [hazelcast/hazelcast#16753] opened 2020-03-16 08:42 UTC
I'm using hazelcast 3.12.2 version. As per the project requirement I have created three MapConfig's by providing MaxsizeConfig as 20% of FREE_HEAP_PERCENTAGE. In each Map I'm trying to cache 10MB,15MB,20MB files of 10 in number. My total heap space while  running application is 450MB.
As per the documentation if heap size reaches to 80% eviction will trigger as per the probabilistic algorithm defined with mentioned free heap percentage configuration,but its not happening.

  
**Describe the bug**
Eviction is not triggering with FREE_HEAP_PERCENTAGE policy

**Expected behavior**
Expected behavior is When 80% of the heap space is utilized eviction should trigger automatically.
**To Reproduce**

Attaching the sample program and heap dump
[java_pid13400.zip](https://github.com/hazelcast/hazelcast/files/4337047/java_pid13400.zip)
[HazelcastMaxSizeTest.zip](https://github.com/hazelcast/hazelcast/files/4337063/HazelcastMaxSizeTest.zip)

**Additional context**

**Comment by ahmetmircik** [comment] 2020-03-16 11:11
Hi @manojPenupothu,
I looked your reproducer. This part seems wrong:
```
private static HazelcastInstance startHazelcast(String instanceName, MaxSizeConfig maxSizeConfig) {

        MapConfig mapConfig = new MapConfig(MAP_NAME);
        mapConfig.setMaxSizeConfig(maxSizeConfig);
        mapConfig.setStatisticsEnabled(false);
        mapConfig.setEvictionPolicy(EvictionPolicy.LRU);
        mapConfig.setMinEvictionCheckMillis(0L);
        mapConfig.setBackupCount(1);

        MapConfig mapConfig1 = new MapConfig(MAP_NAME1);
        mapConfig.setMaxSizeConfig(maxSizeConfig);<-- should be mapConfig1
        mapConfig.setStatisticsEnabled(false);
        mapConfig.setEvictionPolicy(EvictionPolicy.LRU);
        mapConfig.setMinEvictionCheckMillis(0L);
        mapConfig.setBackupCount(1);

        MapConfig mapConfig2 = new MapConfig(MAP_NAME2);
        mapConfig.setMaxSizeConfig(maxSizeConfig);<-- should be mapConfig2
        mapConfig.setStatisticsEnabled(false);
        mapConfig.setEvictionPolicy(EvictionPolicy.LRU);
        mapConfig.setMinEvictionCheckMillis(0L);
        mapConfig.setBackupCount(1);

```  
This code makes only first map evictable since other mapConfigs also set values to first `mapConfig` object.

Also i'll recommend you to give a little more memory to make hazelcast internals work. For this purpose you can increase FREE_HEAP_PERCENTAGE to something >= 30.

When i do both everything seems to be working as expected. 
Can you please verify this on your side?

**Comment by manojPenupothu** [comment] 2020-03-16 11:54
I tried after changing the code accordingly by increasing free heap percentage to 40,providing individual maxsizeconfig to each map and the same heap space of 450MB,but still i'm facing out of memory issue.Attaching the code and heap dump.
Question is even though map size is going beyond why eviction is not triggering.
And one more observation I found is that if i'm trying to cache 400mb by configuring only  one map instance and heap space is less than 400mb then eviction is triggering as expected.But the same is not happening with multiple map instances.
Apart from the above if it is live environment we don't have control on how much data we are going to cache right.It is a dynamic thing.So can you please help me to handle  this scenario.
[HazelcastMaxSizeTest.zip](https://github.com/hazelcast/hazelcast/files/4337996/HazelcastMaxSizeTest.zip)
[java_pid552.zip](https://github.com/hazelcast/hazelcast/files/4337998/java_pid552.zip)

**Comment by ahmetmircik** [comment] 2020-03-16 12:08
This is still wrong:
```
	    MapConfig mapConfig = new MapConfig(MAP_NAME);
        mapConfig.setMaxSizeConfig(maxSizeConfig1);
        mapConfig.setStatisticsEnabled(false);
        mapConfig.setEvictionPolicy(EvictionPolicy.LRU);
        mapConfig.setMinEvictionCheckMillis(0L);
        mapConfig.setBackupCount(1);

        MapConfig mapConfig1 = new MapConfig(MAP_NAME1);
        mapConfig.setMaxSizeConfig(maxSizeConfig2);
        mapConfig.setStatisticsEnabled(false);
        mapConfig.setEvictionPolicy(EvictionPolicy.LRU);
        mapConfig.setMinEvictionCheckMillis(0L);
        mapConfig.setBackupCount(1);

        MapConfig mapConfig2 = new MapConfig(MAP_NAME2);
        mapConfig.setMaxSizeConfig(maxSizeConfig3);
        mapConfig.setStatisticsEnabled(false);
        mapConfig.setEvictionPolicy(EvictionPolicy.LRU);
        mapConfig.setMinEvictionCheckMillis(0L);
        mapConfig.setBackupCount(1);
```

Fixed version is:

```
	    MapConfig mapConfig = new MapConfig(MAP_NAME);
        mapConfig.setMaxSizeConfig(maxSizeConfig1);
        mapConfig.setStatisticsEnabled(false);
        mapConfig.setEvictionPolicy(EvictionPolicy.LRU);
        mapConfig.setMinEvictionCheckMillis(0L);
        mapConfig.setBackupCount(1);

        MapConfig mapConfig1 = new MapConfig(MAP_NAME1);
        mapConfig1.setMaxSizeConfig(maxSizeConfig2);
        mapConfig1.setStatisticsEnabled(false);
        mapConfig1.setEvictionPolicy(EvictionPolicy.LRU);
        mapConfig1.setMinEvictionCheckMillis(0L);
        mapConfig1.setBackupCount(1);

        MapConfig mapConfig2 = new MapConfig(MAP_NAME2);
        mapConfig2.setMaxSizeConfig(maxSizeConfig3);
        mapConfig2.setStatisticsEnabled(false);
        mapConfig2.setEvictionPolicy(EvictionPolicy.LRU);
        mapConfig2.setMinEvictionCheckMillis(0L);
        mapConfig2.setBackupCount(1);
```

Can you please retry after replacing `mapConfig with mapConfig1 for MAP_NAME1's map config` and replace `mapConfig with mapConfig2 for MAP_NAME2 map config`.

**Comment by manojPenupothu** [comment] 2020-03-17 09:16
This code works exactly as expected with bytes.But the same code if i'm trying to store objects of bigger size eviction is not triggered. Do we have any recommendation for this.

**Comment by ahmetmircik** [comment] 2020-03-17 09:52
can you please share a reproducer for this also?

**Comment by manojPenupothu** [comment] 2020-03-17 11:46
Actually the issue is happening with live environment.But it can attach some of the logs from hazelcast health monitor
{"log":"com.hazelcast.internal.diagnostics.HealthMonitor","lvl":"INFO","thread":"hz.ams-broker-promotion-hazelcast.HealthMonitor","msg":"[153.78.37.95]:5701 [ams-broker-promotion] [3.12.2] processors=8, physical.memory.total=31.4G, physical.memory.free=18.8G, swap.space.total=0, swap.space.free=0, heap.memory.used=7.2G, heap.memory.free=1.0G, heap.memory.total=8.3G, heap.memory.max=8.9G, heap.memory.used/total=86.95%, heap.memory.used/max=81.00%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, load.process=73.01%, load.system=72.42%, load.systemAverage=5.86, thread.count=68, thread.peakCount=75, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=84868, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0","@timestamp":"2020-03-17T11:33:16.006Z","app":"cmp"}

{"log":"com.hazelcast.internal.diagnostics.HealthMonitor","lvl":"INFO","thread":"hz.ams-broker-promotion-hazelcast.HealthMonitor","msg":"[153.78.37.95]:5701 [ams-broker-promotion] [3.12.2] processors=8, physical.memory.total=31.4G, physical.memory.free=18.8G, swap.space.total=0, swap.space.free=0, heap.memory.used=7.8G, heap.memory.free=537.2M, heap.memory.total=8.3G, heap.memory.max=8.9G, heap.memory.used/total=93.63%, heap.memory.used/max=87.21%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, load.process=89.94%, load.system=89.45%, load.systemAverage=7.16, thread.count=68, thread.peakCount=75, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=1, executor.q.priorityOperation.size=0, operations.completed.count=84868, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0","@timestamp":"2020-03-17T11:33:38.027Z","app":"cmp"}

{"log":"com.hazelcast.internal.diagnostics.HealthMonitor","lvl":"INFO","thread":"hz.ams-broker-promotion-hazelcast.HealthMonitor","msg":"[153.78.37.95]:5701 [ams-broker-promotion] [3.12.2] processors=8, physical.memory.total=31.4G, physical.memory.free=18.8G, swap.space.total=0, swap.space.free=0, heap.memory.used=7.8G, heap.memory.free=517.6M, heap.memory.total=8.3G, heap.memory.max=8.9G, heap.memory.used/total=93.89%, heap.memory.used/max=87.46%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, load.process=96.93%, load.system=96.28%, load.systemAverage=7.74, thread.count=71, thread.peakCount=75, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=84868, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0","@timestamp":"2020-03-17T11:34:00.569Z","app":"cmp"}

Can you please let us know if something wrong in this.And the configuration is same as earlier shared reproducer

**Comment by ahmetmircik** [comment] 2020-03-17 14:10
Try to set `hazelcast.map.eviction.batch.size`. This forces map to evict more than 1 entry at a time. Since, in your case, entry sizes are not equal, eviction one entry at a time may not be the ideal option.

```
Config config = new Config();
config.setProperty("hazelcast.map.eviction.batch.size", "3");
```

**Comment by manojPenupothu** [comment] 2020-03-17 19:29
I have tried with above configuration and free heap percentage is >=30,but the attached code is not evicting and eventually leading to Heap space.For test purpose i have hardcoded file size but in live environment file size is dynamic.In that case just want to know is there any hard limit on file size i'm going to store in hazelcast map?
Is there any minimum requirement on heap space for hazelcast to evict the entries?
Attaching the heap dump and reproducer.I'm running the test with 450mb heap space.
[HazelcastMaxSizeTest.zip](https://github.com/hazelcast/hazelcast/files/4345412/HazelcastMaxSizeTest.zip)
[java_pid14504.zip](https://github.com/hazelcast/hazelcast/files/4345415/java_pid14504.zip)

**Comment by ahmetmircik** [comment] 2020-03-18 06:52
>I have tried with above configuration and free heap percentage is >=30,but the attached code is not evicting and eventually leading to Heap space

Yes, because you are getting OOME during serialization phase, it is before put to map. This is not map eviction related problem. In the reproducer, you want to put 100MB object and serialization creates a clone of it. This means at the same time you have two copy of that 100MB object. But you don't have enough memory and you go OOM.You need to give much memory to process.

>For test purpose i have hardcoded file size but in live environment file size is dynamic.In that case just want to know is there any hard limit on file size i'm going to store in hazelcast map?

No hard limit but huge objects are not appropriate, we generally purpose smaller objects in size like 5 or 10 MB at max. Otherwise, overall system performance degrades.

>Is there any minimum requirement on heap space for hazelcast to evict the entries?

As i said what you saw is not eviction related per se. Just test your needs and find an appropriate memory value for your case.

**Comment by ahmetmircik** [comment] 2020-04-08 08:02
Closing this issue now, if you have further questions, it can be opened again.

**Closed by ahmetmircik** 2020-04-08 08:02 UTC
Labels: Module: IMap, Source: Community, Team: Core, Type: Defect
