### ISSUE TITLE
Client not dealing with Serverside OOME correctly

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#8821] opened 2016-08-31 17:16 UTC
When using the following simulator program I run into problems.

```
coordinator-remote start-worker --count 2 --workerType member
coordinator-remote start-worker --count 2 --workerType javaclient
coordinator-remote run atomiclong.properties --duration 5m
```

And while this is running I cause an OOME on the first member:

```
coordinator-remote kill-worker  --workerType member --command OOME
```

The clients are running into problems eventually

```
INFO  19:58:57 AtomicLongTest Starting Test start on all client Workers
INFO  19:58:58 AtomicLongTest Completed Test start
INFO  19:58:58 AtomicLongTest Test will run for 00d 00h 05m 00s
INFO  19:59:08 AtomicLongTest Running 00d 00h 00m 10s (  3.33%)        17,736 ops         0.00 ops/s      4,622 µs (avg)  1,001,390 µs (99.9th)  1,014,497 µs (max)
INFO  19:59:18 AtomicLongTest Running 00d 00h 00m 20s (  6.67%)       256,117 ops    23,838.10 ops/s        891 µs (avg)     23,855 µs (99.9th)     49,512 µs (max)
INFO  19:59:28 AtomicLongTest Running 00d 00h 00m 30s ( 10.00%)       591,016 ops    33,489.90 ops/s        598 µs (avg)      2,807 µs (99.9th)     28,082 µs (max)
INFO  19:59:38 AtomicLongTest Running 00d 00h 00m 40s ( 13.33%)       941,685 ops    35,065.12 ops/s        578 µs (avg)      2,914 µs (99.9th)     15,958 µs (max)
INFO  19:59:43 Valid connection from /127.0.0.1:39730 (magic bytes found)
INFO  19:59:43 Killing 1 worker with versionSpec [null] and workerType [member]...
INFO  19:59:43 Killing 1 workers starting
INFO  19:59:43 Killing [C_A1_W1]
INFO  19:59:43 Kill send to worker [C_A1_W1]
INFO  19:59:43 Waiting for [C_A1_W1] to die
INFO  19:59:48 Waiting for [C_A1_W1] to die
INFO  19:59:48 AtomicLongTest Running 00d 00h 00m 50s ( 16.67%)     1,277,776 ops    33,609.10 ops/s        607 µs (avg)      2,301 µs (99.9th)     18,202 µs (max)
INFO  19:59:53 Waiting for [C_A1_W1] to die
INFO  19:59:58 Waiting for [C_A1_W1] to die
INFO  19:59:58 AtomicLongTest Running 00d 00h 01m 00s ( 20.00%)     1,367,108 ops     8,933.20 ops/s      1,805 µs (avg)      9,977 µs (99.9th)  2,592,079 µs (max)
INFO  20:00:03 Waiting for [C_A1_W1] to die
INFO  20:00:08 Waiting for [C_A1_W1] to die
INFO  20:00:08 AtomicLongTest Running 00d 00h 01m 10s ( 23.33%)     1,367,108 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:00:13 Waiting for [C_A1_W1] to die
INFO  20:00:18 Waiting for [C_A1_W1] to die
INFO  20:00:18 AtomicLongTest Running 00d 00h 01m 20s ( 26.67%)     1,367,108 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:00:23 Waiting for [C_A1_W1] to die
INFO  20:00:28 Waiting for [C_A1_W1] to die
INFO  20:00:28 AtomicLongTest Running 00d 00h 01m 30s ( 30.00%)     1,367,108 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:00:33 Waiting for [C_A1_W1] to die
INFO  20:00:38 Waiting for [C_A1_W1] to die
INFO  20:00:38 AtomicLongTest Running 00d 00h 01m 40s ( 33.33%)     1,370,623 ops       351.50 ops/s    240,088 µs (avg) 39,057,358 µs (99.9th) 39,057,358 µs (max)
INFO  20:00:43 Waiting for [C_A1_W1] to die
INFO  20:00:48 Waiting for [C_A1_W1] to die
INFO  20:00:48 AtomicLongTest Running 00d 00h 01m 50s ( 36.67%)     1,370,623 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:00:53 Waiting for [C_A1_W1] to die
INFO  20:00:58 Waiting for [C_A1_W1] to die
INFO  20:00:58 AtomicLongTest Running 00d 00h 02m 00s ( 40.00%)     1,370,623 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:01:03 Waiting for [C_A1_W1] to die
INFO  20:01:08 Waiting for [C_A1_W1] to die
INFO  20:01:08 AtomicLongTest Running 00d 00h 02m 10s ( 43.33%)     1,370,623 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:01:13 Waiting for [C_A1_W1] to die
INFO  20:01:18 Waiting for [C_A1_W1] to die
INFO  20:01:18 AtomicLongTest Running 00d 00h 02m 20s ( 46.67%)     1,374,516 ops       389.30 ops/s    228,458 µs (avg) 39,963,328 µs (99.9th) 39,963,328 µs (max)
INFO  20:01:23 Waiting for [C_A1_W1] to die
INFO  20:01:28 Waiting for [C_A1_W1] to die
INFO  20:01:28 AtomicLongTest Running 00d 00h 02m 30s ( 50.00%)     1,376,121 ops       160.50 ops/s     49,805 µs (avg)  3,527,409 µs (99.9th)  3,529,506 µs (max)
INFO  20:01:33 Waiting for [C_A1_W1] to die
INFO  20:01:38 Waiting for [C_A1_W1] to die
INFO  20:01:38 AtomicLongTest Running 00d 00h 02m 40s ( 53.33%)     1,376,121 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:01:43 Waiting for [C_A1_W1] to die
INFO  20:01:48 Waiting for [C_A1_W1] to die
INFO  20:01:48 AtomicLongTest Running 00d 00h 02m 50s ( 56.67%)     1,376,121 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:01:53 Waiting for [C_A1_W1] to die
INFO  20:01:58 Waiting for [C_A1_W1] to die
INFO  20:01:58 AtomicLongTest Running 00d 00h 03m 00s ( 60.00%)     1,376,121 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:02:03 Waiting for [C_A1_W1] to die
INFO  20:02:08 Waiting for [C_A1_W1] to die
INFO  20:02:08 AtomicLongTest Running 00d 00h 03m 10s ( 63.33%)     1,376,121 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:02:13 Waiting for [C_A1_W1] to die
INFO  20:02:18 Waiting for [C_A1_W1] to die
INFO  20:02:18 AtomicLongTest Running 00d 00h 03m 20s ( 66.67%)     1,376,123 ops         0.20 ops/s     54,811 ms (avg)     54,827 ms (99.9th)     54,827 ms (max)
INFO  20:02:23 Waiting for [C_A1_W1] to die
INFO  20:02:28 Waiting for [C_A1_W1] to die
INFO  20:02:28 AtomicLongTest Running 00d 00h 03m 30s ( 70.00%)     1,376,123 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:02:33 Waiting for [C_A1_W1] to die
INFO  20:02:38 Waiting for [C_A1_W1] to die
INFO  20:02:38 AtomicLongTest Running 00d 00h 03m 40s ( 73.33%)     1,376,123 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:02:43 Waiting for [C_A1_W1] to die
INFO  20:02:48 Waiting for [C_A1_W1] to die
INFO  20:02:48 AtomicLongTest Running 00d 00h 03m 50s ( 76.67%)     1,376,137 ops         1.40 ops/s     53,743 ms (avg)     86,234 ms (99.9th)     86,234 ms (max)
INFO  20:02:53 Waiting for [C_A1_W1] to die
INFO  20:02:58 Waiting for [C_A1_W1] to die
INFO  20:02:58 AtomicLongTest Running 00d 00h 04m 00s ( 80.00%)     1,376,137 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:03:03 Waiting for [C_A1_W1] to die
INFO  20:03:08 Waiting for [C_A1_W1] to die
INFO  20:03:08 AtomicLongTest Running 00d 00h 04m 10s ( 83.33%)     1,376,137 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:03:13 Waiting for [C_A1_W1] to die
WARN  20:03:13 Failure #1 C_A1_W4 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:03:13 Failure #2 C_A1_W4 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:03:13 Failure #3 C_A1_W4 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:03:13 Failure #4 C_A1_W4 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:03:14 Failure #5 C_A1_W4 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:03:14 Failure #6 C_A1_W4 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:03:15 Failure #7 C_A1_W4 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:03:15 Failure #8 C_A1_W4 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:03:16 Failure #9 C_A1_W4 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:03:16 Failure #10 C_A1_W4 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
INFO  20:03:18 Waiting for [C_A1_W1] to die
INFO  20:03:18 AtomicLongTest Running 00d 00h 04m 20s ( 86.67%)     1,376,137 ops         0.00 ops/s          0 µs (avg)          0 µs (99.9th)          0 µs (max)
INFO  20:03:18 AtomicLongTest Critical failure detected, aborting run phase
INFO  20:03:18 AtomicLongTest Test finished running
INFO  20:03:19 AtomicLongTest Executing Test stop
INFO  20:03:23 Waiting for [C_A1_W1] to die
INFO  20:03:28 Waiting for [C_A1_W1] to die
INFO  20:03:33 Waiting for [C_A1_W1] to die
INFO  20:03:38 Waiting for [C_A1_W1] to die
INFO  20:03:43 Waiting for [C_A1_W1] to die
INFO  20:03:48 Waiting for [C_A1_W1] to die
INFO  20:03:53 Waiting for [C_A1_W1] to die
INFO  20:03:58 Waiting for [C_A1_W1] to die
INFO  20:04:03 Waiting for [C_A1_W1] to die
INFO  20:04:08 Waiting for [C_A1_W1] to die
INFO  20:04:13 Waiting for [C_A1_W1] to die
INFO  20:04:18 Waiting for [C_A1_W1] to die
INFO  20:04:23 Waiting for [C_A1_W1] to die
INFO  20:04:28 Waiting for [C_A1_W1] to die
INFO  20:04:33 Waiting for [C_A1_W1] to die
INFO  20:04:38 Waiting for [C_A1_W1] to die
WARN  20:04:40 Failure #11 C_A1_W3 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:04:40 Failure #12 C_A1_W3 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:04:40 Failure #13 C_A1_W3 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:04:41 Failure #14 C_A1_W3 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:04:41 Failure #15 C_A1_W3 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:04:41 Failure #16 C_A1_W3 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:04:41 Failure #17 C_A1_W3 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
WARN  20:04:41 Failure #18 C_A1_W3 AtomicLongTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: java.io.IOException: No available connection to address [10.169.205.10]:5701]
W
```

Hazelcast version used  here is 3.8-SNAPSHOT.

It is a tricky situation because the member has not killed itself yet. But eventually every client that is touching that OOME'ing member; will run into problems itself.

This is the used hazelcast-client.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast-client
        xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
            http://www.hazelcast.com/schema/config/hazelcast-client-config-3.6.xsd"
        xmlns="http://www.hazelcast.com/schema/client-config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <group>
        <name>workers</name>
    </group>

    <network>
    <redo-operation>true</redo-operation>
        <cluster-members>
            <!--MEMBERS-->
        </cluster-members>
    </network>

    <!--LICENSE-KEY-->

    <serialization>
        <data-serializable-factories>
            <data-serializable-factory factory-id="4000">
                com.hazelcast.simulator.tests.map.domain.IdentifiedDataSerializableObjectFactory
            </data-serializable-factory>
        </data-serializable-factories>

        <portable-version>1</portable-version>
        <portable-factories>
            <portable-factory factory-id="10000001">com.hazelcast.simulator.tests.map.domain.PortableObjectFactory</portable-factory>
            <portable-factory factory-id="10000002">com.hazelcast.simulator.tests.map.helpers.ComplexDomainObjectPortableFactory</portable-factory>
        </portable-factories>
    </serialization>
</hazelcast-client>
```

I need to do further analysis and I'll send the log bundle.

**Comment by tombujok** [comment] 2017-01-13 15:47
@ihsandemir @asimarslan Guys, will you be addressing this within 3.8's code-freeze? Or are we moving it to 3.9?

**Comment by sancar** [comment] 2017-01-19 11:46
I think we need to work on this if there is an issue but team did not have time to focus on this yet. 
We have heartbeat mechanism to figure out unresponsive node. A node that goes OOME can be detected via that. And we have tests that verifying that it works.

So, we need more detailed logs to understand the problem. Is member kicked out of memberlist ? Is client detected hearbeat failure etc ? 

It seems that @pveentjer  also could not work on this to send the long bundle.

**Comment by tombujok** [comment] 2017-01-19 19:44
@pveentjer Could you try reproducing this one with some more verbose logging and ping @sancar?
It's one of the few unassigned issues for 3.8 that looks concerning.

**Comment by sancar** [comment] 2017-03-22 11:16
A related fix is done here:
https://hazelcast.atlassian.net/wiki/display/PM/Client+Back+Pressure+Enchancement+Design+Doc
Server side OOME causing client side OOME because client retries are not handled correctly.
I am closing this issue, assuming it is fixed with  https://github.com/hazelcast/hazelcast/pull/10086

**Closed by sancar** 2017-03-22 11:16 UTC
Labels: Team: Client, Type: Defect
