### ISSUE TITLE
Hazelcast server reaches 100% CPU

### ISSUE THREAD

**Issue by IlaiG** [hazelcast/hazelcast#4038] opened 2014-11-09 08:25 UTC
We are running Hazelcast 3.3.1 in a client-server architecture with 2 Hazelcast server nodes running on AWS.

Both servers reached 100% CPU usage and high network utilization. The only messages in the hazelcast log at that time were:

```
» 15:21:34.673  Nov 07, 2014 1:20:59 PM com.hazelcast.nio.tcp.TcpIpConnection
» 15:21:34.673  INFO: [HAZEL1]:5701 [dev] [3.3.1] Connection [Address[APPSERVER1]:46507] lost. Reason: java.io.EOFException[Remote socket closed!]
» 15:21:34.673  Nov 07, 2014 1:20:59 PM com.hazelcast.nio.tcp.ReadHandler
» 15:21:34.673  WARNING: [HAZEL1]:5701 [dev] [3.3.1] hz._hzInstance_1_dev.IO.thread-in-0 Closing socket to endpoint Address[APPSERVER1]:46507, Cause:java.io.EOFException: Remote socket closed!
» 15:21:34.673  Nov 07, 2014 1:20:59 PM com.hazelcast.client.ClientEndpointManager
» 15:21:34.673  INFO: [HAZEL1]:5701 [dev] [3.3.1] Destroying ClientEndpoint{conn=Connection [ip-10-140-150-135.ec2.internal/APPSERVER1:46508 -> Address[APPSERVER1]:46508] live=true, client=true, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='aba631c2-5287-4524-a1ed-275972e692da', ownerUuid='67682b74-08fa-4e9c-96e0-577b995c5841'}', firstConnection=false, authenticated=true}
» 15:21:35.670  Nov 07, 2014 1:21:00 PM com.hazelcast.nio.tcp.SocketAcceptor
» 15:21:35.670  INFO: [HAZEL1]:5701 [dev] [3.3.1] Accepting socket connection from /APPSERVER1:56784
» 15:21:35.670  Nov 07, 2014 1:21:00 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
» 15:21:35.670  INFO: [HAZEL1]:5701 [dev] [3.3.1] Established socket connection between /HAZEL1:5701 and /APPSERVER1:56784
» 15:21:39.677  Nov 07, 2014 1:21:04 PM com.hazelcast.client.ClientEngine
» 15:21:39.677  SEVERE: [HAZEL1]:5701 [dev] [3.3.1] Dropping: Packet{header=0, isResponse=false, isOperation=false, isEvent=false, partitionId=207, conn=Connection [ip-10-140-150-135.ec2.internal/APPSERVER1:46508 -> Address[APPSERVER1]:46508] live=true, client=true, type=JAVA_CLIENT} -> no endpoint found for live connection.
» 15:21:39.677  Nov 07, 2014 1:21:04 PM com.hazelcast.client.ClientEngine
» 15:21:39.677  SEVERE: [HAZEL1]:5701 [dev] [3.3.1] Dropping: Packet{header=0, isResponse=false, isOperation=false, isEvent=false, partitionId=196, conn=Connection [ip-10-140-150-135.ec2.internal/APPSERVER1:46508 -> Address[APPSERVER1]:46508] live=true, client=true, type=JAVA_CLIENT} -> no endpoint found for live connection.
» 15:21:39.877  Nov 07, 2014 1:21:04 PM com.hazelcast.client.ClientEngine
» 15:21:39.877  SEVERE: [HAZEL1]:5701 [dev] [3.3.1] Dropping: Packet{header=0, isResponse=false, isOperation=false, isEvent=false, partitionId=211, conn=Connection [ip-10-140-150-135.ec2.internal/APPSERVER1:46508 -> Address[APPSERVER1]:46508] live=true, client=true, type=JAVA_CLIENT} -> no endpoint found for live connection.
» 15:21:39.877  Nov 07, 2014 1:21:04 PM com.hazelcast.client.ClientEngine
» 15:21:39.877  SEVERE: [HAZEL1]:5701 [dev] [3.3.1] Dropping: Packet{header=0, isResponse=false, isOperation=false, isEvent=false, partitionId=259, conn=Connection [ip-10-140-150-135.ec2.internal/APPSERVER1:46508 -> Address[APPSERVER1]:46508] live=true, client=true, type=JAVA_CLIENT} -> no endpoint found for live connection.
» 15:21:39.877  Nov 07, 2014 1:21:04 PM com.hazelcast.client.ClientEngine
» 15:21:39.877  SEVERE: [HAZEL1]:5701 [dev] [3.3.1] Dropping: Packet{header=0, isResponse=false, isOperation=false, isEvent=false, partitionId=144, conn=Connection [ip-10-140-150-135.ec2.internal/APPSERVER1:46508 -> Address[APPSERVER1]:46508] live=true, client=true, type=JAVA_CLIENT} -> no endpoint found for live connection.
```

There was no heavy load coming from our side at that time.

All connections from our code to the hazelcast servers failed and the only solution was to restart all hazelcast servers.

**Comment by enesakar** [comment] 2015-01-15 12:01
we can not progress without more information (e.g. thread dump).
I am closing, you can reopen it when reproduced with more data.

**Closed by enesakar** 2015-01-15 12:01 UTC
Labels: PENDING

**Comment by efic1** [comment] 2015-01-15 14:25
Just an update on this issue, the root cause was time synchronization of the cluster nodes, we had a few node which drifted a lot (more than 5 min). setting a ntp of the servers solved the problem.
