### ISSUE TITLE
inconsistency between hazelcast invalid config exceptions

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#6624] opened 2015-11-02 10:47 UTC
In hazelcast, if user has invalid config, we are throwing invalid config exceptions. In some cases, we are throwing run time exceptions. We need to examine those exceptions and provide consistency.

**Comment by mesutcelik** [comment] 2015-11-02 10:51
any example?

**Comment by kobalski** [comment] 2015-11-02 11:24
One example can be like here, that line was only throwing `RuntimeException` before : https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java#L152

**Comment by mmedenjak** [comment] 2021-02-25 21:40
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/14713

**Closed by mmedenjak** 2021-02-25 21:40 UTC
Labels: Estimation: M, Module: Config, Priority: Medium, Public API/SPI breaking change, Source: Internal, Team: Core, Type: Enhancement
