### ISSUE TITLE
Hazelcast 3.4.2 NPE in UTFEncoderDecoder

### ISSUE THREAD

**Issue by mirkosertic** [hazelcast/hazelcast#6131] opened 2015-09-04 11:56 UTC
There are some very strange exceptions in Hazelcast 3.4.2. We are seeing the following StackTrace in our Logs:

java.lang.NullPointerException: null
	at com.hazelcast.nio.UTFEncoderDecoder.readUTF0(UTFEncoderDecoder.java:516) ~[hazelcast-3.4.2.jar:3.4.2]
	at com.hazelcast.nio.UTFEncoderDecoder.readUTF(UTFEncoderDecoder.java:77) ~[hazelcast-3.4.2.jar:3.4.2]
	at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readUTF(ByteArrayObjectDataInput.java:434) ~[hazelcast-3.4.2.jar:3.4.2]
	at com.hazelcast.nio.IOUtil.extractOperationCallId(IOUtil.java:66) ~[hazelcast-3.4.2.jar:3.4.2]
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.loadOperation(BasicOperationService.java:664) [hazelcast-3.4.2.jar:3.4.2]
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:637) [hazelcast-3.4.2.jar:3.4.2]
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.access$1500(BasicOperationService.java:630) [hazelcast-3.4.2.jar:3.4.2]
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:582) [hazelcast-3.4.2.jar:3.4.2]
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466) [hazelcast-3.4.2.jar:3.4.2]
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458) [hazelcast-3.4.2.jar:3.4.2]
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432) [hazelcast-3.4.2.jar:3.4.2]

Any ideas what is causing this issue?

**Comment by serkan-ozal** [comment] 2015-09-04 12:01
Caused by this line `return stringCreator.buildString(data);`. Is there any security manager in the system that prevents reflection?

Also can you test it with `3.5.2` also?

**Comment by serkan-ozal** [comment] 2015-09-04 12:06
Can you also provide us your Java version?

**Comment by mirkosertic** [comment] 2015-09-04 12:24
There is no security manager involved. 
We are running Oracle JVM 1.8.0_31 64Bit on RHEL.

Currently i am checking if this is related to the tomcat shutdown or startup process...

Are there good reasons to upgrade to 3.5 ? There seems to be a lot of bug fixes according to the release notes.

**Comment by serkan-ozal** [comment] 2015-09-04 12:46
Thanks for the information.

As I understood, the issue doesn't happen always, right?

Is there any error log like `No fast string creator seems to available, falling back to reflection`?

Can you also try with `-Dhazelcast.nio.faststring=false` since default value of this property is true?

Regards.

**Comment by mirkosertic** [comment] 2015-09-04 12:55
Yes, it does not always happen.
There are no fast string creator error log entries.
I will upgrade to 3.5.2 and continue testing...

**Comment by serkan-ozal** [comment] 2015-09-05 06:25
Any update with the issue?

- Sometimes (now always) null `stringCreator` in `return stringCreator.buildString(data);` seems very strange to me since this field is final. Are you sure that `at com.hazelcast.nio.UTFEncoderDecoder.readUTF0(UTFEncoderDecoder.java:516) ~[hazelcast-3.4.2.jar:3.4.2]` is the top of the stack trace?
- Do you have more logs? Can you share them?

**Comment by mirkosertic** [comment] 2015-09-08 07:22
Well, we are now running on 3.5.2 and cannot reproduce this issue anymore,,,

**Comment by serkan-ozal** [comment] 2015-09-08 16:34
Thanks for the response. As said before, I think, it is caused by an issue while trying to create `FastStringCreator` and in this case, `stringCreator` becomes `null`. But not sure what is the exact path in your case. So closing this one as fixed in `3.5.2` and also this fix is exist at master branch.

**Closed by serkan-ozal** 2015-09-08 16:34 UTC
Labels: PENDING, Team: Core
