### ISSUE TITLE
fail fast if given class names in the config does not exist

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#7166] opened 2015-12-24 11:27 UTC
you can see a discussion about the problem: https://github.com/hazelcast/hazelcast/pull/7107/files#diff-3dffd84a99122128d983e9c2491c4668R487

**Comment by burakcelebi** [comment] 2018-01-31 10:15
Duplicate of https://github.com/hazelcast/hazelcast/issues/6323

**Closed by burakcelebi** 2018-01-31 10:15 UTC
Labels: Source: Internal, Team: Core, Type: Enhancement
