### ISSUE TITLE
Querying in Maps

### ISSUE THREAD

**Issue by kovalcikm** [hazelcast/hazelcast#12801] opened 2018-04-06 14:34 UTC
Hello.
Is there any reason why HZ doesn't support querying in maps similar to querying in nested collection based on index? (http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Query/Querying_in_Collections_and_Arrays/index.html)

For collection there is possibility to access by index: Predicates.equal("wheels[0].name", "front-wheel");
I would expect similar approach for nested maps. Something like: Predicates.equal("wheels[{myKey}].name", "front-wheel");
 
This would allow to address map entry for multiple predicates. As far as I know HZ doesn't support multiple conditions for nested collection element.
There is question about that but it is not answered:
https://groups.google.com/forum/#!topic/hazelcast/iEqfKxR87zs

Thank you for your response.

**Comment by halabap** [comment] 2018-04-06 14:49
Hello,

Good idea. We need it too. There seems to be no reason why it should not be possible.

Pavel

**Comment by mmedenjak** [comment] 2018-04-09 13:15
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/8231

**Closed by mmedenjak** 2018-04-09 13:15 UTC
Labels: Estimation: M, Interface: IMap, Priority: Medium, Team: Core, Type: Enhancement
