### ISSUE TITLE
MapDestroyTest.destroyAllReplicasIncludingBackups

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7132] opened 2015-12-21 09:45 UTC
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.MapDestroyTest.assertAllPartitionContainersAreEmpty(MapDestroyTest.java:86)
	at com.hazelcast.map.MapDestroyTest.access$000(MapDestroyTest.java:45)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/782/testReport/junit/com.hazelcast.map/MapDestroyTest/destroyAllReplicasIncludingBackups/

**Comment by mesutcelik** [comment] 2015-12-24 10:10
that does not seem failed in Oracle JDK builds.

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/764/testReport/com.hazelcast.map/MapDestroyTest/destroyAllReplicasIncludingBackups/history/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/4251/testReport/junit/com.hazelcast.map/MapDestroyTest/destroyAllReplicasIncludingBackups/history/

**Comment by enesakar** [comment] 2015-12-24 10:37
can not reproduce. might be related to ibm jdk 6. closing.

**Comment by enesakar** [comment] 2015-12-25 12:25
re-opening. it is reported that failure can be reproduced via:
``` java
@Test
public void destroyAllReplicasIncludingBackups() {
    for(int t=0; t<400; t++) {
        IMap<Integer, Integer> map = instance1.getMap(randomMapName());
        for (int i = 0; i < 1000; i++) {
            map.put(i, i);
        }

        map.destroy();

        assertAllPartitionContainersAreEmptyEventually(instance1);
        assertAllPartitionContainersAreEmptyEventually(instance2);
        assertAllPartitionContainersAreEmptyEventually(instance3);
        assertAllPartitionContainersAreEmptyEventually(instance4);
        assertAllPartitionContainersAreEmptyEventually(instance5);
    }
}
```

**Comment by cangencer** [comment] 2015-12-29 08:36
This is caused by an in-flight MapReplicationOperation running and creating the record store after it's been destroyed.

**Comment by cangencer** [comment] 2015-12-30 08:48
During initial cluster setup, several ReplicaSync requests are sent from partition backup nodes to owner nodes, and these requests are staggered with a random delay, so as a result it means that ReplicaSync requests might be in flight up to 10s after the cluster is started. 

When a map is destroyed, an operation is sent to al the nodes, so it could happen that the backup partition is destroyed before the owner. If between the time a backup and owner partition are destroyed, a previously scheduled sync request is sent from backup to owner, as the map is not yet destroyed on the owner, it will be recreated on the backup, resulting in the test failure.

backup -> destroy map
backup -> SyncRequest to owner
owner -> SyncResponse to node 1
owner -> destroy map

As a result, backup is left with some unrecovrable data from the original map.

**Closed** 2015-12-30 13:37 UTC
Labels: Team: Core, Type: Test-Failure
