### ISSUE TITLE
[TEST-FAILURE] CompletableFutureTest.get_taskThrowsException

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#6291] opened 2015-09-25 08:47 UTC
**Regression**
`com.hazelcast.executor.CompletableFutureTest.get_taskThrowsException`

Failing for the past 1 build (Since Unstable#3775 )
Took 0.75 sec.

**Error Message**
```
Expected: an instance of java.util.concurrent.ExecutionException
     but: <java.lang.NullPointerException> is a java.lang.NullPointerException
Stacktrace was: java.lang.NullPointerException
 at java.lang.management.ThreadInfo.<init>(ThreadInfo.java:168)
 at sun.management.ThreadImpl.dumpThreads0(Native Method)
 at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
 at com.hazelcast.test.AbstractHazelcastClassRunner.generateThreadDump(AbstractHazelcastClassRunner.java:228)
 at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:139)
 at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
 at org.junit.rules.RunRules.evaluate(RunRules.java:20)
 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
 at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:47)
 at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:144)
 at java.lang.Thread.run(Thread.java:745)
```

**Stacktrace**
```
java.lang.AssertionError: 
Expected: an instance of java.util.concurrent.ExecutionException
     but: <java.lang.NullPointerException> is a java.lang.NullPointerException
Stacktrace was: java.lang.NullPointerException
	at java.lang.management.ThreadInfo.<init>(ThreadInfo.java:168)
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
	at com.hazelcast.test.AbstractHazelcastClassRunner.generateThreadDump(AbstractHazelcastClassRunner.java:228)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:139)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:47)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:144)
	at java.lang.Thread.run(Thread.java:745)

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.junit.rules.ExpectedException.handleException(ExpectedException.java:252)
	at org.junit.rules.ExpectedException.access$000(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:241)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:47)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:144)
	at java.lang.Thread.run(Thread.java:745)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3775/testReport/junit/com.hazelcast.executor/CompletableFutureTest/get_taskThrowsException/

**Comment by serkan-ozal** [comment] 2015-09-28 16:33
Not sure but this may be a JDK issue. Seems that NPE is caused by a `null` monitor locked by thread. While `ThreadMXBean::dumpAllThreads` is working (getting informations from all live threads), if the monitor is released at that time (or thread terminated), maybe JVM doesn't handle this case.

**Comment by serkan-ozal** [comment] 2015-10-06 14:34
I think, we can close this one since it seems that JDK issue while getting `ThreadInfo`. I have wrapped `AbstractHazelcastClassRunner:: generateThreadDump` call with `try/catch` so an exception occurred here should not cause failure of the test itself. Any objection?

**Closed** 2015-10-06 18:34 UTC
Labels: Team: Core, Type: Defect
