### ISSUE TITLE
Spring and hazel 3.5.1 error

### ISSUE THREAD

**Issue by LeonardoGomesRibeiro** [hazelcast/hazelcast#7824] opened 2016-03-23 18:02 UTC
Hi!
I'm trying to integrate hazelcast 3.5.1 with Spring 4.1.4.RELEASE and when I try to deploy the application I got this error: 

`org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 2 in XML document from file [C:\Users\leonardo.ribeiro\workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\hyatt-services\WEB-INF\classes\applicationContext.xml] is invalid; nested exception is org.xml.sax.SAXParseException; systemId: http://hazelcast.com/schema/spring/hazelcast-spring-3.5.xsd; lineNumber: 2; columnNumber: 35; s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.`

I'm referencing this ´http://hazelcast.com/schema/spring/hazelcast-spring-3.5.xsd´ on my applicationContext.xml file.

Does anyone know about this issue?

**Comment by jerrinot** [comment] 2016-03-23 18:15
@LeonardoGomesRibeiro: can you try to change the schema URL to use `https` instead of `http`?

**Comment by LeonardoGomesRibeiro** [comment] 2016-03-23 18:23
hi @jerrinot  here is the head of my applicationContext.xml
`<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:sec="http://www.springframework.org/schema/security"
       xmlns:ehcache="http://ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring"
       xmlns:cache="http://www.springframework.org/schema/cache"
       xmlns:hz="https://www.hazelcast.com/schema/spring"
       xsi:schemaLocation="https://www.hazelcast.com/schema/spring
                           https://www.hazelcast.com/schema/spring/hazelcast-spring-3.5.xsd
					       http://www.springframework.org/schema/aop
					       http://www.springframework.org/schema/aop/spring-aop-3.0.xsd
					       http://www.springframework.org/schema/beans
					       http://www.springframework.org/schema/beans/spring-beans-4.0.xsd
					       http://www.springframework.org/schema/context
					       http://www.springframework.org/schema/context/spring-context-4.0.xsd
					       http://www.springframework.org/schema/security
					       http://www.springframework.org/schema/security/spring-security-4.0.xsd
					       http://www.springframework.org/schema/tx
					       http://www.springframework.org/schema/tx/spring-tx-3.0.xsd
					       http://ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring
					       http://ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring/ehcache-spring-1.1.xsd">`

**Comment by jerrinot** [comment] 2016-03-23 18:29
try to change it to:

```xml
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:aop="http://www.springframework.org/schema/aop" xmlns:context="http://www.springframework.org/schema/context" xmlns:tx="http://www.springframework.org/schema/tx" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sec="http://www.springframework.org/schema/security" xmlns:ehcache="http://ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring" xmlns:cache="http://www.springframework.org/schema/cache" xmlns:hz="http://www.hazelcast.com/schema/spring" xsi:schemaLocation="http://www.hazelcast.com/schema/spring https://www.hazelcast.com/schema/spring/hazelcast-spring-3.5.xsd http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.0.xsd http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.0.xsd http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.0.xsd http://www.springframework.org/schema/security http://www.springframework.org/schema/security/spring-security-4.0.xsd http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-3.0.xsd http://ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring http://ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring/ehcache-spring-1.1.xsd">
```

**Comment by LeonardoGomesRibeiro** [comment] 2016-03-23 18:34
@jerrinot after doing this change another issue show up: 
`org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://www.hazelcast.com/schema/spring]

Do you have any idea of this?

Thanks!

**Comment by Donnerbart** [comment] 2016-03-23 18:36
I think there is a last URL missing:
```
xmlns:hz="http://www.hazelcast.com/schema/spring"
```
should probably be
```
xmlns:hz="https://hazelcast.com/schema/spring" 
```

**Comment by mesutcelik** [comment] 2016-03-23 18:44
Can you please try with hazelcast-all 3.5.1 jar file? You might be missing required dependency.

**Comment by LeonardoGomesRibeiro** [comment] 2016-03-23 18:46
Ok @mesutcelik I will try to put this dependency and I will test just now.

**Comment by LeonardoGomesRibeiro** [comment] 2016-03-23 18:56
@mesutcelik I've added the hazelcast-all to the pom.xml of my project.
@Donnerbart I've changed to https

Right now this is the error I get: 
`Expecting namespace 'https://hazelcast.com/schema/spring', but the target namespace of the schema document is 'http://www.hazelcast.com/schema/spring'.`

**Comment by mesutcelik** [comment] 2016-03-23 19:08
you can compare your configuration with this one.
https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/spring-configuration

**Comment by LeonardoGomesRibeiro** [comment] 2016-03-24 16:31
Hey guys, I just found the problem! In my applicationContext.xml there was a wrong version of xsd file. To find that I needed to check every dependency of my project that was referenced on the xml file and compare with the dependency version on my pom.xml :) Right now the project is starting and it seems to be working like a charm! Many thanks for all!

**Comment by mesutcelik** [comment] 2016-03-25 07:33
That is good to hear!!!

Can you please share with us your applicationContext.xml `schemaLocation` definition?

**Comment by mesutcelik** [comment] 2016-03-31 07:39
Hi @LeonardoGomesRibeiro ,

Can you please answer this?

> Can you please share with us your applicationContext.xml schemaLocation definition?

**Comment by LeonardoGomesRibeiro** [comment] 2016-04-01 11:06
Sure @mesutcelik 

`xsi:schemaLocation="http://www.hazelcast.com/schema/spring http://www.hazelcast.com/schema/spring/hazelcast-spring-3.5.xsd http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-4.1.xsd http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.0.xsd http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.0.xsd http://www.springframework.org/schema/security http://www.springframework.org/schema/security/spring-security-4.0.xsd http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-3.0.xsd http://ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring http://ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring/ehcache-spring-1.1.xsd"
`

**Comment by mesutcelik** [comment] 2016-04-01 12:47
ok so there is no SSL related problem as mentioned in previous comments.. cc: @jerrinot @Donnerbart 

closing the ticket. Thank you!

**Closed by mesutcelik** 2016-04-01 12:47 UTC
Labels: Team: Documentation, Team: Integration

**Comment by messaoudi-mounir** [comment] 2016-05-24 09:06
solved form me by adding **hazelcast-al**l with version 3.x in the maven dependencies rather than **hazelcast**. (i am using v 3.6)

<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-all</artifactId>
    <version>3.x</version>
</dependency>

**Comment by varunmaurya** [comment] 2017-04-25 20:34
getting error while trying to setup hazelcast in SpringContext 

org.xml.sax.SAXParseException; lineNumber: 139; columnNumber: 25; schema_reference.4: Failed to read schema document 'https://hazelcast.com/schema/spring/hazelcast-spring.3.8.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

Can some one help !

**Comment by emrahkocaman** [comment] 2017-04-25 21:44
@varunmaurya This is a closed and almost one year old issue. Can you please create a new issue stating your Hazelcast version, full stack trace, a sample spring context xml file that reproduces the problem?

**Comment by Donnerbart** [comment] 2017-04-26 10:30
I guess it's just a typo (`.` vs. `-`):
`https://hazelcast.com/schema/spring/hazelcast-spring.3.8.xsd`
vs.
`https://hazelcast.com/schema/spring/hazelcast-spring-3.8.xsd`

Please fix the URL, then it should work.
