### ISSUE TITLE
member jvm freeze / unfreeze  client get ops sometimes return null unexpectedly 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16732] opened 2020-03-09 11:53 UTC
in the member jvm freeze and unfreeze test, some times we see clients get a Null value back from a get operation just after a Member jvm is unfrozen, however after we wait until the cluster is the correct size and the cluster is safe, when we check the map size it is also correct. 
so we are only seeing a temporary "data loss"  just after a member jvm is unfrozen.

freeze is     kill -STOP ${pid}
so the jvm is taken off the processor and then later allowed to continue to run.

http://jenkins.hazelcast.com/view/freeze/job/freeze-data-loss/23/console

/disk1/jenkins/workspace/freeze-data-loss/4.1-SNAPSHOT/2020_03_09-11_01_58/x Failed

http://54.147.27.51/~jenkins/workspace/freeze-data-loss/4.1-SNAPSHOT/2020_03_09-11_01_58/x

```
fail HzClient1HZ get hzcmd.map.GetNotNull threadId=4 global.AssertionException: DATA LOSS! for map mapBak1Bin key 539400 
```

```
size hzcmd.map.validate.Size [driver=Client, threads=1, duration=0, bench=No, interval=0, size=1000000, name=mapBak1Bin]
size Done
```

**Comment by Danny-Hazelcast** [comment] 2020-03-09 11:55
member freeze unfreeze test we some times see
temporary "data loss" when client get operation return null values.  but when we check the size of the map it is correct.

**Comment by ahmetmircik** [comment] 2020-03-16 07:38
We can think of this freeze and unfreeze test as a split brain test. When split brain occurs on freeze, a client can see any half of the cluster. 

If there is no data in the half of the cluster that client see, seeing null is legitimate in current design.

I could able to reproduce this issue, and in my tests i saw client thinks other 3 members were left the cluster and it could only connect other remaining node:
```
Members [1] {
	Member [10.0.0.94]:5701 - 0ccb414c-0433-4baa-8c0a-4f540bbf96d6
}

global.AssertionException: DATA LOSS!
```

Given that map backup count is 1 in the test, losing 3 nodes bring the possibility of seeing null. If i rerun the test after increasing backup count to 3, nulls disappear.

We can close this issue since seeing null is expected under these circumstances.

For further info on client behavior during split brain this document is helpful: https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1766850758/Ownerless+Client+Design

**Comment by Danny-Hazelcast** [comment] 2020-03-16 08:03
``` ' We can think of this freeze and unfreeze test as a split brain test. When split brain occurs on freeze, a client can see any half of the cluster. '```

the freeze test is not a split brain test,   the cluster should not split. and in the test we can see cluster size going from 4 down to 3 and back up to 4 and repeating.


 for i in {1..5}; do
        m=$(hz randMember)
        hz freeze ${m} >> out.txt
        hz run ${HZ_CMD_BENCH_SRC}/lab/hz/functions/untilClusterSize3 >> out.txt
        hz run ${HZ_CMD_BENCH_SRC}/lab/hz/functions/untilClusterSafe >> out.txt
        hz unfreeze ${m} >> out.txt
        hz run ${HZ_CMD_BENCH_SRC}/lab/hz/functions/untilClusterSize4 >> out.txt
        hz run ${HZ_CMD_BENCH_SRC}/lab/hz/functions/untilClusterSafe >> out.txt
 done


data loss is not expected and i have passing runs of this test 
http://jenkins.hazelcast.com/view/freeze/job/freeze-data-loss/

**Comment by Danny-Hazelcast** [comment] 2020-03-16 09:48
Old behavior: When split-brain occurs, the client follows the owner connection. Client will remain connected to whatever the owner connection sees in the cluster. 
Old behavior server check: The cluster has a check to see if the owner of the client is still a member.  This check for necessary to handle lock operations(or similar), because if a client gets a lock where its owner is not part of, it could lead to a lock forever held.
New behavior: The behavior actually follows from item number 5. There is no specific logic to split-brain. After split-brain occurs, the client will follow the first applicable (see item 5 for details) the member list.
New behavior server check: In the new design there is no server-side check. Client will eventually close the connections to other half of the split. The check is not necessary for locks anymore because locks are not cleared with owner logic. It has a different mechanism see >Member-Side
https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1766850758/Ownerless+Client+Design (edited) 





11:47
as i understand from here, it can pass with 3.12 since it also does an extra check if the owner of the client is still a member (edited)

**Comment by ahmetmircik** [comment] 2020-03-16 09:56
>11:47
as i understand from here, it can pass with 3.12 since it also does an extra check if the owner of the client is still a member (edited)

Editing myself, 3.12's check is irrelevant from the case here (talked with @sancar)

**Comment by Danny-Hazelcast** [comment] 2020-04-02 07:27
related ?

https://github.com/hazelcast/hazelcast/issues/16836

https://github.com/hazelcast/hazelcast/pull/16603

**Comment by Danny-Hazelcast** [comment] 2020-04-03 06:14
3 passing runs to 1 failing run 

Latest Fail

Hazelcast Enterprise 4.0.1-SNAPSHOT (20200402 - 100900d, e3aea38)

http://jenkins.hazelcast.com/view/freeze/job/freeze-data-loss/33/console

fail HzClient2HZ get hzcmd.map.GetNotNull threadId=3 global.AssertionException: DATA LOSS! for map mapBak1Bin key 88838 

/disk1/jenkins/workspace/freeze-data-loss/4.0.1-SNAPSHOT/2020_04_02-14_40_36/x

 http://54.147.27.51/~jenkins/workspace/freeze-data-loss/4.0.1-SNAPSHOT/2020_04_02-14_40_36/x

**Comment by ahmetmircik** [comment] 2020-04-03 15:40
Here is my understanding of what happened...

As i see from the logs, the issue here is a split brain issue. 

If one client gets member list from just unfrozen node, just before it joins back to other nodes' cluster, in this specific time interval, the client thinks there is only this unfrozen member in the cluster and disconnects from others.(unfrozen member's member-list-version is greater than the known by client) 

As in this test failure, this issue manifests itself to user as a data lost issue along the time interval till the join end. After join, there is no data lost. (Having sufficient backup count also makes this test pass)

It seems it is working as designed.

**Comment by mmedenjak** [comment] 2020-04-06 09:51
Thank you for the explanation. @sancar can you confirm and can we close this issue?

**Comment by ahmetmircik** [comment] 2020-04-06 10:16
We have talked with Sancar and have decided on creating a new issue to pursue possible improvements here like selecting the brain that has more members.

**Comment by sancar** [comment] 2020-04-06 12:03
I have checked the logs and indeed this seems like a split brain situation. And the client behaves as expected.

The cluster is split 3 to 1. 
A member from 3 member side of the split brain:
```
Members {size:3, ver:14} [
	Member [10.0.0.209]:4701 - d6e3ffb0-1387-4517-8b86-24e06b3b892f this
	Member [10.0.0.28]:4701 - 5cc31838-c82b-45fd-b26f-1dafe8738e22
	Member [10.0.0.141]:4701 - 15b39e5a-5baf-40fb-93db-5c77380e1b75
]

INFO: [10.0.0.209]:4701 [HZ] [4.0.1-SNAPSHOT] [10.0.0.67]:4701 should merge to us because our data member count is bigger than theirs [3 > 1]
Apr 02, 2020 2:55:38 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [10.0.0.209]:4701 [HZ] [4.0.1-SNAPSHOT] [10.0.0.67]:4701 should merge to us because our data member count is bigger than theirs [3 > 1]
Apr 02, 2020 2:55:38 PM com.hazelcast.internal.cluster.impl.MembershipManager
INFO: [10.0.0.209]:4701 [HZ] [4.0.1-SNAPSHOT] Updating local member list version: 14 to 17 because of split brain merge caller: [10.0.0.67]:4701 with member list version: 16
Apr 02, 2020 2:55:38 PM com.hazelcast.internal.cluster.ClusterService
INFO: [10.0.0.209]:4701 [HZ] [4.0.1-SNAPSHOT] 

```

Other half of the split brain
```
Apr 02, 2020 2:54:33 PM com.hazelcast.internal.cluster.ClusterService
INFO: [10.0.0.67]:4701 [HZ] [4.0.1-SNAPSHOT] 

Members {size:1, ver:16} [
	Member [10.0.0.67]:4701 - b8e9418d-b171-4315-b508-196dcf34c87d this
]

Apr 02, 2020 2:55:13 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [10.0.0.67]:4701 [HZ] [4.0.1-SNAPSHOT] We should merge to [10.0.0.209]:4701 because their data member count is bigger than ours [3 > 1]
Apr 02, 2020 2:55:18 PM com.hazelcast.internal.nio.tcp.TcpIpConnection
INFO: [10.0.0.67]:4701 [HZ] [4.0.1-SNAPSHOT] Initialized new cluster connection between /10.0.0.67:42593 and /10.0.0.141:4701
Apr 02, 2020 2:55:38 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [10.0.0.67]:4701 [HZ] [4.0.1-SNAPSHOT] We should merge to [10.0.0.209]:4701 because their data member count is bigger than ours [3 > 1]
Apr 02, 2020 2:55:38 PM com.hazelcast.internal.cluster.impl.TcpIpJoiner
WARNING: [10.0.0.67]:4701 [HZ] [4.0.1-SNAPSHOT] [10.0.0.67]:4701 is merging [tcp/ip] to [10.0.0.209]:4701
Apr 02, 2020 2:55:38 PM com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp
INFO: [10.0.0.67]:4701 [HZ] [4.0.1-SNAPSHOT] Locking cluster state. Initiator: [10.0.0.67]:4701, lease-time: 60000
Apr 02, 2020 2:55:38 PM com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp
INFO: [10.0.0.67]:4701 [HZ] [4.0.1-SNAPSHOT] Extending cluster state lock. Initiator: [10.0.0.67]:4701, lease-time: 20000
Apr 02, 2020 2:55:38 PM com.hazelcast.internal.cluster.impl.operations.CommitClusterStateOp
INFO: [10.0.0.67]:4701 [HZ] [4.0.1-SNAPSHOT] Changing cluster state from ClusterState{state=ACTIVE, lock=LockGuard{lockOwner=[10.0.0.67]:4701, lockOwnerId='10196a14-75a4-4808-ad55-d6f30ec5f344', lockExpiryTime=1585839418722}} to ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=FROZEN}, initiator: [10.0.0.67]:4701, transient: false
Apr 02, 2020 2:55:38 PM com.hazelcast.internal.cluster.impl.operations.MergeClustersOp
WARNING: [10.0.0.67]:4701 [HZ] [4.0.1-SNAPSHOT] [10.0.0.67]:4701 is merging to [10.0.0.209]:4701, because: instructed by master [10.0.0.67]:4701
Apr 02, 2020 2:55:38 PM com.hazelcast.core.LifecycleService
INFO: [10.0.0.67]:4701 [HZ] [4.0.1-SNAPSHOT] [10.0.0.67]:4701 is MERGING
```

When the client sees the Data loss, It is during the time that cluster is split. The behaviour actually same as 3.12. The connection is not named owner connection anymore, but client listens the memberlist from a single connection as before. 
 It does not matter which half for this test, we will see data loss in either case. 

```
Apr 02, 2020 2:54:33 PM com.hazelcast.client.impl.spi.ClientClusterService
INFO: hz.client_1 [HZ] [4.0.1-SNAPSHOT] 

Members [1] {
	Member [10.0.0.67]:5701 - b8e9418d-b171-4315-b508-196dcf34c87d
}

global.AssertionException: DATA LOSS! for map mapBak1Bin key 273665
```

I think this behaviour is expected.

**Comment by ahmetmircik** [comment] 2020-04-06 15:07
Closing this issue, since current behavior found here aligns with the design and it is expected. But some enhancement ideas are around and have opened an enhancement issue for them: https://github.com/hazelcast/hazelcast/issues/16854.

**Closed by ahmetmircik** 2020-04-06 15:07 UTC
Labels: Module: Cluster, Module: Partitioning, Source: Internal, Team: Core, Type: Defect
