### ISSUE TITLE
HazelcastSerializationException with hibernate L2 Cache+Spring Boot

### ISSUE THREAD

**Issue by tandonraghav** [hazelcast/hazelcast#13326] opened 2018-06-19 22:54 UTC
I am trying to integrate hazelcast with a Spring boot project(**Embedded Tomcat .WAR**) for hibernate L2 cache.
**Hazelcast - 3.9.4**
**hazelcast-hibernate4**

Setting up Hibernate L2 cache in Cluster Mode and connecting like a Native client.
The setup works fine (both for L2+Query cache) and I can see data in my cluster .

But in few operations i start getting Exceptions as 

Probably ClassLoader used by Hazelcast is different, but how to set a classloader for a Hibernate Native Client. I can set in ClientConfig, but then I am not able to use that instance in hibernate by below property.
>hibernate.cache.hazelcast.instance_name

```
    com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.fsi.shared.api.bean.setting
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:83)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:72)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:273)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574)
	at com.hazelcast.hibernate.serialization.Value.readData(Value.java:78)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:158)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:105)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:191)
	at com.hazelcast.query.impl.CachedQueryEntry.getValue(CachedQueryEntry.java:75)
	at com.hazelcast.hibernate.distributed.LockEntryProcessor.process(LockEntryProcessor.java:49)
	at com.hazelcast.hibernate.distributed.LockEntryProcessor.process(LockEntryProcessor.java:32)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:335)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:194)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:179)
	at com.hazelcast.map.impl.operation.EntryOperation.runVanilla(EntryOperation.java:395)
	at com.hazelcast.map.impl.operation.EntryOperation.run(EntryOperation.java:177)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:569)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:554)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:67)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
Caused by: java.lang.ClassNotFoundException: com.fsi.shared.api.bean.SettingComponent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:173)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:147)
	at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:593)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1859)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1745)
	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1985)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1564)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at java.util.HashMap.readObject(HashMap.java:1409)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:79)
	... 32 more
```

**HibernateConfig.java**

                    properties.put(Environment.CACHE_REGION_FACTORY, HazelcastCacheRegionFactory.class.getName());
			properties.put(Environment.CACHE_PROVIDER_CONFIG, systemSettings.getHibernateCacheServerPropertiesLocation());
			properties.setProperty(Environment.TRANSACTION_STRATEGY, JdbcTransactionFactory.class.getName());
			properties.put("javax.persistence.sharedCache.mode", SharedCacheMode.ENABLE_SELECTIVE);
			properties.put("javax.persistence.cache.retrieveMode", CacheRetrieveMode.USE);

			properties.put("hibernate.cache.hazelcast.use_native_client",true);
			properties.put("hibernate.cache.hazelcast.native_client_address","127.0.0.1:5704");
			properties.put("hibernate.cache.hazelcast.native_client_group","dev");
			properties.put("hibernate.cache.hazelcast.native_client_password","dev-pass");
                    properties.put(Environment.USE_QUERY_CACHE, true);		        
                    properties.put(Environment.USE_SECOND_LEVEL_CACHE,true);

  <hazelcast-client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                               http://www.hazelcast.com/schema/client-config/hazelcast-client-config-3.9.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config">

    <hazelcast-client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                               http://www.hazelcast.com/schema/client-config/hazelcast-client-config-3.9.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config">

    <group>
        <name>dev</name>
        <password>dev-pass</password>
    </group>

    <network>
        <cluster-members>
            <address>127.0.0.1:5701</address>
        </cluster-members>
    </network>
</hazelcast-client>

**Comment by emre-aydin** [comment] 2018-06-20 05:18
Hi @tandonraghav ,

You're on the right track trying to use a custom `ClientConfig` and an existing client instance, but the property you're using is wrong. You need to specify `hibernate.cache.hazelcast.native_client_instance_name` property as your existing client instance name. See the [relevant section on project README ](https://github.com/hazelcast/hazelcast-hibernate#setting-client-server-for-hibernate) for more information.

I'm closing the issue as this should fix your problem. Please feel free to re-open if you still have problem.

**Comment by tandonraghav** [comment] 2018-06-20 10:57
Hi @emre-aydin ,

Thanks for the info, I just missed that. Still I am not able to make it work after hours of debugging.
I am able to use myInstance as Hz Client and setting ClassLoader, but still no Luck.

When I am starting hazelcast-3.9.4 as ` java  -Xmx256m -jar hazelcast-3.9.4.jar` I am getting 
exception on Client side.

      @Bean
	public ClientConfig clientConfig() {
		ClientConfig clientConfig = new ClientConfig();
		clientConfig.setInstanceName("hazelcast-instance");
		clientConfig.setClassLoader(SettingComponent.class.getClassLoader());
		ClientNetworkConfig clientNetworkConfig = clientConfig.getNetworkConfig();
		clientNetworkConfig.addAddress("127.0.0.1:5701");


		GroupConfig groupConfig=clientConfig.getGroupConfig();
		groupConfig.setName("dev");
		groupConfig.setPassword("dev-pass");

		return clientConfig;
	}

	@Bean
	public HazelcastInstance hazelcastInstance(){
		HazelcastInstance hazelcastInstance= HazelcastClient.newHazelcastClient(clientConfig());
		return  hazelcastInstance;
	}


>com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -2000

But the above doesnt happen if Hazelcast is started as Embedded Cluster Member.
I am stuck now and dont know what I am doing wrong.

Even I tried giving my jar in Classpath as
>java -cp api.jar:hazelcast-hibernate4-3.8.jar -Xmx256m -jar hazelcast-3.9.4.jar

**Comment by emre-aydin** [comment] 2018-06-20 11:15
From the README:

> NOTE: To use Native Client, add hazelcast-<version>.jar,hazelcast-hibernate(3,4)-<version>.jar and hibernate-core-<version>.jar into your remote cluster's classpath.

`java -Xmx256m -jar hazelcast-3.9.4.jar` -> so you need to add hazelcast-hibernate and hibernate-core JARs here.

**Closed** 2018-06-20 11:15 UTC
Labels: Team: Integration

**Comment by tandonraghav** [comment] 2018-06-20 11:36
Yes, I also tried with 
>java -cp api.jar:hazelcast-hibernate4-3.8.jar:hibernate-core-4.3.11.Final.jar -Xmx256m -jar lib/hazelcast-3.9.4.jar

Still get this
>com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -2000

Do i still need to configure class Loader? Why this is happening only with spring boot .war , and not with Embedded Jetty server.

Some are also referring to Hazelcast-hibernate4+Hazelcast issue and need to configure **Shade Plugin**

**Comment by emre-aydin** [comment] 2018-06-20 11:55
This looks like a classpath problem, I don't think it has much to do with classloader but you might try configuring it as well. With your current classpath, it should work.

> Why this is happening only with spring boot .war , and not with Embedded Jetty server.

I'm not familiar with your setup, so can't comment on this one. Can you please try to narrow down the issue to a problem with Hazelcast Hibernate module and possibly provide a reproducer? You can use our [Google group](https://groups.google.com/forum/#!forum/hazelcast) or Stackoverflow to get help with the issues you have.

**Comment by tandonraghav** [comment] 2018-06-20 22:29
@emre-aydin , I  found that I am only getting this Exception for **@Transactional** methods.
Now, I am confused as I cannot change JpaTransactionManager to HazelcastTransactionManager.

Not able to find anything concrete. Do I need to replace spring with Hazelcast?

**Comment by emre-aydin** [comment] 2018-06-21 07:32
@tandonraghav no, you don't need to. It should work with JpaTransactionManager as well.
