### ISSUE TITLE
ClientStatisticsTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10730] opened 2017-06-12 09:16 UTC
**testStatisticsPeriod
testStatisticsCollectionNonDefaultPeriod
testStatisticsTwoClients
testStatisticsClusterReconnect**

```
java.lang.NullPointerException: null
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.newStringRendererGauge(MetricsRegistryImpl.java:238)
	at com.hazelcast.client.impl.statistics.Statistics$PeriodicStatistics.<init>(Statistics.java:363)
	at com.hazelcast.client.impl.statistics.Statistics.start(Statistics.java:114)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:436)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:76)
	at com.hazelcast.client.statistics.ClientStatisticsTest.createHazelcastClient(ClientStatisticsTest.java:278)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsPeriod(ClientStatisticsTest.java:136)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1309/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1308/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1307/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/619/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/618/

**Comment by hasancelik** [comment] 2017-06-19 07:46
**testStatisticsClusterReconnect
testStatisticsTwoClients
testStatisticsPeriod
testStatisticsCollectionNonDefaultPeriod**

```
java.lang.NullPointerException: null
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.newStringRendererGauge(MetricsRegistryImpl.java:238)
	at com.hazelcast.client.impl.statistics.Statistics$PeriodicStatistics.<init>(Statistics.java:353)
	at com.hazelcast.client.impl.statistics.Statistics.start(Statistics.java:113)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:439)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:76)
	at com.hazelcast.client.statistics.ClientStatisticsTest.createHazelcastClient(ClientStatisticsTest.java:278)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod(ClientStatisticsTest.java:79)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1316/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1315/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1314/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/627/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/626/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/625/

**Comment by Donnerbart** [comment] 2017-08-14 10:03
We had another NPE failure in this test:
**com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod(ClientStatisticsTest.java:94)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10147/testReport/junit/com.hazelcast.client.statistics/ClientStatisticsTest/testStatisticsCollectionNonDefaultPeriod/

I've made a PR to improve the assert messages and found a little bug in the test as well (not related to this issue though): https://github.com/hazelcast/hazelcast/pull/11088

**Comment by mdogan** [comment] 2017-09-29 16:05
```
java.lang.AssertionError: Time difference between two collections is 4018 ms, but it should be less than 3000.0 ms
	at com.hazelcast.client.statistics.ClientStatisticsTest.verifyThatCollectionIsPeriodic(ClientStatisticsTest.java:360)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod(ClientStatisticsTest.java:136)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10984/testReport/com.hazelcast.client.statistics/ClientStatisticsTest/testStatisticsCollectionNonDefaultPeriod/

**Comment by mdogan** [comment] 2017-09-29 16:06
```
java.lang.AssertionError: Time difference between two collections is 4266 ms, but it should be less than 3000.0 ms
	at com.hazelcast.client.statistics.ClientStatisticsTest.verifyThatCollectionIsPeriodic(ClientStatisticsTest.java:360)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod(ClientStatisticsTest.java:136)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10983/testReport/com.hazelcast.client.statistics/ClientStatisticsTest/testStatisticsCollectionNonDefaultPeriod/

**Comment by mdogan** [comment] 2017-10-02 06:53
```
java.lang.AssertionError: Time difference between two collections is 8927 ms, but it should be less than 3000.0 ms
	at com.hazelcast.client.statistics.ClientStatisticsTest.verifyThatCollectionIsPeriodic(ClientStatisticsTest.java:360)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod(ClientStatisticsTest.java:136)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10986/testReport/junit/com.hazelcast.client.statistics/ClientStatisticsTest/testStatisticsCollectionNonDefaultPeriod/

**Comment by mdogan** [comment] 2017-10-02 08:27
```
java.lang.AssertionError: Time difference between two collections is 3709 ms, but it should be less than 3000.0 ms
	at com.hazelcast.client.statistics.ClientStatisticsTest.verifyThatCollectionIsPeriodic(ClientStatisticsTest.java:360)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod(ClientStatisticsTest.java:136)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10990/testReport/junit/com.hazelcast.client.statistics/ClientStatisticsTest/testStatisticsCollectionNonDefaultPeriod/

**Comment by sancar** [comment] 2017-10-02 10:28
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10999/testReport/junit/com.hazelcast.client.statistics/ClientStatisticsTest/testStatisticsClusterReconnect/

Error Message

CountDownLatch failed to complete within 120 seconds, count left: 1
Stacktrace
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsClusterReconnect(ClientStatisticsTest.java:194)
```

**Comment by sancar** [comment] 2017-10-02 10:33
Tests are marked as `ignore` here, because they were failing frequently
https://github.com/hazelcast/hazelcast/commit/e8a2e6a1e4bf7d3f8dccdd3ef8c9e4fccdf350f0

**Comment by sancar** [comment] 2017-10-02 12:32
One more test is ignored here. 
https://github.com/hazelcast/hazelcast/commit/5f02c2986ac8f7647f1715e2b7e0721d85bf83f6

**Comment by mmedenjak** [comment] 2017-10-02 13:02
This one also failed a couple of times. 
**ClientStatisticsTest.testStatisticsPeriod**
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11011

```
java.lang.AssertionError: clientStatistics.size() should be 1 expected:<1> but was:<0>
	at com.hazelcast.client.statistics.ClientStatisticsTest.getStats(ClientStatisticsTest.java:314)
	at com.hazelcast.client.statistics.ClientStatisticsTest.access$000(ClientStatisticsTest.java:68)
	at com.hazelcast.client.statistics.ClientStatisticsTest.waitForFirstStatisticsCollection(ClientStatisticsTest.java:333)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsPeriod(ClientStatisticsTest.java:162)
```

**Comment by ihsandemir** [comment] 2017-10-02 14:16
[com.hazelcast.client.statistics.ClientStatisticsTest-output.txt](https://github.com/hazelcast/hazelcast/files/1349152/com.hazelcast.client.statistics.ClientStatisticsTest-output.txt)

I analysed the testStatisticsClusterReconnect test log as attached above. We see that the client is disconnected at 
09:35:54,633  INFO |testStatisticsClusterReconnect| - [LifecycleService] hz.client_7.cluster- - hz.client_7 [dev] [3.9-SNAPSHOT] HazelcastClient 3.9-SNAPSHOT (20171002 - 3942221) is CLIENT_DISCONNECTED

Now it tries to connect to the closed member and it fails and writes this log:
09:35:54,635  WARN |testStatisticsClusterReconnect| - [ClientConnectionManager] hz.client_7.cluster- - hz.client_7 [dev] [3.9-SNAPSHOT] Unable to get alive cluster connection, try in 2999 ms later, attempt 1 of 2.

So, the second try will be around at 09:35:57,634. The new member starts but it is not started until 09:35:58,215 and the client attempt fails and hence all attempts are consumed but the new member did not start.

09:35:58,215  WARN |testStatisticsClusterReconnect| - [ClientConnectionManager] hz.client_7.cluster- - hz.client_7 [dev] [3.9-SNAPSHOT] Unable to get alive cluster connection, try in 2970 ms later, attempt 2 of 2.

Hence, the problem is member starting late. The last log above is misleading, the client should not need to sleep anymore since it already consumed all attempts.

**Comment by mmedenjak** [comment] 2017-10-02 14:19
He are having lots of environment issues because of an upgraded surefire library. It will be reverted soon, try again after it is merged: 
https://github.com/hazelcast/hazelcast/pull/11492
https://github.com/hazelcast/hazelcast-enterprise/pull/1748

**Comment by jerrinot** [comment] 2017-10-04 19:32
@sancar: what's the state of this issue? I assume it's not closed by #11493, is it?

**Comment by sancar** [comment] 2017-10-04 20:44
@ihsandemir is working on the issues. https://github.com/hazelcast/hazelcast/pull/11491 removed a couple of ignores but not all. 
https://github.com/hazelcast/hazelcast/pull/11493 is related but does not really fix a test. 
@ihsandemir will continue to fix and remove the ignores.

**Comment by hasancelik** [comment] 2017-12-18 08:09
**testStatisticsClusterReconnect**
```
java.lang.AssertionError: clientStatistics.size() should be 1 expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.statistics.ClientStatisticsTest.getStats(ClientStatisticsTest.java:312)
	at com.hazelcast.client.statistics.ClientStatisticsTest.access$000(ClientStatisticsTest.java:67)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/789/testReport/junit/com.hazelcast.client.statistics/ClientStatisticsTest/testStatisticsClusterReconnect/

**Closed** 2017-12-18 09:11 UTC
Labels: Team: Client, Type: Test-Failure
