### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.kafka.SqlPrimitiveTest

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25230] opened 2023-08-16 11:41 UTC
_master_ (commit  f68300e1bdaff7268439fa63c5dc5f44539e20aa)

Failed on RedPanda 23.1.z: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.1.z/15/

<details><summary>Stacktrace:</summary>

```
21:24:58,717 ERROR || - [SchemaRegistryRestApplication] Time-limited test - Error starting the schema registry
io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryInitializationException: Error initializing kafka store while initializing schema registry
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:352) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:75) [kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:99) [kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.rest.Application.configureHandler(Application.java:296) [rest-utils-7.4.0.jar:?]
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:194) [rest-utils-7.4.0.jar:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createSchemaRegistry(KafkaTestSupport.java:257) [hazelcast-jet-kafka-5.4.0-SNAPSHOT-tests.jar:?]
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.createSchemaRegistry(KafkaSqlTestSupport.java:59) [test-classes/:?]
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.initialize(SqlAvroTest.java:75) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41) [hazelcast-5.4.0-SNAPSHOT-tests.jar:?]
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66) [hazelcast-5.4.0-SNAPSHOT-tests.jar:?]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293) [junit-4.13.2.jar:4.13.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.confluent.kafka.schemaregistry.storage.exceptions.StoreInitializationException: io.confluent.kafka.schemaregistry.storage.exceptions.StoreException: Failed to write Noop record to kafka store.
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.init(KafkaStore.java:148) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:350) ~[kafka-schema-registry-7.4.0.jar:?]
	... 24 more
Caused by: io.confluent.kafka.schemaregistry.storage.exceptions.StoreException: Failed to write Noop record to kafka store.
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.getLatestOffset(KafkaStore.java:490) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.waitUntilKafkaReaderReachesLastOffset(KafkaStore.java:293) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.init(KafkaStore.java:146) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:350) ~[kafka-schema-registry-7.4.0.jar:?]
	... 24 more
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.NotLeaderOrFollowerException: For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.valueOrError(FutureRecordMetadata.java:97) ~[kafka-clients-3.4.1.jar:?]
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:79) ~[kafka-clients-3.4.1.jar:?]
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:30) ~[kafka-clients-3.4.1.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.getLatestOffset(KafkaStore.java:485) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.waitUntilKafkaReaderReachesLastOffset(KafkaStore.java:293) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.init(KafkaStore.java:146) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:350) ~[kafka-schema-registry-7.4.0.jar:?]
	... 24 more
Caused by: org.apache.kafka.common.errors.NotLeaderOrFollowerException: For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.
```

</details>

Stdout can be found here:  https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Redpanda-23.1.z/15/

**Comment by sumnerib** [comment] 2023-08-23 11:28
Crashed on master with RedPanda: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.1.z/16/

**Comment by k-jamroz** [comment] 2023-09-18 16:39
Duplicate of #25406?

**Comment by olukas** [comment] 2024-08-02 10:40
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.

**Closed by olukas** 2024-08-02 10:40 UTC
Labels: Type: Test-Failure, Source: Internal, Team: Integration, Module: SQL
