### ISSUE TITLE
Hazelcast in permanent frozen state

### ISSUE THREAD

**Issue by nickhristov** [hazelcast/hazelcast#9972] opened 2017-02-23 22:24 UTC
I wrote a comment in another issue a several days ago, but I think this is a separate problem, so logging this as a separate issue for now.

I was running a two node hazelcast cluster when the cluster fractured and could not recover after I launched new nodes. Here is the error which I kept seeing:

```
Cluster state either is locked or doesn't allow new members to join -> ClusterState{state=FROZEN, lock=ClusterStateLock{lockOwner=null, transactionId='null', lockExpiryTime=0}}
```

Here are the relevant logs:

```
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.957  ERROR [hz._hzInstance_1_Union.generic-operation.thread-0] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Reason of failure for node join : Cluster state either is locked or doesn't allow new members to join -> ClusterState{state=FROZEN, lock=ClusterStateLock{lockOwner=null, transactionId='null', lockExpiryTime=0}}
ip-10-0-30-217	INFO	2017-02-02 04:57:49.957  INFO [hz._hzInstance_1_Union.generic-operation.thread-0] com.hazelcast.instance.Node - [10.0.30.217]:5702 [Union] [3.6.3] Node is already shutting down... Waiting for shutdown process to complete...
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.957  ERROR [hz._hzInstance_1_Union.generic-operation.thread-0] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Reason of failure for node join : Cluster state either is locked or doesn't allow new members to join -> ClusterState{state=FROZEN, lock=ClusterStateLock{lockOwner=null, transactionId='null', lockExpiryTime=0}}
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.956  ERROR [hz._hzInstance_1_Union.generic-operation.thread-0] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Node could not join cluster. Before join check failed node is going to shutdown now!
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.956  ERROR [hz._hzInstance_1_Union.generic-operation.thread-0] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Node could not join cluster. Before join check failed node is going to shutdown now!
ip-10-0-20-229	INFO	2017-02-02 04:57:49.955  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] Removing Member [10.0.30.217]:5702
ip-10-0-20-229	INFO	2017-02-02 04:57:49.955  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.ClusterService - [10.0.20.229]:5701 [Union] [3.6.3] Removing Member [10.0.30.217]:5702
ip-10-0-20-229	INFO	2017-02-02 04:57:49.955  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] Removing Member [10.0.30.217]:5702
ip-10-0-20-229	INFO	2017-02-02 04:57:49.955  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.ClusterService - [10.0.20.229]:5701 [Union] [3.6.3] Removing Member [10.0.30.217]:5702

ip-10-0-30-217	INFO	2017-02-02 04:57:49.954  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.instance.Node - [10.0.30.217]:5702 [Union] [3.6.3] Shutting down connection manager...
ip-10-0-30-217	WARN	2017-02-02 04:57:49.954  WARN [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.instance.Node - [10.0.30.217]:5702 [Union] [3.6.3] Terminating forcefully...
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.954  ERROR [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Reason of failure for node join : Cluster state either is locked or doesn't allow new members to join -> ClusterState{state=FROZEN, lock=ClusterStateLock{lockOwner=null, transactionId='null', lockExpiryTime=0}}
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.954  ERROR [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Node could not join cluster. Before join check failed node is going to shutdown now!
ip-10-0-20-229	WARN	2017-02-02 04:57:49.954  WARN [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.impl.ClusterJoinManager - [10.0.20.229]:5701 [Union] [3.6.3] New join request has been received from an existing endpoint Member [10.0.30.217]:5702. Removing old member and processing join request...


ip-10-0-30-217	INFO	2017-02-02 04:57:49.953  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.impl.ClusterJoinManager - [10.0.30.217]:5702 [Union] [3.6.3] Ignoring master response Address[10.0.20.229]:5701 from Address[10.0.20.229]:5701 since this node has an active master Address[10.0.30.217]:5701
ip-10-0-30-217	INFO	2017-02-02 04:57:48.954  INFO [cached1] com.hazelcast.cluster.impl.TcpIpJoiner - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.20.229]:5702 is added to the blacklist.
ip-10-0-30-217	INFO	2017-02-02 04:57:48.951  INFO [cached1] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Could not connect to: /10.0.20.229:5702. Reason: SocketException[Connection refused to address /10.0.20.229:5702]
ip-10-0-30-217	INFO	2017-02-02 04:57:48.947  INFO [cached3] com.hazelcast.cluster.impl.TcpIpJoiner - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.30.217]:5703 is added to the blacklist.
ip-10-0-30-217	INFO	2017-02-02 04:57:48.946  INFO [cached2] com.hazelcast.cluster.impl.TcpIpJoiner - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.20.229]:5703 is added to the blacklist.
ip-10-0-30-217	INFO	2017-02-02 04:57:48.946  INFO [cached2] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Could not connect to: /10.0.20.229:5703. Reason: SocketException[Connection refused to address /10.0.20.229:5703]
ip-10-0-30-217	INFO	2017-02-02 04:57:48.946  INFO [cached3] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Could not connect to: /10.0.30.217:5703. Reason: SocketException[Connection refused to address /10.0.30.217:5703]
ip-10-0-30-217	INFO	2017-02-02 04:57:48.945  INFO [cached3] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Connecting to /10.0.30.217:5703, timeout: 0, bind-any: true
ip-10-0-20-229	INFO	2017-02-02 04:57:48.943  INFO [cached2] com.hazelcast.nio.tcp.TcpIpConnectionManager - [10.0.20.229]:5701 [Union] [3.6.3] Established socket connection between /10.0.20.229:5701 and /10.0.30.217:55154
ip-10-0-30-217	INFO	2017-02-02 04:57:48.943  INFO [cached3] com.hazelcast.nio.tcp.TcpIpConnectionManager - [10.0.30.217]:5702 [Union] [3.6.3] Established socket connection between /10.0.30.217:49505 and /10.0.30.217:5701
ip-10-0-30-217	INFO	2017-02-02 04:57:48.942  INFO [cached1] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Connecting to /10.0.20.229:5702, timeout: 0, bind-any: true
ip-10-0-20-229	INFO	2017-02-02 04:57:48.942  INFO [hz._hzInstance_1_Union.IO.thread-Acceptor] com.hazelcast.nio.tcp.SocketAcceptorThread - [10.0.20.229]:5701 [Union] [3.6.3] Accepting socket connection from /10.0.30.217:55154
ip-10-0-30-217	INFO	2017-02-02 04:57:48.940  INFO [cached1] com.hazelcast.nio.tcp.TcpIpConnectionManager - [10.0.30.217]:5702 [Union] [3.6.3] Established socket connection between /10.0.30.217:55154 and /10.0.20.229:5701
ip-10-0-30-217	INFO	2017-02-02 04:57:48.935  INFO [cached3] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Connecting to /10.0.30.217:5701, timeout: 0, bind-any: true
ip-10-0-30-217	INFO	2017-02-02 04:57:48.934  INFO [cached2] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Connecting to /10.0.20.229:5703, timeout: 0, bind-any: true
ip-10-0-30-217	INFO	2017-02-02 04:57:48.934  INFO [cached1] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Connecting to /10.0.20.229:5701, timeout: 0, bind-any: true
ip-10-0-30-217	INFO	2017-02-02 04:57:48.901  INFO [vert.x-worker-thread-0] com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThreadingModel - [10.0.30.217]:5702 [Union] [3.6.3] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads
ip-10-0-30-217	INFO	2017-02-02 04:57:48.767  INFO [vert.x-worker-thread-0] com.hazelcast.core.LifecycleService - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.30.217]:5702 is STARTING
ip-10-0-30-217	INFO	2017-02-02 04:57:48.766  INFO [vert.x-worker-thread-0] com.hazelcast.instance.Node - [10.0.30.217]:5702 [Union] [3.6.3] Creating TcpIpJoiner
ip-10-0-30-217	INFO	2017-02-02 04:57:48.250  INFO [vert.x-worker-thread-0] com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor - [10.0.30.217]:5702 [Union] [3.6.3] Starting with 2 generic operation threads and 2 partition operation threads.
ip-10-0-30-217	INFO	2017-02-02 04:57:48.207  INFO [vert.x-worker-thread-0] com.hazelcast.spi.OperationService - [10.0.30.217]:5702 [Union] [3.6.3] Backpressure is disabled
ip-10-0-30-217	INFO	2017-02-02 04:57:47.979  INFO [vert.x-worker-thread-0] com.hazelcast.system - [10.0.30.217]:5702 [Union] [3.6.3] Hazelcast 3.6.3 (20160527 - 08b28c3) starting at Address[10.0.30.217]:5702
ip-10-0-30-217	INFO	2017-02-02 04:57:47.979  INFO [vert.x-worker-thread-0] com.hazelcast.system - [10.0.30.217]:5702 [Union] [3.6.3] Configured Hazelcast Serialization version : 1
ip-10-0-30-217	INFO	2017-02-02 04:57:47.979  INFO [vert.x-worker-thread-0] com.hazelcast.system - [10.0.30.217]:5702 [Union] [3.6.3] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
ip-10-0-30-217	INFO	2017-02-02 04:57:47.969  INFO [vert.x-worker-thread-0] com.hazelcast.instance.DefaultAddressPicker - [LOCAL] [Union] [3.6.3] Picked Address[10.0.30.217]:5702, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5702], bind any local is true
ip-10-0-30-217	INFO	2017-02-02 04:57:47.965  INFO [vert.x-worker-thread-0] com.hazelcast.instance.DefaultAddressPicker - [LOCAL] [Union] [3.6.3] Prefer IPv4 stack is true.
ip-10-0-30-217	INFO	2017-02-02 04:57:47.963  INFO [vert.x-worker-thread-0] com.hazelcast.instance.DefaultAddressPicker - [LOCAL] [Union] [3.6.3] Interfaces is enabled, trying to pick one address matching to one of: [10.0.30.217]
ip-10-0-30-217	INFO	2017-02-02 04:57:47.779  INFO [main] com.turvo.presence.PresenceMain - Adding participating host to cluster 10.0.20.229
ip-10-0-30-217	INFO	2017-02-02 04:57:47.772  INFO [main] com.turvo.presence.PresenceMain - Adding participating host to cluster 10.0.30.217
ip-10-0-30-217	INFO	2017-02-02 04:57:47.027  INFO [main] org.springframework.context.annotation.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7f416310: startup date [Thu Feb 02 04:57:47 UTC 2017]; root of context hierarchy
ip-10-0-20-229	WARN	2017-02-02 04:57:45.799  WARN [hz._hzInstance_1_Union.IO.thread-in-2] com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader - [10.0.20.229]:5701 [Union] [3.6.3] hz._hzInstance_1_Union.IO.thread-in-2 Closing socket to endpoint Address[10.0.30.217]:5702, Cause:java.io.EOFException: Remote socket closed!
ip-10-0-20-229	WARN	2017-02-02 04:57:45.798  WARN [hz._hzInstance_1_Union.IO.thread-in-0] com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader - [10.0.20.229]:5701 [Union] [3.6.3] hz._hzInstance_1_Union.IO.thread-in-0 Closing socket to endpoint Address[10.0.30.217]:5702, Cause:java.io.EOFException: Remote socket closed!
ip-10-0-20-229	INFO	2017-02-02 04:57:45.797  INFO [hz._hzInstance_1_Union.IO.thread-in-0] com.hazelcast.nio.tcp.TcpIpConnection - [10.0.20.229]:5701 [Union] [3.6.3] Connection [Address[10.0.30.217]:5702] lost. Reason: java.io.EOFException[Remote socket closed!]
ip-10-0-20-229	INFO	2017-02-02 04:57:45.795  INFO [hz._hzInstance_1_Union.IO.thread-in-2] com.hazelcast.nio.tcp.TcpIpConnection - [10.0.20.229]:5701 [Union] [3.6.3] Connection [Address[10.0.30.217]:5702] lost. Reason: java.io.EOFException[Remote socket closed!]
ip-10-0-30-217	INFO	2017-02-02 04:18:01.871  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.impl.operations.JoinCheckOperation - [10.0.30.217]:5702 [Union] [3.6.3] Ignoring join check from Address[10.0.30.217]:5701, because this node is not master...
ip-10-0-30-217	INFO	2017-02-02 04:18:01.871  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.impl.operations.JoinCheckOperation - [10.0.30.217]:5702 [Union] [3.6.3] Ignoring join check from Address[10.0.30.217]:5701, because this node is not master...
ip-10-0-30-217	ERROR	2017-02-02 04:16:39.966  ERROR [vert.x-acceptor-thread-0] io.vertx.core.http.impl.HttpServerImpl - java.net.BindException: Address already in use
ip-10-0-30-217	ERROR	2017-02-02 04:16:39.966  ERROR [vert.x-acceptor-thread-0] io.vertx.core.http.impl.HttpServerImpl - java.net.BindException: Address already in use
ip-10-0-30-217	INFO	2017-02-02 04:16:39.719  INFO [main] com.turvo.presence.PresenceMain - Service initialized
ip-10-0-30-217	INFO	2017-02-02 04:16:39.719  INFO [main] com.turvo.presence.PresenceMain - Service initialized
ip-10-0-20-229	INFO	2017-02-02 04:16:38.666  INFO [hz._hzInstance_1_Union.migration] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] All migration tasks have been completed, queues are empty.
ip-10-0-20-229	INFO	2017-02-02 04:16:38.666  INFO [hz._hzInstance_1_Union.migration] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] All migration tasks have been completed, queues are empty.
ip-10-0-30-217	INFO	2017-02-02 04:16:38.589  INFO [vert.x-worker-thread-0] com.hazelcast.core.LifecycleService - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.30.217]:5702 is STARTED
ip-10-0-30-217	INFO	2017-02-02 04:16:38.589  INFO [vert.x-worker-thread-0] com.hazelcast.core.LifecycleService - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.30.217]:5702 is STARTED
ip-10-0-20-229	INFO	2017-02-02 04:16:36.797  INFO [hz._hzInstance_1_Union.migration] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] Re-partitioning cluster data... Migration queue size: 135
ip-10-0-20-229	INFO	2017-02-02 04:16:36.797  INFO [hz._hzInstance_1_Union.migration] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] Re-partitioning cluster data... Migration queue size: 135
ip-10-0-20-229	INFO	2017-02-02 04:16:36.546  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.ClusterService - [10.0.20.229]:5701 [Union] [3.6.3] 
Members [2] {
	Member [10.0.20.229]:5701 this
	Member [10.0.30.217]:5702
}
```

At this point the error is non-recoverable, and I am left with one node which is in frozen state.

Questions:

- I am not clear what exactly happened. I *think* that the partitioning event occurred and master disappeared leaving the node with one slave node trying to rejoin a non-existing master.
- Is the state of the cluster at this point completely inconsistent and unrecoverable?
- Would a forceful state change to active work? What would be the behavior at that point?

My end goal is to be able to rebuild a cluster automatically, even if it means that some processes die as a result (they will be be re-launched by auto-scaling). Ideally I should have no data loss. To this end I wonder if it makes sense for me to tie the state of the hazelcast cluster to the health of a process, i.e state = "FROZEN" || state = "PASSIVE" means unhealthy. Being unhealthy for more than 60 seconds, kills the process. This along with a map store seems like the a brutal way to try to solve the problem, but it may be good enough.

**Comment by mdogan** [comment] 2017-02-24 07:14
Hi @nickhristov, 

Thanks for the report. We'll investigate this.

**Comment by nickhristov** [comment] 2017-03-03 07:19
Hello, 

I wanted to ask if there is any update on this issue? Progress, or potential root cause analysis? Any way to avoid this issue, a recommended configuration?

Thanks

**Comment by mmedenjak** [comment] 2017-07-12 13:36
@nickhristov looks like the node for which you have posted the logs is going into shutdown and is thus rejecting join requests. Can you show us some logs from before this? Do you know why the node is going into shutdown?

**Comment by nickhristov** [comment] 2017-07-12 21:50
@mmedenjak I opened this issue quite a few months ago. I don't have the logs any longer.

The node was going into shut down because it was a part of a development cluster and that cluster has a high turn over of nodes. Nevertheless, I was expecting that the cluster would eventually recover.

**Comment by mmedenjak** [comment] 2017-07-13 06:17
Interesting, the node went into shutdown but couldn't complete it, possibly because it couldn't communicate with other nodes. We'll try and get to the bottom of this.
Are you still using Hazelcast and which version? Are you still experiencing this issue?

**Comment by gdongus** [comment] 2018-07-03 09:09
Facing the same issue during a unit test with the following code:

` new HazelcastUtil(Hazelcast.newHazelcastInstance())
                .tryToExecuteInLock(LOCK_ID, () -> countDownLatch.countDown());`

` public boolean tryToExecuteInLock(final String processId, final Runnable runnable) {
        final Lock lock = hazelcastInstance.getLock(processId);

        log.debug("Trying to get lock for: '{}'", processId);
        if (lock.tryLock()) {
            try {
                log.debug("got lock for: '{}'", processId);
                runnable.run();
                return true;
            } finally {
                log.debug("Trying to unlock: '{}'", processId);
                lock.unlock();
                log.debug("Successfully unlocked: '{}'", processId);
            }
        } else {
            log.debug("Failed to get lock for: '{}'", processId);
            return false;
        }
    }`

**Comment by devozerov** [comment] 2019-12-06 15:09
Hi. Are we still targeting this to 4.0? If yes, could you provide any hints on how to reproduce the problem?

**Comment by mmedenjak** [comment] 2019-12-06 15:16
I was about to comment that this is not going to be fixed. I've tried the reproducer posted [here](https://github.com/hazelcast/hazelcast/issues/9972#issuecomment-402067938) in 3.12 but could not reproduce the issue. 

In Hazelcast 4.0, we have replaced the entire implementation of ILock with the unsafe mode of CP subsystem (https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#removal-of-deprecated-concurrency-api-implementations). If you don't require strong consistency guarantees, that mode might fit your use case and solve the issue. If you do require strong consistency guarantees, you definitely might want to try out using the CP subsystem by turning off unsafe mode and running the appropriate number of members. Please try it out.

Given that we don't have logs for the initial report and that we suspect there was a problem where the nodes were not able to communicate, I am closing this issue.

Please reopen or comment when you have more information.

**Closed by mmedenjak** 2019-12-06 15:16 UTC
Labels: Source: Community, Team: Core, Type: Defect
