### ISSUE TITLE
Jetty Hazelcast session manager Testing start an Hazelcast instance to join an already running one with testcontainers/docker

### ISSUE THREAD

**Issue by olamy** [hazelcast/hazelcast#18508] opened 2021-04-12 03:36 UTC
**Describe the bug**
While writing some integration test for Jetty Hazelcast session manager, we start an Hazelcast instance using Testcontainers/docker then try to start another on the current host to join the docker one as cluster member.

**Expected behavior**
The instance started in the host should be able to join the cluster

**To Reproduce**

1. clone https://github.com/olamy/hazelcast-testcontainers
2. `mvn install`

**Additional context**

**Comment by leszko** [comment] 2021-04-14 07:22
Jetty Session Manager is maintained by Jetty Project, so I suggest creating a GH Issue here: https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-hazelcast

**Comment by olamy** [comment] 2021-04-14 08:11
@leszko thanks for the answer. I'm actually a Jetty committer maintaining the session manager :).
Maybe the issue title is not correct but my issue is concerning Hazelcast and not Jetty.
Please look at the sample project.

**Comment by leszko** [comment] 2021-04-14 08:23
ok, we'll look into this.

**Comment by alparslanavci** [comment] 2021-04-15 08:59
@olamy it looks `localhost` hostname resolution causes an issue to reach the container network. Please try resolving the IP address before giving it to the Hazelcast configuration as below:

```
String host = InetAddress.getByName(hazelcast.getContainerIpAddress()).getHostAddress();
```

**Comment by olamy** [comment] 2021-04-19 10:22
@alparslanavci thanks for your answer but it doesn't work. You should look at this reproduction project I provide here https://github.com/olamy/hazelcast-testcontainers

I get this error/timeout
```
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:55077, timeout: 10000, bind-any: true
10064 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:20:21 AM com.hazelcast.nio.tcp.TcpIpConnection
10065 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] Initialized new cluster connection between /172.17.0.9:5701 and /172.17.0.1:57416
Apr. 19, 2021 8:20:21 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Initialized new cluster connection between /127.0.0.1:53025 and /127.0.0.1:55077
16048 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:20:27 AM com.hazelcast.internal.cluster.ClusterService
16048 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] 
16048 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: 
16049 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Members {size:2, ver:2} [
16049 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: 	Member [127.0.0.1]:5701 - 1336deda-38e1-4c6f-a8c2-f577d1172c99 this
16049 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: 	Member [127.0.0.1]:5705 - 312a3f0f-ddf7-40b5-ab85-e767b9cc4fc1
16049 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: ]
16049 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: 
48284 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:20:59 AM com.hazelcast.internal.diagnostics.HealthMonitor
48285 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] processors=4, physical.memory.total=2.9G, physical.memory.free=1.3G, swap.space.total=2.0G, swap.space.free=2.0G, heap.memory.used=227.7M, heap.memory.free=25.8M, heap.memory.total=253.5M, heap.memory.max=2.1G, heap.memory.used/total=89.66%, heap.memory.used/max=10.66%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, load.process=33.33%, load.system=66.67%, load.systemAverage=2.77, thread.count=39, thread.peakCount=39, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=153, executor.q.priorityOperation.size=20, operations.completed.count=83802, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.p
48285 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: ercentage=0.00%, operations.pending.invocations.count=13, proxy.count=0, clientEndpoint.count=0, connection.active.count=1, client.connection.count=0, connection.count=1
Apr. 19, 2021 8:21:19 PM com.hazelcast.internal.cluster.ClusterService
WARNING: [127.0.0.1]:5705 [dev] [3.12.10] Not updating members received from caller: [127.0.0.1]:55077 because node is not joined! 
68268 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:21:19 AM com.hazelcast.internal.diagnostics.HealthMonitor
68268 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] processors=4, physical.memory.total=2.9G, physical.memory.free=1.2G, swap.space.total=2.0G, swap.space.free=2.0G, heap.memory.used=190.8M, heap.memory.free=126.7M, heap.memory.total=317.5M, heap.memory.max=2.1G, heap.memory.used/total=60.08%, heap.memory.used/max=8.95%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, load.process=100.00%, load.system=0.00%, load.systemAverage=4.35, thread.count=39, thread.peakCount=39, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=218, executor.q.priorityOperation.size=23, operations.completed.count=170279, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.
68268 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: percentage=0.00%, operations.pending.invocations.count=28, proxy.count=0, clientEndpoint.count=0, connection.active.count=1, client.connection.count=0, connection.count=1
78091 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:21:29 AM com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
78091 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: WARNING: [127.0.0.1]:5701 [dev] [3.12.10] Suspecting Member [127.0.0.1]:5705 - 312a3f0f-ddf7-40b5-ab85-e767b9cc4fc1 because it has not sent any heartbeats since 2021-04-19 10:20:27.392. Now: 2021-04-19 10:21:29.403, heartbeat timeout: 60000 ms, suspicion level: 1.00
78128 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:21:29 AM com.hazelcast.nio.tcp.TcpIpConnection
78128 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] Connection[id=1, /172.17.0.9:5701->/172.17.0.1:57416, qualifier=null, endpoint=[127.0.0.1]:5705, alive=false, type=MEMBER] closed. Reason: Suspecting Member [127.0.0.1]:5705 - 312a3f0f-ddf7-40b5-ab85-e767b9cc4fc1 because it has not sent any heartbeats since 2021-04-19 10:20:27.392. Now: 2021-04-19 10:21:29.403, heartbeat timeout: 60000 ms, suspicion level: 1.00
Apr. 19, 2021 8:21:29 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connection[id=1, /127.0.0.1:53025->/127.0.0.1:55077, qualifier=null, endpoint=[127.0.0.1]:55077, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
78138 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:21:29 AM com.hazelcast.internal.cluster.impl.MembershipManager
78139 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] Removing Member [127.0.0.1]:5705 - 312a3f0f-ddf7-40b5-ab85-e767b9cc4fc1
78150 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:21:29 AM com.hazelcast.internal.cluster.ClusterService
78150 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] 
78150 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: 
78150 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Members {size:1, ver:3} [
78150 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: 	Member [127.0.0.1]:5701 - 1336deda-38e1-4c6f-a8c2-f577d1172c99 this
78150 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: ]
78150 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: 
78164 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:21:29 AM com.hazelcast.transaction.TransactionManagerService
78164 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] Committing/rolling-back live transactions of [127.0.0.1]:5705, UUID: 312a3f0f-ddf7-40b5-ab85-e767b9cc4fc1
78165 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:21:29 AM com.hazelcast.nio.tcp.TcpIpConnector
78165 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] Connecting to /127.0.0.1:5705, timeout: 10000, bind-any: true
78178 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:21:29 AM com.hazelcast.nio.tcp.TcpIpConnector
78178 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] Could not connect to: /127.0.0.1:5705. Reason: SocketException[Connection refused to address /127.0.0.1:5705]
Apr. 19, 2021 8:21:31 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:55077, timeout: 10000, bind-any: true
80290 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: Apr 19, 2021 10:21:31 AM com.hazelcast.nio.tcp.TcpIpConnection
80290 [docker-java-stream--1009653334] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] Initialized new cluster connection between /172.17.0.9:5701 and /172.17.0.1:57560
Apr. 19, 2021 8:21:31 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Initialized new cluster connection between /127.0.0.1:53128 and /127.0.0.1:55077
Apr. 19, 2021 8:21:32 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
WARNING: [127.0.0.1]:5705 [dev] [3.12.10] Could not create connection to possible master [127.0.0.1]:5701
Apr. 19, 2021 8:21:36 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
WARNING: [127.0.0.1]:5705 [dev] [3.12.10] Could not create connection to possible master [127.0.0.1]:5701
Apr. 19, 2021 8:21:41 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
WARNING: [127.0.0.1]:5705 [dev] [3.12.10] Could not create connection to possible master [127.0.0.1]:5701
Apr. 19, 2021 8:21:46 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
WARNING: [127.0.0.1]:5705 [dev] [3.12.10] Could not create connection to possible master [127.0.0.1]:5701
```

**Comment by olamy** [comment] 2021-04-21 01:00
@leszko @alparslanavci  do you guys have enough informations?

**Comment by alparslanavci** [comment] 2021-05-26 17:22
@olamy sorry for the late reply. 

It looks like the issue is caused by the port mapping of test-containers. The Hazelcast member running inside container knows and assumes that it is running with the port `5701`, but the Hazelcast member running outside of the container tries to connect to the container-running Hazelcast member using the random assigned port by test-containers. This causes the conflict on the member lists of two members and they cannot form a cluster eventually. 

I know that it is deprecated and not recommended to use but could you please try the same setup with `org.testcontainers.containers.FixedHostPortGenericContainer`?

**Comment by alparslanavci** [comment] 2021-05-26 17:31
In addition to `FixedHostPortGenericContainer `, another way of running this use case might be using the `setPortBindings` method with `5701:5701` port mapping.

**Comment by olamy** [comment] 2021-06-13 23:33
Hi @alparslanavci 
I try using that but still no luck :(
Do you have any example?
Or maybe you could look at this project (https://github.com/olamy/hazelcast-testcontainers.git ) just run `mvn clean verify` and tell me what is wrong?
Thanks

**Comment by alparslanavci** [comment] 2021-06-15 16:22
@olamy It looks you removed `-Dhazelcast.local.publicAddress=127.0.0.1` setting. You'll need this to expose a Hazelcast instance running in a container. See [here](https://github.com/hazelcast/hazelcast-docker#hazelcast-hello-world) for details.

**Comment by olamy** [comment] 2021-07-12 03:35
@alparslanavci sorry for late answer but I can get it working using testcontainer java api (your documentation is using command line).
Please have a look at this reproducer https://github.com/olamy/hazelcast-testcontainers .
It seems to work but the logs shows ` Connection closed` 

```
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Initialized new cluster connection between /127.0.0.1:54459 and /127.0.0.1:5701
12877 [docker-java-stream-68561203] INFO HazelcastDockerLogs - STDERR: Jul 12, 2021 2:51:29 AM com.hazelcast.internal.cluster.ClusterService
12877 [docker-java-stream-68561203] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] 
12877 [docker-java-stream-68561203] INFO HazelcastDockerLogs - STDERR: 
12877 [docker-java-stream-68561203] INFO HazelcastDockerLogs - STDERR: Members {size:2, ver:2} [
12877 [docker-java-stream-68561203] INFO HazelcastDockerLogs - STDERR: 	Member [127.0.0.1]:5701 - bba08749-9774-4238-afe6-78a694679530 this
12877 [docker-java-stream-68561203] INFO HazelcastDockerLogs - STDERR: 	Member [127.0.0.1]:5705 - 198d07d9-7b47-41a9-8b1d-6541a663cfb9
12877 [docker-java-stream-68561203] INFO HazelcastDockerLogs - STDERR: ]
12877 [docker-java-stream-68561203] INFO HazelcastDockerLogs - STDERR: 
Jul. 12, 2021 12:51:29 PM com.hazelcast.cache.impl.operation.OnJoinCacheOperation
WARNING: [127.0.0.1]:5705 [dev] [3.12.10] This member is joining a cluster whose members support JCache, however the cache-api artifact is missing from this member's classpath. In case JCache API will be used, add cache-api artifact in this member's classpath and restart the member.
Jul. 12, 2021 12:51:29 PM com.hazelcast.internal.cluster.ClusterService
INFO: [127.0.0.1]:5705 [dev] [3.12.10] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - bba08749-9774-4238-afe6-78a694679530
	Member [127.0.0.1]:5705 - 198d07d9-7b47-41a9-8b1d-6541a663cfb9 this
]

Jul. 12, 2021 12:51:30 PM com.hazelcast.core.LifecycleService
INFO: [127.0.0.1]:5705 [dev] [3.12.10] [127.0.0.1]:5705 is STARTED
13913 [docker-java-stream-68561203] INFO HazelcastDockerLogs - STDERR: Jul 12, 2021 2:51:30 AM com.hazelcast.internal.partition.impl.PartitionStateManager
13913 [docker-java-stream-68561203] INFO HazelcastDockerLogs - STDERR: INFO: [127.0.0.1]:5701 [dev] [3.12.10] Initializing cluster partition table arrangement...
23019 [main] INFO AppTest - clusterMember/address: Member [127.0.0.1]:5701 - bba08749-9774-4238-afe6-78a694679530/[127.0.0.1]:5701
23019 [main] INFO AppTest - clusterMember/address: Member [127.0.0.1]:5705 - 198d07d9-7b47-41a9-8b1d-6541a663cfb9 this/[127.0.0.1]:5705
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connection[id=1, /127.0.0.1:54459->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connection[id=2, /127.0.0.1:54462->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connection[id=3, /127.0.0.1:54463->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connection[id=4, /127.0.0.1:54464->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connection[id=5, /127.0.0.1:54465->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connection[id=6, /127.0.0.1:54466->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connection[id=7, /127.0.0.1:54467->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connection[id=8, /127.0.0.1:54468->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connection[id=9, /127.0.0.1:54469->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Could not connect to: /127.0.0.1:5701. Reason: SocketException[Connection refused to address /127.0.0.1:5701]
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Could not connect to: /127.0.0.1:5701. Reason: SocketException[Connection refused to address /127.0.0.1:5701]
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Could not connect to: /127.0.0.1:5701. Reason: SocketException[Connection refused to address /127.0.0.1:5701]
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [127.0.0.1]:5705 [dev] [3.12.10] Could not connect to: /127.0.0.1:5701. Reason: SocketException[Connection refused to address /127.0.0.1:5701]
Jul. 12, 2021 12:51:40 PM com.hazelcast.nio.tcp.TcpIpConnectionErrorHandler
WARNING: [127.0.0.1]:5705 [dev] [3.12.10] Removing connection to endpoint [127.0.0.1]:5701 Cause => java.net.SocketException {Connection refused to address /127.0.0.1:5701}, Error-Count: 5

```

**Comment by alparslanavci** [comment] 2021-08-04 11:40
@olamy I tried in my local setup and yes, I also see the same connection closed logs. It looks they are thrown when the container in the test-containers is shut down. The test-containers might be keeping the port open for a small amount of time after the Hazelcast container is terminated. Since the local Hazelcast instance is still up and running, it is still trying to connect to the open port but it is not identified and closed. I can say this is not a fatal issue, and won't affect the Hazelcast cluster's running at all.

**Comment by alparslanavci** [comment] 2021-10-15 10:03
@olamy is it ok to close this? Do you have any other questions?

**Comment by alparslanavci** [comment] 2021-11-02 13:03
@olamy I am closing the issue because of inactivity. Feel free to reopen if needed.

**Closed by alparslanavci** 2021-11-02 13:03 UTC
Labels: Type: Defect, Team: Integration, Source: Community
