### ISSUE TITLE
DurableRetrieveResultTest.testSingleExecution_WhenMigratedAfterCompletion_WhenOwnerMemberKilled

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10033] opened 2017-03-06 20:18 UTC
**master**
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.durableexecutor.DurableRetrieveResultTest.testSingleExecution_WhenMigratedAfterCompletion_WhenOwnerMemberKilled(DurableRetrieveResultTest.java:142)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/7442/testReport/junit/com.hazelcast.durableexecutor/DurableRetrieveResultTest/testSingleExecution_WhenMigratedAfterCompletion_WhenOwnerMemberKilled/

**Comment by hasancelik** [comment] 2017-03-13 11:36
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.durableexecutor.DurableRetrieveResultTest.testSingleExecution_WhenMigratedAfterCompletion_WhenOwnerMemberKilled(DurableRetrieveResultTest.java:142)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/156/testReport/junit/com.hazelcast.durableexecutor/DurableRetrieveResultTest/testSingleExecution_WhenMigratedAfterCompletion_WhenOwnerMemberKilled/

**Comment by sancar** [comment] 2017-03-16 12:16
@tkountis I ignored the test in this PR, because it was failing a lot. 
https://github.com/hazelcast/hazelcast/pull/9821/files

**Comment by hasancelik** [comment] 2017-03-20 12:53
**maintenance**
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.durableexecutor.DurableRetrieveResultTest.testSingleExecution_WhenMigratedAfterCompletion_WhenOwnerMemberKilled(DurableRetrieveResultTest.java:182)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/63/testReport/junit/com.hazelcast.durableexecutor/DurableRetrieveResultTest/testSingleExecution_WhenMigratedAfterCompletion_WhenOwnerMemberKilled/

**Comment by tkountis** [comment] 2017-03-22 18:53
Will merge #10134 I think thats the reason for the failure, and keep this open to see if it happens again. Wasn't able to reproduce locally, for more than 2k executions.

**Comment by enesakar** [comment] 2017-03-28 08:36
closing. Hasan will reopen incase of failure.

**Comment by mmedenjak** [comment] 2017-03-29 16:00
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/7870/
https://console.aws.amazon.com/s3/buckets/j-artifacts/new-lab-fast-pr/7870/new-lab-fast-pr-7870.zip/details?region=us-east-1

**Closed** 2017-04-25 12:12 UTC
Labels: Team: Core, Type: Test-Failure
