### ISSUE TITLE
[map] Decrease of performance indexed search on v3.7.6 and above

### ISSUE THREAD

**Issue by illian64** [hazelcast/hazelcast#11231] opened 2017-08-26 15:21 UTC
Hello!
I found decrease of performance for indexed search.
I put objects (200 000) in map. Each object has 2 fields, for example String field1 and String field2.
field1 - isn't unique, field2 - is unique. Both has index.
After that I try to find values by field1 and field2 100 times.

```java
Predicate predicate = entryObject.get("field1").equal(value1)
    .and(entryObject.get("field2").equal(value2));
```

For version 3.7.5 and below search takes about 50 milliseconds.
For version 3.7.6 and above (include 3.8.4 and 3.9 EA) search takes about 5000 milliseconds.

If field1 will be unique, search on version 3.7.6 and above takes about 50 milliseconds again.

I wrote very simple test for reproduce it.

Do I something wrong?

```java
@Slf4j
public class SoHazelcastTest {
    public static final int COUNT = 200_000;
    public static final String MAP = "map";

    @Test
    public void testUnique() throws Exception {
        test(true); //approximately 50 milliseconds on 3.7.5 and 3.7.6
    }

    @Test
    public void testNotUnique() throws Exception {
        test(false); //approximately 50 milliseconds on 3.7.5 and approximately 5000 milliseconds on 3.7.6
    }

    private void test(boolean uniqueValue1) {
        Config hazelcastConfig = new Config();
        MapConfig mapConfig = hazelcastConfig.getMapConfig(MAP);
        mapConfig.addMapIndexConfig(new MapIndexConfig("field1", false));
        mapConfig.addMapIndexConfig(new MapIndexConfig("field2", false));
        HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(hazelcastConfig);

        log.info("Fill in");
        for (int i = 0; i < COUNT; i++) {
            String value1 = uniqueValue1 ? "v1" + i : "v1";
            hazelcastInstance.getMap(MAP).put(UUID.randomUUID(), new StoredObject(value1, "value2_" + i));
        }

        log.info("Start search");
        long startTime = System.nanoTime();
        for (int i = 0; i < 100; i++) {
            String value1 = uniqueValue1 ? "v1" + i : "v1";
            EntryObject entryObject = new PredicateBuilder().getEntryObject();
            Predicate predicate = entryObject.get("field1").equal(value1)
                    .and(entryObject.get("field2").equal("value2_" + i));
            assertEquals(1, hazelcastInstance.getMap(MAP).values(predicate).size());
        }
        long durationInMills = (System.nanoTime() - startTime) / 1000000;
        log.info("Finish search, durationInMills = {}", durationInMills);

        Hazelcast.shutdownAll();
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    private static class StoredObject implements Serializable {
        private String field1;
        private String field2;
    }
}
```

**Comment by pveentjer** [comment] 2017-08-27 06:59
@illian64 thanks for the reproducer and nailing it down to the commit!

**Comment by jerrinot** [comment] 2018-03-08 14:52
@taburet: isnt this a duplicate of the issue you have been working on?

**Comment by taburet** [comment] 2018-03-08 14:54
@jerrinot not sure yet, but most likely it is not, since here we have the degradation on non-unique indexes only, going to check this tomorrow.

**Comment by taburet** [comment] 2018-03-09 12:52
I have profiled 3.7.5, 3.7.6 and 3.10-SNAPSHOT. As it turned out, the slowdown is caused by the introduction of the result set copying for indexed queries in 3.7.6. This was done to make the returned result set more consistent, so the index modifications performed after the result set was obtained are not affecting the result set contents. In the provided test this causes copying of 200k entries on every query invocation in the non-unique index case.

In the 3.9 series the `hazelcast.index.copy.behavior` option was introduced to control this copying behavior. If its value is set to `NEVER` the behavior and the performance are exactly the same as it was in 3.7.5. The default value is `COPY_ON_READ`, which provides more strict consistency guarantees than `NEVER`. See [Copying Indexes](http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Query/How_Distributed_Query_Works/Indexing_Queries.html#page_Copying+Indexes) and [`IndexCopyBehavior`](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/query/impl/IndexCopyBehavior.java) for more in-depth details.

**Comment by mmedenjak** [comment] 2018-03-12 12:30
Closing as the cause is in correctness constraints and there is a workaround.

**Closed by mmedenjak** 2018-03-12 12:30 UTC
Labels: Estimation: M, Interface: IMap, Team: Core, Type: Perf. Defect
