### ISSUE TITLE
cluster split heal test's loose data / structures from the cluster

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12851] opened 2018-04-12 09:35 UTC
I see random fail in the split heal test's, https://hazelcast-l337.ci.cloudbees.com/view/split/

after some re run the test do pass.

looking at 
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-atomic-long/

I am looking in to the logs but I do not see why it should have lost the data.

after some split heal cycle we see
`fail HzMember2HZAA split_validate_qA hzcmd.atomic.ilong.Size threadId=0 global.AssertionException: atomicLongsplit_atomicA303 size 0 != expected 1`

which means the atomic long `atomicLongsplit_atomicA303` was lost out of the cluster.

i set longer setting for 
-Dhazelcast.max.no.heartbeat.seconds=120
-Dhazelcast.max.no.master.confirmation.seconds=250

but the next run https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-atomic-long/27/console 

also lost an atomic long.

I don't know why it should happen that we lost structures out of the split cluster ?

essentially the tests all have the same format:

  start a 5 node cluster,

  load some data/structs into the cluster

  split the cluster into a 2 and 3 node cluster

  heal the cluster into a 5 node cluster 

  check for the data / structs

after a few split/heal cycles we lose the data/structs.

**Comment by Danny-Hazelcast** [comment] 2018-04-12 09:37
even if the cluster splits into some odd size, like a 
2 node 
1 node
2 node 
cluster on heal should't all the struct / data still be present in the final cluster ?

**Comment by Danny-Hazelcast** [comment] 2018-04-13 06:53
I have this test https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-total/4/console

```
hz cluster -ee -size M5 -v ${hzVersion} -boxes a.box -user ${user}

hz run load
hz run validate

for i in {0..20} ; do
    #hz run clusterFrozen
    hz split Member Member
    hz run untilClusterSize1 untilClusterSafe
    #hz run clusterActive
    hz heal
    hz run untilClusterSize5 untilClusterSafe
    hz run size
    hz run validate
done
```

which splits the cluster up into single members and rejoins,  and each time we validate
the data is still there.

**Comment by Danny-Hazelcast** [comment] 2018-04-16 06:51
issue possible related  https://github.com/hazelcast/hazelcast/issues/12868

**Comment by mmedenjak** [comment] 2018-04-16 13:50
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/12868

**Closed by mmedenjak** 2018-04-16 13:50 UTC
Labels: Team: Core, Type: Critical, Type: Defect
