### ISSUE TITLE
CacheExpirationTest.test_backupOperationAppliesDefaultExpiryPolicy

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#14434] opened 2019-01-30 08:03 UTC
Failed on PR builder:
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/81/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_backupOperationAppliesDefaultExpiryPolicy_useSyncBackups_true_/
```
java.lang.AssertionError: expected:<100> but was:<101>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.test.HazelcastTestSupport$13.run(HazelcastTestSupport.java:1082)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsEventually(HazelcastTestSupport.java:1079)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_backupOperationAppliesDefaultExpiryPolicy(CacheExpirationTest.java:324)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Holmistr** [comment] 2019-02-06 08:53
Perhaps related to https://github.com/hazelcast/hazelcast-enterprise/issues/2684

**Comment by ahmetmircik** [comment] 2019-03-01 07:54
This test was marked as ignored. There is a new issue for the root cause of failure: https://github.com/hazelcast/hazelcast-enterprise/issues/2723

**Comment by tezc** [comment] 2019-03-12 09:47
Failed again on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/50/testReport/com.hazelcast.cache.eviction/CacheExpirationTest/test_backupOperationAppliesDefaultExpiryPolicy_useSyncBackups_true_/

**Comment by ihsandemir** [comment] 2019-12-09 12:09
I saw a failure on my PR build: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4908/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_backupOperationAppliesDefaultExpiryPolicy_useSyncBackups_true_/

```
Stacktrace
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.test.backup.TestBackupUtils$5.run(TestBackupUtils.java:155)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1345)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1447)
	at com.hazelcast.test.backup.TestBackupUtils.assertExpirationTimeExistsEventually(TestBackupUtils.java:149)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_backupOperationAppliesDefaultExpiryPolicy(CacheExpirationTest.java:316)
```

**Comment by mdogan** [comment] 2019-12-10 08:10
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4936/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_backupOperationAppliesDefaultExpiryPolicy_useSyncBackups_true_/

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.test.backup.TestBackupUtils$5.run(TestBackupUtils.java:155)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1345)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1447)
	at com.hazelcast.test.backup.TestBackupUtils.assertExpirationTimeExistsEventually(TestBackupUtils.java:149)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_backupOperationAppliesDefaultExpiryPolicy(CacheExpirationTest.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
Hiccups measured while running test 'test_backupOperationAppliesDefaultExpiryPolicy[useSyncBackups:true](com.hazelcast.cache.eviction.CacheExpirationTest):'
07:19:35, accumulated pauses: 197 ms, max pause: 57 ms, pauses over 1000 ms: 0
07:19:40, accumulated pauses: 556 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:19:45, accumulated pauses: 142 ms, max pause: 34 ms, pauses over 1000 ms: 0
07:19:50, accumulated pauses: 426 ms, max pause: 13 ms, pauses over 1000 ms: 0
07:19:55, accumulated pauses: 670 ms, max pause: 12 ms, pauses over 1000 ms: 0
07:20:00, accumulated pauses: 815 ms, max pause: 33 ms, pauses over 1000 ms: 0
07:20:05, accumulated pauses: 564 ms, max pause: 17 ms, pauses over 1000 ms: 0
07:20:10, accumulated pauses: 249 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:20:15, accumulated pauses: 174 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:20:20, accumulated pauses: 71 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:20:25, accumulated pauses: 35 ms, max pause: 2 ms, pauses over 1000 ms: 0
07:20:30, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:20:35, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:20:40, accumulated pauses: 32 ms, max pause: 3 ms, pauses over 1000 ms: 0
07:20:45, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:20:50, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:20:55, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:21:00, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:21:05, accumulated pauses: 41 ms, max pause: 3 ms, pauses over 1000 ms: 0
07:21:10, accumulated pauses: 32 ms, max pause: 3 ms, pauses over 1000 ms: 0
07:21:15, accumulated pauses: 40 ms, max pause: 3 ms, pauses over 1000 ms: 0
07:21:20, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:21:25, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:21:30, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:21:35, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:21:40, accumulated pauses: 278 ms, max pause: 246 ms, pauses over 1000 ms: 0
07:21:45, accumulated pauses: 2 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by devozerov** [comment] 2019-12-16 09:51
Another failure, now with an extended error message: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5073/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_backupOperationAppliesDefaultExpiryPolicy_useSyncBackups_true_/

**Comment by devozerov** [comment] 2019-12-16 09:52
```
java.lang.AssertionError: Non existent key on backup partition key=0, accessor=CacheBackupAccessor{cacheName='f4ba6e57-750c-4ebf-98d1-729d52eb86f6'} AbstractBackupAccessor{replicaIndex=1}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.backup.TestBackupUtils.lambda$assertExpirationTimeExistsEventually$4(TestBackupUtils.java:146)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1351)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1453)
	at com.hazelcast.test.backup.TestBackupUtils.assertExpirationTimeExistsEventually(TestBackupUtils.java:134)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_backupOperationAppliesDefaultExpiryPolicy(CacheExpirationTest.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sancar** [comment] 2019-12-20 11:23
Another failure 
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5207/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_backupOperationAppliesDefaultExpiryPolicy_useSyncBackups_true_/

```
Error Message
Non existent key on backup partition key=0, accessor=CacheBackupAccessor{cacheName='d8223c40-ea41-4c71-b6c4-5539f603155b'} AbstractBackupAccessor{replicaIndex=1}
Stacktrace
java.lang.AssertionError: Non existent key on backup partition key=0, accessor=CacheBackupAccessor{cacheName='d8223c40-ea41-4c71-b6c4-5539f603155b'} AbstractBackupAccessor{replicaIndex=1}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.backup.TestBackupUtils.lambda$assertExpirationTimeExistsEventually$4(TestBackupUtils.java:146)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.test.backup.TestBackupUtils.assertExpirationTimeExistsEventually(TestBackupUtils.java:134)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_backupOperationAppliesDefaultExpiryPolicy(CacheExpirationTest.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Closed** 2019-12-20 16:28 UTC
Labels: Module: ICache, Source: Internal, Team: Core, Type: Test-Failure
