### ISSUE TITLE
SqlErrorClientTest.testMapMigration fails

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#17347] opened 2020-08-14 09:52 UTC
The `com.hazelcast.sql.SqlErrorClientTest.testMapMigration[smartRouting:true]` failed on the PR builder http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/1812/

**Stacktrace**
```
junit.framework.AssertionFailedError: expected:<1009> but was:<1005>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.hazelcast.sql.SqlErrorAbstractTest.checkMapMigration(SqlErrorAbstractTest.java:147)
	at com.hazelcast.sql.SqlErrorClientTest.testMapMigration(SqlErrorClientTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment] 2020-08-17 07:49
@devozerov can you take a look?

**Comment by ahmetmircik** [comment] 2020-08-17 10:21
New similar test failure but happening on node side: 
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/1843/testReport/junit/com.hazelcast.sql/SqlErrorTest/testMapMigration/

```
Error Message
expected:<1009> but was:<1005>
Stacktrace
junit.framework.AssertionFailedError: expected:<1009> but was:<1005>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.hazelcast.sql.SqlErrorAbstractTest.checkMapMigration(SqlErrorAbstractTest.java:147)
	at com.hazelcast.sql.SqlErrorTest.testMapMigration(SqlErrorTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by devozerov** [comment] 2020-08-17 11:03
The problem is fixed in https://github.com/hazelcast/hazelcast/pull/17361
The description of the change could be found in the PR.

**Comment by sancar** [comment] 2020-09-18 11:46
@devozerov There is one recent failure here: 
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2406/testReport/junit/com.hazelcast.sql/SqlErrorClientTest/testMapMigration_smartRouting_false_/
```
Error Message
Exception is not thrown.
Stacktrace
junit.framework.AssertionFailedError: Exception is not thrown.
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:227)
	at com.hazelcast.sql.SqlErrorAbstractTest.assertSqlException(SqlErrorAbstractTest.java:264)
	at com.hazelcast.sql.SqlErrorAbstractTest.checkMapMigration(SqlErrorAbstractTest.java:154)
	at com.hazelcast.sql.SqlErrorClientTest.testMapMigration(SqlErrorClientTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

I am reopening to issue to investigate the failure.

**Comment by lazerion** [comment] 2020-09-19 09:27
@devozerov Recent failure on [Hazelcast-4.master-sonar](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/626/testReport/com.hazelcast.sql/SqlErrorClientTest/testMapDestroy_secondMember_smartRouting_true_/)
```
com.hazelcast.sql.SqlErrorClientTest.testMapDestroy_secondMember[smartRouting:true]
```

**Comment by devozerov** [comment] 2020-09-22 07:07
The fix for both failures is implemented: https://github.com/hazelcast/hazelcast/pull/17595

**Closed** 2020-09-22 09:19 UTC
Labels: Module: SQL, Source: Internal, Team: Core, Type: Test-Failure
