### ISSUE TITLE
Management center 3.11 does not work when deployed as ROOT app

### ISSUE THREAD

**Issue by juantula** [hazelcast/hazelcast#14141] opened 2018-11-16 21:04 UTC
I'm upgrading to Hazelcast 3.11 and when tried to update Management Center to version 3.11, deployed as ROOT app in Tomcat, login page breaks due to a JS issue, in the following code:

    <script type="text/javascript">
      // we need to get the mancenter prefix from JAVA env somehow
      window.MANCENTER_URL_PREFIX =
        document.querySelector("meta[name='ctx']").getAttribute('content')
        // and we need to trim `/`, router configuration adds them when needed
          .replace(/^\/|\/$/g, '')
    </script>

The reason is that the meta tag has no "content" attribute in this scenario:
<meta name="ctx"/>

**Comment by juantula** [comment] 2018-11-16 21:06
Sorry, meta tag was just dropped. It is rendered in this way:
`<meta name="ctx"/>`

**Comment by emre-aydin** [comment] 2018-11-21 09:16
Hi @juantula,

Thanks for reporting the issue. We were able to reproduce it. We're working on a fix right now. Will update you once it's fixed.

**Comment by emre-aydin** [comment] 2018-11-27 09:42
@juantula we have a fix ready for the issue you had. It will be released around the end of December with MC version 3.11.2. Unfortunately, it won't make it into version 3.11.1 which will be released in a few days because we had a code freeze for 3.11.1 couple of days ago. 

BTW, please note that for patch versions, Management Center does not sync with IMDG so don't confuse MC version with Hazelcast version.

**Comment by emre-aydin** [comment] 2018-12-04 08:41
@juantula we have merged the fix. It will be released with MC 3.11.2.

**Closed by emre-aydin** 2018-12-04 08:41 UTC
Labels: Source: Community, Team: Management Center, Type: Defect

**Comment by juantula** [comment] 2018-12-04 20:58
Awesome, thanks!

**Comment by emre-aydin** [comment] 2018-12-14 17:08
@juantula there was a change regarding the release plans. MC 3.11.2 was released today, and it contained only a single bug fix (not this one). This issue will be fixed with MC 3.11.3 which is scheduled for end of the month as before.

**Comment by emre-aydin** [comment] 2019-01-31 12:53
@juantula MC 3.11.3 is released. You can find it [here](https://hazelcast.org/download/#management-center).
