### ISSUE TITLE
XML for FlakeId

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#13951] opened 2018-10-12 15:27 UTC
Flake ID Generator can only be configured in Java

In 3.10 XSD, there's no section for `hazelcast` or `hazelcast-client`.

**Comment by neilstevenson** [comment] 2018-10-12 15:36
It's missing from
https://hazelcast.com/schema/client-config/hazelcast-client-config-3.10.xsd
and
https://hazelcast.com/schema/config/hazelcast-config-3.10.xsd

**Comment by mmedenjak** [comment] 2018-10-24 06:30
Closing as the root cause has been identified as another issue.

**Closed by mmedenjak** 2018-10-24 06:30 UTC
