### ISSUE TITLE
[map] [map-store] MapLoaderTest.testSenderAndBackupTerminates_AfterInitialLoad

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8508] opened 2016-07-12 08:03 UTC
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
    at org.apache.log4j.Category.callAppenders(Category.java:201)
    at org.apache.log4j.Category.forcedLog(Category.java:388)
    at org.apache.log4j.Category.log(Category.java:823)
    at com.hazelcast.logging.Log4jFactory$Log4jLogger.log(Log4jFactory.java:50)
    at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:167)
    at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:155)
    at com.hazelcast.logging.AbstractLogger.fine(AbstractLogger.java:45)
    at com.hazelcast.test.mocknetwork.MockJoiner.getJoinAddress(MockJoiner.java:84)
    at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:51)
    at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
    at com.hazelcast.instance.Node.join(Node.java:650)
    at com.hazelcast.instance.Node.start(Node.java:362)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:132)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:116)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newInstances(TestHazelcastInstanceFactory.java:166)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newInstances(TestHazelcastInstanceFactory.java:172)
    at com.hazelcast.map.impl.mapstore.MapLoaderTest.testSenderAndBackupTerminates_AfterInitialLoad(MapLoaderTest.java:67)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/279/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testSenderAndBackupTerminates_AfterInitialLoad/

**Comment by hasancelik** [comment] 2016-09-05 08:17
```
com.hazelcast.spi.exception.TargetNotMemberException: Not Member! target: [127.0.0.1]:5359, partitionId: 8, operation: com.hazelcast.map.impl.operation.LoadMapOperation, service: hz:impl:mapService
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:324)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.access$300(Invocation.java:94)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation$InvocationRetryTask.run(Invocation.java:530)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:111)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
	at com.hazelcast.map.impl.proxy.MapProxySupport.loadAllInternal(MapProxySupport.java:477)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.loadAll(MapProxyImpl.java:562)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testSenderAndBackupTerminates_AfterInitialLoad(MapLoaderTest.java:77)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK7/com.hazelcast$hazelcast/119/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testSenderAndBackupTerminates_AfterInitialLoad/

**Comment by tombujok** [comment] 2016-12-19 13:12
Failures unrelated to map-loader:
First failure -> got stuck on cluster creation (jenkins/network hiccup)
Second failure -> probably a split brain 
#9498 should make it more stable.

**Comment by mmedenjak** [comment] 2017-03-29 20:25
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/7884/
https://console.aws.amazon.com/s3/buckets/j-artifacts/new-lab-fast-pr/7884/new-lab-fast-pr-7884.zip/details?region=us-east-1

**Comment by Donnerbart** [comment] 2017-05-05 17:30
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8716/
https://console.aws.amazon.com/s3/buckets/j-artifacts/new-lab-fast-pr/8716/new-lab-fast-pr-8716.zip/details?region=us-east-1

**Comment by blazember** [comment] 2018-02-12 14:11
Closing as could not reproduce it with thousands of executions. Some logging was added to `MapLoaderTest.testSenderAndBackupTerminates_AfterInitialLoad` to provide us with some additional info if it fails again.

**Closed by blazember** 2018-02-12 14:11 UTC
Labels: Team: Core, Type: Test-Failure
