### ISSUE TITLE
Hazelcast instance name with Hibernate still creates multiple instances

### ISSUE THREAD

**Issue by chandreshp** [hazelcast/hazelcast#4374] opened 2015-01-02 05:28 UTC
I am using below setting in my grails-hibernate application:
cache.hazelcast.instance_name = hc_cache

We have 3 databases configured and by default, Hazelcast creates 3 cache instances although the contents are the same across them. On specifying an instance name, it should be creating a single instance with the specified name but it still creates the three instances.
I am using Hazelcast 3.2.6 and Grails 2.2.3

**Comment by mesutcelik** [comment] 2015-01-06 12:03
you are missing **hibernate.** prefix. Can you please try again?

```
hibernate.cache.hazelcast.instance_name
```

I am closing this ticket. please feel free to reopen if you still see the problem.

**Comment by chandreshp** [comment] 2015-01-06 12:38
As I said, I am using grails. So, below is my configuration:
hibernate {
    jdbc.batch_size = 50
    cache.use_second_level_cache = true
    cache.use_query_cache = true
//    cache.provider_class = 'net.sf.ehcache.hibernate.SingletonEhCacheProvider'
    cache.region.factory_class = 'com.hazelcast.hibernate.HazelcastCacheRegionFactory'
    cache.hazelcast.instance_name = hc_cache
}
I don't think I need to prefix 'hibernate.'.

**Comment by mesutcelik** [comment] 2015-01-09 07:35
Hi @chandreshp ,
Can you please create unit test or reproducer application? That would be very helpful to pinpoint the problem if exists.

Thanks in advance.

**Comment by chandreshp** [comment] 2015-01-27 10:06
I was trying to reproduce this issue using the demo code samples that come with hazelcast 3.4 but got below errors:
A. Tried 'mvn exec:java -Dexec.mainClass="com.hazelcast.hibernate.CreateDB"' on "hazelcast-3.4\code-samples\hazelcast-integration\hibernate-2ndlevel-cache" on windows 7 and it gave below error even though it said "BUILD SUCCESS":
[INFO] --- exec-maven-plugin:1.3.2:java (default-cli) @ hibernate-2ndlevel-cache ---
[WARNING] Warning: killAfter is now deprecated. Do you need it ? Please comment on MEXEC-6.
[WARNING] thread Thread[Timer-0,5,com.hazelcast.hibernate.CreateDB] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[Timer-0,5,com.hazelcast.hibernate.CreateDB] will linger despite being asked to die via interruption
[WARNING] thread Thread[derby.rawStoreDaemon,5,derby.daemons] will linger despite being asked to die via interruption
[WARNING] NOTE: 2 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running
 code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.hazelcast.hibernate.CreateDB,maxpri=10]
java.lang.IllegalThreadStateException
        at java.lang.ThreadGroup.destroy(ThreadGroup.java:775)
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:328)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

B. Tried '"mvn exec:java -Dexec.mainClass="com.hazelcast.hibernate.ManageEmployee"' and it gave below error:
Jan 27, 2015 3:29:34 PM org.hibernate.hql.internal.ast.ASTQueryTranslatorFactory <init>
INFO: HHH000397: Using ASTQueryTranslatorFactory
Failed to create sessionFactory object.java.lang.NoClassDefFoundError: org/hibernate/cache/QueryResultsRegion
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ExceptionInInitializerError
        at com.hazelcast.hibernate.ManageEmployee.main(ManageEmployee.java:29)
        ... 6 more
Caused by: java.lang.NoClassDefFoundError: org/hibernate/cache/QueryResultsRegion
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:240)
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:125)
        at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:87)
        at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:46)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:105)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:251)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:225)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206)
        at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:295)
        at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2442)
        at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2438)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1855)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1928)
        at com.hazelcast.hibernate.ManageEmployee.main(ManageEmployee.java:26)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.hibernate.cache.QueryResultsRegion
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 22 more

Thanks.
Please let me know where I may need to correct.

**Comment by bilalyasar** [comment] 2015-01-27 10:49
@chandreshp you can edit these line as following:
https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/hibernate-2ndlevel-cache/pom.xml#L25
```
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>${hazelcast.version}</version>
        </dependency>

        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-hibernate4</artifactId>
            <version>${hazelcast.version}</version>
        </dependency>
```
hazelcast-all includes hibernate3 and hibernate4 and this cause exceptions, so we have to seperate them as shown above.

**Comment by chandreshp** [comment] 2015-01-27 11:06
Thanks @bilalyasar.
I am now getting below error with 'mvn exec:java -Dexec.mainClass="com.hazelcast.hibernate.ManageEmployee"':
INFO: [172.16.50.168]:5701 [hibernate] [3.4] Address[172.16.50.168]:5701 is STARTED
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NoSuchMethodError: org.hibernate.SessionFactory.openSession()Lorg/hibernate/classic/Session;
        at com.hazelcast.hibernate.ManageEmployee.main(ManageEmployee.java:33)
        ... 6 more

**Comment by bilalyasar** [comment] 2015-01-27 11:24
the problem is same, in your classpath is there any hazelcast-all.jar?
and can you try this command in hibernate 2nd level cache directory:
killall -9 java
rm -rf hibernateDB/
mvn exec:java -Dexec.mainClass="com.hazelcast.hibernate.CreateDB"
mvn exec:java -Dexec.mainClass="com.hazelcast.hibernate.ManageEmployee"

and this is my pom.xml: https://gist.github.com/bilalyasar/61cecc4539f5ecada9df

**Comment by chandreshp** [comment] 2015-01-27 11:43
Thanks @bilalyasar. Your suggestions worked and the example now works flawlessly. I will reproduce this issue and then will give details.

**Comment by chandreshp** [comment] 2015-01-29 06:52
I have modified the code sample for "hibernate 2nd level cache" to reproduce the issue. In essence, on supplying "hibernate.cache.hazelcast.instance_name" to both the schemas, there should be only one member/instance of hazelcast but instead two are created. Link for code to reproduce the issue:
https://drive.google.com/file/d/0B-ZNyhIT_jtJUDJwb0VyQjh0YlE/view?usp=sharing

**Comment by bilalyasar** [comment] 2015-01-29 12:07
@chandreshp thanks for sample application, i tried your sample application and added this line `hibernate.cfg.xml` and `testHibernate.cfg.xml` 
`<property name="hibernate.cache.hazelcast.instance_name">name</property>`
and see that only 1 instance has started.
But when i removed instance_name property or when instance_name's are different, 2 instance are starting. I couldn't find anything unexpected.  
so if you want to start only 1 instance their names should be same in the config xml files.

**Comment by chandreshp** [comment] 2015-01-29 12:33
I tried setting the same property as you have specified but I still see two members created. If you need more information or want to see my environment, please ping me on my google id : <cprakash at gmail . com>.

**Comment by chandreshp** [comment] 2015-01-30 08:58
@bilalyasar Just checked on another system and you are right - the bug didn't reproduce itself. Will check on my system again to find out what is going on and update here.

**Comment by bilalyasar** [comment] 2015-01-30 11:10
this is my hibernate.cfg.xml file: https://gist.github.com/bilalyasar/206dca2684e960a5e4ca
and this is testHibernate.cfg.xml file: https://gist.github.com/bilalyasar/d8b4ef14f7b5025e33d3

the property instance_name same for the two of them and 1 instance is started.
As you said maybe there is another misconfiguration in your system.

**Comment by chandreshp** [comment] 2015-02-03 09:11
It was my bad. Please close this issue as invalid.

**Closed** 2015-02-03 09:17 UTC
Labels: Team: Integration, Type: Defect
