### ISSUE TITLE
TransactionalList does not exhibit behaviour of conventional List (java.util.list).

### ISSUE THREAD

**Issue by shalakhansidmul** [hazelcast/hazelcast#10294] opened 2017-04-11 06:19 UTC
The TransactionalList does not have methods such as `iterator()`,  `remove(int index)`, etc.

**Comment by mmedenjak** [comment] 2017-04-11 06:27
Applies to `TransactionalSet` as well.

**Comment by mdogan** [comment] 2017-05-31 12:13
duplicate of https://github.com/hazelcast/hazelcast/issues/2207

**Closed by mdogan** 2017-05-31 12:13 UTC
Labels: Team: Core, Type: Enhancement
