### ISSUE TITLE
Dynamic wan replication configuration

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast#6794] opened 2015-11-19 16:43 UTC
Hi - 

I would like to be able to dynamically (at runtime) alter/define the WAN replication configuration.

Is this possible? If so any pointers to samples or what classes in the API I should be looking into?

**Comment by mesutcelik** [comment] 2015-11-20 08:03
Thanks @bitsofinfo for the consideration. It is actually a duplicate of https://github.com/hazelcast/hazelcast/issues/592 so i am closing this ticket. 

Unfortunately we don't have dynamic configuration at the moment. I hope we will get it in future releases.

**Closed by mesutcelik** 2015-11-20 08:03 UTC
Labels: Team: Integration

**Comment by bitsofinfo** [comment] 2015-11-20 14:51
what the advantage is to WAN replication out of the box, vs just listing WAN connected Hazelcast IPs individually in the normal peer cluster setup?
