### ISSUE TITLE
Client disconnects sometimes

### ISSUE THREAD

**Issue by nick7ikin** [hazelcast/hazelcast#8745] opened 2016-08-18 16:22 UTC
I use hazelcast in my application and sometimes I get client disconnected from member without any visible reason. My application requires quick disconnect detection so client is configured to send heartbeats quite frequently:
`clientConfig.setProperty("hazelcast.client.heartbeat.interval", "200");  // millis`
with a quite small timeout:
`clientConfig.setProperty("hazelcast.client.heartbeat.timeout", "800");  // millis`

It works well most of the time, but sometimes client get disconnected for very short period of time. Here are logs from the application:

```
2016-08-18 08:20:42,261 [hz.client_0_new.user-3] INFO: [HZ] Lifecycle CLIENT_DISCONNECTED
2016-08-18 08:20:42,267 [hz.client_0_new.user-4] INFO: [HZ] Lifecycle CLIENT_CONNECTED
```

In order check are there any issue with local network I setup on client `tcpdump` to log packets between client and master. I see that each heartbeats produces 3 packets like this:

```
2016-08-18 08:20:41.045422 IP 192.168.0.22.54442 > 192.168.9.27.5701: Flags [P.], seq 82596:82650, ack 671902, win 30408, options [nop,nop,TS val 222472448 ecr
2016-08-18 08:20:41.046125 IP 192.168.9.27.5701 > 192.168.0.22.54442: Flags [P.], seq 671902:671937, ack 82650, win 256, options [nop,nop,TS val 179323671 ecr 2
2016-08-18 08:20:41.046151 IP 192.168.0.22.54442 > 192.168.9.27.5701: Flags [.], ack 671937, win 30408, options [nop,nop,TS val 222472448 ecr 179323671], length
```

Here `192.168.0.22.54442` - client socket, `192.168.9.27.5701` - member socket. There isn't any another host in this cluster. Also I setup ping utility to check if there are any network issues. It was run with the following command on the client:

```
fping -e -A -l -p200 -t200 192.168.9.27
```

so it sends ping packet each 200 millis with 200 ms timeout. Ping utility have to discover network issue before the hazelcast client which has heartbeat timeout 800 ms. Ping packets are also captured by tcpdump.

So for the disconnect, mentioned above, which occurred at `2016-08-18 08:20:42,261` there are the following tcpdump logs:

```
2016-08-18 08:20:41.445637 IP 192.168.0.22.54442 > 192.168.9.27.5701: Flags [P.], seq 82650:82704, ack 671937, win 30408, options [nop,nop,TS val 222472548 ecr 179323671], length 54
2016-08-18 08:20:41.446160 IP 192.168.9.27.5701 > 192.168.0.22.54442: Flags [P.], seq 671937:671972, ack 82704, win 256, options [nop,nop,TS val 179323771 ecr 222472548], length 35
2016-08-18 08:20:41.446191 IP 192.168.0.22.54442 > 192.168.9.27.5701: Flags [.], ack 671972, win 30408, options [nop,nop,TS val 222472548 ecr 179323771], length 0
2016-08-18 08:20:41.617500 IP 192.168.0.22 > 192.168.9.27: ICMP echo request, id 20791, seq 1622, length 76
2016-08-18 08:20:41.617899 IP 192.168.9.27 > 192.168.0.22: ICMP echo reply, id 20791, seq 1622, length 76
2016-08-18 08:20:41.819522 IP 192.168.0.22 > 192.168.9.27: ICMP echo request, id 20791, seq 1623, length 76
2016-08-18 08:20:41.819823 IP 192.168.9.27 > 192.168.0.22: ICMP echo reply, id 20791, seq 1623, length 76
2016-08-18 08:20:42.021579 IP 192.168.0.22 > 192.168.9.27: ICMP echo request, id 20791, seq 1624, length 76
2016-08-18 08:20:42.021985 IP 192.168.9.27 > 192.168.0.22: ICMP echo reply, id 20791, seq 1624, length 76
2016-08-18 08:20:42.122151 IP 192.168.9.27.54327 > 224.2.2.3.54327: UDP, length 362
2016-08-18 08:20:42.223288 IP 192.168.0.22 > 192.168.9.27: ICMP echo request, id 20791, seq 1625, length 76
2016-08-18 08:20:42.223688 IP 192.168.9.27 > 192.168.0.22: ICMP echo reply, id 20791, seq 1625, length 76
2016-08-18 08:20:42.255676 IP 192.168.0.22.54442 > 192.168.9.27.5701: Flags [P.], seq 82704:82758, ack 671972, win 30408, options [nop,nop,TS val 222472751 ecr 179323771], length 54
2016-08-18 08:20:42.256944 IP 192.168.9.27.5701 > 192.168.0.22.54442: Flags [P.], seq 671972:672007, ack 82758, win 256, options [nop,nop,TS val 179323974 ecr 222472751], length 35
2016-08-18 08:20:42.256972 IP 192.168.0.22.54442 > 192.168.9.27.5701: Flags [.], ack 672007, win 30408, options [nop,nop,TS val 222472751 ecr 179323974], length 0
2016-08-18 08:20:42.258250 IP 192.168.0.22.54442 > 192.168.9.27.5701: Flags [F.], seq 82758, ack 672007, win 30408, options [nop,nop,TS val 222472751 ecr 179323974], length 0
2016-08-18 08:20:42.259052 IP 192.168.9.27.5701 > 192.168.0.22.54442: Flags [F.], seq 672007, ack 82759, win 256, options [nop,nop,TS val 179323974 ecr 222472751], length 0
2016-08-18 08:20:42.259075 IP 192.168.0.22.54442 > 192.168.9.27.5701: Flags [.], ack 672008, win 30408, options [nop,nop,TS val 222472751 ecr 179323974], length 0
2016-08-18 08:20:42.261140 IP 192.168.0.22.48292 > 192.168.9.27.5702: Flags [S], seq 2613303381, win 29200, options [mss 1460,sackOK,TS val 222472752 ecr 0,nop,wscale 0], length 0
2016-08-18 08:20:42.261531 IP 192.168.9.27.5702 > 192.168.0.22.48292: Flags [R.], seq 0, ack 2613303382, win 0, length 0
2016-08-18 08:20:42.264023 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [S], seq 811796638, win 29200, options [mss 1460,sackOK,TS val 222472753 ecr 0,nop,wscale 0], length 0
2016-08-18 08:20:42.264419 IP 192.168.9.27.5701 > 192.168.0.22.54490: Flags [S.], seq 1530777610, ack 811796639, win 28960, options [mss 1460,sackOK,TS val 179323976 ecr 222472753,nop,wscale 7], length 0
2016-08-18 08:20:42.264444 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [.], ack 1, win 29200, options [nop,nop,TS val 222472753 ecr 179323976], length 0
2016-08-18 08:20:42.265015 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [P.], seq 1:7, ack 1, win 29200, options [nop,nop,TS val 222472753 ecr 179323976], length 6
2016-08-18 08:20:42.265363 IP 192.168.9.27.5701 > 192.168.0.22.54490: Flags [.], ack 7, win 227, options [nop,nop,TS val 179323976 ecr 222472753], length 0
2016-08-18 08:20:42.265513 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [P.], seq 7:357, ack 1, win 29200, options [nop,nop,TS val 222472753 ecr 179323976], length 350
2016-08-18 08:20:42.265962 IP 192.168.9.27.5701 > 192.168.0.22.54490: Flags [.], ack 357, win 235, options [nop,nop,TS val 179323976 ecr 222472753], length 0
2016-08-18 08:20:42.266610 IP 192.168.9.27.5701 > 192.168.0.22.54490: Flags [P.], seq 1:249, ack 357, win 235, options [nop,nop,TS val 179323976 ecr 222472753], length 248
2016-08-18 08:20:42.266621 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [.], ack 249, win 30016, options [nop,nop,TS val 222472753 ecr 179323976], length 0
2016-08-18 08:20:42.267183 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [P.], seq 357:411, ack 249, win 30016, options [nop,nop,TS val 222472753 ecr 179323976], length 54
2016-08-18 08:20:42.267770 IP 192.168.9.27.5701 > 192.168.0.22.54490: Flags [P.], seq 249:378, ack 411, win 235, options [nop,nop,TS val 179323977 ecr 222472753], length 129
2016-08-18 08:20:42.267798 IP 192.168.9.27.5701 > 192.168.0.22.54490: Flags [P.], seq 378:465, ack 411, win 235, options [nop,nop,TS val 179323977 ecr 222472753], length 87
2016-08-18 08:20:42.267855 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [.], ack 465, win 31088, options [nop,nop,TS val 222472754 ecr 179323977], length 0
2016-08-18 08:20:42.275159 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [P.], seq 411:498, ack 465, win 31088, options [nop,nop,TS val 222472755 ecr 179323977], length 87
2016-08-18 08:20:42.276020 IP 192.168.9.27.5701 > 192.168.0.22.54490: Flags [P.], seq 465:509, ack 498, win 235, options [nop,nop,TS val 179323979 ecr 222472755], length 44
2016-08-18 08:20:42.276214 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [P.], seq 498:585, ack 509, win 31088, options [nop,nop,TS val 222472756 ecr 179323979], length 87
2016-08-18 08:20:42.277138 IP 192.168.9.27.5701 > 192.168.0.22.54490: Flags [P.], seq 509:553, ack 585, win 235, options [nop,nop,TS val 179323979 ecr 222472756], length 44
2016-08-18 08:20:42.278321 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [P.], seq 585:1392, ack 553, win 31088, options [nop,nop,TS val 222472756 ecr 179323979], length 807
2016-08-18 08:20:42.280052 IP 192.168.9.27.5701 > 192.168.0.22.54490: Flags [P.], seq 553:588, ack 1392, win 248, options [nop,nop,TS val 179323980 ecr 222472756], length 35
2016-08-18 08:20:42.319509 IP 192.168.0.22.54490 > 192.168.9.27.5701: Flags [.], ack 588, win 31088, options [nop,nop,TS val 222472767 ecr 179323980], length 0
```

As I can see the last heartbeat before disconnect finished at `08:20:41.446191`. After that from `08:20:41.617500` to `08:20:42.223688` there were 4 ping packets and no heartbeats sent by hazelcast. So between the last heartbeat (`08:20:41.446191`) and the next hazelcast packed (`08:20:42.255676`) it is approximately 809ms which is greater than client's timeout (800ms). And that's why the client got disconnected.

So the question is why hazelcast wasn't able to send heartbeats for such a long period of time? While it is obvious that local network worked properly. Could you give any ideas?

**Comment by jerrinot** [comment] 2016-08-20 12:52
Hello @nick7ikin,

800ms is really a very aggressive timeout. Depending on your JVM configuration it can be easily exceeded due a pause caused by garbage collection. All it takes is a 400ms pause on a client and 400ms on a server. I would recommend you to enable verbose GC logs. However there can be other reasons - for example threads can be occupied by a long running task, etc. 

What is your use case? I assume you have a strict SLA so you need to detect a failure quickly to active some kind of circuit-breaker / fallback strategy? Is this correct? If so then perhaps you could use [async interface](https://github.com/jerrinot/hazelcast/blob/c59ad46ee1277282b4eaa7b489f8a4ac58c4909e/hazelcast/src/main/java/com/hazelcast/core/IMap.java#L321-L321) and where you can enforce maximum waiting time better.

**Comment by sancar** [comment] 2017-02-14 15:57
Closing because unresponsive. 
@nick7ikin 
Feel free to reopen if you need further answers to your questions.

**Closed by sancar** 2017-02-14 15:57 UTC
Labels: Team: Client
