### ISSUE TITLE
Wrong Topic statistics

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#7442] opened 2016-02-01 21:33 UTC
I have a simple HZ 3.5.4 env, 1 client, 1 server. Client perform put/get on server. There is 1 topic between server and client. 1 class on the server side publish messages to the topic and 1 class on the client side receive them. I monitor Topic statistics via JMX. The stats say: localPublishOperatrionCount = 10046. The same is totalMessageCount. These numbers are correct. But localReceiveOperationCount = 65590. I don't see how this is possible.

Please have a look.

Thanks, Denis

**Comment by jerrinot** [comment] 2016-02-02 16:12
Hi @dsukhoroslov, thanks for a bug report. 

I can't reproduce this issue, could you please share your code / reproducer?

**Comment by dsukhoroslov** [comment] 2016-02-03 10:45
Hi @jerrinot 

There is no code for this particular case. Ok, I'll try to prepare a test..

**Comment by muratayan** [comment] 2016-02-22 14:27
Hello @dsukhoroslov, 

Any update about the sample code for reproducing the issue? I couldn't reproduce as well.

**Comment by dsukhoroslov** [comment] 2016-02-24 14:21
Hi @muratayan,
No, not yet. Had no time to take closer look on this.

**Comment by mesutcelik** [comment] 2016-03-11 08:30
Hi @dsukhoroslov ,

I am closing the ticket now. please feel free to reopen once you have time to reproduce the issue.

**Closed by mesutcelik** 2016-03-11 08:30 UTC
Labels: Team: Integration, Type: Defect
