### ISSUE TITLE
Hazelcast (3.8.4) closing listeners

### ISSUE THREAD

**Issue by cryptomorph** [hazelcast/hazelcast#11264] opened 2017-08-30 14:33 UTC
**Issue**

As discussed 2017-08-29 with Al

We are losing notification from a hazelcast node through ITopic listeners (MessageListener<E>). Infrequently (but often enough to be a concern) we lose all notifications for new messages posted to an ITopic that are stored on one node in a cluster. Other nodes in the cluster seem to continue to work normally and the client continues to receive new messages from those nodes. This happens with no exceptions/errors seen at the client side.

This is not an issue with ReliableTopics and associated listeners.

**Replication**

We can replicate this issue as follows:

1. Run a cluster of 2 nodes and one client application subscribed to the ITopics.
2. Post messages (increasing integers) in an ITopic
3. Repeatedly shut down and restart one node until we see the client logging messages with obvious gaps.

**Comment by pcortizona** [comment] 2017-08-31 12:13
We have observed the same behavior.

**Comment by sancar** [comment] 2017-09-05 08:40
Same problem also reported here
https://github.com/hazelcast/hazelcast/issues/10101#issuecomment-325620776
Pasting here as future reference.

**Comment by sancar** [comment] 2017-09-05 09:50
The issue caused by using hostnames to connect.
For a workaround using ip addresses instead of hostnames will work. 

fix is almost ready. It will be applied to 3.9 and backported to 3.8.6
Related issue : https://github.com/hazelcast/hazelcast/pull/11226

**Comment by sancar** [comment] 2017-09-15 09:14
fixed by https://github.com/hazelcast/hazelcast/pull/11368

**Closed by sancar** 2017-09-15 09:14 UTC
Labels: Team: Client, Type: Defect
