### ISSUE TITLE
About Invocation thread, number shown in the log, Invocations, timeouts, backup-timeouts

### ISSUE THREAD

**Issue by alexzhao8898** [hazelcast/hazelcast#8731] opened 2016-08-17 04:13 UTC
Hi,
I had develop a application about hazalcast. Unluckily, we found that the application will be hanged on about about 4 hours,
I found that something in the log.
2016-08-17 06:28:01,445 DEBUG [OperationService]: {hz._hzInstance_1_dev.InvocationMonitorThread} [1.1.1.4]:5701 [dev] [3.6.4] Invocations:62 timeouts:0 backup-timeouts:0
in every 4 hours, Invocations number is not normal, 
in the application, Invocation number is 1 to 0, but after  that time, i,e. it show 62, abnormal start. (some times may hanged, may core dump...)
So,what is the meaning of those 3 numbers?

**Comment by jerrinot** [comment] 2016-08-17 09:48
@alexzhao8898: the log message means you have 62 in-flight invocations. none of them timed out - they  are still waiting for a response. 

Some invocations can be internal, it depends what features of Hazelcast you are using. Can you describe you scenario a bit? what's your cluster size? Can you reproduce the hanging situation?

**Comment by alexzhao8898** [comment] 2016-08-17 12:03
In our application, there are many uncertainties.
Simply said that, the application is about 2000 TPS with cluster, and monitor the network. 
After getting message from 2000 TPS for about 5 hours(load test), some times may hanged, may core dump...), and transaction id may needed to store in hazalcast. 
Cluster is only 2, and we are only found that the number is strange and want to clafity what is the meaning only
Btw, is invocations means the message send from host A to host B for update the memory because sync thru internal TCP?

**Comment by jerrinot** [comment] 2016-08-20 13:41
@alexzhao8898: Invocation is a counter-part of an operation. It's used (among other things) to correlate responses with waiting threads. 

Example: 
I have 2 Hazelcast members: MemberA and MemberA. 
When MemberA wants to access an entry stored in MemberB then it will create an invocation and binds it to a `GetOperation`. The `GetOperation` is sent over the network to `MemberB`. Eventually a response arrives and the invocation is used to find whoever is waiting for the response. 

Can you try your scenario with Hazelcast 3.7? It's a fresh release with tons of internal improvements + MUCH better diagnostics & troubleshooting capabilities.

**Comment by pveentjer** [comment] 2017-07-10 08:39
Closing this ticket due to lack of updates. Feel free to reopen it.

**Closed by pveentjer** 2017-07-10 08:39 UTC
Labels: Team: Core, Type: Defect
