### ISSUE TITLE
Compilation error for Sources

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26302] opened 2024-04-01 19:06 UTC
Error on zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-EE-5.maintenance-ZingJDK17/75/consoleFull#-169004011769eb5c31-3d34-428d-9488-b96b4ee53c1d

Possible failure [commit](https://github.com/hazelcast/hazelcast-mono/commit/99d5664944f7d32f33e78aec2840afc341afbce2) : 99d5664944f7d32f33e78aec2840afc341afbce2

<details><summary>Standard output:</summary>

```
19:17:28 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-EE-5.maintenance-ZingJDK17/hazelcast/hazelcast/src/main/java/com/hazelcast/jet/pipeline/Sources.java:[760,32] incompatible types: inference variable V has incompatible equality constraints K,V,K,K,K,V,V
```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-EE-5.maintenance-ZingJDK17/75/

**Comment by JackPGreen** [comment] 2024-04-03 09:59
Unable to reproduce [locally via Docker](https://hazelcast.atlassian.net/browse/HZ-2245?focusedCommentId=93755).

**Comment by orcunc** [comment] 2024-05-02 08:22
I am closing this issue as there is no compilation problem anymore. Here is a the link to a green build 
https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-EE-5.maintenance-ZingJDK17/78/

**Closed by orcunc** 2024-05-02 08:22 UTC
Labels: Team: Core, Type: Test-Failure, Module: Jet
