### ISSUE TITLE
Hazelcast AWS discovery does not support custom port

### ISSUE THREAD

**Issue by ramesshh** [hazelcast/hazelcast#10406] opened 2017-04-20 14:51 UTC
Hazelcast's built-in AWS discovery mechanism does not support setting port other than default ones

https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/util/AddressHelper.java#L69

**Comment by emrahkocaman** [comment] 2017-04-24 07:19
Hi @ramesshh , closing this issue as it's duplicate of https://github.com/hazelcast/hazelcast-aws/issues/3.
Please check that issue for details.

**Closed by emrahkocaman** 2017-04-24 07:19 UTC
