### ISSUE TITLE
TopicOverloadDistributedTest.whenBlock_whenNoSpace

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7603] opened 2016-02-25 10:26 UTC
```
java.lang.AssertionError: expected:<100> but was:<14>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.topic.impl.reliable.TopicOverloadAbstractTest.whenBlock_whenNoSpace(TopicOverloadAbstractTest.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:785)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/50/testReport/junit/com.hazelcast.topic.impl.reliable/TopicOverloadDistributedTest/whenBlock_whenNoSpace/

**Comment by gurbuzali** [comment] 2016-02-25 10:30
almost duplicate of https://github.com/hazelcast/hazelcast/issues/6819, the difference is this one runs on more members. anyway the test is ignored on master, I've just missed maintenance

**Closed by gurbuzali** 2016-02-25 10:30 UTC
Labels: Team: Core, Type: Test-Failure
