### ISSUE TITLE
Failure while executing MigrationInfo Problem while reading IdentifiedDataSerializable, namespace: -18, classId: 6, exception: null EnterpriseDataSerializableSerializer

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#19261] opened 2021-08-04 12:56 UTC
sql predicate not returning correct result during 4.2 -> 5.0 RU
http://jenkins.hazelcast.com/view/rollup/job/rollup-sql/159/console

```
WARNING: [10.0.0.254]:5701 [HZ] [5.0-SNAPSHOT] Failure while executing MigrationInfo{uuid=fecabbec-4085-426c-afec-1a5df3bb8780, partitionId=3, source=[10.0.0.238]:5701 - 9344f684-5e40-48ca-8b4c-a1e6cb50eb5d, sourceCurrentReplicaIndex=1, sourceNewReplicaIndex=-1, destination=[10.0.0.243]:5701 - 40746268-664f-4567-b85a-5143e61320a7, destinationCurrentReplicaIndex=3, destinationNewReplicaIndex=1, master=[10.0.0.238]:5701, initialPartitionVersion=369, partitionVersionIncrement=2, status=ACTIVE}
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading IdentifiedDataSerializable, namespace: -18, classId: 6, exception: null
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.rethrowIdsReadException(EnterpriseDataSerializableSerializer.java:315)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:168)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
```

/disk1/workspace/rollup-sql/5.0-snapshot/2021_08_04-12_21_50/sql is not a valid command. In Slack, all messages that start 

Danny Conlon  3:54 PM
/disk1/workspace/rollup-sql/5.0-SNAPSHOT/2021_08_04-12_21_50/sql

**Comment by Danny-Hazelcast** [comment] 2021-08-04 13:01
https://github.com/hazelcast/hazelcast/issues/19086

**Comment by mmedenjak** [comment] 2021-08-04 13:03
Closing as a duplicate of https://github.com/hazelcast/hazelcast/issues/19086

**Closed by mmedenjak** 2021-08-04 13:03 UTC
Labels: Type: Defect

**Comment by mmedenjak** [comment] 2021-08-06 14:15
Fix was merged, feel free to retest @Danny-Hazelcast
