### ISSUE TITLE
CacheConfigHolder misses DataPersistenceConfig

### ISSUE THREAD

**Issue by ufukyilmaz** [hazelcast/hazelcast#21620] opened 2022-06-15 07:47 UTC
**Describe the bug**
`CacheConfigHolder` which used in client serialization of `CacheConfig`
doesn't have `DataPersistenceConfig` element which exists in the real
cache config object. Therefore, these cache config accesses from the
client miss this element or updates on this element are ignored.
 
See:
- https://github.com/hazelcast/hazelcast/blob/edabe3f269fec45323f0a4ef817fb27ec3b57be2/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/holder/CacheConfigHolder.java
- https://github.com/hazelcast/hazelcast/blob/edabe3f269fec45323f0a4ef817fb27ec3b57be2/hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java#L95

**Comment by AyberkSorgun** [comment] 2022-06-21 13:02
Closing as duplicate of [#4282](https://github.com/hazelcast/hazelcast-enterprise/issues/4282)

**Closed by AyberkSorgun** 2022-06-21 13:02 UTC
Labels: Type: Defect, Team: Core, Module: Config
