### ISSUE TITLE
RSS Memory Leak in 4.0.1

### ISSUE THREAD

**Issue by bcluap** [hazelcast/hazelcast#17107] opened 2020-06-18 17:51 UTC
**Describe the bug**
A program with a Hazelcast instance continues to grow RSS which indicates a leak in off-heap memory.

This is not a leak in the heap - the program can be run as follows and does not get an OOM error and the heap never runs out of space.

java -Xms30m -Xmx30m -XX:MetaspaceSize=30m -XX:MaxMetaspaceSize=30m -jar <jarfile>

**Expected behavior**
There should be no noticeable RSS increase once all classes and loaded and a steady state is achieved

**To Reproduce**

Run a simple program like this:
```
public class NewMain {
    private static final org.slf4j.Logger log = LoggerFactory.getLogger(NewMain.class);
    public static void main(String[] args) {
        try {
            Config cfg = new Config();
            cfg.setInstanceName(UUID.randomUUID().toString());
            HazelcastInstance hcInstance = Hazelcast.getOrCreateHazelcastInstance(cfg);
            Thread.sleep(3600000L);
            log.warn("Shutting down HC");
            hcInstance.shutdown();
            hcInstance = null;
            log.warn("Shut down HC");
            Thread.sleep(3600000L);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

With a fixed heap and metaspace and use top or similar to track the resident set size. It will start at around 100MB and grow constantly at around 1MB per minute.

When Hazelcast shuts down then the RSS remains static from then on - hence ruling out something else causing this

**Additional context**

Linux pcb 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

Running same code on 3.12.7 does not grow nearly as fast.
cfg.getMetricsConfig().setEnabled(false) does not resolve this issue.

This is not a theoretical issue as this is causing JVM's to be killed in ECS & K8S clusters after a day or so as the RSS grows and grows and hits the container limit. 

Forcing a GC does not change the RSS size. Native memory monitoring to try and work out what is being leaked has not helped much. Does not seem to be a native buffer leak.

**Comment by bcluap** [comment] 2020-06-25 14:13
Just an update on this. I've increased the max allowed memory usage and after 2 days the RSS seems to have stabilised. It seems like this could be due to JIT compiler optimsing Hazelcast bytecode slowly but surely and using up memory as the native code base grows.

**Comment by mmedenjak** [comment] 2020-06-26 09:43
Thank you for the update @bcluap ! I've pinged a colleague and we'll take a look as well.

**Comment by bcluap** [comment] 2020-06-26 11:38
![image](https://user-images.githubusercontent.com/26746221/85852958-f83c0980-b7b1-11ea-9ef4-bfa277ad88cb.png)

This is the kind of thing we see on AWS. It stabilized eventually but seems rather excessive for so much memory to be used by the JIT compiler

**Comment by tkountis** [comment] 2020-06-26 13:33
@bcluap thanks for your report.
I started looking into this, I already have a couple of pointers from my initial analysis, I will follow up once I have something solid.

**Comment by tkountis** [comment] 2020-06-29 11:08
@bcluap I had a few runs over the weekend, using your example I can't reproduce your observation
> grow constantly at around 1MB per minute.

I have tried with duration of 3hrs per run, here is my chart from running your code with your exact JVM params
![image](https://user-images.githubusercontent.com/3369598/85994013-16db1400-b9ef-11ea-82f3-b95e43f56d1b.png)

On that I can't definitively say that I can see a leak (or not), but it doesn't show an infinite increase.

To smooth out the outcome I made a few additions to the JVM props and here are the results
![image](https://user-images.githubusercontent.com/3369598/85997225-29f6df80-ba01-11ea-8443-6a290bf851a0.png)

- Blue line, your run with your JVM properties
- Red line, JVM in interpreted mode & Serial GC to minimize JVM internal needs in memory utilization
- Orange line, JVM in compiled mode & Serial GC as above

Similarly, there is a growth in RSS utilization present in the charts but it appears to be stabilizing within the period of 3 hrs.
I am in the process of producing longer runs just to confirm the above, but it will take some time. In the meantime I wanted to ask you a few questions.

- Do you see this 1MB / min rate on the vanilla code you provided or on your deployed application?
- Could you run your application with following extra JVM options and share with us the behavior in a chart?

```
 -XX:+UseSerialGC
 -XX:+AlwaysPreTouch
 -Xint
```

**Comment by tkountis** [comment] 2020-07-01 09:45
@bcluap here is another update. I believe your observation is most likely related to our Metrics service.
There, we have a few native (ie. off-heap) allocations as a side effect of using the JDK compression libs, which rely on mallloc directly.

During the longer runs I notice similar patterns (to my previous results) that have a _slightly_ positive trendline. On these runs full backtraces were captured, and the only place where native memory is used outside the usual JVM suspects, were the `Deflaters` inside the `MetricsCompressor` class. Here is a screen of the trace.

![image](https://user-images.githubusercontent.com/3369598/86164859-5e09f780-bb0a-11ea-88bd-452a6d822ca8.png)
*Note: This is based on sampling, but its over a very long period of 10hrs*

In fact when the Metrics are disabled the RSS is almost flat
![image](https://user-images.githubusercontent.com/3369598/86167723-f86c3a00-bb0e-11ea-8f8d-d0272891fcdf.png)

--

Now, the fix candidate is [here](https://github.com/hazelcast/hazelcast/pull/17145), which is basically a missing call to `Deflater:end`. 

In an ideal world this wouldn't present itself, because the `Deflater` is a cleanable resource, registered with `java.lang.ref.Cleaner` meaning that when it becomes unreachable, the Cleaner would have triggered the `end` and released the native resources. Indeed, this is what happens most of the time, even in your sample reproducer. However, this all depends on timing with GC, and promotion rates. In some unlucky situations, the Deflater can get promoted due to high allocation rate, in which case the `end` will be called much later when a major GC runs. This behavior however can be problematic, when both heap & off-heap increase the RSS at the same time on a limited memory container, or similar situations. Keep in mind that the allocation per Deflater will be different in a real environment where the actual metrics blob will be bigger.

I know you tried disabling metrics, but I believe that you tried it on your reproducer on an attempt to identify the root cause and not in your production environment. 

Therefore, I want to suggest doing that again on your real environment, and let us know if you see a difference.

---

Here is a before & after screens
**before**
![image](https://user-images.githubusercontent.com/3369598/86168838-a4625500-bb10-11ea-9e5b-3fc58c81becf.png)

**after**
![image](https://user-images.githubusercontent.com/3369598/86168871-adebbd00-bb10-11ea-8d37-5d64484a495c.png)

*Notes:*
- *The above screens have other optimizations in place, so don't compare them on your own captures. The purpose here is to demonstrate the trendline in both cases.*
- *All line charts above show RSS utilization in KB on Y axis & time in seconds in the X axis*

**Comment by bcluap** [comment] 2020-07-01 10:26
Hi Thomas,

Thanks ever so much for your analysis on this.

I did a to of digging as well and unfortunately in the process have been unable to recreate the situation as bad as it was behaving. I have tried endlessly to recreate it with the basic test and cannot get it to be as bad as it once was. My initial thought was that I was going insane but I absolutely 100% got the basic test on JDK 11 to go from 100M RSS to 200M RSS unless than an hour, with GC not making it drop. Subsequent to that, I ran tests with different scenarios and over the last week so a few things changed:
- Using JDK 14 hotspot
- Using JDK 14 Openj9
- Turning metrics on and off
- Using older versions of Hazelcast
- Tuning JIT settings, cache size etc
- Ran some Ubuntu updates in the meantime 
- Rebooted laptop once or twice

And on all of those the RSS was perfectly behaved. (Especially on OJ9 which is much more efficient with memory). As one does, I then went back to JDK 11 hotspot with HC 4.0.1 and now cannot reproduce the problem nearly as badly. As per your graphs, it grows from maybe 100M to 140M over time (mostly due to JIT). If was not for a colleague of mine who witnessed the initial problem, I would be wondering if I was making things up.

Then in terms of our actual production environment, I turned off metrics and changed to JDK 14 & OJ9. With just those changes our RSS graph changed dramatically:

![image](https://user-images.githubusercontent.com/26746221/86233607-f7cab680-bb95-11ea-8b33-10f9b614ab18.png)

You can see the bounce where the JVM changed and subsequent lower RSS. To be honest I attribute most of this to the JVM change as opposed to turning metrics off.

**Comment by tkountis** [comment] 2020-07-01 10:53
Thanks for your update @bcluap, I am not familiar with OJ9 to be honest, so its hard to comment on that part. But the behavior is related to many factors, GC, JIT/CodeCache, Heap, JNI, Agents/Profilers even the underline malloc library. So its hard to point the finger at any one of these.

Having said that, the metrics finding could be problematic on an environment where the allocation rate is high. I didn't try it myself, but I am sure if you have bigger heap, and you stress it with a benchmark more & more Deflaters will escape the young GC and the RSS will grow more.

Anyhow, I guess I am glad that you can't reproduce it, for now, :D but do keep an eye on it and lets us know if you see it again. In the meantime we will try to get this merged.

**Closed** 2020-07-02 11:55 UTC
Labels: Source: Community, Team: Core, Type: Defect
