### ISSUE TITLE
`com.hazelcast.internal.diagnostics.DiagnosticsLogTest.testLogFileContent` test failure

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#16395] opened 2020-01-02 13:12 UTC
- Fails on `Hazelcast-3.x-CorrettoJDK11`
- In [this build](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-CorrettoJDK11/44/testReport/junit/com.hazelcast.internal.diagnostics/DiagnosticsLogTest/testLogFileContent/)
- Stacktrace
```
'01-01-2020 06:36:23 1577860583749 BuildInfo[
                          Build=20200101
                          BuildNumber=20200101
                          Revision=701a5c9
                          Version=4.0-SNAPSHOT
                          SerialVersion=1
                          Enterprise=false]
01-01-2020 06:36:23 1577860583749 SystemProperties[
                          hazelcast.local.localAddress=127.0.0.1
                          hazelcast.logging.class=com.hazelcast.test.TestLoggerFactory
                          hazelcast.metrics.collection.frequency=1
                          hazelcast.metrics.debug.enabled=true
                          hazelcast.phone.home.enabled=false
                          hazelcast.test.use.network=false
                          hazelcast.wait.seconds.before.join=1
                          java.class.path=/home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-CorrettoJDK11/hazelcast/hazelcast/target/test-classes:/home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-CorrettoJDK11/hazelcast/hazelcast/target/classes:/home/jenkins/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.7/jackson-core-2.9.7.jar:/home/jenkins/.m2/repository/org/snakeyaml/snakeyaml-engine/1.0/snakeyaml-engine-1.0.jar:/home/jenkins/.m2/repository/com/hazelcast/hazelcast-aws/2.4/hazelcast-aws-2.4.jar:/home/jenkins/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/home/jenkins/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/jenkins/.m2/repository/javax/cache/cache-tests/1.1.1/cache-tests-1.1.1-tests.jar:/home/jenkins/.m2/repository/javax/cache/cache-tests/1.1.1/cache-tests-1.1.1.jar:/home/jenkins/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/jenkins/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar:/home/jenkins/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar:/home/jenkins/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/home/jenkins/.m2/repository/net/spy/spymemcached/2.12.2/spymemcached-2.12.2.jar:/home/jenkins/.m2/repository/com/atomikos/transactions-jdbc/3.9.3/transactions-jdbc-3.9.3.jar:/home/jenkins/.m2/repository/com/atomikos/transactions-jta/3.9.3/transactions-jta-3.9.3.jar:/home/jenkins/.m2/repository/com/atomikos/transactions/3.9.3/transactions-3.9.3.jar:/home/jenkins/.m2/repository/com/atomikos/transactions-api/3.9.3/transactions-api-3.9.3.jar:/home/jenkins/.m2/repository/com/atomikos/atomikos-util/3.9.3/atomikos-util-3.9.3.jar:/home/jenkins/.m2/repository/org/apache/geronimo/specs/geronimo-jta_1.1_spec/1.1.1/geronimo-jta_1.1_spec-1.1.1.jar:/home/jenkins/.m2/repository/org/nanohttpd/nanohttpd/2.3.1/nanohttpd-2.3.1.jar:/home/jenkins/.m2/repository/org/apache/httpcomponents/httpclient/4.3.1/httpclient-4.3.1.jar:/home/jenkins/.m2/repository/org/apache/httpcomponents/httpcore/4.3/httpcore-4.3.jar:/home/jenkins/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/jenkins/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar:/home/jenkins/.m2/repository/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.jar:/home/jenkins/.m2/repository/org/codehaus/groovy/groovy-all/2.1.8/groovy-all-2.1.8.jar:/home/jenkins/.m2/repository/org/jruby/jruby-complete/1.7.22/jruby-complete-1.7.22.jar:/home/jenkins/.m2/repository/org/ops4j/pax/exam/pax-exam-junit4/2.6.0/pax-exam-junit4-2.6.0.jar:/home/jenkins/.m2/repository/org/ops4j/pax/exam/pax-exam-spi/2.6.0/pax-exam-spi-2.6.0.jar:/home/jenkins/.m2/repository/asm/asm/3.0/asm-3.0.jar:/home/jenkins/.m2/repository/org/ops4j/pax/tinybundles/tinybundles/1.0.0/tinybundles-1.0.0.jar:/home/jenkins/.m2/repository/biz/aQute/bndlib/1.43.0/bndlib-1.43.0.jar:/home/jenkins/.m2/repository/org/ops4j/base/ops4j-base-lang/1.4.0/ops4j-base-lang-1.4.0.jar:/home/jenkins/.m2/repository/org/ops4j/pax/exam/pax-exam-container-paxrunner/2.6.0/pax-exam-container-paxrunner-2.6.0.jar:/home/jenkins/.m2/repository/org/ops4j/pax/exam/pax-exam/2.6.0/pax-exam-2.6.0.jar:/home/jenkins/.m2/repository/org/ops4j/base/ops4j-base-store/1.4.0/ops4j-base-store-1.4.0.jar:/home/jenkins/.m2/repository/org/ops4j/base/ops4j-base-util-property/1.4.0/ops4j-base-util-property-1.4.0.jar:/home/jenkins/.m2/repository/org/ops4j/pax/exam/pax-exam-container-remote/2.6.0/pax-exam-container-remote-2.6.0.jar:/home/jenkins/.m2/repository/org/ops4j/pax/swissbox/pax-swissbox-core/1.5.1/pax-swissbox-core-1.5.1.jar:/home/jenkins/.m2/repository/org/ops4j/pax/swissbox/pax-swissbox-lifecycle/1.5.1/pax-swissbox-lifecycle-1.5.1.jar:/home/jenkins/.m2/repository/org/ops4j/pax/exam/pax-exam-container-rbc-client/2.6.0/pax-exam-container-rbc-client-2.6.0.jar:/home/jenkins/.m2/repository/org/ops4j/pax/exam/pax-exam-container-rbc/2.6.0/pax-exam-container-rbc-2.6.0.jar:/home/jenkins/.m2/repository/org/ops4j/base/ops4j-base-io/1.4.0/ops4j-base-io-1.4.0.jar:/home/jenkins/.m2/repository/org/ops4j/base/ops4j-base-net/1.4.0/ops4j-base-net-1.4.0.jar:/home/jenkins/.m2/repository/org/ops4j/base/ops4j-base-monitors/1.4.0/ops4j-base-monitors-1.4.0.jar:/home/jenkins/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar:/home/jenkins/.m2/repository/org/ops4j/pax/exam/pax-exam-link-mvn/2.6.0/pax-exam-link-mvn-2.6.0.jar:/home/jenkins/.m2/repository/org/ops4j/pax/runner/pax-runner-no-jcl/1.8.6/pax-runner-no-jcl-1.8.6.jar:/home/jenkins/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/jenkins/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/jenkins/.m2/repository/javax/cache/cache-api/1.1.1/cache-api-1.1.1.jar:/home/jenkins/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/jenkins/.m2/repository/org/mockito/mockito-core/2.19.0/mockito-core-2.19.0.jar:/home/jenkins/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar:/home/jenkins/.m2/repository/org/powermock/powermock-api-mockito2/2.0.2/powermock-api-mockito2-2.0.2.jar:/home/jenkins/.m2/repository/org/powermock/powermock-api-support/2.0.2/powermock-api-support-2.0.2.jar:/home/jenkins/.m2/repository/org/powermock/powermock-reflect/2.0.2/powermock-reflect-2.0.2.jar:/home/jenkins/.m2/repository/org/powermock/powermock-core/2.0.2/powermock-core-2.0.2.jar:/home/jenkins/.m2/repository/org/powermock/powermock-module-junit4/2.0.2/powermock-module-junit4-2.0.2.jar:/home/jenkins/.m2/repository/org/powermock/powermock-module-junit4-common/2.0.2/powermock-module-junit4-common-2.0.2.jar:/home/jenkins/.m2/repository/org/reflections/reflections/0.9.10/reflections-0.9.10.jar:/home/jenkins/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar:/home/jenkins/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar:/home/jenkins/.m2/repository/org/openjdk/jmh/jmh-core/1.21/jmh-core-1.21.jar:/home/jenkins/.m2/repository/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar:/home/jenkins/.m2/repository/org/apache/commons/commons-math3/3.2/commons-math3-3.2.jar:/home/jenkins/.m2/repository/org/openjdk/jmh/jmh-generator-annprocess/1.21/jmh-generator-annprocess-1.21.jar:/home/jenkins/.m2/repository/com/google/code/findbugs/annotations/3.0.0/annotations-3.0.0.jar:/home/jenkins/.m2/repository/net/bytebuddy/byte-buddy/1.8.17/byte-buddy-1.8.17.jar:/home/jenkins/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/home/jenkins/.m2/repository/net/bytebuddy/byte-buddy-agent/1.8.17/byte-buddy-agent-1.8.17.jar:/home/jenkins/.m2/repository/nl/jqno/equalsverifier/equalsverifier/1.7.8/equalsverifier-1.7.8.jar:
                          java.class.version=55.0
                          java.home=/usr/share/jdks/amazon-corretto-11.0.2.9.3-linux-x64
                          java.io.tmpdir=/tmp
                          java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
                          java.net.preferIPv4Stack=true
                          java.runtime.name=OpenJDK Runtime Environment
                          java.runtime.version=11.0.2+9-LTS
                          java.specification.name=Java Platform API Specification
                          java.specification.vendor=Oracle Corporation
                          java.specification.version=11
                          java.vendor=Amazon.com Inc.
                          java.vendor.url=https://aws.amazon.com/corretto/
                          java.vendor.url.bug=https://github.com/corretto/corretto-11/issues/
                          java.vendor.version=Corretto-11.0.2.9.3
                          java.version=11.0.2
                          java.version.date=2019-01-15
                          java.vm.args=-Xms4g -Xmx4g -XX:MaxPermSize=2048m --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-exports=java.xml/jdk.xml.internal=ALL-UNNAMED --illegal-access=warn -Dhazelcast.phone.home.enabled=false -Dhazelcast.test.use.network=false -Dlog4j.skipJansi=true -verbose:gc -Xloggc:/home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-CorrettoJDK11/test_gc.log 
                          java.vm.compressedOopsMode=Zero based
                          java.vm.info=mixed mode
                          java.vm.name=OpenJDK 64-Bit Server VM
                          java.vm.specification.name=Java Virtual Machine Specification
                          java.vm.specification.vendor=Oracle Corporation
                          java.vm.specification.version=11
                          java.vm.vendor=Amazon.com Inc.
                          java.vm.version=11.0.2+9-LTS
                          javax.cache.Cache=com.hazelcast.cache.ICache
                          javax.cache.Cache.Entry=com.hazelcast.cache.impl.CacheEntry
                          javax.cache.annotation.CacheInvocationContext=javax.cache.annotation.impl.cdi.CdiCacheKeyInvocationContextImpl
                          javax.management.builder.initial=com.hazelcast.cache.impl.TCKMBeanServerBuilder
                          os.arch=amd64
                          os.name=Linux
                          os.version=3.10.0-693.11.1.el7.x86_64
                          sun.arch.data.model=64
                          sun.boot.library.path=/usr/share/jdks/amazon-corretto-11.0.2.9.3-linux-x64/lib
                          sun.cpu.endian=little
                          sun.cpu.isalist=
                          sun.io.unicode.encoding=UnicodeLittle
                          sun.java.command=/home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-CorrettoJDK11/hazelcast/hazelcast/target/surefire/surefirebooter6325235523635167189.jar /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-CorrettoJDK11/hazelcast/hazelcast/target/surefire 2020-01-01T06-15-30_840-jvmRun1 surefire9333217144413977951tmp surefire_014090533673874019532tmp
                          sun.java.launcher=SUN_STANDARD
                          sun.jnu.encoding=ANSI_X3.4-1968
                          sun.management.compiler=HotSpot 64-Bit Tiered Compilers
                          sun.os.patch.level=unknown]
01-01-2020 06:36:23 1577860583749 ConfigProperties[
                          hazelcast.diagnostics.enabled=true
                          hazelcast.diagnostics.max.rolled.file.count=3
                          hazelcast.diagnostics.max.rolled.file.size.mb=0.2
                          hazelcast.diagnostics.metrics.period.seconds=1
                          hazelcast.graceful.shutdown.max.wait=120
                          hazelcast.partition.backup.sync.interval=1
                          hazelcast.wait.seconds.before.join=0]
' didn't contain expected 'Metric['
at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertContains(HazelcastTestSupport.java:960)
	at com.hazelcast.internal.diagnostics.DiagnosticsLogTest$1.run(DiagnosticsLogTest.java:87)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.internal.diagnostics.DiagnosticsLogTest.testLogFileContent(DiagnosticsLogTest.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by tkountis** [comment] 2020-01-02 16:24
I can't reproduce this locally, but what I find interesting is that the tests have a JVM crash (from a known issue) which was not reported.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0f7f986351, pid=391, tid=274248
#
# JRE version: OpenJDK Runtime Environment (11.0.2+9) (build 11.0.2+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM (11.0.2+9-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x5d9351]  ClassLoaderData::loader_name_and_id() const+0x1
#
# Core dump will be written. Default location: /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-CorrettoJDK11/hazelcast/hazelcast/core.391
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  S U M M A R Y ------------

Command Line: -Xms4g -Xmx4g -XX:MaxPermSize=2048m --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-exports=java.xml/jdk.xml.internal=ALL-UNNAMED --illegal-access=warn -Dhazelcast.phone.home.enabled=false -Dhazelcast.test.use.network=false -Dlog4j.skipJansi=true -verbose:gc -Xloggc:/home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-CorrettoJDK11/test_gc.log /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-CorrettoJDK11/hazelcast/hazelcast/target/surefire/surefirebooter6325235523635167189.jar /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-CorrettoJDK11/hazelcast/hazelcast/target/surefire 2020-01-01T06-15-30_840-jvmRun1 surefire9333217144413977951tmp surefire_014090533673874019532tmp

Host: Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz, 72 cores, 377G, Ubuntu 18.04.3 LTS
Time: Wed Jan  1 06:37:14 2020 UTC elapsed time: 1303 seconds (0d 0h 21m 43s)

---------------  T H R E A D  ---------------

Current thread (0x00007f06f80d7000):  JavaThread "hz.festive_cori.partition-operation.thread-43" daemon [_thread_in_vm, id=274248, stack(0x00007f0a0f6f7000,0x00007f0a0f7f8000)]

Stack: [0x00007f0a0f6f7000,0x00007f0a0f7f8000],  sp=0x00007f0a0f7f53d0,  free space=1016k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x5d9351]  ClassLoaderData::loader_name_and_id() const+0x1
V  [libjvm.so+0xd82ef5]  SystemDictionary::check_constraints(unsigned int, InstanceKlass*, Handle, bool, Thread*)+0x115
V  [libjvm.so+0xd8322b]  SystemDictionary::define_instance_class(InstanceKlass*, Thread*)+0xdb
V  [libjvm.so+0xd83bcc]  SystemDictionary::resolve_from_stream(Symbol*, Handle, Handle, ClassFileStream*, Thread*)+0x19c
V  [libjvm.so+0x9332a0]  jvm_define_class_common(JNIEnv_*, char const*, _jobject*, signed char const*, int, _jobject*, char const*, Thread*)+0x1f0
V  [libjvm.so+0x933503]  JVM_DefineClassWithSource+0x83
C  [libjava.so+0xe792]  Java_java_lang_ClassLoader_defineClass1+0x1c2
J 820  java.lang.ClassLoader.defineClass1(Ljava/lang/ClassLoader;Ljava/lang/String;[BIILjava/security/ProtectionDomain;Ljava/lang/String;)Ljava/lang/Class; java.base@11.0.2 (0 bytes) @ 0x00007f0f685fd77d [0x00007f0f685fd640+0x000000000000013d]
J 34775 c1 java.lang.ClassLoader.defineClass(Ljava/lang/String;[BIILjava/security/ProtectionDomain;)Ljava/lang/Class; java.base@11.0.2 (43 bytes) @ 0x00007f0f61d8227c [0x00007f0f61d81f20+0x000000000000035c]
J 36284 c1 com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(Ljava/lang/String;[B)Ljava/lang/Class; (36 bytes) @ 0x00007f0f6227da6c [0x00007f0f6227d980+0x00000000000000ec]
J 36204 c2 com.hazelcast.internal.usercodedeployment.UserCodeDeploymentClassLoader.loadClass(Ljava/lang/String;Z)Ljava/lang/Class; (73 bytes) @ 0x00007f0f6a9b6c98 [0x00007f0f6a9b11c0+0x0000000000005ad8]
J 5876 c2 java.lang.ClassLoader.loadClass(Ljava/lang/String;)Ljava/lang/Class; java.base@11.0.2 (7 bytes) @ 0x00007f0f68d3ce60 [0x00007f0f68d3cde0+0x0000000000000080]
J 35946 c2 java.io.ObjectInputStream.readObject0(Z)Ljava/lang/Object; java.base@11.0.2 (566 bytes) @ 0x00007f0f6a8dfd88 [0x00007f0f6a8dc7c0+0x00000000000035c8]
J 36192 c2 java.io.ObjectInputStream.readObject()Ljava/lang/Object; java.base@11.0.2 (134 bytes) @ 0x00007f0f68bc5ccc [0x00007f0f68bc5c80+0x000000000000004c]
J 36194 c2 com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(Lcom/hazelcast/nio/ObjectDataInput;)Ljava/lang/Object; (37 bytes) @ 0x00007f0f6921b354 [0x00007f0f69219f00+0x0000000000001454]
J 34151 c2 com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(Lcom/hazelcast/nio/ObjectDataInput;)Ljava/lang/Object; (75 bytes) @ 0x00007f0f69c760c8 [0x00007f0f69c75fe0+0x00000000000000e8]
J 14257 c2 com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject()Ljava/lang/Object; (11 bytes) @ 0x00007f0f693e160c [0x00007f0f693e15c0+0x000000000000004c]
j  com.hazelcast.map.impl.operation.EntryBackupOperation.readInternal(Lcom/hazelcast/nio/ObjectDataInput;)V+7
```

issue is related to an [JDK bug](https://bugs.openjdk.java.net/browse/JDK-8212937), fixed [here](https://bugs.openjdk.java.net/browse/JDK-8214528)
Can we upgrade the OpenJDK based builds to >11.0.3

We have also seen this before, [here](https://github.com/hazelcast/hazelcast/issues/14319)

**Comment by Holmistr** [comment] 2020-01-03 09:17
As @lazerion mentioned, this is the same issue as linked. I will update the JDK version in our builds to fix it.

**Comment by tkountis** [comment] 2020-01-03 10:56
Thanks @Holmistr, you might want to look into why this was not reported, maybe we need to modify that failure-string matching on Jenkins.

**Comment by tkountis** [comment] 2020-01-06 14:16
I don't see anything wrong with the test, other than the JVM crash which happens around the same time (minute). I don't know if the crash might have influenced the test somehow, but from a look at the test and the diagnostics writer, I didn't identify any reason for this failure. 
I am suggesting to close this for now, once we fix the root cause for the crash, and see if it happens again.

**Comment by mmedenjak** [comment] 2020-01-09 13:17
I managed to reproduce it once after running for hours on a corretto build - http://jenkins.hazelcast.com/job/matko-Hazelcast-3.x-CorrettoJDK11.

I see that a log file containing all of the static diagnostic plugin data and the metrics data is more than 200kb. This means, we roll over as soon as we print out all of the metrics data. As we roll over, we print out just the static plugin data before waiting for a second for the metrics plugin to print out metrics data again.

If the assertion checks the file at just the right times, it can see only the static plugin data, since we constantly roll over the files as soon as we print out the metrics.

The potential solution is simply increasing the limit for rolling over the files so we leave room for several seconds of metrics data before creating a new diagnostics file. If the test fails with this too, we'll see if there's another root cause.

**Closed** 2020-01-10 08:54 UTC
Labels: Priority: Low, Source: Internal, Team: Core, Type: Test-Failure
