### ISSUE TITLE
SqlErrorClientTest.testExecutionError_fromSecondMember

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#17504] opened 2020-09-07 10:08 UTC
The `com.hazelcast.sql.SqlErrorClientTest.testExecutionError_fromSecondMember[smartRouting:false]` failed on PR builder (branch `4.1-BETA-1`).
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2256/

**Stacktrace**
```
java.lang.NullPointerException
	at com.hazelcast.sql.SqlErrorAbstractTest.checkExecutionError(SqlErrorAbstractTest.java:115)
	at com.hazelcast.sql.SqlErrorClientTest.testExecutionError_fromSecondMember(SqlErrorClientTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by devozerov** [comment] 2020-09-14 12:55
This test checks for a specific error message. Somehow in this run, the error message was `null`. It is impossible in the normal run. 

I suppose that there was a long GC pause that caused the client member to timeout, hence leading to some other exception, other than expected. This is the only sensible explanation I have at the moment.

I am in doubt about how to proceed with the failure, given that Jenkins logs no longer exist, so we cannot prove or disprove my idea. Can we close it for now, and re-open if it happens again? At the very least we will have logs.

**Comment by mmedenjak** [comment] 2020-09-14 15:23
I've kicked off a jenkins build which will run it several hundreds of times (http://jenkins.hazelcast.com/job/matko-Hazelcast-pr-builder/). If it fails, we get the logs. If it doesn't fail, you may add some additional logging or improve the test based on your hunch and we can close and wait for the next failure.

If the test doesn't fail and you don't know how to improve it, we'll just close it until the next failure, as you proposed :)

**Comment by kwart** [comment] 2020-09-14 15:35
The logs from the reported build are available in the S3: https://console.aws.amazon.com/s3/object/j-artifacts/Hazelcast-pr-builder/2256/Hazelcast-pr-builder-2256.zip?region=us-east-1

Attaching the test log itself - [com.hazelcast.sql.SqlErrorClientTest-output.txt](https://github.com/hazelcast/hazelcast/files/5219484/com.hazelcast.sql.SqlErrorClientTest-output.txt)

**Comment by devozerov** [comment] 2020-09-15 05:55
Yes, this appears to be a kind of temporal hiccup that caused the client to close the connection (see below). Note that the test uses a standard instance factory. So if this specific test may fail this way, then it is likely that most client-related tests are similarly affected.
 
```
14:27:44,395  WARN |testMemberDisconnect_execute[smartRouting:true]| - [TcpClientConnection] pool-78-thread-1 - hz.client_33 [dev] [4.1-BETA-1-SNAPSHOT] MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2020-09-05 14:27:44.389, lastWriteTime=2020-09-05 14:27:44.390, closedTime=2020-09-05 14:27:44.395, connected server version=4.1-BETA-1-SNAPSHOT}} closed. Reason: com.hazelcast.spi.exception.TargetDisconnectedException[Mocked Remote socket closed]
com.hazelcast.spi.exception.TargetDisconnectedException: Mocked Remote socket closed
	at com.hazelcast.client.test.TestClientRegistry$MockedTcpClientConnection$4.run(TestClientRegistry.java:316) [hazelcast-4.1-BETA-1-SNAPSHOT-tests.jar:4.1-BETA-1-SNAPSHOT]
	at com.hazelcast.client.test.TwoWayBlockableExecutor$BlockableRunnable.run(TwoWayBlockableExecutor.java:97) [hazelcast-4.1-BETA-1-SNAPSHOT-tests.jar:4.1-BETA-1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

**Comment by sancar** [comment] 2020-09-15 07:18
@devozerov I have also take a look at the logs. I think the socket disconnection in `testMemberDisconnect_execute` test is expected. Because we can see that a related member is shutting down a couple of lines above 

```
14:27:44,393  INFO |testMemberDisconnect_execute[smartRouting:true]| - [LifecycleService] Thread-386 - [127.0.0.1]:5701 [dev] [4.1-BETA-1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
14:27:44,393  INFO |testMemberDisconnect_execute[smartRouting:true]| - [MigrationManager] hz.blissful_cohen.cached.thread-3 - [127.0.0.1]:5701 [dev] [4.1-BETA-1-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5701 - 5e54c4d9-0a72-4588-9d2c-fc6b69299925 this is handled
14:27:44,393  INFO |testMemberDisconnect_execute[smartRouting:true]| - [Node] Thread-386 - [127.0.0.1]:5701 [dev] [4.1-BETA-1-SNAPSHOT] Shutting down connection manager...
14:27:44,395  INFO |testMemberDisconnect_execute[smartRouting:true]| - [MockServer] Thread-386 - [127.0.0.1]:5701 [dev] [4.1-BETA-1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:40001, connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}
14:27:44,395  INFO |testMemberDisconnect_execute[smartRouting:true]| - [Node] Thread-386 - [127.0.0.1]:5701 [dev] [4.1-BETA-1-SNAPSHOT] Shutting down node engine...
14:27:44,395  WARN |testMemberDisconnect_execute[smartRouting:true]| - [TcpClientConnection] pool-78-thread-1 - hz.client_33 [dev] [4.1-BETA-1-SNAPSHOT] MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2020-09-05 14:27:44.389, lastWriteTime=2020-09-05 14:27:44.390, closedTime=2020-09-05 14:27:44.395, connected server version=4.1-BETA-1-SNAPSHOT}} closed. Reason: com.hazelcast.spi.exception.TargetDisconnectedException[Mocked Remote socket closed]
com.hazelcast.spi.exception.TargetDisconnectedException: Mocked Remote socket closed
	at com.hazelcast.client.test.TestClientRegistry$MockedTcpClientConnection$4.run(TestClientRegistry.java:316) [hazelcast-4.1-BETA-1-SNAPSHOT-tests.jar:4.1-BETA-1-SNAPSHOT]
	at com.hazelcast.client.test.TwoWayBlockableExecutor$BlockableRunnable.run(TwoWayBlockableExecutor.java:97) [hazelcast-4.1-BETA-1-SNAPSHOT-tests.jar:4.1-BETA-1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```


On the other hand, the logs of the failing test do not show any disconnection. The last log before failure is as follows:

```
14:27:33,395  INFO |testExecutionError_fromSecondMember[smartRouting:false]| - [ClientClusterService] hz.client_4.event-291 - hz.client_4 [dev] [4.1-BETA-1-SNAPSHOT] 

Members [2] {
	Member [127.0.0.1]:5701 - 12d53854-5340-4f23-a287-993d3e96a347
	Member [127.0.0.1]:5702 - 277a8753-be28-48e4-bcc8-83d79113a820
}

14:27:33,396  INFO |testExecutionError_fromSecondMember[smartRouting:false]| - [PartitionStateManager] testExecutionError_fromSecondMember - [127.0.0.1]:5701 [dev] [4.1-BETA-1-SNAPSHOT] Initializing cluster partition table arrangement...
```

**Comment by mmedenjak** [comment] 2020-09-15 09:40
Ran the test 10k times on the lab, no failures. I suggest we improve the test, if possible, and close the issue. WDYT @devozerov ?

**Comment by mmedenjak** [comment] 2020-09-15 09:42
Also, have you considered using `HazelcastTestSupport#smallInstanceConfig` in SQL tests? It uses less resources for an instance in case it's not needed for a particular test.

**Comment by devozerov** [comment] 2020-09-16 07:34
@sancar thanks for the comment, I misread the logs (thought that it was for only one test, not for the test class). 

Still, the root cause is not known. The test is question checks a deterministic condition - how a custom error is propagated from the member participating in the query execution to the client. The only reason why it may fail that comes to my mind is some sort of timeout (e.g. due to GC), or broken connection, etc. From the logs, we do not have clear evidence that this is the case. At the same time, we cannot make the test fail after multiple runs, either locally, or on Jenkins.

I create a PR that uses `smallInstanceConfig` [1] as @mmedenjak suggested. This is just a random attempt to fix an unknown problem, but I do not see what else can be done at the moment. Let's merge it and see if the test fails again. If yes, we will try to introduce artificial timeouts at different execution stages, in the hope to reproduce it. It will be a time-consuming activity.

[1] https://github.com/hazelcast/hazelcast/pull/17553

**Closed** 2020-09-16 08:44 UTC
Labels: Module: SQL, Source: Internal, Team: Core, Type: Test-Failure
