### ISSUE TITLE
partitionService is not updated when memberAdded or PostJoin.

### ISSUE THREAD

**Issue by wenerme** [hazelcast/hazelcast#5884] opened 2015-08-07 06:45 UTC
In memberAdded or PostJoin, the partition info is not updated, so I can not rely on these callback.

I implement a new service by follow the spi, what I want to do is when new node added, I will rebackup the data, how can I achieve this ?

**Comment by pveentjer** [comment] 2015-08-07 07:50
Which HZ version are you using?

**Comment by wenerme** [comment] 2015-08-07 07:51
3.5

**Comment by mdogan** [comment] 2015-11-02 09:17
@wenerme: Partitioning info is updated whenever needed lazily after cluster membership changes. It means, partitions are migrated one by one and their replicates. If you have partitioned data, you should implement `MigrationAwareService`.

**Comment by gurbuzali** [comment] 2016-08-01 12:11
I'm closing this issue, the solution to the issue is in @mdogan 's response.

**Closed by gurbuzali** 2016-08-01 12:11 UTC
Labels: Team: Core
