### ISSUE TITLE
com.hazelcast.internal.cluster.impl.ClusterRollingRestartTest got stuck [HZ-2366]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24274] opened 2023-04-14 06:35 UTC
_master_ (commit f7242148a89972cb339dbf927502859f3c2220dd)

Failed on OpenJDK 19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts/34/console

<details><summary>Stacktrace:</summary>

```
19:02:35 [INFO] Running com.hazelcast.internal.cluster.impl.ClusterRollingRestartTest
23:12:49 Build timed out (after 300 minutes). Marking the build as failed.
23:12:49 Stopping Docker container after build completion
23:12:52 Build was aborted
```

</details>

S3 Bucket for stdout: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK-sts/34/

**Comment by ramizdundar** [comment] 2023-05-03 11:22
There are 2 issues in this test. First, 5702 has communication problems with other nodes. This causes a problem while finishing migrations. And since migrations are still on progress we can't lock the cluster. And this fails the test.

Secondly, termination of the 5702 got stuck. This means that since there is no timeout for `HazelcastTestSupport.shutdownNodeFactory()`, the whole jenkins job timed out.

I couldn't reproduce the issue yet. But, I think I also wasted my time because this is also possibly mockito issue. There is a mockito method call in the thread dump. I realized this too late. I also post my findings here in case if we encounter this issue after we fix mockito issues.

<details>
<summary>Part of thread dump</summary>

```
"hz.ClusterRollingRestartTest_elegant_hellman.partition-operation.thread-7" 
	java.lang.Thread.State: WAITING, on lock=java.util.concurrent.locks.ReentrantLock$NonfairSync@52f58260, cpu=4249691 nsecs, usr=0 nsecs, blocked=0 msecs, waited=126103 msecs
		at java.base@19.0.1/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:218)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:218)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:218)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:218)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:218)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:218)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:218)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:218)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:218)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:218)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at app//com.hazelcast.instance.impl.Node.getNodeExtension(Node.java:764)
		at app//com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.applyCompletedMigrations(InternalPartitionServiceImpl.java:867)
		at app//com.hazelcast.internal.partition.operation.BaseMigrationOperation.applyCompletedMigrations(BaseMigrationOperation.java:117)
		at app//com.hazelcast.internal.partition.operation.BaseMigrationOperation.beforeRun(BaseMigrationOperation.java:94)
		at app//com.hazelcast.internal.partition.operation.MigrationOperation.beforeRun(MigrationOperation.java:57)
		at app//com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:269)
		at app//com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:502)
		at app//com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:202)
		at app//com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:142)
		at app//com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.loop(OperationThread.java:134)
		at app//com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:115)
		at app//com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
```
</details>

**Comment by ramizdundar** [comment] 2023-05-03 11:23
Bumping to 5.4

**Comment by ramizdundar** [comment] 2023-06-12 11:56
It seems after mockito upgrade this test hasn't failed since: https://github.com/hazelcast/hazelcast/pull/24619. Closing for now.

**Closed by ramizdundar** 2023-06-12 11:56 UTC
Labels: Team: Core, Type: Test-Failure, Source: Internal, to-jira
