### ISSUE TITLE
com.hazelcast.core.OperationTimeoutException: MapSizeOperation invocation failed to complete due to operation-heartbeat-timeout. 

### ISSUE THREAD

**Issue by SaketSureshPandit** [hazelcast/hazelcast#9697] opened 2017-01-19 12:36 UTC
Hi,
We are using Hazelcast 3.7.4 in embedded version in our application which is deployed on 8 JVM,s across 4 physical servers(2 instances on each server). When the application was deployed everything was fine and we did not see any problem. On app start up the logic will cache the values to the Hazelcast IMAP. After this there is no write to the cache again and all the other operations only read from this cache. 
Last time when we had to back out there were hung threads as we had updated the cache and we could see that when this was being replicated in the cluster there were hung threads. But that was the last time. 
This time there was no write operation on the cache after the onetime load on app start up. 
This is the 3rd version of Hazelcast (3.6.1, 3.6.3, 3.7.4) that we had to back out from production.
We need support on this issue as it is impacting production.

We started receiving the below exception in production continuously and then the CPU usage shooted to 100% up after this exceptions started showing up. The server CPU was being utilized at 100% for quite sometime which does not happen usually. We had to revert back Hazelcast implementation again.

```
com.hazelcast.core.OperationTimeoutException: MapSizeOperation invocation failed to complete due to operation-heartbeat-timeout. Current time:
 2017-01-18 15:02:56.396. Total elapsed time: 121000 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2017-01-18 15:
02:43.810. Invocation{op=com.hazelcast.map.impl.operation.MapSizeOperation{serviceName='hz:impl:mapService', identityHash=1386528744, partitio
nId=9, replicaIndex=0, callId=0, invocationTime=1484773255395 (2017-01-18 15:00:55.395), waitTimeout=-1, callTimeout=60000, name=VALUE_M
AP}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1484773255396, firstInvocationTime='2017-
01-18 15:00:55.396', lastHeartbeatMillis=0, lastHeartbeatTime='1969-12-31 18:00:00.000', target=[SERVER2]:5701, pendingResponse=
{VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=12, /111.111.111.111:5700->/111.111.111.112:34519, endpoint=[SERVER2]
:5701, alive=true, type=MEMBER]}
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:150)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:98)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
        at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:139)
        at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:70)
        at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:359)
        at com.hazelcast.map.impl.proxy.MapProxySupport.size(MapProxySupport.java:630)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.size(MapProxyImpl.java:82)
```

**Comment by jerrinot** [comment] 2017-01-19 12:56
hi @SaketSureshPandit,

it would be good to know what's causing the CPU utilization. Do you have GC logs? That's the first thing I would look at.

**Comment by SaketSureshPandit** [comment] 2017-01-20 07:44
sorry @jerrinot i do not have any thread or heap dumps as the team did not get those before restarting the servers.
But in this issue, above, i did mentioned that there was no update to the cache, which is not correct.
There was update to the iMAP after an update on the front end so as to reflect the changes in the cache.
Immediately after this update the CPU utilization went high and reached 100% for almost 10-12 mins after which team decided to restart the servers to avoid any further impact. This decision was taken because in past when ever the CPU Utilization spiked due to hazelcast exceptions, the servers crashed eventually sending notifications to different teams and created lots of tickets.
Whenever there is update 

There are no changes to configuration and it is same as we had earlier with versions.

`//new config object
		Config cfg = new Config();

		//setting the cache cluster name
		GroupConfig grpCfg = new GroupConfig();
		grpCfg.setName(config.getCacheClusterName());
		cfg.setGroupConfig(grpCfg);		

		MapConfig mapConfig = cfg.getMapConfig("*");
		mapConfig.setMaxIdleSeconds(0);
		mapConfig.setTimeToLiveSeconds(0);
		mapConfig.setEvictionPolicy(EvictionPolicy.LFU);
		mapConfig.getMaxSizeConfig().setMaxSizePolicy(MaxSizePolicy.PER_NODE).setSize(Constants.INT_10000);
		//setting the percentage for eviction
		mapConfig.setEvictionPercentage(Constants.INT_10);
		
		
		//setting the network configuration
		NetworkConfig netCfg = cfg.getNetworkConfig();
		netCfg.setPort(5700).setPortAutoIncrement(true);
		netCfg.setReuseAddress(true);
		netCfg.setPortCount(4);
		
		JoinConfig joinCfg = netCfg.getJoin();
		
		joinCfg.getMulticastConfig().setEnabled(false);
		joinCfg.getTcpIpConfig().setEnabled(true);
		
		if(cacheHostMembers!= null && cacheHostMembers.length()>0){
			StringTokenizer tokens = new StringTokenizer(cacheHostMembers, Constants.STR_COMMA);
			while(tokens.hasMoreTokens()){
				joinCfg.getTcpIpConfig().addMember((String) tokens.nextElement());
			}
		}`

**Comment by mmedenjak** [comment] 2017-07-11 19:26
@SaketSureshPandit It seems like hazelcast became unresponsive after the CPU load became too high. Can you run your app with a java profiler and reproduce the issue so you can see where the CPU time is being spent?

**Comment by magiccrafter** [comment] 2018-01-04 15:51
Same with the latest (3.9.2) version. I will try to reproduce it. Two instances and the error was thrown after calling localKeySet with hz Predicate for first time after the app start. Here is the stack trace:
```
2018-01-04 16:31:20.821  INFO c.h.s.i.o.impl.InvocationMonitor --- [hz.application-cluster.InvocationMonitorThread] : [hostname1]:5701 [application-cluster] [3.9.2] Invocations:1 timeouts:1 backup-timeouts:0
2018-01-04 16:31:20.828 ERROR o.s.i.handler.LoggingHandler --- [task-scheduler-4] : com.hazelcast.core.OperationTimeoutException: QueryPartitionOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2018-01-04 16:31:20.821. Start time: 2018-01-04 16:29:20.663. Total elapsed time: 120159 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2018-01-04 16:31:13.727. Invocation{op=com.hazelcast.map.impl.query.QueryPartitionOperation{serviceName='hz:impl:mapService', identityHash=67251021, partitionId=42, replicaIndex=0, callId=-3622, invocationTime=1515079760667 (2018-01-04 16:29:20.667), waitTimeout=-1, callTimeout=60000, name=timers}, tryCount=250, tryPauseMillis=500, invokeCount=2, callTimeoutMillis=60000, firstInvocationTimeMs=1515079760663, firstInvocationTime='2018-01-04 16:29:20.663', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 01:00:00.000', target=[hostname2]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=1, /a:5701->/b:45172, endpoint=[hostname2]:5701, alive=true, type=MEMBER]}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:164)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:106)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.addResultsOfPredicate(MapQueryEngineImpl.java:194)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.doRunQueryOnPartitionThreads(MapQueryEngineImpl.java:182)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.runQueryOnLocalPartitions(MapQueryEngineImpl.java:116)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.execute(MapQueryEngineImpl.java:89)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.localKeySet(MapProxyImpl.java:700)
	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mmedenjak** [comment] 2018-03-15 12:32
@magiccrafter @SaketSureshPandit these issues happen when an instance is unresponsive and does not return heartbeats. You can mitigate these exceptions by increasing the operation heartbeat timeout:
```
public static final HazelcastProperty OPERATION_CALL_TIMEOUT_MILLIS
            = new HazelcastProperty("hazelcast.operation.call.timeout.millis", 60000, MILLISECONDS);
```
But in the end it would be best if you could determine why your instances were unresponsive in the first place. Is there a long GC? Are there network issues?

**Comment by mmedenjak** [comment] 2018-08-29 06:53
@magiccrafter @SaketSureshPandit any updates on the issue?

**Comment by mmedenjak** [comment] 2018-09-17 06:58
Closing the issue due to non-activity. Please open a new issue when you have more information or when you encounter other problems running Hazelcast.

**Closed by mmedenjak** 2018-09-17 06:58 UTC
Labels: Estimation: S, Module: IMap, Module: Query, Source: Community, Team: Core, Type: Defect
