### ISSUE TITLE
Hazelcast Embedded Cache Expiry Issue

### ISSUE THREAD

**Issue by ysheela** [hazelcast/hazelcast#24200] opened 2023-04-04 22:26 UTC
**Describe the bug**
We are using embedded version of Hazelcast 5.2.1. In our AKS kubernetes production cluster, we are noticing that when a cluster is restarted sometimes there are members with partitions containing entries that are not expiring at all even though we have  both eviction and expiry policies defined on the maps.

Noticing the behavior is not the same across all maps. It is happening only for certain paritions.

Our current eviction policy is: MaxSizePolicy.PER_NODE and Max Size is defined to be 10000. And expiry policy is with ttl as 10 minutes and maxIdleSeconds as 5 minutes.

We also added PER ENTRY expiry settings as well and the behavior seems similar.

Can you please advise if anyone has been encountering  issues with expiry?

We would like to know how to ensure that all the entries are removed from the map once expired?

Greatly appreciate help on this

**Expected behavior**
We were hoping that all entries are expired based on the configuration settings and TTL settings defined at map or per entry level,

**Comment by ahmetmircik** [comment] 2023-04-05 06:03
@ysheela can you please create a small reproducer for this, better without k8?

**Comment by ysheela** [comment] 2023-04-05 18:46
Interestingly the issue does not happen in our QA as well as preview environments. It is happening in productions and not for all tenants. Initially when found, we saw 4 tenants having this issue so we went ahead and added TTL per Entry. After deployment of the change and with additional logs noticing that there is one tenant where we are not expiring the entries at all.
![image](https://user-images.githubusercontent.com/1878095/230175957-d63e0620-20ba-4a3a-9ac9-7feacbd3957d.png)

**Comment by ahmetmircik** [comment] 2023-04-06 06:13
A possible reason can be making use of locking. Transactions or explicit IMap.lock calls can lock keys and locked keys cannot be removed even that are expired. Can this be a case for you?

**Comment by ysheela** [comment] 2023-04-06 13:56
@ahmetmircik : We are are using any locks. We add an entry into the map using put method  with TTL per entry.
`   map.put( key,     value,          ttlInSecs,          TimeUnit.SECONDS);`

When the original issue was reported by a customer in production, noticed that there were atleast 4 tenants whose owned entry is never changing and is constant even though they have no traffic. It indicated entries are not expiring.

That is when we added TTL per entry, after deploying this change we are noticing a tenant on one instance of service is holding on to an entry. 
We are not using any explicit locks in our code. So is there any other way the locks could be added and if so how to detect and remove them so that they expire

**Comment by ahmetmircik** [comment] 2023-04-06 14:17
Normally, locked key count can be seen with `getLockedEntryCount` of returned object from `IMap#getLocalMapStats` call, but if you have no locks, cause could be something else.

In this case, best option is to have a reproduce, otherwise all hazelcast config, logs, api calls, how you manage clusters, scale-up/down situations etc is needed to have a possible reasoning since no such known issue exists currently.

**Comment by ysheela** [comment] 2023-04-06 16:52
@ahmetmircik : We do not explicitly lock entries, but will go ahead and add the metric to send to prometheus.
One clarification, how accurate are the metrics from IMap#getLocalMapStats.
Noticing that there is owned entry count which is not expiring at all for one of the tenants without high traffic

**Comment by ahmetmircik** [comment] 2023-04-10 16:39
You can expect stats are up to date, each call to IMap#getLocalMapStats will create latest state of it regardless of the traffic.

**Comment by ysheela** [comment] 2023-04-10 21:18
@ahmetmircik : And also we are not explicitly locking entries, does hazelcast lock entries even if we do not?

**Comment by ahmetmircik** [comment] 2023-04-11 07:28
No it doesn't lock entries. 
Locking is one possible reason of the issue, but if you don't make use of locking, it is eliminated and reason of the issue can be something else. Maybe you can create an isolated project to replicate your use case and can try to reproduce the issue.

**Comment by ysheela** [comment] 2023-04-11 12:37
@ahmetmircik : Unfortunately this issue does not appear locally or in our QA environment, It seems to be happening in production where we have 12 instances of services and the owned entry count for a particular tenant and that too on one instance of service was not going down to zero when the traffic is completely stopped.
We were hoping the entry count  to expire even though we added the expiry configuration for the map and also modified to add TTL per entry.

Here is the screenshot of the owned entry count on one instance of service, as you can see the owned entry count is dropping to zero but is not based on the TTL defined and is happening after several hours in some instances. We also stopped traffic coming from the tenant , hoping that should bring down the entries but it was holding on to the entry.

![image](https://user-images.githubusercontent.com/1878095/231162780-93045ff9-2500-45cc-a92e-aa972b90e957.png)

Any advice is greatly appreciated. Also please let us know if it is possible for you to join a call so that we can share and show what is happening in this case since it is not reproducible locally.

**Comment by ysheela** [comment] 2023-04-11 13:48
@ahmetmircik :  Also please note we did turn on the additional logging and noticed that Expiry is happening on that instance of the server but as mentioned earlier, it is not at the same frequency as defined in the expiry configuration for the Map and TTL per entry.

We also planning to add the Entry, Map and Event Listeners to see if there is anything else that can be inferred from the logs. Do not see any exceptions or errors in the logs. Is there any other debug trace that can be added to help in narrowing down the issue.

**Comment by ahmetmircik** [comment] 2023-04-11 14:06
Then issue seems the frequency of expiration. For this case, i will copy one of my previous answer for another issue here. Hope it helps.

Expiration can occur in two ways:
- By explicitly calling IMap#get on key (in this case, entry is immediately removed from IMap)
- With the help of a background sweeper task (in this case, entries will be removed gradually from
IMap, no need an explicit touch)

For the 2nd case, you can tune expiration frequency with some properties. These are the most aggressive values for them, for an example:
- Run cleanup round in every second. Default is 5 seconds.
  `System.setProperty("hazelcast.internal.map.expiration.task.period.seconds", "1");`
- Scan all entries of map in every round to find expirables.
  `System.setProperty("hazelcast.internal.map.expiration.cleanup.percentage", "100");`
- Set cleanup operation count to partition count. 271 is current default. 
  This means send one cleanup operation to each partition in every round. 
  Otherwise it will pick a small value which doesn't hurt the system and scans partitions gradually.
  `System.setProperty("hazelcast.internal.map.expiration.cleanup.operation.count", "271");`

**Comment by ahmetmircik** [comment] 2023-04-13 11:48
@ysheela if everything is ok, can we close this issue?

**Comment by ahmetmircik** [comment] 2023-04-25 09:56
any update @ysheela?

**Comment by ysheela** [comment] 2023-06-02 14:17
Sorry for the delay, yes the issue has been resolved. We can close this issue.

**Closed** 2023-06-02 14:26 UTC
Labels: Type: Defect, Source: Community
