### ISSUE TITLE
queue.take() method throws wrong exception when thread is interrupted

### ISSUE THREAD

**Issue by ashutosh0205** [hazelcast/hazelcast#4473] opened 2015-01-22 14:58 UTC
when a thread is waiting for an element to be available in queue after calling queue.take() method and if some other thread interrupt this waiting thread than this method throws HazlecastException instead of InterruptedException.

**Comment by gurbuzali** [comment] 2015-01-22 19:55
duplicate of https://github.com/hazelcast/hazelcast/issues/4143

**Closed by gurbuzali** 2015-01-22 19:55 UTC
