### ISSUE TITLE
ClientQueryCacheRecreationTest.query_cache_recreates_itself_after_server_restart

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#16328] opened 2019-12-23 08:15 UTC
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5243/testReport/junit/com.hazelcast.client.map.impl.querycache/ClientQueryCacheRecreationTest/query_cache_recreates_itself_after_server_restart/

```
junit.framework.AssertionFailedError: expected:<200> but was:<168>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheRecreationTest$1.run(ClientQueryCacheRecreationTest.java:115)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheRecreationTest.query_cache_recreates_itself_after_server_restart(ClientQueryCacheRecreationTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
Hiccups measured while running test 'query_cache_recreates_itself_after_server_restart(com.hazelcast.client.map.impl.querycache.ClientQueryCacheRecreationTest):'
07:40:20, accumulated pauses: 209 ms, max pause: 67 ms, pauses over 1000 ms: 0
07:40:25, accumulated pauses: 254 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:40:30, accumulated pauses: 132 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:40:35, accumulated pauses: 307 ms, max pause: 19 ms, pauses over 1000 ms: 0
07:40:40, accumulated pauses: 443 ms, max pause: 20 ms, pauses over 1000 ms: 0
07:40:45, accumulated pauses: 316 ms, max pause: 25 ms, pauses over 1000 ms: 0
07:40:50, accumulated pauses: 256 ms, max pause: 19 ms, pauses over 1000 ms: 0
07:40:55, accumulated pauses: 272 ms, max pause: 13 ms, pauses over 1000 ms: 0
07:41:00, accumulated pauses: 273 ms, max pause: 12 ms, pauses over 1000 ms: 0
07:41:05, accumulated pauses: 165 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:41:10, accumulated pauses: 224 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:41:15, accumulated pauses: 253 ms, max pause: 12 ms, pauses over 1000 ms: 0
07:41:20, accumulated pauses: 261 ms, max pause: 20 ms, pauses over 1000 ms: 0
07:41:25, accumulated pauses: 257 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:41:30, accumulated pauses: 189 ms, max pause: 17 ms, pauses over 1000 ms: 0
07:41:35, accumulated pauses: 112 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:41:40, accumulated pauses: 83 ms, max pause: 7 ms, pauses over 1000 ms: 0
07:41:45, accumulated pauses: 121 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:41:50, accumulated pauses: 96 ms, max pause: 6 ms, pauses over 1000 ms: 0
07:41:55, accumulated pauses: 59 ms, max pause: 4 ms, pauses over 1000 ms: 0
07:42:00, accumulated pauses: 118 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:42:05, accumulated pauses: 206 ms, max pause: 8 ms, pauses over 1000 ms: 0
07:42:10, accumulated pauses: 139 ms, max pause: 7 ms, pauses over 1000 ms: 0
07:42:15, accumulated pauses: 71 ms, max pause: 6 ms, pauses over 1000 ms: 0
07:42:20, accumulated pauses: 145 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:42:25, accumulated pauses: 196 ms, max pause: 135 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment] 2020-01-08 10:46
Failed again in PR builder - http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5442/testReport/junit/com.hazelcast.client.map.impl.querycache/ClientQueryCacheRecreationTest/query_cache_recreates_itself_after_server_restart/

@ahmetmircik can we change the test somehow since we know it's a known issue?

**Comment by ahmetmircik** [comment] 2020-01-08 13:40
@mmedenjak please see https://github.com/hazelcast/hazelcast/pull/16438

**Comment by lazerion** [comment] 2020-01-12 15:07
Fails on [Hazelcast-3.x-Windows-OracleJDK8 build 132](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/132/testReport/junit/com.hazelcast.client.map.impl.querycache/ClientQueryCacheRecreationTest/query_cache_recreates_itself_after_server_restart/)
FYI

**Comment by sancar** [comment] 2020-07-03 12:19
Failed again here
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/1321/testReport/junit/com.hazelcast.client.map.impl.querycache/ClientQueryCacheRecreationTest/query_cache_recreates_itself_after_server_restart/

```
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientQueryCacheRecreationTest.query_cache_recreates_itself_after_server_restart:112->HazelcastTestSupport.assertTrueEventually:1344->HazelcastTestSupport.assertTrueEventually:1242->lambda$query_cache_recreates_itself_after_server_restart$0:114 expected:<200> but was:<185>
[INFO] 
[ERROR] Tests run: 27794, Failures: 1, Errors: 0, Skipped: 1001
[INFO] 
```

**Comment by ahmetmircik** [comment] 2020-07-09 12:17
This is a known flaky test and it will be handled in this PR: #16438.
Not much value to keep this issue open, closing it now.

**Comment by mmedenjak** [comment] 2020-07-11 07:38
@ahmetmircik do we know why it is flaky and any other way how to fix it? I prefer not to merge any kind of flaky annotation or way of repeating tests when they fail.

**Comment by ahmetmircik** [comment] 2020-07-13 13:32
@mmedenjak yes it is based on lossy eventing system, this is the root cause. Please see my approach summarized here: https://github.com/hazelcast/hazelcast/pull/16438#issuecomment-573022159

**Comment by mmedenjak** [comment] 2020-09-01 08:03
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2161

**Comment by vbekiaris** [comment] 2020-09-18 06:24
Another failure: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2401/

**Comment by mmedenjak** [comment] 2020-09-18 06:27
Let's ignore the test then, if we know the root cause and we won't fix it unless we improve the eventing system. @ahmetmircik WDYT?

**Comment by ahmetmircik** [comment] 2020-09-18 08:00
we can close the issue but this time, we will lose the chance to see if the issue is getting worse.

**Comment by mmedenjak** [comment] 2020-09-18 08:24
Ok then, but if it keeps getting worse, I'd rather ignore it so we have more green builds.

**Comment by sancar** [comment] 2020-10-05 06:57
Failed again at: @ahmetmircik @mmedenjak 
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2572/testReport/junit/com.hazelcast.client.map.impl.querycache/ClientQueryCacheRecreationTest/query_cache_recreates_itself_after_server_restart/

```
Error Message
expected:<200> but was:<191>
Stacktrace
junit.framework.AssertionFailedError: expected:<200> but was:<191>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheRecreationTest.lambda$query_cache_recreates_itself_after_server_restart$0(ClientQueryCacheRecreationTest.java:114)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1253)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1355)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheRecreationTest.query_cache_recreates_itself_after_server_restart(ClientQueryCacheRecreationTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment] 2020-11-02 16:55
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2854

**Comment by lazerion** [comment] 2020-11-21 07:33
- Similar failure on [Build #102 (Nov 19, 2020 2:15:00 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-OracleJDK8/102/testReport/junit/com.hazelcast.client.map.impl.querycache/ClientQueryCacheRecreationTest/query_cache_recreates_itself_after_server_restart/)
- `Hazelcast-4.maintenance-OracleJDK8`

**Comment by hakanmemisoglu** [comment] 2021-02-18 09:53
After running the tests repeatedly:

There are some warnings which can be observed in the logs:

-  Type A `expectedSequence < foundSequence`:


```
Event lost detected for queryCache=`d0b205c1-e330-4b25-8122-724a98fea9d2`: partitionId=4, expectedSequence=1, foundSequence=9, cacheSize=0
```


- Type B `expectedSequence > foundSequence`:


```
Event lost detected for queryCache=`9e1ef967-6e2d-4fd4-9af0-5b84acd81b58`: partitionId=4, expectedSequence=10, foundSequence=1, cacheSize=100
```

Type A warnings do not cause test failure whereas Type B warnings cause a test failure.
Additionally, the test failures are hard to observe since It requires the tests to run for hours.


I thought the problematic part might be this part in the test: 
https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/test/java/com/hazelcast/client/map/impl/querycache/ClientQueryCacheRecreationTest.java#L101-L106

Events fired up for the last iterations of `map.put()` are processed in the same time or after `internalQueryCache.recreate()` method.

So I have put a `Thread.sleep()` in this method: https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulator.java#L68-L72

It makes Event processor thread to run after `recreate` method which is run in test thread. 
As a result, the issue became easily reproducible in each run. 

I think the problem is event processor cannot differentiate two messages from different sequences from same partition. (??)

There are 2 things that fixed the test so far:
- Change the test block as 
 ```java
        for (int i = 100; i < 200; i++) {
            map.put(i, i);
        }
        
        // ----> Wait here until queryCache.size() == 100

        InternalQueryCache internalQueryCache = (InternalQueryCache) queryCache;
        internalQueryCache.recreate();

```
I will send a PR for this. However, it limits the test conditions. 

- Relax the conditions that event will be applied:

Here, put `return true` before `handleUnexpectedEvent` 
https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/SubscriberAccumulator.java#L77-L101

Obviously, this is wrong thing but it solidifies the cause I came up with.

**Comment by mmedenjak** [comment] 2021-02-18 14:57
Nice analysis and finding @hakanmemisoglu !

**Comment by sancar** [comment] 2021-03-11 08:56
@hakanmemisoglu Is this backported ? I have got a failure in 4.0.z pr builder. 
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4231/testReport/junit/com.hazelcast.client.map.impl.querycache/ClientQueryCacheRecreationTest/query_cache_recreates_itself_after_server_restart/

**Comment by hakanmemisoglu** [comment] 2021-03-11 10:54
@sancar 
Here is the PR for back port: https://github.com/hazelcast/hazelcast/pull/18383

**Comment by mmedenjak** [comment] 2021-04-06 18:10
*ServerQueryCacheRecreationTest.query_cache_recreates_itself_after_server_restart*

```
junit.framework.AssertionFailedError: expected:<300> but was:<292>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:384)
	at com.hazelcast.map.impl.querycache.ServerQueryCacheRecreationTest.lambda$query_cache_recreates_itself_after_server_restart$0(ServerQueryCacheRecreationTest.java:102)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1350)
	at com.hazelcast.map.impl.querycache.ServerQueryCacheRecreationTest.query_cache_recreates_itself_after_server_restart(ServerQueryCacheRecreationTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Closed** 2021-04-14 20:43 UTC
Labels: Module: IMap, Source: Internal, Team: Client, Type: Test-Failure
