### ISSUE TITLE
Hazelcast Cache not deleted in k8s near cache

### ISSUE THREAD

**Issue by dino-lee** [hazelcast/hazelcast#18887] opened 2021-06-11 10:38 UTC
Hello :)
Hazelcast Issue in k8s 
This is my gradle implements
```gradle
 implementation group: 'com.hazelcast', name: 'spring-data-hazelcast', version: '2.4.0'
 implementation group: 'com.hazelcast', name: 'hazelcast-all', version: '4.2'
```

First, Upload all data from MongoDB to the spring data hazelcast repository at Pod Initialize time.
Once Cache Uploaded, data cannot be deleted.
It remains even after deploy restart.
It is used within k8s and uses the Near Cache kubernetes config.

If the Hazelcast Cache method is kubernetes embedded, does the storage exist other than Pod? 
We found that Cache remained even though Pod was all deploy restart.

This is our yaml
svc.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kubectl
  name: hazelcast-service
spec:
  selector:
    app: test-app
  ports:
    - name: hazelcast
      port: 5701
  type: ClusterIP
```

deploy yaml
```yaml
          name: test-app
          ports:
            - name: http
              containerPort: 8080
            - name: multicast
              containerPort: 5701

```

Could you tell me the cause of this issue?

Thanks :)

**Comment by mmedenjak** [comment] 2021-06-15 11:10
@leszko can someone take a look?

**Comment by leszko** [comment] 2021-06-15 12:03
@dino-lee I guess that when the deployment is restarted, then the instances restart one by one, and therefore there is always at least 1 replica running. That is why the data is not lost (deleted). It's actually a feature of Hazelcast, not a bug :)

To have the data removed, you have the following options:
1. Make sure that all replicas at stopped at some point (then no HZ instance is running, so there is no place to store the data)
2. Remove the data "manually"  (from the application code or using a separate job).
3. Use Client-Server topology instead of Embedded, then you can manage your Hazelcast cluster separately

**Comment by dino-lee** [comment] 2021-06-16 01:18
@leszko 
I Understand.
Even if Hazelcast is one when it is deployed, it is shared with the existing data. 

Thanks Reply :)

**Comment by leszko** [comment] 2021-06-16 07:23
Happy to help. Closing the issue, feel free to reopen if needed.

**Closed by leszko** 2021-06-16 07:23 UTC
Labels: Source: Community, Team: Integration, Type: Defect
