### ISSUE TITLE
com.hazelcast.client.TcpClientConnectionTest.testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER] [HZ-4835]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26384] opened 2024-07-29 12:54 UTC
_master_ (commit eb0e0ae793adaaab1f52ab29b7d459b43a4db6a7)

Failed on openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21/28/testReport/junit/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice_0__routingMode_SINGLE_MEMBER_/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.client.TcpClientConnectionTest.lambda$testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice$8(TcpClientConnectionTest.java:245)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1216)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1321)
	at com.hazelcast.client.TcpClientConnectionTest.testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice(TcpClientConnectionTest.java:242)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-21/28/

**Comment by Patras3** [comment] 2024-07-30 13:10
Failed again on _master_ with Windows - OracleJDK21: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK21/14/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice_0__routingMode_SINGLE_MEMBER_/

**Comment by Patras3** [comment] 2024-08-01 10:43
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: master
Builds between : 2024-07-08 20:05 - 2024-07-31 18:11
Jobs: 25, Runs: 93, Passed: 60, Failed: 33, Skipped: 0, Fail Ratio: 35.48%
Run on:
+----------------------------------------------------+
| JDK          | PASSED | FAILED | SKIPPED |  RATIO  |
+----------------------------------------------------+
| zing-17      |   0    |   3    |    0    | 100.00% |
| openj9-21    |   1    |   2    |    0    |  66.67% |
| zing-21      |   2    |   2    |    0    |  50.00% |
| oracle-17    |   10   |   7    |    0    |  41.18% |
| unknown      |   20   |   13   |    0    |  39.39% |
| openj9-17    |   2    |   1    |    0    |  33.33% |
| microsoft-17 |   3    |   1    |    0    |  25.00% |
| corretto-21  |   3    |   1    |    0    |  25.00% |
| redhat-17    |   3    |   1    |    0    |  25.00% |
| openjdk-21   |   3    |   1    |    0    |  25.00% |
| openjdk-17   |   3    |   1    |    0    |  25.00% |
| corretto-17  |   3    |   0    |    0    |   0.00% |
| redhat-21    |   3    |   0    |    0    |   0.00% |
| microsoft-21 |   2    |   0    |    0    |   0.00% |
| oracle-21    |   2    |   0    |    0    |   0.00% |
+----------------------------------------------------+
Note: Passing since 2024-07-30 18:12

Builds Timeline:
2024-07-31 18:11 - PASSED (redhat-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK21/29/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-31 03:00 - PASSED (microsoft-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK17/126/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-31 00:02 - PASSED (openjdk-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK21/27/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-30 18:12 - FIXED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/29/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-30 06:01 - PASSED (corretto-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK21/27/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-30 00:13 - PASSED (redhat-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK17/128/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-29 21:09 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17/148/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-29 20:05 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK21/14/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-29 02:44 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/100/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-28 21:13 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/109/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-28 19:33 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/57/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-28 09:01 - FAILED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/65/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-28 04:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/65/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-28 00:15 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21/27/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-27 20:07 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/126/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-27 09:14 - REGRESSION (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21/28/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-27 09:12 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-little-endian/316/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-27 00:04 - PASSED (microsoft-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK21/27/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-26 00:00 - PASSED (corretto-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17/151/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-25 19:33 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/56/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-25 06:02 - FIXED (openj9-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-17/129/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-25 04:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/64/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-25 00:01 - FIXED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK17/144/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-24 22:44 - FIXED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/30/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-24 22:32 - FIXED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64/26/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-24 18:11 - PASSED (redhat-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK21/28/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-24 03:00 - FIXED (microsoft-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK17/125/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-24 00:02 - FIXED (openjdk-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK21/26/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-23 18:12 - FAILED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/28/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-23 06:01 - FIXED (corretto-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK21/26/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-23 00:13 - FIXED (redhat-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK17/127/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-22 21:09 - FIXED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17/147/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-22 20:05 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK21/13/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-22 19:33 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/55/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-22 04:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/63/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-22 02:45 - FIXED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/99/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-21 21:13 - FIXED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/108/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-21 09:01 - FAILED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/64/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-21 00:15 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21/26/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-20 20:07 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/125/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-20 09:14 - FIXED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21/27/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-20 09:12 - FIXED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-little-endian/315/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-20 00:04 - PASSED (microsoft-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK21/26/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-19 19:33 - FIXED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/54/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-19 04:15 - FIXED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/62/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-19 00:00 - PASSED (corretto-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17/150/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-18 06:02 - REGRESSION (openj9-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-17/128/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-18 00:01 - REGRESSION (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK17/143/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-17 22:44 - REGRESSION (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/29/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-17 22:33 - REGRESSION (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64/25/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-17 03:00 - REGRESSION (microsoft-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK17/124/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-17 02:43 - FAILED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/219/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-17 00:02 - REGRESSION (openjdk-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK21/25/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-16 19:33 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/53/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-16 18:12 - REGRESSION (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/27/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-16 06:01 - REGRESSION (corretto-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK21/25/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-16 04:15 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/61/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-16 02:43 - FAILED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/218/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-16 00:13 - REGRESSION (redhat-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK17/126/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-15 21:09 - REGRESSION (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17/146/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-15 05:13 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/98/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-14 21:13 - FAILED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/107/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-14 09:01 - FAILED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/63/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-14 02:43 - FAILED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/216/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-13 20:07 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/124/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-13 19:33 - REGRESSION (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/52/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-13 09:14 - FAILED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21/26/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-13 09:12 - FAILED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-little-endian/314/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-13 04:15 - REGRESSION (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/60/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-13 02:43 - REGRESSION (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/215/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-12 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/214/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-12 00:00 - PASSED (corretto-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17/149/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-11 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/536/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-11 06:13 - PASSED (openj9-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-17/127/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-11 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/213/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-11 00:01 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK17/142/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-10 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/535/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-10 22:44 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/28/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-10 22:32 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64/24/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-10 19:33 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/51/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-10 18:11 - PASSED (redhat-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK21/26/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-10 04:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/59/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-10 03:00 - PASSED (microsoft-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK17/123/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-10 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/212/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-10 00:02 - PASSED (openjdk-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK21/24/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-09 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/534/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-09 18:12 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/26/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-09 06:01 - PASSED (corretto-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK21/24/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-09 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/211/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-09 00:13 - PASSED (redhat-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK17/125/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-08 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/533/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-08 21:09 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17/145/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/
2024-07-08 20:05 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK21/11/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice[0: routingMode=SINGLE_MEMBER]/

----------------------------------------
```

**Comment by olukas** [comment] 2024-08-02 07:15
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/26330

**Closed by olukas** 2024-08-02 07:15 UTC
Labels: Team: Client, Team: Core, Type: Test-Failure, Source: Internal, to-jira, Module: Client
