### ISSUE TITLE
TransactionQueueTest.testIssue859And863

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3796] opened 2014-10-08 15:14 UTC
```
java.lang.AssertionError: expected:<2000> but was:<1999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.queue.TransactionQueueTest.testIssue859And863(TransactionQueueTest.java:265)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/1803/testReport/junit/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/

**Comment by bilalyasar** [comment] 2015-01-07 07:24
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/2504/testReport/junit/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/

**Comment by bilalyasar** [comment] 2015-01-22 08:09
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/418/testReport/junit/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/

**Comment by sancar** [comment] 2015-02-05 15:35
:(
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/11673/testReport/junit/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/

**Comment by sancar** [comment] 2015-02-06 15:31
@jerrinot Are you still working on this? I started to get this failure in all my prs. We need to fix this asap. It seems you already send a fix, but this is still failing.

**Comment by jerrinot** [comment] 2015-02-06 15:36
@sancar: nope. If ale PRs are failing with this then it's likely a new regression.

**Comment by sancar** [comment] 2015-02-06 15:37
And I just tried, it passed in my local. Probably randomly failing.

**Comment by jerrinot** [comment] 2015-02-06 15:38
yeah, according to https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast%24hazelcast/11673/testReport/junit/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/history/ 

it's failing from time to time. I'll have a look.

**Comment by bilalyasar** [comment] 2015-02-11 08:49
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK7/com.hazelcast$hazelcast/142/testReport/junit/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/

**Comment by sancar** [comment] 2015-02-11 21:10
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/11840/

**Comment by mesutcelik** [comment] 2015-02-20 08:42
who is working on that issue? 

**new failure below**

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK8/154/com.hazelcast$hazelcast/testReport/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/

**Comment by mesutcelik** [comment] 2015-02-21 11:38
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.6/153/

**Comment by mesutcelik** [comment] 2015-02-25 07:48
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/479/com.hazelcast$hazelcast/testReport/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/

**Comment by mesutcelik** [comment] 2015-03-04 14:52
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/2804/com.hazelcast$hazelcast/testReport/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/testIssue859And863/

**Comment by gurbuzali** [comment] 2015-03-05 09:57
I've changed the test so that it will use `shutdown` instead of `terminate`
Let's see if test fails even with `shutdown`

**Comment by mesutcelik** [comment] 2015-03-06 07:50
@gurbuzali ,

failed again despite your fix....

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/2812/testReport/junit/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/testIssue859And863/

**Comment by mesutcelik** [comment] 2015-03-07 05:40
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/751/com.hazelcast$hazelcast/testReport/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/

**Comment by bilalyasar** [comment] 2015-03-10 21:03
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/2831/testReport/junit/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/testIssue859And863/

**Comment by mesutcelik** [comment] 2015-03-13 08:16
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/2846/com.hazelcast$hazelcast/testReport/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/testIssue859And863/

**Comment by mesutcelik** [comment] 2015-03-13 14:23
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/756/com.hazelcast$hazelcast/testReport/com.hazelcast.queue/TransactionQueueTest/testIssue859And863/

**Comment by bwzhang2011** [comment] 2015-06-07 13:13
@mesutcelik, does it fail with 3.5 EA2 snapshot ?

**Comment by bwzhang2011** [comment] 2015-08-07 15:08
@gurbuzali, any update with such issue ?

**Comment by bwzhang2011** [comment] 2015-11-08 12:01
@gurbuzali, any update with such issue ? will it be back ported into 3.5 branch once it's fixed ?

**Comment by bwzhang2011** [comment] 2015-11-25 22:59
@gurbuzali, any update with such issue ? we're caring about any issues or fixes with IQueue or TransactionQueue related.

**Comment by gurbuzali** [comment] 2015-11-28 16:04
I've increased the item count to 100K and thread-count to 10, couldn't reproduce it.
I've seen below stack-traces but test is not failing.
I'll remove `ignore` and close the issue, let's see if it will fail again

**Comment by hasancelik** [comment] 2016-04-15 07:03
```
java.lang.AssertionError: expected:<1000> but was:<999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest$5.run(TransactionQueueTest.java:364)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:871)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.testIssue859And863(TransactionQueueTest.java:361)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/176/testReport/junit/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/testIssue859And863/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/175/testReport/junit/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/testIssue859And863/

**Comment by hasancelik** [comment] 2016-04-15 13:08
suppressed by https://github.com/hazelcast/hazelcast/commit/2543fd9c08fdd81f20267190d798bcf56af9da51

**Closed** 2016-06-17 08:34 UTC
Labels: SUPPRESSED, Team: Core, Type: Test-Failure
