### ISSUE TITLE
MapLoader.load() swallow org.springframework.jdbc.BadSqlGrammarException

### ISSUE THREAD

**Issue by localarm** [hazelcast/hazelcast#19731] opened 2021-10-06 21:15 UTC
**Describe the bug**
When throw org.springframework.jdbc.BadSqlGrammarException(String task, String sql, SQLException ex) at MapLoader implementation I got empty ExecutionException

**Expected behavior**
When throw org.springframework.jdbc.BadSqlGrammarException at MapLoader implementation I got BadSqlGrammarException

Hazelcast 5.0

**Comment by vbekiaris** [comment] 2021-10-07 07:48
@localarm thanks for raising an issue. Can you post a reproducer or some sample code to demonstrate actual vs expected behaviour?

**Comment by ahmetmircik** [comment] 2021-12-27 13:29
Hi @localarm, the reason of failure is a missing constructor that hazelcast is looking for to clone the exception. The expected constructor signatures can be one from this list:
- `(String message, Throwable cause)`
- `(Throwable cause)`
- `(String message)`
- `()` // empty constructor.

`DataAccessResourceFailureException` has 2 constructors from this expected list. This is the reason it worked as expected.
```
     public DataAccessResourceFailureException(String msg) {
		super(msg);
	  }

	public DataAccessResourceFailureException(String msg, @Nullable Throwable cause) {
		super(msg, cause);
	}
```

But `BadSqlGrammarException` has no matching constructor with the expected list. Maybe you can have an exception translator in spring to fix this. For example an exception with a constructor like this would work:

`public BadSqlGrammarException2(String msg, Throwable ex) {`

**Comment by ahmetmircik** [comment] 2022-01-04 10:34
closing based on https://github.com/hazelcast/hazelcast/issues/19731#issuecomment-1001570941

**Closed by ahmetmircik** 2022-01-04 10:34 UTC
Labels: Type: Defect, Team: Core, Source: Community, Module: IMap
