### ISSUE TITLE
com.hazelcast.spring.cache.TestCacheManager.testBean_withTTL failure [HZ-996]

### ISSUE THREAD

**Issue by fbarotov** [hazelcast/hazelcast#19527] opened 2021-09-14 10:57 UTC
on master

Failed on [Hazelcast-pr-builder/7140](http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/7140/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/testBean_withTTL/)

Stacktrace:
```
java.lang.AssertionError: expected:<ali> but was:<null>
	at com.hazelcast.spring.cache.TestCacheManager.testBean_withTTL(TestCacheManager.java:87)
```

Standard output:
```
BuildInfo right after testBean_withTTL(com.hazelcast.spring.cache.TestCacheManager): BuildInfo{version='5.0-SNAPSHOT', build='20210914', buildNumber=20210914, revision=d8a103b, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testBean_withTTL(com.hazelcast.spring.cache.TestCacheManager):'
10:45:05, accumulated pauses: 2052 ms, max pause: 78 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

**Comment by gurbuzali** [comment] 2021-09-23 09:03
I couldn't reproduce this on local an the logs are missing in the surefire-reports, just above stacktrace and output. I'll close the issue now, we can revisit if fails again.

**Comment by ramizdundar** [comment] 2021-10-13 12:25
_5.0.z_ (commit e70f143872aa5beb83d53111e17fd1366de15b27)

Failed on PR builder: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/7798/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/testBean_withTTL/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<ali> but was:<null>
	at com.hazelcast.spring.cache.TestCacheManager.testBean_withTTL(TestCacheManager.java:87)
```

</details>

<details><summary>Standard output:</summary>

```
BuildInfo right after testBean_withTTL(com.hazelcast.spring.cache.TestCacheManager): BuildInfo{version='5.0.1-SNAPSHOT', build='20211012', buildNumber=20211012, revision=554cc59, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testBean_withTTL(com.hazelcast.spring.cache.TestCacheManager):'
21:41:55, accumulated pauses: 125 ms, max pause: 28 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by olukas** [comment] 2022-01-03 09:53
Failed also on `master` with Oracle JDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8/178/testReport/com.hazelcast.spring.cache/TestCacheManager/testBean_withTTL/

**Comment by olukas** [comment] 2022-03-14 08:00
Failed on `5.1.z` branch on CorrettoJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-CorrettoJDK8/25/testReport/com.hazelcast.spring.cache/TestCacheManager/testBean_withTTL/

**Closed** 2022-03-22 19:02 UTC
Labels: Type: Test-Failure, Source: Internal, Module: Spring, to-jira, Team: Platform
