### ISSUE TITLE
MigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8063] opened 2016-05-02 07:31 UTC
```
java.lang.AssertionError: Replica: 1 is not found in Partition [12]{
    0:Address[127.0.0.1]:10058
    2:Address[127.0.0.1]:10056
    3:Address[127.0.0.1]:10053
    5:Address[127.0.0.1]:10007
    6:Address[127.0.0.1]:10055
}
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertNotNull(Assert.java:712)
    at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndData(PartitionCorrectnessTestSupport.java:193)
    at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport$AssertSizeAndDataTask.run(PartitionCorrectnessTestSupport.java:247)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:871)
    at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:150)
    at com.hazelcast.internal.partition.MigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated(MigrationCorrectnessTest.java:122)
    at com.hazelcast.internal.partition.MigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate(MigrationCorrectnessTest.java:100)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/4966/testReport/junit/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_7_/

**Comment by metanet** [comment] 2016-05-11 07:55
Most probably fixed by recent fixes in migration system. Closing this one.

**Comment by hasancelik** [comment] 2016-09-19 10:02
```
java.lang.AssertionError: Replica: 1 is not found in Partition [28]{
	0:[127.0.0.1]:9203
	4:[127.0.0.1]:9206
}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionVersionsAndBackupValues(PartitionCorrectnessTestSupport.java:216)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndData(PartitionCorrectnessTestSupport.java:177)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport$AssertSizeAndDataTask.run(PartitionCorrectnessTestSupport.java:291)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:905)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:919)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:152)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated(AbstractMigrationCorrectnessTest.java:99)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate(AbstractMigrationCorrectnessTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/332/testReport/junit/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_4_/

**Comment by hasancelik** [comment] 2016-11-28 11:22
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.terminateNodes(PartitionCorrectnessTestSupport.java:146)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated(AbstractMigrationCorrectnessTest.java:95)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate(AbstractMigrationCorrectnessTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1105/testReport/junit/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_4_/

**Comment by mdogan** [comment] 2016-11-28 11:24
Issue in the last [comment](https://github.com/hazelcast/hazelcast/issues/8063#issuecomment-263247074) is already fixed by https://github.com/hazelcast/hazelcast/pull/9323

**Comment by mdogan** [comment] 2016-12-13 09:25
Not failing since [Sep 19](https://github.com/hazelcast/hazelcast/issues/8063#issuecomment-247954161). Please re-open if fails again.

**Comment by mdogan** [comment] 2016-12-16 12:00
```
java.lang.AssertionError: Replica: 2 is not found in Partition [2]{
	0:[127.0.0.1]:5072
	1:[127.0.0.1]:5074
}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionVersionsAndBackupValues(PartitionCorrectnessTestSupport.java:238)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndData(PartitionCorrectnessTestSupport.java:199)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.access$000(PartitionCorrectnessTestSupport.java:58)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport$AssertSizeAndDataTask.run(PartitionCorrectnessTestSupport.java:326)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:913)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:927)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:170)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:166)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated(AbstractMigrationCorrectnessTest.java:93)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate(AbstractMigrationCorrectnessTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/6308/testReport/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_2_nodes_3_/

**Comment by mdogan** [comment] 2016-12-19 08:49
[Last failure](https://github.com/hazelcast/hazelcast/issues/8063#issuecomment-267579930) is caused by processing member update operations in broken order. See related issue: https://github.com/hazelcast/hazelcast/issues/9486

Logs of the failure are filled by following warning:
```
08:00:46,268  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,269  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.generic-operation.thread-31 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,269  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,269  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,269  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,270  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.generic-operation.thread-33 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,270  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.generic-operation.thread-35 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,271  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.generic-operation.thread-2 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,271  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.generic-operation.thread-3 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,271  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.generic-operation.thread-4 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,271  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.generic-operation.thread-5 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
08:00:46,271  WARN |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:2,nodes:3]| - [ClusterService] hz._hzInstance_32_dev.generic-operation.thread-6 - [127.0.0.1]:5074 [dev] [3.8-SNAPSHOT] Received an inconsistent member update which contains new members and removes some of the current members! Ignoring and requesting a new member update...
....
```

**Comment by blazember** [comment] 2018-08-13 14:53
New failure from the PR builder:

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/16722/testReport/junit/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_4_fragmented_false_/

**Error Message**
```
Replica version mismatch! Owner: [127.0.0.1]:5701, Backup: [127.0.0.1]:5708, Partition: Partition [0]{
 0:[127.0.0.1]:5701
 1:[127.0.0.1]:5708
 2:[127.0.0.1]:5709
}, Replica: 1 owner versions: [1, 1, 1, 0, 0, 0] backup versions: [0, 0, 0, 0, 0, 0] expected:<1> but was:<0>
```
**Stacktrace**
```
java.lang.AssertionError: 
Replica version mismatch! Owner: [127.0.0.1]:5701, Backup: [127.0.0.1]:5708, Partition: Partition [0]{
	0:[127.0.0.1]:5701
	1:[127.0.0.1]:5708
	2:[127.0.0.1]:5709
}, Replica: 1 owner versions: [1, 1, 1, 0, 0, 0] backup versions: [0, 0, 0, 0, 0, 0] expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionVersionsAndBackupValues(PartitionCorrectnessTestSupport.java:284)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndData(PartitionCorrectnessTestSupport.java:220)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.access$000(PartitionCorrectnessTestSupport.java:61)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport$AssertSizeAndDataTask.run(PartitionCorrectnessTestSupport.java:359)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1279)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1305)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:178)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:174)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated(AbstractMigrationCorrectnessTest.java:104)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate(AbstractMigrationCorrectnessTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
**Some notable accumulated pauses**
```
13:49:45, accumulated pauses: 1353 ms, max pause: 186 ms, pauses over 1000 ms: 0
13:49:50, accumulated pauses: 1031 ms, max pause: 213 ms, pauses over 1000 ms: 0
13:49:55, accumulated pauses: 1611 ms, max pause: 518 ms, pauses over 1000 ms: 0
13:50:00, accumulated pauses: 1231 ms, max pause: 405 ms, pauses over 1000 ms: 0
13:50:05, accumulated pauses: 1092 ms, max pause: 263 ms, pauses over 1000 ms: 0
13:50:10, accumulated pauses: 1054 ms, max pause: 179 ms, pauses over 1000 ms: 0
13:50:15, accumulated pauses: 800 ms, max pause: 248 ms, pauses over 1000 ms: 0
13:50:20, accumulated pauses: 368 ms, max pause: 9 ms, pauses over 1000 ms: 0
13:50:25, accumulated pauses: 394 ms, max pause: 13 ms, pauses over 1000 ms: 0
13:50:30, accumulated pauses: 491 ms, max pause: 178 ms, pauses over 1000 ms: 0
13:50:35, accumulated pauses: 306 ms, max pause: 13 ms, pauses over 1000 ms: 0
13:50:40, accumulated pauses: 315 ms, max pause: 10 ms, pauses over 1000 ms: 0
13:50:45, accumulated pauses: 326 ms, max pause: 27 ms, pauses over 1000 ms: 0
13:50:50, accumulated pauses: 328 ms, max pause: 16 ms, pauses over 1000 ms: 0
13:50:55, accumulated pauses: 249 ms, max pause: 18 ms, pauses over 1000 ms: 0
13:51:00, accumulated pauses: 367 ms, max pause: 55 ms, pauses over 1000 ms: 0
13:51:05, accumulated pauses: 295 ms, max pause: 25 ms, pauses over 1000 ms: 0
13:51:10, accumulated pauses: 219 ms, max pause: 7 ms, pauses over 1000 ms: 0
13:51:15, accumulated pauses: 389 ms, max pause: 25 ms, pauses over 1000 ms: 0
13:51:20, accumulated pauses: 118 ms, max pause: 6 ms, pauses over 1000 ms: 0
13:51:25, accumulated pauses: 108 ms, max pause: 7 ms, pauses over 1000 ms: 0
13:51:30, accumulated pauses: 89 ms, max pause: 3 ms, pauses over 1000 ms: 0
13:51:35, accumulated pauses: 82 ms, max pause: 9 ms, pauses over 1000 ms: 0
13:51:40, accumulated pauses: 75 ms, max pause: 6 ms, pauses over 1000 ms: 0
13:51:45, accumulated pauses: 64 ms, max pause: 5 ms, pauses over 1000 ms: 0
13:51:50, accumulated pauses: 84 ms, max pause: 8 ms, pauses over 1000 ms: 0
13:51:55, accumulated pauses: 63 ms, max pause: 4 ms, pauses over 1000 ms: 0
13:52:00, accumulated pauses: 51 ms, max pause: 5 ms, pauses over 1000 ms: 0
13:52:05, accumulated pauses: 77 ms, max pause: 3 ms, pauses over 1000 ms: 0
13:52:10, accumulated pauses: 73 ms, max pause: 9 ms, pauses over 1000 ms: 0
13:52:15, accumulated pauses: 55 ms, max pause: 5 ms, pauses over 1000 ms: 0
13:52:20, accumulated pauses: 48 ms, max pause: 4 ms, pauses over 1000 ms: 0
13:52:25, accumulated pauses: 63 ms, max pause: 5 ms, pauses over 1000 ms: 0
13:52:30, accumulated pauses: 45 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:52:35, accumulated pauses: 44 ms, max pause: 6 ms, pauses over 1000 ms: 0
13:52:40, accumulated pauses: 191 ms, max pause: 166 ms, pauses over 1000 ms: 0
```

**Comment by mdogan** [comment] 2018-08-14 09:01
Latest failure log: 
[MigrationCorrectnessTest-testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate.log](https://github.com/hazelcast/hazelcast/files/2286206/MigrationCorrectnessTest-testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate.log)

**Comment by mmedenjak** [comment] 2018-10-01 07:49
@mdogan @metanet any update on this issue? Can you unassign if you are unable to work on it? Thanks!

**Comment by mdogan** [comment] 2018-10-01 08:33
@mmedenjak: I'm trying to identify the issue but have no clue yet.

**Comment by Holmistr** [comment] 2018-11-07 08:44
After discussion with @mdogan , the last failure didn't give any insight in the logs. We also haven't seen this issue for a while. The current strategy is to close this issue, wait for another failure and with fingers crossed, hope for more interesting logs.

**Comment by olukas** [comment] 2019-02-25 07:25
It failed again on OracleJDK7: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK7/8/testReport/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_4_fragmented_true_/

Stacktrace:
```
java.lang.AssertionError: 
Replica version mismatch! Owner: [127.0.0.1]:5706, Backup: [127.0.0.1]:5716, Partition: Partition [92]{
	0:[127.0.0.1]:5706 - 408d259f-3a58-4d95-ad92-f32ac67a7559
	1:[127.0.0.1]:5710 - 70d1c259-7804-4e23-88a4-9502267819d4
	2:[127.0.0.1]:5717 - b86e50c3-0f35-46d6-9f88-af0c056b18a8
	3:[127.0.0.1]:5716 - 6bdadd52-74af-4090-a48c-27cdf5f2983e
	4:[127.0.0.1]:5714 - 1ca3ff75-35a9-42f0-a6c4-727d532625c9
	5:[127.0.0.1]:5709 - 6a957991-c1ba-47c1-8e48-e2ffd73e1a22
	6:[127.0.0.1]:5715 - a89434be-80df-451d-be65-684116b50252
}, Replica: 3 owner versions: [1, 1, 1, 0, 0, 0] backup versions: [0, 0, 0, 0, 0, 0] expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionVersionsAndBackupValues(PartitionCorrectnessTestSupport.java:284)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndData(PartitionCorrectnessTestSupport.java:222)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.access$000(PartitionCorrectnessTestSupport.java:61)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport$AssertSizeAndDataTask.run(PartitionCorrectnessTestSupport.java:359)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:178)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:174)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated(AbstractMigrationCorrectnessTest.java:98)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate(AbstractMigrationCorrectnessTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

Accumulated pauses:
```
Hiccups measured while running test 'testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:true](com.hazelcast.internal.partition.MigrationCorrectnessTest):'
10:31:15, accumulated pauses: 143 ms, max pause: 33 ms, pauses over 1000 ms: 0
10:31:20, accumulated pauses: 156 ms, max pause: 28 ms, pauses over 1000 ms: 0
10:31:25, accumulated pauses: 61 ms, max pause: 21 ms, pauses over 1000 ms: 0
10:31:30, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:31:35, accumulated pauses: 64 ms, max pause: 24 ms, pauses over 1000 ms: 0
10:31:40, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:31:45, accumulated pauses: 54 ms, max pause: 15 ms, pauses over 1000 ms: 0
10:31:50, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:31:55, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:32:00, accumulated pauses: 48 ms, max pause: 7 ms, pauses over 1000 ms: 0
10:32:05, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:32:10, accumulated pauses: 53 ms, max pause: 12 ms, pauses over 1000 ms: 0
10:32:15, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:32:20, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:32:25, accumulated pauses: 53 ms, max pause: 14 ms, pauses over 1000 ms: 0
10:32:30, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:32:35, accumulated pauses: 44 ms, max pause: 6 ms, pauses over 1000 ms: 0
10:32:40, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:32:45, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:32:50, accumulated pauses: 51 ms, max pause: 11 ms, pauses over 1000 ms: 0
10:32:55, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:33:00, accumulated pauses: 57 ms, max pause: 18 ms, pauses over 1000 ms: 0
10:33:05, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:33:10, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:33:15, accumulated pauses: 53 ms, max pause: 11 ms, pauses over 1000 ms: 0
10:33:20, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:33:25, accumulated pauses: 53 ms, max pause: 12 ms, pauses over 1000 ms: 0
10:33:30, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:33:35, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:33:40, accumulated pauses: 56 ms, max pause: 15 ms, pauses over 1000 ms: 0
10:33:45, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
10:33:50, accumulated pauses: 754 ms, max pause: 721 ms, pauses over 1000 ms: 0
```

Debug log was enabled for that run. I also marked that run as `Keep this build forever` to persist those logs in Jenkins. Once when investigation will be done then please set that run back to `Don't keep this build forever`.

**Comment by mdogan** [comment] 2019-02-25 07:38
Currently there are a few known bugs in migration system, introduced by https://github.com/hazelcast/hazelcast/pull/14351. I have sent fixes for those via https://github.com/hazelcast/hazelcast/pull/14526.

**Comment by mmedenjak** [comment] 2020-09-02 16:13
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2198/

**Comment by mdogan** [comment] 2020-09-02 19:21
Same issue: https://github.com/hazelcast/hazelcast/issues/17377

**Closed** 2020-09-22 13:32 UTC
Labels: Module: Partitioning, Source: Internal, Team: Core, Type: Test-Failure
