### ISSUE TITLE
hazelcast instance force-restart

### ISSUE THREAD

**Issue by aviram26** [hazelcast/hazelcast#8246] opened 2016-05-25 11:53 UTC
Following noctarius request for - http://stackoverflow.com/questions/37431300/hazelcast-instance-force-restart

**Description of environment and program:**
I have a 4-node cluster of hazelcast community 3.6.2 running on docker.
My program only monitors the state of the cluster and tries to recover if a connectivity issue is detected.
To identify a problem I use the following:

```
LifecycleService.isRunning()
Cluster.getMembers().size() > 1
Cluster.getClusterState() == ClusterState.ACTIVE
```

**The problem:**
To simulate a full cluster split I'm using docker network disconnect/connect.
After reconnecting, some of the nodes are in `FROZEN` state. The program identifies this and tries to shutdown the node using `HazelcastInstance.shutdown()`.
From this point on the only thing I get from the node/s is:

> com.hazelcast.cluster.impl.operations.JoinCheckOperation
> INFO: [172.17.0.3]:5701 [dev] [3.6.2] Ignoring join check from Address[172.17.0.2]:5701, because cluster is in FROZEN state ...

How can I overcome this? My purpose is to to recover all nodes and rebuild the cluster.
Let me know if additional code/logs are needed...

**Comment by aviram26** [comment] 2016-06-05 08:30
any news? any eta?

**Comment by jerrinot** [comment] 2016-06-05 08:42
@aviram26: Do you have more logs you could share? A member transiting into `FROZEN` state on its own is very suspicious. Can you reproduce it with DEBUG/FINEST log settings?

**Comment by aviram26** [comment] 2016-06-05 09:23
The configuration is very strait-forward: just run a 4-node cluster.
You need to have the ability to split-brain the cluster by disconnecting the network. I did it using docker disconnect/connect. It can also be done in other ways. Important thing is that I didn't mess with the execution of the program. 
After several disconnect/connect (sometime once/usually two or three) some of the nodes are FROZEN.
This should be very easy to reproduce.
Let me know otherwise.

**Comment by bwzhang2011** [comment] 2016-06-19 13:32
@jerrinot,  hazelcast cluster under force way should be provided while cluster currently could not be recovered itself.  how about such ability or feature could be provided in hazelcast mancenter or hazelcast-cli.

**Comment by metanet** [comment] 2016-06-20 09:33
hi @aviram26 
before starting a cluster merge, the `merging` side moves all of its nodes to `FROZEN` state. This is done due to prevent migrations among the nodes of the `merging` side and move the data to the `merged` side. So you can see your `merging` nodes in `FROZEN` temporarily. As I see from your "monitoring code", you may shutdown your node during this merge process. 

Could you clarify the problem a little bit more? Do you still see your nodes in `FROZEN` after the merge is completed and they all connected to the other side?

**Comment by aviram26** [comment] 2016-07-03 11:40
Hi @metanet 
I understand the theory, but in practice, as I mentioned above, after calling shutdown I only get
```
com.hazelcast.cluster.impl.operations.JoinCheckOperation
INFO: [172.17.0.3]:5701 [dev] [3.6.2] Ignoring join check from Address[172.17.0.2]:5701, because cluster is in FROZEN state ...
```
The node does not recover, neither completes the shutdown. It is "Frozen" forever.
Please try to reproduce. As I described, I only have a cluster that does nothing. Starting each instance with `new HazelcastInstance()` and then disconnecting/reconnecting all nodes produces the probelm.

**Comment by nickhristov** [comment] 2017-02-14 23:02
I have seen the same issue with 3.6.3. The error message was this:

```
Cluster state either is locked or doesn't allow new members to join -> ClusterState{state=FROZEN, lock=ClusterStateLock{lockOwner=null, transactionId='null', lockExpiryTime=0}}
```

Here are the relevant logs:

```
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.957  ERROR [hz._hzInstance_1_Union.generic-operation.thread-0] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Reason of failure for node join : Cluster state either is locked or doesn't allow new members to join -> ClusterState{state=FROZEN, lock=ClusterStateLock{lockOwner=null, transactionId='null', lockExpiryTime=0}}
ip-10-0-30-217	INFO	2017-02-02 04:57:49.957  INFO [hz._hzInstance_1_Union.generic-operation.thread-0] com.hazelcast.instance.Node - [10.0.30.217]:5702 [Union] [3.6.3] Node is already shutting down... Waiting for shutdown process to complete...
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.957  ERROR [hz._hzInstance_1_Union.generic-operation.thread-0] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Reason of failure for node join : Cluster state either is locked or doesn't allow new members to join -> ClusterState{state=FROZEN, lock=ClusterStateLock{lockOwner=null, transactionId='null', lockExpiryTime=0}}
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.956  ERROR [hz._hzInstance_1_Union.generic-operation.thread-0] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Node could not join cluster. Before join check failed node is going to shutdown now!
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.956  ERROR [hz._hzInstance_1_Union.generic-operation.thread-0] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Node could not join cluster. Before join check failed node is going to shutdown now!
ip-10-0-20-229	INFO	2017-02-02 04:57:49.955  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] Removing Member [10.0.30.217]:5702
ip-10-0-20-229	INFO	2017-02-02 04:57:49.955  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.ClusterService - [10.0.20.229]:5701 [Union] [3.6.3] Removing Member [10.0.30.217]:5702
ip-10-0-20-229	INFO	2017-02-02 04:57:49.955  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] Removing Member [10.0.30.217]:5702
ip-10-0-20-229	INFO	2017-02-02 04:57:49.955  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.ClusterService - [10.0.20.229]:5701 [Union] [3.6.3] Removing Member [10.0.30.217]:5702

ip-10-0-30-217	INFO	2017-02-02 04:57:49.954  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.instance.Node - [10.0.30.217]:5702 [Union] [3.6.3] Shutting down connection manager...
ip-10-0-30-217	WARN	2017-02-02 04:57:49.954  WARN [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.instance.Node - [10.0.30.217]:5702 [Union] [3.6.3] Terminating forcefully...
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.954  ERROR [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Reason of failure for node join : Cluster state either is locked or doesn't allow new members to join -> ClusterState{state=FROZEN, lock=ClusterStateLock{lockOwner=null, transactionId='null', lockExpiryTime=0}}
ip-10-0-30-217	ERROR	2017-02-02 04:57:49.954  ERROR [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.security - [10.0.30.217]:5702 [Union] [3.6.3] Node could not join cluster. Before join check failed node is going to shutdown now!
ip-10-0-20-229	WARN	2017-02-02 04:57:49.954  WARN [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.impl.ClusterJoinManager - [10.0.20.229]:5701 [Union] [3.6.3] New join request has been received from an existing endpoint Member [10.0.30.217]:5702. Removing old member and processing join request...


ip-10-0-30-217	INFO	2017-02-02 04:57:49.953  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.impl.ClusterJoinManager - [10.0.30.217]:5702 [Union] [3.6.3] Ignoring master response Address[10.0.20.229]:5701 from Address[10.0.20.229]:5701 since this node has an active master Address[10.0.30.217]:5701
ip-10-0-30-217	INFO	2017-02-02 04:57:48.954  INFO [cached1] com.hazelcast.cluster.impl.TcpIpJoiner - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.20.229]:5702 is added to the blacklist.
ip-10-0-30-217	INFO	2017-02-02 04:57:48.951  INFO [cached1] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Could not connect to: /10.0.20.229:5702. Reason: SocketException[Connection refused to address /10.0.20.229:5702]
ip-10-0-30-217	INFO	2017-02-02 04:57:48.947  INFO [cached3] com.hazelcast.cluster.impl.TcpIpJoiner - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.30.217]:5703 is added to the blacklist.
ip-10-0-30-217	INFO	2017-02-02 04:57:48.946  INFO [cached2] com.hazelcast.cluster.impl.TcpIpJoiner - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.20.229]:5703 is added to the blacklist.
ip-10-0-30-217	INFO	2017-02-02 04:57:48.946  INFO [cached2] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Could not connect to: /10.0.20.229:5703. Reason: SocketException[Connection refused to address /10.0.20.229:5703]
ip-10-0-30-217	INFO	2017-02-02 04:57:48.946  INFO [cached3] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Could not connect to: /10.0.30.217:5703. Reason: SocketException[Connection refused to address /10.0.30.217:5703]
ip-10-0-30-217	INFO	2017-02-02 04:57:48.945  INFO [cached3] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Connecting to /10.0.30.217:5703, timeout: 0, bind-any: true
ip-10-0-20-229	INFO	2017-02-02 04:57:48.943  INFO [cached2] com.hazelcast.nio.tcp.TcpIpConnectionManager - [10.0.20.229]:5701 [Union] [3.6.3] Established socket connection between /10.0.20.229:5701 and /10.0.30.217:55154
ip-10-0-30-217	INFO	2017-02-02 04:57:48.943  INFO [cached3] com.hazelcast.nio.tcp.TcpIpConnectionManager - [10.0.30.217]:5702 [Union] [3.6.3] Established socket connection between /10.0.30.217:49505 and /10.0.30.217:5701
ip-10-0-30-217	INFO	2017-02-02 04:57:48.942  INFO [cached1] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Connecting to /10.0.20.229:5702, timeout: 0, bind-any: true
ip-10-0-20-229	INFO	2017-02-02 04:57:48.942  INFO [hz._hzInstance_1_Union.IO.thread-Acceptor] com.hazelcast.nio.tcp.SocketAcceptorThread - [10.0.20.229]:5701 [Union] [3.6.3] Accepting socket connection from /10.0.30.217:55154
ip-10-0-30-217	INFO	2017-02-02 04:57:48.940  INFO [cached1] com.hazelcast.nio.tcp.TcpIpConnectionManager - [10.0.30.217]:5702 [Union] [3.6.3] Established socket connection between /10.0.30.217:55154 and /10.0.20.229:5701
ip-10-0-30-217	INFO	2017-02-02 04:57:48.935  INFO [cached3] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Connecting to /10.0.30.217:5701, timeout: 0, bind-any: true
ip-10-0-30-217	INFO	2017-02-02 04:57:48.934  INFO [cached2] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Connecting to /10.0.20.229:5703, timeout: 0, bind-any: true
ip-10-0-30-217	INFO	2017-02-02 04:57:48.934  INFO [cached1] com.hazelcast.nio.tcp.InitConnectionTask - [10.0.30.217]:5702 [Union] [3.6.3] Connecting to /10.0.20.229:5701, timeout: 0, bind-any: true
ip-10-0-30-217	INFO	2017-02-02 04:57:48.901  INFO [vert.x-worker-thread-0] com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThreadingModel - [10.0.30.217]:5702 [Union] [3.6.3] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads
ip-10-0-30-217	INFO	2017-02-02 04:57:48.767  INFO [vert.x-worker-thread-0] com.hazelcast.core.LifecycleService - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.30.217]:5702 is STARTING
ip-10-0-30-217	INFO	2017-02-02 04:57:48.766  INFO [vert.x-worker-thread-0] com.hazelcast.instance.Node - [10.0.30.217]:5702 [Union] [3.6.3] Creating TcpIpJoiner
ip-10-0-30-217	INFO	2017-02-02 04:57:48.250  INFO [vert.x-worker-thread-0] com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor - [10.0.30.217]:5702 [Union] [3.6.3] Starting with 2 generic operation threads and 2 partition operation threads.
ip-10-0-30-217	INFO	2017-02-02 04:57:48.207  INFO [vert.x-worker-thread-0] com.hazelcast.spi.OperationService - [10.0.30.217]:5702 [Union] [3.6.3] Backpressure is disabled
ip-10-0-30-217	INFO	2017-02-02 04:57:47.979  INFO [vert.x-worker-thread-0] com.hazelcast.system - [10.0.30.217]:5702 [Union] [3.6.3] Hazelcast 3.6.3 (20160527 - 08b28c3) starting at Address[10.0.30.217]:5702
ip-10-0-30-217	INFO	2017-02-02 04:57:47.979  INFO [vert.x-worker-thread-0] com.hazelcast.system - [10.0.30.217]:5702 [Union] [3.6.3] Configured Hazelcast Serialization version : 1
ip-10-0-30-217	INFO	2017-02-02 04:57:47.979  INFO [vert.x-worker-thread-0] com.hazelcast.system - [10.0.30.217]:5702 [Union] [3.6.3] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
ip-10-0-30-217	INFO	2017-02-02 04:57:47.969  INFO [vert.x-worker-thread-0] com.hazelcast.instance.DefaultAddressPicker - [LOCAL] [Union] [3.6.3] Picked Address[10.0.30.217]:5702, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5702], bind any local is true
ip-10-0-30-217	INFO	2017-02-02 04:57:47.965  INFO [vert.x-worker-thread-0] com.hazelcast.instance.DefaultAddressPicker - [LOCAL] [Union] [3.6.3] Prefer IPv4 stack is true.
ip-10-0-30-217	INFO	2017-02-02 04:57:47.963  INFO [vert.x-worker-thread-0] com.hazelcast.instance.DefaultAddressPicker - [LOCAL] [Union] [3.6.3] Interfaces is enabled, trying to pick one address matching to one of: [10.0.30.217]
ip-10-0-30-217	INFO	2017-02-02 04:57:47.779  INFO [main] com.turvo.presence.PresenceMain - Adding participating host to cluster 10.0.20.229
ip-10-0-30-217	INFO	2017-02-02 04:57:47.772  INFO [main] com.turvo.presence.PresenceMain - Adding participating host to cluster 10.0.30.217
ip-10-0-30-217	INFO	2017-02-02 04:57:47.027  INFO [main] org.springframework.context.annotation.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7f416310: startup date [Thu Feb 02 04:57:47 UTC 2017]; root of context hierarchy
ip-10-0-20-229	WARN	2017-02-02 04:57:45.799  WARN [hz._hzInstance_1_Union.IO.thread-in-2] com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader - [10.0.20.229]:5701 [Union] [3.6.3] hz._hzInstance_1_Union.IO.thread-in-2 Closing socket to endpoint Address[10.0.30.217]:5702, Cause:java.io.EOFException: Remote socket closed!
ip-10-0-20-229	WARN	2017-02-02 04:57:45.798  WARN [hz._hzInstance_1_Union.IO.thread-in-0] com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader - [10.0.20.229]:5701 [Union] [3.6.3] hz._hzInstance_1_Union.IO.thread-in-0 Closing socket to endpoint Address[10.0.30.217]:5702, Cause:java.io.EOFException: Remote socket closed!
ip-10-0-20-229	INFO	2017-02-02 04:57:45.797  INFO [hz._hzInstance_1_Union.IO.thread-in-0] com.hazelcast.nio.tcp.TcpIpConnection - [10.0.20.229]:5701 [Union] [3.6.3] Connection [Address[10.0.30.217]:5702] lost. Reason: java.io.EOFException[Remote socket closed!]
ip-10-0-20-229	INFO	2017-02-02 04:57:45.795  INFO [hz._hzInstance_1_Union.IO.thread-in-2] com.hazelcast.nio.tcp.TcpIpConnection - [10.0.20.229]:5701 [Union] [3.6.3] Connection [Address[10.0.30.217]:5702] lost. Reason: java.io.EOFException[Remote socket closed!]
ip-10-0-30-217	INFO	2017-02-02 04:18:01.871  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.impl.operations.JoinCheckOperation - [10.0.30.217]:5702 [Union] [3.6.3] Ignoring join check from Address[10.0.30.217]:5701, because this node is not master...
ip-10-0-30-217	INFO	2017-02-02 04:18:01.871  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.impl.operations.JoinCheckOperation - [10.0.30.217]:5702 [Union] [3.6.3] Ignoring join check from Address[10.0.30.217]:5701, because this node is not master...
ip-10-0-30-217	ERROR	2017-02-02 04:16:39.966  ERROR [vert.x-acceptor-thread-0] io.vertx.core.http.impl.HttpServerImpl - java.net.BindException: Address already in use
ip-10-0-30-217	ERROR	2017-02-02 04:16:39.966  ERROR [vert.x-acceptor-thread-0] io.vertx.core.http.impl.HttpServerImpl - java.net.BindException: Address already in use
ip-10-0-30-217	INFO	2017-02-02 04:16:39.719  INFO [main] com.turvo.presence.PresenceMain - Service initialized
ip-10-0-30-217	INFO	2017-02-02 04:16:39.719  INFO [main] com.turvo.presence.PresenceMain - Service initialized
ip-10-0-20-229	INFO	2017-02-02 04:16:38.666  INFO [hz._hzInstance_1_Union.migration] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] All migration tasks have been completed, queues are empty.
ip-10-0-20-229	INFO	2017-02-02 04:16:38.666  INFO [hz._hzInstance_1_Union.migration] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] All migration tasks have been completed, queues are empty.
ip-10-0-30-217	INFO	2017-02-02 04:16:38.589  INFO [vert.x-worker-thread-0] com.hazelcast.core.LifecycleService - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.30.217]:5702 is STARTED
ip-10-0-30-217	INFO	2017-02-02 04:16:38.589  INFO [vert.x-worker-thread-0] com.hazelcast.core.LifecycleService - [10.0.30.217]:5702 [Union] [3.6.3] Address[10.0.30.217]:5702 is STARTED
ip-10-0-20-229	INFO	2017-02-02 04:16:36.797  INFO [hz._hzInstance_1_Union.migration] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] Re-partitioning cluster data... Migration queue size: 135
ip-10-0-20-229	INFO	2017-02-02 04:16:36.797  INFO [hz._hzInstance_1_Union.migration] com.hazelcast.partition.InternalPartitionService - [10.0.20.229]:5701 [Union] [3.6.3] Re-partitioning cluster data... Migration queue size: 135
ip-10-0-20-229	INFO	2017-02-02 04:16:36.546  INFO [hz._hzInstance_1_Union.generic-operation.thread-1] com.hazelcast.cluster.ClusterService - [10.0.20.229]:5701 [Union] [3.6.3] 
Members [2] {
	Member [10.0.20.229]:5701 this
	Member [10.0.30.217]:5702
}
```

At this point the error is non-recoverable, and I am left with one node which is in frozen state.

My use case is rather simple: I am trying to run vert.x in clustered mode: the amount of data which I am storing in hazelcast is miniscule, but I care very much about stability of the cluster: it must be able to auto-heal when partition events happen.

**Comment by metanet** [comment] 2017-05-25 08:04
The last report about this was on 3.6.x and we don't hear any problem after 3.7. We couldn't reproduce this issue locally but there were a lot of improvements in both 3.7 and 3.8. Closing for now and we can re-open it if we see it occurs again.

**Closed by metanet** 2017-05-25 08:04 UTC
Labels: Team: Core, Type: Defect
