### ISSUE TITLE
Hazelcast ScheduledExecutorService OOME

### ISSUE THREAD

**Issue by jevel0per** [hazelcast/hazelcast#9799] opened 2017-02-04 12:58 UTC
Using ScheduledExecutorService from hazelcast 3.8 i've got an out of memory exception. The thing is i'm making a service which should remind to user about some event during a day. Execution of tasks should be fault-tolerant. A user sets new reminder which is a task for ScheduledExecutorService, thus amount of tasks can be several thousands per day. Each task adds to scheduler as one-shot action using schedule(Runnable command, long delay, TimeUnit unit). A delay can't be longer then 24 hours. When i've started to make tests and add tasks in loop, i've got an oom exception. I thought a task after execution will be removed from memory, but probably i was wrong.

Can you answer for several question:
1. Should a task be removed from memory after execution?
2. Is there any setting to do that?
3. Can i use ScheduledExecutorService for a lot of one-shot action tasks?

**Comment by tkountis** [comment] 2017-02-04 16:22
Have you tried destroying the future after execution, at the moment all
tasks stay in memory so a user can easily retrieve their status using the
future. So your option as I see it, is keeping track of the future and
destroying when done. If you want to avoid storing the future locally, you
can also retrieve all tasks of a given executor by getAllScheduled . One
way to do this periodically, would be to schedule a maintenance task every
so often, which checks status and cleans.


On 4 Feb 2017 12:58 p.m., "jevel0per" <notifications@github.com> wrote:

Using ScheduledExecutorService from hazelcast 3.8 i've got an out of memory
exception. The thing is i'm making a service which should remind to user
about some event during a day. Execution of task should be fault-tolerant.
A user sets new reminder which is a task for ScheduledExecutorService, thus
amount of tasks can be several thousands per day. Each task adds to
scheduler as one-shot action using schedule(Runnable command, long delay,
TimeUnit unit). A delay can't be longer then 24 hours. When i've started to
make tests and add tasks in loop, i've got an oom exception. I thought a
task after execution will be removed from memory, but probably i was wrong.

Can you answer for several question:

   1. Should a task be removed from memory after execution?
   2. Is there any setting to do that?
   3. Can i use ScheduledExecutorService for a lot of one-shot action tasks?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hazelcast/hazelcast/issues/9799>, or mute the thread

**Comment by tkountis** [comment] 2017-02-04 16:27
Thinking about it again, this is an interesting use-case, you could open a
feature request for it!

**Comment by jevel0per** [comment] 2017-02-05 21:56
thanks for answering.
As far as i understood you recommended to make like this:
```
   
scheduler.getAllScheduledFutures().values()
                    .stream()
                    .flatMap(Collection::stream)
                    .filter(f -> f.getStats().getTotalRuns() > 0)
                    .forEach(IScheduledFuture::dispose);
```
truly when i did that, amount of tasks became to reduce. I can see it using `scheduler.getAllScheduledFutures().size()`, but it didn't help, i'm still get an OOM exception. I see a lot of _ScheduledFutureProxy, ScheduledTaskHandlerImpl, Registration_ with jvisualvm.

i had to code my own distributed scheduler based on local **ScheduledExecutorService, IMap, EntryUpdatedListener and MembershipListener** for fault-tolerant. I made it with similar API so i could easily swap them in the project. With my scheduler i don't get an OOM, but i think it's better to have a ready-made solution, because my solution based on top of hazelcast may have worse performance and bugs. It will be great if you make that feature.

To be honest i don't know how to open a feature request correctly, but i can do that if you help)

Also i've noticed the next thing:
```
  IScheduledExecutorService scheduler1 = hz.getScheduledExecutorService("scheduler1");
  IScheduledExecutorService scheduler2 = hz.getScheduledExecutorService("scheduler2");
  scheduler1.schedule(new Task(), 0, TimeUnit.MILLISECONDS);
  assertEquals(scheduler1.getAllScheduledFutures().size(), scheduler2.getAllScheduledFutures().size());
```
is it a normal? I thought that different schedulers had to have different IScheduledFuture

**Comment by tkountis** [comment] 2017-02-06 08:19
You came across the rather unfortunate defect, a fix is already in the works, here:
https://github.com/hazelcast/hazelcast/pull/9785 <https://github.com/hazelcast/hazelcast/pull/9785>

Your code looks correct, I would be interested though to see whats your scheduling rate, 
and cleaning rate (having in mind that the scheduling is done in a future time).
The reason you see those references in your visualvm, most likely, has to do with the fact
that, the futures are acting as listeners to partition events, therefore they are still strongly referenced.
However, in my mind, as long as your creation/cleanup phases are within a certain pace, you shouldn’t have a problem.

Can you share you test code ?

**Comment by jevel0per** [comment] 2017-02-07 06:09
you were right, the thing was in scheduling rate. when i reduce the rate of adding new tasks, i stopped to get an OOM.

but after ending of process a memory is still filled by a lot of instances:
```
com.hazelcast.spi.impl.eventservice.impl.Registration
com.hazelcast.scheduledexecutor.impl.ScheduledTaskHandlerImpl
com.hazelcast.scheduledexecutor.impl.ScheduledFutureProxy
com.hazelcast.internal.partition.impl.PartitionLostListenerAdapter
and java.util.concurrent.ConcurrentHashMap$Node
```

in the same time amount of Futures is 0.
Calling "Perform GC" from jvisualvm doesn't help.
Is it normal?

it's very hard to show you my working example because it's one of microservices basen on spring boot  so that  to test it need other services.

I wrote very simple example where i don't get an OOM, but there is the problem with filled memory i was talking about. i can show it if you want to.

**Comment by tkountis** [comment] 2017-02-07 11:33
Cool. Now regarding the remaining heap occupiers that you report, these are also legitimate
references, until you call `dispose()` on an IScheduledFuture, it is strongly referenced inside that HZ instance,
hence GC won’t clean it.

In other words, if you call dispose in *all* your futures, and then call ‘Perform GC’ then you should observe a clean up.

As for the example that you have written, that should also do, if you can share. I am mostly interested to see in what rate you 
do the scheduling and the disposal. eg. if you schedule a task every other second, for 24hrs then disposing once per day won’t do much
preventing the OOM. 

Last, reading your initial question, i would suggest on changing the implementation slightly. 
Instead of scheduling multiple tiny reminder tasks, you could schedule 1 task, and put your tasks in an IMap along with schedule time.
Then your single task, can periodically check that IMap and pop tasks that are due for running. This way, you should occupy significantly less resources.
Just my two cents.

~tk

**Comment by tkountis** [comment] 2017-02-09 22:49
@jevel0per do you have any update on that ? would you be able to share with us the test code so we can confirm if the scheduling/cleaning rates are the root cause ?

**Comment by tkountis** [comment] 2017-04-10 10:55
There has been no update regarding this. The believed root-cause seems to be the rate of the task creation along with the slower clean-up. Will close this, we can always re-open if needed.

**Closed by tkountis** 2017-04-10 10:55 UTC
Labels: Team: Core

**Comment by hitendrapratap** [comment] 2017-05-17 16:07
Why we have to keep tasks after its being executed?
