### ISSUE TITLE
*ListenerOnReconnectTest.testListenersNonSmartRoutingMultipleServer

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast#11115] opened 2017-08-16 15:00 UTC
On a PR submitted(https://github.com/hazelcast/hazelcast/pull/11109), the QueueItemListenerOnReconnectTest.testListenersNonSmartRoutingMultipleServer test failed. https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10213/testReport/junit/com.hazelcast.client.listeners/QueueItemListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

Stacktrace
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$8.run(AbstractListenersOnReconnectTest.java:482)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1086)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1103)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsOnMembers(AbstractListenersOnReconnectTest.java:475)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:468)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateOwnerNode(AbstractListenersOnReconnectTest.java:455)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingMultipleServer(AbstractListenersOnReconnectTest.java:406)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```
 (STDOUT)
```
Finished Running Test: testClusterReconnectDueToHeartbeatSmartRouting in 25.063 seconds.
14:35:17,260  INFO |testListenersNonSmartRoutingMultipleServer| - [LifecycleService] Thread-0 - hz.client_2 [dev] [3.9-SNAPSHOT] HazelcastClient 3.9-SNAPSHOT (20170816 - 4535e8e) is SHUTTING_DOWN
14:35:17,261  WARN |testListenersNonSmartRoutingMultipleServer| - [TestClientRegistry$MockedNodeConnection] pool-17-thread-1 - Server connection closed: null
14:35:17,261  INFO |testListenersNonSmartRoutingMultipleServer| - [ClientConnectionManager] Thread-0 - hz.client_2 [dev] [3.9-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5006, connection: MockedClientConnection{localAddress=[127.0.0.1]:40008, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteEndpoint=[127.0.0.1]:5006, lastReadTime=2017-08-16 14:35:12.940, lastWriteTime=2017-08-16 14:35:12.940, closedTime=2017-08-16 14:35:17.261, lastHeartbeatRequested=2017-08-16 14:35:12.777, lastHeartbeatReceived=2017-08-16 14:35:12.778, connected server version=3.9-SNAPSHOT}}
14:35:17,261  INFO |testListenersNonSmartRoutingMultipleServer| - [MockConnectionManager] pool-17-thread-1 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:40008, connection: MockedNodeConnection{ remoteEndpoint = [127.0.0.1]:40008, localEndpoint = [127.0.0.1]:5006, connectionId = 2}
14:35:17,262  INFO |testListenersNonSmartRoutingMultipleServer| - [ClientEndpointManager] hz._hzInstance_6_dev.event-34 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteEndpoint = [127.0.0.1]:40008, localEndpoint = [127.0.0.1]:5006, connectionId = 2}, principal='ClientPrincipal{uuid='93c14aae-ed20-4376-b9a5-d28a2746bb16', ownerUuid='3f6ff2d8-2fbe-4787-ac67-5a64803c6807'}, firstConnection=true, authenticated=true, clientVersion=3.9-SNAPSHOT, creationTime=1502893994027, latest statistics=null}
14:35:17,262  WARN |testListenersNonSmartRoutingMultipleServer| - [TwoWayBlockableExecutor] pool-17-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40008, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteEndpoint=[127.0.0.1]:5006, lastReadTime=2017-08-16 14:35:12.940, lastWriteTime=2017-08-16 14:35:12.940, closedTime=2017-08-16 14:35:17.261, lastHeartbeatRequested=2017-08-16 14:35:12.777, lastHeartbeatReceived=2017-08-16 14:35:12.778, connected server version=3.9-SNAPSHOT}}
14:35:17,262  INFO |testListenersNonSmartRoutingMultipleServer| - [LifecycleService] Thread-0 - hz.client_2 [dev] [3.9-SNAPSHOT] HazelcastClient 3.9-SNAPSHOT (20170816 - 4535e8e) is SHUTDOWN
14:35:17,262  INFO |testListenersNonSmartRoutingMultipleServer| - [LifecycleService] Thread-0 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] [127.0.0.1]:5006 is SHUTTING_DOWN
14:35:17,262  WARN |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] Terminating forcefully...
14:35:17,262  INFO |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] Shutting down connection manager...
14:35:17,262  INFO |testListenersNonSmartRoutingMultipleServer| - [MockConnectionManager] Thread-0 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5012, connection: MockConnection{localEndpoint=[127.0.0.1]:5006, remoteEndpoint=[127.0.0.1]:5012}
14:35:17,263  INFO |testListenersNonSmartRoutingMultipleServer| - [MockConnectionManager] Thread-0 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5002, connection: MockConnection{localEndpoint=[127.0.0.1]:5006, remoteEndpoint=[127.0.0.1]:5002}
14:35:17,263  WARN |testListenersNonSmartRoutingMultipleServer| - [MembershipManager] Thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] Member [127.0.0.1]:5006 - 3f6ff2d8-2fbe-4787-ac67-5a64803c6807 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5006 - 3f6ff2d8-2fbe-4787-ac67-5a64803c6807 this
14:35:17,263  INFO |testListenersNonSmartRoutingMultipleServer| - [MockConnectionManager] Thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5006, connection: MockConnection{localEndpoint=[127.0.0.1]:5012, remoteEndpoint=[127.0.0.1]:5006}
14:35:17,263  INFO |testListenersNonSmartRoutingMultipleServer| - [MockConnectionManager] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5006, connection: MockConnection{localEndpoint=[127.0.0.1]:5002, remoteEndpoint=[127.0.0.1]:5006}
14:35:17,263  INFO |testListenersNonSmartRoutingMultipleServer| - [MembershipManager] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Removing Member [127.0.0.1]:5006 - 3f6ff2d8-2fbe-4787-ac67-5a64803c6807
14:35:17,263  INFO |testListenersNonSmartRoutingMultipleServer| - [ClusterService] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] 

Members {size:2, ver:6} [
	Member [127.0.0.1]:5002 - de3866f3-a202-4f5a-9259-ddccef807a8f this
	Member [127.0.0.1]:5012 - dfd2eb3c-0b51-4a9e-a381-c8bf5eb1bf65
]

14:35:17,263  INFO |testListenersNonSmartRoutingMultipleServer| - [TransactionManagerService] hz._hzInstance_2_dev.cached.thread-9 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Committing/rolling-back alive transactions of Member [127.0.0.1]:5006 - 3f6ff2d8-2fbe-4787-ac67-5a64803c6807, UUID: 3f6ff2d8-2fbe-4787-ac67-5a64803c6807
14:35:17,263  INFO |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] Shutting down node engine...
14:35:17,263  INFO |testListenersNonSmartRoutingMultipleServer| - [TransactionManagerService] hz._hzInstance_12_dev.cached.thread-4 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] Committing/rolling-back alive transactions of Member [127.0.0.1]:5006 - 3f6ff2d8-2fbe-4787-ac67-5a64803c6807, UUID: 3f6ff2d8-2fbe-4787-ac67-5a64803c6807
14:35:17,263  INFO |testListenersNonSmartRoutingMultipleServer| - [ClusterService] hz._hzInstance_12_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] 

Members {size:2, ver:6} [
	Member [127.0.0.1]:5002 - de3866f3-a202-4f5a-9259-ddccef807a8f
	Member [127.0.0.1]:5012 - dfd2eb3c-0b51-4a9e-a381-c8bf5eb1bf65 this
]

14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [NodeExtension] Thread-0 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] Destroying node NodeExtension.
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] Hazelcast Shutdown is completed in 13 ms.
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [LifecycleService] Thread-0 - [127.0.0.1]:5006 [dev] [3.9-SNAPSHOT] [127.0.0.1]:5006 is SHUTDOWN
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [LifecycleService] Thread-0 - [127.0.0.1]:5009 [dev] [3.9-SNAPSHOT] [127.0.0.1]:5009 is SHUTTING_DOWN
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5009 [dev] [3.9-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [LifecycleService] Thread-0 - [127.0.0.1]:5009 [dev] [3.9-SNAPSHOT] [127.0.0.1]:5009 is SHUTDOWN
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [LifecycleService] Thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] [127.0.0.1]:5012 is SHUTTING_DOWN
14:35:17,275  WARN |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] Terminating forcefully...
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] Shutting down connection manager...
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [MockConnectionManager] Thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5002, connection: MockConnection{localEndpoint=[127.0.0.1]:5012, remoteEndpoint=[127.0.0.1]:5002}
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [MockConnectionManager] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5012, connection: MockConnection{localEndpoint=[127.0.0.1]:5002, remoteEndpoint=[127.0.0.1]:5012}
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [MembershipManager] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Removing Member [127.0.0.1]:5012 - dfd2eb3c-0b51-4a9e-a381-c8bf5eb1bf65
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [ClusterService] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] 

Members {size:1, ver:7} [
	Member [127.0.0.1]:5002 - de3866f3-a202-4f5a-9259-ddccef807a8f this
]

14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [TransactionManagerService] hz._hzInstance_2_dev.cached.thread-9 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Committing/rolling-back alive transactions of Member [127.0.0.1]:5012 - dfd2eb3c-0b51-4a9e-a381-c8bf5eb1bf65, UUID: dfd2eb3c-0b51-4a9e-a381-c8bf5eb1bf65
14:35:17,275  INFO |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] Shutting down node engine...
14:35:17,393  INFO |testListenersNonSmartRoutingMultipleServer| - [MigrationManager] hz._hzInstance_2_dev.migration - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Partition balance is ok, no need to re-partition cluster data... 
14:35:18,390  INFO |testListenersNonSmartRoutingMultipleServer| - [NodeExtension] Thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] Destroying node NodeExtension.
14:35:18,390  INFO |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] Hazelcast Shutdown is completed in 1115 ms.
14:35:18,390  INFO |testListenersNonSmartRoutingMultipleServer| - [LifecycleService] Thread-0 - [127.0.0.1]:5012 [dev] [3.9-SNAPSHOT] [127.0.0.1]:5012 is SHUTDOWN
14:35:18,390  INFO |testListenersNonSmartRoutingMultipleServer| - [LifecycleService] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] [127.0.0.1]:5002 is SHUTTING_DOWN
14:35:18,390  WARN |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Terminating forcefully...
14:35:18,391  INFO |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Shutting down connection manager...
14:35:18,391  INFO |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Shutting down node engine...
14:35:18,402  INFO |testListenersNonSmartRoutingMultipleServer| - [NodeExtension] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Destroying node NodeExtension.
14:35:18,403  INFO |testListenersNonSmartRoutingMultipleServer| - [Node] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] Hazelcast Shutdown is completed in 13 ms.
14:35:18,404  INFO |testListenersNonSmartRoutingMultipleServer| - [LifecycleService] Thread-0 - [127.0.0.1]:5002 [dev] [3.9-SNAPSHOT] [127.0.0.1]:5002 is SHUTDOWN
BuildInfo right after testListenersNonSmartRoutingMultipleServer(com.hazelcast.client.listeners.QueueItemListenerOnReconnectTest): BuildInfo{version='3.9-SNAPSHOT', build='20170816', buildNumber=20170816, revision=4535e8e, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testListenersNonSmartRoutingMultipleServer(com.hazelcast.client.listeners.QueueItemListenerOnReconnectTest):'
14:33:00, accumulated pauses: 1326 ms, max pause: 310 ms, pauses over 1000 ms: 0
14:33:05, accumulated pauses: 1008 ms, max pause: 103 ms, pauses over 1000 ms: 0
14:33:10, accumulated pauses: 1438 ms, max pause: 251 ms, pauses over 1000 ms: 0
14:33:15, accumulated pauses: 1105 ms, max pause: 272 ms, pauses over 1000 ms: 0
14:33:20, accumulated pauses: 892 ms, max pause: 116 ms, pauses over 1000 ms: 0
14:33:25, accumulated pauses: 658 ms, max pause: 27 ms, pauses over 1000 ms: 0
14:33:30, accumulated pauses: 673 ms, max pause: 38 ms, pauses over 1000 ms: 0
14:33:35, accumulated pauses: 654 ms, max pause: 80 ms, pauses over 1000 ms: 0
14:33:40, accumulated pauses: 53 ms, max pause: 4 ms, pauses over 1000 ms: 0
14:33:45, accumulated pauses: 31 ms, max pause: 1 ms, pauses over 1000 ms: 0
14:33:50, accumulated pauses: 63 ms, max pause: 15 ms, pauses over 1000 ms: 0
14:33:55, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
14:34:00, accumulated pauses: 35 ms, max pause: 5 ms, pauses over 1000 ms: 0
14:34:05, accumulated pauses: 32 ms, max pause: 1 ms, pauses over 1000 ms: 0
14:34:10, accumulated pauses: 37 ms, max pause: 6 ms, pauses over 1000 ms: 0
14:34:15, accumulated pauses: 37 ms, max pause: 5 ms, pauses over 1000 ms: 0
14:34:20, accumulated pauses: 48 ms, max pause: 13 ms, pauses over 1000 ms: 0
14:34:25, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
14:34:30, accumulated pauses: 47 ms, max pause: 11 ms, pauses over 1000 ms: 0
14:34:35, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
14:34:40, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
14:34:45, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
14:34:50, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
14:34:55, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
14:35:00, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
14:35:05, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
14:35:10, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
14:35:15, accumulated pauses: 98 ms, max pause: 72 ms, pauses over 1000 ms: 0

```

**Comment by ihsandemir** [comment] 2017-08-16 15:03
[new-lab-fast-pr #10213 test - testListenersNonSmartRoutingMultipleServer [Jenkins].htm.zip](https://github.com/hazelcast/hazelcast/files/1228590/new-lab-fast-pr.10213.test.-.testListenersNonSmartRoutingMultipleServer.Jenkins.htm.zip)

**Comment by ihsandemir** [comment] 2017-08-22 14:02
another run: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10366/

**Comment by hasancelik** [comment] 2017-08-28 09:41
*maintenance*
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$8.run(AbstractListenersOnReconnectTest.java:482)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:988)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsOnMembers(AbstractListenersOnReconnectTest.java:475)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:468)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateOwnerNode(AbstractListenersOnReconnectTest.java:455)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingMultipleServer(AbstractListenersOnReconnectTest.java:406)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast-client/242/testReport/junit/com.hazelcast.client.listeners/QueueItemListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

**Comment by tombujok** [comment] 2017-10-06 12:11
Hi @sancar What is the status on this one? Could we try to close it ASAP? I see two PRs, but to master not to maintenance branch.

**Comment by mdogan** [comment] 2017-10-06 12:14
@tombujok: Root cause of this failure is https://github.com/hazelcast/hazelcast/issues/11490. PR https://github.com/hazelcast/hazelcast/pull/11520 should fix it but it can't be back-ported to maintenance. Fix depends on cluster management improvements introduced in 3.9.

**Closed** 2017-10-09 11:18 UTC
Labels: Team: Client, Type: Test-Failure
