### ISSUE TITLE
[TEST-FAILURE] JCacheListenerTest.testSyncListener_shouldNotHang_whenCacheDestroyed

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4357] opened 2014-12-23 11:31 UTC
```
java.lang.AssertionError: Cache operations should not hang when sync listener is present!, failed to complete within 120 seconds , count left: 2
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:197)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:183)
	at com.hazelcast.cache.JCacheListenerTest.testSyncListener_shouldNotHang_AfterAction(JCacheListenerTest.java:311)
	at com.hazelcast.cache.JCacheListenerTest.testSyncListener_shouldNotHang_whenCacheDestroyed(JCacheListenerTest.java:270)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/415/testReport/junit/com.hazelcast.cache/JCacheListenerTest/testSyncListener_shouldNotHang_whenCacheDestroyed/

**Comment by bilalyasar** [comment] 2015-01-09 07:30
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/2528/testReport/junit/com.hazelcast.cache/JCacheListenerTest/testSyncListener_shouldNotHang_whenCacheDestroyed/

**Comment by bilalyasar** [comment] 2015-01-23 08:03
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK8/com.hazelcast$hazelcast/123/testReport/junit/com.hazelcast.cache/JCacheListenerTest/testSyncListener_shouldNotHang_whenCacheDestroyed/

**Comment by mesutcelik** [comment] 2015-02-25 13:11
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/160/com.hazelcast$hazelcast/testReport/com.hazelcast.cache/JCacheListenerTest/testSyncListener_shouldNotHang_whenCacheDestroyed/

**Comment by serkan-ozal** [comment] 2015-03-05 13:32
BTW, The problem was about that if cache is destroyed/closed between these lines

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractInternalCacheProxy.java#L304

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractInternalCacheProxy.java#L307

registered `CountDownLatch` is not cleared (counted down) since `notifyAndClearSyncListenerLatches` method cleared before. And also in `awaitLatch` method, there was no check about if cache is closed or destroyed. So waiting indefinitely `CountDownLatch` hangs caller thread even if cache is closed or destroyed.

Anyway this PR fixes this problem.

**Comment by mesutcelik** [comment] 2015-05-30 05:13
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/549/com.hazelcast$hazelcast/testReport/com.hazelcast.cache/JCacheListenerTest/testSyncListener_shouldNotHang_whenCacheDestroyed/

**Comment by serkan-ozal** [comment] 2015-05-30 07:06
From the Jenkins logs

```
...
02:27:15,460  WARN [EventService] hz._hzInstance_1700_dev.event-8520 - [127.0.0.1]:6843 [dev] [3.5-EA2-SNAPSHOT] Error while logging processing event
java.lang.UnsupportedOperationException: Event object not supported : com.hazelcast.cache.impl.client.CacheInvalidationMessage
	at com.hazelcast.cache.impl.CacheEventListenerAdaptor.handleEvent(CacheEventListenerAdaptor.java:125)
	at com.hazelcast.cache.impl.AbstractCacheService.dispatchEvent(AbstractCacheService.java:344)
	at com.hazelcast.cache.impl.AbstractCacheService.dispatchEvent(AbstractCacheService.java:51)
	at com.hazelcast.spi.impl.eventservice.impl.EventPacketProcessor.process(EventPacketProcessor.java:52)
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventPacketProcessor.run(RemoteEventPacketProcessor.java:38)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:190)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:174)
...
```

Possibly caused by this commit https://github.com/hazelcast/hazelcast/commit/090824a5d8b113cd7bf5b54afb9b5cfc48cd40b6#diff-1a37ba2b434ee879fd223d1ee8b69be7

**Comment by serkan-ozal** [comment] 2015-05-30 07:19
Another logs says that cache operation are retried when cache is destroyed since `RETRY_INVOCATION` is returned as `ExceptionAction` at here https://github.com/hazelcast/hazelcast/blob/5b743438236163460284662d6621937579e2ab05/hazelcast/src/main/java/com/hazelcast/cache/impl/operation/AbstractCacheOperation.java#L82

```
02:29:14,846  WARN [Invocation] hz._hzInstance_1700_dev.response - [127.0.0.1]:6843 [dev] [3.5-EA2-SNAPSHOT] Retrying invocation: Invocation{ serviceName='hz:impl:cacheService', op=com.hazelcast.cache.impl.operation.CachePutOperation{serviceName='null', partitionId=243, callId=7525, invocationTime=1432942154845, waitTimeout=-1, callTimeout=60000}, partitionId=243, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=240, callTimeout=60000, target=Address[127.0.0.1]:6842, backupsExpected=0, backupsCompleted=0}, Reason: com.hazelcast.cache.CacheNotExistsException: Cache is already destroyed or not created yet, on Member [127.0.0.1]:6842 this
02:29:15,346 FATAL [CachePutOperation] hz._hzInstance_1699_dev.partition-operation.thread-3 - [127.0.0.1]:6842 [dev] [3.5-EA2-SNAPSHOT] Cache is already destroyed or not created yet, on Member [127.0.0.1]:6842 this
com.hazelcast.cache.CacheNotExistsException: Cache is already destroyed or not created yet, on Member [127.0.0.1]:6842 this
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.<init>(AbstractCacheRecordStore.java:112)
	at com.hazelcast.cache.impl.CacheRecordStore.<init>(CacheRecordStore.java:61)
	at com.hazelcast.cache.impl.CacheService.createNewRecordStore(CacheService.java:59)
	at com.hazelcast.cache.impl.CachePartitionSegment$1.createNew(CachePartitionSegment.java:56)
	at com.hazelcast.cache.impl.CachePartitionSegment$1.createNew(CachePartitionSegment.java:53)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40)
	at com.hazelcast.cache.impl.CachePartitionSegment.getOrCreateCache(CachePartitionSegment.java:76)
	at com.hazelcast.cache.impl.AbstractCacheService.getOrCreateCache(AbstractCacheService.java:120)
	at com.hazelcast.cache.impl.operation.AbstractCacheOperation.beforeRun(AbstractCacheOperation.java:68)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:131)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:309)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:142)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)
02:29:15,847 FATAL [CachePutOperation] hz._hzInstance_1699_dev.partition-operation.thread-3 - [127.0.0.1]:6842 [dev] [3.5-EA2-SNAPSHOT] Cache is already destroyed or not created yet, on Member [127.0.0.1]:6842 this
com.hazelcast.cache.CacheNotExistsException: Cache is already destroyed or not created yet, on Member [127.0.0.1]:6842 this
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.<init>(AbstractCacheRecordStore.java:112)
	at com.hazelcast.cache.impl.CacheRecordStore.<init>(CacheRecordStore.java:61)
	at com.hazelcast.cache.impl.CacheService.createNewRecordStore(CacheService.java:59)
	at com.hazelcast.cache.impl.CachePartitionSegment$1.createNew(CachePartitionSegment.java:56)
	at com.hazelcast.cache.impl.CachePartitionSegment$1.createNew(CachePartitionSegment.java:53)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40)
	at com.hazelcast.cache.impl.CachePartitionSegment.getOrCreateCache(CachePartitionSegment.java:76)
	at com.hazelcast.cache.impl.AbstractCacheService.getOrCreateCache(AbstractCacheService.java:120)
	at com.hazelcast.cache.impl.operation.AbstractCacheOperation.beforeRun(AbstractCacheOperation.java:68)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:131)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:309)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:142)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)
02:29:16,348 FATAL [CachePutOperation] hz._hzInstance_1699_dev.partition-operation.thread-3 - [127.0.0.1]:6842 [dev] [3.5-EA2-SNAPSHOT] Cache is already destroyed or not created yet, on Member [127.0.0.1]:6842 this
com.hazelcast.cache.CacheNotExistsException: Cache is already destroyed or not created yet, on Member [127.0.0.1]:6842 this
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.<init>(AbstractCacheRecordStore.java:112)
	at com.hazelcast.cache.impl.CacheRecordStore.<init>(CacheRecordStore.java:61)
	at com.hazelcast.cache.impl.CacheService.createNewRecordStore(CacheService.java:59)
	at com.hazelcast.cache.impl.CachePartitionSegment$1.createNew(CachePartitionSegment.java:56)
	at com.hazelcast.cache.impl.CachePartitionSegment$1.createNew(CachePartitionSegment.java:53)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40)
	at com.hazelcast.cache.impl.CachePartitionSegment.getOrCreateCache(CachePartitionSegment.java:76)
	at com.hazelcast.cache.impl.AbstractCacheService.getOrCreateCache(AbstractCacheService.java:120)
	at com.hazelcast.cache.impl.operation.AbstractCacheOperation.beforeRun(AbstractCacheOperation.java:68)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:131)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:309)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:142)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)
```

**Comment by serkan-ozal** [comment] 2015-06-01 11:43
closed via https://github.com/hazelcast/hazelcast/commit/0e50fe9ca6d7e83daf6beb4489d6be3f2d6996a4

**Closed by serkan-ozal** 2015-06-01 11:43 UTC
Labels: Team: Core, Type: Defect
