### ISSUE TITLE
Hazelcast  client throws error after disconnection and reconnection

### ISSUE THREAD

**Issue by sfargier** [hazelcast/hazelcast#4222] opened 2014-12-03 16:03 UTC
Hi,
I am getting errors thrown by hazelcast after the java client gets disconnected then reconnected to the cluster.

**To reproduce:**
- a member starts a cluster
- the client connects to it
- the member gets killed -> the client gets the disconnected event after the heartbeat timeout (I registered a LifecycleListener)
- the member is restarted -> the client gets the connected event
- I try to use the client and get the error (see stack trace below)
Of course if I create a new client instance it works.

Also when that happens, I noticed that the TCP connection between the client and killed member was not closed (it still appears in ESTABLISHED state), even though the member process is effectively dead (it does not appear in any task manager). Closing the connection seems to make the client work again.

Thanks for the help!

Found with Hazelcast 3.3.2 on windows 7
Stack trace:
```
Error while fetching cluster partition table! 
java.util.concurrent.ExecutionException: com.hazelcast.spi.exception.TargetDisconnectedException
	at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:207)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:136)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:113)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitionsFrom(ClientPartitionServiceImpl.java:112)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.access$300(ClientPartitionServiceImpl.java:44)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl$RefreshTask.run(ClientPartitionServiceImpl.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: com.hazelcast.spi.exception.TargetDisconnectedException
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:113)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitionsFrom(ClientPartitionServiceImpl.java:112)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.access$300(ClientPartitionServiceImpl.java:44)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl$RefreshTask.run(ClientPartitionServiceImpl.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:194)
	... 10 more
```

**Comment by sancar** [comment] 2015-06-04 14:56
Closing since we could not reproduce the issue.

**Closed by sancar** 2015-06-04 14:56 UTC
Labels: PENDING, Team: Client

**Comment by renatojava** [comment] 2018-01-01 18:24
I have the same issue, for reproduce is simple, you might have two App, for example, two springboot app, the first is server and the second is client, first you up server and afterwards the second (client), if the server goes down and you up again, the client lost the connection and never reconnect.

**Comment by sancar** [comment] 2018-01-02 06:59
Hi @renatojava 
Client has a limit to try to open connections to server. If client exhaust all limits then it will not try to connect again. 
You may want to checkout following documentation to configure client behaviour regarding its lifecycle and behaviour when connection to cluster.
http://docs.hazelcast.org/docs/3.9.1/manual/html-single/index.html#handling-client-connection-failure
http://docs.hazelcast.org/docs/3.9.1/manual/html-single/index.html#configuring-client-connection-strategy

If documentation is not clear or if you have further problems, please use our google group to ask questions.
https://groups.google.com/forum/#!forum/hazelcast
When we found a bug needed to be fix, or a enhancement idea that is caused by your use case, we can open an issue here. 
Regards.
