### ISSUE TITLE
ClientMapNearCacheBasicTest.whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue_onDataAdapter

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10421] opened 2017-04-24 08:39 UTC
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (499 vs. 500) (NearCacheStatsImpl{ownedEntryCount=500, ownedEntryMemoryCost=74400, creationTime=1492996401029, hits=0, misses=1001, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<499> but was:<500>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:271)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$2.run(NearCacheTestUtils.java:291)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:288)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue(AbstractNearCacheBasicTest.java:1036)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue_onDataAdapter(AbstractNearCacheBasicTest.java:1008)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.lang.Thread.run(Thread.java:701)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/84/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheBasicTest/whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue_onDataAdapter_format_BINARY_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/550/

**Comment by Donnerbart** [comment] 2017-04-24 08:44
Duplicate of https://github.com/hazelcast/hazelcast/issues/10389

**Closed by Donnerbart** 2017-04-24 08:44 UTC
Labels: Team: Client, Team: Core, Type: Test-Failure
