### ISSUE TITLE
PartitionMigrationListenerTest.testMigrationListenerCalledOnlyOnceWhenMigrationHappens [HZ-1771]

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#17776] opened 2020-10-27 17:16 UTC
The `com.hazelcast.partition.PartitionMigrationListenerTest.testMigrationListenerCalledOnlyOnceWhenMigrationHappens` failed on PR builder (`master` branch):
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2776/

**Stacktrace**
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.partition.PartitionMigrationListenerTest.lambda$testMigrationListenerCalledOnlyOnceWhenMigrationHappens$2(PartitionMigrationListenerTest.java:281)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1253)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1355)
	at com.hazelcast.partition.PartitionMigrationListenerTest.testMigrationListenerCalledOnlyOnceWhenMigrationHappens(PartitionMigrationListenerTest.java:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vbekiaris** [comment] 2021-02-08 15:32
The root cause is the same as here https://github.com/hazelcast/hazelcast/issues/16299#issuecomment-775201557.

**Comment by Fly-Style** [comment] 2021-02-12 07:55
Since this test is not reproducible both locally and on Jenkins, we can close an issue.
WDYT @mmedenjak ?

**Comment by vbekiaris** [comment] 2021-02-12 08:03
I agree we can close this with same reasoning as discussed [here](https://github.com/hazelcast/hazelcast/issues/16299#issuecomment-775201557). If those tests fail again, then we can reconsider the test assertions.

**Comment by mmedenjak** [comment] 2021-04-04 18:22
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4392

**Comment by mmedenjak** [comment] 2021-08-30 12:09
Moving to 5.1. Feel free to send a PR with some logging if you have some ideas.

**Comment by olukas** [comment] 2022-07-27 07:25
Failed on `master` on MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MicrosoftJDK17/22/testReport/com.hazelcast.partition/PartitionMigrationListenerTest/testMigrationListenerCalledOnlyOnceWhenMigrationHappens/

**Comment by arodionov** [comment] 2022-08-12 15:31
Failed on PR https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/12565/display/redirect
details: [build log](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12565/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12565/Hazelcast-pr-builder-12565.zip)

**Comment by olukas** [comment] 2022-08-31 06:12
Failed on `master` on CorrettoJDK11: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-CorrettoJDK11/49/testReport/com.hazelcast.partition/PartitionMigrationListenerTest/testMigrationListenerCalledOnlyOnceWhenMigrationHappens/

**Comment by olukas** [comment] 2022-09-01 06:26
Failed on `5.1.z` on OracleJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK11/49/testReport/com.hazelcast.partition/PartitionMigrationListenerTest/testMigrationListenerCalledOnlyOnceWhenMigrationHappens/

**Comment by ahmetmircik** [comment] 2022-11-22 07:44
Seems this reasoning is still valid: https://github.com/hazelcast/hazelcast/issues/16299#issuecomment-775201557

Test has wrong expectations and more than 1 time calling of migration listener is legitimate.

**Comment by ahmetmircik** [comment] 2022-11-22 07:48
@vbekiaris does it make sense to relax expectations of the test WDYT?

**Comment by vbekiaris** [comment] 2022-11-22 08:06
@ahmetmircik yes, let's do that

**Comment by olukas** [comment] 2022-11-24 08:08
Failed again on _master_ with OracleJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK17/57/testReport/com.hazelcast.partition/PartitionMigrationListenerTest/testMigrationListenerCalledOnlyOnceWhenMigrationHappens/

**Comment by arodionov** [comment] 2022-12-02 11:51
Failed again in a PR build https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/14695/display/redirect 

`[ERROR]   PartitionMigrationListenerTest.testMigrationListenerCalledOnlyOnceWhenMigrationHappens:280->HazelcastTestSupport.assertTrueEventually:1349->HazelcastTestSupport.assertTrueEventually:1247->lambda$testMigrationListenerCalledOnlyOnceWhenMigrationHappens$2:288 expected:<0> but was:<3>
`

**Comment by olukas** [comment] 2023-01-05 06:47
Reopening as issue occurred again on: _5.2.z_ (commit b8f9cc61f13f1de1443b932ecc9e211fc296bf6f)
with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK11/67/testReport/com.hazelcast.partition/PartitionMigrationListenerTest/testMigrationListenerCalledOnlyOnceWhenMigrationHappens/

@ahmetmircik Could you please backport the fix to `5.2.z` branch?

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<10> but was:<6>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.partition.PartitionMigrationListenerTest.lambda$testMigrationListenerCalledOnlyOnceWhenMigrationHappens$2(PartitionMigrationListenerTest.java:287)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1247)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1349)
	at com.hazelcast.partition.PartitionMigrationListenerTest.testMigrationListenerCalledOnlyOnceWhenMigrationHappens(PartitionMigrationListenerTest.java:280)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>


<details><summary>Standard output:</summary>

```
Finished Running Test: testMigrationStats_afterPartitionsLost_when_NO_MIGRATION in 4.046 seconds.
23:08:31,952  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [LifecycleService] Thread-20363 - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
23:08:31,953  WARN |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [Node] Thread-20363 - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Terminating forcefully...
23:08:31,953  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [Node] Thread-20363 - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Shutting down connection manager...
23:08:31,953  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [MockServer] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=ac12316a-4d27-4533-9866-009355007e5b], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=fd8570ff-842d-45d3-ac15-f36b4aa9bd83], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=ac12316a-4d27-4533-9866-009355007e5b], alive=false}
23:08:31,953  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [MockServer] Thread-20363 - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5701, uuid=fd8570ff-842d-45d3-ac15-f36b4aa9bd83], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=ac12316a-4d27-4533-9866-009355007e5b], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=fd8570ff-842d-45d3-ac15-f36b4aa9bd83], alive=false}
23:08:31,953  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [MembershipManager] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Removing Member [127.0.0.1]:5702 - ac12316a-4d27-4533-9866-009355007e5b
23:08:31,953  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [PartitionStateManager] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Storing snapshot of partition assignments while removing UUID ac12316a-4d27-4533-9866-009355007e5b
23:08:31,954  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [ClusterService] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - fd8570ff-842d-45d3-ac15-f36b4aa9bd83 this
]

23:08:31,954  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [TransactionManagerService] hz.quizzical_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: ac12316a-4d27-4533-9866-009355007e5b
23:08:31,954  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [Node] Thread-20363 - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Shutting down node engine...
23:08:31,962  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [MigrationManager] hz.quizzical_snyder.migration - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Partition balance is ok, no need to repartition.
23:08:31,970  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [NodeExtension] Thread-20363 - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Destroying node NodeExtension.
23:08:31,970  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [Node] Thread-20363 - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Hazelcast Shutdown is completed in 17 ms.
23:08:31,970  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [LifecycleService] Thread-20363 - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
23:08:31,971  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [LifecycleService] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
23:08:31,971  WARN |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [Node] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Terminating forcefully...
23:08:31,971  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [Node] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Shutting down connection manager...
23:08:31,971  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [Node] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Shutting down node engine...
23:08:31,990  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [NodeExtension] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Destroying node NodeExtension.
23:08:31,992  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [Node] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Hazelcast Shutdown is completed in 21 ms.
23:08:31,992  INFO |testMigrationListenerCalledOnlyOnceWhenMigrationHappens| - [LifecycleService] Thread-20363 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testMigrationListenerCalledOnlyOnceWhenMigrationHappens(com.hazelcast.partition.PartitionMigrationListenerTest): BuildInfo{version='5.2.2-SNAPSHOT', build='20230104', buildNumber=20230104, revision=b8f9cc6, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testMigrationListenerCalledOnlyOnceWhenMigrationHappens(com.hazelcast.partition.PartitionMigrationListenerTest):'
23:06:25, accumulated pauses: 86 ms, max pause: 20 ms, pauses over 1000 ms: 0
23:06:30, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:06:35, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:06:40, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:06:45, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:06:50, accumulated pauses: 55 ms, max pause: 11 ms, pauses over 1000 ms: 0
23:06:55, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:07:00, accumulated pauses: 52 ms, max pause: 6 ms, pauses over 1000 ms: 0
23:07:05, accumulated pauses: 39 ms, max pause: 5 ms, pauses over 1000 ms: 0
23:07:10, accumulated pauses: 56 ms, max pause: 7 ms, pauses over 1000 ms: 0
23:07:15, accumulated pauses: 54 ms, max pause: 2 ms, pauses over 1000 ms: 0
23:07:20, accumulated pauses: 83 ms, max pause: 23 ms, pauses over 1000 ms: 0
23:07:25, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:07:30, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:07:35, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:07:40, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:07:45, accumulated pauses: 56 ms, max pause: 1 ms, pauses over 1000 ms: 0
23:07:50, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:07:55, accumulated pauses: 54 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:08:00, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:08:05, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:08:10, accumulated pauses: 57 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:08:15, accumulated pauses: 63 ms, max pause: 7 ms, pauses over 1000 ms: 0
23:08:20, accumulated pauses: 66 ms, max pause: 8 ms, pauses over 1000 ms: 0
23:08:25, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:08:30, accumulated pauses: 401 ms, max pause: 383 ms, pauses over 1000 ms: 0



```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-OracleJDK11/67/

**Comment by ahmetmircik** [comment] 2023-01-05 07:58
Already backported the fix, but seems the fix couldn't prevent this latest incident.

**Comment by olukas** [comment] 2023-01-05 08:57
Ok, in that case I'm moving milestone to `5.3 Backlog` since it's probable that issue is still also on master branch.

**Comment by ahmetmircik** [comment] 2023-05-03 08:53
This is a failure related to testing as far as we know, and seems not failed recently, closing it by thinking wishfully.
See this for further info: https://github.com/hazelcast/hazelcast/issues/16299#issuecomment-775201557.

**Comment by sumnerib** [comment] 2023-10-30 12:30
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/87/testReport/junit/com.hazelcast.partition/PartitionMigrationListenerTest/testMigrationListenerCalledOnlyOnceWhenMigrationHappens/

**Comment by olukas** [comment] 2024-08-02 11:27
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.

**Closed by olukas** 2024-08-02 11:27 UTC
Labels: Team: Core, Type: Test-Failure, Source: Internal, Module: Partitioning, to-jira
