### ISSUE TITLE
ThreadLeakClientTest.testThreadLeak

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10655] opened 2017-05-29 06:44 UTC
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:201)
	at java.lang.Thread.join(Thread.java:722)
	at java.lang.Thread.join(Thread.java:683)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:778)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:770)
	at classloading.ThreadLeakTest.assertHazelcastThreadShutdown(ThreadLeakTest.java:68)
	at classloading.ThreadLeakClientTest.testThreadLeak(ThreadLeakClientTest.java:45)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/600/testReport/junit/classloading/ThreadLeakClientTest/testThreadLeak/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/601/com.hazelcast$hazelcast-client/testReport/classloading/ThreadLeakClientTest/testThreadLeak/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/603/testReport/junit/classloading/ThreadLeakClientTest/testThreadLeak/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/1292/testReport/junit/classloading/ThreadLeakClientTest/testThreadLeak/

**Comment by sancar** [comment] 2017-05-29 07:13
From a quick look, this test failure is caused by com.hazelcast.test.jitter.JitterThread. 
It is set to daemon. Should we not wait for daemon threads for the tests ? 
Since this is a static thread per process we can't wait for it to join in hazelcast.shutdown. So it seems logical to me exclude daemon threads from ThreadClientLeakTest. One question though, when this `JitterThread` daemon actually die? From code it looks like never, ever. @jerrinot 

I checked the codebase, there are 2 other daemon threads in hazelcast codebase, 
One is HealthMonitorThread, and the other is `SimpleGarbageCollector extends Thread` .

Health monitor being daemon seems wrong, since we are actually waiting it to finish.

I don't know if there is a special reason behind `SimpleGarbageCollector` being daemon ? @mdogan

**Comment by Donnerbart** [comment] 2017-05-29 10:50
I would not exclude daemon threads, since they should eventually shutdown as well. We may not be able to wait for them to join in `Hazelcast.shutdown()`, but we should be able to do so in the test code. Just imagine someone starting and stopping Hazelcast in the same JVM -> piling up daemon threads sounds like a very bad idea.

The `JitterThread` maybe an exception, because it is not started by Hazelcast, but the test environment. It maybe shutdown after the test completes, so we shouldn't wait for it in the `ThreadLeakTest`. I've added a whitelist for the test here: https://github.com/hazelcast/hazelcast/pull/10667

I can't find the `SimpleGarbageCollector` in `master` and `maintenance-3.x`. Where is that class located?

**Comment by sancar** [comment] 2017-05-29 10:53
SimpleGarbageCollector is from enterprise

**Comment by Donnerbart** [comment] 2017-05-29 11:06
Stupid me... Actually the `ThreadLeakTest`s are completely missing on EE side. I'll create a PR to add them.

**Comment by Donnerbart** [comment] 2017-05-31 10:20
Fixed via https://github.com/hazelcast/hazelcast/pull/10667

**Comment by hasancelik** [comment] 2017-06-05 08:04
```
05:18:22 Running classloading.ThreadLeakClientTest
07:58:36 Build timed out (after 240 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1301/consoleFull#1060638406255793cf-53c4-4118-98a6-ea4bf097b7a5

This test have been aborting since fix, check the build history:

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/

**Closed** 2017-06-06 11:18 UTC
Labels: Team: Client, Team: Core, Type: Test-Failure
