### ISSUE TITLE
ManCenter - Shutting down a node from within ManCenter seems to prevent a node restarting

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#7101] opened 2015-12-17 17:07 UTC
Cluster of 2 nodes.  We shut them both down from ManCenter (3.6-EA3-SNAPSHOT).  We then attempt to restart both nodes.  Frequently, one of the nodes on restart will immediately shutdown (without error).  Restarting it again for a second time and everything is fine.

To be clear: On the first restart, both nodes come up, form a cluster (we see this cluster formation on both nodes), and then one node shuts itself down (or is told to shutdown).

**Comment by bilalyasar** [comment] 2015-12-21 14:06
@StanAccy, i am trying to reproduce your case, how you restart the node? can you explain a little bit?

**Comment by StanAccy** [comment] 2015-12-21 15:13
From a simple script - we were using the StartServer.class from the HZ Enterprise JAR.
The logs didnt tell us anything except that the node started, formed a cluster, then initiated an orderly shutdown.  We saw this behavior repeatedly.  In the end we just started killing the process directly on the box.

**Comment by bilalyasar** [comment] 2015-12-21 15:38
i still couldn't reproduce your case, only when i click the shutdown button 2 times, your scenario happens, but i don't think you press the button 2 times..  By the way i am shutting down the members one by one from members own page. then start 2 nodes programatically.

**Comment by StanAccy** [comment] 2015-12-21 15:55
We had two nodes, I shut one down, then the other - node by node.  Restart
both nodes from scripts.  one stayed up, one shut itself down.

N

**Comment by muratayan** [comment] 2015-12-24 10:00
@StanAccy I was also not able to reproduce this issue. Can you please provide a screencast of the procedure of closing nodes through mancenter and restarting them?

**Comment by mesutcelik** [comment] 2015-12-28 07:41
I think I was able to reproduce problem. Each shutdown request is created and kept in a queue inside management center until hazelcast member retrieves the shutdown request from the queue. Shutdown Request is only cleaned up when Management Center receives shutdown completed message.

So in your case, either Management Center did not receive `completed` message or there was no running member when shutdown operation is triggered from Management Center. That means when hazelcast member has been started, it retrieved the old shutdown request and applied it by shutting down itself.

Unfortunately, there is no easy workaround for this right now. Instead of each hazelcast member polling tasks for themselves, Management Center should directly apply the operation on the member in future.

**Closed** 2016-05-12 16:32 UTC
Labels: Team: Integration, Type: Defect
