### ISSUE TITLE
ClientMapUnboundReturnValues_TxnTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11537] opened 2017-10-09 08:51 UTC
**testClientTxnMap_withException_NoPreCheck**
```
com.hazelcast.transaction.TransactionException: com.hazelcast.map.QueryResultSizeExceededException: This exception has been thrown to prevent an OOME on this Hazelcast instance. An OOME might occur when a query collects large data sets from the whole cluster, e.g. by calling IMap.values(), IMap.keySet() or IMap.entrySet(). See GroupProperty.QUERY_RESULT_SIZE_LIMIT for further details.
	at com.hazelcast.map.impl.query.QueryResult.add(QueryResult.java:90)
	at com.hazelcast.map.impl.query.QueryResultProcessor.populateResult(QueryResultProcessor.java:40)
	at com.hazelcast.map.impl.query.QueryResultProcessor.populateResult(QueryResultProcessor.java:27)
	at com.hazelcast.map.impl.query.QueryRunner.populateNonEmptyResult(QueryRunner.java:175)
	at com.hazelcast.map.impl.query.QueryRunner.populateResult(QueryRunner.java:151)
	at com.hazelcast.map.impl.query.QueryRunner.runIndexOrPartitionScanQueryOnOwnedPartitions(QueryRunner.java:122)
	at com.hazelcast.map.impl.query.QueryOperation.run(QueryOperation.java:65)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:569)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:554)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:326)
	at com.hazelcast.map.impl.query.QueryDispatcher.dispatchFullQueryOnAllMembersOnQueryThread(QueryDispatcher.java:100)
	at com.hazelcast.map.impl.query.QueryDispatcher.dispatchFullQueryOnQueryThread(QueryDispatcher.java:81)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.dispatchOnQueryThreads(MapQueryEngineImpl.java:156)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.doRunQueryOnQueryThreads(MapQueryEngineImpl.java:149)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.runQueryOnAllPartitions(MapQueryEngineImpl.java:128)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.execute(MapQueryEngineImpl.java:88)
	at com.hazelcast.map.impl.tx.TransactionalMapProxy.values(TransactionalMapProxy.java:411)
	at com.hazelcast.client.impl.protocol.task.transactionalmap.TransactionalMapValuesWithPredicateMessageTask.innerCall(TransactionalMapValuesWithPredicateMessageTask.java:49)
	at com.hazelcast.client.impl.protocol.task.AbstractTransactionalMessageTask.call(AbstractTransactionalMessageTask.java:34)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.addResultsOfPredicate(MapQueryEngineImpl.java:195)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.doRunQueryOnQueryThreads(MapQueryEngineImpl.java:150)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.runQueryOnAllPartitions(MapQueryEngineImpl.java:128)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.execute(MapQueryEngineImpl.java:88)
	at com.hazelcast.map.impl.tx.TransactionalMapProxy.values(TransactionalMapProxy.java:411)
	at com.hazelcast.client.impl.protocol.task.transactionalmap.TransactionalMapValuesWithPredicateMessageTask.innerCall(TransactionalMapValuesWithPredicateMessageTask.java:49)
	at com.hazelcast.client.impl.protocol.task.AbstractTransactionalMessageTask.call(AbstractTransactionalMessageTask.java:34)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.proxy.txn.ClientTransactionUtil.invoke(ClientTransactionUtil.java:46)
	at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:61)
	at com.hazelcast.client.proxy.txn.ClientTxnMapProxy.values(ClientTxnMapProxy.java:241)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.internalRunTxn(ClientMapUnboundReturnValuesTestSupport.java:269)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.runClientMapTestTxn(ClientMapUnboundReturnValuesTestSupport.java:114)
	at com.hazelcast.client.map.ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withException_NoPreCheck(ClientMapUnboundReturnValues_TxnTest.java:31)
```

**testClientTxnMap_withException_PreCheck**
```
com.hazelcast.transaction.TransactionException: com.hazelcast.map.QueryResultSizeExceededException: This exception has been thrown to prevent an OOME on this Hazelcast instance. An OOME might occur when a query collects large data sets from the whole cluster, e.g. by calling IMap.values(), IMap.keySet() or IMap.entrySet(). See GroupProperty.QUERY_RESULT_SIZE_LIMIT for further details. The configured query result size limit is 100000 items. Result size exceeded in local pre-check.
	at com.hazelcast.map.impl.query.QueryResultSizeLimiter.precheckMaxResultLimitOnLocalPartitions(QueryResultSizeLimiter.java:139)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.adjustQuery(MapQueryEngineImpl.java:105)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.execute(MapQueryEngineImpl.java:86)
	at com.hazelcast.map.impl.tx.TransactionalMapProxy.values(TransactionalMapProxy.java:411)
	at com.hazelcast.client.impl.protocol.task.transactionalmap.TransactionalMapValuesWithPredicateMessageTask.innerCall(TransactionalMapValuesWithPredicateMessageTask.java:49)
	at com.hazelcast.client.impl.protocol.task.AbstractTransactionalMessageTask.call(AbstractTransactionalMessageTask.java:34)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.proxy.txn.ClientTransactionUtil.invoke(ClientTransactionUtil.java:46)
	at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:61)
	at com.hazelcast.client.proxy.txn.ClientTxnMapProxy.values(ClientTxnMapProxy.java:241)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.internalRunTxn(ClientMapUnboundReturnValuesTestSupport.java:269)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.runClientMapTestTxn(ClientMapUnboundReturnValuesTestSupport.java:114)
	at com.hazelcast.client.map.ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withException_PreCheck(ClientMapUnboundReturnValues_TxnTest.java:36)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1492/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1493/#showFailuresLink
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1495/#showFailuresLink
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1496/#showFailuresLink

**Comment by tombujok** [comment] 2017-10-09 11:16
Is it a new regression? and is it critical?

**Comment by sancar** [comment] 2017-10-09 11:20
This looks like regression that we need to fix.

**Comment by Donnerbart** [comment] 2017-10-09 11:24
There have been recent changes to the `TxnMap`, but not to the `QueryResultSizeLimiter`. So I guess the txn changes may be the reason (just a speculation though).

**Comment by ahmetmircik** [comment] 2017-10-09 14:32
As far as i see, this exception was always there but tests were passing without failure, only logs contained exception messages. Recent changes [here](https://github.com/hazelcast/hazelcast/pull/11478) surfaced it. So this is not a new regression. See logs [here](https://s3.console.aws.amazon.com/s3/object/j-artifacts/Hazelcast-3.x-nightly/1490) for a previous run to see exception is not new.

**Comment by tombujok** [comment] 2017-10-09 19:04
That's a great finding @ahmetmircik. @sancar could you verify that and close the issue?

**Comment by sancar** [comment] 2017-10-10 10:26
@tombujok I am working on it.

**Closed** 2017-10-10 13:22 UTC
Labels: Team: Client, Team: Core, Type: Test-Failure
