### ISSUE TITLE
Invalid connection type: NONE

### ISSUE THREAD

**Issue by dimas** [hazelcast/hazelcast#10480] opened 2017-05-03 10:47 UTC
Hazelcast 3.7.3
Looks like all of the nodes complain about one node logging "Cannot get client information from: [10.0.138.213]:5701"

Logged by com.hazelcast.client.ClientEngine
```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid connection type: NONE
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:85)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
	at com.hazelcast.client.impl.ClientEngineImpl.getConnectedClientStats(ClientEngineImpl.java:499)
	at com.hazelcast.util.PhoneHome.phoneHome(PhoneHome.java:143)
	at com.hazelcast.util.PhoneHome$1.run(PhoneHome.java:80)
	at com.hazelcast.spi.impl.executionservice.impl.SkipOnConcurrentExecutionDecorator.run(SkipOnConcurrentExecutionDecorator.java:40)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: java.lang.IllegalArgumentException: Invalid connection type: NONE
	at com.hazelcast.client.impl.ClientEndpointImpl.getClientType(ClientEndpointImpl.java:175)
	at com.hazelcast.client.impl.operations.GetConnectedClientsOperation.run(GetConnectedClientsOperation.java:43)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:396)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:111)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
	... 11 common frames omitted
```

The 10.0.138.213 itself logs lots of:
```
java.lang.IllegalArgumentException: Invalid connection type: NONE
        at com.hazelcast.client.impl.ClientEndpointImpl.getClientType(ClientEndpointImpl.java:175)
        at com.hazelcast.client.impl.ClientHeartbeatMonitor.monitor(ClientHeartbeatMonitor.java:84)
        at com.hazelcast.client.impl.ClientHeartbeatMonitor.run(ClientHeartbeatMonitor.java:79)
        at com.hazelcast.spi.impl.executionservice.impl.SkipOnConcurrentExecutionDecorator.run(SkipOnConcurrentExecutionDecorator.java:40)
        at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

**Comment by sancar** [comment] 2017-05-04 06:49
It should be impossible to get a connection without NONE type. 
It is caused by changes here https://github.com/hazelcast/hazelcast/pull/9183 
It changes the logic of how connections handled on server side. 
These issues are fixed in 3.7.6.

**Closed by sancar** 2017-05-04 06:49 UTC
Labels: Team: Client
