### ISSUE TITLE
[map] IMap.get arbitrarily works slowly with big values

### ISSUE THREAD

**Issue by olessio** [hazelcast/hazelcast#9776] opened 2017-01-30 10:14 UTC
I have a simple test:
- the server adds, for example, 100 records into the map; value length is about 800K
- the client gets all values one by one

As a result, I see that sometimes (few times per 100 invocations) it takes about 5 seconds to do IMap.get. With increasing value length number of 'slow' invocations increases as well.

Increasing buffer size helps, but since I can't predict the value size, I assume that I may still face the same problem.

I use:
java 1.8.0_102
hazelcast 3.7.4
mac os el capitan

Reproducer can be found [here](https://github.com/olessio/HazelcastTest/blob/master/src/main/java/ServerAndClient.java)

In the attachment you can find:
1) jfr files
2) thread dump at the moment, when the application 'stuck'

[threaddump_and_jfr.zip](https://github.com/hazelcast/hazelcast/files/738608/threaddump_and_jfr.zip)

**Comment by gAmUssA** [comment] 2017-01-30 20:30
@olessio running time is very small.
server side recording - 33 sec
client side - 6 sec

Could you provide JFR recording for longer run? couple mins at least?

**Comment by olessio** [comment] 2017-02-03 09:37
Here is new JFR recording, for the app, where client and server are in the same jvm.
I've got to slow "get" invocations:
10:26:20.080 - 10:26:25.203
10:26:29.910 - 10:26:35.041

[clientandserver.jfr.zip](https://github.com/hazelcast/hazelcast/files/750006/clientandserver.jfr.zip)

**Comment by mmedenjak** [comment] 2017-07-12 12:57
Hi @olessio! Thanks for the detailed description and the reproducer and recordings. I haven't been able to detect the cause by looking at the recordings but here are some things I have observed : 
- the issue can also be observed if instead of a client there is an another member (server). This means that the client code is not the cause but the server code
- the issue does not appear in hazelcast 3.8.3. I am not sure which change caused the fix but can you try upgrading to that version?

**Comment by sancar** [comment] 2017-08-23 10:23
Hi @olessio again, 
We are closing the ticket since we could not get feedback from you and we could not reproduce the problem. Please try 3.8.4 . If issue remains, you can always reopen the ticket.

**Closed by sancar** 2017-08-23 10:23 UTC
Labels: Team: Client, Team: Core, Type: Defect
