### ISSUE TITLE
Reducing checktyle suppresions

### ISSUE THREAD

**Issue by bontorhumala** [hazelcast/hazelcast#7712] opened 2016-03-09 20:23 UTC
Hi, some friends and I are looking to contribute to Hazelcast as part of university project - see the [twitter account](https://twitter.com/delftswa) and last year [project](http://delftswa.github.io/). We noted that Hazelcast considers checkstyle as technical debt. We are not looking at refactoring codes. Mostly simpler stuff like adding Javadoc, remove modifier redundancy, ordering of variables - constructor - methods, adding a header to files, etc.

Would you guys appreciate this kind of fixes i.e reduce the number of checkstyle error/suppressions? Are there any concerns? Thanks

**Comment by Donnerbart** [comment] 2016-03-09 20:52
We like all kinds of contribution and reducing technical debt is a valuable task.

The biggest risk I see is that your work could interfere with our release cycle. Normally we do this kind of cleanups early, directly after a release. In this way we don't mix cleanup and feature PR at the end of the development phase.

For our main project this window is closing soon. But we recently pulled out a lot of modules as plugins into their own repositories (http://hazelcast.org/plugins/). I'll check with our Integration Team if we could put you on some of those projects.

May I ask how many people you are? Could your group work together on a single PR or do you need work for several groups?

**Comment by bontorhumala** [comment] 2016-03-09 21:14
To clear things us, our group is the only one working on Hazelcast as other groups are working in other open source projects. There are 4 of us in this group. We could work together on a single PR. When will the window be closed? Maybe the deadline fits perfectly to our deadline :)

**Comment by Donnerbart** [comment] 2016-03-09 21:22
There is no exact date yet, but there is already a huge amount of cleanup PRs pending for Hazelcast 3.7 (mostly improvements of what is public and what is private API). I'll bring your offer up in our standup tomorrow. I think we should be able to find a task for your group.

When is your deadline? Since we also need time to review we should pick something suitable for your available time :)

**Comment by bontorhumala** [comment] 2016-03-09 21:42
The project deadline is the first week of April but now that you are offering specific task (which is even better for us), we would really appreciate it if you can give the task(s) by tomorrow or friday so that we can work on it as soon as possible :) Thanks for bringing it up tomorrow!

The project is mainly about analysing the project, but contributing is a small part of it as a way to get a better feel of the project. We have started working on contribution for the past 2-3 weeks and got 1 merged - https://github.com/hazelcast/hazelcast/pull/7577. Currently, we are looking to give more contributions. Thats why we aim to finish our contributions by Tuesday next week.

**Comment by Donnerbart** [comment] 2016-03-09 22:00
Okay, that's a quite tight schedule. I'll try to find a little task which fits into this then.

**Comment by Donnerbart** [comment] 2016-03-10 12:21
I had a look at the plugins and there is not really much to do anymore (I already did a cleanup session after we pulled them out). Nevertheless we have some other options :)

We have a concept for community contributions called HEP (Hazelcast Enhancement Proposals). You can find a list of open feature requests here: https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Enhancement+Proposals#HazelcastEnhancementProposals-SomeOpenFeatureRequests

I would suggest to sort the table by expected effort and have a look at S/S or S/M tasks. This would be the way to go if you would like to actually do some real coding :)

If you want to stick with CheckStyle cleanups we only seem to have the main project left at the moment (plugins are already quite clean).

For the start I would avoid the removal of `NPathComplexity` and `CyclomaticComplexity`, which normally needs quite a bit of refactoring. This is no general problem, but may delay the review process and clash with your deadline. Also suppressions like `MethodCount`, `ClassFanOutComplexity`, `ClassDataAbstractionCoupling` etc. will most probably stay forever, since we have some classes like `IMap` where we cannot reduce the number of methods. So those are no good candidates to look at.

You could have a look at wildcard suppressions like `checks=""`, which actually disables CheckStyle for a whole class or package. You can remove such a suppression, run CheckStyle and see what pops up. A good strategy is to fix low hanging fruits and add a finer suppression for e.g. `NPathComplexity`, `CyclomaticComplexity` or `ReturnCount`. This already helps a lot to see what is actually missing to cleanup a class.

Another very helpful thing would of course be the JavaDoc suppressions. Those could actually be harder than the coding issues, since you have to understand what you are documenting. But this could also line up nicely with your project goal, if I understood that correctly. So this would also be very appreciated.

A general advice is to keep PRs small, e.g. for those wildcard suppressions just a single one per PR. You can use the Gitter chat mentioned on the HEP page to reach out for us anytime.

**Comment by bontorhumala** [comment] 2016-03-10 13:38
Noted, I think this solves the issue for me. Thanks @Donnerbart!

**Comment by Jorik0** [comment] 2016-03-21 18:29
I don't know if this is the right place for this. But we've encountered a small problem while reducing the checkstyle suppressions.

On our Windows machines the suppressions.xml file is completely ignored by maven. On Ubuntu everything works fine.

Do you know what might cause this?

**Comment by Donnerbart** [comment] 2016-03-21 19:46
Hmm, I have no spontaneous idea. I have no Java setup on my Windows machine, so I can't try this out easily. I assume you used the `-P checkstyle` profile? Could you run Maven with debug options `-Xe` and upload the output to http://gist.githubusercontent.com?

**Comment by Jorik0** [comment] 2016-03-21 20:04
https://gist.github.com/Jorik0/8ff57efba480b8fce1ab

I think I found the problem. If you look at line 499, you can see that maven looks for suppressions.xml at 'C:\Users\Jorik\Documents\hazelcast/checkstyle/suppressions.xml' . I'm guessing it can't handle the switch between "\" and "/". This is a typical Windows problem, as Linux only uses "/" and Windows uses both for some reason.

**Comment by Donnerbart** [comment] 2016-03-21 20:15
Hmm, that could be. You can test this if you adjust the path and see if it works then :) Should be defined in the main `pom.xml`: `<suppressionsLocation>${main.basedir}/checkstyle/suppressions.xml</suppressionsLocation>`

**Comment by Jorik0** [comment] 2016-03-21 20:28
I tried `<suppressionsLocation>${main.basedir}\checkstyle\suppressions.xml</suppressionsLocation>` as `<suppressionsLocation>${main.basedir}/checkstyle/suppressions.xml</suppressionsLocation>`is the current setting in the pom file. While did did change the path to `C:\Users\Jorik\Documents\hazelcast\checkstyle\suppressions.xml` it still generated the same error. And at closer inspection the problem seems to be the beginning of the path: "C" gets recognized as an unknown protocol instead of a partition.

It seems to be caused by [this problem](https://maven.apache.org/plugin-developers/common-bugs.html#Converting_between_URLs_and_Filesystem_Paths).

I wouldn't know how to solve this.

**Comment by Donnerbart** [comment] 2016-03-21 20:32
Hmm, maybe it helps to specify the protocol by adding `file:`, but I don't know by heart if this is allowed or best practice in this configuration context. I'll put it on my "nice to have" todo list to check :)

**Comment by Jorik0** [comment] 2016-03-21 20:41
I tried adding `file:`.

Interestingly enough this does remove the error message (and the file seems to be successfully found), but the suppressions still get ignored.

https://gist.github.com/Jorik0/96b0c4a92c57e7f3afd1

I guess I'll keep working in Linux for now. :disappointed:

**Comment by Donnerbart** [comment] 2016-03-21 21:16
Yeah, sorry. Most of our Engineers work with MacOS or Linux machines. As I said, it's on my list, but with a very low priority.

**Closed** 2017-01-17 11:31 UTC
Labels: Team: QuSP
