### ISSUE TITLE
can not invoke putAll from EntryProcessor

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#10566] opened 2017-05-11 15:59 UTC
I want to store data in 3 caches in one go.  All data belongs to the same partition via PartitionAware key. HZ stores single records properly, but when I call putAll on the third cache it throws exception:
```
2017-05-11 18:41:30.391 [hz.test-0.partition-operation.thread-4] ERROR com.hazelcast.map.impl.operation.EntryOperation - [localhost]:10000 [test] [3.8.1] Thread[hz.test-0.partition-operation.thread-4,5,test-0] cannot make invocation on multiple partitions!
java.lang.IllegalThreadStateException: Thread[hz.test-0.partition-operation.thread-4,5,test-0] cannot make invocation on multiple partitions!
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.ensureNotCallingFromPartitionOperationThread(InvokeOnPartitions.java:80) ~[hazelcast-all-3.8.1.jar:3.8.1]
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:67) ~[hazelcast-all-3.8.1.jar:3.8.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartitions(OperationServiceImpl.java:390) ~[hazelcast-all-3.8.1.jar:3.8.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartitions(OperationServiceImpl.java:396) ~[hazelcast-all-3.8.1.jar:3.8.1]
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokePutAllOperationFactory(MapProxySupport.java:868) ~[hazelcast-all-3.8.1.jar:3.8.1]
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokePutAllOperation(MapProxySupport.java:861) ~[hazelcast-all-3.8.1.jar:3.8.1]
	at com.hazelcast.map.impl.proxy.MapProxySupport.putAllInternal(MapProxySupport.java:821) ~[hazelcast-all-3.8.1.jar:3.8.1]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAll(MapProxyImpl.java:377) ~[hazelcast-all-3.8.1.jar:3.8.1]
```
looks like the putAll operation is not designed to be used from EP at all. 

Please have a look.

Thanks, Denis.

**Comment by ahmetmircik** [comment] 2017-05-11 17:59
Hi @dsukhoroslov,
 
Right `putAll` is not designed for that but even calling a regular `put` from EP is not safe and it can cause deadlocks. No official support declared for them, as far as i know.

**Comment by tombujok** [comment] 2017-05-12 11:06
Calling putAll from EP is impossible since it doesn't know about your convention that all keys belong to the same partition.

Try using executor service instead of EP.  That should work

**Comment by dsukhoroslov** [comment] 2017-05-12 12:53
My current solution uses executor. It works, but requires explicit locks and leads to timeouts sometime. I just tested the EP approach - no need for locks any more, no timeouts, no concurrent updates. I do IMap.set(key, value) in a loop instead of putAll, it works fine. Got performance increase in 10..50% depending on scenario. May be will get even more with OBJECT in-memory format..

**Comment by mmedenjak** [comment] 2017-12-12 21:51
Related: https://github.com/hazelcast/hazelcast/issues/7820

**Comment by mmedenjak** [comment] 2018-02-19 12:44
Closing this issue as it is basically a duplicate of the above mentioned improvement.

**Closed by mmedenjak** 2018-02-19 12:44 UTC
Labels: Priority: Low, Source: Community, Team: Core, Type: Enhancement
