### ISSUE TITLE
Management center members conflict ?

### ISSUE THREAD

**Issue by trixprod** [hazelcast/hazelcast#14168] opened 2018-11-24 11:38 UTC
Hello,
I'm launching 2 dockers instance connected to the same management center.

The management center doesn't recognize both 2 members.
Instead of, i see every 3 sec each member takeover the other one.

You can see the issue on screenshots

![hazelcast1](https://user-images.githubusercontent.com/12997320/48967756-d3841c80-efe5-11e8-937d-8ce676ab90de.png)
![hazelcast2](https://user-images.githubusercontent.com/12997320/48967757-d3841c80-efe5-11e8-8b31-cf2103086399.png)

Have you an idea of that issue ?
Thank you.

**Comment by jbee** [comment] 2018-11-27 12:57
Sounds like both members use the same group name (cluster name) but do not actually form a cluster. They send their data roughly every 5-6 sec to MC and their are off a bit so MC sees them changing.

**Comment by emre-aydin** [comment] 2018-11-27 13:11
@trixprod can you check your Hazelcast members' logs? As Jan said, they probably don't form a cluster. You need to see some lines in your logs that says the cluster has two members.

**Comment by trixprod** [comment] 2018-11-30 20:52
Imo, issue is my 2 members cannot communicate between them.
So a new cluster is created on each and the mancenter is confused.

I guess a proper solution would be to designate a "master cluster" and forbid slaves to create a new one if connection can't be reached.

**Comment by emre-aydin** [comment] 2018-12-03 06:59
@trixprod you need to make sure your members have the same group name (see the [relevant section in reference manual](https://docs.hazelcast.org/docs/latest/manual/html-single/#creating-cluster-groups)). Since the issue is not valid, I'm closing it. Please ask any questions you might have over the [Google group](https://groups.google.com/forum/#!forum/hazelcast) or [Gitter](https://gitter.im/hazelcast/hazelcast).

**Closed by emre-aydin** 2018-12-03 06:59 UTC
Labels: Source: Community, Team: Management Center
