### ISSUE TITLE
DurableExecutorService re-executes completed tasks in case of node failure.

### ISSUE THREAD

**Issue by shalakhansidmul** [hazelcast/hazelcast#9965] opened 2017-02-22 13:44 UTC
Hello,
I tried the following use case. I have some questions regarding behaviour of re-execution of tasks in  case of node failure.

[https://github.com/shalakhansidmul/hazelcast_test](https://github.com/shalakhansidmul/hazelcast_test)
In the provided example, there are 4 tasks:
SumTask, PutSumInAMapTask, SquareTask, PrintTheSquareTask.
All are HazelcastInstanceAware.
Order of execution:

Node1 will submit Sumtask to the executor.
Just before returning, Sumtask will submit PutSumInAMapTask to the executor.
Just before returning, PutSumInAMapTask will submit SquareTask to the executor.
Just before returning, SquareTask will submit PrintThe SquareTask to the executor.
There are 4 nodes in my Hazelcast cluster.
Steps:
Start the MasterMember(Node1) and three SlaveMembers(Node2,Node3,Node4) .
Observation:
SumTask submitted from node1. It executes on Node2
It submits PutSumInAMapTask and returns.
Randomly, PutSumInAMapTask also executes on Node2.
While the task is still running, I kill Node2.
The Hazelcast cluster repartitions the data and re-executes SumTask and PutSumInAMapTask on Node3.
Why does it execute SumTask even when it is completed?
It should ideally just resume/restart PutSumInAMapTask , right?

**Comment by tkountis** [comment] 2017-03-01 13:32
Hi @shalakhansidmul thanks for the finding. We have identified the cause, and pushed a fix on the PR above. Feel free to checkout the code and give it a try.

**Comment by shalakhansidmul** [comment] 2017-03-02 07:14
Hello @tkountis 
I tried the solution you have provided.
It works like a charm :)
Thank you for the quick resolution of my problem. :) great job !
I have 2 more requirements from the durable task executor. 
1 .Support for submitting and persisting callback along with task to Durable executor. Persisting the callback to handle node failure and failover of task.
2. Support for providing member selector for task execution to Durable executor.

I would be filing another issue for them. If this is also resolved soon, it would be perfect!
Thanks again.

**Comment by tkountis** [comment] 2017-03-02 07:56
glad that it works for you @shalakhansidmul. Hopefully we will merge it soon, and be available in next SNAPSHOT and in the upcoming patch of 3.8.1

----- Following discussion unrelated to this issue -----

Regarding your feature request, this introduces new API, which can only be considered for upcoming versions, so you won’t have as fast resolution as on this one. It will also be based on how useful this will be to other users too, if we see enough up-votes.

however, reading through your request I can offer your an alternative that might make it easier for your to accomplish what you want.

Hazelcast has recently released the `ScheduledExecutorService` which allows for scheduling on members as well, keep in mind though, that when scheduling on members, the tasks are *not* durable in an event of a failure. On key owners they are. For your callback chaining needs, I would recommend, on using the `StatefulTask` on the `ScheduledExecutorService` and keeping the last completed task on the state. If the task gets migrated due to a node failure, you can check the state and continue from where your last known condition. I think it will be a much cleaner approach. Now, you might say that you don’t want to schedule the task, but execute it now; if you specify 0 as delay, then you will have similar behaviour to the executor. have a go at it and let us know if the result is any better

**Closed** 2017-03-06 13:16 UTC
Labels: Team: Core, Type: Defect
