### ISSUE TITLE
ClassCastException in SystemPropertiesConfigParser when using Flway 10.11.0

### ISSUE THREAD

**Issue by wilkinsona** [hazelcast/hazelcast#26308] opened 2024-04-09 21:03 UTC
**Describe the bug**
Flyway 10.11.0 sets a System property with a `Boolean` value. This causes a `ClassCastException` in `SystemPropertiesConfigParser` as it assumes that all values in the `Properties` instance will be a `String`.

**Expected behavior**
Tolerance of non-String System property values.

**To Reproduce**

```
System.getProperties().put("example", false);
Hazelcast.newHazelcastInstance();
```

**Additional context**

Anyone using Flyway 10.11.0 and Hazelcast in the same JVM will experience this failure if Flyway has [set the system property](https://github.com/flyway/flyway/blob/00db8d5f5f9defc84d5fc1871f78acc8ccde0380/flyway-core/src/main/java/org/flywaydb/core/internal/jdbc/JdbcUtils.java#L49) before a Hazelcast instance is created.

**Comment by wilkinsona** [comment] 2024-04-10 06:55
This has been fixed, but not released, on the Flyway side: https://github.com/flyway/flyway/issues/3866.

**Comment by JackPGreen** [comment] 2024-04-15 11:42
Duplicate of https://github.com/hazelcast/hazelcast/issues/26310

**Closed by JackPGreen** 2024-04-15 11:42 UTC
Labels: Type: Defect

**Comment by JackPGreen** [comment] 2024-04-15 11:49
Thanks for the report @wilkinsona
