### ISSUE TITLE
Map entries are lost when peer crashes

### ISSUE THREAD

**Issue by hazelcastuser2016** [hazelcast/hazelcast#7523] opened 2016-02-15 17:01 UTC
- Hazelcast version: 3.6
- Cluster size: 2
- Java version: 7

We have 2 members using a shared map (tested with backup count >= 2).
Both members put entries in the map.
Then one member is killed and we detect lost map entries on the alive member (possibly some entries put by the alive member itself).
Can this scenario be fixed by https://github.com/hazelcast/hazelcast/issues/5444 ?

**Comment by jerrinot** [comment] 2016-02-15 17:11
hi @hazelcastuser2016,

I don't think it's the same issue. You are killing a single member. Other than that the cluster is in a steady state. Do you have a reproducer for this?

**Comment by hazelcastuser2016** [comment] 2016-02-15 21:55
Hi @jerrinot,

you can reproduce the problem with the following main methods.

- Member1 puts five entries in a shared map.
- Member2 puts other five entries in the map, then halts.
- Then Member1 (after sleeping) prints all "merged" keys in the map: you should observe that some values are missing.


```java
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

public class Member1 {

    public static void main(final String[] args) throws InterruptedException {
        final HazelcastInstance instance = Hazelcast.newHazelcastInstance();
        final IMap<Object, Object> map = instance.getMap("sharedMap");
        map.put(0, "");
        map.put(1, "");
        map.put(2, "");
        map.put(3, "");
        map.put(4, "");

        System.out.println(instance.getMap("sharedMap").keySet());

        System.out.println("Please start Member2...");

        Thread.sleep(60000);

        System.out.println(instance.getMap("sharedMap").keySet());
    }
}
```

```java
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

public class Member2 {

    public static void main(final String[] args) throws InterruptedException {
        final HazelcastInstance instance = Hazelcast.newHazelcastInstance();
        final IMap<Object, Object> map = instance.getMap("sharedMap");
        map.put("5", "");
        map.put("6", "");
        map.put("7", "");
        map.put("8", "");
        map.put("9", "");

        Runtime.getRuntime().halt(1);
    }
}
```

**Comment by gurbuzali** [comment] 2016-02-16 08:37
this is exactly the same scenario as in #5444 
you start the second member, repartitioning starts, while repartitioning goes on you kill a member, data loss.

**Comment by jerrinot** [comment] 2016-02-16 08:39
@gurbuzali: I am looking into it. you are probably right. I didn't realize the partition process (and backup creation) was not fully finished when on the `halt()` is called.

**Comment by jerrinot** [comment] 2016-02-16 08:46
@gurbuzali, @hazelcastuser2016: guys, you are right. it's the same thing as the #5444. I apologize for my mistake. 

When I put `while (!instance.getPartitionService().isClusterSafe());` just before the `halt()` line then the data-loss is gone.

**Comment by jerrinot** [comment] 2016-02-16 08:49
I'm closing this ticket as it's duplicate of #5444

**Closed by jerrinot** 2016-02-16 08:49 UTC
Labels: Team: Core, Type: Defect
