### ISSUE TITLE
Hazelcat 3.5 - InvalidConfigurationException: cvc-complex-type.2.4.a: 

### ISSUE THREAD

**Issue by ssozonoff** [hazelcast/hazelcast#5551] opened 2015-06-22 08:19 UTC
I have a configuration working fine with Hazelcast 3.4.3, upon upgrading to 3.5 I get the following XML validation error. The XML itself validates just fine using an external validator so seems something is messed up with your internal validation. Can the validation be disabled ?

Thanks

Caused by: com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'group'. One of '{"http://www.hazelcast.com/schema/client-config":import, "http://www.hazelcast.com/schema/client-config":group, "http://www.hazelcast.com/schema/client-config":license-key, "http://www.hazelcast.com/schema/client-config":properties, "http://www.hazelcast.com/schema/client-config":network, "http://www.hazelcast.com/schema/client-config":executor-pool-size, "http://www.hazelcast.com/schema/client-config":security, "http://www.hazelcast.com/schema/client-config":listeners, "http://www.hazelcast.com/schema/client-config":serialization, "http://www.hazelcast.com/schema/client-config":native-memory, "http://www.hazelcast.com/schema/client-config":proxy-factories, "http://www.hazelcast.com/schema/client-config":load-balancer, "http://www.hazelcast.com/schema/client-config":near-cache, "http://www.hazelcast.com/schema/client-config":query-caches}' is expected.
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:193)
	at com.hazelcast.client.config.XmlClientConfigBuilder.parseAndBuildConfig(XmlClientConfigBuilder.java:183)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:164)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:157)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:69)
	at com.hazelcast.client.cache.impl.HazelcastClientCachingProvider.instanceFromProperties(HazelcastClientCachingProvider.java:114)
	at com.hazelcast.client.cache.impl.HazelcastClientCachingProvider.createHazelcastCacheManager(HazelcastClientCachingProvider.java:62)
	at com.hazelcast.client.cache.impl.HazelcastClientCachingProvider.createHazelcastCacheManager(HazelcastClientCachingProvider.java:38)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:95)
	... 22 more

**Comment by bilalyasar** [comment] 2015-06-22 08:24
Can you post your hazelcast.xml file?

**Comment by ssozonoff** [comment] 2015-06-22 08:35
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast-client xsi:schemaLocation="http://www.hazelcast.com/schema/client-config hazelcast-client-config-3.5.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>ikentoo</name>
        <password>iKentoo-2015</password>
    </group>
    <properties>
        <property name="hazelcast.client.connection.timeout">10000</property>
        <property name="hazelcast.client.retry.count">6</property>
        <property name="hazelcast.prefer.ipv4.stack">true</property>
    </properties>
    <network>
        <cluster-members>
            <address>localhost</address>
        </cluster-members>
        <smart-routing>true</smart-routing>
        <redo-operation>true</redo-operation>
        <connection-timeout>30000</connection-timeout>
    </network>
</hazelcast-client>

**Comment by bilalyasar** [comment] 2015-06-22 09:00
@ssozonoff , I just created very simple maven project with your hazelcast-client.xml
It worked in my environment, can you try in your environment?
https://github.com/bilalyasar/invalid-config

**Comment by ssozonoff** [comment] 2015-06-22 09:16
Yes this works fine however our real environment is not that simple. As mentioned I was also able to validate the XML using a 3rd party validator.

The only thing I can say is that this very same configuration works fine with Hazelcast 3.4.3

I change to 3.5 and it no longer works with the error I mentioned.

**Comment by bilalyasar** [comment] 2015-06-22 09:21
Because with 3.5, we introduced new [fail-fast on invalid configuration feature.](https://github.com/hazelcast/hazelcast/blob/4270dc61e315b82c1b6db4f65851c03eba595a83/hazelcast/src/main/resources/release_notes.txt#L29) ( xml configs are validated according to schemas)
But according to your xml, hazelcast-client doesn't fail with simple project..
So we have to find why your hazelcast-client.xml file fails in your project although it doesn't fail [simple project.] (https://github.com/bilalyasar/invalid-config)

**Comment by ssozonoff** [comment] 2015-06-22 09:42
In the meantime is there a way to turn off this validation behavior ?

**Comment by bilalyasar** [comment] 2015-06-22 11:05
@ssozonoff, no there is no configuration for disabling validation behaviour.
I am trying to reproduce your case but i couldn't succeed it. Your hazelcast-client.xml file is working in my environment well.
Can you provide some infos about your environment like java version, OS etc?
I want to reproduce your case.

**Comment by bilalyasar** [comment] 2015-06-22 11:07
Can you also post logs from starting node section:
like
```
Jun 22, 2015 2:06:35 PM com.hazelcast.client.config.XmlClientConfigLocator
INFO: Loading 'hazelcast-client.xml' from classpath.
Jun 22, 2015 2:06:35 PM com.hazelcast.core.LifecycleService
```

**Comment by ssozonoff** [comment] 2015-06-22 11:19
I am running under OSX Yosemite
java build 1.7.0_40-b43

Spring framework 4.0.3 although this client is being started up from Datanucleus L2 JCache plugin and thats why we are not using Spring configuration. I will look at getting you some logging as requested.

''' text
Jun 22, 2015 1:11:39 PM com.hazelcast.client.config.XmlClientConfigLocator
INFO: Loading configuration classpath:datanucleus-hazel-ik-mysqldev.xml from System property 'hazelcast.client.config'
Jun 22, 2015 1:11:39 PM com.hazelcast.client.config.XmlClientConfigLocator
INFO: Using classpath resource at datanucleus-hazel-ik-mysqldev.xml
Jun 22, 2015 1:11:39 PM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_ikentoo][3.4.3] is STARTING
Jun 22, 2015 1:11:39 PM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_ikentoo][3.4.3] is STARTED
Jun 22, 2015 1:11:39 PM com.hazelcast.nio.tcp.SocketAcceptor
INFO: [localhost]:5701 [ikentoo] [3.4.3] Accepting socket connection from /127.0.0.1:54329
Jun 22, 2015 1:11:39 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [localhost]:5701 [ikentoo] [3.4.3] Established socket connection between /127.0.0.1:5701 and /127.0.0.1:54329
Jun 22, 2015 1:11:39 PM com.hazelcast.client.impl.client.AuthenticationRequest
INFO: [localhost]:5701 [ikentoo] [3.4.3] Received auth from Connection [/127.0.0.1:5701 -> /127.0.0.1:54329], endpoint=null, live=true, type=JAVA_CLIENT, successfully authenticated
Jun 22, 2015 1:11:39 PM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_ikentoo][3.4.3] is CLIENT_CONNECTED
Jun 22, 2015 1:11:39 PM com.hazelcast.client.spi.impl.ClusterListenerThread
INFO: 

Members [1] {
	Member [localhost]:5701
}

Jun 22, 2015 1:11:39 PM com.hazelcast.nio.tcp.SocketAcceptor
INFO: [localhost]:5701 [ikentoo] [3.4.3] Accepting socket connection from /127.0.0.1:54330
Jun 22, 2015 1:11:39 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [localhost]:5701 [ikentoo] [3.4.3] Established socket connection between /127.0.0.1:5701 and /127.0.0.1:54330
Jun 22, 2015 1:11:39 PM com.hazelcast.client.impl.client.AuthenticationRequest
INFO: [localhost]:5701 [ikentoo] [3.4.3] Received auth from Connection [/127.0.0.1:5701 -> /127.0.0.1:54330], endpoint=null, live=true, type=JAVA_CLIENT, successfully authenticated
'''

**Comment by ssozonoff** [comment] 2015-06-22 11:44
```text
Jun 22, 2015 1:32:50 PM com.hazelcast.client.config.XmlClientConfigLocator
INFO: Loading configuration classpath:datanucleus-hazel-ik-mysqldev.xml from System property 'hazelcast.client.config'
Jun 22, 2015 1:32:50 PM com.hazelcast.client.config.XmlClientConfigLocator
INFO: Using classpath resource at datanucleus-hazel-ik-mysqldev.xml

java.lang.reflect.InvocationTargetException
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:518)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:779)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManager(JDOPersistenceManagerFactory.java:810)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManager(JDOPersistenceManagerFactory.java:793)
	at org.springframework.orm.jdo.JdoTransactionManager.doBegin(JdoTransactionManager.java:310)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:631)
	at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:301)
	at org.datanucleus.NucleusContext.getLevel2Cache(NucleusContext.java:1568)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:769)
	... 10 more
Caused by: org.datanucleus.exceptions.NucleusException: Error creating cache
	at com.ikentoo.dn.cache.JavaxCacheLevel2Cache.<init>(JavaxCacheLevel2Cache.java:98)
	... 18 more
Caused by: javax.cache.CacheException: Error opening URI [hazelcast]
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:98)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:127)
	at com.hazelcast.cache.HazelcastCachingProvider.getCacheManager(HazelcastCachingProvider.java:156)
	at com.ikentoo.dn.cache.JavaxCacheLevel2Cache.<init>(JavaxCacheLevel2Cache.java:66)
	... 18 more
Caused by: com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'group'. One of '{"http://www.hazelcast.com/schema/client-config":import, "http://www.hazelcast.com/schema/client-config":group, "http://www.hazelcast.com/schema/client-config":license-key, "http://www.hazelcast.com/schema/client-config":properties, "http://www.hazelcast.com/schema/client-config":network, "http://www.hazelcast.com/schema/client-config":executor-pool-size, "http://www.hazelcast.com/schema/client-config":security, "http://www.hazelcast.com/schema/client-config":listeners, "http://www.hazelcast.com/schema/client-config":serialization, "http://www.hazelcast.com/schema/client-config":native-memory, "http://www.hazelcast.com/schema/client-config":proxy-factories, "http://www.hazelcast.com/schema/client-config":load-balancer, "http://www.hazelcast.com/schema/client-config":near-cache, "http://www.hazelcast.com/schema/client-config":query-caches}' is expected.
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:193)
	at com.hazelcast.client.config.XmlClientConfigBuilder.parseAndBuildConfig(XmlClientConfigBuilder.java:183)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:164)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:157)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:69)
	at com.hazelcast.client.cache.impl.HazelcastClientCachingProvider.instanceFromProperties(HazelcastClientCachingProvider.java:114)
	at com.hazelcast.client.cache.impl.HazelcastClientCachingProvider.createHazelcastCacheManager(HazelcastClientCachingProvider.java:62)
	at com.hazelcast.client.cache.impl.HazelcastClientCachingProvider.createHazelcastCacheManager(HazelcastClientCachingProvider.java:38)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:95)
	... 21 more
```

**Comment by jimbokun** [comment] 2015-06-23 14:03
The bug is in line 67 of:

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/AbstractXmlConfigHelper.java

The schemaValidation method modifies the document namespaces:

        root.setAttribute("xmlns", xmlns);
        root.setAttribute("xmlns:xsi", xsi);
        root.setAttribute("xsi:schemaLocation", hazelcastSchemaLocation);

But xmlns is sometimes "http://www.hazelcast.com/schema/config", instead of "http://www.hazelcast.com/schema/client-config", even when invoked from the subclass:

https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/config/XmlClientConfigBuilder.java

Using an explicit namespace in the client config file fixed the issue for me:

    <hz:hazelcast-client xmlns:hz="http://www.hazelcast.com/schema/client-config">
      
      <hz:network>
        <hz:cluster-members>
          
          <hz:address>127.0.0.1:5708</hz:address>
        </hz:cluster-members>
      </hz:network>
    </hz:hazelcast-client>

**Comment by bilalyasar** [comment] 2015-06-25 08:58
Before validating xml, we are using transformer and some transformers corrupts xml, this causes exceptions.
If you get exceptions, can you try your project with the flag `-Djaxp.debug=1`? Then can you post logs here?
You can select transformer by giving some system property.
Also as a workaround you can try this:
```
System.setProperty("javax.xml.transform.TransformerFactory",
                "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
```
This factory should be in your classpath. And many jdks includes this factory.

**Comment by stefanLeo** [comment] 2015-06-26 08:29
I am having the exact same issue when upgrading from 3.4 to 3.5.
For me the solution was override XmlConfigBuilder and to add  

DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
documentBuilderFactory.setNamespaceAware(true);

As soon as I had that in place it worked for me.

**Comment by bilalyasar** [comment] 2015-06-26 08:32
@stefanLeo, yes your way is also a solution, but in that case you have to add hazelcast namespace to your xml file.

**Comment by stefanLeo** [comment] 2015-06-26 12:05
@bilalyasar , yeah right this is needed, but no big deal :-)

FYI: Running it with the old approach and -DJaxp-debug=1 I get:

JAXP: find factoryId =javax.xml.parsers.DocumentBuilderFactory
JAXP: loaded from fallback value: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
JAXP: created new instance of class com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl using ClassLoader: null
JAXP: using thread context class loader (sun.misc.Launcher$AppClassLoader@14dad5dc) for search
JAXP: Looking up system property 'javax.xml.xpath.XPathFactory:http://java.sun.com/jaxp/xpath/dom'
JAXP: The property is undefined.
JAXP: found null in $java.home/jaxp.properties
JAXP: Calling net.sf.saxon.xpath.XPathFactoryImpl.isObjectModelSupported("http://java.sun.com/jaxp/xpath/dom")
JAXP: -- returning true
JAXP: factory 'net.sf.saxon.xpath.XPathFactoryImpl' was found for http://java.sun.com/jaxp/xpath/dom
JAXP: find factoryId =javax.xml.parsers.DocumentBuilderFactory
JAXP: loaded from fallback value: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
JAXP: created new instance of class com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl using ClassLoader: null
JAXP: find factoryId =javax.xml.parsers.DocumentBuilderFactory
JAXP: loaded from fallback value: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
JAXP: created new instance of class com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl using ClassLoader: null
JAXP: find factoryId =javax.xml.parsers.DocumentBuilderFactory
JAXP: loaded from fallback value: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
JAXP: created new instance of class com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl using ClassLoader: null
JAXP: find factoryId =javax.xml.transform.TransformerFactory
JAXP: using thread context class loader (sun.misc.Launcher$AppClassLoader@14dad5dc) for search
JAXP: Looking up system property 'javax.xml.validation.SchemaFactory:http://www.w3.org/2001/XMLSchema'
JAXP: The property is undefined.
JAXP: found null in $java.home/jaxp.properties
JAXP: attempting to use the platform default XML Schema validator
JAXP: createInstance(com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory)
JAXP: loaded com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory from jar:file:/C:/Program%20Files/Java/jdk1.8.0_45/jre/lib/rt.jar!/com/sun/org/apache/xerces/internal/jaxp/validation/XMLSchemaFactory.class
JAXP: factory 'com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory' was found for http://www.w3.org/2001/XMLSchema

**Comment by monastyrev** [comment] 2015-07-16 07:38
Same error for me - migrating from 3.4 to 3.5 gives an error 
Caused by: com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'group'. One of '{"http://www.hazelcast.com/schema/config":import, "http://www.hazelcast.com/schema/config":group ...

```xml
<?xml version="1.0" encoding="UTF-8"?>

<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.5.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>dev</name>
        <password>dev-pass</password>
    </group>
```

**Comment by mesutcelik** [comment] 2015-08-04 08:18
fixed by https://github.com/hazelcast/hazelcast/pull/5659

**Closed by mesutcelik** 2015-08-04 08:18 UTC
Labels: Team: Integration, Type: Defect

**Comment by alexey-su** [comment] 2015-10-20 12:00
Resolve this issuer if change xsd files

From file 
hazelcast/hazelcast-client/src/main/resources/hazelcast-client-config-3.5.xsd
to
hazelcast/hazelcast/src/main/resources/hazelcast-config-3.5.xsd
```
<xs:element name="hazelcast">
  <xs:complexType>
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element ref="import"/>
```
change element "import" to
```
<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
```
We have to change 3 files:
hazelcast-config-3.4.xsd
hazelcast-config-3.5.xsd
hazelcast-config-3.6.xsd

bilalyasar commented on 22 Jun
But according to your xml, hazelcast-client doesn't fail with simple project..

**Comment by Pankajain2** [comment] 2022-07-20 14:43
Getting the same issue when upgrading from "hazelcast-all" version 3.8.2 to 4.2.5. With 3.8.2 it was working fine, but with 4.2.5 I'm stuck with below issue.

com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'group'. One of '{"http://www.hazelcast.com/schema/config":import, "http://www.hazelcast.com/schema/config":config-replacers, "http://www.hazelcast.com/schema/config":cluster-name, "http://www.hazelcast.com/schema/config":license-key, "http://www.hazelcast.com/schema/config":instance-name, "http://www.hazelcast.com/schema/config":management-center, "http://www.hazelcast.com/schema/config":properties, "http://www.hazelcast.com/schema/config":wan-replication, "http://www.hazelcast.com/schema/config":network, "http://www.hazelcast.com/schema/config":partition-group, "http://www.hazelcast.com/schema/config":executor-service, "http://www.hazelcast.com/schema/config":durable-executor-service, "http://www.hazelcast.com/schema/config":scheduled-executor-service, "http://www.hazelcast.com/schema/config":queue, "http://www.hazelcast.com/schema/config":map, "http://www.hazelcast.com/schema/config":multimap, "http://www.hazelcast.com/schema/config":replicatedmap, "http://www.hazelcast.com/schema/config":cache, "http://www.hazelcast.com/schema/config":list, "http://www.hazelcast.com/schema/config":set, "http://www.hazelcast.com/schema/config":topic, "http://www.hazelcast.com/schema/config":reliable-topic, "http://www.hazelcast.com/schema/config":ringbuffer, "http://www.hazelcast.com/schema/config":listeners, "http://www.hazelcast.com/schema/config":serialization, "http://www.hazelcast.com/schema/config":native-memory, "http://www.hazelcast.com/schema/config":security, "http://www.hazelcast.com/schema/config":member-attributes, "http://www.hazelcast.com/schema/config":split-brain-protection, "http://www.hazelcast.com/schema/config":lite-member, "http://www.hazelcast.com/schema/config":hot-restart-persistence, "http://www.hazelcast.com/schema/config":user-code-deployment, "http://www.hazelcast.com/schema/config":cardinality-estimator, "http://www.hazelcast.com/schema/config":flake-id-generator, "http://www.hazelcast.com/schema/config":crdt-replication, "http://www.hazelcast.com/schema/config":pn-counter, "http://www.hazelcast.com/schema/config":advanced-network, "http://www.hazelcast.com/schema/config":cp-subsystem, "http://www.hazelcast.com/schema/config":auditlog, "http://www.hazelcast.com/schema/config":metrics, "http://www.hazelcast.com/schema/config":instance-tracking, "http://www.hazelcast.com/schema/config":sql}' is expected.
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:120)
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:169)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:151)
	at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:97)
	at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:61)
	at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:47)

Using below code for starting the node

System.setProperty("hazelcast.ignoreXxeProtectionFailures", "true");
Config config = new ClasspathXmlConfig(ConfigUtil.getStringValue(AppConstants.HAZELCAST_FILE));
HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
instance.getConfig().getExecutorConfig("defaultExecutorService").setPoolSize(300).setQueueCapacity(50).setStatisticsEnabled(true);
		
Below is mine hazelcast.xml schema deleration

<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.1.xsd" xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

**Comment by pmi4** [comment] 2023-08-04 09:14
I have same problem using io.vertx:vertx-hazelcast 4.4.4 and hazelcast-aws 3.4
