### ISSUE TITLE
SQL client support

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#17173] opened 2020-07-03 13:12 UTC
We need to support execution of SQL queries on client members. 

We will reuse existing request-response client architecture for now, for the sake of simplicity. This approach is not very good because client handler threads will be blocked waiting for SQL results. In future, we will rework it to reactive approach, but this is out of the scope of 4.1 due to lack of time.

We will have three operations:
1. `Execute` - starts execution of a query, receives back query ID, metadata and the first page of rows
2. `Fetch` - fetches the next page of rows
3. `Close` - cancels the query

When a member receives a query, it opens a cursor and saves it in a local collection. Further `fetch` and `close` requests should be routed to the same member. Therefore, the protocol should be sticky: we pick the member for execution randomly, but all subsequent requests related to the same query are routed to the same member.

Lite members cannot initiate query execution for now. Therefore, we need to filter out lite members on the client-side when choosing the target member.

**Comment by sancar** [comment] 2020-07-06 11:50
Already mentioned on the pr but, for the sake of completeness repeating here. 
Our users do not have ability to say that a unisocket client should connect to a data member only. 
Instead, as a design choice, we have implemented every request in a way that, it should be able to redirected to a data-member if needed from the lite member. 
I think we should follow the same design for the SQL client support as well. Otherwise, 
1. a customers app may never be able to run a query because unisocket client is connected to a non-lite member. 
2. It can also stop working after some time because client is disconnected from the data member and connected to lite-member. 

Another concern could be for smart-routing.  In the current design, the client sends the request to a single-member. Then, all the results should be gathered on that member. The better design for smart clients is to fetch from the each member directly. We are trying to migrate existing multi-member invocations this way because of performance. It could be better to design the SQL support this way from the day one.

**Comment by devozerov** [comment] 2020-07-06 11:57
@sancar These two design goals are clear, but we cannot follow them for different reasons.
1. We do not support SQL on lite members explicitly. It will require additional engineering efforts, but the end results will be a query execution flow that is considerably slower than when a member is connected to a data member. We reject to support lit members because we assume that nowadays users are not likely to use them. We may change this decision someday, but at the moment this should be perceived as a limitation of the SQL engine, not the protocol
1. It is impossible to fetch results from all members. Server-side handling is very complicated - it places different stages to different members, establishes data flow edges between them, performs re-tries, controls topology state, etc. We do not want to have this logic on the client-side for the obvious reason - it will be very difficult to implement, and we hardly ever see SQL implemented on non-Java platforms, maintained by contributors. Instead, we choose the opposite approach - all the complexity is written once on the server-side.

**Comment by viliam-durina** [comment] 2020-07-06 13:17
My 2 cents: I actually am surprised that a unisocket client can connect to a lite member. A lite member is in a way a client. One client should not connect to another client and expect it to forward its requests. Maybe we should start here...

On the other hand, unisocket clients are by design slower, their operation requires more hops. So users expect lower performance from them, they should not be used for heavy tasks.

**Comment by sancar** [comment] 2020-07-06 13:34
@viliam-durina We may rediscuss if a client should connect to lite-member. It will not be straight forward one.  The clients will be load-balancing via only data members. Adding a lite member will not help clients to scale. Heavily depends on the use case(number of clients, or they smart or not, the nature of the operation they are doing etc)

**Comment by sancar** [comment] 2020-07-08 09:27
@Vladimir Ozerov In the current design, the SQL query is not able to continue if a client connection is dropped. This is very unusual when compared to other read-only operations. 
A map.get for example can be retried in any of the members or connections still works. Keep in mind that, this needs to be well documented in order not to surprise our clients. 


And when it comes to fetching from all members. We know that it makes all clients complicated, but this is a price we are willing to pay. We value performance over simple client code. It might be out of scope for the first beta version. But consider this for the next version.

**Comment by devozerov** [comment] 2020-07-08 09:34
@sancar, `map.get` is a stateless idempotent operation, that could be retried easily. SQL is stateful and is not idempotent, therefore no retires are possible.It is very unlikely that any retry logic will be implemented in future.

**Comment by devozerov** [comment] 2020-07-24 07:10
Reopening because the protocol PR is not merged yet.

**Closed** 2020-07-24 07:20 UTC
Labels: Estimation: M, Module: SQL, Priority: High, Source: Internal, Team: Core, Type: Enhancement
