### ISSUE TITLE
com.hazelcast.collection.impl.queue.QueueDestroyTest.checkStatsMapEntryRemovedWhenQueueDestroyed

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast#21901] opened 2022-08-03 19:40 UTC
commit https://github.com/hazelcast/hazelcast/pull/21838/commits/282a8b9215717f83e0c4a3b2bfcd616d040c7d8a

Failed on Hazelcast PR Builder: https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/12352/testReport/junit/com.hazelcast.collection.impl.queue/QueueDestroyTest/checkStatsMapEntryRemovedWhenQueueDestroyed_instance_com_hazelcast_collection_impl_queue_QueueDestroyTest$$Lambda$3939_1859270850_3e908a0b_/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.collection.impl.queue.QueueDestroyTest.checkStatsMapEntryRemovedWhenQueueDestroyed(QueueDestroyTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3938/715405137@5c96d290] in 0.136 seconds.
Started Running Test: checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]
18:44:54,400  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [MetricsConfigHelper] checkStatsMapEntryRemovedWhenQueueDestroyed - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
18:44:54,400  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [logo] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
18:44:54,400  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
18:44:54,401  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220803 - 9f76f4a) starting at [127.0.0.1]:5702
18:44:54,401  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Cluster name: dev
18:44:54,401  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
18:44:54,401  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Jet is enabled
18:44:54,404  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [MetricsConfigHelper] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
18:44:54,408  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [CPSubsystem] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
18:44:54,410  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [JetServiceBackend] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
18:44:54,411  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Diagnostics] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
18:44:54,411  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [LifecycleService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTING
18:44:54,411  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [ClusterService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5702 - f450026e-5c58-4fd1-add1-28814d528378 this
]

18:44:54,411  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Node] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Config seed port is 5701 and cluster size is 1. Some of the ports seem occupied!
18:44:54,411  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [JobCoordinationService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Jet started scanning for jobs
18:44:54,411  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [LifecycleService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTED
18:44:54,412 DEBUG |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [JobCoordinationService] hz.nervous_joliot.cached.thread-3 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
18:44:54,412  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [MetricsConfigHelper] checkStatsMapEntryRemovedWhenQueueDestroyed - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
18:44:54,413  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [logo] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
18:44:54,413  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
18:44:54,413  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220803 - 9f76f4a) starting at [127.0.0.1]:5703
18:44:54,413  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Cluster name: dev
18:44:54,413  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
18:44:54,413  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Jet is enabled
18:44:54,415  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [MetricsConfigHelper] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
18:44:54,419  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [CPSubsystem] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
18:44:54,422  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [JetServiceBackend] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
18:44:54,424  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Diagnostics] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
18:44:54,424  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [LifecycleService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5703 is STARTING
18:44:54,424  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [MockServer] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-f450026e-5c58-4fd1-add1-28814d528378, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=f450026e-5c58-4fd1-add1-28814d528378], alive=true}
18:44:54,425  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [MockServer] hz.nervous_joliot.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5703-ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=f450026e-5c58-4fd1-add1-28814d528378], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0], alive=true}
18:44:54,425  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [ClusterService] hz.nervous_joliot.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5702 - f450026e-5c58-4fd1-add1-28814d528378 this
	Member [127.0.0.1]:5703 - ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0
]

18:44:54,511 DEBUG |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [JobCoordinationService] hz.nervous_joliot.cached.thread-1 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
18:44:54,529  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [ClusterService] hz.agitated_joliot.generic-operation.thread-1 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5702 - f450026e-5c58-4fd1-add1-28814d528378
	Member [127.0.0.1]:5703 - ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0 this
]

18:44:54,530  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Node] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Config seed port is 5701 and cluster size is 2. Some of the ports seem occupied!
18:44:54,530  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [JobCoordinationService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Jet started scanning for jobs
18:44:54,531  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [LifecycleService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5703 is STARTED
18:44:54,533  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [PartitionStateManager] hz.nervous_joliot.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Initializing cluster partition table arrangement...
18:44:54,632 DEBUG |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [JobRepository] hz.nervous_joliot.cached.thread-1 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Job cleanup took 0ms
18:44:55,778  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [LifecycleService] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
18:44:55,778  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Node] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Terminating forcefully...
18:44:55,778  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Node] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
18:44:55,778  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [MockServer] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5703, uuid=ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=f450026e-5c58-4fd1-add1-28814d528378], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0], alive=false}
18:44:55,779  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [MockServer] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=f450026e-5c58-4fd1-add1-28814d528378], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=f450026e-5c58-4fd1-add1-28814d528378], alive=false}
18:44:55,779  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [MembershipManager] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Removing Member [127.0.0.1]:5703 - ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0
18:44:55,779  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [PartitionStateManager] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Storing snapshot of partition assignments while removing UUID ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0
18:44:55,779  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [ClusterService] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5702 - f450026e-5c58-4fd1-add1-28814d528378 this
]

18:44:55,779  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [TransactionManagerService] hz.nervous_joliot.cached.thread-12 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: ae470ec4-3616-4dba-80a4-a3d4e1e3b6a0
18:44:55,779  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Node] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Shutting down node engine...
18:44:55,780  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [MigrationManager] hz.nervous_joliot.migration - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Partition balance is ok, no need to repartition.
18:44:55,781  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [NodeExtension] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
18:44:55,781  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Node] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
18:44:55,781  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [LifecycleService] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
18:44:55,781  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
18:44:55,781  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Terminating forcefully...
18:44:55,781  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
18:44:55,781  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down node engine...
18:44:55,783  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [NodeExtension] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
18:44:55,784  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
18:44:55,784  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b]| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
BuildInfo right after checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b](com.hazelcast.collection.impl.queue.QueueDestroyTest): BuildInfo{version='5.2-SNAPSHOT', build='20220803', buildNumber=20220803, revision=9f76f4a, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$3939/1859270850@3e908a0b](com.hazelcast.collection.impl.queue.QueueDestroyTest):'
18:44:50, accumulated pauses: 1164 ms, max pause: 962 ms, pauses over 1000 ms: 0
18:44:55, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by vbekiaris** [comment] 2022-08-08 14:37
duplicate of #21696

**Closed by vbekiaris** 2022-08-08 14:37 UTC
Labels: Team: Core, Type: Test-Failure, Source: Internal
