### ISSUE TITLE
Strange NPE Hazelcast Client

### ISSUE THREAD

**Issue by ejnickey** [hazelcast/hazelcast#13427] opened 2018-07-09 13:06 UTC
I've run into the following nullPointerException thrown by Hazelcast.  After mentioning it to the Google group, it sounds like it might be bug with Hazelcast.  
```
java.lang.NullPointerException
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:204)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:198)
	at com.hazelcast.client.proxy.ClientMapProxy.containsKeyInternal(ClientMapProxy.java:278)
	at com.hazelcast.client.proxy.ClientMapProxy.containsKey(ClientMapProxy.java:272)
```

**Comment by pveentjer** [comment] 2018-07-10 04:42
Which HZ version?

**Comment by ejnickey** [comment] 2018-07-10 14:42
We're using HZ 3.9.3.

So the bug only appears during production runs, I haven't yet been able to reproduce in testing.  Basically it comes from a MapReduce job that writes data into HZ.  I'll see if I can reproduce it.

**Comment by pveentjer** [comment] 2018-07-12 09:39
You know that MapReduce is deprecated? It will be removed in HZ 4.0

**Comment by sancar** [comment] 2018-09-10 12:56
Hi @ejnickey, do you have a reproducer ? 
I could not find a path that can cause NP as in given stacktrace.

**Comment by sancar** [comment] 2018-09-18 14:00
Hi @ejnickey . Closing this issue for now since we can't reproduce it. Please share more if you are able to reproduce it.

**Closed by sancar** 2018-09-18 14:00 UTC
Labels: Module: IMap, Source: Community, Team: Client, Type: Defect
