### ISSUE TITLE
EntryProcessorTest.testBackupMapEntryProcessorAllKeys

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#5786] opened 2015-07-27 07:17 UTC
```
junit.framework.AssertionFailedError: expected:<86> but was:<85>
    at junit.framework.Assert.fail(Assert.java:57)
    at junit.framework.Assert.failNotEquals(Assert.java:329)
    at junit.framework.Assert.assertEquals(Assert.java:78)
    at junit.framework.Assert.assertEquals(Assert.java:86)
    at junit.framework.TestCase.assertEquals(TestCase.java:253)
    at com.hazelcast.map.EntryProcessorTest.testBackupMapEntryProcessorAllKeys(EntryProcessorTest.java:481)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/627/testReport/junit/com.hazelcast.map/EntryProcessorTest/testBackupMapEntryProcessorAllKeys/

**Comment by tombujok** [comment] 2015-08-20 09:10
It seems to be IBM-JDK specific.
I couldn't reproduce it on OSX running the test with Repeat(100) on the following Oracle JDKs:
jdk1.7.0_80.jdk
jdk1.8.0_51.jdk
jdk1.8.0_60.jdk

**Comment by gurbuzali** [comment] 2015-10-27 13:34
closing this one, not failed recently

**Comment by hasancelik** [comment] 2016-02-16 09:27
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.EntryProcessorTest.testBackupMapEntryProcessorAllKeys(EntryProcessorTest.java:470)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/396/testReport/junit/com.hazelcast.map/EntryProcessorTest/testBackupMapEntryProcessorAllKeys/

**Comment by ahmetmircik** [comment] 2016-06-09 13:02
not failed recently.

**Comment by hasancelik** [comment] 2017-05-02 06:50
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.EntryProcessorTest.testBackupMapEntryProcessorAllKeys(EntryProcessorTest.java:625)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/384/testReport/junit/com.hazelcast.map/EntryProcessorTest/testBackupMapEntryProcessorAllKeys_0__BINARY_/

**Comment by hasancelik** [comment] 2017-05-15 08:13
```
java.lang.AssertionError: Cluster size is not correct. Expected: 2 Actual: 3
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:871)
	at com.hazelcast.map.EntryProcessorTest.testBackupMapEntryProcessorAllKeys(EntryProcessorTest.java:623)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/475/testReport/junit/com.hazelcast.map/EntryProcessorTest/testBackupMapEntryProcessorAllKeys_0__BINARY_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/469/testReport/junit/com.hazelcast.map/EntryProcessorTest/testBackupMapEntryProcessorAllKeys_1__OBJECT_/

**Closed** 2017-05-15 08:24 UTC
Labels: Team: Core, Type: Test-Failure
