### ISSUE TITLE
No DataSerializerFactory registered for namespace: -26

### ISSUE THREAD

**Issue by kasured** [hazelcast/hazelcast#6221] opened 2015-09-15 09:52 UTC
Installation and usage scenario
1) 2-node hazelcast cluster enterprise nodes with High-Density JCache and Elastic Memory for Maps  features enabled
2) Java clients connects to the cluster and performs reads/writes/delete
3) Everything goes fine until the point in time when I start seeing the huge amount of Warning/Severe level logs in hazelcast server. They are coming in bulk and in an interval of about 1-2 minutes
4) This does not affect the cluster and the clients. They still can write and read
5) From the logs it seems like the nodes cannot communicate something internally between each other
6) seems like -26 is some internal  serialization factory 
7) On the servers: export CLASSPATH=$HAZELCAST_HOME/lib/hazelcast-enterprise-all-3.5.1.jar:$HAZELCAST_HOME/lib/cache-api-1.0.0.jar
8) clients are using hazelcast-enterprise-client-3.5.1.jar and hazelcast-enterprise-3.5.1.jar

INFO: [node1ip]:5710 [xxxxxx] [3.5.1] processors=16, physical.memory.total=110.2G, physical.memory.free=61.5G, swap.space.total=0, swap.space.free=0, heap.memory.used=6.2G, heap.memory.free
=787.9M, heap.memory.total=7.0G, heap.memory.max=8.9G, heap.memory.used/total=88.97%, heap.memory.used/max=69.85%, native.memory.used=13.4G, native.memory.free=65.3G, native.memory.total=13.5G, native.memory.max
=78.8G, minor.gc.count=6112, minor.gc.time=195996ms, major.gc.count=14, major.gc.time=44908ms, load.process=0.00%, load.system=0.00%, load.systemAverage=0.08, thread.count=93, thread.peakCount=397, cluster.timeD
iff=-4, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operation.size=0, execu
tor.q.priorityOperation.size=0, executor.q.response.size=0, operations.remote.size=0, operations.running.size=0, operations.pending.invocations.count=0, operations.pending.invocations.percentage=0.00%, prox
y.count=66, clientEndpoint.count=2, connection.active.count=3, client.connection.count=2, connection.count=1
Sep 15, 2015 3:04:55 AM com.hazelcast.spi.OperationService
SEVERE: [node1IP]:5710 [xxxxxxx [3.5.1] No DataSerializerFactory registered for namespace: -26
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -26
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:98)
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39)
        at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41)
        at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:325)
        at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:489)
        at com.hazelcast.client.impl.operations.OperationFactoryWrapper.readData(OperationFactoryWrapper.java:55)
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:111)
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39)
        at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41)
        at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:325)
        at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:489)
        at com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation.readInternal(PartitionIteratingOperation.java:162)
        at com.hazelcast.spi.Operation.readData(Operation.java:451)
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:111)
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39)
        at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41)
        at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:276)
        at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:200)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:294)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:142)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:115)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)

Sep 15, 2015 3:04:55 AM com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor
SEVERE: [node1IP]:5710 [xxxxx] [3.5.1] Failed to process packet: Packet{header=1, isResponse=false, isOperation=true, isEvent=false, partitionId=-1, conn=Connection [/node1IP:57221 -> /node2IP:5712], endpoint=Address[node2IP]:5712, live=true, type=MEMBER} on hz._hzInstance_1_xxxxxx.generic-operation.thread-3
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -26
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:98)
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39)
        at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41)
        at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:325)
        at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:489)
        at com.hazelcast.client.impl.operations.OperationFactoryWrapper.readData(OperationFactoryWrapper.java:55)
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:111)
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39)
        at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41)
        at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:325)

**Comment by kasured** [comment] 2015-09-15 11:08
Also as is specified in the readme notes 
"hazelcast-enterprise-all–3.5.1.jar — This library is the combination of hazelcast–enterprise–version.jar and Hazelcast Enterprise client extensions."
The aforementioned jar is the only jar included on the CLASSPATH on the server (by default). 

However I have compared hazelcast-enterprise vs hazelcast-enterprise-all and seems like there are differences in the META-INF/services/ folder. The main point of interest is the com.hazelcast.DataSerializerHook. 
Namely, in the "-all" version the following section is absent, but present in the hazelcast-enterprise.jar
# enterprise hooks
com.hazelcast.cache.hidensity.operation.HiDensityCacheDataSerializerHook
com.hazelcast.cache.operation.EnterpriseCacheDataSerializerHook
com.hazelcast.enterprise.wan.EWRDataSerializerHook

As soon as on the client side I am using the hazelcast-enterprise.jar Might it be the case that factoriId might be different and causing the problem? But why I do see that exception only after application starts read/write/delete at the same time.

**Comment by jerrinot** [comment] 2015-09-15 11:11
Hello @kasured,

This is a known issue in Hazelcast Enterprise 3.5.1. There was a problem in 3.5.1 build process - as you have identified the descriptors weren't merged correctly. It's already fixed in 3.5.2. Can you please re-run it with 3.5.2? 


a cross-post form https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/hazelcast/PdL3TG_-YE8

**Comment by kasured** [comment] 2015-09-15 11:19
@jerrinot Thanks for the quick reply. 
1) Could you please point me to the relevant ticket on this?
2) Does this introduce the long term cluster functionality instability? Currently I am not seeing any but the logs are growing drastically.
3) In case we are not going to upgrade to 3.5.2 yet, is there any workaround this? Lets say I will use hazelcast-enterprise-all-3.5.1.jar on the client side making the ClassLoader register hooks in the same manner?

**Comment by jerrinot** [comment] 2015-09-15 11:25
@kasured: 
1. Unfortunately there is no public ticket as Hazelcast Enterprise only is affected. There is no publicly available issue tracker Hazelcast Enterprise only bugs. 

2. Well, it means some objects can't be de-serialized. It's hard to reason about its effect. One would have to investigate every single object affected. I would certainly NOT recommend using it. 

3. If you register the hooks yourself then it should work, However it would probably have some impact on supportability of your installation.

**Comment by kasured** [comment] 2015-09-15 11:38
@jerrinot 
From what I can see right now, it does not affect any read/write/delete operations (at least no exceptions reported on client api side) and only starts to show itself when delete comes into play. Cannot understand right now why "the wrong" hook appears only at this time, cause reads/writes to the HiDensity happens without no errors for the long time before that.

As to the second point you mentioned I did not mean to register hooks myself but instead use the same jar on the client side as dependency. So instead of two jars hazelcast-enterprise-3.5.1.jar and hazelcast-enterprise-client-3.5.1.jar, just use one hazelcast-enterprise-all-3.5.1.jar so it will match the same that is used on the hazelcast server nodes.

Just do not want to come across other types of issues with the new version.

**Comment by jerrinot** [comment] 2015-09-15 14:22
You can try it, but I'd strongly recommend to upgrade to Hazelcast 3.5.2. 
It's a patch release; We are very careful when it comes to regression testing of patch releases -> risk of regression is very low. 

I'm closing this ticket as the issue is known and it's fixed in a patch release.

**Closed by jerrinot** 2015-09-15 14:22 UTC
Labels: PENDING, Type: Defect

**Comment by kasured** [comment] 2015-09-16 05:25
For the sake of consistency I have tried the possible workaround with the same jars on both server and client sides. The impact did not change a bit. The same error. 

I have identified that the problem occurs when we call remove on the unwrapped ICache instance and connected with the HiDensityCacheDataSerializerHook. Most probably the CacheRemove operation cannot be deserialized due to that.

No clues why it happens only on remove as we are using the cache put and get without any problems. Would be great if you provide more details what happens exactly so that all pieces match.

Anyways, latter on after we upgrade to the 3.5.2 I will report if the issue is still reproducible.

**Comment by StanAccy** [comment] 2015-12-17 00:48
We just hit a similar issue on 3.6-EA3-SNAPSHOT.  Removing the enterprise-all and just using the server side JAR fixed the problem.

**Comment by gregrluck** [comment] 2015-12-17 05:37
Should have this fixed for 3.6-EA3 out this Friday.

**Comment by gregrluck** [comment] 2015-12-18 13:34
If this is the cause, can we do this:

Log "You are using an Enterprise feature of Hazelcast with the Enterprise jars" rather than No DataSerializerFactory registered for namespace: -26
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -26
