### ISSUE TITLE
Lost data if a node is killed during data repartition

### ISSUE THREAD

**Issue by elmor** [hazelcast/hazelcast#5444] opened 2015-06-03 13:27 UTC
Hi,

I am evaluating HazelCast 3.42 against Coherence and I experienced a strange behavior with Hazelcast.

 I have a cluster of two nodes(I will name them node1 and node2) and two clients 

I have a map name “toto” (I joined the hazelcast configuration file server.xml) 

1.       I inserted 100000 entries into the map=> all is ok.

2.       I kill the node  node2. All is ok I found the 100000 entries into the node1.

3.       I restart the node2.  While node2 is synchronizing with node1, I kill again node2.

4.       Node1 only have 51919 elements L I lost 48081 entries L (The pb seems to be due to the partitioning)

 

Ho  How can I avoid to lose elements of a node is killed during synchronisation ?

 

I can see the following errors in the log file of my server

Members [1] {

            Member [192.88.65.124]:5701 this

}

> 

####<Jun 2, 2015 3:03:43 PM CEST> <Info> <com.hazelcast.partition.InternalPartitionService> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.migration> <<anonymous>> <> <> <1433250223501> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Partition balance is ok, no need to re-partition cluster data... > 

####<Jun 2, 2015 3:05:14 PM CEST> <Info> <Health> <dcaclx01.dns21.socgen> <Hazel1> <weblogic.GCMonitor> <<anonymous>> <> <> <1433250314135> <BEA-310002> <79% of the total memory in the server is free.> 

####<Jun 2, 2015 3:05:41 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketAcceptor> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.IO.thread-Acceptor> <<anonymous>> <> <> <1433250341255> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Accepting socket connection from /192.88.65.123:2247> 

####<Jun 2, 2015 3:05:41 PM CEST> <Info> <com.hazelcast.nio.tcp.TcpIpConnectionManager> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-4> <<anonymous>> <> <> <1433250341267> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Established socket connection between /192.88.65.124:5701 and dcaclx02.dns21-3.socgen/192.88.65.123:2247> 

####<Jun 2, 2015 3:05:47 PM CEST> <Info> <com.hazelcast.cluster.ClusterService> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.generic-operation.thread-1> <<anonymous>> <> <> <1433250347267> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] 

 

Members [2] {

            Member [192.88.65.124]:5701 this

            Member [192.88.65.123]:5701

}

> 

####<Jun 2, 2015 3:05:47 PM CEST> <Info> <com.hazelcast.partition.InternalPartitionService> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.migration> <<anonymous>> <> <> <1433250347582> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Re-partitioning cluster data... Migration queue size: 135>

####<Jun 2, 2015 3:05:48 PM CEST> <Info> <com.hazelcast.nio.tcp.TcpIpConnection> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.IO.thread-in-2> <<anonymous>> <> <> <1433250348783> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Connection [Address[192.88.65.123]:5701] lost. Reason: java.io.EOFException[Remote socket closed!]>

####<Jun 2, 2015 3:05:48 PM CEST> <Warning> <com.hazelcast.nio.tcp.ReadHandler> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.IO.thread-in-2> <<anonymous>> <> <> <1433250348786> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] hz._hzInstance_1_dev.IO.thread-in-2 Closing socket to endpoint Address[192.88.65.123]:5701, Cause:java.io.EOFException: Remote socket closed!>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.partition.InternalPartitionService> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.migration> <<anonymous>> <> <> <1433250349207> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] All migration tasks have been completed, queues are empty.>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-5> <<anonymous>> <> <> <1433250349490> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Connecting to /192.88.65.123:5701, timeout: 0, bind-any: true>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-5> <<anonymous>> <> <> <1433250349511> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Could not connect to: /192.88.65.123:5701. Reason: SocketException[Connection refused to address /192.88.65.123:5701]>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-4> <<anonymous>> <> <> <1433250349716> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Connecting to /192.88.65.123:5701, timeout: 0, bind-any: true>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-4> <<anonymous>> <> <> <1433250349717> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Could not connect to: /192.88.65.123:5701. Reason: SocketException[Connection refused to address /192.88.65.123:5701]>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-4> <<anonymous>> <> <> <1433250349717> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Connecting to /192.88.65.123:5701, timeout: 0, bind-any: true>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-4> <<anonymous>> <> <> <1433250349719> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Could not connect to: /192.88.65.123:5701. Reason: SocketException[Connection refused to address /192.88.65.123:5701]>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-4> <<anonymous>> <> <> <1433250349719> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Connecting to /192.88.65.123:5701, timeout: 0, bind-any: true>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-4> <<anonymous>> <> <> <1433250349725> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Could not connect to: /192.88.65.123:5701. Reason: SocketException[Connection refused to address /192.88.65.123:5701]>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-1> <<anonymous>> <> <> <1433250349727> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Connecting to /192.88.65.123:5701, timeout: 0, bind-any: true>

####<Jun 2, 2015 3:05:49 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-1> <<anonymous>> <> <> <1433250349728> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Could not connect to: /192.88.65.123:5701. Reason: SocketException[Connection refused to address /192.88.65.123:5701]>

####<Jun 2, 2015 3:05:50 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-1> <<anonymous>> <> <> <1433250350491> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Connecting to /192.88.65.123:5701, timeout: 0, bind-any: true>

####<Jun 2, 2015 3:05:50 PM CEST> <Info> <com.hazelcast.nio.tcp.SocketConnector> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-1> <<anonymous>> <> <> <1433250350493> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Could not connect to: /192.88.65.123:5701. Reason: SocketException[Connection refused to address /192.88.65.123:5701]>

####<Jun 2, 2015 3:05:50 PM CEST> <Warning> <com.hazelcast.nio.tcp.TcpIpConnectionMonitor> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-1> <<anonymous>> <> <> <1433250350495> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Removing connection to endpoint Address[192.88.65.123]:5701 Cause => java.net.SocketException {Connection refused to address /192.88.65.123:5701}, Error-Count: 5>

####<Jun 2, 2015 3:05:50 PM CEST> <Info> <com.hazelcast.cluster.ClusterService> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-3> <<anonymous>> <> <> <1433250350495> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2] Removing Member [192.88.65.123]:5701>

####<Jun 2, 2015 3:05:50 PM CEST> <Info> <com.hazelcast.cluster.ClusterService> <dcaclx01.dns21.socgen> <Hazel1> <hz._hzInstance_1_dev.cached.thread-3> <<anonymous>> <> <> <1433250350503> <BEA-000000> <[192.88.65.124]:5701 [dev] [3.4.2]

 

Thanks in advance for your help,

ps:
the hazelcast.xml file is:
<?xml version="1.0" encoding="UTF-8"?>

<hazelcast
	xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.4.xsd"
	xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<group>
		<name>dev</name>
		<password>dev-pass</password>
	</group>
	<management-center enabled="true">http://dcaclx01.dns21.socgen:8080/mancenter
	</management-center>
	
	<properties>
		<property name="hazelcast.jmx">true</property>
		<property name="hazelcast.jmx.detailed">true</property>		
	</properties>
	<network>
		<port auto-increment="true" port-count="100">5701</port>
		<outbound-ports>
			
			<ports>0</ports>
		</outbound-ports>
		<join>
			<multicast enabled="false">
				<multicast-group>224.2.2.3</multicast-group>
				<multicast-port>54327</multicast-port>
			</multicast>
			<tcp-ip enabled="true">
				<interface>192.88.65.123</interface>
				<interface>192.88.65.124</interface>
			</tcp-ip>
			<aws enabled="false">
				<access-key>my-access-key</access-key>
				<secret-key>my-secret-key</secret-key>
				
				<region>us-west-1</region>
				
				<host-header>ec2.amazonaws.com</host-header>
				
				<security-group-name>hazelcast-sg</security-group-name>
				<tag-key>type</tag-key>
				<tag-value>hz-nodes</tag-value>
			</aws>
		</join>
		<interfaces enabled="false">
			<interface>10.10.1.*</interface>
		</interfaces>
		<ssl enabled="false" />
		<socket-interceptor enabled="false" />
		<symmetric-encryption enabled="false">
			
			<algorithm>PBEWithMD5AndDES</algorithm>
			
			<salt>thesalt</salt>
			
			<password>thepass</password>
			
			<iteration-count>19</iteration-count>
		</symmetric-encryption>
	</network>

	<partition-group enabled="false" />
	<executor-service name="default">
		<pool-size>16</pool-size>
		
		<queue-capacity>0</queue-capacity>
	</executor-service>
	<queue name="default">
		
		<max-size>0</max-size>
		
		<backup-count>1</backup-count>

		
		<async-backup-count>0</async-backup-count>

		<empty-queue-ttl>-1</empty-queue-ttl>
	</queue>

	<map name="toto">
		
		<near-cache>
			
			<max-size>5000</max-size>

			
			<time-to-live-seconds>0</time-to-live-seconds>

			
			<max-idle-seconds>60</max-idle-seconds>

			
			<eviction-policy>LRU</eviction-policy>

			
			<invalidate-on-change>true</invalidate-on-change>

			
			<cache-local-entries>false</cache-local-entries>
		</near-cache>

		<in-memory-format>BINARY</in-memory-format>

		
		<backup-count>1</backup-count>
		
		<async-backup-count>0</async-backup-count>
		
		<time-to-live-seconds>0</time-to-live-seconds>
		
		<max-idle-seconds>0</max-idle-seconds>
		
		<eviction-policy>LRU</eviction-policy>
		
		<max-size policy="PER_NODE">200000</max-size>
		
		<eviction-percentage>25</eviction-percentage>
		
		<min-eviction-check-millis>100</min-eviction-check-millis>
		
		<merge-policy>com.hazelcast.map.merge.PutIfAbsentMapMergePolicy
		</merge-policy>

	</map>

	<map name="default">
		
		<in-memory-format>BINARY</in-memory-format>

		
		<backup-count>1</backup-count>
		
		<async-backup-count>0</async-backup-count>
		
		<time-to-live-seconds>0</time-to-live-seconds>
		
		<max-idle-seconds>0</max-idle-seconds>
		
		<eviction-policy>NONE</eviction-policy>
		
		<max-size policy="PER_NODE">0</max-size>
		
		<eviction-percentage>25</eviction-percentage>
		
		<min-eviction-check-millis>100</min-eviction-check-millis>
		
		<merge-policy>com.hazelcast.map.merge.PutIfAbsentMapMergePolicy
		</merge-policy>

	</map>

	<multimap name="default">
		<backup-count>1</backup-count>
		<value-collection-type>SET</value-collection-type>
	</multimap>

	<multimap name="default">
		<backup-count>1</backup-count>
		<value-collection-type>SET</value-collection-type>
	</multimap>

	<list name="default">
		<backup-count>1</backup-count>
	</list>

	<set name="default">
		<backup-count>1</backup-count>
	</set>

	<jobtracker name="default">
		<max-thread-size>0</max-thread-size>
		
		<queue-size>0</queue-size>
		<retry-count>0</retry-count>
		<chunk-size>1000</chunk-size>
		<communicate-stats>true</communicate-stats>
		<topology-changed-strategy>CANCEL_RUNNING_OPERATION
		</topology-changed-strategy>
	</jobtracker>

	<semaphore name="default">
		<initial-permits>0</initial-permits>
		<backup-count>1</backup-count>
		<async-backup-count>0</async-backup-count>
	</semaphore>

	<serialization>
		<portable-version>0</portable-version>
	</serialization>

	<services enable-defaults="true" />

</hazelcast>

**Comment by metanet** [comment] 2015-06-03 13:48
Hi @elmor,

Could you please check this comment: https://github.com/hazelcast/hazelcast/issues/5388#issuecomment-107469413

**Comment by elmor** [comment] 2015-06-03 15:06
Hi @metanet,

thanks for your answer.
Unfortunately I am not agree with you. Having the a node  going down again while the sync is in progress and losing data is not desirable at all and should be avoided.

If the first node has 100% of the data, we cannot accept to lose data if the node is going down while repartition process. We cannot know when a JVM, a VM, a router ... will crash

Isn't it possible to copy data in the backup before sending a partition to a node?
The partition backup will be overwritten by the partition sent by the new node. If the new node never send data, no data will be lost.

**Comment by metanet** [comment] 2015-06-04 08:05
Hi @elmor,

I understand your point but what we provide is safety of your data if it already has 1 backup. Your second node is crashing when the cluster is not in safe state. You won't use your data in every node failure during repartitioning. It is the moment when ownership of a partition is passed to the second node but its 1st backup is not guaranteed yet. After second node receives data of a partition, we remove the partition data from the first node. This is done this way because it becomes a more problematic case if you have many nodes and your initial node is not a backup of the partition anymore.

**Comment by elmor** [comment] 2015-06-04 14:21
OK so I need at least 3 nodes and 2 backups to be sure to not lose data ?

**Comment by fchameau** [comment] 2015-06-04 14:47
Hi,
- Could you please confirm the above statement from 'elmor' before we try it for real (3 nodes, 2 backups will make the trick) ?
- If yes, we believe this would be valuable as stated explicitely in the documentation (if not yet ? we did not find such detail)

Note: we are in the middle of a POC experiencing several distributed cache solutions. Some other do work well on this very same failover use case (the data is removed from node 1 only when node 2 is up and has acknoledged the reception of the full half data, with backup of this data still on node 1, and not partition per partition).

Many thanks in advance for your feedback.

**Comment by Verdoso** [comment] 2015-06-10 07:49
Even if the 3 node rule works, in order to have 3 nodes you have to start with 2, so there you go.

Pretty disappointed on how Hazelcast deals with this, at all levels.

**Comment by metanet** [comment] 2015-06-11 07:49
Hi,

Independent of number of nudes, a new node joining to the cluster takes some of the partitions from the other nodes (=migration). For a specific partition, when its data is moved from an existing node to the new node, existing node removes that data for preventing data-inconsistency problems. When the new node receives data of the migrating partition, it starts sending backups for that partition to the other nodes. The cluster is not in safe state until this process is completed and there may be data loss for a specific case as I explained in my previous comment: https://github.com/hazelcast/hazelcast/issues/5388#issuecomment-107469413 .

**Comment by Verdoso** [comment] 2015-06-12 16:48
I understand what the issue is, what I can't comprehend is why this is not considered a bug to be fixed. 

It means that no matter what you do, no matter how many nodes or backups you configure, you cannot trust your data to be safe, as one failure when a new node joins the cluster, no matter the size, could compromise the data you already have.

Maybe it's me trying to use Hazelcast in a way it was not meant to be used, but this tiny detail means I have to go back to my customer and tell him we have to start again the selection process for a data-grid solution. It makes me sad.

**Comment by pveentjer** [comment] 2015-06-13 08:23
Imho this is a bug and needs to get fixed ASAP.

**Comment by wenerme** [comment] 2015-06-14 16:34
+1

**Comment by bwzhang2011** [comment] 2015-06-15 15:38
@pveentjer, hope such could be resolved ASAP. looking forward to that.

**Comment by dfex55** [comment] 2015-06-18 09:26
+1
Maybe the already existing backups can be used by the new location, so repartitioning can be finished/acknowledged in a shorter time.
After that, the location of backups can be reorganized by the new owning node.

**Comment by lukasblu** [comment] 2015-06-18 12:04
+1

Adding an additional node should improve reliability and performance - not introduce a potential risk of losing data...

If adding a node takes longer, because of additional synchronization, then I can live with that, but losing data is certainly not an option.

A scenario where a new node crashes while joining a cluster is actually quite realistic. The new node might have too little memory or some Firewall setup was wrong and the node needs to be killed, etc. etc.

**Comment by mnaspreda** [comment] 2015-06-29 09:03
Hi Hazelcast team,

we have faced the same issue on 2.6.x. Will this fix be applied also to 2.6 branch?

Thanks in advanced!!

**Comment by Fabryprog** [comment] 2015-07-20 12:55
+1

**Comment by bwzhang2011** [comment] 2015-10-30 23:50
@gurbuzali, any update with such issue ?

**Comment by niakris** [comment] 2015-11-02 11:37
+1 really looking forward to get this one fixed ASAP

**Comment by ChristerF** [comment] 2015-11-07 07:43
+1

**Comment by DDani** [comment] 2015-11-09 11:54
+1!

**Comment by nick7ikin** [comment] 2015-11-10 11:07
This is critical issue that produces lots of inconsistent states

**Comment by jerrinot** [comment] 2015-11-10 12:02
Hello all,

thank you for your feedback; It's much appreciated(for real!) and it helps us to prioritize our work. We are now in a feature freeze for 3.6 release. We are going to address this issue in Hazelcast 3.7.

**Comment by dolomite52** [comment] 2015-11-10 15:55
-1 this is not a feature, this is a horrible bug that is so problematic that it should be fixed immediately. Why would you let this fester until March 2016?

**Comment by ChristerF** [comment] 2015-11-12 06:44
Agree on the -1, I do hope that no data loss is the #1 feature for any Hazelcast release and I do hope that is the case. @gregrluck wouldn't you agree with that?

**Comment by enesakar** [comment] 2015-11-12 10:56
March is the worst case. We will try to backport the fix to 3.6.1 or 3.6.2 patch releases if we can find a solution that does not have a major side effect and compatibility problem.
We have some solution ideas that is expected to work in theory. Partitioning is probably the most critical component of the system; we can not quickly change the partitioning system without extensive testing.

**Comment by bwzhang2011** [comment] 2015-12-06 13:05
@pveentjer, any update with such issue ? any better solution for data lost not only for the node under repartition to be killed ?

**Comment by gregrluck** [comment] 2015-12-07 16:02
We are just finishing 3.6, then we will start on 3.7 including a fix for this issue.

**Comment by bwzhang2011** [comment] 2015-12-08 14:33
@gregrluck,  maybe it's better add some chapter for data lost risk reason mentioned above as some times we use kill -9 for node shutdown which exists the risk of data lost. for another side,  hope the solution could be back ported for most of the version released since 3.5.

**Comment by gawlikt** [comment] 2016-01-13 13:39
Is there any suggested workaround for this issue until fix is provided ?
I'm using hazelcast on two machines, each machine having three apps, each app is adding one member to hazelcast cluster - so I have six members in my cluster.

occasionally I need to restart two apps (one per machine)
as a result I always loose some data stored in IMaps

as a workaround I was thinking about increasing number of backups for two maps.
I have such Beans defined:
```java
	@Bean(destroyMethod = "shutdown")
	public HazelcastInstance hazelcastInstance() {
		Config config = new Config("hazelcastInstance");
		config.getGroupConfig().setName(System.getProperty("hazelcast.group"))
				.setPassword(System.getProperty("hazelcast.password"));
		config.addMapConfig(new com.hazelcast.config.MapConfig(CacheElement.MapName1).setBackupCount(5));
		config.addMapConfig(new com.hazelcast.config.MapConfig(CacheElement.MapName2).setBackupCount(5));

		hazelcastInstance = HazelcastInstanceFactory.newHazelcastInstance(config);

		return hazelcastInstance;
	}
```


I was testing this in eclipse on my laptop 
4 apps, so 4 members on one machine
when I kill 2 instances I loose my data again

so can anyone suggest some proper workaround for this issue ?

**Comment by jerrinot** [comment] 2016-01-13 15:00
@gawlikt: The only reliable workaround is to restart members one-by-one.
We are working on a proper fix.

**Comment by channingwalton** [comment] 2016-02-12 21:39
hi @enesakar, you mentioned above that March is the worst case for a fix, is that still possible?

**Comment by channingwalton** [comment] 2016-03-01 14:51
Hi, I hate to keep asking but we are doing some planning around our use of hazelcast that critically depends on this issue being fixed. 
Do you have any idea at all when this is likely to be resolved?

**Comment by gregrluck** [comment] 2016-03-01 18:45
We realise our critical this issue is. 

This issue is being worked on by a team of Core engineers at Hazelcast. They are about a month in. We anticipate having a fix in trunk in the next month. We plan to do a tagged  master release so that you and others on this thread can test that we have actually fixed the issue. This way we can get it out to you are the earliest time for testing.

**Comment by channingwalton** [comment] 2016-03-01 21:58
Thanks for the update @gregrluck, its much appreciated.

**Comment by nick7ikin** [comment] 2016-03-24 10:24
As a temporary workaround consider switching to client-server mode. So one node will contain all data in consistent state and must be always turned on. The rest nodes will connect as clients and they can only work through the network with data on server. In local network environment this approach has quite good speed.

**Comment by channingwalton** [comment] 2016-03-24 11:32
Thanks @nick7ikin

**Comment by burakcelebi** [comment] 2016-04-07 13:54
Our engineering team has finished their “Solution Design" for the issue. 

Your input is always appreciated. You can review and comment on our design here:

[Avoid Data Loss on Migration - Solution Design](https://hazelcast.atlassian.net/wiki/display/COM/Avoid+Data+Loss+on+Migration+-+Solution+Design)
PR: https://github.com/hazelcast/hazelcast/pull/7911

Thanks in advance for any feedback you can provide!

**Closed** 2016-04-14 15:24 UTC
Labels: Team: Core, Type: Critical

**Comment by bwzhang2011** [comment] 2016-05-24 14:58
@elmor, @gawlikt, would you mind sparing some time and take a look it ?
