### ISSUE TITLE
AdvancedNetworkClientIntegrationTest.testPartitions

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16343] opened 2019-12-24 10:38 UTC
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK13/27/testReport/com.hazelcast.client.io/AdvancedNetworkClientIntegrationTest/testPartitions/

**Stacktrace**
```
java.lang.NullPointerException
	at com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testPartitions(AdvancedNetworkClientIntegrationTest.java:154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by tezc** [comment] 2019-12-27 07:45
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/69/testReport/com.hazelcast.client.io/AdvancedNetworkClientIntegrationTest/testPartitions/

**Comment by devozerov** [comment] 2019-12-27 12:35
@sancar could you please assist with the issue? This failure appears to be a regression from https://github.com/hazelcast/hazelcast/pull/16255 (commit https://github.com/hazelcast/hazelcast/commit/3438fcc724c259529fecd169078bee5365e3b1f6)
The problem is that we removed `InternalPartitionService.firstArrangement()` from `AddClusterViewListenerMessageTask` and now partition table is never initialized on the server. I am not sure whether it was an intentional change or not. Also, it seems strange that the variable `ClientPartitionServiceImpl.triggeringPartitionAssingment` is unused.

**Comment by sancar** [comment] 2019-12-27 12:43
The change was intentional. We don't want client to trigger partition arrangement until it does a partition based operation. `triggeringPartitionAssingment` seems like a leftover, we should delete it.

**Comment by sancar** [comment] 2019-12-27 12:49
@devozerov  I think we can say that test is wrong and modify it. 
I think it is legal for `getOwner` to return null, that is what I understand from the javadoc of Partition.getOwner 
```
 /**
     * Returns the current member that owns this partition.
     *
     * The returned value could be stale as soon as it is returned.
     *
     * It can be that null is returned if the owner of a partition has not been established.
     *
     * @return the owner member of the partition
     */
```

**Comment by devozerov** [comment] 2019-12-27 13:00
@sancar That was my thought as well :) What I did is tried to use `assertTrueEventually`, but it failed as either because the table is never initialized. As a user, I would not expect that. It is ok if we show the partition owner eventually, but returning `null` forever looks like a broken API to me. 
Maybe we should trigger partition init from the client on the first call to "getOwner" and wait for the response from the server?

**Comment by sancar** [comment] 2019-12-30 10:18
@devozerov I have checked that a call to getOwner triggers the partition table and does not wait for the response. I will implement the same logic for the client. In my pr, I can use `assertTrueEventually` in this test. Assigning this to myself.

**Closed** 2019-12-31 13:39 UTC
Labels: Source: Internal, Team: Client, Team: Core, Type: Test-Failure
