### ISSUE TITLE
what is the default user/password for hazelcast-mancenter?

### ISSUE THREAD

**Issue by artworx** [hazelcast/hazelcast#13286] opened 2018-06-11 14:53 UTC
I've just downloaded v3.10 of hazelcast management center, unzipped it and run start.sh 

![selection_160](https://user-images.githubusercontent.com/1954578/41238964-f71386cc-6d9f-11e8-9198-fb8fe40d0a4d.png)

I see that it created `~/hazelcast-mancenter3.10/` with a bunch of files in it that wasn't there before. 

What is the default username/password?

**Comment by emre-aydin** [comment] 2018-06-11 15:04
Hi @artworx 

It doesn't have a default username/password. It asks you to choose a username/password when you first open the Management Center URL. If it didn't ask, you may have run Management Center before, chosen a username/password so it's using that. 

If you're certain that you don't have any data that you think you'd need under `~/hazelcast-mancenter-3.10/` directory, you can stop Management Center, delete the directory, start it back again. This time, when you open up the Management Center URL, it needs to ask for a username/password. Please report back with your findings.

**Comment by artworx** [comment] 2018-06-11 19:08
I've never run the software before, the directory `~/hazelcast-mancenter-3.10/` did not exist and I'm getting the login prompt every time. 

I've also tried to run in in docker using `hazelcast/management-center` that showed the same behavior.

I'm on Linux btw, if that helps.

**Comment by emre-aydin** [comment] 2018-06-12 08:16
I just tried the same on Linux with MC 3.10 and it asks me to choose a username/password. Can you please share the logs? It might give us a clue about what's wrong. BTW, as a quick resolution for the issue, you can create a user by executing the following `curl` command (creates a user named `emre` with password `pass1357`:

```
curl 'http://localhost:8080/hazelcast-mancenter/security/saveConfig' -H 'Origin: http://localhost:8080' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://localhost:8080/hazelcast-mancenter/login.html' -H 'X-Requested-With: XMLHttpRequest'  --data 'providerHiddenInput=Default&usernameInput=emre&passwordInput=pass1357&confirmPasswordInput=pass1357'
```

**Comment by emre-aydin** [comment] 2018-06-12 08:18
And also, can you try the same with MC 3.10.1? It also works with both HZ 3.9.x and HZ 3.10.x, and contains some more features.

**Comment by artworx** [comment] 2018-06-12 09:40
### using docker 

The docker compose i've used: 

```
version: '2'
services:
  management:
    image: hazelcast/management-center:3.10.1
    ports:
      - '8080:8080'
```
Docker logs: https://gist.github.com/artworx/adf4eb314b3352cc412684008b5231c0

### with a local install 

`rm -rf ~/hazelcast-mancenter3.10/ && ./start.sh`

Logs https://gist.github.com/artworx/70fb55e36a0bd67ad65815796df4c054

Running the provided curl, i get: 
```
curl 'http://localhost:8080/hazelcast-mancenter/security/saveConfig' -H 'Origin: http://localhost:8080' -H 'Acceptent-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://localhost:8080/hazelcast-mancenter/login.html' -H 'X-Requested-With: XMLHttpRequest'  --data 'providerHiddenInput=Default&usernameInput=emre&passwordInput=pass1357&confirmPasswordInput=pass1357'
{"result":"success"}
```

**Comment by emre-aydin** [comment] 2018-06-12 09:51
That means you have successfully created a user, so you can use it to login. Or you can delete the `hazelcast-mancenter3.10` folder and use the curl command again with the desired username/password and use those credentials to log in.

As for the original problem, I can't reproduce it, it shows me the user creation screen each time I try. Which browser are you using? Is it possible that you have disabled javascript?

**Comment by artworx** [comment] 2018-06-12 10:07
Using Chrome 67.0.3396.79 only the login shows up. 

Using Firefox, the "Configure security"  popup shows up, so I guess its a browser compatibility issue.

**Comment by emre-aydin** [comment] 2018-06-12 10:13
I'm using the same version to test. MC is compatible with the said version of Chrome. It might be due to a plugin blocking the display of the popup, or another setting that interferes with it. I'm closing the issue. Feel free to open another issue if you can narrow down cause of this problem. Thanks.

**Closed by emre-aydin** 2018-06-12 10:13 UTC
Labels: Team: Integration
