### ISSUE TITLE
Interruption may cause lock.unlock() operation throw IllegalMonitorStateException

### ISSUE THREAD

**Issue by chhaj5236** [hazelcast/hazelcast#13699] opened 2018-09-06 10:49 UTC
Hazelcast version: 3.10
JDK Version: 1.8.0_162

In our server log, we noticed following errors:
```
Exception in thread "Thread-1" java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: null, thread ID: 0
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.concurrent.lock.LockProxySupport.unlock(LockProxySupport.java:151)
	at com.hazelcast.concurrent.lock.LockProxy.unlock(LockProxy.java:106)
```

And we reproduce these errors by following test codes:

```java
public class App {
    public static void main(String[] args) throws InterruptedException {
        HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
        final ILock lock = hazelcastInstance.getLock("testLock");
        final ICondition condition = lock.newCondition("testCondition");

        Thread thread = new Thread() {
            @Override
            public void run() {
                lock.lock();

                try {
                    while (true) {
                        condition.await();
                    }
                } catch (InterruptedException e) {
                    System.out.println("interrupted...");
                } finally {
                    lock.unlock();
                }
            }
        };

        thread.start();
        thread.interrupt();
        thread.join();
        System.out.println("thread finished");
    }
}
```

But if we replace `lock` and `condition` with JUC implementation, it just works fine. Or we just add `lock.lock()` in "catch(InterruptedException e)" code block, it works without any error messages either.

Will Hazelcast re-acquire lock released by `await()` if the InterruptedException occurs as `java.util.concurrent.locks.Condition#await()` doc suggested? Since it seems like the lock is not re-acquiring after the InterruptedException, or if I miss something important?

Thanks for help : )

**Comment by blazember** [comment] 2018-09-10 08:28
Thanks for reporting this issue and for the reproducer @chhaj5236 

As your reproducer proves, `ICondition#await()` indeed violates the contract of `Condition#await()` by not re-acquiring the lock on wakeup in the interrupted case. 

**Analysis**
When `ICondition#await()` is called,  `AwaitOperation` is invoked. This is a `BlockingOperation`, being parked while waiting for a signal to wake up the caller thread. If interrupted in this phase, `AwaitOperation` does not re-acquire the lock - since it is not scheduled - and the proxies don't re-acquire it either. The proxies can handle the interrupt and re-acquire the locks - in an uninterruptible way - before rethrowing the `InterruptedException`.

**Comment by cforce** [comment] 2018-11-22 10:51
related to
https://github.com/hazelcast/hazelcast/issues/14083
https://github.com/hazelcast/hazelcast/issues/11617
https://github.com/hazelcast/hazelcast/issues/13699

**Comment by mmedenjak** [comment] 2019-10-25 12:51
Closing as the entire lock implementation was replaced with the unsafe mode of CP subsystem (see https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#removal-of-deprecated-concurrency-api-implementations). This new implementation also doesn't support conditions but please try using it and open a new issue if it occurs.

**Closed by mmedenjak** 2019-10-25 12:51 UTC
Labels: Module: Lock, Priority: Medium, Source: Community, Team: Core, Type: Defect
