### ISSUE TITLE
Query with predicate on indexed field problem

### ISSUE THREAD

**Issue by iboar** [hazelcast/hazelcast#12358] opened 2018-02-15 16:40 UTC
Hello,

In my project I recently encountered a problem related to Map with configured QueryCache.

I have entity with two fields:
```
class AccountingRule {
    long key;
    String code;
}
```

Map configuration for it's Map including QueryCache configuration:

```        
MapConfig mapConfig = new MapConfig("AccountingRule")
                .setInMemoryFormat(InMemoryFormat.BINARY)
                .setReadBackupData(true)
                .setBackupCount(1)
                .addQueryCacheConfig(new QueryCacheConfig()
                        .setName("AccountingRule")
                        .setPredicateConfig(new PredicateConfig(TruePredicate.INSTANCE))
                        .setIncludeValue(true)
                        .setPopulate(true)
                        .setDelaySeconds(0)
                 );
```

In main I run hazelcast instance with my configuration and then:
- add index to QueryCache
- put entity into IMap
- wait until insertion is propagated to QueryCache by checking if QueryCache.get returned inserted entity 
- get same entity from QueryCache using predicate on indexed field
```
        HazelcastInstance hazelcast = createHazelcastInstance();
        IMap<Long, AccountingRule> map = hazelcast.getMap("AccountingRule");
        QueryCache<Long, AccountingRule> queryCache = map.getQueryCache("AccountingRule");

        queryCache.addIndex("code", false);

        while (true) {
            AccountingRule ar = newAccountingRule();
            map.put(ar.getKey(), ar);

            // wait for query cache
            AccountingRule fromQueryCache = queryCache.get(ar.getKey());
            while (fromQueryCache == null) {
                log.info("Waiting for query cache");
                fromQueryCache = queryCache.get(ar.getKey());
            }
            log.info("query cache updated");

            // get entity from query cache using predicate
            Predicate codePredicate = equal("code", ar.getCode());
            AccountingRule fromQueryCacheWithPredicate = getOnlyElement(queryCache.values(codePredicate), null);
            if (fromQueryCacheWithPredicate == null) {
                log.error("AccountingRule with id {} from query cash is null", ar.getKey());
                System.exit(1);
            }
        }
```
Unfortunately it fails. QueryCache.get returned entity but query based on predicate on indexed field returns nothing. When I wait a little bit and retry query it's ok. It looks like indexes are updated asynchronously am I right? Is there any option to avoid it? 

There are two options when it works:
- remove index -> no index no problem :)
- declare index in QueryCache conf like this, not in main:

```
        MapConfig mapConfig = new MapConfig("AccountingRule")
                .setInMemoryFormat(InMemoryFormat.BINARY)
                .setReadBackupData(true)
                .setBackupCount(1)
                .addQueryCacheConfig(new QueryCacheConfig()
                        .setName("AccountingRule")
                        .setPredicateConfig(new PredicateConfig(TruePredicate.INSTANCE))
                        .setIncludeValue(true)
                        .setPopulate(true)
                        .setDelaySeconds(0)
                        .addIndexConfig(new MapIndexConfig("code", false))
                 );
```

The question is why when I add index not in configuration it doesn't work properly.

**Comment by taburet** [comment] 2018-02-26 17:56
Hello @iboar,

> I have done small performance test and it looks like adding index configuration using QueryCacheConfig.addIndexConfig does not create index at all.

You are right, but that's easy to fix and it's already fixed in my local branch.

>  It looks like indexes are updated asynchronously am I right? Is there any option to avoid it?

The problem is that Query Cache is a highly concurrent structure, it pushes up updates to the underlying record store and indexes from the multiple threads running in the background. In general, it's not safe to assume that two consecutive accesses to the QC instance will produce compatible results.

You still may observe the state of QC when the store and indexes are fully consistent about the state of a particular entry. This can be achieved using entry listeners, see `QueryCache#addEntryListener` and `EntryAddedListener` for more details. If this approach is not suitable to your needs, please describe your use case in more details.

Don't forget that QC is eventually consistent. For instance, updates done to the entries stored in two or more different partitions may arrive to the QC out of order. So it's safe to reason about the ordering of the entry events (and about the entry states as a result) only for the entries stored inside a certain partition.

**Comment by mmedenjak** [comment] 2018-03-12 12:33
@iboar have you had a chance to try out the suggestion?

**Comment by iboar** [comment] 2018-03-12 13:46
@mmedenjak solution based on EntryEvents it's much better than the original one. Thanks.
Now I have some problems with events sequence, I will create another issue soon probably.

**Closed** 2018-03-15 12:55 UTC
Labels: Estimation: M, Interface: IMap, Source: Community, Team: Core, To Triage
