### ISSUE TITLE
Hazlecast OperationTimeoutException: No response for 120000 ms (hazlecast.3.2.3)

### ISSUE THREAD

**Issue by itsram5** [hazelcast/hazelcast#6243] opened 2015-09-17 21:21 UTC
Hi all,
Using the hazlecast.3.2.3 version.
Java version 6.

Getting the time out exception on invocation of the cluster  and stops responding .

Cluster is set up with 4 nodes.

Happening more frequently in production environment. 

Please find the log reference below.

Could you please help me with this this resolution
 
Com.hazelcast.core.OperationTimeoutException: No response for 120000 ms. Aborting invocation! InvocationFuture{invocation=BasicInvocation{ serviceName='hz:core:partitionService', op=com.hazelcast.partition.impl.MigrationOperation{partitionId=46, migration=MigrationInfo{ partitionId=46, source=Address[10.87.169.140]:5705, destination=Address[10.87.169.135]:5705, master=Address[10.87.169.140]:5705, valid=true, processing=false}, compressed=true}, partitionId=46, replicaIndex=0, tryCount=250, tryPauseMillis=1000, invokeCount=1, callTimeout=60000, target=Address[10.87.169.135]:5705}, done=false} No response has been send  backups-expected: 0 backups-completed: 0 reinvocations: 0
	at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.newOperationTimeoutException(BasicInvocation.java:782)
	at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.waitForResponse(BasicInvocation.java:760)
	at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:697)
	at com.hazelcast.partition.impl.MigrationRequestOperation$MigrationRequestTask.run(MigrationRequestOperation.java:263)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:619)
	at com.hazelcast.util.executor.PoolExecutorThreadFactory$ManagedThread.run(PoolExecutorThreadFactory.java:59)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.resolveResponse(BasicInvocation.java:862)
	at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.resolveResponseOrThrowException(BasicInvocation.java:795)
	at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:698)
	at com.hazelcast.partition.impl.MigrationRequestOperation$MigrationRequestTask.run(MigrationRequestOperation.java:263)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:619)
	at com.hazelcast.util.executor.PoolExecutorThreadFactory$ManagedThread.run(PoolExecutorThreadFactory.java:59)
2015-09-17 12:55:33,974 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 1
2015-09-17 12:55:34,974 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 1
2015-09-17 12:55:35,974 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 1
2015-09-17 12:55:36,458 [hz._hzInstance_1_Prod.tradeIn.migration           ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Partition state sync invocation timed out: java.util.concurrent.TimeoutException: Call BasicInvocation{ serviceName='hz:core:partitionService', op=com.hazelcast.partition.impl.PartitionStateOperation@acbb49, partitionId=-1, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[10.87.169.135]:5705} encountered a timeout
2015-09-17 12:55:36,974 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 34
2015-09-17 12:55:37,974 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 34
2015-09-17 12:55:38,974 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 34
2015-09-17 12:55:39,505 [hz._hzInstance_1_Prod.tradeIn.migration           ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Partition state sync invocation timed out: java.util.concurrent.TimeoutException: Call BasicInvocation{ serviceName='hz:core:partitionService', op=com.hazelcast.partition.impl.PartitionStateOperation@1de71db, partitionId=-1, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[10.87.169.135]:5705} encountered a timeout
2015-09-17 12:55:39,505 [hz._hzInstance_1_Prod.tradeIn.migration           ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Re-partitioning cluster data... Migration queue size: 34
2015-09-17 12:55:39,973 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 33
2015-09-17 12:55:40,973 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 33
2015-09-17 12:55:41,973 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 33
2015-09-17 12:55:42,520 [hz._hzInstance_1_Prod.tradeIn.migration           ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Partition state sync invocation timed out: java.util.concurrent.TimeoutException: Call BasicInvocation{ serviceName='hz:core:partitionService', op=com.hazelcast.partition.impl.PartitionStateOperation@ccce4f, partitionId=-1, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[10.87.169.135]:5705} encountered a timeout
2015-09-17 12:55:42,598 [hz._hzInstance_1_Prod.tradeIn.cached.thread-3     ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Remaining migration tasks in queue => 32
2015-09-17 12:55:42,973 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 32
2015-09-17 12:55:43,973 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 32
2015-09-17 12:55:44,973 [Thread-1                                          ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Waiting for cluster migration tasks: 32
2015-09-17 12:55:45,535 [hz._hzInstance_1_Prod.tradeIn.migration           ] INFO  rnalPartitionService -                      -                      -                      - [10.87.169.140]:5705 [Prod.tradeIn] [3.2.3] Partition state sync invocation timed out: java.util.concurrent.TimeoutException: Call BasicInvocation{ serviceName='hz:core:partitionService', op=com.hazelcast.partition.impl.PartitionStateOperation@aac607, partitionId=-1, replicaIndex=0, tryCount=250, tryPaus

**Comment by jerrinot** [comment] 2015-09-18 12:58
This seems as a duplicate of #6244
I'm closing this issue - my recommendation is the same as in the case of #6244: Upgrade to the latest stable version. Feel free to re-open the issue if you get the same issue even after the upgrade.

**Closed** 2015-09-18 13:03 UTC
Labels: Type: Defect
