### ISSUE TITLE
feature req: way to launch timed job in the cluster on single node

### ISSUE THREAD

**Issue by logemann** [hazelcast/hazelcast#3848] opened 2014-10-14 12:52 UTC
Hazelcast has a nice ExecutorService. Unfortunately that doesnt help the problem that in a cluster, each node would fire a job task when using for example @scheduled annotation from Spring. And using Quartz is way too much overhead. Right now we use @scheduled togehter with tryLock so that the other nodes getting late on the code, are being blocked away. This is more a hack than a clean implementation for a situation like this.

It would be nice if hazelcast would help in triggering methods like spring does but only on a single node. This way i could use hazelcasts executorService and decide how the job is getting submitted to the nodes. Something like a smart @scheduled annotation which makes sure that only one node can execute that method. There i would use the executor Service to exactly tell what to do with the job to be submitted.

**Comment by enesakar** [comment] 2015-01-15 14:16
duplicate of https://github.com/hazelcast/hazelcast/issues/115
closing.

**Closed by enesakar** 2015-01-15 14:16 UTC
Labels: PENDING, Type: Enhancement
