### ISSUE TITLE
Restart/reinstantiate the Hazelcast

### ISSUE THREAD

**Issue by sudheermg** [hazelcast/hazelcast#7350] opened 2016-01-18 11:42 UTC
How to restart (reinstantiate) when the hazelcast instance is down. We observed that Hazelcast instance is not active ( IllegalStateException) in the logs and the root cause for this is Out of memory issue. Because of this the Hazelcast instance went down and all the subsequent requests to hazelcast got failed with IllegalStateException.
 How I can reinstantiate the Hazelcast automatically.

**Comment by Donnerbart** [comment] 2016-01-18 11:51
Duplicate of #7271

**Closed by Donnerbart** 2016-01-18 11:51 UTC
