### ISSUE TITLE
The performance hint implies java.io.Serializable is used for String

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast#15994] opened 2019-11-12 17:53 UTC
```
NFO [InternalSerializationService] [pool-1-thread-1] - Performance Hint: Serialization service will use java.io.Serializable for: java.lang.String. Please consider using a faster serialization option such as DataSerializable.
```

**Comment by mmedenjak** [comment] 2019-11-20 11:52
The serializer for String is registered [here](https://github.com/hazelcast/hazelcast/blob/a12b8096b49835bc2c2706747edd3d65ccbc3413/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/SerializationServiceV1.java#L178) during the construction of the serialization service. But the `constantTypesMap` is [cleared during node shutdown](https://github.com/hazelcast/hazelcast/blob/711cad94be27e7726958192f61701b1d1fb88811/hazelcast/src/main/java/com/hazelcast/instance/impl/Node.java#L583) so there might be a race between the shutdown procedure and some serialization. @gurbuzali do you have some logs to confirm this?

Even so, there is some occurrences of `Please consider using a faster serialization option such as DataSerializable` in the PR builder logs that I'll inspect.

**Comment by mmedenjak** [comment] 2019-11-20 12:11
For instance, this message occurs in the tests:
- `ConfiguredBehaviourTest#testReconnectModeOFFTwoMembers`
- `ConfiguredBehaviourTest#testReconnectModeOFFSingleMember`
- `MapLoaderFailoverTest#testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading`
- `MapLoaderFailoverTest#testLoadsAll_whenInitialLoaderNodeRemovedWhileLoadingAndNoBackups`
- `CacheThroughHazelcastInstanceTest#getCache_whenOwnerInstanceIsShutdown_thenOperateOnCacheFails`
- `CacheThroughHazelcastInstanceTest#getDistributedObject_whenOwnerInstanceIsShutdown_thenOperateOnCacheFails`

All of these are reproducible locally - they shut down an instance after which some serialization is ongoing. These I was unable to reproduce:
- `CacheStatsTest#testHitStat`
- `ReplicatedMapStatsTest#testLastUpdateTime_updatedConcurrently`
- `ReplicatedMapStatsTest#testLastAccessTime_updatedConcurrently`

**Comment by mmedenjak** [comment] 2019-11-20 12:11
Closing as a non-issue then.

**Closed by mmedenjak** 2019-11-20 12:11 UTC
Labels: Module: Serialization, Source: Internal, Source: Jet, Team: Core
