### ISSUE TITLE
EvictionTest.testIssue585SetWithoutTTL

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4433] opened 2015-01-19 07:29 UTC
```
java.lang.AssertionError: the size of the map is not correct expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at com.hazelcast.test.HazelcastTestSupport$3.run(HazelcastTestSupport.java:134)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:251)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:131)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:127)
	at com.hazelcast.map.EvictionTest.testIssue585SetWithoutTTL(EvictionTest.java:174)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/426/testReport/junit/com.hazelcast.map/EvictionTest/testIssue585SetWithoutTTL/

**Comment by ahmetmircik** [comment] 2015-01-19 13:02
A possible fix https://github.com/hazelcast/hazelcast/commit/55697240307f7257c91a1b275fd0713c3b5a3ecb

It looks like with an unlucky timing, background expiration thread may need some more time to find the right partition which includes expiration candidate entry, since expiration operation is not sent whole partitions in one round, it scans some portions of them lazily in every run.

**Comment by bilalyasar** [comment] 2015-01-21 17:42
again failed:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/428/testReport/junit/com.hazelcast.map/EvictionTest/testIssue585SetWithoutTTL/

**Comment by ahmetmircik** [comment] 2015-02-17 09:18
Closing this now, seems test is not failing for a long time and also i did not manage to reproduce the problem. 
Waiting for the next failure.

**Comment by bilalyasar** [comment] 2015-03-10 20:12
seems new failure came :)
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/com.hazelcast$hazelcast/169/testReport/junit/com.hazelcast.map/EvictionTest/testIssue585SetWithoutTTL/

**Comment by ahmetmircik** [comment] 2015-03-11 10:24
Only failing under `IbmJDK1.6`, will try to reproduce there.

**Comment by ahmetmircik** [comment] 2015-05-14 14:42
Seems not failing for a long time, closing this issue and waiting for next failure.

**Comment by hasancelik** [comment] 2016-06-03 07:21
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:280)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:883)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:690)
	at com.hazelcast.map.EvictionTest.testIssue585SetWithoutTTL(EvictionTest.java:187)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/500/testReport/junit/com.hazelcast.map/EvictionTest/testIssue585SetWithoutTTL/

**Comment by ahmetmircik** [comment] 2016-06-09 12:37
should be fixed via https://github.com/hazelcast/hazelcast/commit/5269c9b8158f2f6717e6ee8495c9c4860e558c3f

**Comment by hasancelik** [comment] 2016-06-23 07:55
```
java.lang.AssertionError: Key should be expired after 1 seconds expected null, but was:<value2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.map.EvictionTest$1.run(EvictionTest.java:194)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:884)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:898)
	at com.hazelcast.map.EvictionTest.testIssue585SetWithoutTTL(EvictionTest.java:191)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5317/testReport/junit/com.hazelcast.map/EvictionTest/testIssue585SetWithoutTTL/

**Closed** 2016-06-27 06:55 UTC
Labels: Team: Core, Type: Test-Failure

**Comment by gurbuzali** [comment] 2016-06-27 06:57
the test was very fragile, entry may expire between 2 `set` calls
```
map.set(key, "value", 1, TimeUnit.SECONDS);
// this `set` operation should not affect existing ttl.
/ so "key" should be expired after 1 seconds.
map.set(key, "value2");
```
I've increased the ttl to 5 seconds
