### ISSUE TITLE
MergePolicyProviderConstructorTest.testConstructor

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15296] opened 2019-07-10 09:06 UTC
_master_ (commit 54d318a)

Failed on Sonar :http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/170/testReport/junit/com.hazelcast.test.starter.constructor.test/MergePolicyProviderConstructorTest/testConstructor/

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/170/testReport/junit/com.hazelcast.test.starter.test/HazelcastStarterTest/testHazelcastInstanceCompatibility_withStarterInstance/

MergePolicyProviderConstructorTest.testConstructor
HazelcastStarterTest.testHazelcastInstanceCompatibility_withStarterInstance

**Stacktrace**
```
com.hazelcast.test.starter.GuardianException: java.lang.ClassNotFoundException: com.hazelcast.instance.impl.HazelcastInstanceProxy
	at com.hazelcast.test.starter.HazelcastStarterUtils.rethrowGuardianException(HazelcastStarterUtils.java:53)
	at com.hazelcast.test.starter.HazelcastStarter.getNode(HazelcastStarter.java:127)
	at com.hazelcast.instance.impl.TestUtil.getNode(TestUtil.java:74)
	at com.hazelcast.test.HazelcastTestSupport.getNode(HazelcastTestSupport.java:258)
	at com.hazelcast.test.HazelcastTestSupport.getNodeEngineImpl(HazelcastTestSupport.java:266)
	at com.hazelcast.test.starter.constructor.test.MergePolicyProviderConstructorTest.testConstructor(MergePolicyProviderConstructorTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.instance.impl.HazelcastInstanceProxy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at com.hazelcast.test.starter.HazelcastAPIDelegatingClassloader.loadClass(HazelcastAPIDelegatingClassloader.java:118)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.test.starter.HazelcastStarter.getHazelcastInstanceImpl(HazelcastStarter.java:162)
	at com.hazelcast.test.starter.HazelcastStarter.getNode(HazelcastStarter.java:120)
```

**Comment by vojtechtoman** [comment] 2019-07-12 08:57
Duplicate of https://github.com/hazelcast/hazelcast/issues/15263?

**Closed** 2019-07-12 09:21 UTC
Labels: Source: Internal, Team: Core, Type: Test-Failure
