### ISSUE TITLE
ClientMapEventJournalBasicTest allowReadingWithFutureSeq test failure

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#16970] opened 2020-05-09 11:32 UTC
- Fails on `Hazelcast-4.maintenance-OracleJDK8`
- Fails on [Build #74 (May 7, 2020 2:15:04 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-OracleJDK8/74/testReport/junit/com.hazelcast.client.map/ClientMapEventJournalBasicTest/allowReadingWithFutureSeq/)
- Error 
```
CountDownLatch failed to complete within 30 seconds, count left: 1
```
- Stacktrace
```
java.lang.AssertionError: CountDownLatch failed to complete within 30 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1237)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1222)
	at com.hazelcast.journal.AbstractEventJournalBasicTest.allowReadingWithFutureSeq(AbstractEventJournalBasicTest.java:511)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
- Hiccups
```
Hiccups measured while running test 'allowReadingWithFutureSeq(com.hazelcast.client.map.ClientMapEventJournalBasicTest):'
02:33:00, accumulated pauses: 225 ms, max pause: 92 ms, pauses over 1000 ms: 0
02:33:05, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:33:10, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:33:15, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:33:20, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:33:25, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:33:30, accumulated pauses: 238 ms, max pause: 210 ms, pauses over 1000 ms: 0
```
generally we do not report test failures with high hiccups, but this time it looked suspecting based on accumulated pause and multiple jobs failing.

please note that there is similar failure on `ClientCacheEventJournalBasicTest.allowReadingWithFutureSeq` along with it on failing jobs.

kindly check.

**Comment by mmedenjak** [comment] 2020-05-12 14:01
Duplicate of https://github.com/hazelcast/hazelcast/issues/16964.

**Closed by mmedenjak** 2020-05-12 14:01 UTC
Labels: Source: Internal, Team: Client, Type: Test-Failure
