### ISSUE TITLE
3.6-EA - java.lang.IllegalStateException when starting cluster of 4+ nodes

### ISSUE THREAD

**Issue by fschuh** [hazelcast/hazelcast#6798] opened 2015-11-20 05:37 UTC
When starting a cluster of 4+ nodes, I get the following exception when the last nodes start up:

    04:49:38,247 ERROR hz._hzInstance_1_dev.generic-operation.thread-1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.66]:5701 [dev] [3.6-EA] Cannot set initial state after node joined! -> ACTIVE
    java.lang.IllegalStateException: Cannot set initial state after node joined! -> ACTIVE
            at com.hazelcast.cluster.impl.ClusterServiceImpl.initialClusterState(ClusterServiceImpl.java:877) ~[hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.cluster.impl.operations.FinalizeJoinOperation.run(FinalizeJoinOperation.java:71) ~[hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:167) [hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:386) [hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184) [hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137) [hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124) [hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99) [hazelcast-3.5.2.jar:3.6-EA]

In a cluster of 4 nodes, the third or fourth node always display this error when they start up.
And if I start more nodes, they will all show this error as well.
Usually the first 3 nodes will start up without any errors (nodes 1 and 2 never showed the errors).

Despite throwing that exception, the affected nodes still start up normally.
Note that, most of the time, the cluster still works fine even though I get this error.
But other times it will slow down to a crawl, and IMap get()/put() operations take a long, long time to return.

I'm using TCP discovery for my nodes (I specify the IP address of each node).

Here's the full startup log of an affected third node of my cluster:

    05:27:34,463 INFO  main com.ubi.petz.Application.startup(Application.java:60) - starting up
    Nov 20, 2015 5:27:35 AM com.hazelcast.config.AbstractXmlConfigHelper
    WARNING: Name of the hazelcast schema location incorrect using default
    05:27:35,454 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [LOCAL] [dev] [3.6-EA] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [10.224.111.63, 10.224.111.62, 10.224.111.61, 10.224.111.60, 10.224.111.67, 10.224.111.66, 10.224.111.65, 10.224.111.64, 10.224.111.69, 10.224.111.68]
    05:27:35,454 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [LOCAL] [dev] [3.6-EA] Prefer IPv4 stack is true.
    05:27:35,460 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [LOCAL] [dev] [3.6-EA] Picked Address[10.224.111.63]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
    05:27:35,647 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Backpressure is disabled
    05:27:35,668 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Starting with 2 generic operation threads and 4 partition operation threads.
    05:27:36,028 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Hazelcast 3.6-EA (20151023 - 0bfc9a6) starting at Address[10.224.111.63]:5701
    05:27:36,029 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved.
    05:27:36,029 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Configured Hazelcast Serialization version:1
    05:27:36,033 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Creating TcpIpJoiner
    05:27:36,034 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.63]:5701 is STARTING
    05:27:36,113 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads
    05:27:36,133 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.66:5703, timeout: 0, bind-any: true
    05:27:36,133 INFO  cached3 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.64:5701, timeout: 0, bind-any: true
    05:27:36,134 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.65:5703, timeout: 0, bind-any: true
    05:27:36,135 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.63:5703, timeout: 0, bind-any: true
    05:27:36,136 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.63:5703. Reason: SocketException[Connection refused to address /10.224.111.63:5703]
    05:27:36,136 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.65:5703. Reason: SocketException[Connection refused to address /10.224.111.65:5703]
    05:27:36,136 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.63]:5703 is added to the blacklist.
    05:27:36,137 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.66:5703. Reason: SocketException[Connection refused to address /10.224.111.66:5703]
    05:27:36,137 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.66]:5703 is added to the blacklist.
    05:27:36,137 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.65]:5703 is added to the blacklist.
    05:27:36,137 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.62:5701, timeout: 0, bind-any: true
    05:27:36,138 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.62:5701. Reason: SocketException[Connection refused to address /10.224.111.62:5701]
    05:27:36,138 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.62]:5701 is added to the blacklist.
    05:27:36,137 INFO  cached5 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.61:5701, timeout: 0, bind-any: true
    05:27:36,139 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.64:5703, timeout: 0, bind-any: true
    05:27:36,137 INFO  cached3 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.64:5701. Reason: SocketException[Connection refused to address /10.224.111.64:5701]
    05:27:36,140 INFO  cached3 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.64]:5701 is added to the blacklist.
    05:27:36,140 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.64:5703. Reason: SocketException[Connection refused to address /10.224.111.64:5703]
    05:27:36,140 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.64]:5703 is added to the blacklist.
    05:27:36,146 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.61:5703, timeout: 0, bind-any: true
    05:27:36,146 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.62:5703, timeout: 0, bind-any: true
    05:27:36,146 INFO  cached3 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.60:5701, timeout: 0, bind-any: true
    05:27:36,147 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.68:5702, timeout: 0, bind-any: true
    05:27:36,147 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.62:5703. Reason: SocketException[Connection refused to address /10.224.111.62:5703]
    05:27:36,147 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.62]:5703 is added to the blacklist.
    05:27:36,147 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.61:5703. Reason: SocketException[Connection refused to address /10.224.111.61:5703]
    05:27:36,147 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.60:5703, timeout: 0, bind-any: true
    05:27:36,147 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.68:5702. Reason: SocketException[Connection refused to address /10.224.111.68:5702]
    05:27:36,147 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.61]:5703 is added to the blacklist.
    05:27:36,148 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.68]:5702 is added to the blacklist.
    05:27:36,148 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.60:5703. Reason: SocketException[Connection refused to address /10.224.111.60:5703]
    05:27:36,148 INFO  cached5 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Established socket connection between /10.224.111.63:57254 and /10.224.111.61:5701
    05:27:36,148 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.60]:5703 is added to the blacklist.
    05:27:36,148 INFO  cached3 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Established socket connection between /10.224.111.63:47616 and /10.224.111.60:5701
    05:27:36,150 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.69:5702, timeout: 0, bind-any: true
    05:27:36,150 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.66:5702, timeout: 0, bind-any: true
    05:27:36,151 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.67:5702, timeout: 0, bind-any: true
    05:27:36,151 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.66:5702. Reason: SocketException[Connection refused to address /10.224.111.66:5702]
    05:27:36,151 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.66]:5702 is added to the blacklist.
    05:27:36,152 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.67:5702. Reason: SocketException[Connection refused to address /10.224.111.67:5702]
    05:27:36,152 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.69:5702. Reason: SocketException[Connection refused to address /10.224.111.69:5702]
    05:27:36,152 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.67]:5702 is added to the blacklist.
    05:27:36,152 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.69]:5702 is added to the blacklist.
    05:27:36,154 INFO  cached3 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.64:5702, timeout: 0, bind-any: true
    05:27:36,154 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.65:5702, timeout: 0, bind-any: true
    05:27:36,155 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.62:5702, timeout: 0, bind-any: true
    05:27:36,155 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.63:5702, timeout: 0, bind-any: true
    05:27:36,155 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.65:5702. Reason: SocketException[Connection refused to address /10.224.111.65:5702]
    05:27:36,155 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.62:5702. Reason: SocketException[Connection refused to address /10.224.111.62:5702]
    05:27:36,155 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.65]:5702 is added to the blacklist.
    05:27:36,155 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.63:5702. Reason: SocketException[Connection refused to address /10.224.111.63:5702]
    05:27:36,156 INFO  cached3 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.64:5702. Reason: SocketException[Connection refused to address /10.224.111.64:5702]
    05:27:36,156 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.60:5702, timeout: 0, bind-any: true
    05:27:36,156 INFO  cached3 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.64]:5702 is added to the blacklist.
    05:27:36,155 INFO  cached1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.62]:5702 is added to the blacklist.
    05:27:36,156 INFO  cached4 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.63]:5702 is added to the blacklist.
    05:27:36,156 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.60:5702. Reason: SocketException[Connection refused to address /10.224.111.60:5702]
    05:27:36,156 INFO  cached6 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.60]:5702 is added to the blacklist.
    05:27:36,156 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.61:5702, timeout: 0, bind-any: true
    05:27:36,157 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.61:5702. Reason: SocketException[Connection refused to address /10.224.111.61:5702]
    05:27:36,157 INFO  cached2 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.61]:5702 is added to the blacklist.
    05:27:36,159 INFO  cached11 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.67:5701, timeout: 0, bind-any: true
    05:27:36,160 INFO  cached11 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.67:5701. Reason: SocketException[Connection refused to address /10.224.111.67:5701]
    05:27:36,160 INFO  cached11 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.67]:5701 is added to the blacklist.
    05:27:36,160 INFO  cached8 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.69:5701, timeout: 0, bind-any: true
    05:27:36,160 INFO  cached12 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.69:5703, timeout: 0, bind-any: true
    05:27:36,161 INFO  cached5 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.67:5703, timeout: 0, bind-any: true
    05:27:36,161 INFO  cached9 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.68:5701, timeout: 0, bind-any: true
    05:27:36,161 INFO  cached8 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.69:5701. Reason: SocketException[Connection refused to address /10.224.111.69:5701]
    05:27:36,162 INFO  cached8 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.69]:5701 is added to the blacklist.
    05:27:36,162 INFO  cached9 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.68:5701. Reason: SocketException[Connection refused to address /10.224.111.68:5701]
    05:27:36,162 INFO  cached9 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.68]:5701 is added to the blacklist.
    05:27:36,162 INFO  cached5 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.67:5703. Reason: SocketException[Connection refused to address /10.224.111.67:5703]
    05:27:36,161 INFO  cached12 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.69:5703. Reason: SocketException[Connection refused to address /10.224.111.69:5703]
    05:27:36,162 INFO  cached5 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.67]:5703 is added to the blacklist.
    05:27:36,162 INFO  cached12 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.69]:5703 is added to the blacklist.
    05:27:36,163 INFO  cached7 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.65:5701, timeout: 0, bind-any: true
    05:27:36,164 INFO  cached10 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.66:5701, timeout: 0, bind-any: true
    05:27:36,164 INFO  cached11 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Connecting to /10.224.111.68:5703, timeout: 0, bind-any: true
    05:27:36,164 INFO  cached7 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.65:5701. Reason: SocketException[Connection refused to address /10.224.111.65:5701]
    05:27:36,164 INFO  cached10 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.66:5701. Reason: SocketException[Connection refused to address /10.224.111.66:5701]
    05:27:36,164 INFO  cached7 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.65]:5701 is added to the blacklist.
    05:27:36,164 INFO  cached10 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.66]:5701 is added to the blacklist.
    05:27:36,164 INFO  cached11 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Could not connect to: /10.224.111.68:5703. Reason: SocketException[Connection refused to address /10.224.111.68:5703]
    05:27:36,165 INFO  cached11 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.68]:5703 is added to the blacklist.
    05:27:37,180 WARN  hz._hzInstance_1_dev.generic-operation.thread-1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Following unknown addresses are found in partition table sent from master[Address[10.224.111.60]:5701]. (Probably they have recently joined or left the cluster.) {
            Address[10.224.111.61]:5701
            Address[10.224.111.60]:5701
    }
    05:27:37,182 INFO  hz._hzInstance_1_dev.generic-operation.thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] 

    Members [3] {
            Member [10.224.111.60]:5701
            Member [10.224.111.61]:5701
            Member [10.224.111.63]:5701 this
    }

    05:27:37,199 ERROR hz._hzInstance_1_dev.generic-operation.thread-1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Cannot set initial state after node joined! -> ACTIVE
    java.lang.IllegalStateException: Cannot set initial state after node joined! -> ACTIVE
            at com.hazelcast.cluster.impl.ClusterServiceImpl.initialClusterState(ClusterServiceImpl.java:877) ~[hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.cluster.impl.operations.FinalizeJoinOperation.run(FinalizeJoinOperation.java:71) ~[hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:167) [hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:386) [hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184) [hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137) [hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124) [hazelcast-3.5.2.jar:3.6-EA]
            at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99) [hazelcast-3.5.2.jar:3.6-EA]
    05:27:39,189 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Hazelcast JMX agent enabled.
    05:27:39,235 INFO  vert.x-worker-thread-0 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Address[10.224.111.63]:5701 is STARTED

I think this excerpt from the log is probably the cause of the issue:

    05:27:37,180 WARN  hz._hzInstance_1_dev.generic-operation.thread-1 com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224) - [10.224.111.63]:5701 [dev] [3.6-EA] Following unknown addresses are found in partition table sent from master[Address[10.224.111.60]:5701]. (Probably they have recently joined or left the cluster.) {
            Address[10.224.111.61]:5701
            Address[10.224.111.60]:5701
    }

Those two nodes are still part of my cluster, and they never left.
Those nodes also had normal startups with no errors, and they didn't display that warning either.
That's what's probably causing the bug in my opinion.

**Comment by mdogan** [comment] 2015-11-20 08:06
Thanks for the report. This is fixed after EA is released. 

Duplicate of #6684

**Closed by mdogan** 2015-11-20 08:06 UTC
