### ISSUE TITLE
Reset interrupted status when catching exceptions

### ISSUE THREAD

**Issue by wimdeblauwe** [hazelcast/hazelcast#6219] opened 2015-09-15 09:31 UTC
I have noticed that you don't restore the interrupted status of the thread in some cases. This is recommended (See http://stackoverflow.com/questions/3976344/handling-interruptedexception-in-java).

One example (from PartitionIterationOperation):

```
 public void run() throws Exception {
        results = new HashMap<Integer, Object>(partitions.size());
        try {
            Map<Integer, ResponseQueue> responses = executeOperations();
            getResults(responses);
        } catch (Exception e) {
            getLogger(getNodeEngine()).severe(e);
        }
    }
```

The `getResults` method throws an InterruptedException, so it should be modified to:

```
 public void run() throws Exception {
        results = new HashMap<Integer, Object>(partitions.size());
        try {
            Map<Integer, ResponseQueue> responses = executeOperations();
            getResults(responses);
        } catch (InterruptedException e) {
             Thread.currentThread().interrupt();
             getLogger(getNodeEngine()).severe(e);
        } catch (Exception e) {
            getLogger(getNodeEngine()).severe(e);
        }
    }
```

**Comment by jerrinot** [comment] 2015-09-15 09:35
@wimdeblauwe: You are right. Thanks for raising this!

**Comment by wimdeblauwe** [comment] 2015-09-15 09:47
The same issue is also present in `AbstractCallableMessageTask` since `collectResults` in `AbstractMapQueryMessageTask` also throws an InterruptedException. There might be others, but these are the ones I found at first glance.

**Comment by nikit-ap** [comment] 2015-09-22 06:08
also happens in com.hazelcast.client.spi.ClientProxy.invoke()
and generally in com.hazelcast.util.ExceptionUtil

**Comment by Nnidyu** [comment] 2016-11-09 14:49
I have a similar bug with `ITopic#publish`. When the thread is interrupted before or during this call, it destroys the interruption status.

The check is done within `LinkedBlockingQueue#offer` (from `com.hazelcast.util.executor.StripedExecutor.Worker#schedule`) it throws `InterruptedException` and then it is eaten by a catch few lines later:
```java
} catch (InterruptedException e) {
    throw new RejectedExecutionException("Thread is interrupted while offering work");
}
```

Then `RejectedInterruptedException` is eaten in `com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl#executeLocal`.

I am using Hazelcast 3.7.2.

**Comment by guymahieu** [comment] 2016-11-15 08:46
In com.hazelcast.client.spi.impl.listener.ClientSmartListenerService, if there is an `InterruptedException`  when `future.get()` is called, there is also no handling of the interruption, the `ExceptionUtil.rethrow(e)` will simply wrap the exception and throw it.

`        try {
            return future.get();
        } catch (Exception e) {
            throw ExceptionUtil.rethrow(e);
        }
`

Shouldn't this be something like:
`        try {
            return future.get();
        } catch (InterruptedException e) {
            future.cancel(true);   
            throw ExceptionUtil.rethrow(e);
        } catch (Exception e) {
            throw ExceptionUtil.rethrow(e);
        }
`
?

**Comment by sancar** [comment] 2020-02-18 09:49
Closing this since this is duplicate of https://github.com/hazelcast/hazelcast/issues/12452 .

**Closed by sancar** 2020-02-18 09:49 UTC
Labels: Source: Community, Team: Client, Team: Core, Type: Defect
