### ISSUE TITLE
scheduled task dispose OOME hazelcast.executionservice.taskscheduler.remove.oncancel=false (default)

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11657] opened 2017-10-24 04:49 UTC
https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-All/80/consoleFull
/disk1/jenkins/workspace/stable-All/3.9/2017_10_20-17_16_35/executor/scheduled/schedule-dispose Failed
http://54.82.84.143/~jenkins/workspace/stable-All/3.9/2017_10_20-17_16_35/executor/scheduled/schedule-dispose
output/HZ/HzMember2HZ/HzMember2HZ.hprof
output/HZ/HzMember1HZ/HzMember1HZ.hprof

the test was passing before, 
when we fixed https://github.com/hazelcast/hazelcast/issues/11221

we disabled task removal from the internal j.u.c.ScheduledThreadPool in the last patch on 3.9 to avoid that hanging issue we had with the dispose-all. so now tasks will stay in that pool for 1hr before they get cleaned

http://54.82.84.143/~jenkins/workspace/stable-All/3.9/2017_10_20-17_16_35/executor/scheduled/schedule-dispose/schedule

https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/executor/scheduled/ScheduleDispose.java#L20

now we need to use 
```
hazelcast.executionservice.taskscheduler.remove.oncancel
```
 and this should behave as it did before our change.

but it can cause slow operations to the point that the node can hang
https://github.com/hazelcast/hazelcast/issues/11265
we will try to address this better in 3.10

so issues 
https://github.com/hazelcast/hazelcast/issues/11221
and
https://github.com/hazelcast/hazelcast/issues/11265

are related, and we can not fix both of them at the same time, 
currently we are going to hit one of them (oome or hang) depending on how 
`hazelcast.executionservice.taskscheduler.remove.oncancel` is set.

**Comment by tkountis** [comment] 2017-10-31 15:37
@Danny-Hazelcast i am having doubts that this test was consistently & correctly passing before the fix on #11221. Would you be able to run the version before that fix, with your latest test code, to verify this? I am pretty confident that we had the leak before, even though it wasn't always failing!

**Comment by tkountis** [comment] 2018-02-21 15:18
I will address this by providing a capacity per node configuration.
see. https://github.com/hazelcast/hazelcast/issues/11629

Moving this to 3.11 as the change will most likely won't make it to 3.10 at this stage.

**Comment by mmedenjak** [comment] 2019-12-04 15:13
Closing as a duplicate of https://github.com/hazelcast/hazelcast/issues/11629.

**Closed by mmedenjak** 2019-12-04 15:13 UTC
Labels: Module: IScheduledExecutor, Priority: Medium, Source: Internal, Team: Core, Type: Defect
