### ISSUE TITLE
[TEST-FAILURE] MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading

### ISSUE THREAD

**Issue by tombujok** [hazelcast/hazelcast#7369] opened 2016-01-19 16:09 UTC
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast%24hazelcast/688/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

```
Stacktrace

org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:300)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:245)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.map.impl.proxy.MapProxySupport.waitUntilLoaded(MapProxySupport.java:508)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.waitUntilLoaded(MapProxyImpl.java:80)
	at com.hazelcast.map.impl.proxy.MapProxySupport.loadAllInternal(MapProxySupport.java:412)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.loadAll(MapProxyImpl.java:543)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading(MapLoaderFailoverTest.java:112)
```

**Comment by hasancelik** [comment] 2016-01-20 08:24
closing, duplicate of https://github.com/hazelcast/hazelcast/issues/6056

**Closed by hasancelik** 2016-01-20 08:24 UTC
Labels: Team: Core, Type: Test-Failure
