### ISSUE TITLE
Problem with lifetime in case with wan replication 

### ISSUE THREAD

**Issue by alevinsp** [hazelcast/hazelcast#5457] opened 2015-06-05 11:57 UTC
When updating records through the WAN replication the lifetime of record is not updated in the destination cluster. This leads to early eviction entries from the cluster. Version of hazelcast 3.2.4

**Comment by mesutcelik** [comment] 2015-06-24 13:01
I think that is duplicate of https://github.com/hazelcast/hazelcast/pull/5221

**Closed by mesutcelik** 2015-06-24 13:01 UTC
Labels: PENDING, Team: Integration
