### ISSUE TITLE
[TEST-FAILURE] ClientMapTest.testIssue537

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6564] opened 2015-10-26 12:11 UTC
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testIssue537(ClientMapTest.java:139)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast-client/723/testReport/junit/com.hazelcast.client.map/ClientMapTest/testIssue537/

**Comment by Donnerbart** [comment] 2015-11-10 11:13
Duplicate of #6694

**Closed by Donnerbart** 2015-11-10 11:13 UTC
Labels: Team: Client, Type: Defect
