### ISSUE TITLE
CacheManagerManagementTest test failures

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15969] opened 2019-11-11 08:44 UTC
master (commit 94d3d2c713ed0f6c49a2922330cb21e3785be449)

Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/296/#showFailuresLink

```
com.hazelcast.cache.jsr.CacheManagerManagementTest.testJMXGetsCacheAdditionsAndRemovals
com.hazelcast.cache.jsr.CacheManagerManagementTest.testJMXGetsCacheAdditionsAndRemovals
com.hazelcast.cache.jsr.CacheManagerManagementTest.testCacheStatisticsOffThenOnThenOff
com.hazelcast.cache.jsr.CacheManagerManagementTest.testCacheStatisticsOffThenOnThenOff
com.hazelcast.cache.jsr.CacheManagerManagementTest.testCacheManagementOffThenOnThenOff
com.hazelcast.cache.jsr.CacheManagerManagementTest.testCacheManagementOffThenOnThenOff
com.hazelcast.cache.jsr.CacheManagerManagementTest.testDoubleRegistration
com.hazelcast.cache.jsr.CacheManagerManagementTest.testDoubleRegistration
com.hazelcast.cache.jsr.CacheManagerManagementTest.testNoEntriesWhenNoCaches
com.hazelcast.cache.jsr.CacheManagerManagementTest.testNoEntriesWhenNoCaches
com.hazelcast.cache.jsr.CacheManagerManagementTest.testMultipleCacheManagers
com.hazelcast.cache.jsr.CacheManagerManagementTest.testMultipleCacheManagers
```

```
java.lang.AssertionError: 

Expected: an empty collection
     but: <[javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-34, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-79, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-71, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-23, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-60, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-3, javax.cache:type=CacheStatistics,CacheManager=,Cache=myCache, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-11, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-67, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-93, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-19, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-45, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-82, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-56, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-22, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-92, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-61, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-78, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-35, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-57, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-18, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-66, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-4, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-10, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-44, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-70, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-83, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-32, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-73, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-47, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-91, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-21, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-9, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-58, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-50, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-13, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-84, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-99, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-1, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-37, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-81, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-89, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-24, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-76, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-63, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-55, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-6, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-94, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-42, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-68, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-16, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-29, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-30, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-38, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-75, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-86, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-49, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-64, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-7, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-52, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-15, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-97, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-41, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-31, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-74, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-87, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-26, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-39, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-65, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-48, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-8, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-53, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-40, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-96, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-27, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-14, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-0, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-80, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-88, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-25, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-36, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-62, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-77, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-54, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-17, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-5, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-43, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-95, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-69, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-28, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-33, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-85, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-72, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-46, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-90, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-20, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-59, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-2, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-12, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-51, javax.cache:type=CacheStatistics,CacheManager=,Cache=cache-with-stats-98]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.jsr107.tck.management.CacheManagerManagementTest.tearDown(CacheManagerManagementTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:402)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:302)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

**Comment by tezc** [comment] 2019-11-18 06:23
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/303/testReport/

**Comment by lazerion** [comment] 2020-02-11 13:55
- Fails on `Hazelcast-4.master-sonar`
- Fails on [Build #392 (Feb 10, 2020 9:36:04 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/392/#showFailuresLink)

- please let me know if we need a new issue
- Kindly check

**Comment by vbekiaris** [comment] 2020-02-11 15:04
Even though `com.hazelcast.client.cache.jsr.CacheManagerManagementTest` is executed with serial junit runner, I can see traces of `CacheExpirationTest` in the log files. This is the cause of failures, somehow test isolation was broken.

**Comment by vbekiaris** [comment] 2020-02-12 15:42
After all, it seems `CacheExpirationTest` properly finished execution and was not executing at the same time as `CacheManagerManagementTest`. The `CacheExpirationTest` method name which is logged in several other tests in the same build is due to a leak of the loggers' thread local context to `ForkJoinPool#commonPool` threads. Those threads were apparently created during execution of `testSimpleExpiration_put[useSyncBackups:true]` and the test logger's thread local context is inherited (as set [here](https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/test/java/com/hazelcast/test/TestLoggingUtils.java#L37)). Then the same `FJP#commonPool` threads are reused in other tests, but `test-name` key was not cleaned up from the thread local context of the worker thread.

**Comment by lazerion** [comment] 2020-02-15 08:32
- Fails `Hazelcast-4.master-sonar`
- Failed on [Build #396 (Feb 14, 2020 9:17:02 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/396/#showFailuresLink)

kindly check

**Comment by vbekiaris** [comment] 2020-04-10 06:30
@lazerion this test has not failed for the last several sonar builds, we can reopen if it occurs again.

**Comment by lazerion** [comment] 2020-07-18 09:24
- Fails on `Hazelcast-4.master-sonar`
- Fails on [Build #560 (Jul 17, 2020 9:17:00 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/lastCompletedBuild/#showFailuresLink)
- Kindly check.

**Comment by lazerion** [comment] 2020-07-22 13:38
@vbekiaris could you check this out pls? It looks stable on failures :). [Hazelcast-4.master-sonar](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/564/#showFailuresLink)

**Comment by lazerion** [comment] 2020-08-06 12:47
- Continues to fail [Build #581 (Aug 6, 2020 6:32:11 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/581/#showFailuresLink)

**Comment by vbekiaris** [comment] 2020-08-07 12:42
The failures are caused by other tests not destroying caches used in tests -> MBeans are left registered on the platform MBean server -> verifications about number of registered mbeans in `CacheManagerManagementTest` are off. I am trying to reproduce the failures, having added a JMX leak detector in the test's `BeforeClass` method, but the builds so far pass on my clone of the Sonar jenkins job. I will keep on trying.

**Comment by mmedenjak** [comment] 2020-08-11 12:48
Can we add some logging then, maybe some tracking of MBeans creation/destruction and close the issue then?

**Closed** 2020-09-01 08:51 UTC
Labels: Module: ICache, Source: Internal, Team: Core, Type: Test-Failure
