### ISSUE TITLE
After upgrading from 3.6.5 to 3.7.4

### ISSUE THREAD

**Issue by rathishkumar89** [hazelcast/hazelcast#9739] opened 2017-01-24 06:16 UTC
Hi ,
I have followed the instructions from [http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html](url) on a fresh start in the server facing an exception like:

**java.lang.ClassCastException: com.hazelcast.spi.impl.UnmodifiableLazyList cannot be cast to java.util.ArrayList**

P.S all the maps are initialised and while doing the get call using the predicate getting this exception. 

Backend: java with hazelcast

**Comment by jerrinot** [comment] 2017-01-24 06:31
Hi, can you describe your steps and send a full stack trace?

**Comment by rathishkumar89** [comment] 2017-01-24 06:50
Hi jerrinot,

I have placed the stack trace below:

on debugging i found that the issue seems to be happened at the time of retrieving the values from the imap from the following code snippet

**List<Role> roleList = (ArrayList<Role>) roleObject
					.values(UserSqlBuilder.buildRoleSearchHCPredicate(
							Constants.USER_ID, userId));**

2017-01-24 11:33:44 ERROR error:162 - Exception occurred in class com.rathish.test.services.authentication.impl.LocalClient the exception details are: Exception: 
[errorCode  =  504,
 errorMessage  =  Failure - Unable to retrieve entity from database
Detailed exception trace = 
java.lang.ClassCastException: com.hazelcast.spi.impl.UnmodifiableLazyList cannot be cast to java.util.ArrayList
	at com.rathish.test.services.authentication.dao.RoleDao.getRoleByUserId(RoleDao.java:367)
	at com.rathish.test.services.authentication.impl.LocalClient.authorizeCredentials(LocalClient.java:108)
	at com.rathish.test.services.authentication.AuthValidation.validateAuthorization(AuthValidation.java:420)
	at com.rathish.test.services.authentication.AuthValidation.loginValidation(AuthValidation.java:104)
	at com.rathish.test.services.authentication.AuthenticationService.login(AuthenticationService.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:141)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.process(ProxyServlet.java:74)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.doFilter(ProxyServlet.java:291)
	at org.eclipse.equinox.servletbridge.BridgeServlet.process(BridgeServlet.java:149)
	at org.eclipse.equinox.servletbridge.BridgeFilter.doFilter(BridgeFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.rathish.test.web.filter.SessionValidationFilter.doFilter(SessionValidationFilter.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

	at com.rathish.test.services.authentication.dao.RoleDao.getRoleByUserId(RoleDao.java:383)
	at com.rathish.test.services.authentication.impl.LocalClient.authorizeCredentials(LocalClient.java:108)
	at com.rathish.test.services.authentication.AuthValidation.validateAuthorization(AuthValidation.java:420)
	at com.rathish.test.services.authentication.AuthValidation.loginValidation(AuthValidation.java:104)
	at com.rathish.test.services.authentication.AuthenticationService.login(AuthenticationService.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:141)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.process(ProxyServlet.java:74)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.doFilter(ProxyServlet.java:291)
	at org.eclipse.equinox.servletbridge.BridgeServlet.process(BridgeServlet.java:149)
	at org.eclipse.equinox.servletbridge.BridgeFilter.doFilter(BridgeFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.rathish.test.web.filter.SessionValidationFilter.doFilter(SessionValidationFilter.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: com.hazelcast.spi.impl.UnmodifiableLazyList cannot be cast to java.util.ArrayList
	at com.rathish.test.services.authentication.dao.RoleDao.getRoleByUserId(RoleDao.java:367)
	... 56 more

**Comment by jerrinot** [comment] 2017-01-24 07:35
hi @rathishkumar89,

I assume `roleObject` in your code is Hazelcast `IMap`. 

The code invokes [`imap.values(predicate)`](https://github.com/jerrinot/hazelcast/blob/54405ecab28c8511497d283afd98ccf511b52baa/hazelcast/src/main/java/com/hazelcast/core/IMap.java#L1437-L1437), this method has a return type `Collection`. The problem is you cast it to `ArrayList`. However by casting you are assuming a specific implementation of the returned `Collection`. The contract does not guarantee what implementation will be used. It might be `ArrayList` in one version, but it can be another implementation in a different version. If you need a specific type of a Collection for some reason then you need to copy it. 
```java
Collection<V> roleCollection = roleObject.values(UserSqlBuilder.buildRoleSearchHCPredicate(Constants.USER_ID, userId));
ArrayList<V> roleList = new ArrayList(roleCollection);
```

However this should be a last resort. I guess with role checks you will likely check an existence of an element in the collection and there is `contains()` method in the Collection interface.

**Comment by jerrinot** [comment] 2017-01-24 08:31
hi, I am closing it now as everything is working as designed. feel free to re-open it if you still believe it's a Hazelcast issue.

**Closed by jerrinot** 2017-01-24 08:31 UTC
Labels: Team: Core

**Comment by rathishkumar89** [comment] 2017-01-24 11:44
hi Jerrinot,
 I have made the change as per your suggestion it is working but i feel there is a gap from 3.6.5 to 3.7.4 because its is not supporting the backward compatibility. I have 100's DAO calls which uses IMAP.values if this is the fix then i need to change in all the 100's am not sure  whether this will impact the other DAO calls too.

Do I need to make any configuration changes to make the hazelcast to work with backward compatibility?

**Comment by jerrinot** [comment] 2017-01-24 11:57
hi @rathishkumar89,

I am very glad you solved the issue!

We pay big attention to backward compatibility and we invest a lot of our brain energy into it. Hazelcast aims to provide drop-in upgrades between minor versions whenever it's possible. 

However there is a caveat: As a user you have to adhere to a contract of our API. Contract of `IMap.values()` is this: _Give me a predicate and I'll return you a **collection** of values._ It's expressed in Java as `Collection<V> values(Predicate predicate);` 

By casting to `ArrayList` your code makes an assumption that the returned collection is always implemented by `ArrayList`. However this was never part of the API contract. The `ArrayList` was just an implementation detail in some version. 

It's similar to e.g. `java.util.Collections.unmodifiableList()` from the Java Collection API - the contract is that it returns a `List` which is unmodifieable. However you are not supposed to make assumptions about the actual implementation of this list. In some cases it'll use `UnmodifiableRandomAccessList`, in other cases `UnmodifiableList` and it's also free to use a completely different implementation when it see a fit.

**Comment by rathishkumar89** [comment] 2017-01-25 05:08
Hey @jerrinot,

Thanks for your input

The main reason why we're upgrading our HazelCast from 3.6.5 to 3.7.4 is we are occasionally getting TargetDisconnectedException / MemberLeftException. We have read in the release notes of 3.7 release that this exception has been fixed. Would it solve this issue if we upgrade the HazelCast jar?
