### ISSUE TITLE
Custom implementation of nodeextension error 

### ISSUE THREAD

**Issue by henry356-vg** [hazelcast/hazelcast#18992] opened 2021-06-28 23:50 UTC
**Describe the bug**
Hazelcast version 4.2

Custom implementation of NodeExtension failing with below error when creating new instance. This could be due to extension priority list skipping to choose extension in NodeExtensionFactory.

```java
 public static final List<String> EXTENSION_PRIORITY_LIST = unmodifiableList(asList(
            "com.hazelcast.instance.impl.EnterpriseNodeExtension",
            "com.hazelcast.instance.impl.DefaultNodeExtension"
    ));

int currPriority = extensionPriorityList.indexOf(currExt.getName());
                if (currPriority == -1) {
                    continue;
                }
 ```

```
Exception in thread "main" com.hazelcast.core.HazelcastException: ServiceLoader didn't find any services registered under com.hazelcast.instance.impl.NodeExtension

        at com.hazelcast.instance.impl.NodeExtensionFactory.create(NodeExtensionFactory.java:84)

        at com.hazelcast.instance.impl.DefaultNodeContext.createNodeExtension(DefaultNodeContext.java:61)

        at com.hazelcast.instance.impl.Node.<init>(Node.java:233)

        at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)

        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)

        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)

        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)

        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)

        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)

        at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47)
```
 

**Expected behavior**

Custom implementation of NodeExtension service provider should be allowed.

**To Reproduce**

Update META-INF/services/com.hazelcast.instance.impl.NodeExtension with custom implementation and start instance.

**Comment by mmedenjak** [comment] 2021-06-29 06:20
Hi @henry356-vg ! Unfortunately, since 4.0 we don't support custom node extensions or custom services anymore:
- https://github.com/hazelcast/hazelcast/pull/15151
- https://docs.hazelcast.com/imdg/4.2/migration-guides.html#removal-of-user-defined-services

The reason being that it wasn't used often, the SPI was not nicely implemented and compatibility was broken a couple of times. Now, every class in an `impl` or `internal` package is private API, which includes the `NodeExtension`.

The relatively good news is that the code is pretty stable, so if you can find a way how to inject your custom node extension (by downcasting, calling private methods, etc.), I'm reasonably sure it will work across several minor and maybe even major versions.

**Comment by mmedenjak** [comment] 2021-06-29 06:22
Closing as this is intended behaviour. Please comment, reopen this issue or open a new one in case you have further issues.

**Closed by mmedenjak** 2021-06-29 06:22 UTC
Labels: Source: Community, Team: Core
