### ISSUE TITLE
Packaging clash on 5.1-SNAPSHOT giving "No DataSerializerFactory registered for namespace: -38"

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19926] opened 2021-11-10 10:22 UTC
Using 5.1-SNAPSHOT:
```
com/hazelcast/hazelcast-sql/5.1-SNAPSHOT/hazelcast-sql-5.1-20211110.064953-128.jar
com/hazelcast/hazelcast/5.1-SNAPSHOT/hazelcast-5.1-20211110.064453-128.jar
```

My pom has
```
	<dependencies>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-sql</artifactId>
			<version>${hazelcast.version}</version>
		</dependency>
	</dependencies>
```
and
```
                        <plugin>
                                <artifactId>maven-assembly-plugin</artifactId>
                                <configuration>
                                        <descriptorRefs>
                                                <descriptorRef>jar-with-dependencies</descriptorRef>
                                        </descriptorRefs>
                                </configuration>
                                <executions>
                                        <execution>
                                                <phase>package</phase>
                                                <goals>
                                                        <goal>single</goal>
                                                </goals>
                                        </execution>
                                </executions>
                        </plugin>		
```

When I run code such as
```
	public static void main(String[] args) throws Exception {
		Config config = new Config();
		config.getJetConfig().setEnabled(true);

		HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);

		try {
			String mapping = "CREATE OR REPLACE MAPPING \"neil\""
					+ " (" + "    __key VARCHAR," + "    this VARCHAR" + ") " + "TYPE IMap " + " OPTIONS ( "
					+ " 'keyFormat' = 'java'," + " 'keyJavaClass' = '" + String.class.getCanonicalName() + "',"
					+ " 'valueFormat' = 'java'," + " 'valueJavaClass' = '" + String.class.getCanonicalName() + "'"
					+ " )";

			hazelcastInstance.getSql().execute(mapping);
		} catch (Exception e) {
			e.printStackTrace();
		}

		hazelcastInstance.shutdown();
		System.exit(0);
	}
```

using
```
mvn clean install && java -cp target/zzz2-0.0.1-SNAPSHOT-jar-with-dependencies.jar neil.Application 
```

this throws an exception
```
com.hazelcast.sql.HazelcastSqlException: No DataSerializerFactory registered for namespace: -38
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:74)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:211)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:162)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:158)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:154)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at neil.Application.main(Application.java:22)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -38
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:139)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:270)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:386)
	at com.hazelcast.replicatedmap.impl.record.ObjectReplicatedRecordStorage.marshall(ObjectReplicatedRecordStorage.java:41)
	at com.hazelcast.replicatedmap.impl.record.AbstractReplicatedRecordStore.put(AbstractReplicatedRecordStore.java:174)
	at com.hazelcast.replicatedmap.impl.record.AbstractReplicatedRecordStore.put(AbstractReplicatedRecordStore.java:149)
	at com.hazelcast.replicatedmap.impl.operation.PutOperation.run(PutOperation.java:63)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapRuntimeException(AbstractInvocationFuture.java:1968)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1949)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1431)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:600)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:584)
	at com.hazelcast.replicatedmap.impl.ReplicatedMapProxy.put(ReplicatedMapProxy.java:273)
	at com.hazelcast.jet.sql.impl.schema.MappingStorage.put(MappingStorage.java:59)
	at com.hazelcast.jet.sql.impl.schema.MappingCatalog.createMapping(MappingCatalog.java:99)
	at com.hazelcast.jet.sql.impl.PlanExecutor.execute(PlanExecutor.java:108)
	at com.hazelcast.jet.sql.impl.SqlPlanImpl$CreateMappingPlan.execute(SqlPlanImpl.java:140)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:248)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:198)
	... 5 more
```

Works fine with 5.0.1-SNAPSHOT

It works fine in the IDE, it's clash with the use of `maven-assembly-plugin`

**Comment by neilstevenson** [comment] 2021-11-10 10:24
See also https://github.com/hazelcast/hazelcast/issues/18959 ?

**Comment by viliam-durina** [comment] 2021-11-12 08:55
It might be fixed by this: #19931

**Comment by frant-hartm** [comment] 2021-11-15 11:32
I would say this is expected behaviour. We use the service loader mechanism in multiple places, not only for SQL in hazelcast. Instead of assembly plugin you should be using shade plugin with https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer.

We might need to add an entry to documentation that we are not assembly plugin friendly.

**Comment by ivanthescientist** [comment] 2021-11-15 11:54
For the record, this problem can be fixed with assembly plugin's built in capabilities: 
```
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.isc.Application</mainClass>
                        </manifest>
                    </archive>
                    <descriptors>
                        <descriptor>src/main/resources/assembly.xml</descriptor>
                    </descriptors>
```
assembly.xml: 
```
<assembly xmlns="http://maven.apache.org/ASSEMBLY/2.1.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/ASSEMBLY/2.1.0 http://maven.apache.org/xsd/assembly-2.1.0.xsd">
    <id>jar-with-dependencies</id>
    <formats>
        <format>jar</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <dependencySets>
        <dependencySet>
            <outputDirectory>/</outputDirectory>
            <useProjectArtifact>true</useProjectArtifact>
            <unpack>true</unpack>
            <scope>runtime</scope>
        </dependencySet>
    </dependencySets>
    <containerDescriptorHandlers>
        <! -- not enabled by default -->
        <containerDescriptorHandler>
            <handlerName>metaInf-services</handlerName>
        </containerDescriptorHandler>
    </containerDescriptorHandlers>
</assembly>
```

**Comment by neilstevenson** [comment] 2021-11-15 13:21
This has changed from 5.0 to 5.1 though.

**Comment by ivanthescientist** [comment] 2022-01-27 10:35
We resolve this since Integrity Checker has been merged.

**Closed** 2022-01-27 10:36 UTC
Labels: Type: Defect, Priority: High, Source: Internal, Team: SQL
